In [3]:
import pandas as pd

df = pd.read_stata("./data/PSIDSHELF_1968_2021_WIDE.dta")
df

,ID,LINEAGE,PNUM,FUID_1968,FUID_1969,FUID_1970,FUID_1971,FUID_1972,FUID_1973,FUID_1974,...,REL_MAR7_MYEAR,REL_MAR7_SYEAR,REL_MAR7_DYEAR,REL_MAR8_ID,REL_MAR8_MYEAR,REL_MAR8_SYEAR,REL_MAR8_DYEAR,PSID_RETRIEVE,PSIDSHELF_COMPILE,PSIDSHELF_RELEASE
0,1001,1,1,1.0,1597.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
1,1002,1,2,1.0,1597.0,1331.0,108.0,45.0,81.0,378.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
2,1003,1,3,1.0,1964.0,837.0,109.0,494.0,17.0,377.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
3,1004,1,4,1.0,1964.0,837.0,109.0,494.0,17.0,377.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
4,1030,1,30,NaN,NaN,NaN,NaN,NaN,17.0,377.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84116,9308001,9308,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
84117,9308002,9308,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
84118,9308003,9308,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
84119,9308004,9308,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01
84120,9308170,9308,170,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023/11/16,2025/02/23,2025-01

In [6]:
df.describe()

,ID,LINEAGE,PNUM,FUID_1968,FUID_1969,FUID_1970,FUID_1971,FUID_1972,FUID_1973,FUID_1974,...,REL_MAR6_SYEAR,REL_MAR6_DYEAR,REL_MAR7_ID,REL_MAR7_MYEAR,REL_MAR7_SYEAR,REL_MAR7_DYEAR,REL_MAR8_ID,REL_MAR8_MYEAR,REL_MAR8_SYEAR,REL_MAR8_DYEAR
count,8.412100e+04,84121.000000,84121.000000,18192.000000,16862.000000,16978.000000,17252.000000,17628.000000,17777.000000,17988.000000,...,2.000000,4.000000,4.000000e+00,4.000000,1.0,2.000000,1.0,1.0,1.0,1.0
mean,4.176948e+06,4176.866217,81.625991,3631.890391,2206.229392,2343.495465,2468.307790,2562.465396,2642.762165,2800.353569,...,1997.500000,1991.250000,3.736132e+06,1988.000000,1987.0,1991.500000,5434171.0,1987.0,1989.0,1992.0
std,2.584166e+06,2584.176585,81.487894,2335.699954,1306.610924,1321.586809,1378.360058,1459.939907,1517.434490,1567.555091,...,20.506097,14.244882,2.219783e+06,5.163978,NaN,6.363961,NaN,NaN,NaN,NaN
min,1.001000e+03,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1983.000000,1981.000000,1.563172e+06,1982.000000,1987.0,1987.000000,5434171.0,1987.0,1989.0,1992.0
25%,1.800003e+06,1800.000000,4.000000,1438.000000,1042.250000,1188.000000,1294.000000,1302.000000,1301.000000,1467.000000,...,1990.250000,1982.500000,1.961422e+06,1985.000000,1987.0,1989.250000,5434171.0,1987.0,1989.0,1992.0
50%,5.018042e+06,5018.000000,36.000000,2824.000000,2218.000000,2359.000000,2500.000000,2580.000000,2647.000000,2837.500000,...,1997.500000,1986.000000,3.764172e+06,1988.000000,1987.0,1991.500000,5434171.0,1987.0,1989.0,1992.0
75%,6.215172e+06,6215.000000,173.000000,5895.000000,3343.750000,3471.750000,3661.000000,3851.000000,3958.000000,4130.000000,...,2004.750000,1994.750000,5.538881e+06,1991.000000,1987.0,1993.750000,5434171.0,1987.0,1989.0,1992.0
max,9.308170e+06,9308.000000,294.000000,6872.000000,4460.000000,4645.000000,4840.000000,5060.000000,5285.000000,5517.000000,...,2012.000000,2012.000000,5.853012e+06,1994.000000,1987.0,1996.000000,5434171.0,1987.0,1989.0,1992.0

In [8]:
df.columns

Index(['ID', 'LINEAGE', 'PNUM', 'FUID_1968', 'FUID_1969', 'FUID_1970',
       'FUID_1971', 'FUID_1972', 'FUID_1973', 'FUID_1974',
       ...
       'REL_MAR7_MYEAR', 'REL_MAR7_SYEAR', 'REL_MAR7_DYEAR', 'REL_MAR8_ID',
       'REL_MAR8_MYEAR', 'REL_MAR8_SYEAR', 'REL_MAR8_DYEAR', 'PSID_RETRIEVE',
       'PSIDSHELF_COMPILE', 'PSIDSHELF_RELEASE'],
      dtype='object', length=7525)

In [1]:
import pandas as pd

df2 = pd.read_stata("./data/PSID_COMPLETE_MAIN_STUDY_1968_2021_ABRIDGED.dta")
df2

,ID,ER30001,ER30002,ER30003,ER30004,ER30010,ER30018,ER30019,ER30020,ER30021,...,PID35,PID36,PID37,PID38,PID39,PID40,PSID_RETRIEVE,PSIDCMS_COMPILE,PSIDCMS_DATA_TYPE,PSIDCMS_RELEASE
0,1001.0,1,1,1,52,8,0,23.0,1597,1,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
1,1002.0,1,2,2,46,8,0,23.0,1597,2,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
2,1003.0,1,3,7,21,12,0,23.0,1964,1,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
3,1004.0,1,4,3,19,12,0,23.0,1964,2,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
4,1030.0,1,30,0,0,0,97,0.0,1964,0,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84116,9308001.0,9308,1,0,0,0,97,0.0,0,0,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
84117,9308002.0,9308,2,0,0,0,97,0.0,0,0,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
84118,9308003.0,9308,3,0,0,0,97,0.0,0,0,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
84119,9308004.0,9308,4,0,0,0,97,0.0,0,0,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01
84120,9308170.0,9308,170,0,0,0,97,0.0,0,0,...,0,0,0,0,0,0,2023/11/16,2025/02/05,"PSID-CMS, Abridged Version",2025.01

In [2]:
df2.columns

Index(['ID', 'ER30001', 'ER30002', 'ER30003', 'ER30004', 'ER30010', 'ER30018',
       'ER30019', 'ER30020', 'ER30021',
       ...
       'PID35', 'PID36', 'PID37', 'PID38', 'PID39', 'PID40', 'PSID_RETRIEVE',
       'PSIDCMS_COMPILE', 'PSIDCMS_DATA_TYPE', 'PSIDCMS_RELEASE'],
      dtype='object', length=9182)

In [8]:
import pandas as pd

# 컬럼 표시 제한 해제
pd.set_option('display.max_columns', None)   # None = 무제한
pd.set_option('display.expand_frame_repr', False)  # 줄바꿈 없이 가로로 길게

# 이제 df 또는 df.columns 를 출력하면 7,525개 컬럼 전부가 보입니다
df2.head()          # 데이터 미리보기

       ID  ER30001  ER30002  ER30003  ER30004  ER30010  ER30018  ER30019  ER30020  ER30021  ER30022  ER30023  ER30031  ER30041  ER30042  ER30043  ER30044  ER30045  ER30046  ER30052  ER30055  ER30065  ER30066  ER30067  ER30068  ER30069  ER30070  ER30076  ER30079  ER30089  ER30090  ER30091  ER30092  ER30093  ER30094  ER30100  ER30104  ER30115  ER30116  ER30117  ER30118  ER30119  ER30120  ER30126  ER30128  ER30136  ER30137  ER30138  ER30139  ER30140  ER30141  ER30147  ER30149  ER30158  ER30159  ER30160  ER30161  ER30162  ER30163  ER30169  ER30170  ER30186  ER30187  ER30188  ER30189  ER30190  ER30191  ER30197  ER30200  ER30215  ER30216  ER30217  ER30218  ER30219  ER30220  ER30226  ER30229  ER30244  ER30245  ER30246  ER30247  ER30248  ER30249  ER30255  ER30266  ER30281  ER30282  ER30283  ER30284  ER30285  ER30286  ER30292  ER30293  ER30296  ER30311  ER30312  ER30313  ER30314  ER30315  ER30316  ER30322  ER30323  ER30326  ER30341  ER30342  ER30343  ER30344  ER30345  ER30346  ER30352  ER30353  ER30356  ER30371  ER30372  ER30373  ER30374  ER30375  ER30376  ER30381  ER30382  ER30384  ER30397  ER30398  ER30399  ER30400  ER30401  ER30402  ER30403  ER30404  ER30410  ER30411  ER30413  ER30425  ER30427  ER30428  ER30429  ER30430  ER30431  ER30432  ER30433  ER30434  ER30440  ER30441  ER30443  ER30459  ER30461  ER30462  ER30463  ER30464  ER30465  ER30466  ER30467  ER30468  ER30474  ER30478  ER30494  ER30496  ER30497  ER30498  ER30499  ER30500  ER30501  ER30502  ER30503  ER30509  ER30513  ER30526  ER30527  ER30531  ER30533  ER30534  ER30535  ER30536  ER30537  ER30538  ER30539  ER30540  ER30545  ER30549  ER30562  ER30566  ER30568  ER30569  ER30570  ER30571  ER30572  ER30573  ER30574  ER30575  ER30580  ER30584  ER30597  ER30598  ER30602  ER30604  ER30605  ER30606  ER30607  ER30608  ER30609  ER30610  ER30611  ER30616  ER30620  ER30633  ER30634  ER30638  ER30640  ER30641  ER30642  ER30643  ER30644  ER30645  ER30646  ER30647  ER30653  ER30657  ER30670  ER30671  ER30680  ER30685  ER30686  ER30688  ER30689  ER30690  ER30691  ER30692  ER30693  ER30694  ER30699  ER30703  ER30718  ER30719  ER30723  ER30729  ER30730  ER30732  ER30733  ER30734  ER30735  ER30736  ER30737  ER30738  ER30744  ER30748  ER30763  ER30764  ER30770  ER30771  ER30772  ER30773  ER30774  ER30775  ER30776  ER30777  ER30778  ER30779  ER30780  ER30781  ER30782  ER30783  ER30784  ER30785  ER30786  ER30787  ER30788  ER30789  ER30790  ER30798  ER30802  ER30803  ER30805  ER30806  ER30807  ER30808  ER30809  ER30810  ER30811  ER30816  ER30820  ER30826  ER30827  ER30828  ER30829  ER30830  ER30831  ER30832  ER30833  ER30834  ER30835  ER30836  ER30837  ER30838  ER30839  ER30840  ER30841  ER30842  ER30843  ER30844  ER30845  ER30846  ER30847  ER30848  ER30863  ER30864  ER30866  ER31996  ER31997  ER32000  ER32003  ER32006  ER32014  ER32050  ER32052  ER33101  ER33102  ER33103  ER33104  ER33105  ER33106  ER33111  ER33115  ER33116  ER33117  ER33119  ER33121  ER33127  ER33129  ER33130  ER33131  ER33132  ER33133  ER33134  ER33135  ER33136  ER33137  ER33138  ER33139  ER33140  ER33141  ER33142  ER33143  ER33144  ER33145  ER33146  ER33147  ER33148  ER33149  ER33201  ER33202  ER33203  ER33204  ER33205  ER33206  ER33211  ER33215  ER33216  ER33217  ER33275  ER33277  ER33283  ER33285  ER33286  ER33287  ER33288  ER33289  ER33290  ER33291  ER33292  ER33293  ER33294  ER33294A  ER33295  ER33295A  ER33296  ER33296A  ER33297  ER33297A  ER33298  ER33298A  ER33299  ER33299A  ER33301  ER33302  ER33303  ER33304  ER33305  ER33306  ER33311  ER33315  ER33316  ER33317  ER33318  ER33325  ER33327  ER33328  ER33329  ER33330  ER33331  ER33332  ER33333  ER33334  ER33335  ER33336  ER33337  ER33338  ER33339  ER33340  ER33341  ER33342  ER33343  ER33344  ER33345  ER33346  ER33347  ER33401  ER33402  ER33403  ER33404  ER33405  ER33406  ER33411  ER33415  ER33416  ER33417  ER33418  ER33430  ER33437  ER33438  ER33501  ER33502  ER33503  ER33504  ER33505  ER33506  ER33511  ER33512  ER33516  ER33517  ER33518  ER33519  ER33520  ER33521  ER33522  ER33523  ER33545  ER33546  ER33547  ER33601  ER33602  ER33603  ER33604  ER33605  ER33606  ER33611  ER33612  ER33616  ER33617  ER33618  ER33619  ER33620  ER33621  ER33622  ER33623  ER33636  ER33637  ER33639  ER33701  ER33702  ER33703  ER33704  ER33705  ER33706  ER33711  ER33712  ER33716  ER33717  ER33718  ER33719  ER33720  ER33721  ER33722  ER33723  ER33739  ER33740  ER33742  ER33801  ER33802  ER33803  ER33804  ER33805  ER33806  ER33811  ER33813  ER33817  ER33818  ER33819  ER33820  ER33821  ER33822  ER33824  ER33825  ER33847  ER33848  ER33849  ER33901  ER33902  ER33903  ER33904  ER33905  ER33906  ER33911  ER33913  ER33917  ER33918  ER33919  ER33920  ER33921  ER33922  ER33924  ER33925  ER33949  ER33950  ER33951  ER34001  ER34002  ER34003  ER34004  ER34005  ER34006  ER34011  ER34012  ER34013  ER34014  ER34016  ER34020  ER34021  ER34022  ER34023  ER34024  ER34025  ER34027  ER34028  ER34044  ER34045  ER34046  ER34101  ER34102  ER34103  ER34104  ER34105  ER34106  ER34111  ER34112  ER34113  ER34114  ER34116  ER34119  ER34120  ER34121  ER34122  ER34123  ER34124  ER34126  ER34127  ER34128  ER34129  ER34130  ER34153  ER34154  ER34155  ER34201  ER34202  ER34203  ER34204  ER34205  ER34206  ER34211  ER34212  ER34213  ER34214  ER34216  ER34230  ER34231  ER34234  ER34235  ER34236  ER34237  ER34238  ER34267  ER34268  ER34269  ER34301  ER34302  ER34303  ER34305  ER34306  ER34307  ER34312  ER34313  ER34314  ER34315  ER34317  ER34349  ER34381  ER34383  ER34384  ER34385  ER34386  ER34387  ER34388  ER34412  ER34413  ER34414  ER34501  ER34502  ER34503  ER34504  ER34505  ER34506  ER34511  ER34512  ER34513  ER34514  ER34516  ER34548  ER34580  ER34581  ER34582  ER34583  ER34584  ER34585  ER34586  ER34587  ER34588  ER34589  ER34590  ER34592  ER34593  ER34594  ER34595  ER34596  ER34597  ER34649  ER34650  ER34651  ER34701  ER34702  ER34703  ER34704  ER34705  ER34706  ER34711  ER34712  ER34713  ER34714  ER34716  ER34752  ER34788  ER34789  ER34790  ER34791  ER34792  ER34793  ER34794  ER34795  ER34796  ER34797  ER34798  ER34800  ER34801  ER34802  ER34803  ER34804  ER34805  ER34862  ER34863  ER34864  ER34901  ER34902  ER34903  ER34904  ER34905  ER34906  ER34911  ER34912  ER34913  ER34914  ER34916  ER34952  ER34988  ER34989  ER34990  ER34991  ER34992  ER34993  ER34994  ER34995  ER34996  ER34997  ER34998  ER34999  ER35000  ER35002  ER35003  ER35004  ER35005  ER35006  ER35007  ER35063  ER35064  ER35065       V5   V7  V10  V13     V74     V75      V81  V82   V93  V99  V103  V104  V105  V113  V115  V117  V118  V120  V158  V180  V181  V182  V196  V197_A  V239  V243_A  V246  V251  V266  V311  V313  V361  V362  V398  V439     V449  V450     V451  V452  V455  V458    V514    V516    V529  V530  V537  V549  V550  V553  V593  V594  V595  V596  V607  V609_A  V639  V640_A  V699  V718  V719  V732  V733  V740  V787  V794  V800  V801  V802  V876  V877  V1008  V1011  V1013  V1014   V1015  V1016  V1103  V1108    V1122  V1123    V1124  V1125  V1128  V1131  V1189  V1190   V1191   V1196   V1198  V1228  V1236  V1238  V1239  V1241  V1242  V1243  V1264  V1265  V1266  V1267  V1278  V1279_A  V1365  V1367_A  V1384  V1385  V1399  V1400  V1406  V1477  V1485  V1489  V1490  V1491   V1514  V1572  V1573  V1609   V1766  V1767  V1803  V1808    V1823  V1824    V1825  V1826  V1829  V1832  V1890  V1891   V1892   V1897   V1899  V1908  V1939  V1941  V1942  V1944  V1945  V1946  V1967  V1968  V1971  V1972  V1983  V1984_A  V2072  V2074_A  V2096  V2097  V2111  V2112  V2118  V2189  V2197  V2201  V2202  V2203    V2226  V2284  V2285  V2321  V2345  V2346  V2403  V2409    V2423  V2424    V2425  V2426  V2429  V2432  V2491  V2492   V2493   V2498   V2500  V2509  V2539  V2541  V2542  V2544  V2545  V2546  V2566  V2567  V2570  V2571  V2581  V2582_A  V2670  V2672_A  V2687  V2702  V2703  V2708  V2709  V2715  V2815  V2823  V2827  V2828  V2829    V2852  V2911  V2912  V2968  V2979  V2980  V3003  V3009    V3021  V3022  V3023  V3026  V3044  V3045   V3046   V3051   V3053  V3062  V3092  V3094  V3095  V3097  V3098  V3099  V3108  V3109  V3114  V3115_A  V3181  V3183_A  V3209  V3210  V3211  V3212  V3216  V3233  V3241  V3248  V3249    V3256  V3279  V3280  V3300  V3301  V3310  V3311  V3403  V3409    V3417  V3418  V3419  V3422  V3456  V3457   V3458   V3463    V3465  V3474  V3505  V3507  V3508  V3510  V3511  V3512  V3522  V3523  V3528  V3530_A  V3598  V3601_A  V3628  V3629  V3630  V3631  V3638  V3655  V3663  V3670  V3671    V3676  V3699  V3700  V3720  V3721  V3730  V3731  V3803  V3809    V3817  V3818  V3819  V3822  V3856  V3857   V3858   V3863    V3865  V3874  V3918  V3920  V3921  V3923  V3924  V3925  V3939  V3940  V3967  V3968_A  V4053  V4055_A  V4074  V4075  V4076  V4077  V4093  V4099  V4101  V4102  V4105  V4131  V4149  V4150    V4154  V4178  V4179  V4198  V4199  V4204  V4224   V4231  V4232  V4303  V4309    V4318  V4319   V4320  V4321  V4326  V4331  V4371  V4372    V4373    V4379  V4388  V4433  V4435  V4436  V4438  V4439  V4440  V4450  V4451  V4458  V4459_A  V4603  V4605_A  V4609  V4618  V4619  V4620  V4621  V4674  V4684  V4690  V4695  V4698  V4700  V4701  V4751  V4768  V4841    V5029    V5031  V5054  V5055  V5074  V5075  V5096  V5099  V5100   V5113  V5114  V5203  V5209    V5217  V5218   V5219  V5220  V5225  V5230  V5281  V5282    V5283    V5289  V5299  V5347  V5349  V5350  V5352  V5353  V5354  V5364  V5365  V5373  V5374_A  V5502  V5505  V5507_A  V5534  V5535  V5553  V5554  V5555  V5556  V5567  V5570  V5594  V5608  V5614  V5618  V5619    V5626    V5627  V5633  V5634  V5647  V5648  V5650  V5662  V5665   V5681  V5682  V5703  V5709    V5717  V5718  V5719  V5720  V5723  V5728  V5780  V5781    V5782    V5788  V5798  V5847  V5849  V5850  V5852  V5853  V5854  V5864  V5865  V5872  V5873_A  V6034  V6037  V6039_A  V6072  V6073  V6084  V6095  V6096  V6097  V6098  V6116  V6119  V6143  V6157  V6163  V6165  V6166    V6173    V6174  V6180  V6181  V6194  V6195  V6197  V6209  V6212   V6220  V6221  V6303  V6309   V6319  V6320  V6321  V6322  V6326  V6331  V6389  V6390    V6391    V6398  V6409  V6459  V6461  V6462  V6464  V6465  V6466  V6479  V6480  V6482  V6483  V6492  V6497_A  V6590  V6591  V6596_A  V6659  V6662  V6663  V6664  V6686  V6687  V6688  V6689  V6690  V6691  V6713  V6716  V6740  V6754  V6760  V6764  V6765    V6766    V6767  V6773  V6774  V6787  V6788  V6790  V6802  V6805   V6814  V6815  V6903  V6909  V6917  V6918  V6919  V6920  V6925  V6930  V6979  V6980  V6981  V6988  V6999  V7064  V7066  V7067  V7069  V7070  V7071  V7084  V7085  V7087  V7088  V7095  V7100_A  V7192  V7193  V7198_A  V7261  V7264  V7265  V7266  V7287  V7289  V7290  V7291  V7292  V7293  V7294  V7346  V7349  V7373  V7387  V7393  V7397  V7398  V7412  V7413  V7419  V7420  V7433  V7434  V7435  V7447  V7451  V7456  V7457  V7503  V7509  V7517  V7518  V7519  V7520  V7525  V7528  V7571  V7572  V7573  V7580  V7591  V7655  V7657  V7658  V7660  V7661  V7662  V7675  V7676  V7678  V7680  V7706  V7712  V7878  V7879  V7885  V7952  V7955  V7956  V7957  V7976  V7977  V7984  V7985  V7989  V7990  V7991  V7992  V7993  V7994  V7998  V8001  V8025  V8039  V8045  V8049  V8050  V8065  V8066  V8071  V8072  V8085  V8086  V8087  V8099  V8103  V8110  V8111  V8203  V8209  V8217  V8218  V8221  V8224  V8263  V8264  V8265  V8273  V8284  V8349  V8351  V8352  V8354  V8355  V8356  V8364  V8367  V8374  V8380  V8537  V8538  V8544  V8603  V8610  V8611  V8612  V8613  V8622  V8625  V8649  V8663  V8669  V8673  V8674  V8689  V8690  V8695  V8696  V8709  V8710  V8711  V8723  V8727  V8735  V8737  V8739  V8803  V8809  V8817  V8818  V8819  V8820  V8825  V8828  V8871  V8872  V8873  V8881  V8892  V8958  V8960  V8961  V8963  V8964  V8965  V8974  V8975  V8977  V8979  V9005  V9011  V9187  V9188  V9194  V9276  V9279  V9280  V9281  V9292  V9293  V9297  V9298  V9299  V9300  V9301  V9302  V9303  V9304  V9308  V9311  V9335  V9349  V9355  V9359  V9360  V9375  V9376  V9381  V9382  V9395  V9396  V9408  V9419  V9421  V9428  V9430  V9432  V9433  V10003  V10009  V10018  V10019  V10020  V10021  V10026  V10029  V10254  V10255  V10256  V10263  V10278  V10416  V10418  V10419  V10421  V10422  V10423  V10424  V10426  V10437  V10438  V10440  V10445  V10453  V10460  V10670  V10671  V10678  V10865  V10866  V10867  V10877  V10878  V10881  V10882  V10884  V10885  V10888  V10889  V10890  V10891  V10892  V10893  V10894  V10895  V10955  V10958  V10982  V10996  V11002  V11006  V11007  V11022  V11023  V11028  V11029  V11042  V11043  V11055  V11065  V11067  V11074  V11076  V11078  V11079  V11103  V11110  V11125  V11126  V11127  V11128  V11133  V11136  V11395  V11396  V11397  V11404  V11420  V11600  V11605  V11606  V11608  V11609  V11610  V11611  V11612  V11618  V11619  V11621  V11626  V11637  V11651  V11893  V11894  V11896  V11897  V11898  V11899  V11900  V11915  V11937  V11938  V11939  V11945  V11956  V11959  V11960  V11961  V11982  V11991  V11992  V11995  V11996  V11997  V11998  V11999  V12000  V12014  V12270  V12292  V12293  V12294  V12300  V12311  V12314  V12315  V12316  V12337  V12344  V12345  V12348  V12349  V12354  V12371  V12372  V12379  V12383  V12387  V12400  V12401  V12426  V12428  V12435  V12436  V12438  V12439  V12441  V12442  V12443  V12446  V12503  V12509  V12524  V12525  V12526  V12527  V12532  V12535  V12794  V12795  V12796  V12803  V12819  V13008  V13010  V13011  V13013  V13014  V13015  V13016  V13017  V13023  V13024  V13026  V13033  V13046  V13054  V13224  V13225  V13233  V13392  V13393  V13394  V13404  V13405  V13407  V13408  V13409  V13410  V13411  V13417  V13419  V13435  V13436  V13437  V13438  V13448  V13452  V13454  V13470  V13471  V13472  V13473  V13499  V13500  V13501  V13503  V13510  V13512  V13513  V13514  V13542  V13564  V13565  V13566  V13568  V13579  V13582  V13583  V13584  V13607  V13608  V13623  V13624  V13631  V13635  V13640  V13641  V13665  V13667  V13674  V13675  V13677  V13678  V13680  V13681  V13682  V13687  V13703  V13709  V13724  V13725  V13726  V13727  V13732  V13735  V13896  V13897  V13898  V13905  V13921  V14111  V14113  V14114  V14116  V14117  V14118  V14119  V14120  V14126  V14127  V14129  V14136  V14146  V14154  V14320  V14321  V14329  V14484  V14485  V14486  V14501  V14502  V14504  V14505  V14506  V14507  V14508  V14513  V14514  V14518  V14519  V14520  V14524  V14525  V14529  V14530  V14546  V14547  V14548  V14550  V14557  V14559  V14560  V14561  V14589  V14611  V14612  V14613  V14615  V14626  V14629  V14630  V14631  V14654  V14655  V14670  V14671  V14678  V14682  V14687  V14688  V14712  V14714  V14721  V14722  V14724  V14725  V14727  V14728  V14730  V14731  V14732  V14737  V14803  V14809  V14824  V14825  V14826  V14827  V14911  V14912  V14913  V14920  V14936  V15127  V15129  V15130  V15132  V15133  V15134  V15135  V15136  V15140  V15141  V15142  V15145  V15154  V15162  V15455  V15456  V15464  V15757  V15758  V15759  V15769  V15770  V15779  V15780  V15993  V15997  V15999  V16020  V16021  V16022  V16024  V16031  V16033  V16034  V16035  V16063  V16085  V16086  V16087  V16089  V16100  V16103  V16104  V16105  V16128  V16129  V16144  V16145  V16152  V16156  V16161  V16162  V16187  V16189  V16196  V16197  V16199  V16200  V16202  V16203  V16205  V16206  V16207  V16208  V16303  V16309  V16324  V16325  V16326  V16327  V16411  V16412  V16413  V16420  V16436  V16628  V16630  V16631  V16633  V16634  V16635  V16636  V16637  V16641  V16642  V16643  V16646  V16655  V16663  V16973  V16974  V16982  V17292  V17293  V17294  V17304  V17305  V17308  V17309  V17310  V17311  V17312  V17390  V17394  V17396  V17417  V17418  V17419  V17421  V17428  V17430  V17431  V17432  V17460  V17482  V17483  V17484  V17486  V17497  V17500  V17501  V17502  V17525  V17526  V17533  V17534  V17538  V17542  V17545  V17546  V17565  V17567  V17573  V17574  V17576  V17577  V17579  V17580  V17582  V17583  V17584  V17612  V17703  V17709  V17724  V17725  V17726  V17727  V17733  V17736  V17827  V17828  V17829  V17836  V17852  V18046  V18048  V18049  V18051  V18052  V18053  V18054  V18055  V18072  V18073  V18075  V18082  V18093  V18101  V18394  V18395  V18403  V18696  V18697  V18698  V18708  V18709  V18712  V18713  V18714  V18715  V18716  V18721  V18725  V18727  V18748  V18749  V18750  V18752  V18759  V18761  V18762  V18763  V18791  V18813  V18814  V18815  V18817  V18828  V18831  V18832  V18833  V18856  V18857  V18875  V18878  V18889  V18893  V18898  V18899  V18916  V18918  V18925  V18926  V18928  V18929  V18931  V18932  V18934  V18935  V18936  V18943  V18944  V18945  V19003  V19009  V19024  V19025  V19026  V19027  V19033  V19036  V19127  V19128  V19129  V19136  V19152  V19346  V19348  V19349  V19351  V19352  V19353  V19354  V19355  V19372  V19373  V19375  V19382  V19393  V19401  V19694  V19695  V19703  V19996  V19997  V19998  V20008  V20009  V20012  V20013  V20014  V20015  V20016  V20021  V20025  V20027  V20048  V20049  V20050  V20052  V20059  V20061  V20062  V20063  V20091  V20113  V20114  V20115  V20117  V20128  V20131  V20132  V20133  V20156  V20157  V20175  V20178  V20189  V20193  V20198  V20199  V20216  V20218  V20225  V20226  V20228  V20229  V20231  V20232  V20234  V20235  V20236  V20243  V20244  V20245  V20303  V20309  V20324  V20325  V20326  V20327  V20333  V20336  V20427  V20428  V20429  V20436  V20452  V20648  V20650  V20651  V20653  V20654  V20655  V20656  V20657  V20672  V20673  V20675  V20682  V20693  V20701  V20994  V20995  V21003  V21296  V21297  V21298  V21308  V21309  V21312  V21313  V21314  V21315  V21316  V21321  V21326  V21328  V21354  V21355  V21356  V21358  V21365  V21367  V21368  V21369  V21397  V21419  V21420  V21421  V21423  V21434  V21437  V21438  V21439  V21462  V21463  V21481  V21484  V21495  V21499  V21504  V21505  V21522  V21524  V21531  V21532  V21534  V21535  V21537  V21538  V21540  V21541  V21542  V21547  V21548  V21549  V21603  V21607  V21610  V21611  V21612  V21613  V21622  V21624  V21627  V21733  V21738  V21739  V21803  V21806  V21807  V21960  V22403  V22405  V22406  V22408  V22409  V22410  V22411  V22412  V22427  V22428  V22430  V22448  V22456  V22800  V22801  V22809  V23153  V23154  V23156  V23167  V23168  V23171  V23172  V23173  V23174  V23175  V23180  V23185  V23187  V23211  V23212  V23213  V23215  V23222  V23224  V23225  V23226  V23254  V23275  V23276  V23277  V23279  V23290  V23293  V23294  V23295  V23318  V23319  V23322  V23323  V23324  V23327  V23331  V23333  V23334  V23336  V23338  V23345  V23346  V23348  V23349  V23351  V23352  V23354  V23355  V23356  V23361  V23362  V23363  ER2005  ER2005C  ER2005E  ER2006  ER2007  ER2009  ER2010  ER2011  ER2012  ER2013  ER2014  ER2032  ER2033  ER2036  ER2037  ER2038  ER2045  ER2046  ER2049  ER2050  ER2055  ER2056  ER2069  ER2070  ER2071  ER2561A  ER2563  ER2564  ER2565  ER3054A  ER3055  ER3056  ER3475  ER3702  ER3703  ER3706  ER3707  ER3708  ER3709  ER3710  ER3711  ER3712  ER3713  ER3853  ER3857  ER3858  ER3880  ER3883  ER3884  ER3885  ER3887  ER3894  ER3896  ER3897  ER3898  ER3919A  ER3941  ER3944  ER3945  ER3946  ER3948  ER3959  ER3962  ER3963  ER3964  ER4017  ER4048  ER4119  ER4122  ER4141  ER4144  ER4153  ER4156  ER4157C  ER4157E  ER4158  ER4159  ER4159A  ER4159C  ER4159G  ER4159H  ER4159J  ER4159K  ER4159M  ER4159N  ER4159P  ER4159Q  ER4159R  ER4160  ER4161  ER4162  ER5004  ER5005  ER5005C  ER5005E  ER5006  ER5008  ER5009  ER5010  ER5011  ER5012  ER5013  ER5031  ER5032  ER5035  ER5036  ER5037  ER5044  ER5045  ER5048  ER5049  ER5054  ER5055  ER5068  ER5069  ER5070  ER5560A  ER5562  ER5563  ER5564  ER6053A  ER6054  ER6055  ER6476  ER6704  ER6705  ER6708  ER6709  ER6710  ER6711  ER6712  ER6713  ER6714  ER6715  ER6723  ER6727  ER6728  ER6750  ER6753  ER6754  ER6755  ER6757  ER6764  ER6766  ER6767  ER6768  ER6789A  ER6811  ER6814  ER6815  ER6816  ER6818  ER6829  ER6832  ER6833  ER6834  ER6857  ER6888  ER6959  ER6962  ER6981  ER6984  ER6993  ER6996  ER6997C  ER6997E  ER6998  ER6999  ER6999A  ER6999C  ER6999G  ER6999H  ER6999J  ER6999K  ER6999M  ER6999N  ER6999P  ER6999Q  ER6999R  ER7000  ER7000A  ER7000B  ER7004  ER7005  ER7005C  ER7005E  ER7006  ER7008  ER7009  ER7010  ER7011  ER7012  ER7013  ER7031  ER7032  ER7035  ER7042  ER7043  E

In [5]:
import ydata_profiling as pp

report = pp.ProfileReport(df2, title='EDA')
report.to_file('report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                                                         | 0/9182 [00:00<?, ?it/s]
  0%|                                                                               | 1/9182 [00:00<1:33:49,  1.63it/s]
  0%|                                                                               | 2/9182 [00:00<1:02:19,  2.45it/s]
  0%|▏                                                                               | 15/9182 [00:01<11:45, 13.00it/s]
  0%|▏                                                                               | 17/9182 [00:01<12:09, 12.57it/s]
  0%|▏                                                                               | 19/9182 [00:02<12:28, 12.24it/s]
  0%|▏                                                                               | 21/9182 [00:02<14:26, 10.57it/s]
  0%|▏                                                                               | 22/9182 [00:02<14:38, 10.43it/s]
  0%|▏                                                                               | 23/9182 [00:02<23:24,  6.52it/s]
  0%|▎                                                                               | 30/9182 [00:02<11:45, 12.98it/s]
  0%|▎                                                                               | 32/9182 [00:04<24:20,  6.27it/s]
  0%|▎                                                                               | 34/9182 [00:04<22:46,  6.70it/s]
  0%|▎                                                                               | 39/9182 [00:04<16:20,  9.33it/s]
  0%|▎                                                                               | 41/9182 [00:04<17:45,  8.58it/s]
  0%|▎                                                                               | 43/9182 [00:04<17:50,  8.53it/s]
  0%|▍                                                                               | 45/9182 [00:05<15:48,  9.63it/s]
  1%|▍                                                                               | 47/9182 [00:05<16:49,  9.05it/s]
  1%|▍                                                                               | 49/9182 [00:05<18:33,  8.20it/s]
  1%|▍                                                                               | 50/9182 [00:05<22:00,  6.92it/s]
  1%|▍                                                                               | 51/9182 [00:06<22:38,  6.72it/s]
  1%|▍                                                                               | 55/9182 [00:06<14:21, 10.60it/s]
  1%|▍                                                                               | 57/9182 [00:06<19:24,  7.84it/s]
  1%|▌                                                                               | 58/9182 [00:07<23:07,  6.58it/s]
  1%|▌                                                                               | 59/9182 [00:07<23:48,  6.38it/s]
  1%|▌                                                                               | 60/9182 [00:07<23:46,  6.40it/s]
  1%|▌                                                                               | 61/9182 [00:07<29:57,  5.07it/s]
  1%|▌                                                                               | 62/9182 [00:07<31:14,  4.87it/s]
  1%|▌                                                                               | 63/9182 [00:08<30:30,  4.98it/s]
  1%|▋                                                                               | 76/9182 [00:08<07:54, 19.19it/s]
  1%|▋                                                                               | 78/9182 [00:08<11:32, 13.14it/s]
  1%|▋                                                                               | 80/9182 [00:09<18:55,  8.01it/s]
  1%|▋                                                                               | 82/9182 [00:09<18:46,  8.08it/s]
  1%|▋                                                                               | 83/9182 [00:09<18:53,  8.03it/s]
  1%|▊                                                                               | 87/9182 [00:10<14:12, 10.67it/s]
  1%|▊                                                                               | 89/9182 [00:10<16:06,  9.41it/s]
  1%|▊                                                                               | 91/9182 [00:10<21:05,  7.18it/s]
  1%|▊                                                                               | 92/9182 [00:10<21:14,  7.13it/s]
  1%|▉                                                                              | 103/9182 [00:11<11:02, 13.70it/s]
  1%|▉                                                                              | 105/9182 [00:12<20:54,  7.24it/s]
  1%|▉                                                                              | 106/9182 [00:12<20:39,  7.32it/s]
  1%|▉                                                                              | 107/9182 [00:12<25:24,  5.95it/s]
  1%|▉                                                                              | 115/9182 [00:13<11:38, 12.98it/s]
  1%|█                                                                              | 118/9182 [00:13<13:24, 11.26it/s]
  1%|█                                                                              | 122/9182 [00:13<12:54, 11.70it/s]
  1%|█                                                                              | 124/9182 [00:14<20:57,  7.21it/s]
  1%|█                                                                              | 126/9182 [00:14<19:54,  7.58it/s]
  1%|█                                                                              | 128/9182 [00:14<17:56,  8.41it/s]
  1%|█                                                                              | 130/9182 [00:15<19:24,  7.78it/s]
  1%|█▏                                                                             | 132/9182 [00:15<21:55,  6.88it/s]
  2%|█▏                                                                             | 139/9182 [00:16<10:49, 13.93it/s]
  2%|█▏                                                                             | 142/9182 [00:16<15:10,  9.93it/s]
  2%|█▏                                                                             | 144/9182 [00:16<15:48,  9.52it/s]
  2%|█▎                                                                             | 146/9182 [00:16<14:00, 10.75it/s]
  2%|█▎                                                                             | 148/9182 [00:16<15:57,  9.43it/s]
  2%|█▎                                                                             | 150/9182 [00:17<17:03,  8.82it/s]
  2%|█▎                                                                             | 152/9182 [00:17<14:42, 10.23it/s]
  2%|█▎                                                                             | 154/9182 [00:17<16:27,  9.14it/s]
  2%|█▎                                                                             | 156/9182 [00:17<14:06, 10.66it/s]
  2%|█▎                                                                             | 158/9182 [00:17<14:21, 10.47it/s]
  2%|█▍                                                                             | 160/9182 [00:18<15:46,  9.53it/s]
  2%|█▍                                                                             | 162/9182 [00:18<15:45,  9.54it/s]
  2%|█▍                                                                             | 164/9182 [00:18<14:52, 10.10it/s]
  2%|█▍                                                                             | 166/9182 [00:18<15:59,  9.40it/s]
  2%|█▍                                                                             | 168/9182 [00:19<15:15,  9.84it/s]
  2%|█▍                                                                             | 170/9182 [00:19<17:05,  8.79it/s]
  2%|█▍                                                                             | 171/9182 [00:19<27:23,  5.48it/s]
  2%|█▍                                                                             | 172/9182 [00:20<26:22,  5.69it/s]
  2%|█▍                                                                             | 173/9182 [00:20<29:33,  5.08it/s]
  2%|█▍                                                                             | 174/9182 [00:20<28:58,  5.18it/s]
  2%|█▌                                                                             | 175/9182 [00:20<31:52,  4.71it/s]
  2%|█▌                                                                             | 184/9182 [00:21<16:49,  8.91it/s]
  2%|█▌                                                                             | 185/9182 [00:21<17:37,  8.51it/s]
  2%|█▌                                                                             | 186/9182 [00:21<17:38,  8.50it/s]
  2%|█▌                                                                             | 187/9182 [00:21<18:35,  8.06it/s]
  2%|█▌                                                                             | 188/9182 [00:21<20:50,  7.19it/s]
  2%|█▋                                                                             | 189/9182 [00:22<20:14,  7.41it/s]
  2%|█▋                                                                             | 190/9182 [00:22<21:38,  6.93it/s]
  2%|█▋                                                                             | 197/9182 [00:22<09:56, 15.07it/s]
  2%|█▋                                                                             | 199/9182 [00:23<17:55,  8.35it/s]
  2%|█▊                                                                             | 204/9182 [00:23<13:11, 11.35it/s]
  2%|█▊                                                                             | 206/9182 [00:23<15:36,  9.59it/s]
  2%|█▊                                                                             | 208/9182 [00:23<17:18,  8.64it/s]
  2%|█▊                                                                             | 209/9182 [00:24<20:51,  7.17it/s]
  2%|█▊                                                                             | 210/9182 [00:24<29:08,  5.13it/s]
  2%|█▊                                                                             | 217/9182 [00:25<14:08, 10.56it/s]
  2%|█▉                                                                             | 219/9182 [00:25<18:11,  8.21it/s]
  2%|█▉                                                                             | 221/9182 [00:25<16:09,  9.24it/s]
  2%|█▉                                                                             | 223/9182 [00:26<16:17,  9.16it/s]
  2%|█▉                                                                             | 225/9182 [00:26<23:46,  6.28it/s]
  2%|█▉                                                                             | 226/9182 [00:26<22:27,  6.65it/s]
  2%|█▉                                                                             | 227/9182 [00:26<24:09,  6.18it/s]
  2%|█▉                                                                             | 228/9182 [00:26<28:43,  5.19it/s]
  2%|█▉                                                                             | 229/9182 [00:27<29:19,  5.09it/s]
  3%|██                                                                             | 236/9182 [00:27<10:58, 13.58it/s]
  3%|██                                                                             | 238/9182 [00:28<26:17,  5.67it/s]
  3%|██                                                                             | 240/9182 [00:28<26:00,  5.73it/s]
  3%|██                                                                             | 242/9182 [00:29<25:47,  5.78it/s]
  3%|██▏                                                                            | 247/9182 [00:30<30:19,  4.91it/s]
  3%|██▏                                                                            | 248/9182 [00:30<31:53,  4.67it/s]
  3%|██▏                                                                            | 250/9182 [00:31<37:10,  4.01it/s]
  3%|██▏                                                                            | 251/9182 [00:31<37:13,  4.00it/s]
  3%|██▏                                                                            | 252/9182 [00:31<33:58,  4.38it/s]
  3%|██▏                                                                            | 255/9182 [00:32<46:08,  3.22it/s]
  3%|██▏                                                                            | 261/9182 [00:33<23:28,  6.33it/s]
  3%|██▎                                                                            | 263/9182 [00:33<23:50,  6.24it/s]
  3%|██▎                                                                            | 265/9182 [00:33<20:21,  7.30it/s]
  3%|██▎                                                                            | 267/9182 [00:33<18:01,  8.24it/s]
  3%|██▎                                                                            | 269/9182 [00:33<17:38,  8.42it/s]
  3%|██▎                                                                            | 271/9182 [00:34<15:20,  9.68it/s]
  3%|██▎                                                                            | 273/9182 [00:34<19:00,  7.81it/s]
  3%|██▎                                                                            | 275/9182 [00:35<26:14,  5.66it/s]
  3%|██▎                                                                            | 276/9182 [00:35<24:52,  5.97it/s]
  3%|██▍                                                                            | 277/9182 [00:35<36:10,  4.10it/s]
  3%|██▍                                                                            | 278/9182 [00:36<37:51,  3.92it/s]
  3%|██▍                                                                            | 279/9182 [00:36<40:09,  3.70it/s]
  3%|██▍                                                                            | 286/9182 [00:36<20:30,  7.23it/s]
  3%|██▍                                                                            | 287/9182 [00:38<45:41,  3.24it/s]
  3%|██▍                                                                          | 288/9182 [00:39<1:02:45,  2.36it/s]
  3%|██▍                                                                            | 289/9182 [00:39<54:16,  2.73it/s]
  3%|██▍                                                                            | 290/9182 [00:39<48:56,  3.03it/s]
  3%|██▋                                                                            | 306/9182 [00:40<11:51, 12.48it/s]
  3%|██▋                                                                            | 308/9182 [00:40<11:49, 12.51it/s]
  3%|██▋                                                                            | 314/9182 [00:40<09:47, 15.09it/s]
  3%|██▋                                                                            | 316/9182 [00:41<17:15,  8.56it/s]
  3%|██▋                                                                            | 318/9182 [00:41<21:21,  6.92it/s]
  4%|██▊                                                                            | 324/9182 [00:42<13:31, 10.92it/s]
  4%|██▊                                                                            | 327/9182 [00:43<27:06,  5.44it/s]
  4%|██▊                                                                            | 329/9182 [00:43<24:55,  5.92it/s]
  4%|██▊                                                                            | 331/9182 [00:44<21:55,  6.73it/s]
  4%|██▊                                                                            | 333/9182 [00:44<21:28,  6.87it/s]
  4%|██▉                                                                            | 335/9182 [00:45<34:17,  4.30it/s]
  4%|██▉                                                                            | 336/9182 [00:45<33:58,  4.34it/s]

  4%|██▉                                                                            | 340/9182 [00:45<22:44,  6.48it/s]
  4%|██▉                                                                            | 342/9182 [00:46<25:58,  5.67it/s]
  4%|██▉                                                                            | 346/9182 [00:46<25:10,  5.85it/s]
  4%|██▉                                                                            | 347/9182 [00:47<27:13,  5.41it/s]
  4%|██▉                                                                            | 348/9182 [00:47<26:24,  5.57it/s]
  4%|███                                                                            | 349/9182 [00:47<26:32,  5.55it/s]
  4%|███                                                                            | 350/9182 [00:48<41:13,  3.57it/s]
  4%|███                                                                            | 351/9182 [00:48<47:23,  3.11it/s]
  4%|███                                                                            | 352/9182 [00:48<44:50,  3.28it/s]
  4%|███                                                                            | 362/9182 [00:50<24:07,  6.09it/s]
  4%|███                                                                            | 363/9182 [00:50<23:16,  6.32it/s]
  4%|███▏                                                                           | 365/9182 [00:51<43:03,  3.41it/s]
  4%|███▏                                                                           | 366/9182 [00:51<41:16,  3.56it/s]
  4%|███▏                                                                           | 368/9182 [00:52<33:36,  4.37it/s]
  4%|███▏                                                                           | 369/9182 [00:52<35:29,  4.14it/s]
  4%|███▏                                                                           | 375/9182 [00:53<24:56,  5.88it/s]
  4%|███▏                                                                           | 376/9182 [00:53<27:41,  5.30it/s]
  4%|███▏                                                                           | 377/9182 [00:53<28:16,  5.19it/s]
  4%|███▎                                                                           | 378/9182 [00:53<29:06,  5.04it/s]
  4%|███▎                                                                           | 379/9182 [00:54<31:32,  4.65it/s]
  4%|███▎                                                                           | 380/9182 [00:54<41:23,  3.54it/s]
  4%|███▍                                                                           | 393/9182 [00:56<19:57,  7.34it/s]
  4%|███▍                                                                           | 394/9182 [00:56<21:02,  6.96it/s]
  4%|███▍                                                                           | 395/9182 [00:56<20:53,  7.01it/s]
  4%|███▍                                                                           | 399/9182 [00:57<20:41,  7.08it/s]
  4%|███▍                                                                           | 400/9182 [00:57<24:09,  6.06it/s]
  4%|███▍                                                                           | 402/9182 [00:58<35:09,  4.16it/s]
  4%|███▍                                                                           | 403/9182 [00:58<34:15,  4.27it/s]
  4%|███▍                                                                           | 404/9182 [00:58<31:22,  4.66it/s]
  4%|███▌                                                                           | 409/9182 [00:58<17:34,  8.32it/s]
  4%|███▌                                                                           | 411/9182 [00:58<17:32,  8.33it/s]
  4%|███▌                                                                           | 412/9182 [00:59<17:26,  8.38it/s]
  5%|███▌                                                                           | 415/9182 [00:59<14:17, 10.23it/s]
  5%|███▌                                                                           | 417/9182 [01:00<24:43,  5.91it/s]
  5%|███▌                                                                           | 418/9182 [01:00<25:56,  5.63it/s]
  5%|███▋                                                                           | 422/9182 [01:00<15:55,  9.17it/s]
  5%|███▋                                                                           | 424/9182 [01:00<17:03,  8.56it/s]
  5%|███▋                                                                           | 427/9182 [01:01<18:16,  7.98it/s]
  5%|███▋                                                                           | 429/9182 [01:01<19:04,  7.65it/s]
  5%|███▋                                                                           | 430/9182 [01:01<19:14,  7.58it/s]
  5%|███▋                                                                           | 431/9182 [01:01<23:52,  6.11it/s]
  5%|███▋                                                                           | 432/9182 [01:02<28:51,  5.05it/s]
  5%|███▋                                                                           | 433/9182 [01:02<33:10,  4.40it/s]
  5%|███▋                                                                           | 434/9182 [01:02<28:50,  5.06it/s]
  5%|███▋                                                                           | 435/9182 [01:02<31:16,  4.66it/s]
  5%|███▊                                                                           | 436/9182 [01:03<31:53,  4.57it/s]
  5%|███▊                                                                           | 437/9182 [01:03<29:08,  5.00it/s]
  5%|███▊                                                                           | 438/9182 [01:03<31:25,  4.64it/s]
  5%|███▊                                                                           | 447/9182 [01:04<13:37, 10.69it/s]
  5%|███▊                                                                           | 448/9182 [01:04<20:55,  6.96it/s]
  5%|███▊                                                                           | 449/9182 [01:04<23:10,  6.28it/s]
  5%|███▉                                                                           | 461/9182 [01:05<07:57, 18.27it/s]
  5%|████                                                                           | 465/9182 [01:06<14:45,  9.84it/s]
  5%|████                                                                           | 468/9182 [01:07<21:00,  6.91it/s]
  5%|████                                                                           | 470/9182 [01:07<24:30,  5.92it/s]
  5%|████                                                                           | 472/9182 [01:07<21:24,  6.78it/s]
  5%|████                                                                           | 474/9182 [01:07<18:43,  7.75it/s]
  5%|████                                                                           | 478/9182 [01:07<13:32, 10.72it/s]
  5%|████▏                                                                          | 480/9182 [01:08<16:38,  8.71it/s]
  5%|████▏                                                                          | 482/9182 [01:08<19:50,  7.31it/s]
  5%|████▏                                                                          | 485/9182 [01:09<32:22,  4.48it/s]
  5%|████▏                                                                          | 486/9182 [01:10<35:18,  4.11it/s]
  5%|████▎                                                                          | 496/9182 [01:10<13:11, 10.98it/s]
  5%|████▎                                                                          | 499/9182 [01:10<12:53, 11.22it/s]
  5%|████▎                                                                          | 502/9182 [01:10<13:55, 10.38it/s]
  5%|████▎                                                                          | 504/9182 [01:11<23:22,  6.19it/s]
  6%|████▎                                                                          | 506/9182 [01:11<21:05,  6.85it/s]
  6%|████▎                                                                          | 508/9182 [01:12<19:40,  7.35it/s]
  6%|████▍                                                                          | 510/9182 [01:12<18:19,  7.89it/s]
  6%|████▍                                                                          | 518/9182 [01:12<10:36, 13.61it/s]
  6%|████▍                                                                          | 520/9182 [01:13<12:29, 11.56it/s]
  6%|████▍                                                                          | 522/9182 [01:13<13:52, 10.40it/s]
  6%|████▌                                                                          | 524/9182 [01:14<29:19,  4.92it/s]
  6%|████▌                                                                          | 525/9182 [01:14<31:04,  4.64it/s]
  6%|████▌                                                                          | 533/9182 [01:15<14:56,  9.64it/s]
  6%|████▌                                                                          | 535/9182 [01:15<16:54,  8.53it/s]
  6%|████▌                                                                          | 537/9182 [01:15<15:02,  9.57it/s]
  6%|████▋                                                                          | 542/9182 [01:15<13:00, 11.07it/s]
  6%|████▋                                                                          | 544/9182 [01:15<13:28, 10.69it/s]
  6%|████▋                                                                          | 546/9182 [01:16<18:13,  7.90it/s]
  6%|████▋                                                                          | 547/9182 [01:17<27:11,  5.29it/s]
  6%|████▋                                                                          | 548/9182 [01:17<26:49,  5.36it/s]
  6%|████▋                                                                          | 549/9182 [01:17<25:36,  5.62it/s]
  6%|████▊                                                                          | 556/9182 [01:18<19:46,  7.27it/s]
  6%|████▊                                                                          | 557/9182 [01:18<19:48,  7.26it/s]
  6%|████▊                                                                          | 562/9182 [01:18<12:14, 11.74it/s]
  6%|████▊                                                                          | 564/9182 [01:18<14:47,  9.70it/s]
  6%|████▊                                                                          | 566/9182 [01:19<16:26,  8.74it/s]
  6%|████▉                                                                          | 570/9182 [01:19<22:20,  6.42it/s]
  6%|████▉                                                                          | 571/9182 [01:20<22:28,  6.39it/s]
  6%|████▉                                                                          | 572/9182 [01:20<22:43,  6.32it/s]
  6%|████▉                                                                          | 573/9182 [01:20<23:51,  6.01it/s]
  6%|████▉                                                                          | 574/9182 [01:20<26:38,  5.39it/s]
  6%|████▉                                                                          | 575/9182 [01:20<27:03,  5.30it/s]
  6%|████▉                                                                          | 576/9182 [01:21<24:49,  5.78it/s]
  6%|████▉                                                                          | 577/9182 [01:21<25:41,  5.58it/s]
  6%|████▉                                                                          | 578/9182 [01:21<26:24,  5.43it/s]
  6%|████▉                                                                          | 579/9182 [01:21<28:38,  5.01it/s]
  6%|████▉                                                                          | 580/9182 [01:21<28:52,  4.97it/s]
  6%|████▉                                                                          | 581/9182 [01:21<25:36,  5.60it/s]
  6%|█████                                                                          | 591/9182 [01:22<08:16, 17.31it/s]
  6%|█████                                                                          | 593/9182 [01:22<09:16, 15.43it/s]
  6%|█████                                                                          | 595/9182 [01:23<15:02,  9.51it/s]
  7%|█████▏                                                                         | 597/9182 [01:23<16:29,  8.67it/s]
  7%|█████▏                                                                         | 598/9182 [01:23<16:58,  8.43it/s]
  7%|█████▏                                                                         | 599/9182 [01:23<18:13,  7.85it/s]
  7%|█████▏                                                                         | 602/9182 [01:23<14:51,  9.63it/s]
  7%|█████▏                                                                         | 605/9182 [01:24<12:58, 11.01it/s]
  7%|█████▏                                                                         | 608/9182 [01:24<13:55, 10.26it/s]
  7%|█████▏                                                                         | 610/9182 [01:24<14:08, 10.10it/s]
  7%|█████▎                                                                         | 613/9182 [01:25<19:57,  7.16it/s]
  7%|█████▎                                                                         | 614/9182 [01:25<20:39,  6.91it/s]
  7%|█████▎                                                                         | 615/9182 [01:25<22:29,  6.35it/s]
  7%|█████▎                                                                         | 616/9182 [01:25<24:29,  5.83it/s]
  7%|█████▎                                                                         | 617/9182 [01:26<29:27,  4.85it/s]
  7%|█████▎                                                                         | 618/9182 [01:26<41:16,  3.46it/s]
  7%|█████▍                                                                         | 629/9182 [01:27<19:10,  7.43it/s]
  7%|█████▍                                                                         | 632/9182 [01:29<28:21,  5.02it/s]
  7%|█████▍                                                                         | 633/9182 [01:29<27:43,  5.14it/s]
  7%|█████▍                                                                         | 634/9182 [01:29<26:23,  5.40it/s]
  7%|█████▍                                                                         | 635/9182 [01:29<26:52,  5.30it/s]
  7%|█████▌                                                                         | 645/9182 [01:29<12:19, 11.54it/s]
  7%|█████▌                                                                         | 647/9182 [01:30<12:13, 11.64it/s]
  7%|█████▌                                                                         | 649/9182 [01:30<12:42, 11.19it/s]
  7%|█████▌                                                                         | 651/9182 [01:30<17:09,  8.29it/s]
  7%|█████▌                                                                         | 652/9182 [01:31<22:57,  6.19it/s]
  7%|█████▋                                                                         | 656/9182 [01:31<14:42,  9.66it/s]
  7%|█████▋                                                                         | 658/9182 [01:31<14:52,  9.55it/s]
  7%|█████▋                                                                         | 660/9182 [01:32<27:13,  5.22it/s]
  7%|█████▋                                                                         | 662/9182 [01:32<28:50,  4.92it/s]
  7%|█████▋                                                                         | 663/9182 [01:33<40:23,  3.51it/s]
  7%|█████▋                                                                         | 666/9182 [01:33<31:11,  4.55it/s]

  7%|█████▋                                                                         | 667/9182 [01:34<31:17,  4.54it/s]
  7%|█████▊                                                                         | 677/9182 [01:35<20:55,  6.77it/s]
  7%|█████▊                                                                         | 678/9182 [01:35<22:38,  6.26it/s]
  7%|█████▊                                                                         | 679/9182 [01:35<21:43,  6.52it/s]
  7%|█████▉                                                                         | 687/9182 [01:36<12:23, 11.42it/s]
  8%|█████▉                                                                         | 689/9182 [01:36<18:58,  7.46it/s]
  8%|█████▉                                                                         | 690/9182 [01:36<19:00,  7.45it/s]
  8%|█████▉                                                                         | 691/9182 [01:37<19:29,  7.26it/s]
  8%|█████▉                                                                         | 692/9182 [01:37<22:47,  6.21it/s]
  8%|█████▉                                                                         | 693/9182 [01:38<40:13,  3.52it/s]
  8%|█████▉                                                                         | 694/9182 [01:38<50:04,  2.82it/s]
  8%|█████▉                                                                         | 696/9182 [01:38<39:11,  3.61it/s]
  8%|██████                                                                         | 706/9182 [01:39<12:00, 11.77it/s]
  8%|██████                                                                         | 711/9182 [01:39<15:25,  9.16it/s]
  8%|██████▏                                                                        | 716/9182 [01:40<14:32,  9.70it/s]
  8%|██████▏                                                                        | 718/9182 [01:40<14:50,  9.50it/s]
  8%|██████▏                                                                        | 720/9182 [01:41<18:43,  7.53it/s]
  8%|██████▏                                                                        | 722/9182 [01:41<18:21,  7.68it/s]
  8%|██████▏                                                                        | 724/9182 [01:41<22:28,  6.27it/s]
  8%|██████▎                                                                        | 727/9182 [01:42<22:52,  6.16it/s]
  8%|██████▎                                                                        | 729/9182 [01:42<19:58,  7.05it/s]
  8%|██████▎                                                                        | 730/9182 [01:42<23:41,  5.94it/s]
  8%|██████▎                                                                        | 731/9182 [01:43<27:27,  5.13it/s]
  8%|██████▎                                                                        | 732/9182 [01:43<29:11,  4.82it/s]
  8%|██████▎                                                                        | 733/9182 [01:43<27:52,  5.05it/s]
  8%|██████▎                                                                        | 734/9182 [01:43<24:57,  5.64it/s]
  8%|██████▎                                                                        | 736/9182 [01:44<24:08,  5.83it/s]
  8%|██████▎                                                                        | 737/9182 [01:44<23:54,  5.89it/s]
  8%|██████▎                                                                        | 738/9182 [01:44<26:50,  5.24it/s]
  8%|██████▎                                                                        | 739/9182 [01:44<25:59,  5.41it/s]
  8%|██████▎                                                                        | 740/9182 [01:44<26:04,  5.40it/s]
  8%|██████▍                                                                        | 743/9182 [01:45<18:06,  7.76it/s]
  8%|██████▍                                                                        | 744/9182 [01:45<19:37,  7.17it/s]
  8%|██████▍                                                                        | 745/9182 [01:45<25:40,  5.48it/s]
  8%|██████▍                                                                        | 746/9182 [01:45<27:11,  5.17it/s]
  8%|██████▍                                                                        | 747/9182 [01:46<30:10,  4.66it/s]
  8%|██████▍                                                                        | 748/9182 [01:46<40:52,  3.44it/s]
  8%|██████▍                                                                        | 749/9182 [01:46<38:22,  3.66it/s]
  8%|██████▍                                                                        | 750/9182 [01:46<33:07,  4.24it/s]
  8%|██████▍                                                                        | 751/9182 [01:47<29:02,  4.84it/s]
  8%|██████▍                                                                        | 752/9182 [01:47<26:30,  5.30it/s]
  8%|██████▍                                                                        | 753/9182 [01:47<23:11,  6.06it/s]
  8%|██████▍                                                                        | 754/9182 [01:47<21:59,  6.39it/s]
  8%|██████▍                                                                        | 755/9182 [01:47<20:14,  6.94it/s]
  8%|██████▌                                                                        | 756/9182 [01:47<31:42,  4.43it/s]
  8%|██████▌                                                                        | 757/9182 [01:48<30:31,  4.60it/s]
  8%|██████▌                                                                        | 758/9182 [01:48<32:38,  4.30it/s]
  8%|██████▌                                                                        | 759/9182 [01:48<35:41,  3.93it/s]
  8%|██████▌                                                                        | 760/9182 [01:49<37:09,  3.78it/s]
  8%|██████▌                                                                        | 761/9182 [01:49<44:29,  3.15it/s]
  8%|██████▌                                                                        | 762/9182 [01:49<37:22,  3.75it/s]
  8%|██████▌                                                                        | 764/9182 [01:50<39:52,  3.52it/s]
  8%|██████▌                                                                        | 765/9182 [01:50<36:00,  3.90it/s]
  8%|██████▌                                                                        | 766/9182 [01:50<35:40,  3.93it/s]
  8%|██████▌                                                                        | 767/9182 [01:50<34:46,  4.03it/s]
  8%|██████▌                                                                        | 768/9182 [01:51<34:45,  4.04it/s]
  8%|██████▌                                                                        | 769/9182 [01:51<34:28,  4.07it/s]
  8%|██████▋                                                                        | 777/9182 [01:52<29:10,  4.80it/s]
  8%|██████▋                                                                        | 778/9182 [01:53<29:07,  4.81it/s]
  8%|██████▋                                                                        | 779/9182 [01:53<27:53,  5.02it/s]
  8%|██████▋                                                                        | 780/9182 [01:53<30:46,  4.55it/s]
  9%|██████▋                                                                        | 781/9182 [01:53<31:34,  4.43it/s]
  9%|██████▋                                                                        | 782/9182 [01:54<33:19,  4.20it/s]
  9%|██████▋                                                                        | 783/9182 [01:54<32:31,  4.30it/s]
  9%|██████▋                                                                        | 784/9182 [01:54<28:35,  4.90it/s]
  9%|██████▊                                                                        | 785/9182 [01:54<27:43,  5.05it/s]
  9%|██████▊                                                                        | 787/9182 [01:55<30:56,  4.52it/s]
  9%|██████▊                                                                        | 788/9182 [01:55<37:10,  3.76it/s]
  9%|██████▊                                                                        | 789/9182 [01:55<34:18,  4.08it/s]
  9%|██████▊                                                                        | 790/9182 [01:56<32:18,  4.33it/s]
  9%|██████▊                                                                        | 791/9182 [01:56<39:25,  3.55it/s]
  9%|██████▊                                                                        | 792/9182 [01:56<32:28,  4.31it/s]
  9%|██████▊                                                                        | 794/9182 [01:56<25:43,  5.43it/s]
  9%|██████▊                                                                        | 799/9182 [01:56<12:05, 11.56it/s]
  9%|██████▉                                                                        | 801/9182 [01:57<22:27,  6.22it/s]
  9%|██████▉                                                                        | 803/9182 [01:57<20:30,  6.81it/s]
  9%|██████▉                                                                        | 805/9182 [01:58<23:42,  5.89it/s]
  9%|██████▉                                                                        | 806/9182 [01:58<25:28,  5.48it/s]
  9%|██████▉                                                                        | 807/9182 [01:59<30:41,  4.55it/s]
  9%|██████▉                                                                        | 808/9182 [01:59<41:19,  3.38it/s]
  9%|██████▉                                                                        | 809/9182 [01:59<35:04,  3.98it/s]
  9%|██████▉                                                                        | 810/9182 [02:00<41:43,  3.34it/s]
  9%|██████▉                                                                        | 811/9182 [02:00<47:45,  2.92it/s]
  9%|██████▉                                                                        | 812/9182 [02:00<42:16,  3.30it/s]
  9%|██████▉                                                                        | 813/9182 [02:01<41:57,  3.32it/s]
  9%|███████                                                                        | 814/9182 [02:01<48:42,  2.86it/s]
  9%|███████                                                                        | 815/9182 [02:01<40:15,  3.46it/s]
  9%|███████                                                                        | 816/9182 [02:01<32:46,  4.25it/s]
  9%|███████                                                                        | 817/9182 [02:01<35:30,  3.93it/s]
  9%|███████                                                                        | 818/9182 [02:02<35:15,  3.95it/s]
  9%|███████                                                                        | 819/9182 [02:02<33:14,  4.19it/s]
  9%|███████                                                                        | 820/9182 [02:02<38:58,  3.58it/s]
  9%|███████                                                                        | 821/9182 [02:03<35:33,  3.92it/s]
  9%|███████                                                                        | 824/9182 [02:03<20:05,  6.93it/s]
  9%|███████                                                                        | 825/9182 [02:03<20:27,  6.81it/s]
  9%|███████                                                                        | 826/9182 [02:03<23:52,  5.83it/s]
  9%|███████                                                                        | 827/9182 [02:04<31:16,  4.45it/s]
  9%|███████                                                                        | 828/9182 [02:04<33:30,  4.15it/s]
  9%|███████▏                                                                       | 829/9182 [02:04<30:08,  4.62it/s]
  9%|███████▏                                                                       | 830/9182 [02:04<30:14,  4.60it/s]
  9%|███████▏                                                                       | 831/9182 [02:04<30:18,  4.59it/s]
  9%|███████▏                                                                       | 832/9182 [02:05<39:19,  3.54it/s]
  9%|███████▏                                                                       | 833/9182 [02:05<45:00,  3.09it/s]
  9%|███████▏                                                                       | 834/9182 [02:06<40:49,  3.41it/s]
  9%|███████▏                                                                       | 835/9182 [02:06<34:08,  4.07it/s]
  9%|███████▏                                                                       | 836/9182 [02:06<30:52,  4.51it/s]
  9%|███████▏                                                                       | 837/9182 [02:06<26:48,  5.19it/s]
  9%|███████▏                                                                       | 838/9182 [02:06<23:57,  5.81it/s]
  9%|███████▎                                                                       | 843/9182 [02:07<17:37,  7.89it/s]
  9%|███████▎                                                                       | 845/9182 [02:07<15:04,  9.22it/s]
  9%|███████▎                                                                       | 849/9182 [02:07<10:54, 12.74it/s]
  9%|███████▎                                                                       | 851/9182 [02:08<29:39,  4.68it/s]
  9%|███████▎                                                                       | 853/9182 [02:09<37:00,  3.75it/s]
  9%|███████▎                                                                       | 854/9182 [02:09<38:53,  3.57it/s]
  9%|███████▎                                                                       | 855/9182 [02:10<35:59,  3.86it/s]
  9%|███████▎                                                                       | 856/9182 [02:10<34:40,  4.00it/s]
  9%|███████▍                                                                       | 859/9182 [02:10<23:12,  5.98it/s]
  9%|███████▍                                                                       | 860/9182 [02:10<30:04,  4.61it/s]
  9%|███████▍                                                                       | 861/9182 [02:11<40:35,  3.42it/s]
  9%|███████▍                                                                       | 862/9182 [02:11<36:31,  3.80it/s]
  9%|███████▍                                                                       | 863/9182 [02:11<38:48,  3.57it/s]
  9%|███████▍                                                                       | 864/9182 [02:12<32:52,  4.22it/s]
  9%|███████▍                                                                       | 865/9182 [02:12<31:43,  4.37it/s]
  9%|███████▍                                                                       | 866/9182 [02:12<30:51,  4.49it/s]
  9%|███████▍                                                                       | 867/9182 [02:12<28:33,  4.85it/s]
  9%|███████▍                                                                       | 868/9182 [02:12<28:34,  4.85it/s]
  9%|███████▍                                                                       | 869/9182 [02:12<27:15,  5.08it/s]
  9%|███████▍                                                                       | 870/9182 [02:13<27:43,  5.00it/s]
  9%|███████▍                                                                       | 871/9182 [02:13<26:53,  5.15it/s]
  9%|███████▌                                                                       | 872/9182 [02:13<23:02,  6.01it/s]
 10%|███████▌                                                                       | 873/9182 [02:13<20:52,  6.63it/s]
 10%|███████▌                                                                       | 874/9182 [02:14<32:54,  4.21it/s]

 10%|███████▌                                                                       | 875/9182 [02:14<30:18,  4.57it/s]
 10%|███████▌                                                                       | 877/9182 [02:14<23:55,  5.78it/s]
 10%|███████▌                                                                       | 878/9182 [02:14<25:54,  5.34it/s]
 10%|███████▌                                                                       | 879/9182 [02:14<28:19,  4.89it/s]
 10%|███████▌                                                                       | 882/9182 [02:15<22:18,  6.20it/s]
 10%|███████▌                                                                       | 883/9182 [02:15<24:15,  5.70it/s]
 10%|███████▌                                                                       | 884/9182 [02:15<22:39,  6.10it/s]
 10%|███████▌                                                                       | 885/9182 [02:15<22:53,  6.04it/s]
 10%|███████▋                                                                       | 887/9182 [02:15<18:18,  7.55it/s]
 10%|███████▋                                                                       | 888/9182 [02:16<24:07,  5.73it/s]
 10%|███████▋                                                                       | 892/9182 [02:16<12:40, 10.90it/s]
 10%|███████▋                                                                       | 894/9182 [02:16<15:02,  9.19it/s]
 10%|███████▋                                                                       | 896/9182 [02:17<25:04,  5.51it/s]
 10%|███████▋                                                                       | 897/9182 [02:18<33:49,  4.08it/s]
 10%|███████▋                                                                       | 898/9182 [02:18<34:43,  3.98it/s]
 10%|███████▋                                                                       | 899/9182 [02:18<36:50,  3.75it/s]
 10%|███████▋                                                                       | 900/9182 [02:18<34:30,  4.00it/s]
 10%|███████▊                                                                       | 901/9182 [02:19<32:34,  4.24it/s]
 10%|███████▊                                                                       | 902/9182 [02:19<50:12,  2.75it/s]
 10%|███████▊                                                                       | 903/9182 [02:20<46:55,  2.94it/s]
 10%|███████▊                                                                       | 904/9182 [02:20<40:32,  3.40it/s]
 10%|███████▊                                                                       | 908/9182 [02:20<19:20,  7.13it/s]
 10%|███████▊                                                                       | 909/9182 [02:20<19:07,  7.21it/s]
 10%|███████▊                                                                       | 910/9182 [02:20<25:28,  5.41it/s]
 10%|███████▊                                                                       | 911/9182 [02:20<24:42,  5.58it/s]
 10%|███████▊                                                                       | 912/9182 [02:21<22:21,  6.17it/s]
 10%|███████▊                                                                       | 913/9182 [02:21<22:41,  6.08it/s]
 10%|███████▊                                                                       | 914/9182 [02:21<31:41,  4.35it/s]
 10%|███████▉                                                                       | 916/9182 [02:21<21:47,  6.32it/s]
 10%|███████▉                                                                       | 917/9182 [02:22<22:55,  6.01it/s]
 10%|███████▉                                                                       | 918/9182 [02:22<25:25,  5.42it/s]
 10%|███████▉                                                                       | 920/9182 [02:23<33:59,  4.05it/s]
 10%|███████▉                                                                       | 921/9182 [02:23<43:21,  3.18it/s]
 10%|███████▉                                                                       | 925/9182 [02:23<22:24,  6.14it/s]
 10%|███████▉                                                                       | 926/9182 [02:23<21:50,  6.30it/s]
 10%|███████▉                                                                       | 928/9182 [02:24<21:32,  6.39it/s]
 10%|████████                                                                       | 930/9182 [02:24<20:28,  6.72it/s]
 10%|████████                                                                       | 931/9182 [02:24<19:29,  7.06it/s]
 10%|████████                                                                       | 935/9182 [02:24<12:45, 10.77it/s]
 10%|████████                                                                       | 937/9182 [02:25<18:41,  7.36it/s]
 10%|████████                                                                       | 938/9182 [02:25<25:20,  5.42it/s]
 10%|████████                                                                       | 939/9182 [02:25<29:07,  4.72it/s]
 10%|████████                                                                       | 940/9182 [02:26<30:40,  4.48it/s]
 10%|████████                                                                       | 941/9182 [02:26<32:44,  4.19it/s]
 10%|████████                                                                       | 942/9182 [02:26<28:30,  4.82it/s]
 10%|████████                                                                       | 943/9182 [02:26<26:55,  5.10it/s]
 10%|████████                                                                       | 944/9182 [02:27<30:35,  4.49it/s]
 10%|████████▏                                                                      | 945/9182 [02:27<32:57,  4.17it/s]
 10%|████████▏                                                                      | 946/9182 [02:27<27:27,  5.00it/s]
 10%|████████▏                                                                      | 947/9182 [02:27<26:10,  5.24it/s]
 10%|████████▏                                                                      | 948/9182 [02:27<26:11,  5.24it/s]
 10%|████████▏                                                                      | 949/9182 [02:27<23:16,  5.90it/s]
 10%|████████▏                                                                      | 950/9182 [02:28<23:17,  5.89it/s]
 10%|████████▏                                                                      | 951/9182 [02:28<22:47,  6.02it/s]
 10%|████████▏                                                                      | 952/9182 [02:28<23:21,  5.87it/s]
 10%|████████▏                                                                      | 955/9182 [02:28<13:06, 10.46it/s]
 10%|████████▏                                                                      | 957/9182 [02:29<13:00, 10.54it/s]
 10%|████████▎                                                                      | 959/9182 [02:29<21:28,  6.38it/s]
 10%|████████▎                                                                      | 960/9182 [02:30<59:36,  2.30it/s]
 11%|████████▎                                                                      | 966/9182 [02:31<26:01,  5.26it/s]
 11%|████████▎                                                                      | 968/9182 [02:31<29:04,  4.71it/s]
 11%|████████▎                                                                      | 970/9182 [02:31<24:08,  5.67it/s]
 11%|████████▎                                                                      | 972/9182 [02:31<19:56,  6.86it/s]
 11%|████████▍                                                                      | 974/9182 [02:32<18:03,  7.58it/s]
 11%|████████▍                                                                      | 976/9182 [02:32<21:59,  6.22it/s]
 11%|████████▍                                                                      | 977/9182 [02:32<25:01,  5.46it/s]
 11%|████████▍                                                                      | 978/9182 [02:33<25:23,  5.38it/s]
 11%|████████▍                                                                      | 979/9182 [02:33<27:55,  4.90it/s]
 11%|████████▍                                                                      | 980/9182 [02:33<29:57,  4.56it/s]
 11%|████████▍                                                                      | 981/9182 [02:34<32:37,  4.19it/s]
 11%|████████▍                                                                      | 982/9182 [02:34<34:31,  3.96it/s]
 11%|████████▍                                                                      | 983/9182 [02:34<29:37,  4.61it/s]
 11%|████████▍                                                                      | 984/9182 [02:34<32:00,  4.27it/s]
 11%|████████▍                                                                      | 985/9182 [02:34<29:05,  4.69it/s]
 11%|████████▍                                                                      | 986/9182 [02:35<29:17,  4.66it/s]
 11%|████████▍                                                                      | 987/9182 [02:35<31:36,  4.32it/s]
 11%|████████▌                                                                      | 990/9182 [02:35<16:54,  8.07it/s]
 11%|████████▌                                                                      | 992/9182 [02:36<29:59,  4.55it/s]
 11%|████████▌                                                                      | 993/9182 [02:36<28:55,  4.72it/s]
 11%|████████▌                                                                      | 994/9182 [02:36<30:46,  4.43it/s]
 11%|████████▌                                                                      | 995/9182 [02:37<32:43,  4.17it/s]
 11%|████████▌                                                                      | 996/9182 [02:37<42:52,  3.18it/s]
 11%|████████▌                                                                      | 997/9182 [02:37<40:11,  3.39it/s]
 11%|████████▌                                                                      | 998/9182 [02:38<47:58,  2.84it/s]
 11%|████████▌                                                                      | 999/9182 [02:38<42:19,  3.22it/s]
 11%|████████▍                                                                     | 1000/9182 [02:38<39:12,  3.48it/s]
 11%|████████▌                                                                     | 1001/9182 [02:38<33:35,  4.06it/s]
 11%|████████▌                                                                     | 1002/9182 [02:38<28:17,  4.82it/s]
 11%|████████▌                                                                     | 1003/9182 [02:39<24:24,  5.59it/s]
 11%|████████▌                                                                     | 1004/9182 [02:39<24:12,  5.63it/s]
 11%|████████▌                                                                     | 1010/9182 [02:39<15:00,  9.08it/s]
 11%|████████▌                                                                     | 1011/9182 [02:39<16:57,  8.03it/s]
 11%|████████▌                                                                     | 1012/9182 [02:40<20:54,  6.51it/s]
 11%|████████▌                                                                     | 1015/9182 [02:40<15:11,  8.96it/s]
 11%|████████▋                                                                     | 1016/9182 [02:40<16:02,  8.48it/s]
 11%|████████▋                                                                     | 1017/9182 [02:40<20:59,  6.48it/s]
 11%|████████▋                                                                     | 1018/9182 [02:41<23:24,  5.81it/s]
 11%|████████▋                                                                     | 1019/9182 [02:41<23:57,  5.68it/s]
 11%|████████▋                                                                     | 1020/9182 [02:41<33:16,  4.09it/s]
 11%|████████▋                                                                     | 1021/9182 [02:41<28:56,  4.70it/s]
 11%|████████▋                                                                     | 1022/9182 [02:42<31:20,  4.34it/s]
 11%|████████▋                                                                     | 1023/9182 [02:42<29:31,  4.60it/s]
 11%|████████▋                                                                     | 1024/9182 [02:42<28:48,  4.72it/s]
 11%|████████▋                                                                     | 1025/9182 [02:42<39:53,  3.41it/s]
 11%|████████▋                                                                     | 1026/9182 [02:43<37:59,  3.58it/s]
 11%|████████▋                                                                     | 1027/9182 [02:43<36:16,  3.75it/s]
 11%|████████▋                                                                     | 1028/9182 [02:43<36:04,  3.77it/s]
 11%|████████▋                                                                     | 1029/9182 [02:44<36:10,  3.76it/s]
 11%|████████▋                                                                     | 1030/9182 [02:44<36:00,  3.77it/s]
 11%|████████▊                                                                     | 1031/9182 [02:44<45:46,  2.97it/s]
 11%|████████▊                                                                     | 1034/9182 [02:45<26:36,  5.10it/s]
 11%|████████▊                                                                     | 1035/9182 [02:45<24:23,  5.57it/s]
 11%|████████▊                                                                     | 1036/9182 [02:45<22:01,  6.16it/s]
 11%|████████▊                                                                     | 1039/9182 [02:45<16:22,  8.29it/s]
 11%|████████▊                                                                     | 1040/9182 [02:45<20:36,  6.59it/s]
 11%|████████▊                                                                     | 1041/9182 [02:46<22:14,  6.10it/s]
 11%|████████▊                                                                     | 1042/9182 [02:46<41:09,  3.30it/s]
 11%|████████▊                                                                     | 1043/9182 [02:47<44:12,  3.07it/s]
 11%|████████▊                                                                     | 1044/9182 [02:47<44:51,  3.02it/s]
 11%|████████▉                                                                     | 1045/9182 [02:47<41:05,  3.30it/s]
 11%|████████▉                                                                     | 1046/9182 [02:48<41:23,  3.28it/s]
 11%|████████▉                                                                     | 1047/9182 [02:48<40:59,  3.31it/s]
 11%|████████▉                                                                     | 1048/9182 [02:48<41:02,  3.30it/s]
 11%|████████▉                                                                     | 1049/9182 [02:48<38:08,  3.55it/s]
 11%|████████▉                                                                     | 1050/9182 [02:48<32:49,  4.13it/s]
 11%|████████▉                                                                     | 1053/9182 [02:49<21:06,  6.42it/s]
 11%|████████▉                                                                     | 1054/9182 [02:49<19:44,  6.86it/s]
 11%|████████▉                                                                     | 1055/9182 [02:49<20:33,  6.59it/s]
 12%|████████▉                                                                     | 1056/9182 [02:49<19:03,  7.10it/s]
 12%|████████▉                                                                     | 1057/9182 [02:49<19:18,  7.01it/s]
 12%|████████▉                                                                     | 1058/9182 [02:49<18:52,  7.17it/s]
 12%|█████████                                                                     | 1064/9182 [02:50<19:54,  6.80it/s]

 12%|█████████                                                                     | 1065/9182 [02:51<24:00,  5.64it/s]
 12%|█████████                                                                     | 1066/9182 [02:51<23:39,  5.72it/s]
 12%|█████████                                                                     | 1067/9182 [02:51<21:43,  6.22it/s]
 12%|█████████                                                                     | 1068/9182 [02:51<27:46,  4.87it/s]
 12%|█████████                                                                     | 1069/9182 [02:52<25:41,  5.26it/s]
 12%|█████████                                                                     | 1070/9182 [02:52<32:55,  4.11it/s]
 12%|█████████                                                                     | 1071/9182 [02:52<33:06,  4.08it/s]
 12%|█████████                                                                     | 1072/9182 [02:52<34:43,  3.89it/s]
 12%|█████████                                                                     | 1073/9182 [02:52<30:35,  4.42it/s]
 12%|█████████                                                                     | 1074/9182 [02:53<30:33,  4.42it/s]
 12%|█████████▏                                                                    | 1075/9182 [02:53<39:44,  3.40it/s]
 12%|█████████▏                                                                    | 1076/9182 [02:53<34:32,  3.91it/s]
 12%|█████████▏                                                                    | 1077/9182 [02:54<33:51,  3.99it/s]
 12%|█████████▏                                                                    | 1078/9182 [02:54<35:44,  3.78it/s]
 12%|█████████▏                                                                    | 1079/9182 [02:54<37:58,  3.56it/s]
 12%|█████████▏                                                                    | 1081/9182 [02:54<23:49,  5.67it/s]
 12%|█████████▏                                                                    | 1082/9182 [02:54<21:47,  6.19it/s]
 12%|█████████▏                                                                    | 1083/9182 [02:55<21:21,  6.32it/s]
 12%|█████████▏                                                                    | 1087/9182 [02:55<20:26,  6.60it/s]
 12%|█████████▏                                                                    | 1088/9182 [02:55<23:29,  5.74it/s]
 12%|█████████▎                                                                    | 1089/9182 [02:56<26:25,  5.10it/s]
 12%|█████████▎                                                                    | 1090/9182 [02:56<26:18,  5.13it/s]
 12%|█████████▎                                                                    | 1091/9182 [02:56<29:35,  4.56it/s]
 12%|█████████▎                                                                    | 1092/9182 [02:57<33:45,  3.99it/s]
 12%|█████████▎                                                                    | 1093/9182 [02:57<28:32,  4.72it/s]
 12%|█████████▎                                                                    | 1094/9182 [02:57<37:10,  3.63it/s]
 12%|█████████▎                                                                    | 1095/9182 [02:57<32:56,  4.09it/s]
 12%|█████████▎                                                                    | 1096/9182 [02:58<53:47,  2.51it/s]
 12%|█████████▎                                                                    | 1097/9182 [02:59<54:27,  2.47it/s]
 12%|█████████▎                                                                    | 1098/9182 [02:59<53:00,  2.54it/s]
 12%|█████████▎                                                                    | 1099/9182 [02:59<43:48,  3.08it/s]
 12%|█████████▎                                                                    | 1100/9182 [02:59<38:00,  3.54it/s]
 12%|█████████▎                                                                    | 1101/9182 [02:59<35:16,  3.82it/s]
 12%|█████████▍                                                                    | 1105/9182 [03:00<16:56,  7.95it/s]
 12%|█████████▍                                                                    | 1106/9182 [03:00<18:18,  7.35it/s]
 12%|█████████▍                                                                    | 1107/9182 [03:00<19:14,  6.99it/s]
 12%|█████████▍                                                                    | 1108/9182 [03:00<22:12,  6.06it/s]
 12%|█████████▍                                                                    | 1109/9182 [03:00<26:11,  5.14it/s]
 12%|█████████▍                                                                    | 1112/9182 [03:01<16:20,  8.23it/s]
 12%|█████████▍                                                                    | 1113/9182 [03:01<15:46,  8.52it/s]
 12%|█████████▍                                                                    | 1114/9182 [03:01<15:46,  8.52it/s]
 12%|█████████▍                                                                    | 1115/9182 [03:02<25:03,  5.36it/s]
 12%|█████████▍                                                                    | 1116/9182 [03:02<32:39,  4.12it/s]
 12%|█████████▍                                                                    | 1117/9182 [03:02<39:09,  3.43it/s]
 12%|█████████▍                                                                    | 1118/9182 [03:02<41:14,  3.26it/s]
 12%|█████████▌                                                                    | 1119/9182 [03:03<37:12,  3.61it/s]
 12%|█████████▌                                                                    | 1120/9182 [03:03<33:26,  4.02it/s]
 12%|█████████▌                                                                    | 1121/9182 [03:03<36:11,  3.71it/s]
 12%|█████████▌                                                                    | 1122/9182 [03:03<31:03,  4.33it/s]
 12%|█████████▌                                                                    | 1123/9182 [03:04<35:29,  3.78it/s]
 12%|█████████▌                                                                    | 1124/9182 [03:04<39:11,  3.43it/s]
 12%|█████████▌                                                                    | 1125/9182 [03:04<32:03,  4.19it/s]
 12%|█████████▌                                                                    | 1126/9182 [03:04<32:18,  4.16it/s]
 12%|█████████▌                                                                    | 1128/9182 [03:05<24:07,  5.56it/s]
 12%|█████████▌                                                                    | 1129/9182 [03:05<24:19,  5.52it/s]
 12%|█████████▌                                                                    | 1131/9182 [03:05<24:07,  5.56it/s]
 12%|█████████▌                                                                    | 1132/9182 [03:05<26:52,  4.99it/s]
 12%|█████████▌                                                                    | 1133/9182 [03:06<37:30,  3.58it/s]
 12%|█████████▋                                                                    | 1134/9182 [03:06<31:35,  4.25it/s]
 12%|█████████▋                                                                    | 1135/9182 [03:06<29:35,  4.53it/s]
 12%|█████████▋                                                                    | 1137/9182 [03:07<34:38,  3.87it/s]
 12%|█████████▋                                                                    | 1141/9182 [03:07<25:43,  5.21it/s]
 12%|█████████▋                                                                    | 1142/9182 [03:08<27:28,  4.88it/s]
 12%|█████████▋                                                                    | 1143/9182 [03:08<30:17,  4.42it/s]
 12%|█████████▋                                                                    | 1144/9182 [03:09<42:22,  3.16it/s]
 12%|█████████▋                                                                    | 1145/9182 [03:09<52:01,  2.57it/s]
 12%|█████████▋                                                                    | 1146/9182 [03:10<56:24,  2.37it/s]
 12%|█████████▋                                                                    | 1147/9182 [03:10<59:43,  2.24it/s]
 13%|█████████▊                                                                    | 1148/9182 [03:10<51:18,  2.61it/s]
 13%|█████████▊                                                                    | 1149/9182 [03:11<46:58,  2.85it/s]
 13%|█████████▊                                                                    | 1153/9182 [03:11<21:53,  6.11it/s]
 13%|█████████▊                                                                    | 1154/9182 [03:11<25:48,  5.19it/s]
 13%|█████████▊                                                                    | 1157/9182 [03:11<17:03,  7.84it/s]
 13%|█████████▊                                                                    | 1159/9182 [03:12<19:32,  6.84it/s]
 13%|█████████▊                                                                    | 1160/9182 [03:12<21:01,  6.36it/s]
 13%|█████████▊                                                                    | 1161/9182 [03:12<20:50,  6.42it/s]
 13%|█████████▊                                                                    | 1162/9182 [03:12<20:41,  6.46it/s]
 13%|█████████▉                                                                    | 1163/9182 [03:13<21:13,  6.30it/s]
 13%|█████████▉                                                                    | 1164/9182 [03:13<25:23,  5.26it/s]
 13%|█████████▉                                                                    | 1165/9182 [03:13<37:50,  3.53it/s]
 13%|█████████▉                                                                    | 1166/9182 [03:13<32:34,  4.10it/s]
 13%|█████████▉                                                                    | 1170/9182 [03:14<23:58,  5.57it/s]
 13%|█████████▉                                                                    | 1171/9182 [03:15<36:12,  3.69it/s]
 13%|█████████▉                                                                    | 1172/9182 [03:15<36:01,  3.71it/s]
 13%|█████████▉                                                                    | 1173/9182 [03:15<34:45,  3.84it/s]
 13%|█████████▉                                                                    | 1174/9182 [03:15<39:25,  3.39it/s]
 13%|█████████▉                                                                    | 1176/9182 [03:16<38:24,  3.47it/s]
 13%|█████████▉                                                                    | 1177/9182 [03:16<40:03,  3.33it/s]
 13%|██████████                                                                    | 1178/9182 [03:17<36:38,  3.64it/s]
 13%|██████████                                                                    | 1179/9182 [03:17<43:51,  3.04it/s]
 13%|██████████                                                                    | 1180/9182 [03:18<38:25,  3.47it/s]
 13%|██████████                                                                    | 1181/9182 [03:18<48:32,  2.75it/s]
 13%|██████████                                                                    | 1182/9182 [03:18<40:01,  3.33it/s]
 13%|██████████                                                                    | 1185/9182 [03:18<22:50,  5.83it/s]
 13%|██████████                                                                    | 1187/9182 [03:18<20:43,  6.43it/s]
 13%|██████████                                                                    | 1188/9182 [03:19<30:46,  4.33it/s]
 13%|██████████                                                                    | 1189/9182 [03:19<32:21,  4.12it/s]
 13%|██████████                                                                    | 1190/9182 [03:20<33:42,  3.95it/s]
 13%|██████████                                                                    | 1191/9182 [03:20<31:31,  4.23it/s]
 13%|██████████▏                                                                   | 1192/9182 [03:20<27:00,  4.93it/s]
 13%|██████████▏                                                                   | 1193/9182 [03:20<29:59,  4.44it/s]
 13%|██████████▏                                                                   | 1194/9182 [03:20<25:50,  5.15it/s]
 13%|██████████▏                                                                   | 1195/9182 [03:21<26:11,  5.08it/s]
 13%|██████████▏                                                                   | 1196/9182 [03:21<25:31,  5.21it/s]
 13%|██████████▏                                                                   | 1197/9182 [03:22<58:40,  2.27it/s]
 13%|██████████▏                                                                   | 1198/9182 [03:22<47:23,  2.81it/s]
 13%|██████████▏                                                                   | 1199/9182 [03:22<44:08,  3.01it/s]
 13%|██████████▏                                                                   | 1200/9182 [03:23<40:27,  3.29it/s]
 13%|██████████▏                                                                   | 1201/9182 [03:23<45:23,  2.93it/s]
 13%|██████████▏                                                                   | 1205/9182 [03:23<26:41,  4.98it/s]
 13%|██████████▏                                                                   | 1206/9182 [03:23<27:23,  4.85it/s]
 13%|██████████▎                                                                   | 1208/9182 [03:24<22:47,  5.83it/s]
 13%|██████████▎                                                                   | 1209/9182 [03:24<24:05,  5.51it/s]
 13%|██████████▎                                                                   | 1212/9182 [03:24<15:12,  8.73it/s]
 13%|██████████▎                                                                   | 1214/9182 [03:25<25:54,  5.13it/s]
 13%|██████████▎                                                                   | 1215/9182 [03:25<24:57,  5.32it/s]
 13%|██████████▎                                                                   | 1216/9182 [03:25<30:44,  4.32it/s]
 13%|██████████▎                                                                   | 1217/9182 [03:26<37:23,  3.55it/s]
 13%|██████████▎                                                                   | 1218/9182 [03:26<46:38,  2.85it/s]
 13%|██████████▎                                                                   | 1219/9182 [03:27<47:36,  2.79it/s]
 13%|██████████▎                                                                   | 1220/9182 [03:27<38:43,  3.43it/s]
 13%|██████████▎                                                                   | 1221/9182 [03:27<34:51,  3.81it/s]
 13%|██████████▍                                                                   | 1222/9182 [03:27<39:54,  3.32it/s]
 13%|██████████▍                                                                   | 1223/9182 [03:28<35:55,  3.69it/s]
 13%|██████████▍                                                                   | 1224/9182 [03:28<42:11,  3.14it/s]
 13%|██████████▍                                                                   | 1225/9182 [03:28<39:34,  3.35it/s]
 13%|██████████▍                                                                   | 1226/9182 [03:29<39:16,  3.38it/s]
 13%|██████████▍                                                                   | 1227/9182 [03:29<52:52,  2.51it/s]
 13%|██████████▍                                                                   | 1228/9182 [03:30<57:07,  2.32it/s]
 13%|██████████▍                                                                   | 1231/9182 [03:30<43:39,  3.04it/s]
 13%|██████████▍                                                                   | 1232/9182 [03:31<42:43,  3.10it/s]
 13%|██████████▍                                                                   | 1233/9182 [03:31<45:23,  2.92it/s]

 13%|██████████▍                                                                   | 1235/9182 [03:32<37:00,  3.58it/s]
 13%|██████████▍                                                                   | 1236/9182 [03:32<34:06,  3.88it/s]
 13%|██████████▌                                                                   | 1237/9182 [03:32<34:30,  3.84it/s]
 13%|██████████▌                                                                   | 1238/9182 [03:32<40:20,  3.28it/s]
 13%|██████████▌                                                                   | 1239/9182 [03:33<38:15,  3.46it/s]
 14%|██████████▌                                                                   | 1240/9182 [03:33<35:38,  3.71it/s]
 14%|██████████▌                                                                   | 1244/9182 [03:33<16:23,  8.07it/s]
 14%|██████████▌                                                                   | 1246/9182 [03:33<20:35,  6.42it/s]
 14%|██████████▌                                                                   | 1247/9182 [03:34<28:40,  4.61it/s]
 14%|██████████▌                                                                   | 1248/9182 [03:34<34:46,  3.80it/s]
 14%|██████████▌                                                                   | 1250/9182 [03:35<42:41,  3.10it/s]
 14%|██████████▋                                                                   | 1251/9182 [03:36<36:44,  3.60it/s]
 14%|██████████▋                                                                   | 1252/9182 [03:36<41:03,  3.22it/s]
 14%|██████████▋                                                                   | 1253/9182 [03:36<40:34,  3.26it/s]
 14%|██████████▋                                                                   | 1254/9182 [03:36<33:27,  3.95it/s]
 14%|██████████▋                                                                   | 1255/9182 [03:37<30:10,  4.38it/s]
 14%|██████████▋                                                                   | 1256/9182 [03:37<34:35,  3.82it/s]
 14%|██████████▋                                                                   | 1257/9182 [03:37<28:51,  4.58it/s]
 14%|██████████▋                                                                   | 1258/9182 [03:37<31:59,  4.13it/s]
 14%|██████████▋                                                                   | 1259/9182 [03:37<27:10,  4.86it/s]
 14%|██████████▋                                                                   | 1262/9182 [03:37<16:41,  7.90it/s]
 14%|██████████▋                                                                   | 1264/9182 [03:38<14:23,  9.17it/s]
 14%|██████████▊                                                                   | 1266/9182 [03:38<16:31,  7.98it/s]
 14%|██████████▊                                                                   | 1268/9182 [03:38<17:44,  7.44it/s]
 14%|██████████▊                                                                   | 1269/9182 [03:39<22:29,  5.86it/s]
 14%|██████████▊                                                                   | 1270/9182 [03:39<21:23,  6.17it/s]
 14%|██████████▊                                                                   | 1271/9182 [03:39<36:49,  3.58it/s]
 14%|██████████▊                                                                   | 1272/9182 [03:40<35:09,  3.75it/s]
 14%|██████████▊                                                                   | 1273/9182 [03:40<34:22,  3.84it/s]
 14%|██████████▊                                                                   | 1274/9182 [03:40<38:08,  3.46it/s]
 14%|██████████▊                                                                   | 1275/9182 [03:40<31:45,  4.15it/s]
 14%|██████████▊                                                                   | 1276/9182 [03:41<40:46,  3.23it/s]
 14%|██████████▊                                                                   | 1277/9182 [03:41<36:56,  3.57it/s]
 14%|██████████▊                                                                   | 1278/9182 [03:41<36:28,  3.61it/s]
 14%|██████████▊                                                                   | 1279/9182 [03:42<42:58,  3.06it/s]
 14%|██████████▊                                                                   | 1280/9182 [03:42<38:02,  3.46it/s]
 14%|██████████▉                                                                   | 1281/9182 [03:42<33:24,  3.94it/s]
 14%|██████████▉                                                                   | 1282/9182 [03:42<32:52,  4.01it/s]
 14%|██████████▉                                                                   | 1283/9182 [03:43<32:30,  4.05it/s]
 14%|██████████▉                                                                   | 1284/9182 [03:43<32:33,  4.04it/s]
 14%|██████████▉                                                                   | 1285/9182 [03:43<38:25,  3.43it/s]
 14%|██████████▉                                                                   | 1286/9182 [03:44<41:55,  3.14it/s]
 14%|██████████▉                                                                   | 1287/9182 [03:44<37:16,  3.53it/s]
 14%|██████████▉                                                                   | 1288/9182 [03:45<53:47,  2.45it/s]
 14%|██████████▋                                                                 | 1289/9182 [03:45<1:09:30,  1.89it/s]
 14%|██████████▋                                                                 | 1290/9182 [03:46<1:10:16,  1.87it/s]
 14%|██████████▉                                                                   | 1291/9182 [03:46<54:15,  2.42it/s]
 14%|██████████▉                                                                   | 1292/9182 [03:46<54:49,  2.40it/s]
 14%|██████████▉                                                                   | 1293/9182 [03:47<45:54,  2.86it/s]
 14%|██████████▉                                                                   | 1294/9182 [03:47<38:25,  3.42it/s]
 14%|███████████                                                                   | 1301/9182 [03:47<16:45,  7.84it/s]
 14%|███████████                                                                   | 1302/9182 [03:48<23:30,  5.59it/s]
 14%|███████████                                                                   | 1303/9182 [03:48<25:14,  5.20it/s]
 14%|███████████                                                                   | 1304/9182 [03:49<33:14,  3.95it/s]
 14%|███████████                                                                   | 1305/9182 [03:49<29:42,  4.42it/s]
 14%|███████████                                                                   | 1306/9182 [03:49<26:06,  5.03it/s]
 14%|███████████                                                                   | 1307/9182 [03:49<27:37,  4.75it/s]
 14%|███████████                                                                   | 1308/9182 [03:49<34:30,  3.80it/s]
 14%|███████████                                                                   | 1309/9182 [03:50<32:05,  4.09it/s]
 14%|███████████▏                                                                  | 1310/9182 [03:50<33:02,  3.97it/s]
 14%|███████████▏                                                                  | 1311/9182 [03:50<32:37,  4.02it/s]
 14%|███████████▏                                                                  | 1312/9182 [03:50<30:01,  4.37it/s]
 14%|███████████▏                                                                  | 1313/9182 [03:51<43:01,  3.05it/s]
 14%|███████████▏                                                                  | 1314/9182 [03:51<36:24,  3.60it/s]
 14%|███████████▏                                                                  | 1315/9182 [03:51<36:44,  3.57it/s]
 14%|███████████▏                                                                  | 1316/9182 [03:52<36:24,  3.60it/s]
 14%|███████████▏                                                                  | 1318/9182 [03:52<23:15,  5.63it/s]
 14%|███████████▏                                                                  | 1319/9182 [03:52<25:29,  5.14it/s]
 14%|███████████▏                                                                  | 1320/9182 [03:52<22:49,  5.74it/s]
 14%|███████████▏                                                                  | 1322/9182 [03:52<18:05,  7.24it/s]
 14%|███████████▏                                                                  | 1323/9182 [03:53<23:23,  5.60it/s]
 14%|███████████▏                                                                  | 1324/9182 [03:53<24:53,  5.26it/s]
 14%|███████████▎                                                                  | 1325/9182 [03:53<25:10,  5.20it/s]
 14%|███████████▎                                                                  | 1326/9182 [03:53<33:54,  3.86it/s]
 14%|███████████▎                                                                  | 1327/9182 [03:54<37:28,  3.49it/s]
 14%|███████████▎                                                                  | 1329/9182 [03:54<28:49,  4.54it/s]
 14%|███████████▎                                                                  | 1331/9182 [03:54<20:58,  6.24it/s]
 15%|███████████▎                                                                  | 1332/9182 [03:55<36:31,  3.58it/s]
 15%|███████████▎                                                                  | 1333/9182 [03:55<38:31,  3.40it/s]
 15%|███████████▎                                                                  | 1334/9182 [03:56<42:35,  3.07it/s]
 15%|███████████▎                                                                  | 1337/9182 [03:56<29:24,  4.45it/s]
 15%|███████████▎                                                                  | 1338/9182 [03:57<35:58,  3.63it/s]
 15%|███████████▎                                                                  | 1339/9182 [03:57<38:26,  3.40it/s]
 15%|███████████▍                                                                  | 1340/9182 [03:57<40:22,  3.24it/s]
 15%|███████████▍                                                                  | 1341/9182 [03:58<36:39,  3.57it/s]
 15%|███████████▍                                                                  | 1342/9182 [03:58<42:05,  3.10it/s]
 15%|███████████▍                                                                  | 1343/9182 [03:58<34:37,  3.77it/s]
 15%|███████████▍                                                                  | 1344/9182 [03:58<31:47,  4.11it/s]
 15%|███████████▍                                                                  | 1345/9182 [03:59<29:36,  4.41it/s]
 15%|███████████▍                                                                  | 1346/9182 [03:59<38:47,  3.37it/s]
 15%|███████████▍                                                                  | 1348/9182 [03:59<24:32,  5.32it/s]
 15%|███████████▍                                                                  | 1349/9182 [03:59<25:52,  5.05it/s]
 15%|███████████▍                                                                  | 1350/9182 [04:00<31:19,  4.17it/s]
 15%|███████████▍                                                                  | 1351/9182 [04:00<28:21,  4.60it/s]
 15%|███████████▍                                                                  | 1352/9182 [04:00<35:42,  3.65it/s]
 15%|███████████▍                                                                  | 1353/9182 [04:00<32:53,  3.97it/s]
 15%|███████████▌                                                                  | 1354/9182 [04:01<36:27,  3.58it/s]
 15%|███████████▌                                                                  | 1355/9182 [04:01<39:24,  3.31it/s]
 15%|███████████▌                                                                  | 1358/9182 [04:01<22:57,  5.68it/s]
 15%|███████████▌                                                                  | 1360/9182 [04:01<17:56,  7.27it/s]
 15%|███████████▌                                                                  | 1361/9182 [04:02<30:31,  4.27it/s]
 15%|███████████▌                                                                  | 1362/9182 [04:02<29:23,  4.43it/s]
 15%|███████████▌                                                                  | 1363/9182 [04:02<30:36,  4.26it/s]
 15%|███████████▌                                                                  | 1364/9182 [04:03<26:56,  4.83it/s]
 15%|███████████▌                                                                  | 1365/9182 [04:03<25:47,  5.05it/s]
 15%|███████████▌                                                                  | 1366/9182 [04:03<27:33,  4.73it/s]
 15%|███████████▌                                                                  | 1367/9182 [04:03<27:17,  4.77it/s]
 15%|███████████▌                                                                  | 1368/9182 [04:03<27:45,  4.69it/s]
 15%|███████████▋                                                                  | 1369/9182 [04:04<27:50,  4.68it/s]
 15%|███████████▋                                                                  | 1370/9182 [04:04<32:37,  3.99it/s]
 15%|███████████▋                                                                  | 1371/9182 [04:04<37:55,  3.43it/s]
 15%|███████████▋                                                                  | 1372/9182 [04:05<35:14,  3.69it/s]
 15%|███████████▋                                                                  | 1373/9182 [04:05<29:26,  4.42it/s]
 15%|███████████▋                                                                  | 1374/9182 [04:05<28:38,  4.54it/s]
 15%|███████████▋                                                                  | 1375/9182 [04:05<27:16,  4.77it/s]
 15%|███████████▋                                                                  | 1376/9182 [04:05<24:26,  5.32it/s]
 15%|███████████▋                                                                  | 1377/9182 [04:05<22:14,  5.85it/s]
 15%|███████████▋                                                                  | 1380/9182 [04:06<15:58,  8.14it/s]
 15%|███████████▋                                                                  | 1381/9182 [04:06<17:08,  7.59it/s]
 15%|███████████▋                                                                  | 1383/9182 [04:06<18:02,  7.20it/s]
 15%|███████████▊                                                                  | 1385/9182 [04:06<16:49,  7.73it/s]
 15%|███████████▊                                                                  | 1386/9182 [04:07<19:53,  6.53it/s]
 15%|███████████▊                                                                  | 1387/9182 [04:07<18:46,  6.92it/s]
 15%|███████████▊                                                                  | 1388/9182 [04:07<21:24,  6.07it/s]
 15%|███████████▊                                                                  | 1390/9182 [04:07<16:07,  8.05it/s]
 15%|███████████▊                                                                  | 1391/9182 [04:08<23:17,  5.57it/s]
 15%|███████████▊                                                                  | 1392/9182 [04:08<26:32,  4.89it/s]
 15%|███████████▊                                                                  | 1393/9182 [04:08<27:44,  4.68it/s]
 15%|███████████▊                                                                  | 1394/9182 [04:08<24:03,  5.39it/s]
 15%|███████████▊                                                                  | 1395/9182 [04:08<29:01,  4.47it/s]
 15%|███████████▊                                                                  | 1396/9182 [04:09<37:47,  3.43it/s]
 15%|███████████▉                                                                  | 1399/9182 [04:09<21:40,  5.99it/s]

 15%|███████████▉                                                                  | 1400/9182 [04:09<22:24,  5.79it/s]
 15%|███████████▉                                                                  | 1401/9182 [04:10<31:32,  4.11it/s]
 15%|███████████▉                                                                  | 1402/9182 [04:10<31:28,  4.12it/s]
 15%|███████████▉                                                                  | 1403/9182 [04:10<33:01,  3.93it/s]
 15%|███████████▉                                                                  | 1404/9182 [04:10<28:43,  4.51it/s]
 15%|███████████▉                                                                  | 1405/9182 [04:11<26:27,  4.90it/s]
 15%|███████████▉                                                                  | 1406/9182 [04:11<23:59,  5.40it/s]
 15%|███████████▉                                                                  | 1407/9182 [04:11<21:04,  6.15it/s]
 15%|███████████▉                                                                  | 1408/9182 [04:11<31:40,  4.09it/s]
 15%|███████████▉                                                                  | 1412/9182 [04:12<17:08,  7.55it/s]
 15%|████████████                                                                  | 1413/9182 [04:12<31:02,  4.17it/s]
 15%|████████████                                                                  | 1414/9182 [04:13<38:15,  3.38it/s]
 15%|████████████                                                                  | 1415/9182 [04:13<46:22,  2.79it/s]
 15%|████████████                                                                  | 1416/9182 [04:14<43:21,  2.99it/s]
 15%|████████████                                                                  | 1417/9182 [04:14<37:45,  3.43it/s]
 15%|████████████                                                                  | 1418/9182 [04:14<37:33,  3.45it/s]
 15%|████████████                                                                  | 1419/9182 [04:14<35:31,  3.64it/s]
 15%|████████████                                                                  | 1420/9182 [04:15<40:19,  3.21it/s]
 15%|████████████                                                                  | 1421/9182 [04:15<32:38,  3.96it/s]
 15%|████████████                                                                  | 1423/9182 [04:15<29:48,  4.34it/s]
 16%|████████████                                                                  | 1424/9182 [04:15<29:12,  4.43it/s]
 16%|████████████                                                                  | 1425/9182 [04:15<25:28,  5.07it/s]
 16%|████████████▏                                                                 | 1428/9182 [04:16<16:01,  8.07it/s]
 16%|████████████▏                                                                 | 1430/9182 [04:16<17:56,  7.20it/s]
 16%|████████████▏                                                                 | 1435/9182 [04:16<14:09,  9.12it/s]
 16%|████████████▏                                                                 | 1436/9182 [04:17<17:48,  7.25it/s]
 16%|████████████▏                                                                 | 1437/9182 [04:17<19:12,  6.72it/s]
 16%|████████████▏                                                                 | 1438/9182 [04:17<25:01,  5.16it/s]
 16%|████████████▏                                                                 | 1439/9182 [04:18<34:02,  3.79it/s]
 16%|████████████▏                                                                 | 1441/9182 [04:18<28:24,  4.54it/s]
 16%|████████████▏                                                                 | 1442/9182 [04:18<25:56,  4.97it/s]
 16%|████████████▎                                                                 | 1444/9182 [04:19<23:35,  5.47it/s]
 16%|████████████▎                                                                 | 1446/9182 [04:19<18:29,  6.98it/s]
 16%|████████████▎                                                                 | 1447/9182 [04:20<33:29,  3.85it/s]
 16%|████████████▎                                                                 | 1448/9182 [04:20<29:51,  4.32it/s]
 16%|████████████▎                                                                 | 1449/9182 [04:20<35:07,  3.67it/s]
 16%|████████████▎                                                                 | 1450/9182 [04:20<35:27,  3.63it/s]
 16%|████████████▎                                                                 | 1451/9182 [04:21<31:08,  4.14it/s]
 16%|████████████▎                                                                 | 1452/9182 [04:21<29:18,  4.40it/s]
 16%|████████████▎                                                                 | 1453/9182 [04:21<25:31,  5.05it/s]
 16%|████████████▎                                                                 | 1454/9182 [04:21<29:36,  4.35it/s]
 16%|████████████▎                                                                 | 1455/9182 [04:21<33:32,  3.84it/s]
 16%|████████████▎                                                                 | 1456/9182 [04:22<32:48,  3.92it/s]
 16%|████████████▍                                                                 | 1457/9182 [04:22<40:21,  3.19it/s]
 16%|████████████▍                                                                 | 1460/9182 [04:22<24:20,  5.29it/s]
 16%|████████████▍                                                                 | 1461/9182 [04:23<27:21,  4.70it/s]
 16%|████████████▍                                                                 | 1462/9182 [04:23<24:00,  5.36it/s]
 16%|████████████▍                                                                 | 1463/9182 [04:23<26:55,  4.78it/s]
 16%|████████████▍                                                                 | 1464/9182 [04:23<25:32,  5.04it/s]
 16%|████████████▍                                                                 | 1465/9182 [04:24<34:20,  3.75it/s]
 16%|████████████▍                                                                 | 1466/9182 [04:24<35:48,  3.59it/s]
 16%|████████████▍                                                                 | 1467/9182 [04:24<29:20,  4.38it/s]
 16%|████████████▌                                                                 | 1472/9182 [04:24<15:09,  8.48it/s]
 16%|████████████▌                                                                 | 1473/9182 [04:25<19:14,  6.68it/s]
 16%|████████████▌                                                                 | 1474/9182 [04:26<43:11,  2.97it/s]
 16%|████████████▌                                                                 | 1475/9182 [04:26<49:30,  2.59it/s]
 16%|████████████▌                                                                 | 1476/9182 [04:27<48:11,  2.67it/s]
 16%|████████████▌                                                                 | 1477/9182 [04:27<47:29,  2.70it/s]
 16%|████████████▌                                                                 | 1478/9182 [04:28<52:47,  2.43it/s]
 16%|████████████▏                                                               | 1479/9182 [04:28<1:02:48,  2.04it/s]
 16%|████████████▎                                                               | 1480/9182 [04:29<1:00:32,  2.12it/s]
 16%|████████████▌                                                                 | 1481/9182 [04:29<56:38,  2.27it/s]
 16%|████████████▌                                                                 | 1482/9182 [04:29<47:30,  2.70it/s]
 16%|████████████▌                                                                 | 1483/9182 [04:30<43:11,  2.97it/s]
 16%|████████████▋                                                                 | 1488/9182 [04:30<22:22,  5.73it/s]
 16%|████████████▋                                                                 | 1489/9182 [04:30<23:50,  5.38it/s]
 16%|████████████▋                                                                 | 1491/9182 [04:31<23:20,  5.49it/s]
 16%|████████████▋                                                                 | 1492/9182 [04:31<33:42,  3.80it/s]
 16%|████████████▋                                                                 | 1497/9182 [04:31<16:33,  7.74it/s]
 16%|████████████▋                                                                 | 1499/9182 [04:32<25:49,  4.96it/s]
 16%|████████████▊                                                                 | 1501/9182 [04:33<30:22,  4.21it/s]
 16%|████████████▊                                                                 | 1502/9182 [04:33<28:54,  4.43it/s]
 16%|████████████▊                                                                 | 1503/9182 [04:34<34:44,  3.68it/s]
 16%|████████████▊                                                                 | 1505/9182 [04:34<30:15,  4.23it/s]
 16%|████████████▊                                                                 | 1506/9182 [04:34<30:44,  4.16it/s]
 16%|████████████▊                                                                 | 1509/9182 [04:34<21:21,  5.99it/s]
 16%|████████████▊                                                                 | 1511/9182 [04:35<20:01,  6.39it/s]
 16%|████████████▊                                                                 | 1512/9182 [04:35<26:10,  4.88it/s]
 16%|████████████▊                                                                 | 1514/9182 [04:35<20:38,  6.19it/s]
 16%|████████████▊                                                                 | 1515/9182 [04:36<39:44,  3.21it/s]
 17%|████████████▉                                                                 | 1516/9182 [04:37<53:35,  2.38it/s]
 17%|████████████▉                                                                 | 1517/9182 [04:37<48:09,  2.65it/s]
 17%|████████████▉                                                                 | 1521/9182 [04:38<32:46,  3.90it/s]
 17%|████████████▉                                                                 | 1522/9182 [04:38<32:54,  3.88it/s]
 17%|████████████▉                                                                 | 1523/9182 [04:39<37:46,  3.38it/s]
 17%|████████████▉                                                                 | 1524/9182 [04:39<33:50,  3.77it/s]
 17%|████████████▉                                                                 | 1525/9182 [04:39<34:30,  3.70it/s]
 17%|████████████▉                                                                 | 1526/9182 [04:40<37:20,  3.42it/s]
 17%|████████████▉                                                                 | 1527/9182 [04:40<33:54,  3.76it/s]
 17%|████████████▉                                                                 | 1528/9182 [04:40<38:41,  3.30it/s]
 17%|████████████▉                                                                 | 1529/9182 [04:40<35:27,  3.60it/s]
 17%|████████████▉                                                                 | 1530/9182 [04:41<37:52,  3.37it/s]
 17%|█████████████                                                                 | 1531/9182 [04:41<34:16,  3.72it/s]
 17%|█████████████                                                                 | 1534/9182 [04:41<18:15,  6.98it/s]
 17%|█████████████                                                                 | 1536/9182 [04:42<26:57,  4.73it/s]
 17%|█████████████                                                                 | 1539/9182 [04:42<17:22,  7.33it/s]
 17%|█████████████                                                                 | 1541/9182 [04:42<26:15,  4.85it/s]
 17%|█████████████                                                                 | 1543/9182 [04:43<27:46,  4.58it/s]
 17%|█████████████                                                                 | 1544/9182 [04:43<34:01,  3.74it/s]
 17%|█████████████                                                                 | 1545/9182 [04:44<34:17,  3.71it/s]
 17%|█████████████▏                                                                | 1546/9182 [04:44<41:52,  3.04it/s]
 17%|█████████████▏                                                                | 1548/9182 [04:45<31:57,  3.98it/s]
 17%|█████████████▏                                                                | 1549/9182 [04:45<36:44,  3.46it/s]
 17%|█████████████▏                                                                | 1550/9182 [04:45<34:32,  3.68it/s]
 17%|█████████████▏                                                                | 1554/9182 [04:45<18:04,  7.04it/s]
 17%|█████████████▏                                                                | 1555/9182 [04:46<23:18,  5.45it/s]
 17%|█████████████▏                                                                | 1556/9182 [04:46<22:49,  5.57it/s]
 17%|█████████████▏                                                                | 1559/9182 [04:46<20:57,  6.06it/s]
 17%|█████████████▎                                                                | 1563/9182 [04:47<15:31,  8.18it/s]
 17%|█████████████▎                                                                | 1565/9182 [04:47<16:01,  7.92it/s]
 17%|█████████████▎                                                                | 1566/9182 [04:47<22:00,  5.77it/s]
 17%|█████████████▎                                                                | 1567/9182 [04:48<25:35,  4.96it/s]
 17%|█████████████▎                                                                | 1568/9182 [04:49<49:20,  2.57it/s]
 17%|█████████████▎                                                                | 1569/9182 [04:49<42:54,  2.96it/s]
 17%|█████████████▎                                                                | 1570/9182 [04:49<41:07,  3.08it/s]
 17%|█████████████▎                                                                | 1574/9182 [04:50<19:27,  6.52it/s]
 17%|█████████████▍                                                                | 1576/9182 [04:50<29:11,  4.34it/s]
 17%|█████████████▍                                                                | 1577/9182 [04:50<28:41,  4.42it/s]
 17%|█████████████▍                                                                | 1578/9182 [04:51<30:20,  4.18it/s]
 17%|█████████████▍                                                                | 1579/9182 [04:51<29:03,  4.36it/s]
 17%|█████████████▍                                                                | 1580/9182 [04:51<35:00,  3.62it/s]
 17%|█████████████▍                                                                | 1581/9182 [04:51<30:02,  4.22it/s]
 17%|█████████████▍                                                                | 1585/9182 [04:52<21:02,  6.02it/s]
 17%|█████████████▍                                                                | 1586/9182 [04:52<30:39,  4.13it/s]
 17%|█████████████▍                                                                | 1588/9182 [04:53<30:40,  4.13it/s]
 17%|█████████████▍                                                                | 1589/9182 [04:53<31:06,  4.07it/s]
 17%|█████████████▌                                                                | 1590/9182 [04:54<29:30,  4.29it/s]
 17%|█████████████▌                                                                | 1591/9182 [04:54<41:35,  3.04it/s]
 17%|█████████████▌                                                                | 1592/9182 [04:54<40:01,  3.16it/s]
 17%|█████████████▌                                                                | 1593/9182 [04:55<37:22,  3.38it/s]
 17%|█████████████▌                                                                | 1594/9182 [04:55<32:45,  3.86it/s]
 17%|█████████████▌                                                                | 1595/9182 [04:55<31:41,  3.99it/s]

 17%|█████████████▌                                                                | 1596/9182 [04:55<29:35,  4.27it/s]
 17%|█████████████▌                                                                | 1597/9182 [04:55<26:14,  4.82it/s]
 17%|█████████████▌                                                                | 1598/9182 [04:56<30:12,  4.18it/s]
 17%|█████████████▌                                                                | 1602/9182 [04:56<14:22,  8.79it/s]
 17%|█████████████▋                                                                | 1604/9182 [04:57<23:51,  5.29it/s]
 17%|█████████████▋                                                                | 1605/9182 [04:57<24:18,  5.19it/s]
 17%|█████████████▋                                                                | 1606/9182 [04:58<39:26,  3.20it/s]
 18%|█████████████▋                                                                | 1607/9182 [04:58<36:04,  3.50it/s]
 18%|█████████████▋                                                                | 1608/9182 [04:58<34:32,  3.65it/s]
 18%|█████████████▋                                                                | 1609/9182 [04:58<39:06,  3.23it/s]
 18%|█████████████▋                                                                | 1610/9182 [04:59<34:33,  3.65it/s]
 18%|█████████████▋                                                                | 1611/9182 [04:59<39:52,  3.17it/s]
 18%|█████████████▋                                                                | 1612/9182 [04:59<38:07,  3.31it/s]
 18%|█████████████▋                                                                | 1613/9182 [04:59<32:06,  3.93it/s]
 18%|█████████████▋                                                                | 1614/9182 [04:59<26:38,  4.73it/s]
 18%|█████████████▋                                                                | 1617/9182 [05:00<23:56,  5.27it/s]
 18%|█████████████▊                                                                | 1619/9182 [05:00<20:26,  6.17it/s]
 18%|█████████████▊                                                                | 1620/9182 [05:00<23:19,  5.40it/s]
 18%|█████████████▊                                                                | 1622/9182 [05:01<21:34,  5.84it/s]
 18%|█████████████▊                                                                | 1623/9182 [05:01<27:11,  4.63it/s]
 18%|█████████████▊                                                                | 1624/9182 [05:01<29:48,  4.22it/s]
 18%|█████████████▊                                                                | 1625/9182 [05:02<32:30,  3.88it/s]
 18%|█████████████▊                                                                | 1626/9182 [05:02<29:12,  4.31it/s]
 18%|█████████████▊                                                                | 1627/9182 [05:02<32:46,  3.84it/s]
 18%|█████████████▊                                                                | 1628/9182 [05:03<33:16,  3.78it/s]
 18%|█████████████▊                                                                | 1629/9182 [05:03<32:42,  3.85it/s]
 18%|█████████████▊                                                                | 1630/9182 [05:03<29:31,  4.26it/s]
 18%|█████████████▊                                                                | 1632/9182 [05:03<19:24,  6.48it/s]
 18%|█████████████▊                                                                | 1633/9182 [05:04<25:11,  4.99it/s]
 18%|█████████████▉                                                                | 1634/9182 [05:04<26:55,  4.67it/s]
 18%|█████████████▉                                                                | 1635/9182 [05:05<47:06,  2.67it/s]
 18%|█████████████▉                                                                | 1636/9182 [05:05<43:43,  2.88it/s]
 18%|█████████████▉                                                                | 1637/9182 [05:05<43:59,  2.86it/s]
 18%|█████████████▉                                                                | 1638/9182 [05:05<40:14,  3.12it/s]
 18%|█████████████▉                                                                | 1643/9182 [05:06<19:18,  6.51it/s]
 18%|█████████████▉                                                                | 1644/9182 [05:06<22:04,  5.69it/s]
 18%|█████████████▉                                                                | 1647/9182 [05:06<16:52,  7.45it/s]
 18%|██████████████                                                                | 1649/9182 [05:07<16:06,  7.79it/s]
 18%|██████████████                                                                | 1650/9182 [05:07<29:15,  4.29it/s]
 18%|██████████████                                                                | 1651/9182 [05:08<31:47,  3.95it/s]
 18%|██████████████                                                                | 1652/9182 [05:08<45:26,  2.76it/s]
 18%|██████████████                                                                | 1653/9182 [05:09<42:53,  2.93it/s]
 18%|██████████████                                                                | 1654/9182 [05:09<38:05,  3.29it/s]
 18%|██████████████                                                                | 1655/9182 [05:09<31:45,  3.95it/s]
 18%|██████████████                                                                | 1656/9182 [05:09<28:08,  4.46it/s]
 18%|██████████████                                                                | 1657/9182 [05:10<35:42,  3.51it/s]
 18%|██████████████                                                                | 1658/9182 [05:10<32:28,  3.86it/s]
 18%|██████████████                                                                | 1659/9182 [05:10<33:18,  3.76it/s]
 18%|██████████████                                                                | 1660/9182 [05:10<32:22,  3.87it/s]
 18%|██████████████                                                                | 1661/9182 [05:11<34:25,  3.64it/s]
 18%|██████████████                                                                | 1662/9182 [05:11<31:39,  3.96it/s]
 18%|██████████████▏                                                               | 1663/9182 [05:11<29:53,  4.19it/s]
 18%|██████████████▏                                                               | 1664/9182 [05:11<28:01,  4.47it/s]
 18%|██████████████▏                                                               | 1665/9182 [05:11<25:36,  4.89it/s]
 18%|██████████████▏                                                               | 1666/9182 [05:11<21:53,  5.72it/s]
 18%|██████████████▏                                                               | 1667/9182 [05:12<23:42,  5.28it/s]
 18%|██████████████▏                                                               | 1668/9182 [05:12<24:13,  5.17it/s]
 18%|██████████████▏                                                               | 1669/9182 [05:12<24:45,  5.06it/s]
 18%|██████████████▏                                                               | 1670/9182 [05:12<25:53,  4.84it/s]
 18%|██████████████▏                                                               | 1671/9182 [05:13<33:10,  3.77it/s]
 18%|██████████████▏                                                               | 1672/9182 [05:13<29:10,  4.29it/s]
 18%|██████████████▏                                                               | 1673/9182 [05:13<24:16,  5.16it/s]
 18%|██████████████▏                                                               | 1674/9182 [05:13<22:36,  5.53it/s]
 18%|██████████████▏                                                               | 1675/9182 [05:13<32:13,  3.88it/s]
 18%|██████████████▏                                                               | 1676/9182 [05:14<26:52,  4.65it/s]
 18%|██████████████▏                                                               | 1677/9182 [05:14<23:44,  5.27it/s]
 18%|██████████████▎                                                               | 1678/9182 [05:14<33:35,  3.72it/s]
 18%|██████████████▎                                                               | 1679/9182 [05:14<30:27,  4.10it/s]
 18%|██████████████▎                                                               | 1680/9182 [05:15<26:57,  4.64it/s]
 18%|██████████████▎                                                               | 1681/9182 [05:15<23:26,  5.33it/s]
 18%|██████████████▎                                                               | 1682/9182 [05:15<27:47,  4.50it/s]
 18%|██████████████▎                                                               | 1683/9182 [05:15<29:59,  4.17it/s]
 18%|██████████████▎                                                               | 1686/9182 [05:16<22:17,  5.60it/s]
 18%|██████████████▎                                                               | 1687/9182 [05:16<26:19,  4.74it/s]
 18%|██████████████▎                                                               | 1688/9182 [05:16<26:27,  4.72it/s]
 18%|██████████████▎                                                               | 1689/9182 [05:16<28:05,  4.45it/s]
 18%|██████████████▎                                                               | 1690/9182 [05:17<25:32,  4.89it/s]
 18%|██████████████▎                                                               | 1692/9182 [05:17<17:54,  6.97it/s]
 18%|██████████████▍                                                               | 1694/9182 [05:17<14:25,  8.65it/s]
 18%|██████████████▍                                                               | 1696/9182 [05:17<18:13,  6.85it/s]
 18%|██████████████▍                                                               | 1697/9182 [05:17<18:35,  6.71it/s]
 18%|██████████████▍                                                               | 1698/9182 [05:18<25:50,  4.83it/s]
 19%|██████████████▍                                                               | 1699/9182 [05:19<46:19,  2.69it/s]
 19%|██████████████▍                                                               | 1700/9182 [05:19<40:57,  3.04it/s]
 19%|██████████████▍                                                               | 1704/9182 [05:19<22:15,  5.60it/s]
 19%|██████████████▍                                                               | 1706/9182 [05:19<18:04,  6.89it/s]
 19%|██████████████▌                                                               | 1707/9182 [05:20<26:36,  4.68it/s]
 19%|██████████████▌                                                               | 1710/9182 [05:20<17:34,  7.09it/s]
 19%|██████████████▌                                                               | 1712/9182 [05:21<30:55,  4.03it/s]
 19%|██████████████▌                                                               | 1716/9182 [05:21<20:08,  6.18it/s]
 19%|██████████████▌                                                               | 1718/9182 [05:22<30:26,  4.09it/s]
 19%|██████████████▌                                                               | 1719/9182 [05:22<29:32,  4.21it/s]
 19%|██████████████▌                                                               | 1720/9182 [05:23<31:18,  3.97it/s]
 19%|██████████████▌                                                               | 1721/9182 [05:23<30:41,  4.05it/s]
 19%|██████████████▋                                                               | 1722/9182 [05:23<27:04,  4.59it/s]
 19%|██████████████▋                                                               | 1723/9182 [05:24<31:22,  3.96it/s]
 19%|██████████████▋                                                               | 1724/9182 [05:24<34:58,  3.55it/s]
 19%|██████████████▋                                                               | 1725/9182 [05:24<32:56,  3.77it/s]
 19%|██████████████▋                                                               | 1726/9182 [05:24<30:04,  4.13it/s]
 19%|██████████████▋                                                               | 1729/9182 [05:24<16:43,  7.43it/s]
 19%|██████████████▋                                                               | 1731/9182 [05:25<14:44,  8.43it/s]
 19%|██████████████▋                                                               | 1733/9182 [05:25<16:59,  7.31it/s]
 19%|██████████████▋                                                               | 1735/9182 [05:25<14:08,  8.78it/s]
 19%|██████████████▊                                                               | 1737/9182 [05:25<15:03,  8.24it/s]
 19%|██████████████▊                                                               | 1738/9182 [05:26<23:34,  5.26it/s]
 19%|██████████████▊                                                               | 1739/9182 [05:26<31:33,  3.93it/s]
 19%|██████████████▊                                                               | 1740/9182 [05:27<37:04,  3.34it/s]
 19%|██████████████▊                                                               | 1741/9182 [05:27<39:50,  3.11it/s]
 19%|██████████████▊                                                               | 1743/9182 [05:27<27:23,  4.53it/s]
 19%|██████████████▊                                                               | 1744/9182 [05:27<26:15,  4.72it/s]
 19%|██████████████▊                                                               | 1748/9182 [05:29<30:33,  4.06it/s]
 19%|██████████████▊                                                               | 1749/9182 [05:29<28:58,  4.28it/s]
 19%|██████████████▊                                                               | 1750/9182 [05:29<28:07,  4.40it/s]
 19%|██████████████▊                                                               | 1751/9182 [05:29<25:49,  4.80it/s]
 19%|██████████████▉                                                               | 1752/9182 [05:29<22:52,  5.41it/s]
 19%|██████████████▉                                                               | 1753/9182 [05:29<21:16,  5.82it/s]
 19%|██████████████▉                                                               | 1754/9182 [05:30<25:52,  4.79it/s]
 19%|██████████████▉                                                               | 1755/9182 [05:30<22:56,  5.39it/s]
 19%|██████████████▉                                                               | 1756/9182 [05:30<21:01,  5.89it/s]
 19%|██████████████▉                                                               | 1757/9182 [05:30<23:27,  5.28it/s]
 19%|██████████████▉                                                               | 1758/9182 [05:31<25:12,  4.91it/s]
 19%|██████████████▉                                                               | 1759/9182 [05:31<37:57,  3.26it/s]
 19%|██████████████▉                                                               | 1760/9182 [05:31<35:36,  3.47it/s]
 19%|██████████████▉                                                               | 1761/9182 [05:32<38:55,  3.18it/s]
 19%|██████████████▉                                                               | 1762/9182 [05:32<36:17,  3.41it/s]
 19%|██████████████▉                                                               | 1763/9182 [05:32<37:40,  3.28it/s]
 19%|███████████████                                                               | 1769/9182 [05:32<13:02,  9.47it/s]
 19%|███████████████                                                               | 1771/9182 [05:33<19:43,  6.26it/s]
 19%|███████████████                                                               | 1773/9182 [05:34<30:17,  4.08it/s]
 19%|███████████████                                                               | 1774/9182 [05:34<30:26,  4.06it/s]
 19%|███████████████                                                               | 1775/9182 [05:35<30:52,  4.00it/s]
 19%|███████████████                                                               | 1776/9182 [05:35<36:29,  3.38it/s]

 19%|███████████████                                                               | 1777/9182 [05:35<34:39,  3.56it/s]
 19%|███████████████                                                               | 1778/9182 [05:36<35:01,  3.52it/s]
 19%|███████████████                                                               | 1779/9182 [05:36<35:30,  3.47it/s]
 19%|███████████████                                                               | 1780/9182 [05:36<30:51,  4.00it/s]
 19%|███████████████▏                                                              | 1781/9182 [05:36<34:11,  3.61it/s]
 19%|███████████████▏                                                              | 1782/9182 [05:36<28:30,  4.33it/s]
 19%|███████████████▏                                                              | 1786/9182 [05:37<16:31,  7.46it/s]
 19%|███████████████▏                                                              | 1787/9182 [05:37<18:43,  6.58it/s]
 19%|███████████████▏                                                              | 1788/9182 [05:37<19:54,  6.19it/s]
 19%|███████████████▏                                                              | 1789/9182 [05:37<23:05,  5.34it/s]
 19%|███████████████▏                                                              | 1790/9182 [05:38<34:38,  3.56it/s]
 20%|███████████████▏                                                              | 1791/9182 [05:38<36:18,  3.39it/s]
 20%|███████████████▏                                                              | 1792/9182 [05:39<42:33,  2.89it/s]
 20%|███████████████▏                                                              | 1793/9182 [05:39<34:59,  3.52it/s]
 20%|███████████████▏                                                              | 1794/9182 [05:39<32:00,  3.85it/s]
 20%|███████████████▏                                                              | 1795/9182 [05:40<39:51,  3.09it/s]
 20%|███████████████▎                                                              | 1796/9182 [05:40<36:04,  3.41it/s]
 20%|██████████████▊                                                             | 1797/9182 [05:41<1:02:45,  1.96it/s]
 20%|███████████████▎                                                              | 1798/9182 [05:41<50:04,  2.46it/s]
 20%|███████████████▎                                                              | 1799/9182 [05:41<40:16,  3.06it/s]
 20%|███████████████▎                                                              | 1800/9182 [05:41<35:14,  3.49it/s]
 20%|███████████████▎                                                              | 1801/9182 [05:42<49:35,  2.48it/s]
 20%|███████████████▎                                                              | 1802/9182 [05:42<44:00,  2.79it/s]
 20%|███████████████▎                                                              | 1803/9182 [05:42<35:06,  3.50it/s]
 20%|███████████████▎                                                              | 1805/9182 [05:43<30:31,  4.03it/s]
 20%|███████████████▎                                                              | 1806/9182 [05:43<26:10,  4.70it/s]
 20%|███████████████▎                                                              | 1807/9182 [05:43<25:22,  4.85it/s]
 20%|███████████████▎                                                              | 1808/9182 [05:43<30:02,  4.09it/s]
 20%|███████████████▎                                                              | 1809/9182 [05:44<29:41,  4.14it/s]
 20%|███████████████▍                                                              | 1810/9182 [05:44<29:56,  4.10it/s]
 20%|███████████████▍                                                              | 1811/9182 [05:44<27:34,  4.45it/s]
 20%|███████████████▍                                                              | 1813/9182 [05:44<20:58,  5.86it/s]
 20%|███████████████▍                                                              | 1816/9182 [05:44<12:58,  9.46it/s]
 20%|███████████████▍                                                              | 1818/9182 [05:45<15:33,  7.89it/s]
 20%|███████████████▍                                                              | 1820/9182 [05:45<14:15,  8.61it/s]
 20%|███████████████▍                                                              | 1822/9182 [05:45<14:34,  8.42it/s]
 20%|███████████████▍                                                              | 1823/9182 [05:46<22:06,  5.55it/s]
 20%|███████████████▍                                                              | 1824/9182 [05:46<22:01,  5.57it/s]
 20%|███████████████▌                                                              | 1825/9182 [05:46<34:20,  3.57it/s]
 20%|███████████████▌                                                              | 1826/9182 [05:47<31:38,  3.87it/s]
 20%|███████████████▌                                                              | 1827/9182 [05:47<42:32,  2.88it/s]
 20%|███████████████▌                                                              | 1828/9182 [05:47<35:22,  3.47it/s]
 20%|███████████████▌                                                              | 1829/9182 [05:48<40:31,  3.02it/s]
 20%|███████████████▌                                                              | 1830/9182 [05:48<34:34,  3.54it/s]
 20%|███████████████▌                                                              | 1831/9182 [05:48<31:59,  3.83it/s]
 20%|███████████████▌                                                              | 1832/9182 [05:49<35:06,  3.49it/s]
 20%|███████████████▌                                                              | 1833/9182 [05:49<30:22,  4.03it/s]
 20%|███████████████▌                                                              | 1834/9182 [05:49<27:21,  4.48it/s]
 20%|███████████████▌                                                              | 1835/9182 [05:49<24:27,  5.01it/s]
 20%|███████████████▌                                                              | 1836/9182 [05:49<29:54,  4.09it/s]
 20%|███████████████▌                                                              | 1837/9182 [05:50<32:50,  3.73it/s]
 20%|███████████████▌                                                              | 1838/9182 [05:50<38:43,  3.16it/s]
 20%|███████████████▌                                                              | 1839/9182 [05:50<32:08,  3.81it/s]
 20%|███████████████▋                                                              | 1840/9182 [05:50<27:31,  4.45it/s]
 20%|███████████████▋                                                              | 1847/9182 [05:51<15:05,  8.10it/s]
 20%|███████████████▋                                                              | 1848/9182 [05:51<16:11,  7.55it/s]
 20%|███████████████▋                                                              | 1849/9182 [05:52<37:36,  3.25it/s]
 20%|███████████████▋                                                              | 1852/9182 [05:53<27:51,  4.38it/s]
 20%|███████████████▋                                                              | 1853/9182 [05:53<26:07,  4.68it/s]
 20%|███████████████▋                                                              | 1854/9182 [05:53<25:50,  4.73it/s]
 20%|███████████████▊                                                              | 1855/9182 [05:53<23:36,  5.17it/s]
 20%|███████████████▊                                                              | 1856/9182 [05:53<28:52,  4.23it/s]
 20%|███████████████▊                                                              | 1857/9182 [05:54<42:43,  2.86it/s]
 20%|███████████████▊                                                              | 1858/9182 [05:55<55:10,  2.21it/s]
 20%|███████████████▊                                                              | 1859/9182 [05:55<43:31,  2.80it/s]
 20%|███████████████▊                                                              | 1863/9182 [05:55<18:59,  6.43it/s]
 20%|███████████████▊                                                              | 1865/9182 [05:56<23:18,  5.23it/s]
 20%|███████████████▊                                                              | 1867/9182 [05:56<19:25,  6.28it/s]
 20%|███████████████▉                                                              | 1869/9182 [05:56<17:21,  7.02it/s]
 20%|███████████████▉                                                              | 1871/9182 [05:57<30:20,  4.01it/s]
 20%|███████████████▉                                                              | 1872/9182 [05:58<34:57,  3.48it/s]
 20%|███████████████▉                                                              | 1873/9182 [05:58<39:03,  3.12it/s]
 20%|███████████████▉                                                              | 1875/9182 [05:59<52:43,  2.31it/s]
 20%|███████████████▉                                                              | 1879/9182 [06:00<32:50,  3.71it/s]
 20%|███████████████▉                                                              | 1880/9182 [06:00<30:16,  4.02it/s]
 20%|███████████████▉                                                              | 1881/9182 [06:01<39:32,  3.08it/s]
 20%|███████████████▉                                                              | 1882/9182 [06:01<36:08,  3.37it/s]
 21%|███████████████▉                                                              | 1883/9182 [06:01<32:06,  3.79it/s]
 21%|████████████████                                                              | 1891/9182 [06:01<12:05, 10.05it/s]
 21%|████████████████                                                              | 1893/9182 [06:01<12:01, 10.10it/s]
 21%|████████████████                                                              | 1895/9182 [06:02<13:35,  8.93it/s]
 21%|████████████████                                                              | 1897/9182 [06:02<12:04, 10.05it/s]
 21%|████████████████▏                                                             | 1899/9182 [06:02<16:15,  7.47it/s]
 21%|████████████████▏                                                             | 1900/9182 [06:03<32:34,  3.73it/s]
 21%|████████████████▏                                                             | 1901/9182 [06:04<34:59,  3.47it/s]
 21%|████████████████▏                                                             | 1903/9182 [06:04<31:30,  3.85it/s]
 21%|████████████████▏                                                             | 1904/9182 [06:04<30:57,  3.92it/s]
 21%|████████████████▏                                                             | 1905/9182 [06:05<28:26,  4.26it/s]
 21%|████████████████▏                                                             | 1906/9182 [06:05<31:41,  3.83it/s]
 21%|████████████████▏                                                             | 1907/9182 [06:05<28:48,  4.21it/s]
 21%|████████████████▏                                                             | 1908/9182 [06:05<28:39,  4.23it/s]
 21%|████████████████▏                                                             | 1911/9182 [06:05<17:39,  6.86it/s]
 21%|████████████████▏                                                             | 1912/9182 [06:06<17:32,  6.91it/s]
 21%|████████████████▎                                                             | 1916/9182 [06:06<22:46,  5.32it/s]
 21%|████████████████▎                                                             | 1917/9182 [06:07<23:03,  5.25it/s]
 21%|████████████████▎                                                             | 1922/9182 [06:07<13:06,  9.23it/s]
 21%|████████████████▎                                                             | 1924/9182 [06:08<26:14,  4.61it/s]
 21%|████████████████▎                                                             | 1925/9182 [06:08<24:31,  4.93it/s]
 21%|████████████████▎                                                             | 1926/9182 [06:08<24:18,  4.97it/s]
 21%|████████████████▍                                                             | 1928/9182 [06:08<19:35,  6.17it/s]
 21%|████████████████▍                                                             | 1930/9182 [06:09<18:45,  6.44it/s]
 21%|████████████████▍                                                             | 1932/9182 [06:09<21:25,  5.64it/s]
 21%|████████████████▍                                                             | 1933/9182 [06:10<24:07,  5.01it/s]
 21%|████████████████▍                                                             | 1934/9182 [06:10<29:39,  4.07it/s]
 21%|████████████████▍                                                             | 1935/9182 [06:10<29:09,  4.14it/s]
 21%|████████████████▍                                                             | 1936/9182 [06:10<29:18,  4.12it/s]
 21%|████████████████▍                                                             | 1937/9182 [06:11<35:50,  3.37it/s]
 21%|████████████████▍                                                             | 1941/9182 [06:11<19:28,  6.20it/s]
 21%|████████████████▌                                                             | 1943/9182 [06:12<22:57,  5.26it/s]
 21%|████████████████▌                                                             | 1944/9182 [06:12<24:26,  4.94it/s]
 21%|████████████████▌                                                             | 1945/9182 [06:13<27:21,  4.41it/s]
 21%|████████████████▌                                                             | 1946/9182 [06:13<31:58,  3.77it/s]
 21%|████████████████▌                                                             | 1947/9182 [06:13<31:27,  3.83it/s]
 21%|████████████████▌                                                             | 1948/9182 [06:13<32:52,  3.67it/s]
 21%|████████████████▌                                                             | 1949/9182 [06:13<34:15,  3.52it/s]
 21%|████████████████▌                                                             | 1950/9182 [06:14<29:28,  4.09it/s]
 21%|████████████████▌                                                             | 1955/9182 [06:14<15:57,  7.55it/s]
 21%|████████████████▌                                                             | 1956/9182 [06:14<17:04,  7.05it/s]
 21%|████████████████▌                                                             | 1957/9182 [06:15<23:56,  5.03it/s]
 21%|████████████████▋                                                             | 1958/9182 [06:15<33:09,  3.63it/s]
 21%|████████████████▋                                                             | 1959/9182 [06:16<44:20,  2.72it/s]
 21%|████████████████▋                                                             | 1964/9182 [06:16<21:40,  5.55it/s]
 21%|████████████████▋                                                             | 1965/9182 [06:17<24:26,  4.92it/s]
 21%|████████████████▋                                                             | 1966/9182 [06:17<23:53,  5.04it/s]
 21%|████████████████▋                                                             | 1967/9182 [06:17<23:37,  5.09it/s]
 21%|████████████████▋                                                             | 1968/9182 [06:17<25:47,  4.66it/s]
 21%|████████████████▋                                                             | 1971/9182 [06:17<15:09,  7.93it/s]
 21%|████████████████▊                                                             | 1973/9182 [06:17<15:05,  7.96it/s]
 22%|████████████████▊                                                             | 1975/9182 [06:18<14:28,  8.30it/s]
 22%|████████████████▊                                                             | 1977/9182 [06:18<11:53, 10.10it/s]
 22%|████████████████▊                                                             | 1979/9182 [06:18<17:29,  6.86it/s]
 22%|████████████████▊                                                             | 1981/9182 [06:20<37:31,  3.20it/s]

 22%|████████████████▊                                                             | 1982/9182 [06:20<40:49,  2.94it/s]
 22%|████████████████▊                                                             | 1983/9182 [06:21<49:43,  2.41it/s]
 22%|████████████████▊                                                             | 1984/9182 [06:21<41:49,  2.87it/s]
 22%|████████████████▊                                                             | 1985/9182 [06:21<37:30,  3.20it/s]
 22%|████████████████▊                                                             | 1986/9182 [06:21<35:46,  3.35it/s]
 22%|████████████████▉                                                             | 1987/9182 [06:22<31:55,  3.76it/s]
 22%|████████████████▉                                                             | 1988/9182 [06:22<30:44,  3.90it/s]
 22%|████████████████▉                                                             | 1989/9182 [06:22<33:37,  3.57it/s]
 22%|████████████████▉                                                             | 1991/9182 [06:22<21:50,  5.49it/s]
 22%|████████████████▉                                                             | 1992/9182 [06:23<22:43,  5.27it/s]
 22%|████████████████▉                                                             | 1993/9182 [06:23<23:26,  5.11it/s]
 22%|████████████████▉                                                             | 1994/9182 [06:23<21:00,  5.70it/s]
 22%|████████████████▉                                                             | 1995/9182 [06:23<23:36,  5.07it/s]
 22%|████████████████▉                                                             | 1996/9182 [06:23<21:32,  5.56it/s]
 22%|████████████████▉                                                             | 1998/9182 [06:24<24:26,  4.90it/s]
 22%|████████████████▉                                                             | 2000/9182 [06:24<17:33,  6.82it/s]
 22%|████████████████▉                                                             | 2001/9182 [06:24<16:43,  7.15it/s]
 22%|█████████████████                                                             | 2002/9182 [06:24<18:26,  6.49it/s]
 22%|█████████████████                                                             | 2003/9182 [06:25<25:41,  4.66it/s]
 22%|█████████████████                                                             | 2004/9182 [06:25<26:03,  4.59it/s]
 22%|█████████████████                                                             | 2005/9182 [06:25<30:01,  3.98it/s]
 22%|█████████████████                                                             | 2006/9182 [06:26<33:16,  3.59it/s]
 22%|█████████████████                                                             | 2007/9182 [06:26<57:28,  2.08it/s]
 22%|█████████████████                                                             | 2008/9182 [06:27<51:16,  2.33it/s]
 22%|█████████████████                                                             | 2009/9182 [06:27<42:37,  2.80it/s]
 22%|█████████████████                                                             | 2010/9182 [06:28<44:33,  2.68it/s]
 22%|█████████████████                                                             | 2011/9182 [06:28<47:35,  2.51it/s]
 22%|█████████████████▏                                                            | 2016/9182 [06:28<17:35,  6.79it/s]
 22%|█████████████████▏                                                            | 2018/9182 [06:28<19:41,  6.07it/s]
 22%|█████████████████▏                                                            | 2020/9182 [06:29<17:26,  6.85it/s]
 22%|█████████████████▏                                                            | 2022/9182 [06:29<20:35,  5.80it/s]
 22%|█████████████████▏                                                            | 2023/9182 [06:30<34:43,  3.44it/s]
 22%|█████████████████▏                                                            | 2024/9182 [06:31<46:16,  2.58it/s]
 22%|█████████████████▏                                                            | 2025/9182 [06:31<45:27,  2.62it/s]
 22%|█████████████████▏                                                            | 2026/9182 [06:31<42:24,  2.81it/s]
 22%|█████████████████▏                                                            | 2027/9182 [06:32<39:04,  3.05it/s]
 22%|█████████████████▏                                                            | 2028/9182 [06:32<36:52,  3.23it/s]
 22%|█████████████████▏                                                            | 2029/9182 [06:32<36:13,  3.29it/s]
 22%|█████████████████▏                                                            | 2030/9182 [06:33<38:19,  3.11it/s]
 22%|█████████████████▎                                                            | 2031/9182 [06:33<32:30,  3.67it/s]
 22%|█████████████████▎                                                            | 2032/9182 [06:33<37:50,  3.15it/s]
 22%|█████████████████▎                                                            | 2038/9182 [06:33<15:59,  7.45it/s]
 22%|█████████████████▎                                                            | 2039/9182 [06:34<23:27,  5.07it/s]
 22%|█████████████████▎                                                            | 2040/9182 [06:34<22:00,  5.41it/s]
 22%|█████████████████▎                                                            | 2044/9182 [06:34<14:00,  8.49it/s]
 22%|█████████████████▍                                                            | 2046/9182 [06:36<28:35,  4.16it/s]
 22%|█████████████████▍                                                            | 2047/9182 [06:36<28:39,  4.15it/s]
 22%|█████████████████▍                                                            | 2048/9182 [06:36<25:52,  4.59it/s]
 22%|█████████████████▍                                                            | 2050/9182 [06:36<19:23,  6.13it/s]
 22%|█████████████████▍                                                            | 2053/9182 [06:36<15:34,  7.63it/s]
 22%|█████████████████▍                                                            | 2055/9182 [06:36<16:05,  7.38it/s]
 22%|█████████████████▍                                                            | 2056/9182 [06:37<16:59,  6.99it/s]
 22%|█████████████████▌                                                            | 2061/9182 [06:37<16:50,  7.04it/s]
 22%|█████████████████▌                                                            | 2062/9182 [06:38<19:36,  6.05it/s]
 22%|█████████████████▌                                                            | 2063/9182 [06:38<27:55,  4.25it/s]
 22%|█████████████████▌                                                            | 2064/9182 [06:39<29:25,  4.03it/s]
 22%|█████████████████▌                                                            | 2065/9182 [06:39<28:36,  4.15it/s]
 23%|█████████████████▌                                                            | 2066/9182 [06:39<34:22,  3.45it/s]
 23%|█████████████████▌                                                            | 2067/9182 [06:39<31:46,  3.73it/s]
 23%|█████████████████▌                                                            | 2068/9182 [06:40<30:05,  3.94it/s]
 23%|█████████████████▌                                                            | 2069/9182 [06:40<30:16,  3.92it/s]
 23%|█████████████████▌                                                            | 2070/9182 [06:40<26:44,  4.43it/s]
 23%|█████████████████▌                                                            | 2071/9182 [06:40<22:38,  5.23it/s]
 23%|█████████████████▌                                                            | 2072/9182 [06:41<29:09,  4.06it/s]
 23%|█████████████████▌                                                            | 2073/9182 [06:41<29:04,  4.08it/s]
 23%|█████████████████▌                                                            | 2074/9182 [06:41<25:51,  4.58it/s]
 23%|█████████████████▋                                                            | 2075/9182 [06:41<29:16,  4.05it/s]
 23%|█████████████████▋                                                            | 2076/9182 [06:41<24:55,  4.75it/s]
 23%|█████████████████▋                                                            | 2078/9182 [06:42<19:28,  6.08it/s]
 23%|█████████████████▋                                                            | 2079/9182 [06:42<20:11,  5.86it/s]
 23%|█████████████████▋                                                            | 2080/9182 [06:42<22:15,  5.32it/s]
 23%|█████████████████▋                                                            | 2081/9182 [06:42<21:04,  5.61it/s]
 23%|█████████████████▋                                                            | 2082/9182 [06:42<20:31,  5.76it/s]
 23%|█████████████████▋                                                            | 2084/9182 [06:43<18:35,  6.36it/s]
 23%|█████████████████▋                                                            | 2085/9182 [06:43<22:28,  5.26it/s]
 23%|█████████████████▋                                                            | 2086/9182 [06:44<32:46,  3.61it/s]
 23%|█████████████████▋                                                            | 2087/9182 [06:44<34:46,  3.40it/s]
 23%|█████████████████▋                                                            | 2088/9182 [06:44<40:22,  2.93it/s]
 23%|█████████████████▊                                                            | 2090/9182 [06:44<27:25,  4.31it/s]
 23%|█████████████████▊                                                            | 2091/9182 [06:45<27:06,  4.36it/s]
 23%|█████████████████▊                                                            | 2092/9182 [06:45<23:36,  5.00it/s]
 23%|█████████████████▊                                                            | 2093/9182 [06:45<27:36,  4.28it/s]
 23%|█████████████████▊                                                            | 2094/9182 [06:46<33:06,  3.57it/s]
 23%|█████████████████▊                                                            | 2095/9182 [06:46<29:27,  4.01it/s]
 23%|█████████████████▊                                                            | 2096/9182 [06:46<32:39,  3.62it/s]
 23%|█████████████████▊                                                            | 2097/9182 [06:46<29:00,  4.07it/s]
 23%|█████████████████▊                                                            | 2098/9182 [06:47<27:24,  4.31it/s]
 23%|█████████████████▊                                                            | 2099/9182 [06:47<28:50,  4.09it/s]
 23%|█████████████████▊                                                            | 2100/9182 [06:47<25:54,  4.56it/s]
 23%|█████████████████▊                                                            | 2101/9182 [06:47<30:43,  3.84it/s]
 23%|█████████████████▊                                                            | 2102/9182 [06:47<30:07,  3.92it/s]
 23%|█████████████████▊                                                            | 2103/9182 [06:48<26:09,  4.51it/s]
 23%|█████████████████▉                                                            | 2105/9182 [06:48<31:45,  3.71it/s]
 23%|█████████████████▉                                                            | 2110/9182 [06:49<18:43,  6.30it/s]
 23%|█████████████████▉                                                            | 2111/9182 [06:50<34:07,  3.45it/s]
 23%|█████████████████▉                                                            | 2112/9182 [06:50<33:52,  3.48it/s]
 23%|█████████████████▉                                                            | 2113/9182 [06:50<32:59,  3.57it/s]
 23%|█████████████████▉                                                            | 2114/9182 [06:51<37:12,  3.17it/s]
 23%|█████████████████▉                                                            | 2115/9182 [06:51<36:26,  3.23it/s]
 23%|█████████████████▉                                                            | 2116/9182 [06:51<34:20,  3.43it/s]
 23%|█████████████████▉                                                            | 2117/9182 [06:52<35:33,  3.31it/s]
 23%|█████████████████▉                                                            | 2118/9182 [06:52<31:24,  3.75it/s]
 23%|██████████████████                                                            | 2119/9182 [06:52<42:10,  2.79it/s]
 23%|██████████████████                                                            | 2120/9182 [06:53<36:04,  3.26it/s]
 23%|██████████████████                                                            | 2121/9182 [06:53<45:40,  2.58it/s]
 23%|██████████████████                                                            | 2124/9182 [06:53<26:11,  4.49it/s]
 23%|██████████████████                                                            | 2125/9182 [06:54<25:36,  4.59it/s]
 23%|██████████████████                                                            | 2126/9182 [06:54<27:32,  4.27it/s]
 23%|██████████████████                                                            | 2127/9182 [06:54<29:08,  4.03it/s]
 23%|██████████████████                                                            | 2128/9182 [06:55<30:55,  3.80it/s]
 23%|██████████████████                                                            | 2129/9182 [06:55<29:14,  4.02it/s]
 23%|██████████████████▏                                                           | 2135/9182 [06:55<14:11,  8.28it/s]
 23%|██████████████████▏                                                           | 2136/9182 [06:55<16:56,  6.93it/s]
 23%|██████████████████▏                                                           | 2141/9182 [06:55<09:55, 11.82it/s]
 23%|██████████████████▏                                                           | 2143/9182 [06:56<14:07,  8.31it/s]
 23%|██████████████████▏                                                           | 2145/9182 [06:57<25:42,  4.56it/s]
 23%|██████████████████▏                                                           | 2146/9182 [06:57<25:57,  4.52it/s]
 23%|██████████████████▏                                                           | 2147/9182 [06:58<29:11,  4.02it/s]
 23%|██████████████████▏                                                           | 2148/9182 [06:58<28:28,  4.12it/s]
 23%|██████████████████▎                                                           | 2149/9182 [06:58<28:44,  4.08it/s]
 23%|██████████████████▎                                                           | 2150/9182 [06:58<30:44,  3.81it/s]
 23%|██████████████████▎                                                           | 2151/9182 [06:58<26:08,  4.48it/s]
 23%|██████████████████▎                                                           | 2152/9182 [06:59<22:53,  5.12it/s]
 23%|██████████████████▎                                                           | 2153/9182 [06:59<25:21,  4.62it/s]
 23%|██████████████████▎                                                           | 2154/9182 [06:59<28:40,  4.08it/s]
 24%|██████████████████▎                                                           | 2158/9182 [06:59<12:59,  9.02it/s]
 24%|██████████████████▎                                                           | 2160/9182 [07:00<25:32,  4.58it/s]
 24%|██████████████████▎                                                           | 2162/9182 [07:01<24:23,  4.80it/s]
 24%|██████████████████▍                                                           | 2166/9182 [07:01<14:44,  7.93it/s]
 24%|██████████████████▍                                                           | 2168/9182 [07:02<22:20,  5.23it/s]
 24%|██████████████████▍                                                           | 2170/9182 [07:02<27:00,  4.33it/s]
 24%|██████████████████▍                                                           | 2171/9182 [07:03<29:14,  4.00it/s]

 24%|██████████████████▍                                                           | 2172/9182 [07:03<27:38,  4.23it/s]
 24%|██████████████████▍                                                           | 2173/9182 [07:03<25:41,  4.55it/s]
 24%|██████████████████▍                                                           | 2174/9182 [07:03<26:31,  4.40it/s]
 24%|██████████████████▍                                                           | 2175/9182 [07:03<24:53,  4.69it/s]
 24%|██████████████████▍                                                           | 2177/9182 [07:04<20:50,  5.60it/s]
 24%|██████████████████▌                                                           | 2178/9182 [07:04<24:49,  4.70it/s]
 24%|██████████████████▌                                                           | 2179/9182 [07:04<25:39,  4.55it/s]
 24%|██████████████████▌                                                           | 2181/9182 [07:05<20:13,  5.77it/s]
 24%|██████████████████▌                                                           | 2182/9182 [07:05<25:42,  4.54it/s]
 24%|██████████████████▌                                                           | 2183/9182 [07:05<26:41,  4.37it/s]
 24%|██████████████████▌                                                           | 2184/9182 [07:05<23:50,  4.89it/s]
 24%|██████████████████▌                                                           | 2187/9182 [07:06<17:48,  6.55it/s]
 24%|██████████████████▌                                                           | 2188/9182 [07:06<21:32,  5.41it/s]
 24%|██████████████████▌                                                           | 2189/9182 [07:06<19:32,  5.96it/s]
 24%|██████████████████▌                                                           | 2190/9182 [07:06<19:53,  5.86it/s]
 24%|██████████████████▌                                                           | 2191/9182 [07:07<28:13,  4.13it/s]
 24%|██████████████████▌                                                           | 2192/9182 [07:07<34:15,  3.40it/s]
 24%|██████████████████▋                                                           | 2193/9182 [07:07<35:40,  3.26it/s]
 24%|██████████████████▋                                                           | 2196/9182 [07:08<20:26,  5.70it/s]
 24%|██████████████████▋                                                           | 2197/9182 [07:08<35:47,  3.25it/s]
 24%|██████████████████▋                                                           | 2198/9182 [07:09<31:14,  3.73it/s]
 24%|██████████████████▋                                                           | 2199/9182 [07:09<42:46,  2.72it/s]
 24%|██████████████████▋                                                           | 2201/9182 [07:10<35:52,  3.24it/s]
 24%|██████████████████▋                                                           | 2203/9182 [07:10<26:17,  4.42it/s]
 24%|██████████████████▋                                                           | 2204/9182 [07:10<26:54,  4.32it/s]
 24%|██████████████████▋                                                           | 2205/9182 [07:10<26:10,  4.44it/s]
 24%|██████████████████▋                                                           | 2206/9182 [07:10<26:19,  4.42it/s]
 24%|██████████████████▋                                                           | 2207/9182 [07:11<26:28,  4.39it/s]
 24%|██████████████████▊                                                           | 2208/9182 [07:11<25:45,  4.51it/s]
 24%|██████████████████▊                                                           | 2209/9182 [07:11<27:49,  4.18it/s]
 24%|██████████████████▊                                                           | 2210/9182 [07:11<30:04,  3.86it/s]
 24%|██████████████████▊                                                           | 2211/9182 [07:12<28:52,  4.02it/s]
 24%|██████████████████▊                                                           | 2212/9182 [07:12<29:50,  3.89it/s]
 24%|██████████████████▊                                                           | 2213/9182 [07:12<28:22,  4.09it/s]
 24%|██████████████████▊                                                           | 2215/9182 [07:12<19:38,  5.91it/s]
 24%|██████████████████▊                                                           | 2218/9182 [07:13<16:11,  7.17it/s]
 24%|██████████████████▊                                                           | 2221/9182 [07:13<15:18,  7.58it/s]
 24%|██████████████████▉                                                           | 2225/9182 [07:13<09:58, 11.62it/s]
 24%|██████████████████▉                                                           | 2227/9182 [07:14<17:42,  6.54it/s]
 24%|██████████████████▉                                                           | 2229/9182 [07:14<19:51,  5.84it/s]
 24%|██████████████████▉                                                           | 2230/9182 [07:15<34:22,  3.37it/s]
 24%|██████████████████▉                                                           | 2231/9182 [07:16<36:22,  3.19it/s]
 24%|██████████████████▉                                                           | 2232/9182 [07:16<31:55,  3.63it/s]
 24%|██████████████████▉                                                           | 2233/9182 [07:16<33:17,  3.48it/s]
 24%|██████████████████▉                                                           | 2234/9182 [07:16<31:34,  3.67it/s]
 24%|██████████████████▉                                                           | 2235/9182 [07:17<29:34,  3.91it/s]
 24%|██████████████████▉                                                           | 2236/9182 [07:17<26:09,  4.43it/s]
 24%|███████████████████                                                           | 2237/9182 [07:17<24:48,  4.67it/s]
 24%|███████████████████                                                           | 2238/9182 [07:18<30:35,  3.78it/s]
 24%|███████████████████                                                           | 2239/9182 [07:18<36:19,  3.19it/s]
 24%|███████████████████                                                           | 2242/9182 [07:18<19:56,  5.80it/s]
 24%|███████████████████                                                           | 2243/9182 [07:18<26:36,  4.35it/s]
 24%|███████████████████                                                           | 2244/9182 [07:18<23:22,  4.95it/s]
 24%|███████████████████                                                           | 2245/9182 [07:19<22:21,  5.17it/s]
 24%|███████████████████                                                           | 2246/9182 [07:19<25:35,  4.52it/s]
 24%|███████████████████                                                           | 2247/9182 [07:19<23:17,  4.96it/s]
 24%|███████████████████                                                           | 2248/9182 [07:19<20:00,  5.78it/s]
 24%|███████████████████                                                           | 2249/9182 [07:20<24:19,  4.75it/s]
 25%|███████████████████                                                           | 2250/9182 [07:20<25:05,  4.60it/s]
 25%|███████████████████                                                           | 2251/9182 [07:20<31:06,  3.71it/s]
 25%|███████████████████▏                                                          | 2252/9182 [07:21<44:23,  2.60it/s]
 25%|███████████████████▏                                                          | 2253/9182 [07:22<49:42,  2.32it/s]
 25%|███████████████████▏                                                          | 2254/9182 [07:22<54:21,  2.12it/s]
 25%|███████████████████▏                                                          | 2255/9182 [07:22<52:47,  2.19it/s]
 25%|███████████████████▏                                                          | 2256/9182 [07:23<51:49,  2.23it/s]
 25%|██████████████████▋                                                         | 2257/9182 [07:26<1:19:03,  1.46it/s]
 25%|██████████████████▋                                                         | 2258/9182 [07:26<2:10:54,  1.13s/it]
 25%|██████████████████▋                                                         | 2259/9182 [07:26<1:35:21,  1.21it/s]
 25%|██████████████████▋                                                         | 2260/9182 [07:27<1:25:57,  1.34it/s]
 25%|██████████████████▋                                                         | 2261/9182 [07:28<1:23:36,  1.38it/s]
 25%|██████████████████▋                                                         | 2262/9182 [07:28<1:10:41,  1.63it/s]
 25%|███████████████████▏                                                          | 2263/9182 [07:28<58:42,  1.96it/s]
 25%|██████████████████▋                                                         | 2264/9182 [07:29<1:03:45,  1.81it/s]
 25%|███████████████████▏                                                          | 2265/9182 [07:29<57:14,  2.01it/s]
 25%|███████████████████▎                                                          | 2269/9182 [07:29<27:46,  4.15it/s]
 25%|███████████████████▎                                                          | 2270/9182 [07:30<25:26,  4.53it/s]
 25%|███████████████████▎                                                          | 2271/9182 [07:30<26:19,  4.37it/s]
 25%|███████████████████▎                                                          | 2272/9182 [07:30<33:25,  3.45it/s]
 25%|███████████████████▎                                                          | 2273/9182 [07:31<29:56,  3.85it/s]
 25%|███████████████████▎                                                          | 2274/9182 [07:31<29:58,  3.84it/s]
 25%|███████████████████▎                                                          | 2275/9182 [07:31<36:57,  3.12it/s]
 25%|███████████████████▎                                                          | 2276/9182 [07:31<31:13,  3.69it/s]
 25%|███████████████████▎                                                          | 2277/9182 [07:32<26:51,  4.29it/s]
 25%|███████████████████▎                                                          | 2279/9182 [07:32<18:41,  6.15it/s]
 25%|███████████████████▎                                                          | 2280/9182 [07:32<20:10,  5.70it/s]
 25%|███████████████████▍                                                          | 2281/9182 [07:32<23:15,  4.94it/s]
 25%|███████████████████▍                                                          | 2282/9182 [07:32<21:51,  5.26it/s]
 25%|███████████████████▍                                                          | 2283/9182 [07:33<26:06,  4.40it/s]
 25%|███████████████████▍                                                          | 2284/9182 [07:33<33:17,  3.45it/s]
 25%|███████████████████▍                                                          | 2285/9182 [07:33<27:11,  4.23it/s]
 25%|███████████████████▍                                                          | 2286/9182 [07:33<23:02,  4.99it/s]
 25%|███████████████████▍                                                          | 2287/9182 [07:34<22:08,  5.19it/s]
 25%|███████████████████▍                                                          | 2288/9182 [07:34<20:18,  5.66it/s]
 25%|███████████████████▍                                                          | 2289/9182 [07:34<22:39,  5.07it/s]
 25%|███████████████████▍                                                          | 2290/9182 [07:34<24:21,  4.71it/s]
 25%|███████████████████▍                                                          | 2291/9182 [07:34<22:23,  5.13it/s]
 25%|███████████████████▍                                                          | 2292/9182 [07:35<21:15,  5.40it/s]
 25%|███████████████████▌                                                          | 2296/9182 [07:35<14:00,  8.20it/s]
 25%|███████████████████▌                                                          | 2298/9182 [07:36<26:06,  4.39it/s]
 25%|███████████████████▌                                                          | 2299/9182 [07:36<27:12,  4.22it/s]
 25%|███████████████████▌                                                          | 2300/9182 [07:36<30:47,  3.73it/s]
 25%|███████████████████▌                                                          | 2302/9182 [07:37<21:53,  5.24it/s]
 25%|███████████████████▌                                                          | 2305/9182 [07:37<18:43,  6.12it/s]
 25%|███████████████████▌                                                          | 2306/9182 [07:37<20:43,  5.53it/s]
 25%|███████████████████▌                                                          | 2307/9182 [07:37<20:02,  5.72it/s]
 25%|███████████████████▌                                                          | 2308/9182 [07:38<22:48,  5.02it/s]
 25%|███████████████████▌                                                          | 2309/9182 [07:38<21:32,  5.32it/s]
 25%|███████████████████▋                                                          | 2314/9182 [07:39<17:11,  6.66it/s]
 25%|███████████████████▋                                                          | 2315/9182 [07:39<31:13,  3.67it/s]
 25%|███████████████████▋                                                          | 2316/9182 [07:40<32:47,  3.49it/s]
 25%|███████████████████▋                                                          | 2317/9182 [07:41<43:58,  2.60it/s]
 25%|███████████████████▋                                                          | 2318/9182 [07:41<38:57,  2.94it/s]
 25%|███████████████████▋                                                          | 2321/9182 [07:41<23:12,  4.93it/s]
 25%|███████████████████▋                                                          | 2322/9182 [07:41<23:13,  4.92it/s]
 25%|███████████████████▋                                                          | 2323/9182 [07:42<38:45,  2.95it/s]
 25%|███████████████████▋                                                          | 2324/9182 [07:43<43:48,  2.61it/s]
 25%|███████████████████▊                                                          | 2325/9182 [07:43<52:02,  2.20it/s]
 25%|███████████████████▊                                                          | 2326/9182 [07:43<42:17,  2.70it/s]
 25%|███████████████████▊                                                          | 2327/9182 [07:43<34:44,  3.29it/s]
 25%|███████████████████▊                                                          | 2331/9182 [07:44<20:01,  5.70it/s]
 25%|███████████████████▊                                                          | 2332/9182 [07:44<18:38,  6.13it/s]
 25%|███████████████████▊                                                          | 2333/9182 [07:44<17:40,  6.46it/s]
 25%|███████████████████▊                                                          | 2334/9182 [07:44<18:52,  6.05it/s]
 25%|███████████████████▊                                                          | 2335/9182 [07:45<24:12,  4.72it/s]
 25%|███████████████████▊                                                          | 2336/9182 [07:45<26:45,  4.26it/s]
 25%|███████████████████▊                                                          | 2337/9182 [07:45<28:21,  4.02it/s]
 25%|███████████████████▊                                                          | 2338/9182 [07:46<38:47,  2.94it/s]
 25%|███████████████████▊                                                          | 2339/9182 [07:46<42:31,  2.68it/s]
 25%|███████████████████▉                                                          | 2340/9182 [07:47<46:02,  2.48it/s]
 25%|███████████████████▉                                                          | 2341/9182 [07:47<43:18,  2.63it/s]
 26%|███████████████████▉                                                          | 2343/9182 [07:47<28:45,  3.96it/s]
 26%|███████████████████▉                                                          | 2345/9182 [07:47<20:26,  5.57it/s]

 26%|███████████████████▉                                                          | 2346/9182 [07:48<34:19,  3.32it/s]
 26%|███████████████████▉                                                          | 2347/9182 [07:48<32:26,  3.51it/s]
 26%|███████████████████▉                                                          | 2348/9182 [07:49<31:15,  3.64it/s]
 26%|███████████████████▉                                                          | 2349/9182 [07:49<38:12,  2.98it/s]
 26%|███████████████████▉                                                          | 2350/9182 [07:49<33:53,  3.36it/s]
 26%|███████████████████▉                                                          | 2353/9182 [07:49<19:35,  5.81it/s]
 26%|███████████████████▉                                                          | 2354/9182 [07:50<18:14,  6.24it/s]
 26%|████████████████████                                                          | 2357/9182 [07:50<12:15,  9.28it/s]
 26%|████████████████████                                                          | 2359/9182 [07:50<11:24,  9.96it/s]
 26%|████████████████████                                                          | 2361/9182 [07:50<10:07, 11.24it/s]
 26%|████████████████████                                                          | 2363/9182 [07:50<15:24,  7.38it/s]
 26%|████████████████████                                                          | 2366/9182 [07:51<13:23,  8.49it/s]
 26%|████████████████████                                                          | 2369/9182 [07:51<13:18,  8.53it/s]
 26%|████████████████████▏                                                         | 2370/9182 [07:52<18:50,  6.03it/s]
 26%|████████████████████▏                                                         | 2371/9182 [07:52<19:47,  5.73it/s]
 26%|████████████████████▏                                                         | 2372/9182 [07:52<28:25,  3.99it/s]
 26%|████████████████████▏                                                         | 2373/9182 [07:53<33:04,  3.43it/s]
 26%|████████████████████▏                                                         | 2375/9182 [07:53<35:50,  3.17it/s]
 26%|████████████████████▏                                                         | 2376/9182 [07:54<30:42,  3.69it/s]
 26%|████████████████████▏                                                         | 2377/9182 [07:54<27:59,  4.05it/s]
 26%|████████████████████▏                                                         | 2381/9182 [07:54<16:00,  7.08it/s]
 26%|████████████████████▏                                                         | 2382/9182 [07:54<16:16,  6.96it/s]
 26%|████████████████████▏                                                         | 2383/9182 [07:54<17:05,  6.63it/s]
 26%|████████████████████▎                                                         | 2385/9182 [07:55<20:37,  5.49it/s]
 26%|████████████████████▎                                                         | 2388/9182 [07:55<16:24,  6.90it/s]
 26%|████████████████████▎                                                         | 2389/9182 [07:56<20:20,  5.56it/s]
 26%|████████████████████▎                                                         | 2390/9182 [07:56<25:16,  4.48it/s]
 26%|████████████████████▎                                                         | 2395/9182 [07:57<20:59,  5.39it/s]
 26%|████████████████████▎                                                         | 2396/9182 [07:58<31:17,  3.62it/s]
 26%|████████████████████▎                                                         | 2397/9182 [07:58<37:12,  3.04it/s]
 26%|████████████████████▍                                                         | 2399/9182 [07:58<27:49,  4.06it/s]
 26%|████████████████████▍                                                         | 2400/9182 [07:58<27:18,  4.14it/s]
 26%|████████████████████▍                                                         | 2403/9182 [07:59<18:50,  6.00it/s]
 26%|████████████████████▍                                                         | 2404/9182 [07:59<23:05,  4.89it/s]
 26%|████████████████████▍                                                         | 2405/9182 [07:59<21:39,  5.22it/s]
 26%|████████████████████▍                                                         | 2406/9182 [07:59<22:37,  4.99it/s]
 26%|████████████████████▍                                                         | 2407/9182 [08:00<21:26,  5.27it/s]
 26%|████████████████████▍                                                         | 2408/9182 [08:00<19:25,  5.81it/s]
 26%|████████████████████▍                                                         | 2409/9182 [08:00<31:44,  3.56it/s]
 26%|████████████████████▍                                                         | 2410/9182 [08:01<34:24,  3.28it/s]
 26%|████████████████████▍                                                         | 2412/9182 [08:01<30:26,  3.71it/s]
 26%|████████████████████▍                                                         | 2413/9182 [08:01<31:28,  3.58it/s]
 26%|████████████████████▌                                                         | 2414/9182 [08:02<31:29,  3.58it/s]
 26%|████████████████████▌                                                         | 2415/9182 [08:02<28:47,  3.92it/s]
 26%|████████████████████▌                                                         | 2416/9182 [08:02<23:58,  4.70it/s]
 26%|████████████████████▌                                                         | 2417/9182 [08:02<20:33,  5.49it/s]
 26%|████████████████████▌                                                         | 2419/9182 [08:02<14:16,  7.90it/s]
 26%|████████████████████▌                                                         | 2421/9182 [08:02<13:58,  8.07it/s]
 26%|████████████████████▌                                                         | 2422/9182 [08:03<18:45,  6.01it/s]
 26%|████████████████████▌                                                         | 2424/9182 [08:03<17:17,  6.51it/s]
 26%|████████████████████▌                                                         | 2425/9182 [08:03<17:02,  6.61it/s]
 26%|████████████████████▌                                                         | 2426/9182 [08:04<26:29,  4.25it/s]
 26%|████████████████████▌                                                         | 2427/9182 [08:04<25:52,  4.35it/s]
 26%|████████████████████▋                                                         | 2428/9182 [08:04<23:54,  4.71it/s]
 26%|████████████████████▋                                                         | 2429/9182 [08:05<33:20,  3.38it/s]
 26%|████████████████████▋                                                         | 2430/9182 [08:05<32:13,  3.49it/s]
 26%|████████████████████▋                                                         | 2431/9182 [08:05<37:50,  2.97it/s]
 26%|████████████████████▋                                                         | 2432/9182 [08:05<32:00,  3.51it/s]
 26%|████████████████████▋                                                         | 2433/9182 [08:06<29:03,  3.87it/s]
 27%|████████████████████▋                                                         | 2434/9182 [08:06<27:44,  4.05it/s]
 27%|████████████████████▋                                                         | 2436/9182 [08:06<22:25,  5.02it/s]
 27%|████████████████████▋                                                         | 2437/9182 [08:06<23:20,  4.82it/s]
 27%|████████████████████▋                                                         | 2438/9182 [08:07<29:17,  3.84it/s]
 27%|████████████████████▋                                                         | 2439/9182 [08:07<26:54,  4.18it/s]
 27%|████████████████████▋                                                         | 2440/9182 [08:08<39:20,  2.86it/s]
 27%|████████████████████▋                                                         | 2441/9182 [08:08<31:33,  3.56it/s]
 27%|████████████████████▋                                                         | 2442/9182 [08:08<28:38,  3.92it/s]
 27%|████████████████████▊                                                         | 2443/9182 [08:08<28:28,  3.94it/s]
 27%|████████████████████▊                                                         | 2444/9182 [08:08<27:19,  4.11it/s]
 27%|████████████████████▊                                                         | 2445/9182 [08:08<22:47,  4.93it/s]
 27%|████████████████████▊                                                         | 2449/9182 [08:09<11:31,  9.73it/s]
 27%|████████████████████▊                                                         | 2451/9182 [08:09<16:12,  6.92it/s]
 27%|████████████████████▊                                                         | 2454/9182 [08:10<18:31,  6.06it/s]
 27%|████████████████████▊                                                         | 2455/9182 [08:10<19:19,  5.80it/s]
 27%|████████████████████▊                                                         | 2456/9182 [08:10<21:45,  5.15it/s]
 27%|████████████████████▊                                                         | 2457/9182 [08:10<21:20,  5.25it/s]
 27%|████████████████████▉                                                         | 2459/9182 [08:11<19:01,  5.89it/s]
 27%|████████████████████▉                                                         | 2461/9182 [08:11<21:03,  5.32it/s]
 27%|████████████████████▉                                                         | 2462/9182 [08:11<21:32,  5.20it/s]
 27%|████████████████████▉                                                         | 2463/9182 [08:12<33:33,  3.34it/s]
 27%|████████████████████▉                                                         | 2464/9182 [08:13<46:25,  2.41it/s]
 27%|████████████████████▉                                                         | 2465/9182 [08:13<42:37,  2.63it/s]
 27%|████████████████████▉                                                         | 2466/9182 [08:14<52:44,  2.12it/s]
 27%|████████████████████▉                                                         | 2467/9182 [08:14<45:32,  2.46it/s]
 27%|████████████████████▉                                                         | 2469/9182 [08:14<28:52,  3.88it/s]
 27%|████████████████████▉                                                         | 2470/9182 [08:14<29:43,  3.76it/s]
 27%|████████████████████▉                                                         | 2471/9182 [08:15<27:06,  4.13it/s]
 27%|████████████████████▉                                                         | 2472/9182 [08:15<28:14,  3.96it/s]
 27%|█████████████████████                                                         | 2475/9182 [08:15<15:24,  7.26it/s]
 27%|█████████████████████                                                         | 2477/9182 [08:15<13:14,  8.44it/s]
 27%|█████████████████████                                                         | 2479/9182 [08:16<23:32,  4.75it/s]
 27%|█████████████████████                                                         | 2480/9182 [08:16<22:01,  5.07it/s]
 27%|█████████████████████                                                         | 2481/9182 [08:17<28:03,  3.98it/s]
 27%|█████████████████████                                                         | 2483/9182 [08:17<20:53,  5.34it/s]
 27%|█████████████████████                                                         | 2484/9182 [08:17<21:43,  5.14it/s]
 27%|█████████████████████                                                         | 2485/9182 [08:18<36:29,  3.06it/s]
 27%|█████████████████████                                                         | 2486/9182 [08:18<37:28,  2.98it/s]
 27%|█████████████████████▏                                                        | 2487/9182 [08:18<34:38,  3.22it/s]
 27%|█████████████████████▏                                                        | 2488/9182 [08:19<36:31,  3.05it/s]
 27%|█████████████████████▏                                                        | 2489/9182 [08:19<30:21,  3.68it/s]
 27%|█████████████████████▏                                                        | 2490/9182 [08:19<25:10,  4.43it/s]
 27%|█████████████████████▏                                                        | 2491/9182 [08:19<24:01,  4.64it/s]
 27%|█████████████████████▏                                                        | 2492/9182 [08:19<21:18,  5.23it/s]
 27%|█████████████████████▏                                                        | 2493/9182 [08:19<22:05,  5.05it/s]
 27%|█████████████████████▏                                                        | 2494/9182 [08:20<18:59,  5.87it/s]
 27%|█████████████████████▏                                                        | 2497/9182 [08:20<17:42,  6.29it/s]
 27%|█████████████████████▏                                                        | 2498/9182 [08:20<17:44,  6.28it/s]
 27%|█████████████████████▏                                                        | 2499/9182 [08:20<21:25,  5.20it/s]
 27%|█████████████████████▏                                                        | 2500/9182 [08:21<35:52,  3.10it/s]
 27%|█████████████████████▎                                                        | 2502/9182 [08:21<24:46,  4.49it/s]
 27%|█████████████████████▎                                                        | 2503/9182 [08:22<28:00,  3.97it/s]
 27%|█████████████████████▎                                                        | 2504/9182 [08:22<25:13,  4.41it/s]
 27%|█████████████████████▎                                                        | 2505/9182 [08:22<23:05,  4.82it/s]
 27%|█████████████████████▎                                                        | 2506/9182 [08:23<32:54,  3.38it/s]
 27%|█████████████████████▎                                                        | 2507/9182 [08:23<43:41,  2.55it/s]
 27%|█████████████████████▎                                                        | 2508/9182 [08:23<39:11,  2.84it/s]
 27%|█████████████████████▎                                                        | 2509/9182 [08:24<42:45,  2.60it/s]
 27%|█████████████████████▎                                                        | 2510/9182 [08:24<45:56,  2.42it/s]
 27%|█████████████████████▎                                                        | 2511/9182 [08:25<46:25,  2.39it/s]
 27%|█████████████████████▎                                                        | 2512/9182 [08:25<42:58,  2.59it/s]
 27%|█████████████████████▎                                                        | 2513/9182 [08:25<33:37,  3.30it/s]
 27%|█████████████████████▎                                                        | 2514/9182 [08:25<32:24,  3.43it/s]
 27%|█████████████████████▎                                                        | 2515/9182 [08:26<26:59,  4.12it/s]
 27%|█████████████████████▎                                                        | 2516/9182 [08:26<22:31,  4.93it/s]
 27%|█████████████████████▍                                                        | 2517/9182 [08:26<21:25,  5.18it/s]
 27%|█████████████████████▍                                                        | 2518/9182 [08:26<27:58,  3.97it/s]
 27%|█████████████████████▍                                                        | 2519/9182 [08:27<27:51,  3.99it/s]
 27%|█████████████████████▍                                                        | 2520/9182 [08:27<32:58,  3.37it/s]
 27%|█████████████████████▍                                                        | 2521/9182 [08:27<37:51,  2.93it/s]
 27%|█████████████████████▍                                                        | 2522/9182 [08:27<30:07,  3.68it/s]
 27%|█████████████████████▍                                                        | 2523/9182 [08:28<25:34,  4.34it/s]
 27%|█████████████████████▍                                                        | 2524/9182 [08:28<26:34,  4.18it/s]

 27%|█████████████████████▍                                                        | 2525/9182 [08:28<24:56,  4.45it/s]
 28%|█████████████████████▍                                                        | 2526/9182 [08:29<25:05,  4.42it/s]
 28%|█████████████████████▍                                                        | 2527/9182 [08:29<31:50,  3.48it/s]
 28%|█████████████████████▍                                                        | 2528/9182 [08:29<31:33,  3.51it/s]
 28%|█████████████████████▍                                                        | 2529/9182 [08:30<34:42,  3.19it/s]
 28%|█████████████████████▍                                                        | 2530/9182 [08:30<41:04,  2.70it/s]
 28%|█████████████████████▌                                                        | 2531/9182 [08:30<32:54,  3.37it/s]
 28%|█████████████████████▌                                                        | 2534/9182 [08:31<26:10,  4.23it/s]
 28%|█████████████████████▌                                                        | 2538/9182 [08:31<15:08,  7.31it/s]
 28%|█████████████████████▌                                                        | 2540/9182 [08:31<12:46,  8.67it/s]
 28%|█████████████████████▌                                                        | 2542/9182 [08:31<13:37,  8.12it/s]
 28%|█████████████████████▌                                                        | 2544/9182 [08:31<11:59,  9.23it/s]
 28%|█████████████████████▋                                                        | 2549/9182 [08:32<09:54, 11.15it/s]
 28%|█████████████████████▋                                                        | 2551/9182 [08:33<28:38,  3.86it/s]
 28%|█████████████████████▋                                                        | 2552/9182 [08:34<33:46,  3.27it/s]
 28%|█████████████████████▋                                                        | 2553/9182 [08:34<30:46,  3.59it/s]
 28%|█████████████████████▋                                                        | 2554/9182 [08:34<27:11,  4.06it/s]
 28%|█████████████████████▋                                                        | 2558/9182 [08:35<21:50,  5.06it/s]
 28%|█████████████████████▋                                                        | 2559/9182 [08:35<24:25,  4.52it/s]
 28%|█████████████████████▋                                                        | 2560/9182 [08:36<27:22,  4.03it/s]
 28%|█████████████████████▊                                                        | 2561/9182 [08:36<30:57,  3.56it/s]
 28%|█████████████████████▊                                                        | 2562/9182 [08:36<34:45,  3.17it/s]
 28%|█████████████████████▊                                                        | 2563/9182 [08:37<35:12,  3.13it/s]
 28%|█████████████████████▊                                                        | 2564/9182 [08:37<30:36,  3.60it/s]
 28%|█████████████████████▊                                                        | 2569/9182 [08:37<12:27,  8.84it/s]
 28%|█████████████████████▊                                                        | 2571/9182 [08:37<13:47,  7.99it/s]
 28%|█████████████████████▊                                                        | 2573/9182 [08:38<13:45,  8.01it/s]
 28%|█████████████████████▊                                                        | 2575/9182 [08:38<23:43,  4.64it/s]
 28%|█████████████████████▉                                                        | 2576/9182 [08:38<22:15,  4.94it/s]
 28%|█████████████████████▉                                                        | 2577/9182 [08:39<29:37,  3.72it/s]
 28%|█████████████████████▉                                                        | 2578/9182 [08:39<28:30,  3.86it/s]
 28%|█████████████████████▉                                                        | 2579/9182 [08:40<27:48,  3.96it/s]
 28%|█████████████████████▉                                                        | 2580/9182 [08:40<25:09,  4.37it/s]
 28%|█████████████████████▉                                                        | 2583/9182 [08:40<14:09,  7.77it/s]
 28%|█████████████████████▉                                                        | 2585/9182 [08:40<14:39,  7.50it/s]
 28%|█████████████████████▉                                                        | 2587/9182 [08:41<22:03,  4.98it/s]
 28%|█████████████████████▉                                                        | 2588/9182 [08:41<21:25,  5.13it/s]
 28%|██████████████████████                                                        | 2590/9182 [08:41<16:22,  6.71it/s]
 28%|██████████████████████                                                        | 2592/9182 [08:42<21:51,  5.03it/s]
 28%|██████████████████████                                                        | 2593/9182 [08:42<22:25,  4.90it/s]
 28%|██████████████████████                                                        | 2594/9182 [08:42<21:16,  5.16it/s]
 28%|██████████████████████                                                        | 2595/9182 [08:43<27:51,  3.94it/s]
 28%|██████████████████████                                                        | 2597/9182 [08:43<19:30,  5.62it/s]
 28%|██████████████████████                                                        | 2598/9182 [08:43<21:01,  5.22it/s]
 28%|██████████████████████                                                        | 2599/9182 [08:43<20:45,  5.29it/s]
 28%|██████████████████████                                                        | 2600/9182 [08:43<22:11,  4.94it/s]
 28%|██████████████████████                                                        | 2603/9182 [08:43<12:46,  8.58it/s]
 28%|██████████████████████▏                                                       | 2606/9182 [08:44<09:01, 12.14it/s]
 28%|██████████████████████▏                                                       | 2608/9182 [08:44<21:04,  5.20it/s]
 28%|██████████████████████▏                                                       | 2613/9182 [08:45<13:38,  8.03it/s]
 28%|██████████████████████▏                                                       | 2615/9182 [08:45<19:22,  5.65it/s]
 29%|██████████████████████▏                                                       | 2617/9182 [08:47<27:32,  3.97it/s]
 29%|██████████████████████▏                                                       | 2618/9182 [08:47<36:02,  3.03it/s]
 29%|██████████████████████▏                                                       | 2619/9182 [08:48<38:23,  2.85it/s]
 29%|██████████████████████▎                                                       | 2620/9182 [08:48<36:34,  2.99it/s]
 29%|██████████████████████▎                                                       | 2621/9182 [08:49<38:30,  2.84it/s]
 29%|██████████████████████▎                                                       | 2622/9182 [08:49<39:32,  2.77it/s]
 29%|██████████████████████▎                                                       | 2625/9182 [08:49<22:55,  4.77it/s]
 29%|██████████████████████▎                                                       | 2626/9182 [08:49<24:37,  4.44it/s]
 29%|██████████████████████▎                                                       | 2630/9182 [08:49<15:04,  7.25it/s]
 29%|██████████████████████▎                                                       | 2632/9182 [08:50<14:57,  7.30it/s]
 29%|██████████████████████▎                                                       | 2633/9182 [08:50<15:32,  7.02it/s]
 29%|██████████████████████▍                                                       | 2635/9182 [08:50<15:34,  7.01it/s]
 29%|██████████████████████▍                                                       | 2636/9182 [08:50<15:18,  7.13it/s]
 29%|██████████████████████▍                                                       | 2637/9182 [08:51<16:36,  6.57it/s]
 29%|██████████████████████▍                                                       | 2638/9182 [08:51<18:21,  5.94it/s]
 29%|██████████████████████▍                                                       | 2639/9182 [08:51<19:13,  5.67it/s]
 29%|██████████████████████▍                                                       | 2640/9182 [08:51<18:14,  5.98it/s]
 29%|██████████████████████▍                                                       | 2641/9182 [08:51<20:21,  5.35it/s]
 29%|██████████████████████▍                                                       | 2642/9182 [08:52<24:43,  4.41it/s]
 29%|██████████████████████▍                                                       | 2643/9182 [08:52<27:32,  3.96it/s]
 29%|██████████████████████▍                                                       | 2644/9182 [08:52<30:07,  3.62it/s]
 29%|██████████████████████▍                                                       | 2645/9182 [08:53<37:47,  2.88it/s]
 29%|██████████████████████▍                                                       | 2646/9182 [08:53<35:55,  3.03it/s]
 29%|██████████████████████▍                                                       | 2647/9182 [08:53<30:21,  3.59it/s]
 29%|██████████████████████▍                                                       | 2648/9182 [08:54<31:49,  3.42it/s]
 29%|██████████████████████▌                                                       | 2653/9182 [08:54<14:35,  7.46it/s]
 29%|██████████████████████▌                                                       | 2654/9182 [08:54<16:19,  6.66it/s]
 29%|██████████████████████▌                                                       | 2655/9182 [08:54<21:09,  5.14it/s]
 29%|██████████████████████▌                                                       | 2656/9182 [08:55<19:43,  5.52it/s]
 29%|██████████████████████▌                                                       | 2659/9182 [08:55<14:19,  7.59it/s]
 29%|██████████████████████▌                                                       | 2660/9182 [08:55<13:52,  7.84it/s]
 29%|██████████████████████▌                                                       | 2663/9182 [08:56<18:34,  5.85it/s]
 29%|██████████████████████▋                                                       | 2666/9182 [08:56<13:14,  8.20it/s]
 29%|██████████████████████▋                                                       | 2668/9182 [08:56<16:30,  6.57it/s]
 29%|██████████████████████▋                                                       | 2669/9182 [08:57<16:35,  6.55it/s]
 29%|██████████████████████▋                                                       | 2670/9182 [08:57<25:25,  4.27it/s]
 29%|██████████████████████▋                                                       | 2671/9182 [08:58<32:43,  3.32it/s]
 29%|██████████████████████▋                                                       | 2672/9182 [08:58<35:41,  3.04it/s]
 29%|██████████████████████▋                                                       | 2673/9182 [08:58<31:27,  3.45it/s]
 29%|██████████████████████▋                                                       | 2675/9182 [08:58<20:58,  5.17it/s]
 29%|██████████████████████▋                                                       | 2676/9182 [08:59<21:55,  4.95it/s]
 29%|██████████████████████▋                                                       | 2677/9182 [08:59<20:32,  5.28it/s]
 29%|██████████████████████▋                                                       | 2678/9182 [08:59<18:09,  5.97it/s]
 29%|██████████████████████▊                                                       | 2679/9182 [08:59<17:26,  6.22it/s]
 29%|██████████████████████▊                                                       | 2681/9182 [08:59<13:09,  8.24it/s]
 29%|██████████████████████▊                                                       | 2684/9182 [08:59<13:00,  8.33it/s]
 29%|██████████████████████▊                                                       | 2686/9182 [09:00<16:22,  6.61it/s]
 29%|██████████████████████▊                                                       | 2687/9182 [09:00<24:01,  4.50it/s]
 29%|██████████████████████▊                                                       | 2688/9182 [09:01<23:53,  4.53it/s]
 29%|██████████████████████▊                                                       | 2689/9182 [09:01<26:33,  4.08it/s]
 29%|██████████████████████▊                                                       | 2690/9182 [09:01<23:56,  4.52it/s]
 29%|██████████████████████▊                                                       | 2691/9182 [09:02<24:03,  4.50it/s]
 29%|██████████████████████▊                                                       | 2692/9182 [09:02<32:16,  3.35it/s]
 29%|██████████████████████▉                                                       | 2693/9182 [09:02<29:28,  3.67it/s]
 29%|██████████████████████▉                                                       | 2694/9182 [09:02<24:39,  4.39it/s]
 29%|██████████████████████▉                                                       | 2695/9182 [09:02<22:56,  4.71it/s]
 29%|██████████████████████▉                                                       | 2698/9182 [09:02<13:32,  7.98it/s]
 29%|██████████████████████▉                                                       | 2700/9182 [09:03<14:34,  7.41it/s]
 29%|██████████████████████▉                                                       | 2701/9182 [09:03<14:09,  7.63it/s]
 29%|██████████████████████▉                                                       | 2702/9182 [09:03<14:48,  7.29it/s]
 29%|██████████████████████▉                                                       | 2703/9182 [09:03<17:14,  6.26it/s]
 29%|██████████████████████▉                                                       | 2704/9182 [09:04<23:35,  4.58it/s]
 29%|██████████████████████▉                                                       | 2705/9182 [09:04<25:18,  4.27it/s]
 29%|██████████████████████▉                                                       | 2706/9182 [09:04<23:26,  4.60it/s]
 29%|██████████████████████▉                                                       | 2707/9182 [09:05<33:50,  3.19it/s]
 29%|███████████████████████                                                       | 2708/9182 [09:05<36:40,  2.94it/s]
 30%|███████████████████████                                                       | 2709/9182 [09:06<55:30,  1.94it/s]
 30%|███████████████████████                                                       | 2710/9182 [09:06<45:46,  2.36it/s]
 30%|███████████████████████                                                       | 2711/9182 [09:07<38:30,  2.80it/s]
 30%|███████████████████████                                                       | 2712/9182 [09:07<39:18,  2.74it/s]
 30%|███████████████████████                                                       | 2714/9182 [09:08<44:58,  2.40it/s]
 30%|███████████████████████                                                       | 2715/9182 [09:08<45:31,  2.37it/s]
 30%|███████████████████████                                                       | 2716/9182 [09:08<37:33,  2.87it/s]
 30%|███████████████████████                                                       | 2717/9182 [09:09<35:04,  3.07it/s]
 30%|███████████████████████                                                       | 2718/9182 [09:09<33:01,  3.26it/s]
 30%|███████████████████████                                                       | 2719/9182 [09:09<37:50,  2.85it/s]
 30%|███████████████████████                                                       | 2720/9182 [09:09<30:33,  3.53it/s]
 30%|███████████████████████                                                       | 2721/9182 [09:10<31:32,  3.41it/s]
 30%|███████████████████████                                                       | 2722/9182 [09:10<32:33,  3.31it/s]
 30%|███████████████████████▏                                                      | 2723/9182 [09:11<35:19,  3.05it/s]
 30%|███████████████████████▏                                                      | 2724/9182 [09:11<41:42,  2.58it/s]

 30%|███████████████████████▏                                                      | 2725/9182 [09:11<35:34,  3.02it/s]
 30%|███████████████████████▏                                                      | 2726/9182 [09:12<32:39,  3.30it/s]
 30%|███████████████████████▏                                                      | 2727/9182 [09:12<39:14,  2.74it/s]
 30%|███████████████████████▏                                                      | 2728/9182 [09:12<41:21,  2.60it/s]
 30%|███████████████████████▏                                                      | 2729/9182 [09:13<47:52,  2.25it/s]
 30%|███████████████████████▏                                                      | 2730/9182 [09:13<40:50,  2.63it/s]
 30%|███████████████████████▏                                                      | 2731/9182 [09:14<33:19,  3.23it/s]
 30%|███████████████████████▏                                                      | 2732/9182 [09:14<44:16,  2.43it/s]
 30%|███████████████████████▏                                                      | 2733/9182 [09:15<48:03,  2.24it/s]
 30%|███████████████████████▏                                                      | 2734/9182 [09:15<44:53,  2.39it/s]
 30%|███████████████████████▏                                                      | 2735/9182 [09:16<52:29,  2.05it/s]
 30%|███████████████████████▏                                                      | 2736/9182 [09:16<53:13,  2.02it/s]
 30%|███████████████████████▎                                                      | 2737/9182 [09:16<41:47,  2.57it/s]
 30%|███████████████████████▎                                                      | 2738/9182 [09:17<54:20,  1.98it/s]
 30%|███████████████████████▎                                                      | 2739/9182 [09:17<47:40,  2.25it/s]
 30%|███████████████████████▎                                                      | 2741/9182 [09:18<47:58,  2.24it/s]
 30%|███████████████████████▎                                                      | 2744/9182 [09:18<26:46,  4.01it/s]
 30%|███████████████████████▎                                                      | 2745/9182 [09:19<26:51,  3.99it/s]
 30%|███████████████████████▎                                                      | 2746/9182 [09:19<34:14,  3.13it/s]
 30%|███████████████████████▎                                                      | 2747/9182 [09:19<31:37,  3.39it/s]
 30%|███████████████████████▎                                                      | 2748/9182 [09:20<32:46,  3.27it/s]
 30%|███████████████████████▎                                                      | 2749/9182 [09:21<44:56,  2.39it/s]
 30%|███████████████████████▎                                                      | 2750/9182 [09:21<43:00,  2.49it/s]
 30%|███████████████████████▎                                                      | 2751/9182 [09:21<53:51,  1.99it/s]
 30%|███████████████████████▍                                                      | 2752/9182 [09:22<54:42,  1.96it/s]
 30%|███████████████████████▍                                                      | 2754/9182 [09:23<43:03,  2.49it/s]
 30%|███████████████████████▍                                                      | 2755/9182 [09:23<43:23,  2.47it/s]
 30%|██████████████████████▊                                                     | 2756/9182 [09:24<1:02:27,  1.71it/s]
 30%|███████████████████████▍                                                      | 2757/9182 [09:25<52:23,  2.04it/s]
 30%|███████████████████████▍                                                      | 2758/9182 [09:25<49:25,  2.17it/s]
 30%|███████████████████████▍                                                      | 2759/9182 [09:25<42:10,  2.54it/s]
 30%|███████████████████████▍                                                      | 2760/9182 [09:25<36:56,  2.90it/s]
 30%|███████████████████████▍                                                      | 2761/9182 [09:25<29:31,  3.62it/s]
 30%|███████████████████████▍                                                      | 2762/9182 [09:26<26:17,  4.07it/s]
 30%|███████████████████████▍                                                      | 2763/9182 [09:26<25:22,  4.22it/s]
 30%|███████████████████████▍                                                      | 2764/9182 [09:26<41:45,  2.56it/s]
 30%|███████████████████████▍                                                      | 2765/9182 [09:27<33:49,  3.16it/s]
 30%|███████████████████████▍                                                      | 2766/9182 [09:27<35:12,  3.04it/s]
 30%|███████████████████████▌                                                      | 2767/9182 [09:28<48:06,  2.22it/s]
 30%|██████████████████████▉                                                     | 2768/9182 [09:29<1:06:47,  1.60it/s]
 30%|███████████████████████▌                                                      | 2769/9182 [09:29<54:26,  1.96it/s]
 30%|███████████████████████▌                                                      | 2770/9182 [09:29<46:37,  2.29it/s]
 30%|███████████████████████▌                                                      | 2771/9182 [09:30<44:55,  2.38it/s]
 30%|███████████████████████▌                                                      | 2772/9182 [09:30<35:49,  2.98it/s]
 30%|███████████████████████▌                                                      | 2773/9182 [09:30<33:39,  3.17it/s]
 30%|███████████████████████▌                                                      | 2774/9182 [09:31<47:29,  2.25it/s]
 30%|███████████████████████▌                                                      | 2775/9182 [09:31<45:25,  2.35it/s]
 30%|███████████████████████▌                                                      | 2776/9182 [09:32<51:52,  2.06it/s]
 30%|███████████████████████▌                                                      | 2777/9182 [09:32<43:31,  2.45it/s]
 30%|██████████████████████▉                                                     | 2778/9182 [09:34<1:26:06,  1.24it/s]
 30%|███████████████████████                                                     | 2779/9182 [09:34<1:03:55,  1.67it/s]
 30%|███████████████████████▋                                                      | 2783/9182 [09:34<31:31,  3.38it/s]
 30%|███████████████████████▋                                                      | 2784/9182 [09:34<30:57,  3.44it/s]
 30%|███████████████████████▋                                                      | 2786/9182 [09:35<24:04,  4.43it/s]
 30%|███████████████████████▋                                                      | 2787/9182 [09:35<22:41,  4.70it/s]
 30%|███████████████████████▋                                                      | 2788/9182 [09:35<21:55,  4.86it/s]
 30%|███████████████████████▋                                                      | 2792/9182 [09:36<19:37,  5.43it/s]
 30%|███████████████████████▋                                                      | 2793/9182 [09:36<24:16,  4.39it/s]
 30%|███████████████████████▋                                                      | 2794/9182 [09:37<30:44,  3.46it/s]
 30%|███████████████████████▋                                                      | 2795/9182 [09:37<27:58,  3.81it/s]
 30%|███████████████████████▊                                                      | 2796/9182 [09:37<24:30,  4.34it/s]
 30%|███████████████████████▊                                                      | 2797/9182 [09:37<23:51,  4.46it/s]
 30%|███████████████████████▊                                                      | 2798/9182 [09:38<37:07,  2.87it/s]
 30%|███████████████████████▊                                                      | 2799/9182 [09:38<34:53,  3.05it/s]
 30%|███████████████████████▊                                                      | 2800/9182 [09:38<28:34,  3.72it/s]
 31%|███████████████████████▊                                                      | 2801/9182 [09:39<29:15,  3.64it/s]
 31%|███████████████████████▊                                                      | 2802/9182 [09:39<40:32,  2.62it/s]
 31%|███████████████████████▊                                                      | 2803/9182 [09:39<33:01,  3.22it/s]
 31%|███████████████████████▊                                                      | 2804/9182 [09:40<31:30,  3.37it/s]
 31%|███████████████████████▊                                                      | 2805/9182 [09:40<43:23,  2.45it/s]
 31%|███████████████████████▊                                                      | 2807/9182 [09:41<27:54,  3.81it/s]
 31%|███████████████████████▊                                                      | 2808/9182 [09:41<26:54,  3.95it/s]
 31%|███████████████████████▉                                                      | 2812/9182 [09:41<16:54,  6.28it/s]
 31%|███████████████████████▉                                                      | 2813/9182 [09:41<16:34,  6.41it/s]
 31%|███████████████████████▉                                                      | 2814/9182 [09:42<22:30,  4.72it/s]
 31%|███████████████████████▉                                                      | 2815/9182 [09:42<22:33,  4.70it/s]
 31%|███████████████████████▉                                                      | 2816/9182 [09:42<22:51,  4.64it/s]
 31%|███████████████████████▉                                                      | 2819/9182 [09:42<18:37,  5.70it/s]
 31%|███████████████████████▉                                                      | 2820/9182 [09:43<27:47,  3.82it/s]
 31%|███████████████████████▉                                                      | 2821/9182 [09:44<32:13,  3.29it/s]
 31%|███████████████████████▉                                                      | 2822/9182 [09:44<31:18,  3.39it/s]
 31%|███████████████████████▉                                                      | 2823/9182 [09:44<27:46,  3.82it/s]
 31%|███████████████████████▉                                                      | 2825/9182 [09:44<21:22,  4.96it/s]
 31%|████████████████████████                                                      | 2829/9182 [09:45<15:28,  6.84it/s]
 31%|████████████████████████                                                      | 2831/9182 [09:45<18:39,  5.67it/s]
 31%|████████████████████████                                                      | 2834/9182 [09:46<19:27,  5.44it/s]
 31%|████████████████████████                                                      | 2835/9182 [09:46<23:38,  4.47it/s]
 31%|████████████████████████                                                      | 2836/9182 [09:47<22:22,  4.73it/s]
 31%|████████████████████████                                                      | 2837/9182 [09:47<33:34,  3.15it/s]
 31%|████████████████████████                                                      | 2838/9182 [09:47<29:10,  3.62it/s]
 31%|████████████████████████                                                      | 2839/9182 [09:48<36:21,  2.91it/s]
 31%|████████████████████████▏                                                     | 2840/9182 [09:48<33:33,  3.15it/s]
 31%|████████████████████████▏                                                     | 2841/9182 [09:48<33:41,  3.14it/s]
 31%|████████████████████████▏                                                     | 2842/9182 [09:49<30:34,  3.46it/s]
 31%|████████████████████████▏                                                     | 2843/9182 [09:49<27:37,  3.82it/s]
 31%|████████████████████████▏                                                     | 2844/9182 [09:49<25:40,  4.11it/s]
 31%|████████████████████████▏                                                     | 2847/9182 [09:49<15:16,  6.91it/s]
 31%|████████████████████████▏                                                     | 2849/9182 [09:49<13:07,  8.05it/s]
 31%|████████████████████████▏                                                     | 2850/9182 [09:50<15:19,  6.89it/s]
 31%|████████████████████████▏                                                     | 2852/9182 [09:50<13:40,  7.71it/s]
 31%|████████████████████████▏                                                     | 2853/9182 [09:50<21:02,  5.01it/s]
 31%|████████████████████████▏                                                     | 2854/9182 [09:50<20:40,  5.10it/s]
 31%|████████████████████████▎                                                     | 2855/9182 [09:51<20:44,  5.08it/s]
 31%|████████████████████████▎                                                     | 2859/9182 [09:51<10:11, 10.35it/s]
 31%|████████████████████████▎                                                     | 2861/9182 [09:51<16:00,  6.58it/s]
 31%|████████████████████████▎                                                     | 2863/9182 [09:52<15:30,  6.79it/s]
 31%|████████████████████████▎                                                     | 2865/9182 [09:53<29:57,  3.51it/s]
 31%|████████████████████████▎                                                     | 2866/9182 [09:53<33:24,  3.15it/s]
 31%|████████████████████████▎                                                     | 2867/9182 [09:53<31:45,  3.31it/s]
 31%|████████████████████████▎                                                     | 2868/9182 [09:54<28:11,  3.73it/s]
 31%|████████████████████████▎                                                     | 2869/9182 [09:54<31:02,  3.39it/s]
 31%|████████████████████████▍                                                     | 2870/9182 [09:55<34:18,  3.07it/s]
 31%|████████████████████████▍                                                     | 2871/9182 [09:55<37:33,  2.80it/s]
 31%|████████████████████████▍                                                     | 2872/9182 [09:55<35:07,  2.99it/s]
 31%|████████████████████████▍                                                     | 2873/9182 [09:55<30:16,  3.47it/s]
 31%|████████████████████████▍                                                     | 2874/9182 [09:56<32:02,  3.28it/s]
 31%|████████████████████████▍                                                     | 2875/9182 [09:56<40:37,  2.59it/s]
 31%|████████████████████████▍                                                     | 2878/9182 [09:57<24:52,  4.22it/s]
 31%|████████████████████████▍                                                     | 2879/9182 [09:57<30:22,  3.46it/s]
 31%|████████████████████████▍                                                     | 2880/9182 [09:57<27:22,  3.84it/s]
 31%|████████████████████████▍                                                     | 2881/9182 [09:57<24:55,  4.21it/s]
 31%|████████████████████████▌                                                     | 2885/9182 [09:58<11:57,  8.77it/s]
 31%|████████████████████████▌                                                     | 2887/9182 [09:58<20:07,  5.21it/s]
 31%|████████████████████████▌                                                     | 2890/9182 [09:58<15:34,  6.74it/s]
 31%|████████████████████████▌                                                     | 2892/9182 [09:59<17:12,  6.09it/s]
 32%|████████████████████████▌                                                     | 2893/9182 [10:00<22:22,  4.68it/s]
 32%|████████████████████████▌                                                     | 2894/9182 [10:00<30:57,  3.39it/s]
 32%|████████████████████████▌                                                     | 2895/9182 [10:00<29:47,  3.52it/s]
 32%|████████████████████████▌                                                     | 2896/9182 [10:01<27:59,  3.74it/s]
 32%|████████████████████████▌                                                     | 2897/9182 [10:01<29:29,  3.55it/s]
 32%|████████████████████████▌                                                     | 2898/9182 [10:01<33:45,  3.10it/s]
 32%|████████████████████████▋                                                     | 2899/9182 [10:01<28:19,  3.70it/s]

 32%|████████████████████████▋                                                     | 2901/9182 [10:01<18:34,  5.64it/s]
 32%|████████████████████████▋                                                     | 2903/9182 [10:02<15:08,  6.91it/s]
 32%|████████████████████████▋                                                     | 2904/9182 [10:02<15:09,  6.90it/s]
 32%|████████████████████████▋                                                     | 2905/9182 [10:02<18:18,  5.71it/s]
 32%|████████████████████████▋                                                     | 2906/9182 [10:02<19:23,  5.39it/s]
 32%|████████████████████████▋                                                     | 2907/9182 [10:03<21:52,  4.78it/s]
 32%|████████████████████████▋                                                     | 2908/9182 [10:03<23:48,  4.39it/s]
 32%|████████████████████████▋                                                     | 2909/9182 [10:03<28:04,  3.72it/s]
 32%|████████████████████████▋                                                     | 2910/9182 [10:04<43:54,  2.38it/s]
 32%|████████████████████████▋                                                     | 2911/9182 [10:05<46:42,  2.24it/s]
 32%|████████████████████████▋                                                     | 2912/9182 [10:05<45:45,  2.28it/s]
 32%|████████████████████████▋                                                     | 2913/9182 [10:06<48:39,  2.15it/s]
 32%|████████████████████████▊                                                     | 2914/9182 [10:06<41:24,  2.52it/s]
 32%|████████████████████████▊                                                     | 2915/9182 [10:06<43:02,  2.43it/s]
 32%|████████████████████████▊                                                     | 2916/9182 [10:07<54:50,  1.90it/s]
 32%|████████████████████████▊                                                     | 2917/9182 [10:08<59:31,  1.75it/s]
 32%|████████████████████████▊                                                     | 2918/9182 [10:08<56:51,  1.84it/s]
 32%|████████████████████████▊                                                     | 2919/9182 [10:09<51:00,  2.05it/s]
 32%|████████████████████████▊                                                     | 2920/9182 [10:09<46:35,  2.24it/s]
 32%|████████████████████████▊                                                     | 2921/9182 [10:09<38:04,  2.74it/s]
 32%|████████████████████████▊                                                     | 2922/9182 [10:09<35:13,  2.96it/s]
 32%|████████████████████████▊                                                     | 2923/9182 [10:10<32:43,  3.19it/s]
 32%|████████████████████████▊                                                     | 2924/9182 [10:10<27:30,  3.79it/s]
 32%|████████████████████████▊                                                     | 2925/9182 [10:10<28:19,  3.68it/s]
 32%|████████████████████████▊                                                     | 2926/9182 [10:10<31:16,  3.33it/s]
 32%|████████████████████████▊                                                     | 2927/9182 [10:11<25:41,  4.06it/s]
 32%|████████████████████████▊                                                     | 2928/9182 [10:11<30:01,  3.47it/s]
 32%|████████████████████████▉                                                     | 2929/9182 [10:11<34:12,  3.05it/s]
 32%|████████████████████████▉                                                     | 2930/9182 [10:12<38:06,  2.73it/s]
 32%|████████████████████████▎                                                   | 2931/9182 [10:13<1:01:08,  1.70it/s]
 32%|████████████████████████▎                                                   | 2932/9182 [10:13<1:02:20,  1.67it/s]
 32%|████████████████████████▎                                                   | 2933/9182 [10:14<1:03:12,  1.65it/s]
 32%|████████████████████████▉                                                     | 2934/9182 [10:15<55:17,  1.88it/s]
 32%|████████████████████████▉                                                     | 2935/9182 [10:15<43:51,  2.37it/s]
 32%|████████████████████████▉                                                     | 2936/9182 [10:15<46:42,  2.23it/s]
 32%|████████████████████████▉                                                     | 2937/9182 [10:16<46:01,  2.26it/s]
 32%|████████████████████████▉                                                     | 2938/9182 [10:16<52:48,  1.97it/s]
 32%|████████████████████████▉                                                     | 2939/9182 [10:17<46:01,  2.26it/s]
 32%|████████████████████████▎                                                   | 2940/9182 [10:17<1:01:57,  1.68it/s]
 32%|████████████████████████▉                                                     | 2941/9182 [10:18<47:08,  2.21it/s]
 32%|████████████████████████▉                                                     | 2942/9182 [10:18<47:11,  2.20it/s]
 32%|█████████████████████████                                                     | 2943/9182 [10:18<44:38,  2.33it/s]
 32%|█████████████████████████                                                     | 2944/9182 [10:19<36:04,  2.88it/s]
 32%|█████████████████████████                                                     | 2945/9182 [10:19<34:29,  3.01it/s]
 32%|█████████████████████████                                                     | 2946/9182 [10:19<30:38,  3.39it/s]
 32%|█████████████████████████                                                     | 2948/9182 [10:20<32:22,  3.21it/s]
 32%|█████████████████████████                                                     | 2949/9182 [10:20<34:51,  2.98it/s]
 32%|█████████████████████████                                                     | 2950/9182 [10:21<37:27,  2.77it/s]
 32%|█████████████████████████                                                     | 2951/9182 [10:21<41:27,  2.50it/s]
 32%|█████████████████████████                                                     | 2952/9182 [10:21<39:24,  2.63it/s]
 32%|█████████████████████████                                                     | 2953/9182 [10:22<34:48,  2.98it/s]
 32%|█████████████████████████                                                     | 2954/9182 [10:22<35:38,  2.91it/s]
 32%|█████████████████████████                                                     | 2955/9182 [10:23<52:26,  1.98it/s]
 32%|█████████████████████████                                                     | 2956/9182 [10:23<45:09,  2.30it/s]
 32%|█████████████████████████▏                                                    | 2958/9182 [10:24<53:59,  1.92it/s]
 32%|█████████████████████████▏                                                    | 2959/9182 [10:25<47:26,  2.19it/s]
 32%|█████████████████████████▏                                                    | 2960/9182 [10:25<40:38,  2.55it/s]
 32%|█████████████████████████▏                                                    | 2961/9182 [10:25<33:35,  3.09it/s]
 32%|█████████████████████████▏                                                    | 2962/9182 [10:25<31:52,  3.25it/s]
 32%|█████████████████████████▏                                                    | 2963/9182 [10:26<30:05,  3.44it/s]
 32%|█████████████████████████▏                                                    | 2964/9182 [10:26<38:49,  2.67it/s]
 32%|█████████████████████████▏                                                    | 2965/9182 [10:27<40:41,  2.55it/s]
 32%|█████████████████████████▏                                                    | 2966/9182 [10:27<41:30,  2.50it/s]
 32%|█████████████████████████▏                                                    | 2967/9182 [10:27<38:43,  2.68it/s]
 32%|█████████████████████████▏                                                    | 2968/9182 [10:28<40:38,  2.55it/s]
 32%|█████████████████████████▏                                                    | 2969/9182 [10:28<37:17,  2.78it/s]
 32%|█████████████████████████▏                                                    | 2970/9182 [10:29<54:26,  1.90it/s]
 32%|█████████████████████████▏                                                    | 2971/9182 [10:29<49:48,  2.08it/s]
 32%|█████████████████████████▏                                                    | 2972/9182 [10:30<46:01,  2.25it/s]
 32%|█████████████████████████▎                                                    | 2973/9182 [10:30<46:37,  2.22it/s]
 32%|█████████████████████████▎                                                    | 2974/9182 [10:31<43:54,  2.36it/s]
 32%|█████████████████████████▎                                                    | 2975/9182 [10:31<54:17,  1.91it/s]
 32%|█████████████████████████▎                                                    | 2976/9182 [10:32<44:55,  2.30it/s]
 32%|████████████████████████▋                                                   | 2977/9182 [10:33<1:08:50,  1.50it/s]
 32%|█████████████████████████▎                                                    | 2978/9182 [10:33<55:26,  1.86it/s]
 32%|█████████████████████████▎                                                    | 2979/9182 [10:34<49:44,  2.08it/s]
 32%|█████████████████████████▎                                                    | 2980/9182 [10:34<59:01,  1.75it/s]
 32%|█████████████████████████▎                                                    | 2981/9182 [10:35<52:36,  1.96it/s]
 32%|████████████████████████▋                                                   | 2982/9182 [10:36<1:06:46,  1.55it/s]
 32%|█████████████████████████▎                                                    | 2983/9182 [10:36<56:46,  1.82it/s]
 32%|█████████████████████████▎                                                    | 2984/9182 [10:36<44:28,  2.32it/s]
 33%|█████████████████████████▎                                                    | 2985/9182 [10:36<38:05,  2.71it/s]
 33%|█████████████████████████▎                                                    | 2986/9182 [10:36<33:46,  3.06it/s]
 33%|█████████████████████████▎                                                    | 2987/9182 [10:36<28:56,  3.57it/s]
 33%|█████████████████████████▍                                                    | 2989/9182 [10:37<18:07,  5.69it/s]
 33%|█████████████████████████▍                                                    | 2990/9182 [10:37<17:26,  5.92it/s]
 33%|█████████████████████████▍                                                    | 2992/9182 [10:37<12:52,  8.02it/s]
 33%|█████████████████████████▍                                                    | 2994/9182 [10:37<11:05,  9.29it/s]
 33%|█████████████████████████▍                                                    | 2996/9182 [10:37<15:42,  6.56it/s]
 33%|█████████████████████████▍                                                    | 2997/9182 [10:38<17:02,  6.05it/s]
 33%|█████████████████████████▍                                                    | 2998/9182 [10:38<16:49,  6.12it/s]
 33%|█████████████████████████▍                                                    | 2999/9182 [10:38<24:20,  4.23it/s]
 33%|█████████████████████████▍                                                    | 3000/9182 [10:39<27:29,  3.75it/s]
 33%|█████████████████████████▍                                                    | 3001/9182 [10:39<27:22,  3.76it/s]
 33%|█████████████████████████▌                                                    | 3002/9182 [10:39<32:53,  3.13it/s]
 33%|█████████████████████████▌                                                    | 3003/9182 [10:40<28:08,  3.66it/s]
 33%|█████████████████████████▌                                                    | 3004/9182 [10:40<37:17,  2.76it/s]
 33%|█████████████████████████▌                                                    | 3005/9182 [10:41<37:34,  2.74it/s]
 33%|█████████████████████████▌                                                    | 3006/9182 [10:41<35:20,  2.91it/s]
 33%|█████████████████████████▌                                                    | 3007/9182 [10:41<29:43,  3.46it/s]
 33%|█████████████████████████▌                                                    | 3008/9182 [10:41<26:07,  3.94it/s]
 33%|█████████████████████████▌                                                    | 3009/9182 [10:41<22:38,  4.54it/s]
 33%|█████████████████████████▌                                                    | 3010/9182 [10:41<19:11,  5.36it/s]
 33%|█████████████████████████▌                                                    | 3016/9182 [10:41<07:01, 14.63it/s]
 33%|█████████████████████████▋                                                    | 3018/9182 [10:42<14:47,  6.94it/s]
 33%|█████████████████████████▋                                                    | 3020/9182 [10:44<36:10,  2.84it/s]
 33%|█████████████████████████▋                                                    | 3025/9182 [10:44<19:54,  5.15it/s]
 33%|█████████████████████████▋                                                    | 3027/9182 [10:45<20:52,  4.91it/s]
 33%|█████████████████████████▋                                                    | 3029/9182 [10:45<22:18,  4.60it/s]
 33%|█████████████████████████▋                                                    | 3031/9182 [10:46<20:46,  4.93it/s]
 33%|█████████████████████████▊                                                    | 3032/9182 [10:46<22:17,  4.60it/s]
 33%|█████████████████████████▊                                                    | 3033/9182 [10:46<24:21,  4.21it/s]
 33%|█████████████████████████▊                                                    | 3034/9182 [10:47<28:51,  3.55it/s]
 33%|█████████████████████████▊                                                    | 3035/9182 [10:47<33:39,  3.04it/s]
 33%|█████████████████████████▊                                                    | 3036/9182 [10:47<30:14,  3.39it/s]
 33%|█████████████████████████▊                                                    | 3037/9182 [10:48<29:13,  3.50it/s]
 33%|█████████████████████████▊                                                    | 3039/9182 [10:48<20:02,  5.11it/s]
 33%|█████████████████████████▊                                                    | 3040/9182 [10:48<20:19,  5.04it/s]
 33%|█████████████████████████▊                                                    | 3045/9182 [10:48<14:02,  7.28it/s]
 33%|█████████████████████████▉                                                    | 3046/9182 [10:49<15:29,  6.60it/s]
 33%|█████████████████████████▉                                                    | 3047/9182 [10:49<17:25,  5.87it/s]
 33%|█████████████████████████▉                                                    | 3050/9182 [10:49<11:34,  8.83it/s]
 33%|█████████████████████████▉                                                    | 3052/9182 [10:50<15:27,  6.61it/s]
 33%|█████████████████████████▉                                                    | 3053/9182 [10:50<24:04,  4.24it/s]
 33%|█████████████████████████▉                                                    | 3054/9182 [10:50<26:27,  3.86it/s]
 33%|█████████████████████████▉                                                    | 3055/9182 [10:51<32:38,  3.13it/s]
 33%|█████████████████████████▉                                                    | 3056/9182 [10:51<29:23,  3.47it/s]
 33%|█████████████████████████▉                                                    | 3057/9182 [10:52<30:57,  3.30it/s]
 33%|█████████████████████████▉                                                    | 3060/9182 [10:52<18:09,  5.62it/s]
 33%|██████████████████████████                                                    | 3062/9182 [10:52<19:48,  5.15it/s]
 33%|██████████████████████████                                                    | 3063/9182 [10:52<19:14,  5.30it/s]
 33%|██████████████████████████                                                    | 3064/9182 [10:53<19:26,  5.25it/s]

 33%|██████████████████████████                                                    | 3065/9182 [10:53<20:51,  4.89it/s]
 33%|██████████████████████████                                                    | 3066/9182 [10:53<24:56,  4.09it/s]
 33%|██████████████████████████                                                    | 3067/9182 [10:54<29:01,  3.51it/s]
 33%|██████████████████████████                                                    | 3068/9182 [10:54<24:04,  4.23it/s]
 33%|██████████████████████████                                                    | 3069/9182 [10:54<24:12,  4.21it/s]
 33%|██████████████████████████                                                    | 3074/9182 [10:54<10:29,  9.70it/s]
 34%|██████████████████████████▏                                                   | 3076/9182 [10:54<09:41, 10.50it/s]
 34%|██████████████████████████▏                                                   | 3078/9182 [10:55<20:42,  4.91it/s]
 34%|██████████████████████████▏                                                   | 3079/9182 [10:56<21:42,  4.69it/s]
 34%|██████████████████████████▏                                                   | 3080/9182 [10:56<20:57,  4.85it/s]
 34%|██████████████████████████▏                                                   | 3081/9182 [10:56<28:51,  3.52it/s]
 34%|██████████████████████████▏                                                   | 3082/9182 [10:56<26:26,  3.85it/s]
 34%|██████████████████████████▏                                                   | 3083/9182 [10:57<23:55,  4.25it/s]
 34%|██████████████████████████▏                                                   | 3084/9182 [10:57<27:19,  3.72it/s]
 34%|██████████████████████████▏                                                   | 3085/9182 [10:57<25:57,  3.91it/s]
 34%|██████████████████████████▏                                                   | 3086/9182 [10:57<26:03,  3.90it/s]
 34%|██████████████████████████▏                                                   | 3087/9182 [10:58<25:47,  3.94it/s]
 34%|██████████████████████████▏                                                   | 3090/9182 [10:58<14:55,  6.80it/s]
 34%|██████████████████████████▎                                                   | 3091/9182 [10:58<21:38,  4.69it/s]
 34%|██████████████████████████▎                                                   | 3092/9182 [10:59<31:06,  3.26it/s]
 34%|██████████████████████████▎                                                   | 3093/9182 [10:59<26:58,  3.76it/s]
 34%|██████████████████████████▎                                                   | 3094/9182 [10:59<28:32,  3.56it/s]
 34%|██████████████████████████▎                                                   | 3098/9182 [11:00<13:42,  7.39it/s]
 34%|██████████████████████████▎                                                   | 3100/9182 [11:00<19:25,  5.22it/s]
 34%|██████████████████████████▎                                                   | 3101/9182 [11:01<22:28,  4.51it/s]
 34%|██████████████████████████▎                                                   | 3102/9182 [11:01<23:03,  4.39it/s]
 34%|██████████████████████████▎                                                   | 3103/9182 [11:01<26:02,  3.89it/s]
 34%|██████████████████████████▎                                                   | 3104/9182 [11:01<24:51,  4.08it/s]
 34%|██████████████████████████▍                                                   | 3105/9182 [11:02<21:55,  4.62it/s]
 34%|██████████████████████████▍                                                   | 3106/9182 [11:02<30:03,  3.37it/s]
 34%|██████████████████████████▍                                                   | 3107/9182 [11:02<27:05,  3.74it/s]
 34%|██████████████████████████▍                                                   | 3108/9182 [11:03<31:18,  3.23it/s]
 34%|██████████████████████████▍                                                   | 3109/9182 [11:03<33:23,  3.03it/s]
 34%|██████████████████████████▍                                                   | 3110/9182 [11:03<27:32,  3.68it/s]
 34%|██████████████████████████▍                                                   | 3111/9182 [11:04<31:03,  3.26it/s]
 34%|██████████████████████████▍                                                   | 3112/9182 [11:04<32:25,  3.12it/s]
 34%|██████████████████████████▍                                                   | 3116/9182 [11:04<20:03,  5.04it/s]
 34%|██████████████████████████▍                                                   | 3119/9182 [11:04<13:53,  7.27it/s]
 34%|██████████████████████████▌                                                   | 3122/9182 [11:05<13:11,  7.65it/s]
 34%|██████████████████████████▌                                                   | 3123/9182 [11:05<12:44,  7.92it/s]
 34%|██████████████████████████▌                                                   | 3124/9182 [11:06<18:51,  5.35it/s]
 34%|██████████████████████████▌                                                   | 3125/9182 [11:06<18:58,  5.32it/s]
 34%|██████████████████████████▌                                                   | 3126/9182 [11:06<31:48,  3.17it/s]
 34%|██████████████████████████▌                                                   | 3127/9182 [11:07<32:02,  3.15it/s]
 34%|██████████████████████████▌                                                   | 3128/9182 [11:07<31:27,  3.21it/s]
 34%|██████████████████████████▌                                                   | 3131/9182 [11:07<18:20,  5.50it/s]
 34%|██████████████████████████▌                                                   | 3132/9182 [11:08<25:03,  4.02it/s]
 34%|██████████████████████████▌                                                   | 3133/9182 [11:08<28:29,  3.54it/s]
 34%|██████████████████████████▌                                                   | 3134/9182 [11:09<28:53,  3.49it/s]
 34%|██████████████████████████▋                                                   | 3135/9182 [11:09<27:54,  3.61it/s]
 34%|██████████████████████████▋                                                   | 3136/9182 [11:09<36:55,  2.73it/s]
 34%|██████████████████████████▋                                                   | 3137/9182 [11:10<33:26,  3.01it/s]
 34%|██████████████████████████▋                                                   | 3138/9182 [11:10<38:19,  2.63it/s]
 34%|██████████████████████████▋                                                   | 3139/9182 [11:11<49:51,  2.02it/s]
 34%|██████████████████████████▋                                                   | 3140/9182 [11:12<46:56,  2.15it/s]
 34%|██████████████████████████▋                                                   | 3141/9182 [11:12<51:42,  1.95it/s]
 34%|██████████████████████████▋                                                   | 3142/9182 [11:12<43:29,  2.31it/s]
 34%|██████████████████████████▋                                                   | 3143/9182 [11:13<44:21,  2.27it/s]
 34%|██████████████████████████▋                                                   | 3144/9182 [11:13<46:45,  2.15it/s]
 34%|██████████████████████████▋                                                   | 3145/9182 [11:13<39:02,  2.58it/s]
 34%|██████████████████████████▋                                                   | 3146/9182 [11:14<40:44,  2.47it/s]
 34%|██████████████████████████▋                                                   | 3147/9182 [11:14<39:33,  2.54it/s]
 34%|██████████████████████████▋                                                   | 3148/9182 [11:14<33:51,  2.97it/s]
 34%|██████████████████████████▊                                                   | 3149/9182 [11:15<28:10,  3.57it/s]
 34%|██████████████████████████▊                                                   | 3150/9182 [11:15<32:47,  3.07it/s]
 34%|██████████████████████████▊                                                   | 3152/9182 [11:15<22:36,  4.44it/s]
 34%|██████████████████████████▊                                                   | 3153/9182 [11:15<23:16,  4.32it/s]
 34%|██████████████████████████▊                                                   | 3154/9182 [11:16<26:19,  3.82it/s]
 34%|██████████████████████████▊                                                   | 3155/9182 [11:17<39:15,  2.56it/s]
 34%|██████████████████████████▊                                                   | 3156/9182 [11:17<48:14,  2.08it/s]
 34%|██████████████████████████▊                                                   | 3157/9182 [11:18<44:05,  2.28it/s]
 34%|██████████████████████████▊                                                   | 3158/9182 [11:18<59:12,  1.70it/s]
 34%|██████████████████████████▏                                                 | 3159/9182 [11:20<1:15:18,  1.33it/s]
 34%|██████████████████████████▏                                                 | 3160/9182 [11:20<1:04:52,  1.55it/s]
 34%|██████████████████████████▊                                                   | 3161/9182 [11:20<55:16,  1.82it/s]
 34%|██████████████████████████▊                                                   | 3162/9182 [11:21<58:55,  1.70it/s]
 34%|██████████████████████████▊                                                   | 3163/9182 [11:21<46:24,  2.16it/s]
 34%|██████████████████████████▉                                                   | 3164/9182 [11:22<41:00,  2.45it/s]
 34%|██████████████████████████▉                                                   | 3165/9182 [11:22<36:25,  2.75it/s]
 35%|██████████████████████████▉                                                   | 3168/9182 [11:23<38:34,  2.60it/s]
 35%|██████████████████████████▉                                                   | 3169/9182 [11:23<33:46,  2.97it/s]
 35%|██████████████████████████▉                                                   | 3171/9182 [11:23<27:33,  3.63it/s]
 35%|██████████████████████████▉                                                   | 3174/9182 [11:24<23:44,  4.22it/s]
 35%|██████████████████████████▉                                                   | 3175/9182 [11:25<30:02,  3.33it/s]
 35%|██████████████████████████▉                                                   | 3176/9182 [11:25<41:40,  2.40it/s]
 35%|██████████████████████████▉                                                   | 3177/9182 [11:26<36:19,  2.76it/s]
 35%|██████████████████████████▉                                                   | 3178/9182 [11:26<31:43,  3.15it/s]
 35%|███████████████████████████                                                   | 3180/9182 [11:26<26:30,  3.77it/s]
 35%|███████████████████████████                                                   | 3183/9182 [11:26<19:01,  5.25it/s]
 35%|███████████████████████████                                                   | 3184/9182 [11:27<17:51,  5.60it/s]
 35%|███████████████████████████                                                   | 3185/9182 [11:27<22:18,  4.48it/s]
 35%|███████████████████████████                                                   | 3186/9182 [11:28<25:04,  3.99it/s]
 35%|███████████████████████████                                                   | 3187/9182 [11:28<31:53,  3.13it/s]
 35%|███████████████████████████                                                   | 3188/9182 [11:29<47:08,  2.12it/s]
 35%|███████████████████████████                                                   | 3189/9182 [11:29<39:49,  2.51it/s]
 35%|███████████████████████████                                                   | 3190/9182 [11:29<35:12,  2.84it/s]
 35%|███████████████████████████                                                   | 3191/9182 [11:30<37:41,  2.65it/s]
 35%|███████████████████████████                                                   | 3192/9182 [11:30<34:09,  2.92it/s]
 35%|███████████████████████████                                                   | 3193/9182 [11:31<50:01,  2.00it/s]
 35%|███████████████████████████▏                                                  | 3194/9182 [11:31<55:40,  1.79it/s]
 35%|███████████████████████████▏                                                  | 3195/9182 [11:32<53:28,  1.87it/s]
 35%|███████████████████████████▏                                                  | 3196/9182 [11:32<49:01,  2.04it/s]
 35%|███████████████████████████▏                                                  | 3197/9182 [11:33<41:06,  2.43it/s]
 35%|███████████████████████████▏                                                  | 3198/9182 [11:33<37:16,  2.68it/s]
 35%|███████████████████████████▏                                                  | 3199/9182 [11:33<38:23,  2.60it/s]
 35%|██████████████████████████▍                                                 | 3200/9182 [11:35<1:06:08,  1.51it/s]
 35%|███████████████████████████▏                                                  | 3201/9182 [11:35<50:49,  1.96it/s]
 35%|███████████████████████████▏                                                  | 3202/9182 [11:35<46:07,  2.16it/s]
 35%|███████████████████████████▏                                                  | 3203/9182 [11:36<43:53,  2.27it/s]
 35%|███████████████████████████▏                                                  | 3204/9182 [11:36<53:50,  1.85it/s]
 35%|███████████████████████████▏                                                  | 3205/9182 [11:37<48:09,  2.07it/s]
 35%|███████████████████████████▏                                                  | 3206/9182 [11:37<40:49,  2.44it/s]
 35%|███████████████████████████▎                                                  | 3210/9182 [11:37<16:36,  5.99it/s]
 35%|███████████████████████████▎                                                  | 3212/9182 [11:38<20:16,  4.91it/s]
 35%|███████████████████████████▎                                                  | 3214/9182 [11:39<36:26,  2.73it/s]
 35%|███████████████████████████▎                                                  | 3215/9182 [11:40<48:09,  2.06it/s]
 35%|███████████████████████████▎                                                  | 3217/9182 [11:41<56:20,  1.76it/s]
 35%|███████████████████████████▎                                                  | 3218/9182 [11:42<55:14,  1.80it/s]
 35%|███████████████████████████▎                                                  | 3219/9182 [11:43<59:09,  1.68it/s]
 35%|███████████████████████████▎                                                  | 3220/9182 [11:43<50:56,  1.95it/s]
 35%|███████████████████████████▎                                                  | 3221/9182 [11:43<41:34,  2.39it/s]
 35%|███████████████████████████▎                                                  | 3222/9182 [11:43<35:05,  2.83it/s]
 35%|███████████████████████████▍                                                  | 3224/9182 [11:44<27:44,  3.58it/s]
 35%|███████████████████████████▍                                                  | 3227/9182 [11:44<18:45,  5.29it/s]
 35%|███████████████████████████▍                                                  | 3228/9182 [11:44<20:55,  4.74it/s]
 35%|███████████████████████████▍                                                  | 3229/9182 [11:45<20:15,  4.90it/s]
 35%|███████████████████████████▍                                                  | 3230/9182 [11:45<25:41,  3.86it/s]
 35%|███████████████████████████▍                                                  | 3231/9182 [11:46<29:41,  3.34it/s]
 35%|███████████████████████████▍                                                  | 3232/9182 [11:46<35:53,  2.76it/s]
 35%|███████████████████████████▍                                                  | 3233/9182 [11:46<28:56,  3.43it/s]
 35%|███████████████████████████▍                                                  | 3234/9182 [11:47<31:31,  3.14it/s]
 35%|███████████████████████████▍                                                  | 3235/9182 [11:47<32:05,  3.09it/s]

 35%|███████████████████████████▍                                                  | 3236/9182 [11:47<27:35,  3.59it/s]
 35%|███████████████████████████▍                                                  | 3237/9182 [11:47<28:05,  3.53it/s]
 35%|███████████████████████████▌                                                  | 3238/9182 [11:47<27:42,  3.58it/s]
 35%|███████████████████████████▌                                                  | 3239/9182 [11:47<22:58,  4.31it/s]
 35%|███████████████████████████▌                                                  | 3240/9182 [11:48<19:22,  5.11it/s]
 35%|███████████████████████████▌                                                  | 3241/9182 [11:48<16:55,  5.85it/s]
 35%|███████████████████████████▌                                                  | 3244/9182 [11:48<11:05,  8.92it/s]
 35%|███████████████████████████▌                                                  | 3246/9182 [11:48<17:00,  5.82it/s]
 35%|███████████████████████████▌                                                  | 3248/9182 [11:49<14:46,  6.69it/s]
 35%|███████████████████████████▌                                                  | 3250/9182 [11:49<16:26,  6.01it/s]
 35%|███████████████████████████▌                                                  | 3251/9182 [11:49<20:03,  4.93it/s]
 35%|███████████████████████████▋                                                  | 3252/9182 [11:50<27:55,  3.54it/s]
 35%|███████████████████████████▋                                                  | 3253/9182 [11:50<29:43,  3.32it/s]
 35%|███████████████████████████▋                                                  | 3254/9182 [11:50<25:07,  3.93it/s]
 35%|███████████████████████████▋                                                  | 3255/9182 [11:51<25:50,  3.82it/s]
 35%|███████████████████████████▋                                                  | 3256/9182 [11:51<32:35,  3.03it/s]
 35%|███████████████████████████▋                                                  | 3257/9182 [11:51<28:45,  3.43it/s]
 35%|███████████████████████████▋                                                  | 3258/9182 [11:52<27:46,  3.55it/s]
 35%|███████████████████████████▋                                                  | 3259/9182 [11:52<33:38,  2.93it/s]
 36%|███████████████████████████▋                                                  | 3260/9182 [11:52<27:50,  3.55it/s]
 36%|███████████████████████████▋                                                  | 3261/9182 [11:53<28:31,  3.46it/s]
 36%|███████████████████████████▋                                                  | 3262/9182 [11:53<23:14,  4.25it/s]
 36%|███████████████████████████▋                                                  | 3266/9182 [11:53<15:59,  6.17it/s]
 36%|███████████████████████████▊                                                  | 3267/9182 [11:54<23:22,  4.22it/s]
 36%|███████████████████████████▊                                                  | 3268/9182 [11:54<28:18,  3.48it/s]
 36%|███████████████████████████▊                                                  | 3269/9182 [11:55<39:24,  2.50it/s]
 36%|███████████████████████████▊                                                  | 3270/9182 [11:56<38:23,  2.57it/s]
 36%|███████████████████████████▊                                                  | 3271/9182 [11:56<40:09,  2.45it/s]
 36%|███████████████████████████▊                                                  | 3272/9182 [11:56<34:06,  2.89it/s]
 36%|███████████████████████████▊                                                  | 3277/9182 [11:56<14:44,  6.67it/s]
 36%|███████████████████████████▊                                                  | 3279/9182 [11:56<13:13,  7.44it/s]
 36%|███████████████████████████▊                                                  | 3280/9182 [11:57<13:04,  7.52it/s]
 36%|███████████████████████████▊                                                  | 3281/9182 [11:57<15:15,  6.45it/s]
 36%|███████████████████████████▉                                                  | 3283/9182 [11:57<12:28,  7.89it/s]
 36%|███████████████████████████▉                                                  | 3284/9182 [11:57<14:18,  6.87it/s]
 36%|███████████████████████████▉                                                  | 3285/9182 [11:58<20:07,  4.89it/s]
 36%|███████████████████████████▉                                                  | 3286/9182 [11:58<20:02,  4.90it/s]
 36%|███████████████████████████▉                                                  | 3287/9182 [11:58<22:30,  4.37it/s]
 36%|███████████████████████████▉                                                  | 3288/9182 [11:59<27:07,  3.62it/s]
 36%|███████████████████████████▉                                                  | 3289/9182 [11:59<25:26,  3.86it/s]
 36%|███████████████████████████▉                                                  | 3290/9182 [11:59<21:33,  4.55it/s]
 36%|███████████████████████████▉                                                  | 3291/9182 [11:59<24:00,  4.09it/s]
 36%|███████████████████████████▉                                                  | 3292/9182 [11:59<22:43,  4.32it/s]
 36%|███████████████████████████▉                                                  | 3293/9182 [12:00<21:03,  4.66it/s]
 36%|███████████████████████████▉                                                  | 3294/9182 [12:00<22:30,  4.36it/s]
 36%|███████████████████████████▉                                                  | 3295/9182 [12:00<19:53,  4.93it/s]
 36%|███████████████████████████▉                                                  | 3296/9182 [12:00<24:04,  4.07it/s]
 36%|████████████████████████████                                                  | 3297/9182 [12:01<23:29,  4.18it/s]
 36%|████████████████████████████                                                  | 3298/9182 [12:01<24:58,  3.93it/s]
 36%|████████████████████████████                                                  | 3299/9182 [12:01<21:33,  4.55it/s]
 36%|████████████████████████████                                                  | 3301/9182 [12:01<14:26,  6.78it/s]
 36%|████████████████████████████                                                  | 3302/9182 [12:02<15:54,  6.16it/s]
 36%|████████████████████████████                                                  | 3303/9182 [12:02<23:49,  4.11it/s]
 36%|████████████████████████████                                                  | 3304/9182 [12:02<20:10,  4.86it/s]
 36%|████████████████████████████                                                  | 3305/9182 [12:02<20:02,  4.89it/s]
 36%|████████████████████████████                                                  | 3306/9182 [12:03<31:09,  3.14it/s]
 36%|████████████████████████████                                                  | 3307/9182 [12:03<31:32,  3.10it/s]
 36%|████████████████████████████                                                  | 3308/9182 [12:04<36:47,  2.66it/s]
 36%|████████████████████████████                                                  | 3309/9182 [12:04<42:41,  2.29it/s]
 36%|████████████████████████████                                                  | 3310/9182 [12:04<34:06,  2.87it/s]
 36%|████████████████████████████▏                                                 | 3311/9182 [12:05<32:41,  2.99it/s]
 36%|████████████████████████████▏                                                 | 3312/9182 [12:05<31:55,  3.06it/s]
 36%|████████████████████████████▏                                                 | 3315/9182 [12:05<16:30,  5.93it/s]
 36%|████████████████████████████▏                                                 | 3316/9182 [12:05<18:39,  5.24it/s]
 36%|████████████████████████████▏                                                 | 3317/9182 [12:05<19:12,  5.09it/s]
 36%|████████████████████████████▏                                                 | 3318/9182 [12:06<17:47,  5.50it/s]
 36%|████████████████████████████▏                                                 | 3319/9182 [12:07<34:12,  2.86it/s]
 36%|████████████████████████████▏                                                 | 3320/9182 [12:07<29:52,  3.27it/s]
 36%|████████████████████████████▏                                                 | 3321/9182 [12:07<26:08,  3.74it/s]
 36%|████████████████████████████▏                                                 | 3325/9182 [12:07<12:17,  7.94it/s]
 36%|████████████████████████████▎                                                 | 3327/9182 [12:07<13:45,  7.10it/s]
 36%|████████████████████████████▎                                                 | 3328/9182 [12:07<14:19,  6.81it/s]
 36%|████████████████████████████▎                                                 | 3329/9182 [12:08<14:51,  6.56it/s]
 36%|████████████████████████████▎                                                 | 3330/9182 [12:08<16:58,  5.74it/s]
 36%|████████████████████████████▎                                                 | 3331/9182 [12:08<19:56,  4.89it/s]
 36%|████████████████████████████▎                                                 | 3332/9182 [12:09<25:27,  3.83it/s]
 36%|████████████████████████████▎                                                 | 3333/9182 [12:09<26:25,  3.69it/s]
 36%|████████████████████████████▎                                                 | 3335/9182 [12:10<26:01,  3.75it/s]
 36%|████████████████████████████▎                                                 | 3336/9182 [12:10<30:18,  3.21it/s]
 36%|████████████████████████████▎                                                 | 3337/9182 [12:10<26:05,  3.73it/s]
 36%|████████████████████████████▎                                                 | 3338/9182 [12:10<28:59,  3.36it/s]
 36%|████████████████████████████▎                                                 | 3339/9182 [12:11<24:49,  3.92it/s]
 36%|████████████████████████████▍                                                 | 3341/9182 [12:11<23:34,  4.13it/s]
 36%|████████████████████████████▍                                                 | 3342/9182 [12:11<22:26,  4.34it/s]
 36%|████████████████████████████▍                                                 | 3343/9182 [12:11<22:01,  4.42it/s]
 36%|████████████████████████████▍                                                 | 3344/9182 [12:12<20:37,  4.72it/s]
 36%|████████████████████████████▍                                                 | 3346/9182 [12:12<15:10,  6.41it/s]
 36%|████████████████████████████▍                                                 | 3349/9182 [12:12<12:39,  7.68it/s]
 36%|████████████████████████████▍                                                 | 3350/9182 [12:12<12:50,  7.57it/s]
 36%|████████████████████████████▍                                                 | 3351/9182 [12:13<13:51,  7.01it/s]
 37%|████████████████████████████▍                                                 | 3352/9182 [12:13<18:31,  5.24it/s]
 37%|████████████████████████████▍                                                 | 3353/9182 [12:13<22:57,  4.23it/s]
 37%|████████████████████████████▍                                                 | 3354/9182 [12:13<22:17,  4.36it/s]
 37%|████████████████████████████▌                                                 | 3355/9182 [12:14<21:15,  4.57it/s]
 37%|████████████████████████████▌                                                 | 3356/9182 [12:14<18:25,  5.27it/s]
 37%|████████████████████████████▌                                                 | 3357/9182 [12:14<20:54,  4.64it/s]
 37%|████████████████████████████▌                                                 | 3358/9182 [12:14<22:32,  4.30it/s]
 37%|████████████████████████████▌                                                 | 3359/9182 [12:15<26:44,  3.63it/s]
 37%|████████████████████████████▌                                                 | 3360/9182 [12:15<26:51,  3.61it/s]
 37%|████████████████████████████▌                                                 | 3361/9182 [12:15<27:44,  3.50it/s]
 37%|████████████████████████████▌                                                 | 3362/9182 [12:15<23:34,  4.11it/s]
 37%|████████████████████████████▌                                                 | 3363/9182 [12:16<20:51,  4.65it/s]
 37%|████████████████████████████▌                                                 | 3364/9182 [12:16<34:18,  2.83it/s]
 37%|████████████████████████████▌                                                 | 3367/9182 [12:17<24:12,  4.00it/s]
 37%|████████████████████████████▌                                                 | 3368/9182 [12:17<21:28,  4.51it/s]
 37%|████████████████████████████▌                                                 | 3369/9182 [12:17<18:45,  5.17it/s]
 37%|████████████████████████████▋                                                 | 3372/9182 [12:17<11:56,  8.11it/s]
 37%|████████████████████████████▋                                                 | 3374/9182 [12:17<11:19,  8.55it/s]
 37%|████████████████████████████▋                                                 | 3376/9182 [12:18<10:36,  9.12it/s]
 37%|████████████████████████████▋                                                 | 3378/9182 [12:19<35:31,  2.72it/s]
 37%|████████████████████████████▋                                                 | 3379/9182 [12:20<35:29,  2.73it/s]
 37%|████████████████████████████▋                                                 | 3380/9182 [12:21<46:08,  2.10it/s]
 37%|████████████████████████████▋                                                 | 3381/9182 [12:21<41:01,  2.36it/s]
 37%|████████████████████████████▋                                                 | 3382/9182 [12:21<38:27,  2.51it/s]
 37%|████████████████████████████▋                                                 | 3383/9182 [12:22<39:33,  2.44it/s]
 37%|████████████████████████████▋                                                 | 3384/9182 [12:22<34:11,  2.83it/s]
 37%|████████████████████████████▊                                                 | 3389/9182 [12:22<13:52,  6.96it/s]
 37%|████████████████████████████▊                                                 | 3391/9182 [12:22<16:05,  6.00it/s]
 37%|████████████████████████████▊                                                 | 3392/9182 [12:22<15:33,  6.20it/s]
 37%|████████████████████████████▊                                                 | 3393/9182 [12:23<18:40,  5.17it/s]
 37%|████████████████████████████▊                                                 | 3394/9182 [12:23<19:28,  4.95it/s]
 37%|████████████████████████████▊                                                 | 3395/9182 [12:23<21:43,  4.44it/s]
 37%|████████████████████████████▊                                                 | 3396/9182 [12:24<19:52,  4.85it/s]
 37%|████████████████████████████▊                                                 | 3397/9182 [12:24<19:51,  4.85it/s]
 37%|████████████████████████████▊                                                 | 3398/9182 [12:24<20:05,  4.80it/s]
 37%|████████████████████████████▊                                                 | 3399/9182 [12:24<26:19,  3.66it/s]
 37%|████████████████████████████▉                                                 | 3404/9182 [12:25<14:13,  6.77it/s]
 37%|████████████████████████████▉                                                 | 3408/9182 [12:26<14:44,  6.53it/s]
 37%|████████████████████████████▉                                                 | 3409/9182 [12:26<16:46,  5.73it/s]
 37%|████████████████████████████▉                                                 | 3410/9182 [12:26<16:30,  5.83it/s]
 37%|████████████████████████████▉                                                 | 3411/9182 [12:26<16:27,  5.85it/s]
 37%|████████████████████████████▉                                                 | 3412/9182 [12:27<26:37,  3.61it/s]

 37%|████████████████████████████▉                                                 | 3413/9182 [12:27<23:36,  4.07it/s]
 37%|█████████████████████████████                                                 | 3414/9182 [12:27<22:51,  4.21it/s]
 37%|█████████████████████████████                                                 | 3415/9182 [12:27<20:00,  4.80it/s]
 37%|█████████████████████████████                                                 | 3416/9182 [12:27<18:02,  5.33it/s]
 37%|█████████████████████████████                                                 | 3417/9182 [12:28<16:41,  5.76it/s]
 37%|█████████████████████████████                                                 | 3419/9182 [12:28<12:41,  7.57it/s]
 37%|█████████████████████████████                                                 | 3420/9182 [12:28<11:56,  8.04it/s]
 37%|█████████████████████████████                                                 | 3421/9182 [12:28<17:58,  5.34it/s]
 37%|█████████████████████████████                                                 | 3423/9182 [12:28<13:25,  7.15it/s]
 37%|█████████████████████████████                                                 | 3425/9182 [12:29<17:12,  5.57it/s]
 37%|█████████████████████████████                                                 | 3426/9182 [12:29<20:18,  4.72it/s]
 37%|█████████████████████████████                                                 | 3427/9182 [12:29<17:57,  5.34it/s]
 37%|█████████████████████████████                                                 | 3428/9182 [12:30<26:35,  3.61it/s]
 37%|█████████████████████████████▏                                                | 3429/9182 [12:30<30:43,  3.12it/s]
 37%|█████████████████████████████▏                                                | 3430/9182 [12:31<35:10,  2.72it/s]
 37%|█████████████████████████████▏                                                | 3431/9182 [12:31<41:49,  2.29it/s]
 37%|█████████████████████████████▏                                                | 3432/9182 [12:32<45:24,  2.11it/s]
 37%|█████████████████████████████▏                                                | 3433/9182 [12:33<45:11,  2.12it/s]
 37%|█████████████████████████████▏                                                | 3434/9182 [12:33<46:01,  2.08it/s]
 37%|█████████████████████████████▏                                                | 3435/9182 [12:33<47:27,  2.02it/s]
 37%|█████████████████████████████▏                                                | 3436/9182 [12:34<44:33,  2.15it/s]
 37%|█████████████████████████████▏                                                | 3437/9182 [12:35<54:15,  1.76it/s]
 37%|█████████████████████████████▏                                                | 3438/9182 [12:35<43:59,  2.18it/s]
 37%|█████████████████████████████▏                                                | 3439/9182 [12:35<47:49,  2.00it/s]
 37%|█████████████████████████████▏                                                | 3440/9182 [12:36<59:24,  1.61it/s]
 37%|█████████████████████████████▏                                                | 3441/9182 [12:37<54:56,  1.74it/s]
 37%|█████████████████████████████▏                                                | 3442/9182 [12:37<47:38,  2.01it/s]
 37%|█████████████████████████████▏                                                | 3443/9182 [12:38<50:50,  1.88it/s]
 38%|█████████████████████████████▎                                                | 3444/9182 [12:38<40:51,  2.34it/s]
 38%|█████████████████████████████▎                                                | 3445/9182 [12:38<36:09,  2.64it/s]
 38%|█████████████████████████████▎                                                | 3446/9182 [12:39<55:05,  1.74it/s]
 38%|█████████████████████████████▎                                                | 3447/9182 [12:40<52:08,  1.83it/s]
 38%|█████████████████████████████▎                                                | 3448/9182 [12:40<41:39,  2.29it/s]
 38%|█████████████████████████████▎                                                | 3449/9182 [12:40<35:46,  2.67it/s]
 38%|█████████████████████████████▎                                                | 3450/9182 [12:41<33:07,  2.88it/s]
 38%|█████████████████████████████▎                                                | 3451/9182 [12:41<38:48,  2.46it/s]
 38%|█████████████████████████████▎                                                | 3452/9182 [12:41<33:15,  2.87it/s]
 38%|█████████████████████████████▎                                                | 3454/9182 [12:41<21:29,  4.44it/s]
 38%|█████████████████████████████▎                                                | 3455/9182 [12:42<27:04,  3.52it/s]
 38%|█████████████████████████████▎                                                | 3456/9182 [12:42<25:21,  3.76it/s]
 38%|█████████████████████████████▎                                                | 3457/9182 [12:42<24:02,  3.97it/s]
 38%|█████████████████████████████▍                                                | 3458/9182 [12:43<24:45,  3.85it/s]
 38%|█████████████████████████████▍                                                | 3459/9182 [12:43<26:12,  3.64it/s]
 38%|█████████████████████████████▍                                                | 3460/9182 [12:44<32:06,  2.97it/s]
 38%|█████████████████████████████▍                                                | 3461/9182 [12:44<38:01,  2.51it/s]
 38%|█████████████████████████████▍                                                | 3462/9182 [12:44<32:09,  2.96it/s]
 38%|█████████████████████████████▍                                                | 3463/9182 [12:44<30:22,  3.14it/s]
 38%|█████████████████████████████▍                                                | 3464/9182 [12:45<29:40,  3.21it/s]
 38%|█████████████████████████████▍                                                | 3468/9182 [12:45<12:43,  7.49it/s]
 38%|█████████████████████████████▍                                                | 3470/9182 [12:46<27:40,  3.44it/s]
 38%|█████████████████████████████▍                                                | 3471/9182 [12:46<26:15,  3.63it/s]
 38%|█████████████████████████████▍                                                | 3472/9182 [12:47<25:55,  3.67it/s]
 38%|█████████████████████████████▌                                                | 3473/9182 [12:47<29:13,  3.26it/s]
 38%|█████████████████████████████▌                                                | 3474/9182 [12:47<24:32,  3.88it/s]
 38%|█████████████████████████████▌                                                | 3475/9182 [12:47<29:49,  3.19it/s]
 38%|█████████████████████████████▌                                                | 3476/9182 [12:48<30:25,  3.13it/s]
 38%|█████████████████████████████▌                                                | 3477/9182 [12:48<28:04,  3.39it/s]
 38%|█████████████████████████████▌                                                | 3478/9182 [12:48<31:20,  3.03it/s]
 38%|█████████████████████████████▌                                                | 3479/9182 [12:49<26:56,  3.53it/s]
 38%|█████████████████████████████▌                                                | 3481/9182 [12:49<17:26,  5.45it/s]
 38%|█████████████████████████████▌                                                | 3482/9182 [12:49<25:17,  3.76it/s]
 38%|█████████████████████████████▌                                                | 3483/9182 [12:50<26:38,  3.57it/s]
 38%|█████████████████████████████▌                                                | 3484/9182 [12:50<22:25,  4.23it/s]
 38%|█████████████████████████████▌                                                | 3485/9182 [12:50<26:16,  3.61it/s]
 38%|█████████████████████████████▌                                                | 3486/9182 [12:51<26:32,  3.58it/s]
 38%|█████████████████████████████▌                                                | 3487/9182 [12:51<35:41,  2.66it/s]
 38%|█████████████████████████████▋                                                | 3488/9182 [12:51<32:35,  2.91it/s]
 38%|█████████████████████████████▋                                                | 3489/9182 [12:52<32:40,  2.90it/s]
 38%|█████████████████████████████▋                                                | 3490/9182 [12:52<28:18,  3.35it/s]
 38%|█████████████████████████████▋                                                | 3491/9182 [12:52<24:21,  3.89it/s]
 38%|█████████████████████████████▋                                                | 3492/9182 [12:52<20:20,  4.66it/s]
 38%|█████████████████████████████▋                                                | 3493/9182 [12:53<25:29,  3.72it/s]
 38%|█████████████████████████████▋                                                | 3494/9182 [12:53<25:18,  3.75it/s]
 38%|█████████████████████████████▋                                                | 3495/9182 [12:53<22:36,  4.19it/s]
 38%|█████████████████████████████▋                                                | 3496/9182 [12:53<26:53,  3.52it/s]
 38%|█████████████████████████████▋                                                | 3497/9182 [12:54<29:43,  3.19it/s]
 38%|█████████████████████████████▋                                                | 3498/9182 [12:54<30:53,  3.07it/s]
 38%|█████████████████████████████▋                                                | 3499/9182 [12:54<24:52,  3.81it/s]
 38%|█████████████████████████████▋                                                | 3500/9182 [12:54<22:55,  4.13it/s]
 38%|█████████████████████████████▋                                                | 3501/9182 [12:55<23:57,  3.95it/s]
 38%|█████████████████████████████▋                                                | 3502/9182 [12:55<24:20,  3.89it/s]
 38%|█████████████████████████████▊                                                | 3503/9182 [12:55<25:27,  3.72it/s]
 38%|█████████████████████████████▊                                                | 3504/9182 [12:55<26:57,  3.51it/s]
 38%|█████████████████████████████▊                                                | 3505/9182 [12:56<25:51,  3.66it/s]
 38%|█████████████████████████████▊                                                | 3506/9182 [12:56<26:44,  3.54it/s]
 38%|█████████████████████████████▊                                                | 3507/9182 [12:57<31:45,  2.98it/s]
 38%|█████████████████████████████▊                                                | 3508/9182 [12:57<43:08,  2.19it/s]
 38%|█████████████████████████████▊                                                | 3509/9182 [12:58<42:06,  2.25it/s]
 38%|█████████████████████████████▊                                                | 3510/9182 [12:58<41:09,  2.30it/s]
 38%|█████████████████████████████▊                                                | 3511/9182 [12:58<38:09,  2.48it/s]
 38%|█████████████████████████████▊                                                | 3512/9182 [12:59<40:00,  2.36it/s]
 38%|█████████████████████████████▊                                                | 3513/9182 [12:59<32:37,  2.90it/s]
 38%|█████████████████████████████▊                                                | 3514/9182 [12:59<35:28,  2.66it/s]
 38%|█████████████████████████████▊                                                | 3515/9182 [13:00<32:20,  2.92it/s]
 38%|█████████████████████████████▊                                                | 3516/9182 [13:00<34:50,  2.71it/s]
 38%|█████████████████████████████▉                                                | 3517/9182 [13:01<37:50,  2.50it/s]
 38%|█████████████████████████████▉                                                | 3518/9182 [13:01<33:03,  2.86it/s]
 38%|█████████████████████████████▉                                                | 3519/9182 [13:02<39:53,  2.37it/s]
 38%|█████████████████████████████▉                                                | 3520/9182 [13:02<55:21,  1.70it/s]
 38%|█████████████████████████████▉                                                | 3521/9182 [13:03<49:21,  1.91it/s]
 38%|█████████████████████████████▏                                              | 3522/9182 [13:04<1:05:17,  1.44it/s]
 38%|█████████████████████████████▏                                              | 3523/9182 [13:05<1:05:45,  1.43it/s]
 38%|█████████████████████████████▏                                              | 3524/9182 [13:05<1:04:49,  1.45it/s]
 38%|█████████████████████████████▉                                                | 3525/9182 [13:06<59:33,  1.58it/s]
 38%|█████████████████████████████▉                                                | 3526/9182 [13:06<55:42,  1.69it/s]
 38%|█████████████████████████████▉                                                | 3527/9182 [13:07<50:15,  1.88it/s]
 38%|█████████████████████████████▏                                              | 3528/9182 [13:08<1:03:04,  1.49it/s]
 38%|█████████████████████████████▏                                              | 3529/9182 [13:09<1:23:07,  1.13it/s]
 38%|█████████████████████████████▏                                              | 3530/9182 [13:09<1:05:22,  1.44it/s]
 38%|██████████████████████████████                                                | 3533/9182 [13:10<46:49,  2.01it/s]
 38%|██████████████████████████████                                                | 3534/9182 [13:11<43:02,  2.19it/s]
 38%|██████████████████████████████                                                | 3535/9182 [13:11<36:31,  2.58it/s]
 39%|██████████████████████████████                                                | 3541/9182 [13:11<18:10,  5.17it/s]
 39%|██████████████████████████████                                                | 3542/9182 [13:12<18:06,  5.19it/s]
 39%|██████████████████████████████                                                | 3543/9182 [13:12<21:26,  4.38it/s]
 39%|██████████████████████████████                                                | 3544/9182 [13:13<29:56,  3.14it/s]
 39%|██████████████████████████████                                                | 3545/9182 [13:13<26:45,  3.51it/s]
 39%|██████████████████████████████                                                | 3546/9182 [13:13<31:50,  2.95it/s]
 39%|██████████████████████████████▏                                               | 3547/9182 [13:13<29:10,  3.22it/s]
 39%|██████████████████████████████▏                                               | 3548/9182 [13:14<24:45,  3.79it/s]
 39%|██████████████████████████████▏                                               | 3551/9182 [13:14<13:28,  6.96it/s]
 39%|██████████████████████████████▏                                               | 3553/9182 [13:14<19:24,  4.83it/s]
 39%|██████████████████████████████▏                                               | 3554/9182 [13:15<18:02,  5.20it/s]
 39%|██████████████████████████████▏                                               | 3555/9182 [13:16<36:07,  2.60it/s]
 39%|██████████████████████████████▏                                               | 3557/9182 [13:16<25:16,  3.71it/s]
 39%|██████████████████████████████▏                                               | 3558/9182 [13:16<25:29,  3.68it/s]
 39%|██████████████████████████████▏                                               | 3559/9182 [13:17<34:47,  2.69it/s]
 39%|██████████████████████████████▏                                               | 3560/9182 [13:17<29:48,  3.14it/s]
 39%|██████████████████████████████▎                                               | 3561/9182 [13:17<35:02,  2.67it/s]
 39%|██████████████████████████████▎                                               | 3562/9182 [13:18<29:40,  3.16it/s]
 39%|██████████████████████████████▎                                               | 3564/9182 [13:18<21:43,  4.31it/s]
 39%|██████████████████████████████▎                                               | 3565/9182 [13:18<19:33,  4.79it/s]

 39%|██████████████████████████████▎                                               | 3566/9182 [13:18<17:30,  5.35it/s]
 39%|██████████████████████████████▎                                               | 3567/9182 [13:18<16:55,  5.53it/s]
 39%|██████████████████████████████▎                                               | 3569/9182 [13:18<13:04,  7.15it/s]
 39%|██████████████████████████████▎                                               | 3570/9182 [13:19<12:54,  7.25it/s]
 39%|██████████████████████████████▎                                               | 3571/9182 [13:19<13:07,  7.12it/s]
 39%|██████████████████████████████▎                                               | 3572/9182 [13:19<13:12,  7.08it/s]
 39%|██████████████████████████████▎                                               | 3575/9182 [13:19<14:16,  6.54it/s]
 39%|██████████████████████████████▍                                               | 3576/9182 [13:20<15:25,  6.06it/s]
 39%|██████████████████████████████▍                                               | 3577/9182 [13:20<18:14,  5.12it/s]
 39%|██████████████████████████████▍                                               | 3578/9182 [13:21<30:09,  3.10it/s]
 39%|██████████████████████████████▍                                               | 3579/9182 [13:21<28:12,  3.31it/s]
 39%|██████████████████████████████▍                                               | 3583/9182 [13:21<19:20,  4.82it/s]
 39%|██████████████████████████████▍                                               | 3584/9182 [13:22<17:50,  5.23it/s]
 39%|██████████████████████████████▍                                               | 3585/9182 [13:22<19:26,  4.80it/s]
 39%|██████████████████████████████▍                                               | 3586/9182 [13:22<25:35,  3.64it/s]
 39%|██████████████████████████████▍                                               | 3587/9182 [13:23<24:38,  3.78it/s]
 39%|██████████████████████████████▍                                               | 3588/9182 [13:23<22:41,  4.11it/s]
 39%|██████████████████████████████▍                                               | 3589/9182 [13:23<26:03,  3.58it/s]
 39%|██████████████████████████████▍                                               | 3590/9182 [13:23<25:38,  3.64it/s]
 39%|██████████████████████████████▌                                               | 3591/9182 [13:24<22:45,  4.09it/s]
 39%|██████████████████████████████▌                                               | 3592/9182 [13:24<21:42,  4.29it/s]
 39%|██████████████████████████████▌                                               | 3593/9182 [13:24<18:52,  4.94it/s]
 39%|██████████████████████████████▌                                               | 3594/9182 [13:24<19:30,  4.77it/s]
 39%|██████████████████████████████▌                                               | 3595/9182 [13:24<22:21,  4.17it/s]
 39%|██████████████████████████████▌                                               | 3596/9182 [13:25<20:58,  4.44it/s]
 39%|██████████████████████████████▌                                               | 3598/9182 [13:25<18:18,  5.08it/s]
 39%|██████████████████████████████▌                                               | 3602/9182 [13:25<09:14, 10.07it/s]
 39%|██████████████████████████████▌                                               | 3604/9182 [13:26<18:05,  5.14it/s]
 39%|██████████████████████████████▋                                               | 3606/9182 [13:27<20:20,  4.57it/s]
 39%|██████████████████████████████▋                                               | 3607/9182 [13:27<20:08,  4.61it/s]
 39%|██████████████████████████████▋                                               | 3608/9182 [13:27<20:12,  4.60it/s]
 39%|██████████████████████████████▋                                               | 3609/9182 [13:27<24:50,  3.74it/s]
 39%|██████████████████████████████▋                                               | 3610/9182 [13:27<22:14,  4.18it/s]
 39%|██████████████████████████████▋                                               | 3611/9182 [13:28<21:42,  4.28it/s]
 39%|██████████████████████████████▋                                               | 3612/9182 [13:28<24:07,  3.85it/s]
 39%|██████████████████████████████▋                                               | 3613/9182 [13:28<22:33,  4.11it/s]
 39%|██████████████████████████████▋                                               | 3614/9182 [13:29<31:45,  2.92it/s]
 39%|██████████████████████████████▋                                               | 3615/9182 [13:29<26:08,  3.55it/s]
 39%|██████████████████████████████▋                                               | 3616/9182 [13:29<24:45,  3.75it/s]
 39%|██████████████████████████████▋                                               | 3617/9182 [13:29<21:53,  4.24it/s]
 39%|██████████████████████████████▋                                               | 3618/9182 [13:29<18:12,  5.09it/s]
 39%|██████████████████████████████▊                                               | 3624/9182 [13:30<09:54,  9.34it/s]
 39%|██████████████████████████████▊                                               | 3625/9182 [13:30<15:35,  5.94it/s]
 39%|██████████████████████████████▊                                               | 3626/9182 [13:31<15:19,  6.04it/s]
 40%|██████████████████████████████▊                                               | 3627/9182 [13:31<17:47,  5.20it/s]
 40%|██████████████████████████████▊                                               | 3628/9182 [13:32<27:54,  3.32it/s]
 40%|██████████████████████████████▊                                               | 3629/9182 [13:32<28:28,  3.25it/s]
 40%|██████████████████████████████▊                                               | 3630/9182 [13:32<30:34,  3.03it/s]
 40%|██████████████████████████████▊                                               | 3631/9182 [13:33<28:06,  3.29it/s]
 40%|██████████████████████████████▊                                               | 3632/9182 [13:33<29:22,  3.15it/s]
 40%|██████████████████████████████▊                                               | 3633/9182 [13:33<26:16,  3.52it/s]
 40%|██████████████████████████████▉                                               | 3636/9182 [13:33<16:45,  5.51it/s]
 40%|██████████████████████████████▉                                               | 3637/9182 [13:34<25:49,  3.58it/s]
 40%|██████████████████████████████▉                                               | 3641/9182 [13:34<13:47,  6.70it/s]
 40%|██████████████████████████████▉                                               | 3643/9182 [13:34<11:31,  8.01it/s]
 40%|██████████████████████████████▉                                               | 3645/9182 [13:35<18:14,  5.06it/s]
 40%|██████████████████████████████▉                                               | 3646/9182 [13:35<19:33,  4.72it/s]
 40%|██████████████████████████████▉                                               | 3647/9182 [13:35<18:01,  5.12it/s]
 40%|███████████████████████████████                                               | 3652/9182 [13:36<09:21,  9.85it/s]
 40%|███████████████████████████████                                               | 3654/9182 [13:37<19:40,  4.68it/s]
 40%|███████████████████████████████                                               | 3656/9182 [13:37<18:12,  5.06it/s]
 40%|███████████████████████████████                                               | 3657/9182 [13:38<26:14,  3.51it/s]
 40%|███████████████████████████████                                               | 3658/9182 [13:38<25:32,  3.60it/s]
 40%|███████████████████████████████                                               | 3659/9182 [13:38<25:15,  3.65it/s]
 40%|███████████████████████████████                                               | 3660/9182 [13:39<22:49,  4.03it/s]
 40%|███████████████████████████████                                               | 3661/9182 [13:39<21:38,  4.25it/s]
 40%|███████████████████████████████                                               | 3662/9182 [13:39<22:55,  4.01it/s]
 40%|███████████████████████████████                                               | 3663/9182 [13:39<22:13,  4.14it/s]
 40%|███████████████████████████████▏                                              | 3665/9182 [13:40<19:40,  4.67it/s]
 40%|███████████████████████████████▏                                              | 3666/9182 [13:40<19:07,  4.81it/s]
 40%|███████████████████████████████▏                                              | 3667/9182 [13:40<18:17,  5.02it/s]
 40%|███████████████████████████████▏                                              | 3668/9182 [13:40<21:19,  4.31it/s]
 40%|███████████████████████████████▏                                              | 3669/9182 [13:41<23:54,  3.84it/s]
 40%|███████████████████████████████▏                                              | 3670/9182 [13:41<22:32,  4.08it/s]
 40%|███████████████████████████████▏                                              | 3671/9182 [13:41<26:06,  3.52it/s]
 40%|███████████████████████████████▏                                              | 3672/9182 [13:41<23:20,  3.93it/s]
 40%|███████████████████████████████▏                                              | 3673/9182 [13:42<25:13,  3.64it/s]
 40%|███████████████████████████████▏                                              | 3674/9182 [13:42<22:40,  4.05it/s]
 40%|███████████████████████████████▏                                              | 3675/9182 [13:42<30:26,  3.01it/s]
 40%|███████████████████████████████▏                                              | 3676/9182 [13:43<29:14,  3.14it/s]
 40%|███████████████████████████████▏                                              | 3677/9182 [13:43<25:25,  3.61it/s]
 40%|███████████████████████████████▏                                              | 3678/9182 [13:43<22:13,  4.13it/s]
 40%|███████████████████████████████▎                                              | 3679/9182 [13:43<18:57,  4.84it/s]
 40%|███████████████████████████████▎                                              | 3680/9182 [13:44<29:35,  3.10it/s]
 40%|███████████████████████████████▎                                              | 3681/9182 [13:44<23:44,  3.86it/s]
 40%|███████████████████████████████▎                                              | 3682/9182 [13:44<22:24,  4.09it/s]
 40%|███████████████████████████████▎                                              | 3683/9182 [13:44<22:57,  3.99it/s]
 40%|███████████████████████████████▎                                              | 3684/9182 [13:45<23:59,  3.82it/s]
 40%|███████████████████████████████▎                                              | 3685/9182 [13:45<20:13,  4.53it/s]
 40%|███████████████████████████████▎                                              | 3686/9182 [13:45<26:15,  3.49it/s]
 40%|███████████████████████████████▎                                              | 3690/9182 [13:46<16:03,  5.70it/s]
 40%|███████████████████████████████▎                                              | 3691/9182 [13:46<19:05,  4.79it/s]
 40%|███████████████████████████████▎                                              | 3693/9182 [13:46<16:39,  5.49it/s]
 40%|███████████████████████████████▍                                              | 3694/9182 [13:47<20:53,  4.38it/s]
 40%|███████████████████████████████▍                                              | 3695/9182 [13:47<30:32,  2.99it/s]
 40%|███████████████████████████████▍                                              | 3696/9182 [13:48<28:59,  3.15it/s]
 40%|███████████████████████████████▍                                              | 3697/9182 [13:48<34:01,  2.69it/s]
 40%|███████████████████████████████▍                                              | 3698/9182 [13:49<40:17,  2.27it/s]
 40%|███████████████████████████████▍                                              | 3699/9182 [13:49<38:06,  2.40it/s]
 40%|███████████████████████████████▍                                              | 3700/9182 [13:49<35:14,  2.59it/s]
 40%|███████████████████████████████▍                                              | 3701/9182 [13:50<47:26,  1.93it/s]
 40%|███████████████████████████████▍                                              | 3705/9182 [13:51<23:49,  3.83it/s]
 40%|███████████████████████████████▍                                              | 3706/9182 [13:51<22:39,  4.03it/s]
 40%|███████████████████████████████▍                                              | 3708/9182 [13:51<17:06,  5.33it/s]
 40%|███████████████████████████████▌                                              | 3709/9182 [13:51<16:51,  5.41it/s]
 40%|███████████████████████████████▌                                              | 3710/9182 [13:51<15:27,  5.90it/s]
 40%|███████████████████████████████▌                                              | 3711/9182 [13:52<14:32,  6.27it/s]
 40%|███████████████████████████████▌                                              | 3712/9182 [13:52<19:43,  4.62it/s]
 40%|███████████████████████████████▌                                              | 3713/9182 [13:52<24:01,  3.79it/s]
 40%|███████████████████████████████▌                                              | 3714/9182 [13:52<22:23,  4.07it/s]
 40%|███████████████████████████████▌                                              | 3715/9182 [13:53<29:13,  3.12it/s]
 41%|███████████████████████████████▌                                              | 3719/9182 [13:53<17:26,  5.22it/s]
 41%|███████████████████████████████▌                                              | 3720/9182 [13:54<17:48,  5.11it/s]
 41%|███████████████████████████████▌                                              | 3721/9182 [13:54<21:52,  4.16it/s]
 41%|███████████████████████████████▌                                              | 3722/9182 [13:54<20:00,  4.55it/s]
 41%|███████████████████████████████▋                                              | 3723/9182 [13:55<21:56,  4.15it/s]
 41%|███████████████████████████████▋                                              | 3724/9182 [13:55<23:10,  3.93it/s]
 41%|███████████████████████████████▋                                              | 3725/9182 [13:55<25:28,  3.57it/s]
 41%|███████████████████████████████▋                                              | 3726/9182 [13:56<21:05,  4.31it/s]
 41%|███████████████████████████████▋                                              | 3727/9182 [13:56<38:55,  2.34it/s]
 41%|███████████████████████████████▋                                              | 3728/9182 [13:57<42:10,  2.16it/s]
 41%|███████████████████████████████▋                                              | 3729/9182 [13:57<41:05,  2.21it/s]
 41%|███████████████████████████████▋                                              | 3730/9182 [13:57<35:35,  2.55it/s]
 41%|███████████████████████████████▋                                              | 3731/9182 [13:58<30:50,  2.94it/s]
 41%|███████████████████████████████▋                                              | 3732/9182 [13:58<43:11,  2.10it/s]
 41%|███████████████████████████████▋                                              | 3733/9182 [13:59<38:25,  2.36it/s]
 41%|███████████████████████████████▋                                              | 3734/9182 [14:00<56:21,  1.61it/s]
 41%|███████████████████████████████▋                                              | 3735/9182 [14:00<50:34,  1.80it/s]
 41%|███████████████████████████████▋                                              | 3736/9182 [14:01<53:57,  1.68it/s]
 41%|███████████████████████████████▋                                              | 3737/9182 [14:01<52:39,  1.72it/s]
 41%|███████████████████████████████▊                                              | 3738/9182 [14:02<43:59,  2.06it/s]
 41%|██████████████████████████████▉                                             | 3739/9182 [14:03<1:01:11,  1.48it/s]

 41%|███████████████████████████████▊                                              | 3740/9182 [14:03<53:31,  1.69it/s]
 41%|███████████████████████████████▊                                              | 3741/9182 [14:04<45:17,  2.00it/s]
 41%|███████████████████████████████▊                                              | 3742/9182 [14:04<37:09,  2.44it/s]
 41%|███████████████████████████████▊                                              | 3743/9182 [14:04<36:01,  2.52it/s]
 41%|███████████████████████████████▊                                              | 3744/9182 [14:04<31:40,  2.86it/s]
 41%|███████████████████████████████▊                                              | 3745/9182 [14:05<40:58,  2.21it/s]
 41%|███████████████████████████████▊                                              | 3746/9182 [14:05<32:58,  2.75it/s]
 41%|███████████████████████████████▊                                              | 3747/9182 [14:06<34:49,  2.60it/s]
 41%|███████████████████████████████▊                                              | 3748/9182 [14:06<33:22,  2.71it/s]
 41%|███████████████████████████████▊                                              | 3752/9182 [14:06<14:51,  6.09it/s]
 41%|███████████████████████████████▉                                              | 3754/9182 [14:06<14:20,  6.31it/s]
 41%|███████████████████████████████▉                                              | 3755/9182 [14:07<17:23,  5.20it/s]
 41%|███████████████████████████████▉                                              | 3756/9182 [14:08<30:32,  2.96it/s]
 41%|███████████████████████████████▉                                              | 3757/9182 [14:08<32:02,  2.82it/s]
 41%|███████████████████████████████▉                                              | 3758/9182 [14:09<37:44,  2.40it/s]
 41%|███████████████████████████████▉                                              | 3759/9182 [14:09<32:19,  2.80it/s]
 41%|███████████████████████████████▉                                              | 3760/9182 [14:09<31:45,  2.85it/s]
 41%|███████████████████████████████▉                                              | 3761/9182 [14:10<39:12,  2.30it/s]
 41%|███████████████████████████████▉                                              | 3762/9182 [14:10<37:26,  2.41it/s]
 41%|███████████████████████████████▉                                              | 3763/9182 [14:10<30:08,  3.00it/s]
 41%|███████████████████████████████▉                                              | 3764/9182 [14:10<25:17,  3.57it/s]
 41%|███████████████████████████████▉                                              | 3765/9182 [14:11<22:39,  3.98it/s]
 41%|███████████████████████████████▉                                              | 3766/9182 [14:11<27:14,  3.31it/s]
 41%|████████████████████████████████                                              | 3767/9182 [14:12<31:45,  2.84it/s]
 41%|████████████████████████████████                                              | 3768/9182 [14:12<25:55,  3.48it/s]
 41%|████████████████████████████████                                              | 3769/9182 [14:12<26:16,  3.43it/s]
 41%|████████████████████████████████                                              | 3770/9182 [14:12<22:28,  4.01it/s]
 41%|████████████████████████████████                                              | 3771/9182 [14:12<22:35,  3.99it/s]
 41%|████████████████████████████████                                              | 3775/9182 [14:13<12:50,  7.01it/s]
 41%|████████████████████████████████                                              | 3776/9182 [14:13<16:42,  5.39it/s]
 41%|████████████████████████████████                                              | 3777/9182 [14:14<20:10,  4.46it/s]
 41%|████████████████████████████████                                              | 3778/9182 [14:14<22:33,  3.99it/s]
 41%|████████████████████████████████                                              | 3780/9182 [14:14<18:03,  4.98it/s]
 41%|████████████████████████████████                                              | 3781/9182 [14:14<23:11,  3.88it/s]
 41%|████████████████████████████████▏                                             | 3784/9182 [14:15<14:19,  6.28it/s]
 41%|████████████████████████████████▏                                             | 3785/9182 [14:15<21:56,  4.10it/s]
 41%|████████████████████████████████▏                                             | 3786/9182 [14:16<26:10,  3.44it/s]
 41%|████████████████████████████████▏                                             | 3787/9182 [14:16<29:15,  3.07it/s]
 41%|████████████████████████████████▏                                             | 3788/9182 [14:16<25:49,  3.48it/s]
 41%|████████████████████████████████▏                                             | 3789/9182 [14:16<22:42,  3.96it/s]
 41%|████████████████████████████████▏                                             | 3790/9182 [14:17<22:47,  3.94it/s]
 41%|████████████████████████████████▏                                             | 3794/9182 [14:17<13:33,  6.62it/s]
 41%|████████████████████████████████▏                                             | 3795/9182 [14:17<14:27,  6.21it/s]
 41%|████████████████████████████████▏                                             | 3796/9182 [14:17<16:19,  5.50it/s]
 41%|████████████████████████████████▎                                             | 3798/9182 [14:18<15:06,  5.94it/s]
 41%|████████████████████████████████▎                                             | 3799/9182 [14:18<13:57,  6.42it/s]
 41%|████████████████████████████████▎                                             | 3800/9182 [14:18<12:57,  6.92it/s]
 41%|████████████████████████████████▎                                             | 3801/9182 [14:18<14:31,  6.18it/s]
 41%|████████████████████████████████▎                                             | 3802/9182 [14:19<17:44,  5.05it/s]
 41%|████████████████████████████████▎                                             | 3803/9182 [14:19<20:08,  4.45it/s]
 41%|████████████████████████████████▎                                             | 3804/9182 [14:19<23:39,  3.79it/s]
 41%|████████████████████████████████▎                                             | 3805/9182 [14:19<20:27,  4.38it/s]
 41%|████████████████████████████████▎                                             | 3806/9182 [14:20<28:10,  3.18it/s]
 41%|████████████████████████████████▎                                             | 3807/9182 [14:20<30:39,  2.92it/s]
 41%|████████████████████████████████▎                                             | 3808/9182 [14:21<34:05,  2.63it/s]
 41%|████████████████████████████████▎                                             | 3809/9182 [14:21<42:17,  2.12it/s]
 41%|████████████████████████████████▎                                             | 3810/9182 [14:22<33:41,  2.66it/s]
 42%|████████████████████████████████▎                                             | 3811/9182 [14:23<51:19,  1.74it/s]
 42%|████████████████████████████████▍                                             | 3812/9182 [14:23<43:18,  2.07it/s]
 42%|████████████████████████████████▍                                             | 3813/9182 [14:23<40:41,  2.20it/s]
 42%|████████████████████████████████▍                                             | 3814/9182 [14:24<44:20,  2.02it/s]
 42%|████████████████████████████████▍                                             | 3815/9182 [14:24<46:59,  1.90it/s]
 42%|████████████████████████████████▍                                             | 3816/9182 [14:25<39:35,  2.26it/s]
 42%|████████████████████████████████▍                                             | 3817/9182 [14:25<40:12,  2.22it/s]
 42%|████████████████████████████████▍                                             | 3818/9182 [14:25<36:16,  2.46it/s]
 42%|████████████████████████████████▍                                             | 3819/9182 [14:26<33:50,  2.64it/s]
 42%|████████████████████████████████▍                                             | 3822/9182 [14:26<17:08,  5.21it/s]
 42%|████████████████████████████████▍                                             | 3825/9182 [14:27<17:38,  5.06it/s]
 42%|████████████████████████████████▌                                             | 3826/9182 [14:27<20:44,  4.30it/s]
 42%|████████████████████████████████▌                                             | 3827/9182 [14:28<26:49,  3.33it/s]
 42%|████████████████████████████████▌                                             | 3828/9182 [14:28<34:09,  2.61it/s]
 42%|████████████████████████████████▌                                             | 3829/9182 [14:28<29:10,  3.06it/s]
 42%|████████████████████████████████▌                                             | 3830/9182 [14:28<25:39,  3.48it/s]
 42%|████████████████████████████████▌                                             | 3831/9182 [14:29<21:21,  4.18it/s]
 42%|████████████████████████████████▌                                             | 3835/9182 [14:29<10:03,  8.87it/s]
 42%|████████████████████████████████▌                                             | 3837/9182 [14:29<08:52, 10.04it/s]
 42%|████████████████████████████████▌                                             | 3839/9182 [14:29<08:25, 10.58it/s]
 42%|████████████████████████████████▋                                             | 3841/9182 [14:29<08:59,  9.90it/s]
 42%|████████████████████████████████▋                                             | 3843/9182 [14:29<07:43, 11.53it/s]
 42%|████████████████████████████████▋                                             | 3845/9182 [14:30<08:38, 10.29it/s]
 42%|████████████████████████████████▋                                             | 3847/9182 [14:30<10:52,  8.18it/s]
 42%|████████████████████████████████▋                                             | 3849/9182 [14:31<20:52,  4.26it/s]
 42%|████████████████████████████████▋                                             | 3850/9182 [14:32<21:36,  4.11it/s]
 42%|████████████████████████████████▋                                             | 3851/9182 [14:32<28:08,  3.16it/s]
 42%|████████████████████████████████▋                                             | 3852/9182 [14:32<30:54,  2.87it/s]
 42%|████████████████████████████████▋                                             | 3853/9182 [14:32<26:25,  3.36it/s]
 42%|████████████████████████████████▋                                             | 3854/9182 [14:33<23:34,  3.77it/s]
 42%|████████████████████████████████▊                                             | 3857/9182 [14:33<13:31,  6.56it/s]
 42%|████████████████████████████████▊                                             | 3858/9182 [14:33<13:17,  6.68it/s]
 42%|████████████████████████████████▊                                             | 3859/9182 [14:33<14:05,  6.30it/s]
 42%|████████████████████████████████▊                                             | 3860/9182 [14:33<15:58,  5.55it/s]
 42%|████████████████████████████████▊                                             | 3861/9182 [14:34<17:04,  5.19it/s]
 42%|████████████████████████████████▊                                             | 3863/9182 [14:34<15:07,  5.86it/s]
 42%|████████████████████████████████▊                                             | 3864/9182 [14:34<14:18,  6.20it/s]
 42%|████████████████████████████████▊                                             | 3865/9182 [14:35<21:50,  4.06it/s]
 42%|████████████████████████████████▊                                             | 3866/9182 [14:35<25:54,  3.42it/s]
 42%|████████████████████████████████▊                                             | 3867/9182 [14:35<26:48,  3.31it/s]
 42%|████████████████████████████████▊                                             | 3868/9182 [14:36<32:44,  2.70it/s]
 42%|████████████████████████████████▊                                             | 3869/9182 [14:36<30:45,  2.88it/s]
 42%|████████████████████████████████▉                                             | 3870/9182 [14:36<30:47,  2.87it/s]
 42%|████████████████████████████████▉                                             | 3871/9182 [14:37<27:57,  3.17it/s]
 42%|████████████████████████████████▉                                             | 3875/9182 [14:37<13:13,  6.69it/s]
 42%|████████████████████████████████▉                                             | 3878/9182 [14:37<12:14,  7.22it/s]
 42%|████████████████████████████████▉                                             | 3881/9182 [14:38<11:17,  7.83it/s]
 42%|████████████████████████████████▉                                             | 3883/9182 [14:38<14:48,  5.97it/s]
 42%|████████████████████████████████▉                                             | 3884/9182 [14:38<15:28,  5.70it/s]
 42%|█████████████████████████████████                                             | 3885/9182 [14:38<15:25,  5.72it/s]
 42%|█████████████████████████████████                                             | 3886/9182 [14:39<16:20,  5.40it/s]
 42%|█████████████████████████████████                                             | 3887/9182 [14:39<16:44,  5.27it/s]
 42%|█████████████████████████████████                                             | 3888/9182 [14:39<20:45,  4.25it/s]
 42%|█████████████████████████████████                                             | 3889/9182 [14:40<18:55,  4.66it/s]
 42%|█████████████████████████████████                                             | 3890/9182 [14:40<24:00,  3.67it/s]
 42%|█████████████████████████████████                                             | 3891/9182 [14:40<26:32,  3.32it/s]
 42%|█████████████████████████████████                                             | 3892/9182 [14:40<22:55,  3.84it/s]
 42%|█████████████████████████████████                                             | 3893/9182 [14:41<26:10,  3.37it/s]
 42%|█████████████████████████████████                                             | 3894/9182 [14:41<25:07,  3.51it/s]
 42%|█████████████████████████████████                                             | 3895/9182 [14:41<26:36,  3.31it/s]
 42%|█████████████████████████████████                                             | 3896/9182 [14:42<26:00,  3.39it/s]
 42%|█████████████████████████████████                                             | 3897/9182 [14:42<23:06,  3.81it/s]
 42%|█████████████████████████████████                                             | 3898/9182 [14:42<26:23,  3.34it/s]
 42%|█████████████████████████████████                                             | 3899/9182 [14:43<24:54,  3.53it/s]
 42%|█████████████████████████████████▏                                            | 3900/9182 [14:43<23:10,  3.80it/s]
 42%|█████████████████████████████████▏                                            | 3901/9182 [14:43<20:34,  4.28it/s]
 43%|█████████████████████████████████▏                                            | 3906/9182 [14:43<09:54,  8.87it/s]
 43%|█████████████████████████████████▏                                            | 3908/9182 [14:43<10:17,  8.53it/s]
 43%|█████████████████████████████████▏                                            | 3909/9182 [14:44<11:18,  7.77it/s]
 43%|█████████████████████████████████▏                                            | 3910/9182 [14:44<10:54,  8.06it/s]
 43%|█████████████████████████████████▏                                            | 3911/9182 [14:44<14:06,  6.23it/s]
 43%|█████████████████████████████████▏                                            | 3912/9182 [14:45<24:10,  3.63it/s]
 43%|█████████████████████████████████▏                                            | 3913/9182 [14:45<26:07,  3.36it/s]
 43%|█████████████████████████████████▏                                            | 3914/9182 [14:46<31:38,  2.77it/s]
 43%|█████████████████████████████████▎                                            | 3917/9182 [14:46<19:44,  4.44it/s]

 43%|█████████████████████████████████▎                                            | 3918/9182 [14:47<31:47,  2.76it/s]
 43%|█████████████████████████████████▎                                            | 3919/9182 [14:47<27:02,  3.24it/s]
 43%|█████████████████████████████████▎                                            | 3920/9182 [14:47<26:19,  3.33it/s]
 43%|█████████████████████████████████▎                                            | 3921/9182 [14:48<36:02,  2.43it/s]
 43%|█████████████████████████████████▎                                            | 3925/9182 [14:48<16:37,  5.27it/s]
 43%|█████████████████████████████████▎                                            | 3927/9182 [14:48<16:21,  5.36it/s]
 43%|█████████████████████████████████▎                                            | 3928/9182 [14:49<16:15,  5.38it/s]
 43%|█████████████████████████████████▍                                            | 3930/9182 [14:49<12:39,  6.92it/s]
 43%|█████████████████████████████████▍                                            | 3932/9182 [14:49<11:34,  7.56it/s]
 43%|█████████████████████████████████▍                                            | 3934/9182 [14:49<11:34,  7.56it/s]
 43%|█████████████████████████████████▍                                            | 3935/9182 [14:49<14:07,  6.19it/s]
 43%|█████████████████████████████████▍                                            | 3936/9182 [14:50<25:29,  3.43it/s]
 43%|█████████████████████████████████▍                                            | 3937/9182 [14:51<32:34,  2.68it/s]
 43%|█████████████████████████████████▍                                            | 3938/9182 [14:51<27:42,  3.15it/s]
 43%|█████████████████████████████████▍                                            | 3939/9182 [14:51<26:26,  3.30it/s]
 43%|█████████████████████████████████▍                                            | 3940/9182 [14:52<26:30,  3.30it/s]
 43%|█████████████████████████████████▍                                            | 3941/9182 [14:52<21:55,  3.98it/s]
 43%|█████████████████████████████████▍                                            | 3942/9182 [14:52<21:14,  4.11it/s]
 43%|█████████████████████████████████▍                                            | 3943/9182 [14:52<23:12,  3.76it/s]
 43%|█████████████████████████████████▌                                            | 3944/9182 [14:52<21:17,  4.10it/s]
 43%|█████████████████████████████████▌                                            | 3945/9182 [14:53<21:11,  4.12it/s]
 43%|█████████████████████████████████▌                                            | 3946/9182 [14:53<20:02,  4.35it/s]
 43%|█████████████████████████████████▌                                            | 3947/9182 [14:53<23:05,  3.78it/s]
 43%|█████████████████████████████████▌                                            | 3950/9182 [14:53<12:18,  7.08it/s]
 43%|█████████████████████████████████▌                                            | 3953/9182 [14:54<08:44,  9.97it/s]
 43%|█████████████████████████████████▌                                            | 3955/9182 [14:54<11:42,  7.44it/s]
 43%|█████████████████████████████████▌                                            | 3957/9182 [14:54<12:00,  7.25it/s]
 43%|█████████████████████████████████▌                                            | 3958/9182 [14:55<13:37,  6.39it/s]
 43%|█████████████████████████████████▋                                            | 3959/9182 [14:55<13:02,  6.68it/s]
 43%|█████████████████████████████████▋                                            | 3960/9182 [14:55<14:26,  6.02it/s]
 43%|█████████████████████████████████▋                                            | 3961/9182 [14:55<18:03,  4.82it/s]
 43%|█████████████████████████████████▋                                            | 3964/9182 [14:56<10:35,  8.21it/s]
 43%|█████████████████████████████████▋                                            | 3966/9182 [14:57<26:39,  3.26it/s]
 43%|█████████████████████████████████▋                                            | 3967/9182 [14:57<26:56,  3.23it/s]
 43%|█████████████████████████████████▋                                            | 3968/9182 [14:57<25:47,  3.37it/s]
 43%|█████████████████████████████████▋                                            | 3969/9182 [14:57<24:56,  3.48it/s]
 43%|█████████████████████████████████▋                                            | 3970/9182 [14:58<21:33,  4.03it/s]
 43%|█████████████████████████████████▋                                            | 3971/9182 [14:58<23:17,  3.73it/s]
 43%|█████████████████████████████████▊                                            | 3974/9182 [14:58<13:02,  6.65it/s]
 43%|█████████████████████████████████▊                                            | 3976/9182 [14:58<11:19,  7.66it/s]
 43%|█████████████████████████████████▊                                            | 3979/9182 [14:59<14:17,  6.07it/s]
 43%|█████████████████████████████████▊                                            | 3980/9182 [14:59<16:03,  5.40it/s]
 43%|█████████████████████████████████▊                                            | 3981/9182 [15:00<15:18,  5.66it/s]
 43%|█████████████████████████████████▊                                            | 3982/9182 [15:01<29:15,  2.96it/s]
 43%|█████████████████████████████████▊                                            | 3983/9182 [15:01<28:59,  2.99it/s]
 43%|█████████████████████████████████▊                                            | 3984/9182 [15:01<30:12,  2.87it/s]
 43%|█████████████████████████████████▊                                            | 3985/9182 [15:02<32:42,  2.65it/s]
 43%|█████████████████████████████████▊                                            | 3986/9182 [15:02<31:27,  2.75it/s]
 43%|█████████████████████████████████▊                                            | 3987/9182 [15:02<28:06,  3.08it/s]
 43%|█████████████████████████████████▉                                            | 3988/9182 [15:02<28:36,  3.03it/s]
 43%|█████████████████████████████████▉                                            | 3992/9182 [15:03<15:47,  5.48it/s]
 43%|█████████████████████████████████▉                                            | 3993/9182 [15:03<14:44,  5.86it/s]
 43%|█████████████████████████████████▉                                            | 3994/9182 [15:03<17:50,  4.85it/s]
 44%|█████████████████████████████████▉                                            | 3995/9182 [15:04<21:08,  4.09it/s]
 44%|█████████████████████████████████▉                                            | 3996/9182 [15:04<26:23,  3.27it/s]
 44%|█████████████████████████████████▉                                            | 3997/9182 [15:04<24:04,  3.59it/s]
 44%|█████████████████████████████████▉                                            | 3998/9182 [15:05<22:13,  3.89it/s]
 44%|█████████████████████████████████▉                                            | 3999/9182 [15:05<23:57,  3.61it/s]
 44%|█████████████████████████████████▉                                            | 4000/9182 [15:05<24:02,  3.59it/s]
 44%|█████████████████████████████████▉                                            | 4001/9182 [15:05<20:34,  4.20it/s]
 44%|█████████████████████████████████▉                                            | 4002/9182 [15:05<19:45,  4.37it/s]
 44%|██████████████████████████████████                                            | 4003/9182 [15:06<17:41,  4.88it/s]
 44%|██████████████████████████████████                                            | 4004/9182 [15:06<17:29,  4.94it/s]
 44%|██████████████████████████████████                                            | 4008/9182 [15:06<08:05, 10.66it/s]
 44%|██████████████████████████████████                                            | 4010/9182 [15:07<15:05,  5.71it/s]
 44%|██████████████████████████████████                                            | 4012/9182 [15:07<16:52,  5.10it/s]
 44%|██████████████████████████████████                                            | 4013/9182 [15:08<32:56,  2.62it/s]
 44%|██████████████████████████████████                                            | 4014/9182 [15:08<28:40,  3.00it/s]
 44%|██████████████████████████████████▏                                           | 4021/9182 [15:09<13:13,  6.51it/s]
 44%|██████████████████████████████████▏                                           | 4025/9182 [15:09<10:42,  8.03it/s]
 44%|██████████████████████████████████▏                                           | 4027/9182 [15:10<11:26,  7.51it/s]
 44%|██████████████████████████████████▏                                           | 4029/9182 [15:11<18:18,  4.69it/s]
 44%|██████████████████████████████████▏                                           | 4030/9182 [15:11<23:05,  3.72it/s]
 44%|██████████████████████████████████▏                                           | 4031/9182 [15:12<25:00,  3.43it/s]
 44%|██████████████████████████████████▎                                           | 4032/9182 [15:12<22:22,  3.84it/s]
 44%|██████████████████████████████████▎                                           | 4033/9182 [15:12<21:09,  4.05it/s]
 44%|██████████████████████████████████▎                                           | 4034/9182 [15:12<23:04,  3.72it/s]
 44%|██████████████████████████████████▎                                           | 4035/9182 [15:13<23:19,  3.68it/s]
 44%|██████████████████████████████████▎                                           | 4036/9182 [15:13<29:10,  2.94it/s]
 44%|██████████████████████████████████▎                                           | 4037/9182 [15:13<27:49,  3.08it/s]
 44%|██████████████████████████████████▎                                           | 4038/9182 [15:14<31:39,  2.71it/s]
 44%|██████████████████████████████████▎                                           | 4039/9182 [15:15<40:05,  2.14it/s]
 44%|██████████████████████████████████▎                                           | 4041/9182 [15:15<31:34,  2.71it/s]
 44%|██████████████████████████████████▎                                           | 4042/9182 [15:16<35:21,  2.42it/s]
 44%|██████████████████████████████████▎                                           | 4043/9182 [15:16<37:22,  2.29it/s]
 44%|██████████████████████████████████▎                                           | 4044/9182 [15:17<40:05,  2.14it/s]
 44%|██████████████████████████████████▎                                           | 4045/9182 [15:17<39:32,  2.17it/s]
 44%|██████████████████████████████████▎                                           | 4046/9182 [15:18<48:03,  1.78it/s]
 44%|██████████████████████████████████▍                                           | 4047/9182 [15:18<38:05,  2.25it/s]
 44%|██████████████████████████████████▍                                           | 4048/9182 [15:19<41:23,  2.07it/s]
 44%|██████████████████████████████████▍                                           | 4049/9182 [15:19<39:43,  2.15it/s]
 44%|██████████████████████████████████▍                                           | 4050/9182 [15:20<42:25,  2.02it/s]
 44%|██████████████████████████████████▍                                           | 4052/9182 [15:20<28:51,  2.96it/s]
 44%|██████████████████████████████████▍                                           | 4053/9182 [15:21<43:59,  1.94it/s]
 44%|██████████████████████████████████▍                                           | 4054/9182 [15:21<36:46,  2.32it/s]
 44%|██████████████████████████████████▍                                           | 4055/9182 [15:22<39:53,  2.14it/s]
 44%|██████████████████████████████████▍                                           | 4056/9182 [15:23<48:27,  1.76it/s]
 44%|██████████████████████████████████▍                                           | 4057/9182 [15:23<44:05,  1.94it/s]
 44%|██████████████████████████████████▍                                           | 4058/9182 [15:23<34:16,  2.49it/s]
 44%|██████████████████████████████████▍                                           | 4059/9182 [15:23<29:05,  2.93it/s]
 44%|██████████████████████████████████▍                                           | 4060/9182 [15:24<26:52,  3.18it/s]
 44%|██████████████████████████████████▍                                           | 4061/9182 [15:24<26:02,  3.28it/s]
 44%|██████████████████████████████████▌                                           | 4062/9182 [15:24<23:31,  3.63it/s]
 44%|██████████████████████████████████▌                                           | 4063/9182 [15:24<27:06,  3.15it/s]
 44%|██████████████████████████████████▌                                           | 4064/9182 [15:25<24:16,  3.51it/s]
 44%|██████████████████████████████████▌                                           | 4065/9182 [15:25<21:02,  4.05it/s]
 44%|██████████████████████████████████▌                                           | 4066/9182 [15:25<20:23,  4.18it/s]
 44%|██████████████████████████████████▌                                           | 4067/9182 [15:25<22:34,  3.78it/s]
 44%|██████████████████████████████████▌                                           | 4068/9182 [15:26<21:22,  3.99it/s]
 44%|██████████████████████████████████▌                                           | 4069/9182 [15:26<22:07,  3.85it/s]
 44%|██████████████████████████████████▌                                           | 4070/9182 [15:26<28:08,  3.03it/s]
 44%|██████████████████████████████████▌                                           | 4071/9182 [15:27<30:35,  2.78it/s]
 44%|██████████████████████████████████▌                                           | 4075/9182 [15:27<12:48,  6.65it/s]
 44%|██████████████████████████████████▋                                           | 4077/9182 [15:27<14:10,  6.00it/s]
 44%|██████████████████████████████████▋                                           | 4079/9182 [15:27<12:17,  6.92it/s]
 44%|██████████████████████████████████▋                                           | 4081/9182 [15:28<12:22,  6.87it/s]
 44%|██████████████████████████████████▋                                           | 4082/9182 [15:28<14:44,  5.76it/s]
 44%|██████████████████████████████████▋                                           | 4083/9182 [15:28<14:31,  5.85it/s]
 44%|██████████████████████████████████▋                                           | 4084/9182 [15:29<19:12,  4.42it/s]
 45%|██████████████████████████████████▋                                           | 4086/9182 [15:29<13:50,  6.13it/s]
 45%|██████████████████████████████████▋                                           | 4087/9182 [15:29<17:45,  4.78it/s]
 45%|██████████████████████████████████▋                                           | 4088/9182 [15:30<20:47,  4.08it/s]
 45%|██████████████████████████████████▋                                           | 4089/9182 [15:30<23:34,  3.60it/s]
 45%|██████████████████████████████████▋                                           | 4090/9182 [15:30<24:29,  3.46it/s]
 45%|██████████████████████████████████▊                                           | 4091/9182 [15:30<22:03,  3.85it/s]
 45%|██████████████████████████████████▊                                           | 4092/9182 [15:31<29:01,  2.92it/s]
 45%|██████████████████████████████████▊                                           | 4093/9182 [15:31<26:44,  3.17it/s]
 45%|██████████████████████████████████▊                                           | 4096/9182 [15:32<14:10,  5.98it/s]
 45%|██████████████████████████████████▊                                           | 4097/9182 [15:32<21:03,  4.03it/s]
 45%|██████████████████████████████████▊                                           | 4098/9182 [15:32<22:23,  3.78it/s]
 45%|██████████████████████████████████▊                                           | 4101/9182 [15:32<14:27,  5.86it/s]
 45%|██████████████████████████████████▊                                           | 4103/9182 [15:33<11:30,  7.36it/s]

 45%|██████████████████████████████████▊                                           | 4105/9182 [15:33<16:11,  5.22it/s]
 45%|██████████████████████████████████▉                                           | 4106/9182 [15:33<18:54,  4.47it/s]
 45%|██████████████████████████████████▉                                           | 4107/9182 [15:34<19:12,  4.40it/s]
 45%|██████████████████████████████████▉                                           | 4110/9182 [15:34<16:49,  5.02it/s]
 45%|██████████████████████████████████▉                                           | 4111/9182 [15:34<15:25,  5.48it/s]
 45%|██████████████████████████████████▉                                           | 4112/9182 [15:34<15:09,  5.58it/s]
 45%|██████████████████████████████████▉                                           | 4113/9182 [15:35<23:04,  3.66it/s]
 45%|██████████████████████████████████▉                                           | 4114/9182 [15:36<23:19,  3.62it/s]
 45%|██████████████████████████████████▉                                           | 4115/9182 [15:36<29:07,  2.90it/s]
 45%|██████████████████████████████████▉                                           | 4116/9182 [15:36<30:34,  2.76it/s]
 45%|██████████████████████████████████▉                                           | 4117/9182 [15:37<32:56,  2.56it/s]
 45%|██████████████████████████████████▉                                           | 4118/9182 [15:37<32:25,  2.60it/s]
 45%|██████████████████████████████████▉                                           | 4119/9182 [15:38<49:51,  1.69it/s]
 45%|██████████████████████████████████▉                                           | 4120/9182 [15:39<47:09,  1.79it/s]
 45%|███████████████████████████████████                                           | 4121/9182 [15:39<41:20,  2.04it/s]
 45%|███████████████████████████████████                                           | 4122/9182 [15:39<33:44,  2.50it/s]
 45%|███████████████████████████████████                                           | 4123/9182 [15:40<40:23,  2.09it/s]
 45%|███████████████████████████████████                                           | 4124/9182 [15:40<36:28,  2.31it/s]
 45%|███████████████████████████████████                                           | 4125/9182 [15:41<30:54,  2.73it/s]
 45%|███████████████████████████████████                                           | 4128/9182 [15:41<22:15,  3.78it/s]
 45%|███████████████████████████████████                                           | 4129/9182 [15:41<25:40,  3.28it/s]
 45%|███████████████████████████████████                                           | 4130/9182 [15:42<22:12,  3.79it/s]
 45%|███████████████████████████████████                                           | 4131/9182 [15:42<28:12,  2.98it/s]
 45%|███████████████████████████████████                                           | 4132/9182 [15:42<24:15,  3.47it/s]
 45%|███████████████████████████████████                                           | 4133/9182 [15:43<43:35,  1.93it/s]
 45%|███████████████████████████████████▏                                          | 4137/9182 [15:44<20:59,  4.01it/s]
 45%|███████████████████████████████████▏                                          | 4138/9182 [15:44<20:24,  4.12it/s]
 45%|███████████████████████████████████▏                                          | 4139/9182 [15:44<18:50,  4.46it/s]
 45%|███████████████████████████████████▏                                          | 4141/9182 [15:44<16:28,  5.10it/s]
 45%|███████████████████████████████████▏                                          | 4142/9182 [15:45<15:55,  5.28it/s]
 45%|███████████████████████████████████▏                                          | 4143/9182 [15:45<14:59,  5.60it/s]
 45%|███████████████████████████████████▏                                          | 4146/9182 [15:45<09:44,  8.62it/s]
 45%|███████████████████████████████████▏                                          | 4149/9182 [15:45<10:40,  7.86it/s]
 45%|███████████████████████████████████▎                                          | 4151/9182 [15:46<12:09,  6.89it/s]
 45%|███████████████████████████████████▎                                          | 4152/9182 [15:46<12:59,  6.46it/s]
 45%|███████████████████████████████████▎                                          | 4153/9182 [15:46<12:53,  6.50it/s]
 45%|███████████████████████████████████▎                                          | 4154/9182 [15:46<12:19,  6.79it/s]
 45%|███████████████████████████████████▎                                          | 4155/9182 [15:47<17:02,  4.92it/s]
 45%|███████████████████████████████████▎                                          | 4157/9182 [15:47<14:21,  5.83it/s]
 45%|███████████████████████████████████▎                                          | 4158/9182 [15:47<14:53,  5.62it/s]
 45%|███████████████████████████████████▎                                          | 4159/9182 [15:47<14:18,  5.85it/s]
 45%|███████████████████████████████████▎                                          | 4160/9182 [15:48<14:20,  5.83it/s]
 45%|███████████████████████████████████▎                                          | 4161/9182 [15:48<22:47,  3.67it/s]
 45%|███████████████████████████████████▎                                          | 4164/9182 [15:48<12:43,  6.57it/s]
 45%|███████████████████████████████████▍                                          | 4165/9182 [15:48<15:51,  5.27it/s]
 45%|███████████████████████████████████▍                                          | 4166/9182 [15:49<25:11,  3.32it/s]
 45%|███████████████████████████████████▍                                          | 4169/9182 [15:49<14:31,  5.75it/s]
 45%|███████████████████████████████████▍                                          | 4171/9182 [15:50<13:04,  6.39it/s]
 45%|███████████████████████████████████▍                                          | 4173/9182 [15:50<14:20,  5.82it/s]
 45%|███████████████████████████████████▍                                          | 4174/9182 [15:51<23:52,  3.50it/s]
 45%|███████████████████████████████████▍                                          | 4175/9182 [15:51<25:49,  3.23it/s]
 45%|███████████████████████████████████▍                                          | 4176/9182 [15:51<24:09,  3.45it/s]
 45%|███████████████████████████████████▍                                          | 4177/9182 [15:52<24:10,  3.45it/s]
 46%|███████████████████████████████████▌                                          | 4180/9182 [15:52<18:49,  4.43it/s]
 46%|███████████████████████████████████▌                                          | 4181/9182 [15:52<17:49,  4.68it/s]
 46%|███████████████████████████████████▌                                          | 4182/9182 [15:52<16:02,  5.20it/s]
 46%|███████████████████████████████████▌                                          | 4183/9182 [15:53<15:49,  5.26it/s]
 46%|███████████████████████████████████▌                                          | 4184/9182 [15:53<15:07,  5.51it/s]
 46%|███████████████████████████████████▌                                          | 4185/9182 [15:53<13:40,  6.09it/s]
 46%|███████████████████████████████████▌                                          | 4188/9182 [15:53<08:13, 10.12it/s]
 46%|███████████████████████████████████▌                                          | 4190/9182 [15:54<19:37,  4.24it/s]
 46%|███████████████████████████████████▌                                          | 4191/9182 [15:55<29:40,  2.80it/s]
 46%|███████████████████████████████████▌                                          | 4192/9182 [15:55<26:03,  3.19it/s]
 46%|███████████████████████████████████▌                                          | 4193/9182 [15:55<25:25,  3.27it/s]
 46%|███████████████████████████████████▋                                          | 4194/9182 [15:55<22:08,  3.76it/s]
 46%|███████████████████████████████████▋                                          | 4199/9182 [15:56<15:34,  5.33it/s]
 46%|███████████████████████████████████▋                                          | 4200/9182 [15:57<20:24,  4.07it/s]
 46%|███████████████████████████████████▋                                          | 4201/9182 [15:57<21:08,  3.93it/s]
 46%|███████████████████████████████████▋                                          | 4202/9182 [15:57<19:36,  4.23it/s]
 46%|███████████████████████████████████▋                                          | 4203/9182 [15:57<22:41,  3.66it/s]
 46%|███████████████████████████████████▋                                          | 4204/9182 [15:58<20:19,  4.08it/s]
 46%|███████████████████████████████████▋                                          | 4205/9182 [15:58<22:16,  3.73it/s]
 46%|███████████████████████████████████▋                                          | 4206/9182 [15:58<25:21,  3.27it/s]
 46%|███████████████████████████████████▋                                          | 4207/9182 [15:59<26:14,  3.16it/s]
 46%|███████████████████████████████████▋                                          | 4208/9182 [15:59<21:33,  3.84it/s]
 46%|███████████████████████████████████▊                                          | 4210/9182 [15:59<22:34,  3.67it/s]
 46%|███████████████████████████████████▊                                          | 4213/9182 [16:00<15:19,  5.40it/s]
 46%|███████████████████████████████████▊                                          | 4214/9182 [16:00<15:17,  5.42it/s]
 46%|███████████████████████████████████▊                                          | 4215/9182 [16:00<14:14,  5.81it/s]
 46%|███████████████████████████████████▊                                          | 4216/9182 [16:01<20:59,  3.94it/s]
 46%|███████████████████████████████████▊                                          | 4217/9182 [16:01<19:09,  4.32it/s]
 46%|███████████████████████████████████▊                                          | 4218/9182 [16:01<16:26,  5.03it/s]
 46%|███████████████████████████████████▊                                          | 4219/9182 [16:01<20:55,  3.95it/s]
 46%|███████████████████████████████████▊                                          | 4222/9182 [16:02<13:49,  5.98it/s]
 46%|███████████████████████████████████▊                                          | 4223/9182 [16:02<21:00,  3.94it/s]
 46%|███████████████████████████████████▉                                          | 4224/9182 [16:02<20:59,  3.94it/s]
 46%|███████████████████████████████████▉                                          | 4225/9182 [16:03<29:01,  2.85it/s]
 46%|███████████████████████████████████▉                                          | 4226/9182 [16:03<23:49,  3.47it/s]
 46%|███████████████████████████████████▉                                          | 4227/9182 [16:03<21:49,  3.78it/s]
 46%|███████████████████████████████████▉                                          | 4228/9182 [16:04<20:42,  3.99it/s]
 46%|███████████████████████████████████▉                                          | 4229/9182 [16:04<17:17,  4.77it/s]
 46%|███████████████████████████████████▉                                          | 4230/9182 [16:04<17:40,  4.67it/s]
 46%|███████████████████████████████████▉                                          | 4231/9182 [16:04<19:39,  4.20it/s]
 46%|███████████████████████████████████▉                                          | 4232/9182 [16:04<19:26,  4.24it/s]
 46%|███████████████████████████████████▉                                          | 4233/9182 [16:05<21:35,  3.82it/s]
 46%|███████████████████████████████████▉                                          | 4234/9182 [16:05<23:54,  3.45it/s]
 46%|███████████████████████████████████▉                                          | 4237/9182 [16:05<13:18,  6.19it/s]
 46%|████████████████████████████████████                                          | 4238/9182 [16:06<16:23,  5.02it/s]
 46%|████████████████████████████████████                                          | 4242/9182 [16:06<09:43,  8.46it/s]
 46%|████████████████████████████████████                                          | 4244/9182 [16:06<10:47,  7.62it/s]
 46%|████████████████████████████████████                                          | 4245/9182 [16:07<16:58,  4.85it/s]
 46%|████████████████████████████████████                                          | 4246/9182 [16:07<17:12,  4.78it/s]
 46%|████████████████████████████████████                                          | 4247/9182 [16:07<21:55,  3.75it/s]
 46%|████████████████████████████████████                                          | 4248/9182 [16:08<24:08,  3.41it/s]
 46%|████████████████████████████████████                                          | 4249/9182 [16:08<20:57,  3.92it/s]
 46%|████████████████████████████████████                                          | 4250/9182 [16:09<32:08,  2.56it/s]
 46%|████████████████████████████████████                                          | 4252/9182 [16:09<28:33,  2.88it/s]
 46%|████████████████████████████████████▏                                         | 4253/9182 [16:10<25:21,  3.24it/s]
 46%|████████████████████████████████████▏                                         | 4254/9182 [16:10<26:44,  3.07it/s]
 46%|████████████████████████████████████▏                                         | 4258/9182 [16:10<14:27,  5.67it/s]
 46%|████████████████████████████████████▏                                         | 4259/9182 [16:10<14:25,  5.69it/s]
 46%|████████████████████████████████████▏                                         | 4260/9182 [16:10<13:56,  5.88it/s]
 46%|████████████████████████████████████▏                                         | 4261/9182 [16:11<15:13,  5.39it/s]
 46%|████████████████████████████████████▏                                         | 4265/9182 [16:11<08:24,  9.74it/s]
 46%|████████████████████████████████████▏                                         | 4267/9182 [16:11<09:59,  8.20it/s]
 46%|████████████████████████████████████▎                                         | 4269/9182 [16:12<20:06,  4.07it/s]
 47%|████████████████████████████████████▎                                         | 4270/9182 [16:13<25:12,  3.25it/s]
 47%|████████████████████████████████████▎                                         | 4272/9182 [16:13<22:08,  3.70it/s]
 47%|████████████████████████████████████▎                                         | 4273/9182 [16:13<21:47,  3.75it/s]
 47%|████████████████████████████████████▎                                         | 4274/9182 [16:14<20:54,  3.91it/s]
 47%|████████████████████████████████████▎                                         | 4276/9182 [16:14<17:34,  4.65it/s]
 47%|████████████████████████████████████▎                                         | 4277/9182 [16:15<17:25,  4.69it/s]
 47%|████████████████████████████████████▎                                         | 4278/9182 [16:15<23:41,  3.45it/s]
 47%|████████████████████████████████████▎                                         | 4279/9182 [16:15<20:48,  3.93it/s]
 47%|████████████████████████████████████▎                                         | 4280/9182 [16:15<20:31,  3.98it/s]
 47%|████████████████████████████████████▎                                         | 4281/9182 [16:15<18:04,  4.52it/s]
 47%|████████████████████████████████████▍                                         | 4282/9182 [16:15<16:23,  4.98it/s]
 47%|████████████████████████████████████▍                                         | 4283/9182 [16:16<14:55,  5.47it/s]
 47%|████████████████████████████████████▍                                         | 4284/9182 [16:16<14:47,  5.52it/s]
 47%|████████████████████████████████████▍                                         | 4285/9182 [16:16<13:01,  6.27it/s]
 47%|████████████████████████████████████▍                                         | 4289/9182 [16:16<06:57, 11.72it/s]
 47%|████████████████████████████████████▍                                         | 4291/9182 [16:17<11:23,  7.16it/s]

 47%|████████████████████████████████████▍                                         | 4295/9182 [16:17<09:37,  8.47it/s]
 47%|████████████████████████████████████▌                                         | 4297/9182 [16:17<10:11,  7.99it/s]
 47%|████████████████████████████████████▌                                         | 4298/9182 [16:17<10:17,  7.91it/s]
 47%|████████████████████████████████████▌                                         | 4299/9182 [16:20<37:27,  2.17it/s]
 47%|████████████████████████████████████▌                                         | 4300/9182 [16:20<40:45,  2.00it/s]
 47%|████████████████████████████████████▌                                         | 4301/9182 [16:20<34:11,  2.38it/s]
 47%|████████████████████████████████████▌                                         | 4302/9182 [16:20<31:52,  2.55it/s]
 47%|████████████████████████████████████▌                                         | 4304/9182 [16:21<21:07,  3.85it/s]
 47%|████████████████████████████████████▌                                         | 4307/9182 [16:21<13:07,  6.19it/s]
 47%|████████████████████████████████████▌                                         | 4310/9182 [16:21<10:50,  7.49it/s]
 47%|████████████████████████████████████▋                                         | 4312/9182 [16:22<17:44,  4.57it/s]
 47%|████████████████████████████████████▋                                         | 4313/9182 [16:23<26:29,  3.06it/s]
 47%|████████████████████████████████████▋                                         | 4314/9182 [16:23<27:13,  2.98it/s]
 47%|████████████████████████████████████▋                                         | 4315/9182 [16:23<23:59,  3.38it/s]
 47%|████████████████████████████████████▋                                         | 4316/9182 [16:24<25:09,  3.22it/s]
 47%|████████████████████████████████████▋                                         | 4317/9182 [16:24<22:12,  3.65it/s]
 47%|████████████████████████████████████▋                                         | 4318/9182 [16:24<20:47,  3.90it/s]
 47%|████████████████████████████████████▋                                         | 4319/9182 [16:24<21:11,  3.82it/s]
 47%|████████████████████████████████████▋                                         | 4320/9182 [16:25<24:16,  3.34it/s]
 47%|████████████████████████████████████▋                                         | 4321/9182 [16:25<23:16,  3.48it/s]
 47%|████████████████████████████████████▋                                         | 4323/9182 [16:25<15:03,  5.38it/s]
 47%|████████████████████████████████████▋                                         | 4325/9182 [16:25<14:26,  5.61it/s]
 47%|████████████████████████████████████▋                                         | 4326/9182 [16:26<17:40,  4.58it/s]
 47%|████████████████████████████████████▊                                         | 4327/9182 [16:27<22:29,  3.60it/s]
 47%|████████████████████████████████████▊                                         | 4328/9182 [16:27<27:41,  2.92it/s]
 47%|████████████████████████████████████▊                                         | 4329/9182 [16:27<25:02,  3.23it/s]
 47%|████████████████████████████████████▊                                         | 4330/9182 [16:27<24:14,  3.34it/s]
 47%|████████████████████████████████████▊                                         | 4331/9182 [16:28<27:15,  2.97it/s]
 47%|████████████████████████████████████▊                                         | 4332/9182 [16:28<28:36,  2.83it/s]
 47%|████████████████████████████████████▊                                         | 4333/9182 [16:28<26:29,  3.05it/s]
 47%|████████████████████████████████████▊                                         | 4335/9182 [16:29<19:45,  4.09it/s]
 47%|████████████████████████████████████▊                                         | 4336/9182 [16:29<21:29,  3.76it/s]
 47%|████████████████████████████████████▊                                         | 4337/9182 [16:29<24:32,  3.29it/s]
 47%|████████████████████████████████████▊                                         | 4340/9182 [16:30<15:15,  5.29it/s]
 47%|████████████████████████████████████▉                                         | 4341/9182 [16:30<20:18,  3.97it/s]
 47%|████████████████████████████████████▉                                         | 4342/9182 [16:30<19:31,  4.13it/s]
 47%|████████████████████████████████████▉                                         | 4343/9182 [16:31<18:49,  4.28it/s]
 47%|████████████████████████████████████▉                                         | 4344/9182 [16:31<21:24,  3.77it/s]
 47%|████████████████████████████████████▉                                         | 4345/9182 [16:32<29:19,  2.75it/s]
 47%|████████████████████████████████████▉                                         | 4346/9182 [16:32<23:35,  3.42it/s]
 47%|████████████████████████████████████▉                                         | 4347/9182 [16:32<24:16,  3.32it/s]
 47%|████████████████████████████████████▉                                         | 4348/9182 [16:33<24:41,  3.26it/s]
 47%|████████████████████████████████████▉                                         | 4349/9182 [16:33<26:50,  3.00it/s]
 47%|████████████████████████████████████▉                                         | 4350/9182 [16:33<24:50,  3.24it/s]
 47%|████████████████████████████████████▉                                         | 4351/9182 [16:33<23:59,  3.36it/s]
 47%|████████████████████████████████████▉                                         | 4352/9182 [16:34<23:49,  3.38it/s]
 47%|████████████████████████████████████▉                                         | 4353/9182 [16:34<21:01,  3.83it/s]
 47%|████████████████████████████████████▉                                         | 4354/9182 [16:34<20:03,  4.01it/s]
 47%|████████████████████████████████████▉                                         | 4355/9182 [16:34<25:20,  3.17it/s]
 47%|█████████████████████████████████████                                         | 4356/9182 [16:35<23:19,  3.45it/s]
 47%|█████████████████████████████████████                                         | 4357/9182 [16:35<19:57,  4.03it/s]
 47%|█████████████████████████████████████                                         | 4358/9182 [16:35<17:44,  4.53it/s]
 47%|█████████████████████████████████████                                         | 4360/9182 [16:35<13:13,  6.08it/s]
 47%|█████████████████████████████████████                                         | 4361/9182 [16:35<14:55,  5.38it/s]
 48%|█████████████████████████████████████                                         | 4362/9182 [16:36<15:21,  5.23it/s]
 48%|█████████████████████████████████████                                         | 4363/9182 [16:36<16:37,  4.83it/s]
 48%|█████████████████████████████████████                                         | 4364/9182 [16:36<15:53,  5.06it/s]
 48%|█████████████████████████████████████                                         | 4366/9182 [16:36<12:30,  6.42it/s]
 48%|█████████████████████████████████████                                         | 4367/9182 [16:36<11:32,  6.95it/s]
 48%|█████████████████████████████████████                                         | 4368/9182 [16:37<15:33,  5.16it/s]
 48%|█████████████████████████████████████                                         | 4369/9182 [16:37<16:20,  4.91it/s]
 48%|█████████████████████████████████████                                         | 4370/9182 [16:37<19:52,  4.03it/s]
 48%|█████████████████████████████████████▏                                        | 4371/9182 [16:38<20:29,  3.91it/s]
 48%|█████████████████████████████████████▏                                        | 4372/9182 [16:38<26:30,  3.02it/s]
 48%|█████████████████████████████████████▏                                        | 4373/9182 [16:39<29:00,  2.76it/s]
 48%|█████████████████████████████████████▏                                        | 4374/9182 [16:39<24:02,  3.33it/s]
 48%|█████████████████████████████████████▏                                        | 4375/9182 [16:39<25:33,  3.14it/s]
 48%|█████████████████████████████████████▏                                        | 4376/9182 [16:39<24:26,  3.28it/s]
 48%|█████████████████████████████████████▏                                        | 4377/9182 [16:40<23:00,  3.48it/s]
 48%|█████████████████████████████████████▏                                        | 4378/9182 [16:40<24:46,  3.23it/s]
 48%|█████████████████████████████████████▏                                        | 4379/9182 [16:40<29:43,  2.69it/s]
 48%|█████████████████████████████████████▏                                        | 4380/9182 [16:41<24:59,  3.20it/s]
 48%|█████████████████████████████████████▏                                        | 4381/9182 [16:41<25:11,  3.18it/s]
 48%|█████████████████████████████████████▏                                        | 4382/9182 [16:42<34:52,  2.29it/s]
 48%|█████████████████████████████████████▏                                        | 4383/9182 [16:42<31:40,  2.52it/s]
 48%|█████████████████████████████████████▏                                        | 4384/9182 [16:43<42:24,  1.89it/s]
 48%|█████████████████████████████████████▎                                        | 4385/9182 [16:43<33:17,  2.40it/s]
 48%|█████████████████████████████████████▎                                        | 4386/9182 [16:44<42:37,  1.88it/s]
 48%|█████████████████████████████████████▎                                        | 4387/9182 [16:44<37:13,  2.15it/s]
 48%|█████████████████████████████████████▎                                        | 4388/9182 [16:45<42:45,  1.87it/s]
 48%|█████████████████████████████████████▎                                        | 4389/9182 [16:46<40:35,  1.97it/s]
 48%|█████████████████████████████████████▎                                        | 4390/9182 [16:46<43:28,  1.84it/s]
 48%|█████████████████████████████████████▎                                        | 4391/9182 [16:46<35:31,  2.25it/s]
 48%|█████████████████████████████████████▎                                        | 4392/9182 [16:47<34:44,  2.30it/s]
 48%|█████████████████████████████████████▎                                        | 4393/9182 [16:47<30:13,  2.64it/s]
 48%|█████████████████████████████████████▎                                        | 4394/9182 [16:47<32:42,  2.44it/s]
 48%|█████████████████████████████████████▎                                        | 4395/9182 [16:48<35:13,  2.26it/s]
 48%|█████████████████████████████████████▎                                        | 4396/9182 [16:48<33:08,  2.41it/s]
 48%|█████████████████████████████████████▎                                        | 4397/9182 [16:49<35:17,  2.26it/s]
 48%|█████████████████████████████████████▎                                        | 4398/9182 [16:49<36:38,  2.18it/s]
 48%|█████████████████████████████████████▎                                        | 4399/9182 [16:50<37:33,  2.12it/s]
 48%|█████████████████████████████████████▍                                        | 4400/9182 [16:51<50:18,  1.58it/s]
 48%|█████████████████████████████████████▍                                        | 4401/9182 [16:51<38:12,  2.09it/s]
 48%|█████████████████████████████████████▍                                        | 4403/9182 [16:51<28:37,  2.78it/s]
 48%|█████████████████████████████████████▍                                        | 4406/9182 [16:51<17:19,  4.60it/s]
 48%|█████████████████████████████████████▍                                        | 4407/9182 [16:52<15:51,  5.02it/s]
 48%|█████████████████████████████████████▍                                        | 4408/9182 [16:52<19:21,  4.11it/s]
 48%|█████████████████████████████████████▍                                        | 4409/9182 [16:52<16:45,  4.75it/s]
 48%|█████████████████████████████████████▍                                        | 4410/9182 [16:52<15:57,  4.99it/s]
 48%|█████████████████████████████████████▍                                        | 4411/9182 [16:53<21:39,  3.67it/s]
 48%|█████████████████████████████████████▍                                        | 4412/9182 [16:53<24:30,  3.24it/s]
 48%|█████████████████████████████████████▍                                        | 4413/9182 [16:53<28:00,  2.84it/s]
 48%|█████████████████████████████████████▍                                        | 4414/9182 [16:54<34:20,  2.31it/s]
 48%|█████████████████████████████████████▌                                        | 4415/9182 [16:54<31:00,  2.56it/s]
 48%|█████████████████████████████████████▌                                        | 4416/9182 [16:55<26:07,  3.04it/s]
 48%|█████████████████████████████████████▌                                        | 4417/9182 [16:55<25:15,  3.15it/s]
 48%|█████████████████████████████████████▌                                        | 4418/9182 [16:55<27:13,  2.92it/s]
 48%|█████████████████████████████████████▌                                        | 4419/9182 [16:56<26:35,  2.99it/s]
 48%|█████████████████████████████████████▌                                        | 4420/9182 [16:56<28:04,  2.83it/s]
 48%|█████████████████████████████████████▌                                        | 4421/9182 [16:57<31:54,  2.49it/s]
 48%|█████████████████████████████████████▌                                        | 4422/9182 [16:57<33:41,  2.35it/s]
 48%|█████████████████████████████████████▌                                        | 4423/9182 [16:57<30:05,  2.64it/s]
 48%|█████████████████████████████████████▌                                        | 4424/9182 [16:58<30:19,  2.62it/s]
 48%|█████████████████████████████████████▌                                        | 4425/9182 [16:58<27:18,  2.90it/s]
 48%|█████████████████████████████████████▌                                        | 4427/9182 [16:58<18:37,  4.25it/s]
 48%|█████████████████████████████████████▌                                        | 4428/9182 [16:59<21:47,  3.64it/s]
 48%|█████████████████████████████████████▌                                        | 4429/9182 [16:59<25:45,  3.08it/s]
 48%|█████████████████████████████████████▋                                        | 4430/9182 [16:59<24:44,  3.20it/s]
 48%|█████████████████████████████████████▋                                        | 4431/9182 [17:00<25:07,  3.15it/s]
 48%|█████████████████████████████████████▋                                        | 4432/9182 [17:00<30:12,  2.62it/s]
 48%|█████████████████████████████████████▋                                        | 4433/9182 [17:01<31:29,  2.51it/s]
 48%|█████████████████████████████████████▋                                        | 4434/9182 [17:01<29:35,  2.67it/s]
 48%|█████████████████████████████████████▋                                        | 4435/9182 [17:01<28:58,  2.73it/s]
 48%|█████████████████████████████████████▋                                        | 4436/9182 [17:02<29:58,  2.64it/s]
 48%|█████████████████████████████████████▋                                        | 4437/9182 [17:02<24:26,  3.24it/s]
 48%|█████████████████████████████████████▋                                        | 4438/9182 [17:02<27:38,  2.86it/s]
 48%|█████████████████████████████████████▋                                        | 4439/9182 [17:03<28:51,  2.74it/s]
 48%|█████████████████████████████████████▋                                        | 4440/9182 [17:03<26:32,  2.98it/s]
 48%|█████████████████████████████████████▋                                        | 4441/9182 [17:03<24:04,  3.28it/s]
 48%|█████████████████████████████████████▋                                        | 4442/9182 [17:03<25:23,  3.11it/s]
 48%|█████████████████████████████████████▋                                        | 4443/9182 [17:04<23:10,  3.41it/s]
 48%|█████████████████████████████████████▊                                        | 4444/9182 [17:04<23:00,  3.43it/s]

 48%|█████████████████████████████████████▊                                        | 4445/9182 [17:04<24:28,  3.22it/s]
 48%|█████████████████████████████████████▊                                        | 4446/9182 [17:05<27:37,  2.86it/s]
 48%|█████████████████████████████████████▊                                        | 4447/9182 [17:05<27:22,  2.88it/s]
 48%|█████████████████████████████████████▊                                        | 4448/9182 [17:06<27:19,  2.89it/s]
 48%|█████████████████████████████████████▊                                        | 4449/9182 [17:06<34:46,  2.27it/s]
 48%|█████████████████████████████████████▊                                        | 4450/9182 [17:06<32:34,  2.42it/s]
 48%|█████████████████████████████████████▊                                        | 4451/9182 [17:07<26:06,  3.02it/s]
 48%|█████████████████████████████████████▊                                        | 4452/9182 [17:07<31:14,  2.52it/s]
 48%|█████████████████████████████████████▊                                        | 4453/9182 [17:07<25:09,  3.13it/s]
 49%|█████████████████████████████████████▊                                        | 4454/9182 [17:07<21:48,  3.61it/s]
 49%|█████████████████████████████████████▊                                        | 4455/9182 [17:08<17:56,  4.39it/s]
 49%|█████████████████████████████████████▊                                        | 4458/9182 [17:08<10:38,  7.39it/s]
 49%|█████████████████████████████████████▉                                        | 4459/9182 [17:08<12:23,  6.35it/s]
 49%|█████████████████████████████████████▉                                        | 4460/9182 [17:08<12:31,  6.28it/s]
 49%|█████████████████████████████████████▉                                        | 4461/9182 [17:09<16:08,  4.87it/s]
 49%|█████████████████████████████████████▉                                        | 4462/9182 [17:09<18:23,  4.28it/s]
 49%|█████████████████████████████████████▉                                        | 4463/9182 [17:09<17:17,  4.55it/s]
 49%|█████████████████████████████████████▉                                        | 4464/9182 [17:09<14:49,  5.30it/s]
 49%|█████████████████████████████████████▉                                        | 4465/9182 [17:09<15:13,  5.16it/s]
 49%|█████████████████████████████████████▉                                        | 4466/9182 [17:10<17:02,  4.61it/s]
 49%|█████████████████████████████████████▉                                        | 4467/9182 [17:10<19:26,  4.04it/s]
 49%|█████████████████████████████████████▉                                        | 4468/9182 [17:10<20:06,  3.91it/s]
 49%|█████████████████████████████████████▉                                        | 4469/9182 [17:10<17:49,  4.41it/s]
 49%|█████████████████████████████████████▉                                        | 4470/9182 [17:11<23:22,  3.36it/s]
 49%|█████████████████████████████████████▉                                        | 4471/9182 [17:11<24:10,  3.25it/s]
 49%|█████████████████████████████████████▉                                        | 4472/9182 [17:11<20:59,  3.74it/s]
 49%|█████████████████████████████████████▉                                        | 4473/9182 [17:12<20:56,  3.75it/s]
 49%|██████████████████████████████████████                                        | 4474/9182 [17:12<26:43,  2.94it/s]
 49%|██████████████████████████████████████                                        | 4475/9182 [17:13<38:42,  2.03it/s]
 49%|██████████████████████████████████████                                        | 4476/9182 [17:13<34:08,  2.30it/s]
 49%|██████████████████████████████████████                                        | 4477/9182 [17:14<38:23,  2.04it/s]
 49%|██████████████████████████████████████                                        | 4478/9182 [17:14<30:29,  2.57it/s]
 49%|██████████████████████████████████████                                        | 4479/9182 [17:15<34:46,  2.25it/s]
 49%|██████████████████████████████████████                                        | 4480/9182 [17:15<34:15,  2.29it/s]
 49%|██████████████████████████████████████                                        | 4481/9182 [17:15<29:10,  2.69it/s]
 49%|██████████████████████████████████████                                        | 4482/9182 [17:16<30:32,  2.57it/s]
 49%|██████████████████████████████████████                                        | 4483/9182 [17:16<29:16,  2.67it/s]
 49%|██████████████████████████████████████                                        | 4484/9182 [17:17<30:05,  2.60it/s]
 49%|██████████████████████████████████████                                        | 4485/9182 [17:17<29:58,  2.61it/s]
 49%|██████████████████████████████████████                                        | 4486/9182 [17:17<26:59,  2.90it/s]
 49%|██████████████████████████████████████                                        | 4487/9182 [17:18<48:00,  1.63it/s]
 49%|██████████████████████████████████████▏                                       | 4488/9182 [17:19<37:55,  2.06it/s]
 49%|██████████████████████████████████████▏                                       | 4489/9182 [17:19<36:19,  2.15it/s]
 49%|██████████████████████████████████████▏                                       | 4490/9182 [17:19<31:38,  2.47it/s]
 49%|██████████████████████████████████████▏                                       | 4491/9182 [17:20<30:56,  2.53it/s]
 49%|██████████████████████████████████████▏                                       | 4492/9182 [17:20<33:28,  2.34it/s]
 49%|██████████████████████████████████████▏                                       | 4493/9182 [17:20<29:45,  2.63it/s]
 49%|██████████████████████████████████████▏                                       | 4494/9182 [17:21<26:39,  2.93it/s]
 49%|██████████████████████████████████████▏                                       | 4495/9182 [17:21<24:36,  3.17it/s]
 49%|██████████████████████████████████████▏                                       | 4496/9182 [17:21<20:27,  3.82it/s]
 49%|██████████████████████████████████████▏                                       | 4497/9182 [17:21<18:47,  4.15it/s]
 49%|██████████████████████████████████████▏                                       | 4498/9182 [17:21<16:48,  4.64it/s]
 49%|██████████████████████████████████████▏                                       | 4499/9182 [17:21<15:34,  5.01it/s]
 49%|██████████████████████████████████████▏                                       | 4500/9182 [17:22<14:49,  5.26it/s]
 49%|██████████████████████████████████████▎                                       | 4504/9182 [17:22<08:14,  9.45it/s]
 49%|██████████████████████████████████████▎                                       | 4505/9182 [17:22<08:38,  9.02it/s]
 49%|██████████████████████████████████████▎                                       | 4509/9182 [17:22<05:40, 13.73it/s]
 49%|██████████████████████████████████████▎                                       | 4511/9182 [17:22<05:21, 14.55it/s]
 49%|██████████████████████████████████████▎                                       | 4513/9182 [17:23<08:41,  8.95it/s]
 49%|██████████████████████████████████████▎                                       | 4515/9182 [17:23<11:07,  6.99it/s]
 49%|██████████████████████████████████████▎                                       | 4516/9182 [17:24<15:41,  4.95it/s]
 49%|██████████████████████████████████████▍                                       | 4521/9182 [17:24<09:38,  8.06it/s]
 49%|██████████████████████████████████████▍                                       | 4523/9182 [17:24<11:36,  6.69it/s]
 49%|██████████████████████████████████████▍                                       | 4524/9182 [17:25<17:09,  4.52it/s]
 49%|██████████████████████████████████████▍                                       | 4525/9182 [17:26<20:40,  3.75it/s]
 49%|██████████████████████████████████████▍                                       | 4526/9182 [17:26<22:15,  3.49it/s]
 49%|██████████████████████████████████████▍                                       | 4527/9182 [17:26<22:51,  3.39it/s]
 49%|██████████████████████████████████████▍                                       | 4532/9182 [17:26<11:45,  6.59it/s]
 49%|██████████████████████████████████████▌                                       | 4535/9182 [17:27<10:25,  7.42it/s]
 49%|██████████████████████████████████████▌                                       | 4536/9182 [17:28<15:45,  4.92it/s]
 49%|██████████████████████████████████████▌                                       | 4537/9182 [17:28<21:51,  3.54it/s]
 49%|██████████████████████████████████████▌                                       | 4538/9182 [17:29<22:41,  3.41it/s]
 49%|██████████████████████████████████████▌                                       | 4539/9182 [17:29<22:53,  3.38it/s]
 49%|██████████████████████████████████████▌                                       | 4540/9182 [17:29<19:27,  3.98it/s]
 49%|██████████████████████████████████████▌                                       | 4545/9182 [17:30<13:50,  5.59it/s]
 50%|██████████████████████████████████████▋                                       | 4547/9182 [17:30<15:15,  5.06it/s]
 50%|██████████████████████████████████████▋                                       | 4548/9182 [17:30<17:44,  4.35it/s]
 50%|██████████████████████████████████████▋                                       | 4553/9182 [17:31<17:01,  4.53it/s]
 50%|██████████████████████████████████████▋                                       | 4554/9182 [17:32<17:54,  4.31it/s]
 50%|██████████████████████████████████████▋                                       | 4555/9182 [17:32<16:17,  4.73it/s]
 50%|██████████████████████████████████████▋                                       | 4556/9182 [17:33<21:14,  3.63it/s]
 50%|██████████████████████████████████████▋                                       | 4557/9182 [17:33<26:28,  2.91it/s]
 50%|██████████████████████████████████████▋                                       | 4558/9182 [17:33<24:14,  3.18it/s]
 50%|██████████████████████████████████████▋                                       | 4559/9182 [17:34<24:51,  3.10it/s]
 50%|██████████████████████████████████████▋                                       | 4560/9182 [17:34<23:43,  3.25it/s]
 50%|██████████████████████████████████████▋                                       | 4561/9182 [17:34<21:06,  3.65it/s]
 50%|██████████████████████████████████████▊                                       | 4562/9182 [17:34<19:46,  3.89it/s]
 50%|██████████████████████████████████████▊                                       | 4563/9182 [17:35<20:41,  3.72it/s]
 50%|██████████████████████████████████████▊                                       | 4564/9182 [17:35<19:02,  4.04it/s]
 50%|██████████████████████████████████████▊                                       | 4565/9182 [17:35<19:19,  3.98it/s]
 50%|██████████████████████████████████████▊                                       | 4566/9182 [17:35<18:07,  4.24it/s]
 50%|██████████████████████████████████████▊                                       | 4567/9182 [17:36<20:07,  3.82it/s]
 50%|██████████████████████████████████████▊                                       | 4568/9182 [17:36<21:48,  3.53it/s]
 50%|██████████████████████████████████████▊                                       | 4569/9182 [17:36<19:05,  4.03it/s]
 50%|██████████████████████████████████████▊                                       | 4570/9182 [17:37<23:35,  3.26it/s]
 50%|██████████████████████████████████████▊                                       | 4571/9182 [17:37<19:57,  3.85it/s]
 50%|██████████████████████████████████████▊                                       | 4572/9182 [17:37<18:14,  4.21it/s]
 50%|██████████████████████████████████████▊                                       | 4573/9182 [17:38<28:41,  2.68it/s]
 50%|██████████████████████████████████████▊                                       | 4574/9182 [17:38<28:38,  2.68it/s]
 50%|██████████████████████████████████████▊                                       | 4575/9182 [17:38<27:53,  2.75it/s]
 50%|██████████████████████████████████████▊                                       | 4576/9182 [17:39<29:49,  2.57it/s]
 50%|██████████████████████████████████████▉                                       | 4577/9182 [17:39<23:55,  3.21it/s]
 50%|██████████████████████████████████████▉                                       | 4578/9182 [17:39<20:09,  3.81it/s]
 50%|██████████████████████████████████████▉                                       | 4579/9182 [17:39<19:47,  3.88it/s]
 50%|██████████████████████████████████████▉                                       | 4584/9182 [17:40<11:50,  6.47it/s]
 50%|██████████████████████████████████████▉                                       | 4585/9182 [17:40<12:36,  6.08it/s]
 50%|██████████████████████████████████████▉                                       | 4586/9182 [17:40<16:51,  4.54it/s]
 50%|██████████████████████████████████████▉                                       | 4587/9182 [17:41<16:27,  4.66it/s]
 50%|██████████████████████████████████████▉                                       | 4588/9182 [17:41<15:26,  4.96it/s]
 50%|███████████████████████████████████████                                       | 4592/9182 [17:41<09:24,  8.13it/s]
 50%|███████████████████████████████████████                                       | 4593/9182 [17:42<21:40,  3.53it/s]
 50%|███████████████████████████████████████                                       | 4594/9182 [17:42<22:55,  3.34it/s]
 50%|███████████████████████████████████████                                       | 4597/9182 [17:43<16:35,  4.61it/s]
 50%|███████████████████████████████████████                                       | 4598/9182 [17:43<18:28,  4.13it/s]
 50%|███████████████████████████████████████                                       | 4599/9182 [17:44<22:29,  3.40it/s]
 50%|███████████████████████████████████████                                       | 4600/9182 [17:44<21:07,  3.61it/s]
 50%|███████████████████████████████████████                                       | 4601/9182 [17:44<22:27,  3.40it/s]
 50%|███████████████████████████████████████                                       | 4602/9182 [17:45<22:45,  3.35it/s]
 50%|███████████████████████████████████████                                       | 4603/9182 [17:45<20:09,  3.79it/s]
 50%|███████████████████████████████████████▏                                      | 4607/9182 [17:45<09:16,  8.22it/s]
 50%|███████████████████████████████████████▏                                      | 4609/9182 [17:46<13:32,  5.62it/s]
 50%|███████████████████████████████████████▏                                      | 4611/9182 [17:46<12:55,  5.89it/s]
 50%|███████████████████████████████████████▏                                      | 4612/9182 [17:46<12:10,  6.25it/s]
 50%|███████████████████████████████████████▏                                      | 4615/9182 [17:46<10:16,  7.41it/s]
 50%|███████████████████████████████████████▏                                      | 4616/9182 [17:46<12:31,  6.08it/s]
 50%|███████████████████████████████████████▏                                      | 4617/9182 [17:47<12:23,  6.14it/s]
 50%|███████████████████████████████████████▏                                      | 4618/9182 [17:47<20:19,  3.74it/s]
 50%|███████████████████████████████████████▏                                      | 4619/9182 [17:48<25:07,  3.03it/s]
 50%|███████████████████████████████████████▎                                      | 4621/9182 [17:48<24:00,  3.17it/s]
 50%|███████████████████████████████████████▎                                      | 4623/9182 [17:49<17:16,  4.40it/s]
 50%|███████████████████████████████████████▎                                      | 4624/9182 [17:49<17:00,  4.47it/s]
 50%|███████████████████████████████████████▎                                      | 4625/9182 [17:49<25:12,  3.01it/s]

 50%|███████████████████████████████████████▎                                      | 4628/9182 [17:50<16:01,  4.74it/s]
 50%|███████████████████████████████████████▎                                      | 4629/9182 [17:50<15:09,  5.01it/s]
 50%|███████████████████████████████████████▎                                      | 4630/9182 [17:50<13:52,  5.47it/s]
 50%|███████████████████████████████████████▎                                      | 4632/9182 [17:50<10:38,  7.13it/s]
 50%|███████████████████████████████████████▎                                      | 4633/9182 [17:50<10:40,  7.11it/s]
 50%|███████████████████████████████████████▎                                      | 4635/9182 [17:51<11:18,  6.70it/s]
 50%|███████████████████████████████████████▍                                      | 4636/9182 [17:51<16:34,  4.57it/s]
 51%|███████████████████████████████████████▍                                      | 4637/9182 [17:51<16:08,  4.69it/s]
 51%|███████████████████████████████████████▍                                      | 4638/9182 [17:52<18:14,  4.15it/s]
 51%|███████████████████████████████████████▍                                      | 4639/9182 [17:52<24:01,  3.15it/s]
 51%|███████████████████████████████████████▍                                      | 4640/9182 [17:53<23:28,  3.22it/s]
 51%|███████████████████████████████████████▍                                      | 4641/9182 [17:53<23:02,  3.28it/s]
 51%|███████████████████████████████████████▍                                      | 4645/9182 [17:53<12:16,  6.16it/s]
 51%|███████████████████████████████████████▍                                      | 4646/9182 [17:53<12:00,  6.30it/s]
 51%|███████████████████████████████████████▍                                      | 4647/9182 [17:54<18:08,  4.17it/s]
 51%|███████████████████████████████████████▍                                      | 4648/9182 [17:55<27:12,  2.78it/s]
 51%|███████████████████████████████████████▍                                      | 4649/9182 [17:55<24:41,  3.06it/s]
 51%|███████████████████████████████████████▌                                      | 4653/9182 [17:55<11:44,  6.43it/s]
 51%|███████████████████████████████████████▌                                      | 4655/9182 [17:55<09:28,  7.96it/s]
 51%|███████████████████████████████████████▌                                      | 4657/9182 [17:55<11:39,  6.46it/s]
 51%|███████████████████████████████████████▌                                      | 4659/9182 [17:56<11:00,  6.85it/s]
 51%|███████████████████████████████████████▌                                      | 4661/9182 [17:56<10:55,  6.90it/s]
 51%|███████████████████████████████████████▌                                      | 4664/9182 [17:56<09:09,  8.21it/s]
 51%|███████████████████████████████████████▋                                      | 4665/9182 [17:56<09:05,  8.28it/s]
 51%|███████████████████████████████████████▋                                      | 4666/9182 [17:57<10:44,  7.01it/s]
 51%|███████████████████████████████████████▋                                      | 4667/9182 [17:57<14:32,  5.18it/s]
 51%|███████████████████████████████████████▋                                      | 4668/9182 [17:58<22:46,  3.30it/s]
 51%|███████████████████████████████████████▋                                      | 4669/9182 [17:59<38:26,  1.96it/s]
 51%|███████████████████████████████████████▋                                      | 4673/9182 [17:59<17:47,  4.22it/s]
 51%|███████████████████████████████████████▋                                      | 4674/9182 [17:59<17:03,  4.40it/s]
 51%|███████████████████████████████████████▋                                      | 4675/9182 [17:59<17:14,  4.36it/s]
 51%|███████████████████████████████████████▋                                      | 4677/9182 [17:59<13:14,  5.67it/s]
 51%|███████████████████████████████████████▊                                      | 4681/9182 [18:00<10:01,  7.49it/s]
 51%|███████████████████████████████████████▊                                      | 4682/9182 [18:00<11:59,  6.26it/s]
 51%|███████████████████████████████████████▊                                      | 4683/9182 [18:00<12:23,  6.05it/s]
 51%|███████████████████████████████████████▊                                      | 4684/9182 [18:01<18:25,  4.07it/s]
 51%|███████████████████████████████████████▊                                      | 4685/9182 [18:02<35:14,  2.13it/s]
 51%|███████████████████████████████████████▊                                      | 4686/9182 [18:02<31:36,  2.37it/s]
 51%|███████████████████████████████████████▊                                      | 4688/9182 [18:03<28:16,  2.65it/s]
 51%|███████████████████████████████████████▊                                      | 4689/9182 [18:04<27:36,  2.71it/s]
 51%|███████████████████████████████████████▊                                      | 4690/9182 [18:04<24:35,  3.05it/s]
 51%|███████████████████████████████████████▊                                      | 4693/9182 [18:04<13:28,  5.55it/s]
 51%|███████████████████████████████████████▉                                      | 4695/9182 [18:04<12:53,  5.80it/s]
 51%|███████████████████████████████████████▉                                      | 4696/9182 [18:05<15:45,  4.74it/s]
 51%|███████████████████████████████████████▉                                      | 4697/9182 [18:05<17:14,  4.33it/s]
 51%|███████████████████████████████████████▉                                      | 4698/9182 [18:05<20:31,  3.64it/s]
 51%|███████████████████████████████████████▉                                      | 4699/9182 [18:05<22:19,  3.35it/s]
 51%|███████████████████████████████████████▉                                      | 4700/9182 [18:06<18:32,  4.03it/s]
 51%|███████████████████████████████████████▉                                      | 4701/9182 [18:06<23:05,  3.23it/s]
 51%|███████████████████████████████████████▉                                      | 4702/9182 [18:06<19:31,  3.82it/s]
 51%|███████████████████████████████████████▉                                      | 4703/9182 [18:07<20:59,  3.55it/s]
 51%|███████████████████████████████████████▉                                      | 4704/9182 [18:07<17:25,  4.28it/s]
 51%|███████████████████████████████████████▉                                      | 4705/9182 [18:07<17:44,  4.21it/s]
 51%|███████████████████████████████████████▉                                      | 4706/9182 [18:07<19:15,  3.87it/s]
 51%|███████████████████████████████████████▉                                      | 4707/9182 [18:08<21:10,  3.52it/s]
 51%|███████████████████████████████████████▉                                      | 4708/9182 [18:08<18:31,  4.02it/s]
 51%|████████████████████████████████████████                                      | 4709/9182 [18:08<23:04,  3.23it/s]
 51%|████████████████████████████████████████                                      | 4710/9182 [18:09<28:58,  2.57it/s]
 51%|████████████████████████████████████████                                      | 4711/9182 [18:09<31:45,  2.35it/s]
 51%|████████████████████████████████████████                                      | 4712/9182 [18:10<27:48,  2.68it/s]
 51%|████████████████████████████████████████                                      | 4713/9182 [18:10<29:27,  2.53it/s]
 51%|████████████████████████████████████████                                      | 4714/9182 [18:10<28:50,  2.58it/s]
 51%|████████████████████████████████████████                                      | 4718/9182 [18:11<14:24,  5.16it/s]
 51%|████████████████████████████████████████                                      | 4719/9182 [18:11<15:17,  4.87it/s]
 51%|████████████████████████████████████████                                      | 4720/9182 [18:12<21:21,  3.48it/s]
 51%|████████████████████████████████████████                                      | 4721/9182 [18:12<18:57,  3.92it/s]
 51%|████████████████████████████████████████                                      | 4722/9182 [18:12<20:29,  3.63it/s]
 51%|████████████████████████████████████████                                      | 4723/9182 [18:12<21:01,  3.54it/s]
 51%|████████████████████████████████████████▏                                     | 4724/9182 [18:12<19:28,  3.81it/s]
 51%|████████████████████████████████████████▏                                     | 4725/9182 [18:13<20:20,  3.65it/s]
 51%|████████████████████████████████████████▏                                     | 4726/9182 [18:13<20:26,  3.63it/s]
 51%|████████████████████████████████████████▏                                     | 4727/9182 [18:13<16:56,  4.38it/s]
 52%|████████████████████████████████████████▏                                     | 4729/9182 [18:14<18:32,  4.00it/s]
 52%|████████████████████████████████████████▏                                     | 4730/9182 [18:14<20:12,  3.67it/s]
 52%|████████████████████████████████████████▏                                     | 4731/9182 [18:14<17:06,  4.34it/s]
 52%|████████████████████████████████████████▏                                     | 4734/9182 [18:14<09:34,  7.75it/s]
 52%|████████████████████████████████████████▏                                     | 4737/9182 [18:14<06:53, 10.75it/s]
 52%|████████████████████████████████████████▎                                     | 4739/9182 [18:15<09:22,  7.89it/s]
 52%|████████████████████████████████████████▎                                     | 4741/9182 [18:15<08:56,  8.28it/s]
 52%|████████████████████████████████████████▎                                     | 4743/9182 [18:17<22:38,  3.27it/s]
 52%|████████████████████████████████████████▎                                     | 4744/9182 [18:17<21:41,  3.41it/s]
 52%|████████████████████████████████████████▎                                     | 4745/9182 [18:17<21:32,  3.43it/s]
 52%|████████████████████████████████████████▎                                     | 4746/9182 [18:17<20:01,  3.69it/s]
 52%|████████████████████████████████████████▎                                     | 4747/9182 [18:18<19:04,  3.88it/s]
 52%|████████████████████████████████████████▎                                     | 4748/9182 [18:18<22:22,  3.30it/s]
 52%|████████████████████████████████████████▎                                     | 4749/9182 [18:19<28:12,  2.62it/s]
 52%|████████████████████████████████████████▎                                     | 4750/9182 [18:19<22:39,  3.26it/s]
 52%|████████████████████████████████████████▎                                     | 4751/9182 [18:20<30:00,  2.46it/s]
 52%|████████████████████████████████████████▎                                     | 4752/9182 [18:20<33:56,  2.17it/s]
 52%|████████████████████████████████████████▍                                     | 4753/9182 [18:20<35:28,  2.08it/s]
 52%|████████████████████████████████████████▍                                     | 4754/9182 [18:21<41:26,  1.78it/s]
 52%|████████████████████████████████████████▍                                     | 4755/9182 [18:21<34:03,  2.17it/s]
 52%|████████████████████████████████████████▍                                     | 4756/9182 [18:22<31:46,  2.32it/s]
 52%|████████████████████████████████████████▍                                     | 4757/9182 [18:23<35:34,  2.07it/s]
 52%|████████████████████████████████████████▍                                     | 4758/9182 [18:23<34:55,  2.11it/s]
 52%|████████████████████████████████████████▍                                     | 4759/9182 [18:23<32:35,  2.26it/s]
 52%|████████████████████████████████████████▍                                     | 4760/9182 [18:24<28:57,  2.55it/s]
 52%|████████████████████████████████████████▍                                     | 4762/9182 [18:24<17:18,  4.26it/s]
 52%|████████████████████████████████████████▍                                     | 4763/9182 [18:25<29:15,  2.52it/s]
 52%|████████████████████████████████████████▍                                     | 4764/9182 [18:25<24:13,  3.04it/s]
 52%|████████████████████████████████████████▍                                     | 4765/9182 [18:26<24:35,  2.99it/s]
 52%|████████████████████████████████████████▍                                     | 4766/9182 [18:26<34:01,  2.16it/s]
 52%|████████████████████████████████████████▍                                     | 4767/9182 [18:26<33:00,  2.23it/s]
 52%|████████████████████████████████████████▌                                     | 4768/9182 [18:27<43:01,  1.71it/s]
 52%|████████████████████████████████████████▌                                     | 4769/9182 [18:27<37:19,  1.97it/s]
 52%|████████████████████████████████████████▌                                     | 4770/9182 [18:28<32:58,  2.23it/s]
 52%|████████████████████████████████████████▌                                     | 4771/9182 [18:28<26:23,  2.79it/s]
 52%|████████████████████████████████████████▌                                     | 4772/9182 [18:28<21:31,  3.42it/s]
 52%|████████████████████████████████████████▌                                     | 4773/9182 [18:28<22:02,  3.34it/s]
 52%|████████████████████████████████████████▌                                     | 4774/9182 [18:28<19:11,  3.83it/s]
 52%|████████████████████████████████████████▌                                     | 4779/9182 [18:29<07:43,  9.51it/s]
 52%|████████████████████████████████████████▌                                     | 4781/9182 [18:30<14:27,  5.07it/s]
 52%|████████████████████████████████████████▌                                     | 4782/9182 [18:31<24:20,  3.01it/s]
 52%|████████████████████████████████████████▋                                     | 4783/9182 [18:31<23:25,  3.13it/s]
 52%|████████████████████████████████████████▋                                     | 4784/9182 [18:32<29:59,  2.44it/s]
 52%|████████████████████████████████████████▋                                     | 4785/9182 [18:32<30:03,  2.44it/s]
 52%|████████████████████████████████████████▋                                     | 4786/9182 [18:33<30:37,  2.39it/s]
 52%|████████████████████████████████████████▋                                     | 4787/9182 [18:33<29:25,  2.49it/s]
 52%|████████████████████████████████████████▋                                     | 4788/9182 [18:33<28:43,  2.55it/s]
 52%|████████████████████████████████████████▋                                     | 4789/9182 [18:34<26:07,  2.80it/s]
 52%|████████████████████████████████████████▋                                     | 4790/9182 [18:34<28:11,  2.60it/s]
 52%|████████████████████████████████████████▋                                     | 4791/9182 [18:34<30:52,  2.37it/s]
 52%|████████████████████████████████████████▋                                     | 4792/9182 [18:35<26:13,  2.79it/s]
 52%|████████████████████████████████████████▋                                     | 4793/9182 [18:35<21:43,  3.37it/s]
 52%|████████████████████████████████████████▋                                     | 4794/9182 [18:35<26:30,  2.76it/s]
 52%|████████████████████████████████████████▋                                     | 4795/9182 [18:35<21:51,  3.34it/s]
 52%|████████████████████████████████████████▋                                     | 4796/9182 [18:36<19:12,  3.81it/s]
 52%|████████████████████████████████████████▋                                     | 4797/9182 [18:36<22:34,  3.24it/s]
 52%|████████████████████████████████████████▊                                     | 4798/9182 [18:37<32:11,  2.27it/s]
 52%|████████████████████████████████████████▊                                     | 4799/9182 [18:37<29:05,  2.51it/s]
 52%|████████████████████████████████████████▊                                     | 4800/9182 [18:37<27:14,  2.68it/s]
 52%|████████████████████████████████████████▊                                     | 4801/9182 [18:38<22:07,  3.30it/s]

 52%|████████████████████████████████████████▊                                     | 4802/9182 [18:38<24:47,  2.95it/s]
 52%|████████████████████████████████████████▊                                     | 4803/9182 [18:38<23:32,  3.10it/s]
 52%|████████████████████████████████████████▊                                     | 4804/9182 [18:38<18:46,  3.89it/s]
 52%|████████████████████████████████████████▊                                     | 4805/9182 [18:39<19:32,  3.73it/s]
 52%|████████████████████████████████████████▊                                     | 4806/9182 [18:39<20:38,  3.53it/s]
 52%|████████████████████████████████████████▊                                     | 4807/9182 [18:39<22:49,  3.20it/s]
 52%|████████████████████████████████████████▊                                     | 4808/9182 [18:40<22:19,  3.27it/s]
 52%|████████████████████████████████████████▊                                     | 4809/9182 [18:40<19:44,  3.69it/s]
 52%|████████████████████████████████████████▊                                     | 4810/9182 [18:40<21:32,  3.38it/s]
 52%|████████████████████████████████████████▊                                     | 4811/9182 [18:40<19:06,  3.81it/s]
 52%|████████████████████████████████████████▉                                     | 4812/9182 [18:41<20:10,  3.61it/s]
 52%|████████████████████████████████████████▉                                     | 4813/9182 [18:41<25:52,  2.81it/s]
 52%|████████████████████████████████████████▉                                     | 4814/9182 [18:41<23:22,  3.11it/s]
 52%|████████████████████████████████████████▉                                     | 4815/9182 [18:42<29:11,  2.49it/s]
 52%|████████████████████████████████████████▉                                     | 4816/9182 [18:42<24:55,  2.92it/s]
 52%|████████████████████████████████████████▉                                     | 4817/9182 [18:42<23:02,  3.16it/s]
 52%|████████████████████████████████████████▉                                     | 4818/9182 [18:43<18:46,  3.87it/s]
 52%|████████████████████████████████████████▉                                     | 4819/9182 [18:43<17:26,  4.17it/s]
 52%|████████████████████████████████████████▉                                     | 4820/9182 [18:43<17:24,  4.17it/s]
 53%|████████████████████████████████████████▉                                     | 4822/9182 [18:43<11:59,  6.06it/s]
 53%|████████████████████████████████████████▉                                     | 4823/9182 [18:44<17:59,  4.04it/s]
 53%|████████████████████████████████████████▉                                     | 4824/9182 [18:44<21:37,  3.36it/s]
 53%|████████████████████████████████████████▉                                     | 4825/9182 [18:44<22:43,  3.20it/s]
 53%|████████████████████████████████████████▉                                     | 4826/9182 [18:45<22:52,  3.17it/s]
 53%|█████████████████████████████████████████                                     | 4827/9182 [18:45<20:01,  3.63it/s]
 53%|█████████████████████████████████████████                                     | 4832/9182 [18:45<07:33,  9.60it/s]
 53%|█████████████████████████████████████████                                     | 4834/9182 [18:46<14:01,  5.17it/s]
 53%|█████████████████████████████████████████                                     | 4836/9182 [18:46<13:26,  5.39it/s]
 53%|█████████████████████████████████████████                                     | 4838/9182 [18:48<25:20,  2.86it/s]
 53%|█████████████████████████████████████████                                     | 4839/9182 [18:48<28:54,  2.50it/s]
 53%|█████████████████████████████████████████                                     | 4840/9182 [18:49<26:51,  2.69it/s]
 53%|█████████████████████████████████████████                                     | 4841/9182 [18:49<22:51,  3.16it/s]
 53%|█████████████████████████████████████████▏                                    | 4842/9182 [18:49<20:36,  3.51it/s]
 53%|█████████████████████████████████████████▏                                    | 4843/9182 [18:50<26:56,  2.68it/s]
 53%|█████████████████████████████████████████▏                                    | 4844/9182 [18:50<24:34,  2.94it/s]
 53%|█████████████████████████████████████████▏                                    | 4845/9182 [18:50<24:43,  2.92it/s]
 53%|█████████████████████████████████████████▏                                    | 4846/9182 [18:51<31:27,  2.30it/s]
 53%|█████████████████████████████████████████▏                                    | 4847/9182 [18:51<24:28,  2.95it/s]
 53%|█████████████████████████████████████████▏                                    | 4848/9182 [18:51<28:03,  2.57it/s]
 53%|█████████████████████████████████████████▏                                    | 4849/9182 [18:53<50:46,  1.42it/s]
 53%|█████████████████████████████████████████▏                                    | 4850/9182 [18:53<41:36,  1.74it/s]
 53%|█████████████████████████████████████████▏                                    | 4851/9182 [18:53<35:05,  2.06it/s]
 53%|████████████████████████████████████████▏                                   | 4852/9182 [18:56<1:19:45,  1.11s/it]
 53%|█████████████████████████████████████████▏                                    | 4853/9182 [18:56<58:30,  1.23it/s]
 53%|█████████████████████████████████████████▏                                    | 4854/9182 [18:57<47:14,  1.53it/s]
 53%|█████████████████████████████████████████▏                                    | 4855/9182 [18:57<45:12,  1.60it/s]
 53%|█████████████████████████████████████████▎                                    | 4856/9182 [18:57<33:58,  2.12it/s]
 53%|█████████████████████████████████████████▎                                    | 4857/9182 [18:57<27:43,  2.60it/s]
 53%|█████████████████████████████████████████▎                                    | 4858/9182 [18:58<28:22,  2.54it/s]
 53%|█████████████████████████████████████████▎                                    | 4859/9182 [18:58<23:03,  3.12it/s]
 53%|█████████████████████████████████████████▎                                    | 4860/9182 [18:58<18:48,  3.83it/s]
 53%|█████████████████████████████████████████▎                                    | 4861/9182 [18:59<24:09,  2.98it/s]
 53%|█████████████████████████████████████████▎                                    | 4862/9182 [18:59<22:39,  3.18it/s]
 53%|█████████████████████████████████████████▎                                    | 4863/9182 [18:59<19:45,  3.64it/s]
 53%|█████████████████████████████████████████▎                                    | 4864/9182 [18:59<21:10,  3.40it/s]
 53%|█████████████████████████████████████████▎                                    | 4870/9182 [19:00<08:37,  8.34it/s]
 53%|█████████████████████████████████████████▍                                    | 4871/9182 [19:00<09:10,  7.83it/s]
 53%|█████████████████████████████████████████▍                                    | 4872/9182 [19:00<09:48,  7.32it/s]
 53%|█████████████████████████████████████████▍                                    | 4875/9182 [19:00<07:33,  9.50it/s]
 53%|█████████████████████████████████████████▍                                    | 4876/9182 [19:00<07:49,  9.18it/s]
 53%|█████████████████████████████████████████▍                                    | 4878/9182 [19:00<06:51, 10.46it/s]
 53%|█████████████████████████████████████████▍                                    | 4880/9182 [19:00<06:16, 11.42it/s]
 53%|█████████████████████████████████████████▍                                    | 4882/9182 [19:01<06:58, 10.29it/s]
 53%|█████████████████████████████████████████▍                                    | 4884/9182 [19:01<09:42,  7.38it/s]
 53%|█████████████████████████████████████████▌                                    | 4886/9182 [19:03<20:43,  3.45it/s]
 53%|█████████████████████████████████████████▌                                    | 4887/9182 [19:03<21:01,  3.40it/s]
 53%|█████████████████████████████████████████▌                                    | 4888/9182 [19:03<18:32,  3.86it/s]
 53%|█████████████████████████████████████████▌                                    | 4889/9182 [19:03<19:43,  3.63it/s]
 53%|█████████████████████████████████████████▌                                    | 4890/9182 [19:04<20:39,  3.46it/s]
 53%|█████████████████████████████████████████▌                                    | 4891/9182 [19:04<21:04,  3.39it/s]
 53%|█████████████████████████████████████████▌                                    | 4895/9182 [19:04<10:21,  6.90it/s]
 53%|█████████████████████████████████████████▌                                    | 4896/9182 [19:04<10:24,  6.87it/s]
 53%|█████████████████████████████████████████▌                                    | 4897/9182 [19:04<10:40,  6.69it/s]
 53%|█████████████████████████████████████████▌                                    | 4898/9182 [19:05<13:02,  5.47it/s]
 53%|█████████████████████████████████████████▌                                    | 4899/9182 [19:05<11:52,  6.01it/s]
 53%|█████████████████████████████████████████▌                                    | 4900/9182 [19:05<10:48,  6.60it/s]
 53%|█████████████████████████████████████████▋                                    | 4901/9182 [19:05<13:33,  5.26it/s]
 53%|█████████████████████████████████████████▋                                    | 4902/9182 [19:06<15:27,  4.61it/s]
 53%|█████████████████████████████████████████▋                                    | 4903/9182 [19:06<17:55,  3.98it/s]
 53%|█████████████████████████████████████████▋                                    | 4904/9182 [19:06<18:48,  3.79it/s]
 53%|█████████████████████████████████████████▋                                    | 4905/9182 [19:06<16:46,  4.25it/s]
 53%|█████████████████████████████████████████▋                                    | 4906/9182 [19:07<18:29,  3.86it/s]
 53%|█████████████████████████████████████████▋                                    | 4909/9182 [19:07<14:25,  4.94it/s]
 53%|█████████████████████████████████████████▋                                    | 4910/9182 [19:07<16:45,  4.25it/s]
 53%|█████████████████████████████████████████▋                                    | 4911/9182 [19:08<19:07,  3.72it/s]
 53%|█████████████████████████████████████████▋                                    | 4912/9182 [19:08<20:08,  3.53it/s]
 54%|█████████████████████████████████████████▋                                    | 4913/9182 [19:08<18:32,  3.84it/s]
 54%|█████████████████████████████████████████▊                                    | 4916/9182 [19:08<10:18,  6.90it/s]
 54%|█████████████████████████████████████████▊                                    | 4918/9182 [19:09<11:52,  5.98it/s]
 54%|█████████████████████████████████████████▊                                    | 4919/9182 [19:09<12:52,  5.52it/s]
 54%|█████████████████████████████████████████▊                                    | 4920/9182 [19:09<13:53,  5.11it/s]
 54%|█████████████████████████████████████████▊                                    | 4921/9182 [19:10<17:21,  4.09it/s]
 54%|█████████████████████████████████████████▊                                    | 4922/9182 [19:10<15:57,  4.45it/s]
 54%|█████████████████████████████████████████▊                                    | 4925/9182 [19:10<09:15,  7.66it/s]
 54%|█████████████████████████████████████████▊                                    | 4927/9182 [19:11<19:21,  3.66it/s]
 54%|█████████████████████████████████████████▊                                    | 4928/9182 [19:11<18:12,  3.89it/s]
 54%|█████████████████████████████████████████▊                                    | 4929/9182 [19:12<22:36,  3.13it/s]
 54%|█████████████████████████████████████████▉                                    | 4930/9182 [19:12<21:24,  3.31it/s]
 54%|█████████████████████████████████████████▉                                    | 4931/9182 [19:13<24:05,  2.94it/s]
 54%|█████████████████████████████████████████▉                                    | 4932/9182 [19:13<26:01,  2.72it/s]
 54%|█████████████████████████████████████████▉                                    | 4933/9182 [19:13<22:57,  3.08it/s]
 54%|█████████████████████████████████████████▉                                    | 4934/9182 [19:13<20:07,  3.52it/s]
 54%|█████████████████████████████████████████▉                                    | 4935/9182 [19:14<23:19,  3.03it/s]
 54%|█████████████████████████████████████████▉                                    | 4936/9182 [19:14<19:34,  3.62it/s]
 54%|█████████████████████████████████████████▉                                    | 4937/9182 [19:15<24:42,  2.86it/s]
 54%|█████████████████████████████████████████▉                                    | 4938/9182 [19:15<21:26,  3.30it/s]
 54%|█████████████████████████████████████████▉                                    | 4941/9182 [19:15<16:09,  4.37it/s]
 54%|█████████████████████████████████████████▉                                    | 4942/9182 [19:16<18:02,  3.92it/s]
 54%|█████████████████████████████████████████▉                                    | 4943/9182 [19:16<18:19,  3.86it/s]
 54%|█████████████████████████████████████████▉                                    | 4944/9182 [19:17<24:03,  2.94it/s]
 54%|██████████████████████████████████████████                                    | 4945/9182 [19:17<22:36,  3.12it/s]
 54%|██████████████████████████████████████████                                    | 4946/9182 [19:17<19:28,  3.62it/s]
 54%|██████████████████████████████████████████                                    | 4947/9182 [19:17<18:06,  3.90it/s]
 54%|██████████████████████████████████████████                                    | 4951/9182 [19:17<09:02,  7.80it/s]
 54%|██████████████████████████████████████████                                    | 4952/9182 [19:18<21:08,  3.34it/s]
 54%|██████████████████████████████████████████                                    | 4953/9182 [19:18<18:47,  3.75it/s]
 54%|██████████████████████████████████████████                                    | 4955/9182 [19:19<13:29,  5.22it/s]
 54%|██████████████████████████████████████████                                    | 4956/9182 [19:19<14:58,  4.70it/s]
 54%|██████████████████████████████████████████▏                                   | 4959/9182 [19:20<11:48,  5.96it/s]
 54%|██████████████████████████████████████████▏                                   | 4960/9182 [19:20<17:34,  4.00it/s]
 54%|██████████████████████████████████████████▏                                   | 4961/9182 [19:20<17:39,  3.98it/s]
 54%|██████████████████████████████████████████▏                                   | 4962/9182 [19:20<18:35,  3.78it/s]
 54%|██████████████████████████████████████████▏                                   | 4963/9182 [19:21<16:18,  4.31it/s]
 54%|██████████████████████████████████████████▏                                   | 4964/9182 [19:21<18:58,  3.71it/s]
 54%|██████████████████████████████████████████▏                                   | 4965/9182 [19:21<18:53,  3.72it/s]
 54%|██████████████████████████████████████████▏                                   | 4966/9182 [19:22<20:55,  3.36it/s]
 54%|██████████████████████████████████████████▏                                   | 4967/9182 [19:22<18:31,  3.79it/s]
 54%|██████████████████████████████████████████▏                                   | 4968/9182 [19:22<19:02,  3.69it/s]
 54%|██████████████████████████████████████████▏                                   | 4969/9182 [19:22<19:13,  3.65it/s]
 54%|██████████████████████████████████████████▏                                   | 4970/9182 [19:23<16:37,  4.22it/s]
 54%|██████████████████████████████████████████▏                                   | 4971/9182 [19:23<18:39,  3.76it/s]
 54%|██████████████████████████████████████████▏                                   | 4972/9182 [19:23<21:43,  3.23it/s]

 54%|██████████████████████████████████████████▏                                   | 4973/9182 [19:23<18:41,  3.75it/s]
 54%|██████████████████████████████████████████▎                                   | 4974/9182 [19:24<22:50,  3.07it/s]
 54%|██████████████████████████████████████████▎                                   | 4975/9182 [19:24<23:06,  3.03it/s]
 54%|██████████████████████████████████████████▎                                   | 4976/9182 [19:24<19:46,  3.55it/s]
 54%|██████████████████████████████████████████▎                                   | 4977/9182 [19:25<18:09,  3.86it/s]
 54%|██████████████████████████████████████████▎                                   | 4978/9182 [19:25<14:56,  4.69it/s]
 54%|██████████████████████████████████████████▎                                   | 4982/9182 [19:25<10:58,  6.38it/s]
 54%|██████████████████████████████████████████▎                                   | 4987/9182 [19:25<06:59,  9.99it/s]
 54%|██████████████████████████████████████████▍                                   | 4989/9182 [19:26<10:37,  6.58it/s]
 54%|██████████████████████████████████████████▍                                   | 4990/9182 [19:26<10:25,  6.70it/s]
 54%|██████████████████████████████████████████▍                                   | 4991/9182 [19:27<13:10,  5.30it/s]
 54%|██████████████████████████████████████████▍                                   | 4992/9182 [19:27<16:24,  4.26it/s]
 54%|██████████████████████████████████████████▍                                   | 4993/9182 [19:27<15:40,  4.45it/s]
 54%|██████████████████████████████████████████▍                                   | 4994/9182 [19:28<18:46,  3.72it/s]
 54%|██████████████████████████████████████████▍                                   | 4995/9182 [19:28<22:52,  3.05it/s]
 54%|██████████████████████████████████████████▍                                   | 4996/9182 [19:29<24:05,  2.90it/s]
 54%|██████████████████████████████████████████▍                                   | 4997/9182 [19:29<22:12,  3.14it/s]
 54%|██████████████████████████████████████████▍                                   | 4998/9182 [19:29<18:16,  3.82it/s]
 54%|██████████████████████████████████████████▍                                   | 5002/9182 [19:29<09:27,  7.37it/s]
 54%|██████████████████████████████████████████▌                                   | 5004/9182 [19:29<07:47,  8.94it/s]
 55%|██████████████████████████████████████████▌                                   | 5006/9182 [19:30<13:33,  5.14it/s]
 55%|██████████████████████████████████████████▌                                   | 5007/9182 [19:30<13:16,  5.24it/s]
 55%|██████████████████████████████████████████▌                                   | 5008/9182 [19:30<12:42,  5.47it/s]
 55%|██████████████████████████████████████████▌                                   | 5009/9182 [19:31<14:56,  4.65it/s]
 55%|██████████████████████████████████████████▌                                   | 5010/9182 [19:31<13:23,  5.19it/s]
 55%|██████████████████████████████████████████▌                                   | 5011/9182 [19:31<17:12,  4.04it/s]
 55%|██████████████████████████████████████████▌                                   | 5012/9182 [19:32<20:04,  3.46it/s]
 55%|██████████████████████████████████████████▌                                   | 5013/9182 [19:32<24:54,  2.79it/s]
 55%|██████████████████████████████████████████▌                                   | 5014/9182 [19:33<26:47,  2.59it/s]
 55%|██████████████████████████████████████████▌                                   | 5015/9182 [19:33<21:31,  3.23it/s]
 55%|██████████████████████████████████████████▌                                   | 5017/9182 [19:33<20:15,  3.43it/s]
 55%|██████████████████████████████████████████▋                                   | 5018/9182 [19:34<18:27,  3.76it/s]
 55%|██████████████████████████████████████████▋                                   | 5019/9182 [19:34<18:26,  3.76it/s]
 55%|██████████████████████████████████████████▋                                   | 5020/9182 [19:34<18:12,  3.81it/s]
 55%|██████████████████████████████████████████▋                                   | 5021/9182 [19:34<17:06,  4.05it/s]
 55%|██████████████████████████████████████████▋                                   | 5022/9182 [19:34<16:46,  4.13it/s]
 55%|██████████████████████████████████████████▋                                   | 5023/9182 [19:35<17:13,  4.03it/s]
 55%|██████████████████████████████████████████▋                                   | 5027/9182 [19:35<08:14,  8.41it/s]
 55%|██████████████████████████████████████████▋                                   | 5029/9182 [19:35<09:20,  7.41it/s]
 55%|██████████████████████████████████████████▋                                   | 5030/9182 [19:35<09:43,  7.12it/s]
 55%|██████████████████████████████████████████▋                                   | 5031/9182 [19:36<12:19,  5.62it/s]
 55%|██████████████████████████████████████████▋                                   | 5032/9182 [19:36<12:37,  5.48it/s]
 55%|██████████████████████████████████████████▊                                   | 5035/9182 [19:36<07:37,  9.07it/s]
 55%|██████████████████████████████████████████▊                                   | 5037/9182 [19:36<06:29, 10.64it/s]
 55%|██████████████████████████████████████████▊                                   | 5039/9182 [19:37<11:03,  6.24it/s]
 55%|██████████████████████████████████████████▊                                   | 5041/9182 [19:37<10:05,  6.84it/s]
 55%|██████████████████████████████████████████▊                                   | 5043/9182 [19:38<16:27,  4.19it/s]
 55%|██████████████████████████████████████████▊                                   | 5044/9182 [19:38<16:03,  4.29it/s]
 55%|██████████████████████████████████████████▊                                   | 5045/9182 [19:39<18:28,  3.73it/s]
 55%|██████████████████████████████████████████▊                                   | 5046/9182 [19:39<21:04,  3.27it/s]
 55%|██████████████████████████████████████████▊                                   | 5047/9182 [19:39<18:52,  3.65it/s]
 55%|██████████████████████████████████████████▉                                   | 5048/9182 [19:39<21:24,  3.22it/s]
 55%|██████████████████████████████████████████▉                                   | 5049/9182 [19:40<18:46,  3.67it/s]
 55%|██████████████████████████████████████████▉                                   | 5050/9182 [19:40<15:39,  4.40it/s]
 55%|██████████████████████████████████████████▉                                   | 5051/9182 [19:40<14:20,  4.80it/s]
 55%|██████████████████████████████████████████▉                                   | 5055/9182 [19:41<07:45,  8.87it/s]
 55%|██████████████████████████████████████████▉                                   | 5056/9182 [19:41<13:52,  4.96it/s]
 55%|██████████████████████████████████████████▉                                   | 5057/9182 [19:41<15:57,  4.31it/s]
 55%|██████████████████████████████████████████▉                                   | 5058/9182 [19:42<19:18,  3.56it/s]
 55%|██████████████████████████████████████████▉                                   | 5059/9182 [19:42<27:24,  2.51it/s]
 55%|██████████████████████████████████████████▉                                   | 5060/9182 [19:42<22:58,  2.99it/s]
 55%|██████████████████████████████████████████▉                                   | 5061/9182 [19:43<24:16,  2.83it/s]
 55%|███████████████████████████████████████████                                   | 5062/9182 [19:43<22:38,  3.03it/s]
 55%|███████████████████████████████████████████                                   | 5063/9182 [19:43<22:15,  3.08it/s]
 55%|███████████████████████████████████████████                                   | 5064/9182 [19:44<22:12,  3.09it/s]
 55%|███████████████████████████████████████████                                   | 5065/9182 [19:44<21:19,  3.22it/s]
 55%|███████████████████████████████████████████                                   | 5066/9182 [19:45<29:48,  2.30it/s]
 55%|███████████████████████████████████████████                                   | 5067/9182 [19:45<24:49,  2.76it/s]
 55%|███████████████████████████████████████████                                   | 5068/9182 [19:45<22:19,  3.07it/s]
 55%|███████████████████████████████████████████                                   | 5069/9182 [19:45<21:44,  3.15it/s]
 55%|███████████████████████████████████████████                                   | 5070/9182 [19:46<19:18,  3.55it/s]
 55%|███████████████████████████████████████████                                   | 5071/9182 [19:46<21:56,  3.12it/s]
 55%|███████████████████████████████████████████                                   | 5072/9182 [19:46<22:08,  3.09it/s]
 55%|███████████████████████████████████████████                                   | 5073/9182 [19:47<20:15,  3.38it/s]
 55%|███████████████████████████████████████████                                   | 5074/9182 [19:47<17:23,  3.94it/s]
 55%|███████████████████████████████████████████▏                                  | 5079/9182 [19:47<08:36,  7.94it/s]
 55%|███████████████████████████████████████████▏                                  | 5080/9182 [19:48<16:48,  4.07it/s]
 55%|███████████████████████████████████████████▏                                  | 5081/9182 [19:49<18:11,  3.76it/s]
 55%|███████████████████████████████████████████▏                                  | 5082/9182 [19:49<20:12,  3.38it/s]
 55%|███████████████████████████████████████████▏                                  | 5083/9182 [19:49<25:14,  2.71it/s]
 55%|███████████████████████████████████████████▏                                  | 5087/9182 [19:50<16:12,  4.21it/s]
 55%|███████████████████████████████████████████▏                                  | 5090/9182 [19:51<15:50,  4.30it/s]
 55%|███████████████████████████████████████████▏                                  | 5091/9182 [19:51<22:50,  2.99it/s]
 55%|███████████████████████████████████████████▎                                  | 5095/9182 [19:52<17:00,  4.01it/s]
 56%|███████████████████████████████████████████▎                                  | 5099/9182 [19:54<21:27,  3.17it/s]
 56%|███████████████████████████████████████████▎                                  | 5104/9182 [19:54<13:28,  5.04it/s]
 56%|███████████████████████████████████████████▎                                  | 5106/9182 [19:54<12:08,  5.59it/s]
 56%|███████████████████████████████████████████▍                                  | 5108/9182 [19:54<11:19,  6.00it/s]
 56%|███████████████████████████████████████████▍                                  | 5110/9182 [19:55<13:37,  4.98it/s]
 56%|███████████████████████████████████████████▍                                  | 5111/9182 [19:55<13:53,  4.89it/s]
 56%|███████████████████████████████████████████▍                                  | 5112/9182 [19:56<14:57,  4.53it/s]
 56%|███████████████████████████████████████████▍                                  | 5113/9182 [19:56<15:45,  4.30it/s]
 56%|███████████████████████████████████████████▍                                  | 5114/9182 [19:56<17:35,  3.85it/s]
 56%|███████████████████████████████████████████▍                                  | 5115/9182 [19:56<16:08,  4.20it/s]
 56%|███████████████████████████████████████████▍                                  | 5116/9182 [19:57<14:20,  4.73it/s]
 56%|███████████████████████████████████████████▍                                  | 5117/9182 [19:57<16:01,  4.23it/s]
 56%|███████████████████████████████████████████▌                                  | 5121/9182 [19:57<11:11,  6.05it/s]
 56%|███████████████████████████████████████████▌                                  | 5122/9182 [19:58<16:09,  4.19it/s]
 56%|███████████████████████████████████████████▌                                  | 5123/9182 [19:59<22:53,  2.96it/s]
 56%|███████████████████████████████████████████▌                                  | 5124/9182 [20:00<29:51,  2.27it/s]
 56%|███████████████████████████████████████████▌                                  | 5125/9182 [20:00<36:03,  1.88it/s]
 56%|███████████████████████████████████████████▌                                  | 5126/9182 [20:01<30:22,  2.23it/s]
 56%|███████████████████████████████████████████▌                                  | 5127/9182 [20:01<33:17,  2.03it/s]
 56%|███████████████████████████████████████████▌                                  | 5128/9182 [20:02<35:02,  1.93it/s]
 56%|███████████████████████████████████████████▌                                  | 5129/9182 [20:03<42:11,  1.60it/s]
 56%|███████████████████████████████████████████▌                                  | 5130/9182 [20:03<35:08,  1.92it/s]
 56%|███████████████████████████████████████████▌                                  | 5131/9182 [20:04<43:22,  1.56it/s]
 56%|███████████████████████████████████████████▌                                  | 5132/9182 [20:04<37:58,  1.78it/s]
 56%|███████████████████████████████████████████▌                                  | 5133/9182 [20:05<31:21,  2.15it/s]
 56%|███████████████████████████████████████████▌                                  | 5134/9182 [20:05<33:11,  2.03it/s]
 56%|███████████████████████████████████████████▌                                  | 5135/9182 [20:05<26:38,  2.53it/s]
 56%|███████████████████████████████████████████▋                                  | 5136/9182 [20:06<26:09,  2.58it/s]
 56%|███████████████████████████████████████████▋                                  | 5137/9182 [20:06<28:19,  2.38it/s]
 56%|███████████████████████████████████████████▋                                  | 5138/9182 [20:06<24:00,  2.81it/s]
 56%|███████████████████████████████████████████▋                                  | 5139/9182 [20:07<25:27,  2.65it/s]
 56%|███████████████████████████████████████████▋                                  | 5140/9182 [20:07<25:08,  2.68it/s]
 56%|███████████████████████████████████████████▋                                  | 5141/9182 [20:07<24:03,  2.80it/s]
 56%|███████████████████████████████████████████▋                                  | 5142/9182 [20:08<27:23,  2.46it/s]
 56%|███████████████████████████████████████████▋                                  | 5143/9182 [20:08<31:26,  2.14it/s]
 56%|███████████████████████████████████████████▋                                  | 5144/9182 [20:09<26:21,  2.55it/s]
 56%|███████████████████████████████████████████▋                                  | 5145/9182 [20:09<25:59,  2.59it/s]
 56%|███████████████████████████████████████████▋                                  | 5146/9182 [20:09<21:52,  3.08it/s]
 56%|███████████████████████████████████████████▋                                  | 5147/9182 [20:09<20:47,  3.23it/s]
 56%|███████████████████████████████████████████▋                                  | 5148/9182 [20:09<17:42,  3.80it/s]
 56%|███████████████████████████████████████████▋                                  | 5150/9182 [20:10<12:21,  5.44it/s]
 56%|███████████████████████████████████████████▊                                  | 5153/9182 [20:10<08:00,  8.39it/s]
 56%|███████████████████████████████████████████▊                                  | 5155/9182 [20:10<08:22,  8.01it/s]
 56%|███████████████████████████████████████████▊                                  | 5156/9182 [20:10<11:40,  5.74it/s]
 56%|███████████████████████████████████████████▊                                  | 5157/9182 [20:11<13:13,  5.08it/s]
 56%|███████████████████████████████████████████▊                                  | 5158/9182 [20:12<32:59,  2.03it/s]
 56%|███████████████████████████████████████████▊                                  | 5159/9182 [20:13<32:34,  2.06it/s]
 56%|███████████████████████████████████████████▊                                  | 5160/9182 [20:13<25:58,  2.58it/s]

 56%|███████████████████████████████████████████▊                                  | 5161/9182 [20:13<29:55,  2.24it/s]
 56%|███████████████████████████████████████████▊                                  | 5162/9182 [20:14<29:02,  2.31it/s]
 56%|███████████████████████████████████████████▊                                  | 5163/9182 [20:14<27:05,  2.47it/s]
 56%|███████████████████████████████████████████▊                                  | 5164/9182 [20:15<24:51,  2.69it/s]
 56%|███████████████████████████████████████████▉                                  | 5165/9182 [20:15<20:39,  3.24it/s]
 56%|███████████████████████████████████████████▉                                  | 5166/9182 [20:16<26:10,  2.56it/s]
 56%|███████████████████████████████████████████▉                                  | 5167/9182 [20:16<37:19,  1.79it/s]
 56%|███████████████████████████████████████████▉                                  | 5168/9182 [20:16<29:40,  2.25it/s]
 56%|███████████████████████████████████████████▉                                  | 5169/9182 [20:17<28:35,  2.34it/s]
 56%|███████████████████████████████████████████▉                                  | 5170/9182 [20:17<27:01,  2.47it/s]
 56%|███████████████████████████████████████████▉                                  | 5172/9182 [20:17<18:03,  3.70it/s]
 56%|███████████████████████████████████████████▉                                  | 5174/9182 [20:18<19:34,  3.41it/s]
 56%|███████████████████████████████████████████▉                                  | 5175/9182 [20:18<20:23,  3.27it/s]
 56%|███████████████████████████████████████████▉                                  | 5176/9182 [20:19<29:29,  2.26it/s]
 56%|███████████████████████████████████████████▉                                  | 5177/9182 [20:20<27:16,  2.45it/s]
 56%|███████████████████████████████████████████▉                                  | 5178/9182 [20:20<25:26,  2.62it/s]
 56%|███████████████████████████████████████████▉                                  | 5179/9182 [20:20<27:29,  2.43it/s]
 56%|████████████████████████████████████████████                                  | 5180/9182 [20:21<24:07,  2.76it/s]
 56%|████████████████████████████████████████████                                  | 5181/9182 [20:21<24:18,  2.74it/s]
 56%|████████████████████████████████████████████                                  | 5182/9182 [20:21<19:39,  3.39it/s]
 56%|████████████████████████████████████████████                                  | 5185/9182 [20:21<11:27,  5.81it/s]
 56%|████████████████████████████████████████████                                  | 5186/9182 [20:22<15:58,  4.17it/s]
 56%|████████████████████████████████████████████                                  | 5187/9182 [20:22<17:53,  3.72it/s]
 57%|████████████████████████████████████████████                                  | 5188/9182 [20:23<24:14,  2.75it/s]
 57%|████████████████████████████████████████████                                  | 5189/9182 [20:23<22:15,  2.99it/s]
 57%|████████████████████████████████████████████                                  | 5190/9182 [20:24<25:46,  2.58it/s]
 57%|████████████████████████████████████████████                                  | 5191/9182 [20:24<22:58,  2.90it/s]
 57%|████████████████████████████████████████████                                  | 5192/9182 [20:25<26:11,  2.54it/s]
 57%|████████████████████████████████████████████                                  | 5193/9182 [20:25<28:39,  2.32it/s]
 57%|████████████████████████████████████████████                                  | 5194/9182 [20:25<27:21,  2.43it/s]
 57%|████████████████████████████████████████████▏                                 | 5195/9182 [20:25<22:52,  2.91it/s]
 57%|████████████████████████████████████████████▏                                 | 5196/9182 [20:26<22:08,  3.00it/s]
 57%|████████████████████████████████████████████▏                                 | 5197/9182 [20:26<20:16,  3.28it/s]
 57%|████████████████████████████████████████████▏                                 | 5200/9182 [20:26<10:26,  6.35it/s]
 57%|████████████████████████████████████████████▏                                 | 5201/9182 [20:26<12:29,  5.31it/s]
 57%|████████████████████████████████████████████▏                                 | 5202/9182 [20:27<12:47,  5.18it/s]
 57%|████████████████████████████████████████████▏                                 | 5203/9182 [20:27<14:22,  4.61it/s]
 57%|████████████████████████████████████████████▏                                 | 5204/9182 [20:27<14:32,  4.56it/s]
 57%|████████████████████████████████████████████▏                                 | 5205/9182 [20:27<14:28,  4.58it/s]
 57%|████████████████████████████████████████████▏                                 | 5207/9182 [20:27<10:08,  6.53it/s]
 57%|████████████████████████████████████████████▏                                 | 5208/9182 [20:28<09:57,  6.65it/s]
 57%|████████████████████████████████████████████▏                                 | 5209/9182 [20:28<13:38,  4.86it/s]
 57%|████████████████████████████████████████████▎                                 | 5210/9182 [20:28<16:18,  4.06it/s]
 57%|████████████████████████████████████████████▎                                 | 5212/9182 [20:29<16:25,  4.03it/s]
 57%|████████████████████████████████████████████▎                                 | 5213/9182 [20:30<27:46,  2.38it/s]
 57%|████████████████████████████████████████████▎                                 | 5214/9182 [20:30<26:57,  2.45it/s]
 57%|████████████████████████████████████████████▎                                 | 5215/9182 [20:31<24:36,  2.69it/s]
 57%|████████████████████████████████████████████▎                                 | 5216/9182 [20:31<29:58,  2.21it/s]
 57%|████████████████████████████████████████████▎                                 | 5217/9182 [20:31<28:15,  2.34it/s]
 57%|████████████████████████████████████████████▎                                 | 5218/9182 [20:32<29:16,  2.26it/s]
 57%|████████████████████████████████████████████▎                                 | 5219/9182 [20:32<25:21,  2.60it/s]
 57%|████████████████████████████████████████████▎                                 | 5223/9182 [20:33<20:10,  3.27it/s]
 57%|████████████████████████████████████████████▍                                 | 5224/9182 [20:34<23:32,  2.80it/s]
 57%|████████████████████████████████████████████▍                                 | 5225/9182 [20:35<24:53,  2.65it/s]
 57%|████████████████████████████████████████████▍                                 | 5226/9182 [20:35<29:44,  2.22it/s]
 57%|████████████████████████████████████████████▍                                 | 5227/9182 [20:35<24:17,  2.71it/s]
 57%|████████████████████████████████████████████▍                                 | 5228/9182 [20:36<32:13,  2.05it/s]
 57%|████████████████████████████████████████████▍                                 | 5229/9182 [20:36<25:36,  2.57it/s]
 57%|████████████████████████████████████████████▍                                 | 5232/9182 [20:37<20:41,  3.18it/s]
 57%|████████████████████████████████████████████▍                                 | 5233/9182 [20:37<19:41,  3.34it/s]
 57%|████████████████████████████████████████████▍                                 | 5234/9182 [20:38<23:49,  2.76it/s]
 57%|████████████████████████████████████████████▍                                 | 5236/9182 [20:38<17:53,  3.68it/s]
 57%|████████████████████████████████████████████▍                                 | 5237/9182 [20:39<21:43,  3.03it/s]
 57%|████████████████████████████████████████████▍                                 | 5238/9182 [20:39<26:35,  2.47it/s]
 57%|████████████████████████████████████████████▌                                 | 5239/9182 [20:40<24:22,  2.70it/s]
 57%|████████████████████████████████████████████▌                                 | 5240/9182 [20:40<31:21,  2.09it/s]
 57%|████████████████████████████████████████████▌                                 | 5241/9182 [20:40<25:14,  2.60it/s]
 57%|████████████████████████████████████████████▌                                 | 5242/9182 [20:40<20:32,  3.20it/s]
 57%|████████████████████████████████████████████▌                                 | 5246/9182 [20:40<09:07,  7.18it/s]
 57%|████████████████████████████████████████████▌                                 | 5248/9182 [20:41<08:51,  7.41it/s]
 57%|████████████████████████████████████████████▌                                 | 5250/9182 [20:41<07:57,  8.23it/s]
 57%|████████████████████████████████████████████▋                                 | 5254/9182 [20:41<05:53, 11.11it/s]
 57%|████████████████████████████████████████████▋                                 | 5256/9182 [20:42<08:30,  7.70it/s]
 57%|████████████████████████████████████████████▋                                 | 5258/9182 [20:42<12:03,  5.42it/s]
 57%|████████████████████████████████████████████▋                                 | 5260/9182 [20:43<12:48,  5.10it/s]
 57%|████████████████████████████████████████████▋                                 | 5261/9182 [20:43<14:19,  4.56it/s]
 57%|████████████████████████████████████████████▋                                 | 5262/9182 [20:44<19:54,  3.28it/s]
 57%|████████████████████████████████████████████▋                                 | 5263/9182 [20:44<23:57,  2.73it/s]
 57%|████████████████████████████████████████████▋                                 | 5264/9182 [20:45<24:43,  2.64it/s]
 57%|████████████████████████████████████████████▋                                 | 5265/9182 [20:45<22:44,  2.87it/s]
 57%|████████████████████████████████████████████▋                                 | 5266/9182 [20:45<19:18,  3.38it/s]
 57%|████████████████████████████████████████████▋                                 | 5267/9182 [20:45<18:01,  3.62it/s]
 57%|████████████████████████████████████████████▊                                 | 5268/9182 [20:46<18:30,  3.53it/s]
 57%|████████████████████████████████████████████▊                                 | 5272/9182 [20:46<09:24,  6.92it/s]
 57%|████████████████████████████████████████████▊                                 | 5273/9182 [20:46<09:02,  7.20it/s]
 57%|████████████████████████████████████████████▊                                 | 5274/9182 [20:46<08:39,  7.52it/s]
 57%|████████████████████████████████████████████▊                                 | 5275/9182 [20:46<12:03,  5.40it/s]
 57%|████████████████████████████████████████████▊                                 | 5276/9182 [20:47<13:38,  4.77it/s]
 57%|████████████████████████████████████████████▊                                 | 5277/9182 [20:47<16:12,  4.02it/s]
 57%|████████████████████████████████████████████▊                                 | 5278/9182 [20:48<19:53,  3.27it/s]
 57%|████████████████████████████████████████████▊                                 | 5279/9182 [20:48<22:34,  2.88it/s]
 58%|████████████████████████████████████████████▊                                 | 5280/9182 [20:48<21:38,  3.00it/s]
 58%|████████████████████████████████████████████▊                                 | 5282/9182 [20:49<18:58,  3.42it/s]
 58%|████████████████████████████████████████████▉                                 | 5283/9182 [20:49<17:36,  3.69it/s]
 58%|████████████████████████████████████████████▉                                 | 5284/9182 [20:49<16:19,  3.98it/s]
 58%|████████████████████████████████████████████▉                                 | 5285/9182 [20:50<14:37,  4.44it/s]
 58%|████████████████████████████████████████████▉                                 | 5286/9182 [20:50<17:36,  3.69it/s]
 58%|████████████████████████████████████████████▉                                 | 5287/9182 [20:50<18:47,  3.46it/s]
 58%|████████████████████████████████████████████▉                                 | 5288/9182 [20:50<15:32,  4.18it/s]
 58%|████████████████████████████████████████████▉                                 | 5292/9182 [20:51<07:55,  8.18it/s]
 58%|████████████████████████████████████████████▉                                 | 5293/9182 [20:51<10:01,  6.47it/s]
 58%|████████████████████████████████████████████▉                                 | 5294/9182 [20:51<15:39,  4.14it/s]
 58%|████████████████████████████████████████████▉                                 | 5295/9182 [20:52<24:03,  2.69it/s]
 58%|████████████████████████████████████████████▉                                 | 5296/9182 [20:52<22:02,  2.94it/s]
 58%|█████████████████████████████████████████████                                 | 5299/9182 [20:53<13:38,  4.74it/s]
 58%|█████████████████████████████████████████████                                 | 5300/9182 [20:53<15:27,  4.19it/s]
 58%|█████████████████████████████████████████████                                 | 5303/9182 [20:53<10:54,  5.92it/s]
 58%|█████████████████████████████████████████████                                 | 5304/9182 [20:54<12:40,  5.10it/s]
 58%|█████████████████████████████████████████████                                 | 5305/9182 [20:55<22:01,  2.93it/s]
 58%|█████████████████████████████████████████████                                 | 5306/9182 [20:55<21:22,  3.02it/s]
 58%|█████████████████████████████████████████████                                 | 5307/9182 [20:55<22:29,  2.87it/s]
 58%|█████████████████████████████████████████████                                 | 5308/9182 [20:56<22:16,  2.90it/s]
 58%|█████████████████████████████████████████████                                 | 5309/9182 [20:56<19:30,  3.31it/s]
 58%|█████████████████████████████████████████████                                 | 5310/9182 [20:56<18:55,  3.41it/s]
 58%|█████████████████████████████████████████████                                 | 5311/9182 [20:56<22:08,  2.91it/s]
 58%|█████████████████████████████████████████████                                 | 5312/9182 [20:57<18:02,  3.58it/s]
 58%|█████████████████████████████████████████████▏                                | 5313/9182 [20:57<14:47,  4.36it/s]
 58%|█████████████████████████████████████████████▏                                | 5314/9182 [20:57<21:07,  3.05it/s]
 58%|█████████████████████████████████████████████▏                                | 5315/9182 [20:57<18:48,  3.43it/s]
 58%|█████████████████████████████████████████████▏                                | 5316/9182 [20:58<19:41,  3.27it/s]
 58%|█████████████████████████████████████████████▏                                | 5317/9182 [20:58<17:11,  3.75it/s]
 58%|█████████████████████████████████████████████▏                                | 5321/9182 [20:58<07:36,  8.46it/s]
 58%|█████████████████████████████████████████████▏                                | 5323/9182 [21:00<23:32,  2.73it/s]
 58%|█████████████████████████████████████████████▏                                | 5324/9182 [21:00<21:47,  2.95it/s]
 58%|█████████████████████████████████████████████▏                                | 5325/9182 [21:00<19:46,  3.25it/s]
 58%|█████████████████████████████████████████████▏                                | 5326/9182 [21:01<18:25,  3.49it/s]
 58%|█████████████████████████████████████████████▎                                | 5327/9182 [21:01<15:42,  4.09it/s]
 58%|█████████████████████████████████████████████▎                                | 5328/9182 [21:01<17:18,  3.71it/s]
 58%|█████████████████████████████████████████████▎                                | 5332/9182 [21:02<11:21,  5.65it/s]
 58%|█████████████████████████████████████████████▎                                | 5333/9182 [21:02<12:08,  5.28it/s]
 58%|█████████████████████████████████████████████▎                                | 5334/9182 [21:02<13:34,  4.72it/s]
 58%|█████████████████████████████████████████████▎                                | 5335/9182 [21:02<13:06,  4.89it/s]

 58%|█████████████████████████████████████████████▎                                | 5336/9182 [21:03<19:24,  3.30it/s]
 58%|█████████████████████████████████████████████▎                                | 5337/9182 [21:03<20:27,  3.13it/s]
 58%|█████████████████████████████████████████████▎                                | 5340/9182 [21:04<15:29,  4.13it/s]
 58%|█████████████████████████████████████████████▎                                | 5341/9182 [21:04<13:54,  4.60it/s]
 58%|█████████████████████████████████████████████▍                                | 5342/9182 [21:04<16:36,  3.85it/s]
 58%|█████████████████████████████████████████████▍                                | 5343/9182 [21:05<18:51,  3.39it/s]
 58%|█████████████████████████████████████████████▍                                | 5344/9182 [21:05<16:22,  3.90it/s]
 58%|█████████████████████████████████████████████▍                                | 5345/9182 [21:05<24:43,  2.59it/s]
 58%|█████████████████████████████████████████████▍                                | 5349/9182 [21:06<13:30,  4.73it/s]
 58%|█████████████████████████████████████████████▍                                | 5350/9182 [21:06<12:42,  5.02it/s]
 58%|█████████████████████████████████████████████▍                                | 5351/9182 [21:06<13:01,  4.90it/s]
 58%|█████████████████████████████████████████████▍                                | 5353/9182 [21:07<12:57,  4.92it/s]
 58%|█████████████████████████████████████████████▍                                | 5354/9182 [21:07<14:38,  4.36it/s]
 58%|█████████████████████████████████████████████▍                                | 5355/9182 [21:07<14:21,  4.44it/s]
 58%|█████████████████████████████████████████████▍                                | 5356/9182 [21:08<20:48,  3.06it/s]
 58%|█████████████████████████████████████████████▌                                | 5357/9182 [21:08<18:22,  3.47it/s]
 58%|█████████████████████████████████████████████▌                                | 5358/9182 [21:08<17:08,  3.72it/s]
 58%|█████████████████████████████████████████████▌                                | 5359/9182 [21:08<15:51,  4.02it/s]
 58%|█████████████████████████████████████████████▌                                | 5363/9182 [21:09<10:37,  5.99it/s]
 58%|█████████████████████████████████████████████▌                                | 5364/9182 [21:09<12:41,  5.02it/s]
 58%|█████████████████████████████████████████████▌                                | 5365/9182 [21:10<13:48,  4.61it/s]
 58%|█████████████████████████████████████████████▌                                | 5366/9182 [21:10<15:28,  4.11it/s]
 58%|█████████████████████████████████████████████▌                                | 5367/9182 [21:10<17:36,  3.61it/s]
 58%|█████████████████████████████████████████████▌                                | 5368/9182 [21:11<19:26,  3.27it/s]
 58%|█████████████████████████████████████████████▌                                | 5370/9182 [21:11<12:39,  5.02it/s]
 58%|█████████████████████████████████████████████▋                                | 5371/9182 [21:11<13:19,  4.77it/s]
 59%|█████████████████████████████████████████████▋                                | 5372/9182 [21:12<17:55,  3.54it/s]
 59%|█████████████████████████████████████████████▋                                | 5373/9182 [21:12<19:40,  3.23it/s]
 59%|█████████████████████████████████████████████▋                                | 5374/9182 [21:12<16:42,  3.80it/s]
 59%|█████████████████████████████████████████████▋                                | 5377/9182 [21:12<11:35,  5.47it/s]
 59%|█████████████████████████████████████████████▋                                | 5378/9182 [21:12<10:44,  5.90it/s]
 59%|█████████████████████████████████████████████▋                                | 5382/9182 [21:13<06:08, 10.31it/s]
 59%|█████████████████████████████████████████████▋                                | 5384/9182 [21:13<05:40, 11.15it/s]
 59%|█████████████████████████████████████████████▊                                | 5386/9182 [21:13<09:33,  6.62it/s]
 59%|█████████████████████████████████████████████▊                                | 5388/9182 [21:14<10:32,  6.00it/s]
 59%|█████████████████████████████████████████████▊                                | 5389/9182 [21:15<16:49,  3.76it/s]
 59%|█████████████████████████████████████████████▊                                | 5390/9182 [21:15<19:50,  3.19it/s]
 59%|█████████████████████████████████████████████▊                                | 5391/9182 [21:16<25:47,  2.45it/s]
 59%|█████████████████████████████████████████████▊                                | 5394/9182 [21:16<15:14,  4.14it/s]
 59%|█████████████████████████████████████████████▊                                | 5395/9182 [21:16<15:25,  4.09it/s]
 59%|█████████████████████████████████████████████▊                                | 5396/9182 [21:17<16:15,  3.88it/s]
 59%|█████████████████████████████████████████████▊                                | 5397/9182 [21:17<16:09,  3.90it/s]
 59%|█████████████████████████████████████████████▊                                | 5398/9182 [21:17<16:35,  3.80it/s]
 59%|█████████████████████████████████████████████▊                                | 5399/9182 [21:17<14:40,  4.30it/s]
 59%|█████████████████████████████████████████████▉                                | 5404/9182 [21:17<06:01, 10.45it/s]
 59%|█████████████████████████████████████████████▉                                | 5406/9182 [21:18<07:10,  8.78it/s]
 59%|█████████████████████████████████████████████▉                                | 5408/9182 [21:18<10:40,  5.89it/s]
 59%|█████████████████████████████████████████████▉                                | 5413/9182 [21:18<06:09, 10.21it/s]
 59%|█████████████████████████████████████████████▉                                | 5415/9182 [21:19<11:57,  5.25it/s]
 59%|██████████████████████████████████████████████                                | 5417/9182 [21:20<09:57,  6.30it/s]
 59%|██████████████████████████████████████████████                                | 5419/9182 [21:20<09:16,  6.76it/s]
 59%|██████████████████████████████████████████████                                | 5421/9182 [21:20<08:44,  7.17it/s]
 59%|██████████████████████████████████████████████                                | 5423/9182 [21:20<08:32,  7.34it/s]
 59%|██████████████████████████████████████████████                                | 5425/9182 [21:20<07:07,  8.79it/s]
 59%|██████████████████████████████████████████████                                | 5427/9182 [21:21<07:54,  7.91it/s]
 59%|██████████████████████████████████████████████                                | 5429/9182 [21:21<06:44,  9.27it/s]
 59%|██████████████████████████████████████████████▏                               | 5431/9182 [21:21<09:21,  6.68it/s]
 59%|██████████████████████████████████████████████▏                               | 5432/9182 [21:21<08:54,  7.02it/s]
 59%|██████████████████████████████████████████████▏                               | 5434/9182 [21:22<09:02,  6.90it/s]
 59%|██████████████████████████████████████████████▏                               | 5435/9182 [21:22<09:29,  6.58it/s]
 59%|██████████████████████████████████████████████▏                               | 5436/9182 [21:22<12:21,  5.05it/s]
 59%|██████████████████████████████████████████████▏                               | 5437/9182 [21:23<14:13,  4.39it/s]
 59%|██████████████████████████████████████████████▏                               | 5438/9182 [21:23<16:15,  3.84it/s]
 59%|██████████████████████████████████████████████▏                               | 5439/9182 [21:23<16:49,  3.71it/s]
 59%|██████████████████████████████████████████████▏                               | 5442/9182 [21:23<09:25,  6.61it/s]
 59%|██████████████████████████████████████████████▏                               | 5444/9182 [21:24<09:29,  6.56it/s]
 59%|██████████████████████████████████████████████▎                               | 5445/9182 [21:24<09:07,  6.82it/s]
 59%|██████████████████████████████████████████████▎                               | 5446/9182 [21:24<09:35,  6.49it/s]
 59%|██████████████████████████████████████████████▎                               | 5447/9182 [21:24<12:34,  4.95it/s]
 59%|██████████████████████████████████████████████▎                               | 5448/9182 [21:25<13:02,  4.77it/s]
 59%|██████████████████████████████████████████████▎                               | 5449/9182 [21:25<16:57,  3.67it/s]
 59%|██████████████████████████████████████████████▎                               | 5450/9182 [21:26<21:39,  2.87it/s]
 59%|██████████████████████████████████████████████▎                               | 5452/9182 [21:27<23:25,  2.65it/s]
 59%|██████████████████████████████████████████████▎                               | 5453/9182 [21:27<28:46,  2.16it/s]
 59%|██████████████████████████████████████████████▎                               | 5454/9182 [21:28<28:45,  2.16it/s]
 59%|██████████████████████████████████████████████▎                               | 5455/9182 [21:28<22:46,  2.73it/s]
 59%|██████████████████████████████████████████████▎                               | 5456/9182 [21:28<24:14,  2.56it/s]
 59%|██████████████████████████████████████████████▎                               | 5457/9182 [21:29<23:55,  2.59it/s]
 59%|██████████████████████████████████████████████▎                               | 5458/9182 [21:29<19:00,  3.27it/s]
 59%|██████████████████████████████████████████████▎                               | 5459/9182 [21:29<15:58,  3.88it/s]
 59%|██████████████████████████████████████████████▍                               | 5460/9182 [21:29<16:14,  3.82it/s]
 59%|██████████████████████████████████████████████▍                               | 5461/9182 [21:29<17:12,  3.60it/s]
 59%|██████████████████████████████████████████████▍                               | 5463/9182 [21:30<11:12,  5.53it/s]
 60%|██████████████████████████████████████████████▍                               | 5464/9182 [21:30<11:21,  5.46it/s]
 60%|██████████████████████████████████████████████▍                               | 5465/9182 [21:30<14:40,  4.22it/s]
 60%|██████████████████████████████████████████████▍                               | 5466/9182 [21:31<27:42,  2.24it/s]
 60%|██████████████████████████████████████████████▍                               | 5467/9182 [21:32<31:05,  1.99it/s]
 60%|██████████████████████████████████████████████▍                               | 5468/9182 [21:32<27:04,  2.29it/s]
 60%|██████████████████████████████████████████████▍                               | 5469/9182 [21:32<23:19,  2.65it/s]
 60%|██████████████████████████████████████████████▍                               | 5470/9182 [21:33<19:33,  3.16it/s]
 60%|██████████████████████████████████████████████▍                               | 5471/9182 [21:33<17:51,  3.46it/s]
 60%|██████████████████████████████████████████████▍                               | 5472/9182 [21:33<20:42,  2.99it/s]
 60%|██████████████████████████████████████████████▍                               | 5473/9182 [21:33<18:48,  3.29it/s]
 60%|██████████████████████████████████████████████▌                               | 5474/9182 [21:34<15:23,  4.01it/s]
 60%|██████████████████████████████████████████████▌                               | 5475/9182 [21:34<15:36,  3.96it/s]
 60%|██████████████████████████████████████████████▌                               | 5476/9182 [21:34<17:13,  3.59it/s]
 60%|██████████████████████████████████████████████▌                               | 5477/9182 [21:34<15:36,  3.96it/s]
 60%|██████████████████████████████████████████████▌                               | 5479/9182 [21:34<10:20,  5.97it/s]
 60%|██████████████████████████████████████████████▌                               | 5480/9182 [21:35<12:34,  4.91it/s]
 60%|██████████████████████████████████████████████▌                               | 5481/9182 [21:35<12:16,  5.02it/s]
 60%|██████████████████████████████████████████████▌                               | 5482/9182 [21:36<19:19,  3.19it/s]
 60%|██████████████████████████████████████████████▌                               | 5483/9182 [21:36<19:14,  3.20it/s]
 60%|██████████████████████████████████████████████▌                               | 5484/9182 [21:36<24:04,  2.56it/s]
 60%|██████████████████████████████████████████████▌                               | 5485/9182 [21:37<19:36,  3.14it/s]
 60%|██████████████████████████████████████████████▌                               | 5486/9182 [21:37<19:23,  3.18it/s]
 60%|██████████████████████████████████████████████▌                               | 5487/9182 [21:37<20:44,  2.97it/s]
 60%|██████████████████████████████████████████████▌                               | 5488/9182 [21:38<20:38,  2.98it/s]
 60%|██████████████████████████████████████████████▋                               | 5489/9182 [21:38<19:26,  3.16it/s]
 60%|██████████████████████████████████████████████▋                               | 5490/9182 [21:38<15:45,  3.90it/s]
 60%|██████████████████████████████████████████████▋                               | 5491/9182 [21:39<24:05,  2.55it/s]
 60%|██████████████████████████████████████████████▋                               | 5492/9182 [21:39<22:01,  2.79it/s]
 60%|██████████████████████████████████████████████▋                               | 5493/9182 [21:39<17:23,  3.53it/s]
 60%|██████████████████████████████████████████████▋                               | 5494/9182 [21:39<16:16,  3.78it/s]
 60%|██████████████████████████████████████████████▋                               | 5495/9182 [21:40<17:58,  3.42it/s]
 60%|██████████████████████████████████████████████▋                               | 5496/9182 [21:40<15:47,  3.89it/s]
 60%|██████████████████████████████████████████████▋                               | 5500/9182 [21:40<06:55,  8.85it/s]
 60%|██████████████████████████████████████████████▋                               | 5502/9182 [21:41<10:53,  5.63it/s]
 60%|██████████████████████████████████████████████▊                               | 5504/9182 [21:41<08:46,  6.99it/s]
 60%|██████████████████████████████████████████████▊                               | 5506/9182 [21:41<09:39,  6.34it/s]
 60%|██████████████████████████████████████████████▊                               | 5507/9182 [21:42<20:45,  2.95it/s]
 60%|██████████████████████████████████████████████▊                               | 5508/9182 [21:43<22:46,  2.69it/s]
 60%|██████████████████████████████████████████████▊                               | 5509/9182 [21:43<24:31,  2.50it/s]
 60%|██████████████████████████████████████████████▊                               | 5510/9182 [21:44<23:52,  2.56it/s]
 60%|██████████████████████████████████████████████▊                               | 5511/9182 [21:44<21:38,  2.83it/s]
 60%|██████████████████████████████████████████████▊                               | 5512/9182 [21:44<20:47,  2.94it/s]
 60%|██████████████████████████████████████████████▊                               | 5513/9182 [21:45<21:26,  2.85it/s]
 60%|██████████████████████████████████████████████▊                               | 5514/9182 [21:45<22:55,  2.67it/s]
 60%|██████████████████████████████████████████████▊                               | 5515/9182 [21:45<21:30,  2.84it/s]
 60%|██████████████████████████████████████████████▊                               | 5516/9182 [21:46<24:46,  2.47it/s]
 60%|██████████████████████████████████████████████▊                               | 5517/9182 [21:47<31:20,  1.95it/s]
 60%|██████████████████████████████████████████████▊                               | 5518/9182 [21:47<30:44,  1.99it/s]
 60%|██████████████████████████████████████████████▉                               | 5519/9182 [21:49<49:08,  1.24it/s]

 60%|██████████████████████████████████████████████▉                               | 5520/9182 [21:49<37:45,  1.62it/s]
 60%|██████████████████████████████████████████████▉                               | 5521/9182 [21:49<35:04,  1.74it/s]
 60%|██████████████████████████████████████████████▉                               | 5522/9182 [21:50<38:08,  1.60it/s]
 60%|██████████████████████████████████████████████▉                               | 5523/9182 [21:50<28:52,  2.11it/s]
 60%|██████████████████████████████████████████████▉                               | 5527/9182 [21:50<12:39,  4.81it/s]
 60%|██████████████████████████████████████████████▉                               | 5528/9182 [21:51<18:29,  3.29it/s]
 60%|██████████████████████████████████████████████▉                               | 5530/9182 [21:51<16:17,  3.74it/s]
 60%|██████████████████████████████████████████████▉                               | 5531/9182 [21:52<18:28,  3.29it/s]
 60%|██████████████████████████████████████████████▉                               | 5532/9182 [21:53<26:59,  2.25it/s]
 60%|███████████████████████████████████████████████                               | 5533/9182 [21:53<27:29,  2.21it/s]
 60%|███████████████████████████████████████████████                               | 5534/9182 [21:54<29:02,  2.09it/s]
 60%|███████████████████████████████████████████████                               | 5535/9182 [21:55<48:35,  1.25it/s]
 60%|███████████████████████████████████████████████                               | 5536/9182 [21:56<40:50,  1.49it/s]
 60%|███████████████████████████████████████████████                               | 5537/9182 [21:56<33:23,  1.82it/s]
 60%|███████████████████████████████████████████████                               | 5538/9182 [21:57<31:52,  1.91it/s]
 60%|███████████████████████████████████████████████                               | 5539/9182 [21:57<27:25,  2.21it/s]
 60%|███████████████████████████████████████████████                               | 5540/9182 [21:57<25:26,  2.39it/s]
 60%|███████████████████████████████████████████████                               | 5541/9182 [21:57<21:17,  2.85it/s]
 60%|███████████████████████████████████████████████                               | 5542/9182 [21:58<21:19,  2.85it/s]
 60%|███████████████████████████████████████████████                               | 5543/9182 [21:58<16:59,  3.57it/s]
 60%|███████████████████████████████████████████████                               | 5544/9182 [21:59<22:01,  2.75it/s]
 60%|███████████████████████████████████████████████                               | 5545/9182 [21:59<25:50,  2.35it/s]
 60%|███████████████████████████████████████████████                               | 5546/9182 [21:59<22:39,  2.68it/s]
 60%|███████████████████████████████████████████████                               | 5547/9182 [21:59<19:32,  3.10it/s]
 60%|███████████████████████████████████████████████▏                              | 5550/9182 [22:00<11:30,  5.26it/s]
 60%|███████████████████████████████████████████████▏                              | 5551/9182 [22:00<11:11,  5.41it/s]
 60%|███████████████████████████████████████████████▏                              | 5552/9182 [22:00<12:31,  4.83it/s]
 60%|███████████████████████████████████████████████▏                              | 5553/9182 [22:01<13:41,  4.41it/s]
 60%|███████████████████████████████████████████████▏                              | 5554/9182 [22:01<14:24,  4.20it/s]
 60%|███████████████████████████████████████████████▏                              | 5555/9182 [22:01<19:36,  3.08it/s]
 61%|███████████████████████████████████████████████▏                              | 5556/9182 [22:01<16:38,  3.63it/s]
 61%|███████████████████████████████████████████████▏                              | 5557/9182 [22:02<21:07,  2.86it/s]
 61%|███████████████████████████████████████████████▏                              | 5558/9182 [22:02<18:53,  3.20it/s]
 61%|███████████████████████████████████████████████▏                              | 5559/9182 [22:03<24:24,  2.47it/s]
 61%|███████████████████████████████████████████████▏                              | 5560/9182 [22:03<22:21,  2.70it/s]
 61%|███████████████████████████████████████████████▏                              | 5561/9182 [22:04<21:48,  2.77it/s]
 61%|███████████████████████████████████████████████▏                              | 5562/9182 [22:04<25:12,  2.39it/s]
 61%|███████████████████████████████████████████████▎                              | 5563/9182 [22:04<19:59,  3.02it/s]
 61%|███████████████████████████████████████████████▎                              | 5566/9182 [22:05<14:28,  4.16it/s]
 61%|███████████████████████████████████████████████▎                              | 5567/9182 [22:05<12:44,  4.73it/s]
 61%|███████████████████████████████████████████████▎                              | 5568/9182 [22:05<14:17,  4.21it/s]
 61%|███████████████████████████████████████████████▎                              | 5569/9182 [22:05<14:35,  4.13it/s]
 61%|███████████████████████████████████████████████▎                              | 5570/9182 [22:06<15:18,  3.93it/s]
 61%|███████████████████████████████████████████████▎                              | 5571/9182 [22:06<15:25,  3.90it/s]
 61%|███████████████████████████████████████████████▎                              | 5572/9182 [22:06<17:38,  3.41it/s]
 61%|███████████████████████████████████████████████▎                              | 5573/9182 [22:07<19:11,  3.13it/s]
 61%|███████████████████████████████████████████████▎                              | 5576/9182 [22:07<12:38,  4.75it/s]
 61%|███████████████████████████████████████████████▍                              | 5577/9182 [22:07<12:22,  4.86it/s]
 61%|███████████████████████████████████████████████▍                              | 5578/9182 [22:07<12:32,  4.79it/s]
 61%|███████████████████████████████████████████████▍                              | 5579/9182 [22:08<17:01,  3.53it/s]
 61%|███████████████████████████████████████████████▍                              | 5580/9182 [22:09<23:46,  2.53it/s]
 61%|███████████████████████████████████████████████▍                              | 5581/9182 [22:09<19:16,  3.11it/s]
 61%|███████████████████████████████████████████████▍                              | 5582/9182 [22:09<16:51,  3.56it/s]
 61%|███████████████████████████████████████████████▍                              | 5583/9182 [22:10<22:10,  2.70it/s]
 61%|███████████████████████████████████████████████▍                              | 5584/9182 [22:10<20:06,  2.98it/s]
 61%|███████████████████████████████████████████████▍                              | 5585/9182 [22:11<33:37,  1.78it/s]
 61%|███████████████████████████████████████████████▍                              | 5588/9182 [22:11<17:05,  3.50it/s]
 61%|███████████████████████████████████████████████▍                              | 5589/9182 [22:12<21:36,  2.77it/s]
 61%|███████████████████████████████████████████████▍                              | 5590/9182 [22:12<24:23,  2.45it/s]
 61%|███████████████████████████████████████████████▍                              | 5591/9182 [22:14<37:35,  1.59it/s]
 61%|███████████████████████████████████████████████▌                              | 5592/9182 [22:14<32:39,  1.83it/s]
 61%|███████████████████████████████████████████████▌                              | 5593/9182 [22:14<25:45,  2.32it/s]
 61%|███████████████████████████████████████████████▌                              | 5594/9182 [22:14<23:46,  2.51it/s]
 61%|███████████████████████████████████████████████▌                              | 5595/9182 [22:14<19:58,  2.99it/s]
 61%|███████████████████████████████████████████████▌                              | 5599/9182 [22:15<08:34,  6.97it/s]
 61%|███████████████████████████████████████████████▌                              | 5601/9182 [22:15<08:18,  7.19it/s]
 61%|███████████████████████████████████████████████▌                              | 5606/9182 [22:16<10:08,  5.88it/s]
 61%|███████████████████████████████████████████████▋                              | 5608/9182 [22:16<10:48,  5.51it/s]
 61%|███████████████████████████████████████████████▋                              | 5609/9182 [22:16<10:23,  5.73it/s]
 61%|███████████████████████████████████████████████▋                              | 5610/9182 [22:16<09:52,  6.02it/s]
 61%|███████████████████████████████████████████████▋                              | 5612/9182 [22:17<10:27,  5.69it/s]
 61%|███████████████████████████████████████████████▋                              | 5613/9182 [22:17<11:59,  4.96it/s]
 61%|███████████████████████████████████████████████▋                              | 5614/9182 [22:18<18:45,  3.17it/s]
 61%|███████████████████████████████████████████████▋                              | 5615/9182 [22:18<20:15,  2.93it/s]
 61%|███████████████████████████████████████████████▋                              | 5616/9182 [22:19<22:57,  2.59it/s]
 61%|███████████████████████████████████████████████▋                              | 5617/9182 [22:19<22:44,  2.61it/s]
 61%|███████████████████████████████████████████████▋                              | 5618/9182 [22:20<20:15,  2.93it/s]
 61%|███████████████████████████████████████████████▋                              | 5619/9182 [22:20<19:10,  3.10it/s]
 61%|███████████████████████████████████████████████▋                              | 5620/9182 [22:20<20:00,  2.97it/s]
 61%|███████████████████████████████████████████████▋                              | 5621/9182 [22:21<23:23,  2.54it/s]
 61%|███████████████████████████████████████████████▊                              | 5622/9182 [22:21<24:52,  2.39it/s]
 61%|███████████████████████████████████████████████▊                              | 5623/9182 [22:22<24:06,  2.46it/s]
 61%|███████████████████████████████████████████████▊                              | 5624/9182 [22:22<26:13,  2.26it/s]
 61%|███████████████████████████████████████████████▊                              | 5625/9182 [22:22<23:06,  2.57it/s]
 61%|███████████████████████████████████████████████▊                              | 5626/9182 [22:23<28:59,  2.04it/s]
 61%|███████████████████████████████████████████████▊                              | 5627/9182 [22:24<28:21,  2.09it/s]
 61%|███████████████████████████████████████████████▊                              | 5628/9182 [22:24<31:09,  1.90it/s]
 61%|███████████████████████████████████████████████▊                              | 5629/9182 [22:24<26:24,  2.24it/s]
 61%|███████████████████████████████████████████████▊                              | 5630/9182 [22:25<23:21,  2.53it/s]
 61%|███████████████████████████████████████████████▊                              | 5631/9182 [22:25<24:36,  2.41it/s]
 61%|███████████████████████████████████████████████▊                              | 5632/9182 [22:26<23:31,  2.51it/s]
 61%|███████████████████████████████████████████████▊                              | 5633/9182 [22:26<27:16,  2.17it/s]
 61%|███████████████████████████████████████████████▊                              | 5634/9182 [22:27<23:45,  2.49it/s]
 61%|███████████████████████████████████████████████▊                              | 5635/9182 [22:27<30:44,  1.92it/s]
 61%|███████████████████████████████████████████████▉                              | 5636/9182 [22:28<25:11,  2.35it/s]
 61%|███████████████████████████████████████████████▉                              | 5637/9182 [22:28<26:16,  2.25it/s]
 61%|███████████████████████████████████████████████▉                              | 5638/9182 [22:28<23:05,  2.56it/s]
 61%|███████████████████████████████████████████████▉                              | 5639/9182 [22:29<33:01,  1.79it/s]
 61%|███████████████████████████████████████████████▉                              | 5640/9182 [22:30<26:19,  2.24it/s]
 61%|███████████████████████████████████████████████▉                              | 5641/9182 [22:30<28:03,  2.10it/s]
 61%|███████████████████████████████████████████████▉                              | 5642/9182 [22:30<25:52,  2.28it/s]
 61%|███████████████████████████████████████████████▉                              | 5643/9182 [22:30<22:06,  2.67it/s]
 61%|███████████████████████████████████████████████▉                              | 5644/9182 [22:31<17:54,  3.29it/s]
 61%|███████████████████████████████████████████████▉                              | 5645/9182 [22:31<21:23,  2.76it/s]
 61%|███████████████████████████████████████████████▉                              | 5646/9182 [22:31<21:40,  2.72it/s]
 62%|███████████████████████████████████████████████▉                              | 5647/9182 [22:32<19:21,  3.04it/s]
 62%|███████████████████████████████████████████████▉                              | 5648/9182 [22:32<22:40,  2.60it/s]
 62%|███████████████████████████████████████████████▉                              | 5649/9182 [22:33<22:45,  2.59it/s]
 62%|███████████████████████████████████████████████▉                              | 5650/9182 [22:33<23:11,  2.54it/s]
 62%|████████████████████████████████████████████████                              | 5652/9182 [22:33<15:30,  3.79it/s]
 62%|████████████████████████████████████████████████                              | 5655/9182 [22:33<09:37,  6.11it/s]
 62%|████████████████████████████████████████████████                              | 5658/9182 [22:34<08:01,  7.33it/s]
 62%|████████████████████████████████████████████████                              | 5662/9182 [22:34<05:49, 10.07it/s]
 62%|████████████████████████████████████████████████                              | 5664/9182 [22:34<05:59,  9.78it/s]
 62%|████████████████████████████████████████████████▏                             | 5666/9182 [22:35<09:36,  6.10it/s]
 62%|████████████████████████████████████████████████▏                             | 5667/9182 [22:35<09:46,  5.99it/s]
 62%|████████████████████████████████████████████████▏                             | 5668/9182 [22:35<09:19,  6.28it/s]
 62%|████████████████████████████████████████████████▏                             | 5669/9182 [22:35<10:05,  5.80it/s]
 62%|████████████████████████████████████████████████▏                             | 5670/9182 [22:36<11:26,  5.11it/s]
 62%|████████████████████████████████████████████████▏                             | 5671/9182 [22:36<11:37,  5.04it/s]
 62%|████████████████████████████████████████████████▏                             | 5672/9182 [22:36<13:52,  4.21it/s]
 62%|████████████████████████████████████████████████▏                             | 5673/9182 [22:37<14:04,  4.16it/s]
 62%|████████████████████████████████████████████████▏                             | 5674/9182 [22:37<16:01,  3.65it/s]
 62%|████████████████████████████████████████████████▏                             | 5675/9182 [22:38<34:14,  1.71it/s]
 62%|████████████████████████████████████████████████▎                             | 5683/9182 [22:38<09:33,  6.10it/s]
 62%|████████████████████████████████████████████████▎                             | 5685/9182 [22:38<08:13,  7.09it/s]
 62%|████████████████████████████████████████████████▎                             | 5687/9182 [22:39<08:43,  6.67it/s]
 62%|████████████████████████████████████████████████▎                             | 5689/9182 [22:40<13:36,  4.28it/s]
 62%|████████████████████████████████████████████████▎                             | 5690/9182 [22:40<13:20,  4.36it/s]
 62%|████████████████████████████████████████████████▎                             | 5691/9182 [22:41<16:35,  3.51it/s]
 62%|████████████████████████████████████████████████▎                             | 5692/9182 [22:41<21:51,  2.66it/s]
 62%|████████████████████████████████████████████████▍                             | 5698/9182 [22:41<08:39,  6.71it/s]

 62%|████████████████████████████████████████████████▍                             | 5700/9182 [22:42<12:59,  4.46it/s]
 62%|████████████████████████████████████████████████▍                             | 5702/9182 [22:42<10:54,  5.32it/s]
 62%|████████████████████████████████████████████████▍                             | 5704/9182 [22:44<15:42,  3.69it/s]
 62%|████████████████████████████████████████████████▍                             | 5705/9182 [22:44<15:29,  3.74it/s]
 62%|████████████████████████████████████████████████▍                             | 5706/9182 [22:44<15:07,  3.83it/s]
 62%|████████████████████████████████████████████████▍                             | 5707/9182 [22:44<14:39,  3.95it/s]
 62%|████████████████████████████████████████████████▍                             | 5708/9182 [22:44<13:43,  4.22it/s]
 62%|████████████████████████████████████████████████▌                             | 5710/9182 [22:45<09:30,  6.08it/s]
 62%|████████████████████████████████████████████████▌                             | 5711/9182 [22:45<13:37,  4.25it/s]
 62%|████████████████████████████████████████████████▌                             | 5712/9182 [22:46<14:37,  3.95it/s]
 62%|████████████████████████████████████████████████▌                             | 5713/9182 [22:46<16:46,  3.45it/s]
 62%|████████████████████████████████████████████████▌                             | 5714/9182 [22:46<21:08,  2.73it/s]
 62%|████████████████████████████████████████████████▌                             | 5715/9182 [22:47<23:18,  2.48it/s]
 62%|████████████████████████████████████████████████▌                             | 5716/9182 [22:48<37:55,  1.52it/s]
 62%|████████████████████████████████████████████████▌                             | 5717/9182 [22:48<29:24,  1.96it/s]
 62%|████████████████████████████████████████████████▌                             | 5718/9182 [22:49<30:16,  1.91it/s]
 62%|████████████████████████████████████████████████▌                             | 5719/9182 [22:49<24:28,  2.36it/s]
 62%|████████████████████████████████████████████████▌                             | 5720/9182 [22:49<20:52,  2.76it/s]
 62%|████████████████████████████████████████████████▌                             | 5721/9182 [22:50<17:18,  3.33it/s]
 62%|████████████████████████████████████████████████▌                             | 5722/9182 [22:50<19:53,  2.90it/s]
 62%|████████████████████████████████████████████████▌                             | 5723/9182 [22:50<18:53,  3.05it/s]
 62%|████████████████████████████████████████████████▌                             | 5724/9182 [22:51<17:30,  3.29it/s]
 62%|████████████████████████████████████████████████▋                             | 5725/9182 [22:51<16:50,  3.42it/s]
 62%|████████████████████████████████████████████████▋                             | 5726/9182 [22:51<17:05,  3.37it/s]
 62%|████████████████████████████████████████████████▋                             | 5727/9182 [22:51<15:31,  3.71it/s]
 62%|████████████████████████████████████████████████▋                             | 5728/9182 [22:51<13:05,  4.40it/s]
 62%|████████████████████████████████████████████████▋                             | 5729/9182 [22:52<13:27,  4.27it/s]
 62%|████████████████████████████████████████████████▋                             | 5730/9182 [22:52<13:25,  4.29it/s]
 62%|████████████████████████████████████████████████▋                             | 5731/9182 [22:52<11:54,  4.83it/s]
 62%|████████████████████████████████████████████████▋                             | 5732/9182 [22:52<12:11,  4.72it/s]
 62%|████████████████████████████████████████████████▋                             | 5733/9182 [22:52<12:51,  4.47it/s]
 62%|████████████████████████████████████████████████▋                             | 5734/9182 [22:53<12:22,  4.65it/s]
 62%|████████████████████████████████████████████████▋                             | 5735/9182 [22:53<12:19,  4.66it/s]
 62%|████████████████████████████████████████████████▋                             | 5736/9182 [22:53<12:57,  4.43it/s]
 62%|████████████████████████████████████████████████▋                             | 5737/9182 [22:53<12:21,  4.65it/s]
 62%|████████████████████████████████████████████████▋                             | 5738/9182 [22:53<12:23,  4.63it/s]
 63%|████████████████████████████████████████████████▊                             | 5739/9182 [22:54<11:54,  4.82it/s]
 63%|████████████████████████████████████████████████▊                             | 5743/9182 [22:54<05:44, 10.00it/s]
 63%|████████████████████████████████████████████████▊                             | 5745/9182 [22:55<11:26,  5.01it/s]
 63%|████████████████████████████████████████████████▊                             | 5747/9182 [22:55<14:33,  3.93it/s]
 63%|████████████████████████████████████████████████▊                             | 5748/9182 [22:55<13:13,  4.33it/s]
 63%|████████████████████████████████████████████████▊                             | 5752/9182 [22:56<10:10,  5.62it/s]
 63%|████████████████████████████████████████████████▊                             | 5753/9182 [22:56<11:15,  5.07it/s]
 63%|████████████████████████████████████████████████▉                             | 5754/9182 [22:57<13:42,  4.17it/s]
 63%|████████████████████████████████████████████████▉                             | 5755/9182 [22:57<15:36,  3.66it/s]
 63%|████████████████████████████████████████████████▉                             | 5756/9182 [22:58<19:43,  2.89it/s]
 63%|████████████████████████████████████████████████▉                             | 5757/9182 [22:58<17:03,  3.35it/s]
 63%|████████████████████████████████████████████████▉                             | 5758/9182 [22:58<17:22,  3.29it/s]
 63%|████████████████████████████████████████████████▉                             | 5759/9182 [22:58<14:22,  3.97it/s]
 63%|████████████████████████████████████████████████▉                             | 5760/9182 [22:59<14:18,  3.98it/s]
 63%|████████████████████████████████████████████████▉                             | 5761/9182 [22:59<14:16,  3.99it/s]
 63%|████████████████████████████████████████████████▉                             | 5762/9182 [22:59<15:19,  3.72it/s]
 63%|████████████████████████████████████████████████▉                             | 5763/9182 [22:59<12:53,  4.42it/s]
 63%|████████████████████████████████████████████████▉                             | 5764/9182 [22:59<10:53,  5.23it/s]
 63%|████████████████████████████████████████████████▉                             | 5765/9182 [23:00<12:14,  4.65it/s]
 63%|████████████████████████████████████████████████▉                             | 5767/9182 [23:00<11:09,  5.10it/s]
 63%|████████████████████████████████████████████████▉                             | 5768/9182 [23:00<11:53,  4.79it/s]
 63%|█████████████████████████████████████████████████                             | 5769/9182 [23:00<11:36,  4.90it/s]
 63%|█████████████████████████████████████████████████                             | 5770/9182 [23:01<10:24,  5.46it/s]
 63%|█████████████████████████████████████████████████                             | 5775/9182 [23:01<08:19,  6.82it/s]
 63%|█████████████████████████████████████████████████                             | 5776/9182 [23:02<12:49,  4.43it/s]
 63%|█████████████████████████████████████████████████                             | 5777/9182 [23:02<13:23,  4.24it/s]
 63%|█████████████████████████████████████████████████                             | 5778/9182 [23:03<16:10,  3.51it/s]
 63%|█████████████████████████████████████████████████                             | 5781/9182 [23:03<11:32,  4.91it/s]
 63%|█████████████████████████████████████████████████                             | 5782/9182 [23:03<12:27,  4.55it/s]
 63%|█████████████████████████████████████████████████▏                            | 5783/9182 [23:03<13:01,  4.35it/s]
 63%|█████████████████████████████████████████████████▏                            | 5784/9182 [23:04<15:30,  3.65it/s]
 63%|█████████████████████████████████████████████████▏                            | 5785/9182 [23:04<14:08,  4.00it/s]
 63%|█████████████████████████████████████████████████▏                            | 5786/9182 [23:04<12:31,  4.52it/s]
 63%|█████████████████████████████████████████████████▏                            | 5787/9182 [23:05<13:57,  4.06it/s]
 63%|█████████████████████████████████████████████████▏                            | 5788/9182 [23:05<11:41,  4.84it/s]
 63%|█████████████████████████████████████████████████▏                            | 5790/9182 [23:05<08:23,  6.74it/s]
 63%|█████████████████████████████████████████████████▏                            | 5791/9182 [23:05<09:49,  5.75it/s]
 63%|█████████████████████████████████████████████████▏                            | 5792/9182 [23:05<09:55,  5.70it/s]
 63%|█████████████████████████████████████████████████▏                            | 5793/9182 [23:05<10:58,  5.15it/s]
 63%|█████████████████████████████████████████████████▏                            | 5797/9182 [23:06<05:14, 10.76it/s]
 63%|█████████████████████████████████████████████████▎                            | 5799/9182 [23:06<06:59,  8.06it/s]
 63%|█████████████████████████████████████████████████▎                            | 5801/9182 [23:07<10:25,  5.41it/s]
 63%|█████████████████████████████████████████████████▎                            | 5802/9182 [23:07<16:35,  3.40it/s]
 63%|█████████████████████████████████████████████████▎                            | 5803/9182 [23:08<15:01,  3.75it/s]
 63%|█████████████████████████████████████████████████▎                            | 5804/9182 [23:08<17:42,  3.18it/s]
 63%|█████████████████████████████████████████████████▎                            | 5805/9182 [23:08<15:12,  3.70it/s]
 63%|█████████████████████████████████████████████████▎                            | 5807/9182 [23:09<14:45,  3.81it/s]
 63%|█████████████████████████████████████████████████▎                            | 5810/9182 [23:09<13:40,  4.11it/s]
 63%|█████████████████████████████████████████████████▎                            | 5811/9182 [23:09<12:37,  4.45it/s]
 63%|█████████████████████████████████████████████████▍                            | 5813/9182 [23:10<12:01,  4.67it/s]
 63%|█████████████████████████████████████████████████▍                            | 5815/9182 [23:10<09:40,  5.80it/s]
 63%|█████████████████████████████████████████████████▍                            | 5816/9182 [23:10<09:05,  6.17it/s]
 63%|█████████████████████████████████████████████████▍                            | 5817/9182 [23:10<09:12,  6.09it/s]
 63%|█████████████████████████████████████████████████▍                            | 5819/9182 [23:10<07:38,  7.34it/s]
 63%|█████████████████████████████████████████████████▍                            | 5820/9182 [23:11<08:10,  6.85it/s]
 63%|█████████████████████████████████████████████████▍                            | 5821/9182 [23:11<07:47,  7.19it/s]
 63%|█████████████████████████████████████████████████▍                            | 5822/9182 [23:11<08:58,  6.24it/s]
 63%|█████████████████████████████████████████████████▍                            | 5823/9182 [23:11<08:40,  6.46it/s]
 63%|█████████████████████████████████████████████████▍                            | 5826/9182 [23:11<07:07,  7.86it/s]
 63%|█████████████████████████████████████████████████▍                            | 5827/9182 [23:12<10:23,  5.38it/s]
 63%|█████████████████████████████████████████████████▌                            | 5828/9182 [23:12<10:30,  5.32it/s]
 63%|█████████████████████████████████████████████████▌                            | 5829/9182 [23:12<10:50,  5.16it/s]
 63%|█████████████████████████████████████████████████▌                            | 5830/9182 [23:13<10:57,  5.10it/s]
 64%|█████████████████████████████████████████████████▌                            | 5831/9182 [23:13<09:44,  5.74it/s]
 64%|█████████████████████████████████████████████████▌                            | 5832/9182 [23:13<12:15,  4.55it/s]
 64%|█████████████████████████████████████████████████▌                            | 5834/9182 [23:13<08:21,  6.68it/s]
 64%|█████████████████████████████████████████████████▌                            | 5838/9182 [23:13<05:05, 10.94it/s]
 64%|█████████████████████████████████████████████████▌                            | 5840/9182 [23:14<07:14,  7.68it/s]
 64%|█████████████████████████████████████████████████▋                            | 5842/9182 [23:14<07:16,  7.65it/s]
 64%|█████████████████████████████████████████████████▋                            | 5843/9182 [23:14<07:12,  7.72it/s]
 64%|█████████████████████████████████████████████████▋                            | 5844/9182 [23:14<07:14,  7.69it/s]
 64%|█████████████████████████████████████████████████▋                            | 5845/9182 [23:15<09:03,  6.14it/s]
 64%|█████████████████████████████████████████████████▋                            | 5846/9182 [23:15<10:18,  5.39it/s]
 64%|█████████████████████████████████████████████████▋                            | 5847/9182 [23:15<12:12,  4.55it/s]
 64%|█████████████████████████████████████████████████▋                            | 5848/9182 [23:15<11:18,  4.91it/s]
 64%|█████████████████████████████████████████████████▋                            | 5850/9182 [23:15<08:42,  6.37it/s]
 64%|█████████████████████████████████████████████████▋                            | 5851/9182 [23:16<09:37,  5.77it/s]
 64%|█████████████████████████████████████████████████▋                            | 5852/9182 [23:16<10:00,  5.55it/s]
 64%|█████████████████████████████████████████████████▋                            | 5853/9182 [23:16<09:29,  5.85it/s]
 64%|█████████████████████████████████████████████████▋                            | 5855/9182 [23:16<07:10,  7.73it/s]
 64%|█████████████████████████████████████████████████▊                            | 5858/9182 [23:16<05:06, 10.85it/s]
 64%|█████████████████████████████████████████████████▊                            | 5860/9182 [23:17<10:34,  5.23it/s]
 64%|█████████████████████████████████████████████████▊                            | 5861/9182 [23:17<12:08,  4.56it/s]
 64%|█████████████████████████████████████████████████▊                            | 5862/9182 [23:18<10:51,  5.09it/s]
 64%|█████████████████████████████████████████████████▊                            | 5863/9182 [23:19<27:58,  1.98it/s]
 64%|█████████████████████████████████████████████████▊                            | 5864/9182 [23:19<22:46,  2.43it/s]
 64%|█████████████████████████████████████████████████▊                            | 5868/9182 [23:20<14:27,  3.82it/s]
 64%|█████████████████████████████████████████████████▊                            | 5869/9182 [23:21<17:47,  3.10it/s]
 64%|█████████████████████████████████████████████████▊                            | 5870/9182 [23:21<17:24,  3.17it/s]
 64%|█████████████████████████████████████████████████▊                            | 5871/9182 [23:21<20:35,  2.68it/s]
 64%|█████████████████████████████████████████████████▉                            | 5874/9182 [23:21<11:59,  4.60it/s]
 64%|█████████████████████████████████████████████████▉                            | 5875/9182 [23:22<13:36,  4.05it/s]
 64%|█████████████████████████████████████████████████▉                            | 5876/9182 [23:22<12:56,  4.26it/s]
 64%|█████████████████████████████████████████████████▉                            | 5877/9182 [23:23<15:36,  3.53it/s]
 64%|█████████████████████████████████████████████████▉                            | 5878/9182 [23:23<16:07,  3.41it/s]
 64%|█████████████████████████████████████████████████▉                            | 5879/9182 [23:24<23:33,  2.34it/s]

 64%|█████████████████████████████████████████████████▉                            | 5880/9182 [23:24<19:27,  2.83it/s]
 64%|█████████████████████████████████████████████████▉                            | 5881/9182 [23:24<17:51,  3.08it/s]
 64%|█████████████████████████████████████████████████▉                            | 5882/9182 [23:24<14:47,  3.72it/s]
 64%|█████████████████████████████████████████████████▉                            | 5883/9182 [23:25<18:45,  2.93it/s]
 64%|█████████████████████████████████████████████████▉                            | 5884/9182 [23:25<22:08,  2.48it/s]
 64%|██████████████████████████████████████████████████                            | 5887/9182 [23:25<10:54,  5.04it/s]
 64%|██████████████████████████████████████████████████                            | 5889/9182 [23:26<10:58,  5.00it/s]
 64%|██████████████████████████████████████████████████                            | 5891/9182 [23:26<12:53,  4.26it/s]
 64%|██████████████████████████████████████████████████                            | 5892/9182 [23:27<13:05,  4.19it/s]
 64%|██████████████████████████████████████████████████                            | 5893/9182 [23:27<14:57,  3.66it/s]
 64%|██████████████████████████████████████████████████                            | 5894/9182 [23:27<15:40,  3.49it/s]
 64%|██████████████████████████████████████████████████                            | 5895/9182 [23:28<19:41,  2.78it/s]
 64%|██████████████████████████████████████████████████                            | 5896/9182 [23:28<16:03,  3.41it/s]
 64%|██████████████████████████████████████████████████                            | 5897/9182 [23:28<14:57,  3.66it/s]
 64%|██████████████████████████████████████████████████                            | 5898/9182 [23:29<14:23,  3.81it/s]
 64%|██████████████████████████████████████████████████                            | 5899/9182 [23:29<12:31,  4.37it/s]
 64%|██████████████████████████████████████████████████                            | 5900/9182 [23:29<10:31,  5.19it/s]
 64%|██████████████████████████████████████████████████▏                           | 5901/9182 [23:29<13:36,  4.02it/s]
 64%|██████████████████████████████████████████████████▏                           | 5902/9182 [23:30<16:16,  3.36it/s]
 64%|██████████████████████████████████████████████████▏                           | 5903/9182 [23:30<23:18,  2.34it/s]
 64%|██████████████████████████████████████████████████▏                           | 5907/9182 [23:30<09:53,  5.52it/s]
 64%|██████████████████████████████████████████████████▏                           | 5909/9182 [23:31<09:32,  5.72it/s]
 64%|██████████████████████████████████████████████████▏                           | 5910/9182 [23:31<09:45,  5.59it/s]
 64%|██████████████████████████████████████████████████▏                           | 5911/9182 [23:31<08:56,  6.10it/s]
 64%|██████████████████████████████████████████████████▏                           | 5912/9182 [23:31<09:08,  5.96it/s]
 64%|██████████████████████████████████████████████████▏                           | 5914/9182 [23:31<07:21,  7.41it/s]
 64%|██████████████████████████████████████████████████▏                           | 5915/9182 [23:32<07:16,  7.49it/s]
 64%|██████████████████████████████████████████████████▎                           | 5918/9182 [23:32<06:12,  8.75it/s]
 64%|██████████████████████████████████████████████████▎                           | 5919/9182 [23:32<09:04,  5.99it/s]
 64%|██████████████████████████████████████████████████▎                           | 5920/9182 [23:33<15:32,  3.50it/s]
 64%|██████████████████████████████████████████████████▎                           | 5921/9182 [23:34<24:32,  2.22it/s]
 64%|██████████████████████████████████████████████████▎                           | 5922/9182 [23:35<25:32,  2.13it/s]
 65%|██████████████████████████████████████████████████▎                           | 5923/9182 [23:35<23:12,  2.34it/s]
 65%|██████████████████████████████████████████████████▎                           | 5924/9182 [23:35<20:24,  2.66it/s]
 65%|██████████████████████████████████████████████████▎                           | 5925/9182 [23:36<20:13,  2.68it/s]
 65%|██████████████████████████████████████████████████▎                           | 5926/9182 [23:36<22:22,  2.43it/s]
 65%|██████████████████████████████████████████████████▎                           | 5927/9182 [23:37<25:57,  2.09it/s]
 65%|██████████████████████████████████████████████████▎                           | 5928/9182 [23:37<25:14,  2.15it/s]
 65%|██████████████████████████████████████████████████▍                           | 5931/9182 [23:37<15:18,  3.54it/s]
 65%|██████████████████████████████████████████████████▍                           | 5932/9182 [23:38<16:08,  3.35it/s]
 65%|██████████████████████████████████████████████████▍                           | 5933/9182 [23:38<17:09,  3.15it/s]
 65%|██████████████████████████████████████████████████▍                           | 5934/9182 [23:39<20:08,  2.69it/s]
 65%|██████████████████████████████████████████████████▍                           | 5935/9182 [23:39<18:02,  3.00it/s]
 65%|██████████████████████████████████████████████████▍                           | 5936/9182 [23:39<19:10,  2.82it/s]
 65%|██████████████████████████████████████████████████▍                           | 5937/9182 [23:40<21:27,  2.52it/s]
 65%|██████████████████████████████████████████████████▍                           | 5938/9182 [23:41<29:34,  1.83it/s]
 65%|██████████████████████████████████████████████████▍                           | 5939/9182 [23:41<28:55,  1.87it/s]
 65%|██████████████████████████████████████████████████▍                           | 5940/9182 [23:42<26:27,  2.04it/s]
 65%|██████████████████████████████████████████████████▍                           | 5941/9182 [23:42<26:48,  2.01it/s]
 65%|██████████████████████████████████████████████████▍                           | 5942/9182 [23:43<25:08,  2.15it/s]
 65%|██████████████████████████████████████████████████▍                           | 5943/9182 [23:43<24:35,  2.20it/s]
 65%|██████████████████████████████████████████████████▍                           | 5944/9182 [23:43<23:04,  2.34it/s]
 65%|██████████████████████████████████████████████████▌                           | 5945/9182 [23:44<27:41,  1.95it/s]
 65%|██████████████████████████████████████████████████▌                           | 5946/9182 [23:45<28:47,  1.87it/s]
 65%|██████████████████████████████████████████████████▌                           | 5947/9182 [23:45<25:32,  2.11it/s]
 65%|██████████████████████████████████████████████████▌                           | 5948/9182 [23:46<26:22,  2.04it/s]
 65%|██████████████████████████████████████████████████▌                           | 5949/9182 [23:46<31:53,  1.69it/s]
 65%|██████████████████████████████████████████████████▌                           | 5950/9182 [23:47<27:32,  1.96it/s]
 65%|██████████████████████████████████████████████████▌                           | 5951/9182 [23:47<28:52,  1.86it/s]
 65%|██████████████████████████████████████████████████▌                           | 5952/9182 [23:49<39:41,  1.36it/s]
 65%|██████████████████████████████████████████████████▌                           | 5953/9182 [23:49<35:19,  1.52it/s]
 65%|██████████████████████████████████████████████████▌                           | 5955/9182 [23:50<35:57,  1.50it/s]
 65%|██████████████████████████████████████████████████▌                           | 5959/9182 [23:51<20:55,  2.57it/s]
 65%|██████████████████████████████████████████████████▋                           | 5962/9182 [23:51<14:03,  3.82it/s]
 65%|██████████████████████████████████████████████████▋                           | 5963/9182 [23:51<12:47,  4.20it/s]
 65%|██████████████████████████████████████████████████▋                           | 5966/9182 [23:52<11:03,  4.85it/s]
 65%|██████████████████████████████████████████████████▋                           | 5967/9182 [23:52<10:36,  5.05it/s]
 65%|██████████████████████████████████████████████████▋                           | 5968/9182 [23:52<10:41,  5.01it/s]
 65%|██████████████████████████████████████████████████▋                           | 5969/9182 [23:53<15:47,  3.39it/s]
 65%|██████████████████████████████████████████████████▋                           | 5970/9182 [23:53<16:07,  3.32it/s]
 65%|██████████████████████████████████████████████████▋                           | 5971/9182 [23:54<17:24,  3.07it/s]
 65%|██████████████████████████████████████████████████▋                           | 5972/9182 [23:54<17:57,  2.98it/s]
 65%|██████████████████████████████████████████████████▋                           | 5973/9182 [23:54<16:34,  3.23it/s]
 65%|██████████████████████████████████████████████████▋                           | 5974/9182 [23:54<15:52,  3.37it/s]
 65%|██████████████████████████████████████████████████▊                           | 5975/9182 [23:55<15:56,  3.35it/s]
 65%|██████████████████████████████████████████████████▊                           | 5976/9182 [23:55<18:45,  2.85it/s]
 65%|██████████████████████████████████████████████████▊                           | 5977/9182 [23:56<18:10,  2.94it/s]
 65%|██████████████████████████████████████████████████▊                           | 5978/9182 [23:56<20:19,  2.63it/s]
 65%|██████████████████████████████████████████████████▊                           | 5979/9182 [23:56<19:59,  2.67it/s]
 65%|██████████████████████████████████████████████████▊                           | 5980/9182 [23:56<16:44,  3.19it/s]
 65%|██████████████████████████████████████████████████▊                           | 5981/9182 [23:57<17:00,  3.14it/s]
 65%|██████████████████████████████████████████████████▊                           | 5982/9182 [23:57<15:06,  3.53it/s]
 65%|██████████████████████████████████████████████████▊                           | 5983/9182 [23:58<19:27,  2.74it/s]
 65%|██████████████████████████████████████████████████▊                           | 5984/9182 [23:58<18:54,  2.82it/s]
 65%|██████████████████████████████████████████████████▊                           | 5985/9182 [23:58<21:39,  2.46it/s]
 65%|██████████████████████████████████████████████████▉                           | 5989/9182 [23:59<11:36,  4.58it/s]
 65%|██████████████████████████████████████████████████▉                           | 5990/9182 [23:59<11:49,  4.50it/s]
 65%|██████████████████████████████████████████████████▉                           | 5991/9182 [24:00<14:06,  3.77it/s]
 65%|██████████████████████████████████████████████████▉                           | 5992/9182 [24:00<14:34,  3.65it/s]
 65%|██████████████████████████████████████████████████▉                           | 5993/9182 [24:01<20:20,  2.61it/s]
 65%|██████████████████████████████████████████████████▉                           | 5994/9182 [24:01<21:40,  2.45it/s]
 65%|██████████████████████████████████████████████████▉                           | 5995/9182 [24:01<19:21,  2.74it/s]
 65%|██████████████████████████████████████████████████▉                           | 5996/9182 [24:02<17:32,  3.03it/s]
 65%|██████████████████████████████████████████████████▉                           | 5997/9182 [24:02<20:19,  2.61it/s]
 65%|██████████████████████████████████████████████████▉                           | 5998/9182 [24:02<18:47,  2.82it/s]
 65%|██████████████████████████████████████████████████▉                           | 5999/9182 [24:03<17:32,  3.03it/s]
 65%|██████████████████████████████████████████████████▉                           | 6000/9182 [24:03<14:27,  3.67it/s]
 65%|██████████████████████████████████████████████████▉                           | 6001/9182 [24:03<15:59,  3.31it/s]
 65%|██████████████████████████████████████████████████▉                           | 6002/9182 [24:03<14:39,  3.62it/s]
 65%|██████████████████████████████████████████████████▉                           | 6003/9182 [24:04<17:16,  3.07it/s]
 65%|███████████████████████████████████████████████████                           | 6004/9182 [24:04<16:38,  3.18it/s]
 65%|███████████████████████████████████████████████████                           | 6005/9182 [24:05<25:43,  2.06it/s]
 65%|███████████████████████████████████████████████████                           | 6006/9182 [24:05<24:01,  2.20it/s]
 65%|███████████████████████████████████████████████████                           | 6007/9182 [24:05<19:36,  2.70it/s]
 65%|███████████████████████████████████████████████████                           | 6008/9182 [24:06<17:28,  3.03it/s]
 65%|███████████████████████████████████████████████████                           | 6009/9182 [24:06<16:03,  3.29it/s]
 65%|███████████████████████████████████████████████████                           | 6010/9182 [24:06<14:23,  3.67it/s]
 65%|███████████████████████████████████████████████████                           | 6012/9182 [24:06<10:57,  4.82it/s]
 65%|███████████████████████████████████████████████████                           | 6013/9182 [24:07<10:23,  5.08it/s]
 65%|███████████████████████████████████████████████████                           | 6014/9182 [24:07<12:54,  4.09it/s]
 66%|███████████████████████████████████████████████████                           | 6015/9182 [24:07<12:14,  4.31it/s]
 66%|███████████████████████████████████████████████████                           | 6016/9182 [24:07<12:24,  4.25it/s]
 66%|███████████████████████████████████████████████████                           | 6017/9182 [24:08<12:11,  4.33it/s]
 66%|███████████████████████████████████████████████████                           | 6018/9182 [24:08<12:03,  4.37it/s]
 66%|███████████████████████████████████████████████████▏                          | 6022/9182 [24:08<05:24,  9.73it/s]
 66%|███████████████████████████████████████████████████▏                          | 6024/9182 [24:08<07:19,  7.19it/s]
 66%|███████████████████████████████████████████████████▏                          | 6026/9182 [24:10<18:25,  2.85it/s]
 66%|███████████████████████████████████████████████████▏                          | 6027/9182 [24:10<17:08,  3.07it/s]
 66%|███████████████████████████████████████████████████▏                          | 6028/9182 [24:10<16:02,  3.28it/s]
 66%|███████████████████████████████████████████████████▏                          | 6029/9182 [24:11<14:51,  3.54it/s]
 66%|███████████████████████████████████████████████████▏                          | 6030/9182 [24:12<22:37,  2.32it/s]
 66%|███████████████████████████████████████████████████▏                          | 6031/9182 [24:12<20:47,  2.53it/s]
 66%|███████████████████████████████████████████████████▏                          | 6032/9182 [24:13<26:50,  1.96it/s]
 66%|███████████████████████████████████████████████████▏                          | 6033/9182 [24:13<23:00,  2.28it/s]
 66%|███████████████████████████████████████████████████▎                          | 6034/9182 [24:13<21:21,  2.46it/s]
 66%|███████████████████████████████████████████████████▎                          | 6035/9182 [24:14<21:20,  2.46it/s]
 66%|███████████████████████████████████████████████████▎                          | 6038/9182 [24:14<13:01,  4.02it/s]
 66%|███████████████████████████████████████████████████▎                          | 6039/9182 [24:15<16:15,  3.22it/s]
 66%|███████████████████████████████████████████████████▎                          | 6040/9182 [24:15<20:07,  2.60it/s]
 66%|███████████████████████████████████████████████████▎                          | 6041/9182 [24:16<19:59,  2.62it/s]
 66%|███████████████████████████████████████████████████▎                          | 6042/9182 [24:17<28:03,  1.86it/s]
 66%|███████████████████████████████████████████████████▎                          | 6044/9182 [24:17<19:32,  2.68it/s]

 66%|███████████████████████████████████████████████████▎                          | 6045/9182 [24:17<20:06,  2.60it/s]
 66%|███████████████████████████████████████████████████▎                          | 6046/9182 [24:18<22:40,  2.30it/s]
 66%|███████████████████████████████████████████████████▎                          | 6047/9182 [24:20<35:05,  1.49it/s]
 66%|███████████████████████████████████████████████████▍                          | 6048/9182 [24:20<38:27,  1.36it/s]
 66%|███████████████████████████████████████████████████▍                          | 6049/9182 [24:20<30:00,  1.74it/s]
 66%|███████████████████████████████████████████████████▍                          | 6050/9182 [24:21<23:53,  2.19it/s]
 66%|███████████████████████████████████████████████████▍                          | 6051/9182 [24:21<22:34,  2.31it/s]
 66%|███████████████████████████████████████████████████▍                          | 6052/9182 [24:21<22:50,  2.28it/s]
 66%|███████████████████████████████████████████████████▍                          | 6053/9182 [24:21<17:55,  2.91it/s]
 66%|███████████████████████████████████████████████████▍                          | 6054/9182 [24:22<20:42,  2.52it/s]
 66%|███████████████████████████████████████████████████▍                          | 6055/9182 [24:22<16:48,  3.10it/s]
 66%|███████████████████████████████████████████████████▍                          | 6056/9182 [24:22<14:59,  3.47it/s]
 66%|███████████████████████████████████████████████████▍                          | 6057/9182 [24:23<14:16,  3.65it/s]
 66%|███████████████████████████████████████████████████▍                          | 6058/9182 [24:23<14:05,  3.70it/s]
 66%|███████████████████████████████████████████████████▍                          | 6059/9182 [24:23<11:57,  4.35it/s]
 66%|███████████████████████████████████████████████████▍                          | 6060/9182 [24:23<10:51,  4.79it/s]
 66%|███████████████████████████████████████████████████▍                          | 6061/9182 [24:23<13:37,  3.82it/s]
 66%|███████████████████████████████████████████████████▍                          | 6062/9182 [24:24<11:41,  4.44it/s]
 66%|███████████████████████████████████████████████████▌                          | 6063/9182 [24:24<13:59,  3.72it/s]
 66%|███████████████████████████████████████████████████▌                          | 6064/9182 [24:24<13:23,  3.88it/s]
 66%|███████████████████████████████████████████████████▌                          | 6065/9182 [24:24<12:02,  4.32it/s]
 66%|███████████████████████████████████████████████████▌                          | 6066/9182 [24:24<10:31,  4.93it/s]
 66%|███████████████████████████████████████████████████▌                          | 6067/9182 [24:25<09:34,  5.42it/s]
 66%|███████████████████████████████████████████████████▌                          | 6068/9182 [24:25<08:52,  5.85it/s]
 66%|███████████████████████████████████████████████████▌                          | 6069/9182 [24:25<07:53,  6.57it/s]
 66%|███████████████████████████████████████████████████▌                          | 6072/9182 [24:25<04:29, 11.53it/s]
 66%|███████████████████████████████████████████████████▌                          | 6074/9182 [24:25<04:56, 10.47it/s]
 66%|███████████████████████████████████████████████████▌                          | 6076/9182 [24:25<05:16,  9.80it/s]
 66%|███████████████████████████████████████████████████▋                          | 6078/9182 [24:26<06:08,  8.42it/s]
 66%|███████████████████████████████████████████████████▋                          | 6080/9182 [24:26<07:37,  6.78it/s]
 66%|███████████████████████████████████████████████████▋                          | 6081/9182 [24:26<08:25,  6.13it/s]
 66%|███████████████████████████████████████████████████▋                          | 6082/9182 [24:27<09:24,  5.49it/s]
 66%|███████████████████████████████████████████████████▋                          | 6083/9182 [24:27<09:41,  5.33it/s]
 66%|███████████████████████████████████████████████████▋                          | 6084/9182 [24:27<09:24,  5.48it/s]
 66%|███████████████████████████████████████████████████▋                          | 6085/9182 [24:28<10:10,  5.07it/s]
 66%|███████████████████████████████████████████████████▋                          | 6086/9182 [24:28<17:03,  3.02it/s]
 66%|███████████████████████████████████████████████████▋                          | 6087/9182 [24:29<25:16,  2.04it/s]
 66%|███████████████████████████████████████████████████▋                          | 6088/9182 [24:29<20:44,  2.49it/s]
 66%|███████████████████████████████████████████████████▋                          | 6089/9182 [24:30<22:39,  2.27it/s]
 66%|███████████████████████████████████████████████████▋                          | 6090/9182 [24:30<17:55,  2.88it/s]
 66%|███████████████████████████████████████████████████▋                          | 6091/9182 [24:30<16:52,  3.05it/s]
 66%|███████████████████████████████████████████████████▊                          | 6092/9182 [24:30<13:35,  3.79it/s]
 66%|███████████████████████████████████████████████████▊                          | 6093/9182 [24:30<11:45,  4.38it/s]
 66%|███████████████████████████████████████████████████▊                          | 6096/9182 [24:30<06:21,  8.09it/s]
 66%|███████████████████████████████████████████████████▊                          | 6098/9182 [24:31<06:53,  7.46it/s]
 66%|███████████████████████████████████████████████████▊                          | 6100/9182 [24:31<10:46,  4.77it/s]
 66%|███████████████████████████████████████████████████▊                          | 6101/9182 [24:32<12:02,  4.26it/s]
 66%|███████████████████████████████████████████████████▊                          | 6102/9182 [24:33<18:15,  2.81it/s]
 66%|███████████████████████████████████████████████████▊                          | 6103/9182 [24:33<16:21,  3.14it/s]
 66%|███████████████████████████████████████████████████▊                          | 6105/9182 [24:33<12:37,  4.06it/s]
 67%|███████████████████████████████████████████████████▉                          | 6107/9182 [24:33<10:52,  4.71it/s]
 67%|███████████████████████████████████████████████████▉                          | 6108/9182 [24:33<09:54,  5.17it/s]
 67%|███████████████████████████████████████████████████▉                          | 6110/9182 [24:34<12:58,  3.95it/s]
 67%|███████████████████████████████████████████████████▉                          | 6112/9182 [24:34<10:47,  4.74it/s]
 67%|███████████████████████████████████████████████████▉                          | 6114/9182 [24:35<11:21,  4.50it/s]
 67%|███████████████████████████████████████████████████▉                          | 6115/9182 [24:35<11:51,  4.31it/s]
 67%|███████████████████████████████████████████████████▉                          | 6116/9182 [24:35<10:50,  4.71it/s]
 67%|███████████████████████████████████████████████████▉                          | 6117/9182 [24:36<11:34,  4.41it/s]
 67%|███████████████████████████████████████████████████▉                          | 6118/9182 [24:36<12:35,  4.06it/s]
 67%|███████████████████████████████████████████████████▉                          | 6119/9182 [24:36<12:27,  4.10it/s]
 67%|████████████████████████████████████████████████████                          | 6123/9182 [24:37<07:19,  6.96it/s]
 67%|████████████████████████████████████████████████████                          | 6124/9182 [24:37<08:47,  5.80it/s]
 67%|████████████████████████████████████████████████████                          | 6125/9182 [24:37<14:34,  3.50it/s]
 67%|████████████████████████████████████████████████████                          | 6126/9182 [24:38<13:32,  3.76it/s]
 67%|████████████████████████████████████████████████████                          | 6127/9182 [24:38<16:59,  3.00it/s]
 67%|████████████████████████████████████████████████████                          | 6129/9182 [24:38<12:53,  3.95it/s]
 67%|████████████████████████████████████████████████████                          | 6130/9182 [24:39<14:45,  3.45it/s]
 67%|████████████████████████████████████████████████████                          | 6131/9182 [24:39<14:35,  3.49it/s]
 67%|████████████████████████████████████████████████████                          | 6132/9182 [24:40<13:27,  3.78it/s]
 67%|████████████████████████████████████████████████████                          | 6133/9182 [24:40<15:15,  3.33it/s]
 67%|████████████████████████████████████████████████████                          | 6134/9182 [24:40<15:49,  3.21it/s]
 67%|████████████████████████████████████████████████████                          | 6135/9182 [24:40<15:15,  3.33it/s]
 67%|████████████████████████████████████████████████████                          | 6136/9182 [24:41<15:34,  3.26it/s]
 67%|████████████████████████████████████████████████████▏                         | 6137/9182 [24:41<14:42,  3.45it/s]
 67%|████████████████████████████████████████████████████▏                         | 6138/9182 [24:41<14:57,  3.39it/s]
 67%|████████████████████████████████████████████████████▏                         | 6139/9182 [24:42<17:50,  2.84it/s]
 67%|████████████████████████████████████████████████████▏                         | 6140/9182 [24:42<16:15,  3.12it/s]
 67%|████████████████████████████████████████████████████▏                         | 6141/9182 [24:42<15:08,  3.35it/s]
 67%|████████████████████████████████████████████████████▏                         | 6142/9182 [24:42<12:29,  4.05it/s]
 67%|████████████████████████████████████████████████████▏                         | 6143/9182 [24:43<12:03,  4.20it/s]
 67%|████████████████████████████████████████████████████▏                         | 6148/9182 [24:43<05:24,  9.35it/s]
 67%|████████████████████████████████████████████████████▏                         | 6149/9182 [24:44<16:19,  3.10it/s]
 67%|████████████████████████████████████████████████████▏                         | 6150/9182 [24:45<16:48,  3.01it/s]
 67%|████████████████████████████████████████████████████▎                         | 6154/9182 [24:45<10:09,  4.97it/s]
 67%|████████████████████████████████████████████████████▎                         | 6157/9182 [24:46<13:51,  3.64it/s]
 67%|████████████████████████████████████████████████████▎                         | 6158/9182 [24:46<13:10,  3.82it/s]
 67%|████████████████████████████████████████████████████▎                         | 6164/9182 [24:47<06:55,  7.27it/s]
 67%|████████████████████████████████████████████████████▍                         | 6166/9182 [24:48<14:08,  3.55it/s]
 67%|████████████████████████████████████████████████████▍                         | 6168/9182 [24:48<12:39,  3.97it/s]
 67%|████████████████████████████████████████████████████▍                         | 6169/9182 [24:49<12:56,  3.88it/s]
 67%|████████████████████████████████████████████████████▍                         | 6170/9182 [24:49<14:18,  3.51it/s]
 67%|████████████████████████████████████████████████████▍                         | 6171/9182 [24:50<15:10,  3.31it/s]
 67%|████████████████████████████████████████████████████▍                         | 6172/9182 [24:50<14:32,  3.45it/s]
 67%|████████████████████████████████████████████████████▍                         | 6173/9182 [24:50<12:33,  4.00it/s]
 67%|████████████████████████████████████████████████████▍                         | 6174/9182 [24:50<12:25,  4.04it/s]
 67%|████████████████████████████████████████████████████▍                         | 6175/9182 [24:51<13:28,  3.72it/s]
 67%|████████████████████████████████████████████████████▍                         | 6178/9182 [24:51<07:38,  6.55it/s]
 67%|████████████████████████████████████████████████████▍                         | 6179/9182 [24:51<09:49,  5.09it/s]
 67%|████████████████████████████████████████████████████▍                         | 6180/9182 [24:51<10:58,  4.56it/s]
 67%|████████████████████████████████████████████████████▌                         | 6181/9182 [24:52<11:03,  4.52it/s]
 67%|████████████████████████████████████████████████████▌                         | 6182/9182 [24:52<13:31,  3.70it/s]
 67%|████████████████████████████████████████████████████▌                         | 6183/9182 [24:52<15:26,  3.24it/s]
 67%|████████████████████████████████████████████████████▌                         | 6190/9182 [24:53<05:15,  9.49it/s]
 67%|████████████████████████████████████████████████████▌                         | 6192/9182 [24:54<11:00,  4.53it/s]
 67%|████████████████████████████████████████████████████▌                         | 6193/9182 [24:54<13:14,  3.76it/s]
 67%|████████████████████████████████████████████████████▌                         | 6194/9182 [24:54<12:04,  4.12it/s]
 67%|████████████████████████████████████████████████████▋                         | 6195/9182 [24:55<12:08,  4.10it/s]
 67%|████████████████████████████████████████████████████▋                         | 6196/9182 [24:55<12:03,  4.13it/s]
 67%|████████████████████████████████████████████████████▋                         | 6197/9182 [24:55<12:24,  4.01it/s]
 68%|████████████████████████████████████████████████████▋                         | 6198/9182 [24:56<13:10,  3.77it/s]
 68%|████████████████████████████████████████████████████▋                         | 6201/9182 [24:56<09:57,  4.99it/s]
 68%|████████████████████████████████████████████████████▋                         | 6202/9182 [24:56<11:14,  4.42it/s]
 68%|████████████████████████████████████████████████████▋                         | 6203/9182 [24:57<10:54,  4.55it/s]
 68%|████████████████████████████████████████████████████▋                         | 6205/9182 [24:57<08:00,  6.19it/s]
 68%|████████████████████████████████████████████████████▋                         | 6206/9182 [24:57<08:40,  5.72it/s]
 68%|████████████████████████████████████████████████████▋                         | 6207/9182 [24:57<09:02,  5.48it/s]
 68%|████████████████████████████████████████████████████▋                         | 6208/9182 [24:57<08:31,  5.82it/s]
 68%|████████████████████████████████████████████████████▊                         | 6212/9182 [24:57<05:49,  8.49it/s]
 68%|████████████████████████████████████████████████████▊                         | 6215/9182 [24:58<05:31,  8.95it/s]
 68%|████████████████████████████████████████████████████▊                         | 6216/9182 [24:58<07:47,  6.34it/s]
 68%|████████████████████████████████████████████████████▊                         | 6217/9182 [24:59<16:37,  2.97it/s]
 68%|████████████████████████████████████████████████████▊                         | 6218/9182 [25:00<15:46,  3.13it/s]
 68%|████████████████████████████████████████████████████▊                         | 6219/9182 [25:00<15:36,  3.16it/s]
 68%|████████████████████████████████████████████████████▊                         | 6220/9182 [25:00<15:16,  3.23it/s]
 68%|████████████████████████████████████████████████████▊                         | 6223/9182 [25:01<11:59,  4.11it/s]
 68%|████████████████████████████████████████████████████▊                         | 6224/9182 [25:01<12:00,  4.11it/s]
 68%|████████████████████████████████████████████████████▉                         | 6225/9182 [25:01<10:47,  4.56it/s]
 68%|████████████████████████████████████████████████████▉                         | 6226/9182 [25:02<12:55,  3.81it/s]
 68%|████████████████████████████████████████████████████▉                         | 6228/9182 [25:02<11:10,  4.40it/s]
 68%|████████████████████████████████████████████████████▉                         | 6233/9182 [25:02<06:17,  7.81it/s]
 68%|████████████████████████████████████████████████████▉                         | 6235/9182 [25:02<05:36,  8.75it/s]
 68%|████████████████████████████████████████████████████▉                         | 6237/9182 [25:03<06:28,  7.58it/s]

 68%|████████████████████████████████████████████████████▉                         | 6239/9182 [25:03<05:57,  8.24it/s]
 68%|█████████████████████████████████████████████████████                         | 6241/9182 [25:03<05:00,  9.80it/s]
 68%|█████████████████████████████████████████████████████                         | 6243/9182 [25:03<06:02,  8.12it/s]
 68%|█████████████████████████████████████████████████████                         | 6245/9182 [25:04<07:00,  6.99it/s]
 68%|█████████████████████████████████████████████████████                         | 6247/9182 [25:04<08:55,  5.48it/s]
 68%|█████████████████████████████████████████████████████                         | 6248/9182 [25:04<09:07,  5.35it/s]
 68%|█████████████████████████████████████████████████████                         | 6249/9182 [25:05<08:40,  5.64it/s]
 68%|█████████████████████████████████████████████████████▏                        | 6256/9182 [25:05<04:57,  9.83it/s]
 68%|█████████████████████████████████████████████████████▏                        | 6257/9182 [25:05<06:18,  7.73it/s]
 68%|█████████████████████████████████████████████████████▏                        | 6258/9182 [25:06<06:33,  7.43it/s]
 68%|█████████████████████████████████████████████████████▏                        | 6264/9182 [25:06<03:42, 13.10it/s]
 68%|█████████████████████████████████████████████████████▏                        | 6266/9182 [25:07<10:54,  4.45it/s]
 68%|█████████████████████████████████████████████████████▏                        | 6268/9182 [25:08<10:05,  4.81it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6269/9182 [25:08<10:41,  4.54it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6270/9182 [25:08<11:08,  4.36it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6274/9182 [25:08<06:27,  7.51it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6276/9182 [25:09<10:17,  4.71it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6278/9182 [25:10<09:52,  4.90it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6279/9182 [25:10<10:09,  4.76it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6280/9182 [25:10<11:14,  4.30it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6281/9182 [25:10<11:35,  4.17it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6282/9182 [25:11<10:23,  4.65it/s]
 68%|█████████████████████████████████████████████████████▎                        | 6283/9182 [25:11<13:23,  3.61it/s]
 68%|█████████████████████████████████████████████████████▍                        | 6284/9182 [25:11<12:10,  3.97it/s]
 68%|█████████████████████████████████████████████████████▍                        | 6288/9182 [25:12<07:08,  6.76it/s]
 68%|█████████████████████████████████████████████████████▍                        | 6289/9182 [25:12<10:02,  4.80it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6290/9182 [25:13<12:26,  3.87it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6291/9182 [25:13<14:24,  3.35it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6292/9182 [25:13<12:54,  3.73it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6293/9182 [25:13<14:02,  3.43it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6294/9182 [25:14<12:28,  3.86it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6295/9182 [25:15<22:21,  2.15it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6296/9182 [25:15<18:28,  2.60it/s]
 69%|█████████████████████████████████████████████████████▍                        | 6297/9182 [25:16<23:41,  2.03it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6298/9182 [25:16<20:42,  2.32it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6299/9182 [25:16<17:33,  2.74it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6300/9182 [25:16<17:33,  2.74it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6301/9182 [25:16<13:52,  3.46it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6302/9182 [25:17<12:15,  3.92it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6303/9182 [25:17<11:33,  4.15it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6304/9182 [25:17<14:25,  3.32it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6305/9182 [25:18<11:38,  4.12it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6306/9182 [25:18<16:35,  2.89it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6307/9182 [25:18<14:00,  3.42it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6309/9182 [25:19<13:09,  3.64it/s]
 69%|█████████████████████████████████████████████████████▌                        | 6312/9182 [25:20<12:13,  3.91it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6313/9182 [25:20<14:56,  3.20it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6314/9182 [25:21<18:17,  2.61it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6317/9182 [25:21<12:46,  3.74it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6318/9182 [25:22<14:27,  3.30it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6319/9182 [25:22<13:17,  3.59it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6321/9182 [25:22<10:12,  4.67it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6322/9182 [25:22<11:10,  4.26it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6323/9182 [25:23<13:47,  3.46it/s]
 69%|█████████████████████████████████████████████████████▋                        | 6324/9182 [25:23<12:45,  3.73it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6328/9182 [25:24<13:03,  3.64it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6329/9182 [25:25<15:55,  2.99it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6330/9182 [25:25<14:38,  3.25it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6331/9182 [25:25<13:55,  3.41it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6332/9182 [25:25<14:16,  3.33it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6333/9182 [25:26<15:40,  3.03it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6334/9182 [25:26<14:34,  3.26it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6339/9182 [25:26<06:33,  7.23it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6340/9182 [25:27<11:46,  4.02it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6341/9182 [25:27<10:56,  4.33it/s]
 69%|█████████████████████████████████████████████████████▊                        | 6342/9182 [25:28<11:34,  4.09it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6343/9182 [25:28<11:44,  4.03it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6344/9182 [25:29<17:56,  2.64it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6345/9182 [25:29<15:37,  3.03it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6349/9182 [25:29<08:23,  5.63it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6350/9182 [25:29<08:05,  5.83it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6352/9182 [25:30<07:49,  6.02it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6353/9182 [25:30<07:23,  6.37it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6355/9182 [25:30<07:04,  6.66it/s]
 69%|█████████████████████████████████████████████████████▉                        | 6356/9182 [25:30<06:59,  6.74it/s]
 69%|██████████████████████████████████████████████████████                        | 6357/9182 [25:30<08:57,  5.26it/s]
 69%|██████████████████████████████████████████████████████                        | 6358/9182 [25:31<13:39,  3.44it/s]
 69%|██████████████████████████████████████████████████████                        | 6359/9182 [25:31<12:58,  3.63it/s]
 69%|██████████████████████████████████████████████████████                        | 6362/9182 [25:32<08:10,  5.74it/s]
 69%|██████████████████████████████████████████████████████                        | 6363/9182 [25:32<11:55,  3.94it/s]
 69%|██████████████████████████████████████████████████████                        | 6364/9182 [25:33<16:24,  2.86it/s]
 69%|██████████████████████████████████████████████████████                        | 6365/9182 [25:33<14:35,  3.22it/s]
 69%|██████████████████████████████████████████████████████                        | 6366/9182 [25:34<14:48,  3.17it/s]
 69%|██████████████████████████████████████████████████████                        | 6367/9182 [25:35<29:31,  1.59it/s]
 69%|██████████████████████████████████████████████████████                        | 6368/9182 [25:36<36:31,  1.28it/s]
 69%|██████████████████████████████████████████████████████                        | 6369/9182 [25:36<29:22,  1.60it/s]
 69%|██████████████████████████████████████████████████████                        | 6370/9182 [25:36<22:20,  2.10it/s]
 69%|██████████████████████████████████████████████████████                        | 6371/9182 [25:37<19:54,  2.35it/s]
 69%|██████████████████████████████████████████████████████▏                       | 6376/9182 [25:37<08:57,  5.22it/s]
 69%|██████████████████████████████████████████████████████▏                       | 6377/9182 [25:38<09:38,  4.85it/s]
 69%|██████████████████████████████████████████████████████▏                       | 6378/9182 [25:38<12:32,  3.73it/s]
 69%|██████████████████████████████████████████████████████▏                       | 6379/9182 [25:39<17:10,  2.72it/s]
 69%|██████████████████████████████████████████████████████▏                       | 6380/9182 [25:40<24:46,  1.88it/s]
 69%|██████████████████████████████████████████████████████▏                       | 6381/9182 [25:40<23:59,  1.95it/s]
 70%|██████████████████████████████████████████████████████▏                       | 6382/9182 [25:40<23:09,  2.01it/s]
 70%|██████████████████████████████████████████████████████▏                       | 6383/9182 [25:41<26:11,  1.78it/s]
 70%|██████████████████████████████████████████████████████▏                       | 6384/9182 [25:43<41:54,  1.11it/s]
 70%|██████████████████████████████████████████████████████▏                       | 6385/9182 [25:43<33:19,  1.40it/s]
 70%|██████████████████████████████████████████████████████▏                       | 6386/9182 [25:44<30:01,  1.55it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6387/9182 [25:44<24:35,  1.89it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6388/9182 [25:45<24:13,  1.92it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6389/9182 [25:45<22:31,  2.07it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6390/9182 [25:45<20:15,  2.30it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6391/9182 [25:46<22:14,  2.09it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6392/9182 [25:47<18:45,  2.48it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6393/9182 [25:47<26:44,  1.74it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6394/9182 [25:48<23:55,  1.94it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6395/9182 [25:48<21:08,  2.20it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6396/9182 [25:48<19:13,  2.42it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6397/9182 [25:49<19:55,  2.33it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6398/9182 [25:49<19:28,  2.38it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6399/9182 [25:49<16:29,  2.81it/s]
 70%|██████████████████████████████████████████████████████▎                       | 6400/9182 [25:49<14:50,  3.13it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6403/9182 [25:50<09:08,  5.07it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6408/9182 [25:51<08:31,  5.42it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6409/9182 [25:51<08:56,  5.17it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6410/9182 [25:51<10:03,  4.59it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6411/9182 [25:51<10:24,  4.43it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6412/9182 [25:52<09:11,  5.02it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6413/9182 [25:52<11:05,  4.16it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6414/9182 [25:53<13:52,  3.33it/s]
 70%|██████████████████████████████████████████████████████▍                       | 6415/9182 [25:53<16:35,  2.78it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6416/9182 [25:53<16:06,  2.86it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6417/9182 [25:53<13:11,  3.49it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6420/9182 [25:54<08:06,  5.68it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6421/9182 [25:54<11:38,  3.95it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6422/9182 [25:54<11:45,  3.91it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6423/9182 [25:55<12:00,  3.83it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6424/9182 [25:55<18:31,  2.48it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6425/9182 [25:56<15:46,  2.91it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6426/9182 [25:56<17:36,  2.61it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6427/9182 [25:57<17:54,  2.56it/s]

 70%|██████████████████████████████████████████████████████▌                       | 6428/9182 [25:57<23:41,  1.94it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6429/9182 [25:58<20:47,  2.21it/s]
 70%|██████████████████████████████████████████████████████▌                       | 6430/9182 [25:58<18:49,  2.44it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6431/9182 [25:58<17:10,  2.67it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6432/9182 [25:59<17:01,  2.69it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6433/9182 [25:59<16:21,  2.80it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6434/9182 [25:59<17:56,  2.55it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6435/9182 [26:00<15:37,  2.93it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6438/9182 [26:00<10:40,  4.28it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6439/9182 [26:01<12:34,  3.64it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6440/9182 [26:01<15:51,  2.88it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6441/9182 [26:02<16:06,  2.84it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6442/9182 [26:02<22:07,  2.06it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6443/9182 [26:02<18:35,  2.46it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6444/9182 [26:03<17:34,  2.60it/s]
 70%|██████████████████████████████████████████████████████▋                       | 6445/9182 [26:03<15:51,  2.88it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6446/9182 [26:04<17:36,  2.59it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6447/9182 [26:04<15:44,  2.90it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6448/9182 [26:04<18:08,  2.51it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6449/9182 [26:05<16:58,  2.68it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6450/9182 [26:05<13:42,  3.32it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6451/9182 [26:06<17:22,  2.62it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6452/9182 [26:06<16:32,  2.75it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6453/9182 [26:06<15:29,  2.93it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6454/9182 [26:06<14:41,  3.09it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6455/9182 [26:07<18:10,  2.50it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6456/9182 [26:07<16:38,  2.73it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6458/9182 [26:08<16:41,  2.72it/s]
 70%|██████████████████████████████████████████████████████▊                       | 6459/9182 [26:08<18:25,  2.46it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6460/9182 [26:09<16:37,  2.73it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6464/9182 [26:09<08:47,  5.15it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6465/9182 [26:10<15:10,  2.98it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6466/9182 [26:10<14:04,  3.22it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6467/9182 [26:10<13:35,  3.33it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6468/9182 [26:11<13:12,  3.42it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6469/9182 [26:11<12:23,  3.65it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6470/9182 [26:11<11:15,  4.02it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6471/9182 [26:12<12:03,  3.75it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6472/9182 [26:12<16:34,  2.73it/s]
 70%|██████████████████████████████████████████████████████▉                       | 6473/9182 [26:13<17:26,  2.59it/s]
 71%|██████████████████████████████████████████████████████▉                       | 6474/9182 [26:13<17:01,  2.65it/s]
 71%|███████████████████████████████████████████████████████                       | 6475/9182 [26:13<13:33,  3.33it/s]
 71%|███████████████████████████████████████████████████████                       | 6476/9182 [26:13<13:07,  3.43it/s]
 71%|███████████████████████████████████████████████████████                       | 6477/9182 [26:13<11:13,  4.02it/s]
 71%|███████████████████████████████████████████████████████                       | 6480/9182 [26:14<07:37,  5.91it/s]
 71%|███████████████████████████████████████████████████████                       | 6481/9182 [26:14<07:20,  6.13it/s]
 71%|███████████████████████████████████████████████████████                       | 6482/9182 [26:14<07:22,  6.10it/s]
 71%|███████████████████████████████████████████████████████                       | 6483/9182 [26:14<08:02,  5.60it/s]
 71%|███████████████████████████████████████████████████████                       | 6485/9182 [26:15<10:25,  4.31it/s]
 71%|███████████████████████████████████████████████████████                       | 6486/9182 [26:15<10:01,  4.48it/s]
 71%|███████████████████████████████████████████████████████                       | 6487/9182 [26:15<09:45,  4.60it/s]
 71%|███████████████████████████████████████████████████████                       | 6488/9182 [26:16<10:47,  4.16it/s]
 71%|███████████████████████████████████████████████████████                       | 6489/9182 [26:16<12:58,  3.46it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6490/9182 [26:16<11:59,  3.74it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6491/9182 [26:17<12:57,  3.46it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6492/9182 [26:17<14:46,  3.03it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6493/9182 [26:17<12:54,  3.47it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6494/9182 [26:18<10:25,  4.30it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6495/9182 [26:18<18:29,  2.42it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6496/9182 [26:18<17:02,  2.63it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6497/9182 [26:19<15:10,  2.95it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6498/9182 [26:19<17:03,  2.62it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6499/9182 [26:20<17:20,  2.58it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6500/9182 [26:20<24:47,  1.80it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6501/9182 [26:21<19:47,  2.26it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6502/9182 [26:21<20:54,  2.14it/s]
 71%|███████████████████████████████████████████████████████▏                      | 6503/9182 [26:21<18:09,  2.46it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6504/9182 [26:22<15:54,  2.80it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6506/9182 [26:22<09:45,  4.57it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6507/9182 [26:22<13:38,  3.27it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6508/9182 [26:23<14:01,  3.18it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6510/9182 [26:24<15:39,  2.84it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6511/9182 [26:24<18:23,  2.42it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6512/9182 [26:25<22:06,  2.01it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6513/9182 [26:25<22:11,  2.01it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6514/9182 [26:25<17:19,  2.57it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6515/9182 [26:26<18:09,  2.45it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6516/9182 [26:26<17:54,  2.48it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6517/9182 [26:28<33:09,  1.34it/s]
 71%|███████████████████████████████████████████████████████▎                      | 6518/9182 [26:28<27:24,  1.62it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6519/9182 [26:28<22:41,  1.96it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6520/9182 [26:29<17:42,  2.51it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6521/9182 [26:29<19:10,  2.31it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6522/9182 [26:29<15:32,  2.85it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6527/9182 [26:29<06:23,  6.92it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6528/9182 [26:30<07:47,  5.68it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6529/9182 [26:30<10:33,  4.18it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6530/9182 [26:31<10:09,  4.35it/s]
 71%|███████████████████████████████████████████████████████▍                      | 6531/9182 [26:31<16:22,  2.70it/s]
 71%|███████████████████████████████████████████████████████▌                      | 6538/9182 [26:31<05:33,  7.92it/s]
 71%|███████████████████████████████████████████████████████▌                      | 6540/9182 [26:32<05:46,  7.62it/s]
 71%|███████████████████████████████████████████████████████▌                      | 6544/9182 [26:32<04:09, 10.55it/s]
 71%|███████████████████████████████████████████████████████▌                      | 6546/9182 [26:32<04:30,  9.76it/s]
 71%|███████████████████████████████████████████████████████▌                      | 6548/9182 [26:33<06:17,  6.98it/s]
 71%|███████████████████████████████████████████████████████▋                      | 6550/9182 [26:34<12:05,  3.63it/s]
 71%|███████████████████████████████████████████████████████▋                      | 6551/9182 [26:34<12:44,  3.44it/s]
 71%|███████████████████████████████████████████████████████▋                      | 6552/9182 [26:35<14:01,  3.13it/s]
 71%|███████████████████████████████████████████████████████▋                      | 6556/9182 [26:35<08:31,  5.13it/s]
 71%|███████████████████████████████████████████████████████▋                      | 6557/9182 [26:36<10:08,  4.31it/s]
 71%|███████████████████████████████████████████████████████▋                      | 6558/9182 [26:36<11:22,  3.84it/s]
 71%|███████████████████████████████████████████████████████▊                      | 6564/9182 [26:36<05:51,  7.45it/s]
 71%|███████████████████████████████████████████████████████▊                      | 6565/9182 [26:37<06:55,  6.29it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6566/9182 [26:37<08:56,  4.88it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6567/9182 [26:37<08:52,  4.91it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6568/9182 [26:38<08:53,  4.90it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6569/9182 [26:38<11:05,  3.93it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6570/9182 [26:38<11:10,  3.89it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6571/9182 [26:39<13:24,  3.24it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6574/9182 [26:39<07:49,  5.56it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6575/9182 [26:39<08:15,  5.26it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6576/9182 [26:39<07:50,  5.54it/s]
 72%|███████████████████████████████████████████████████████▊                      | 6577/9182 [26:40<09:56,  4.37it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6579/9182 [26:40<07:07,  6.09it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6581/9182 [26:40<08:13,  5.27it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6582/9182 [26:41<09:14,  4.69it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6583/9182 [26:41<10:03,  4.30it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6584/9182 [26:42<15:14,  2.84it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6585/9182 [26:42<13:33,  3.19it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6586/9182 [26:42<12:42,  3.41it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6587/9182 [26:42<14:12,  3.04it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6588/9182 [26:43<14:25,  3.00it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6589/9182 [26:43<11:59,  3.60it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6590/9182 [26:43<11:16,  3.83it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6591/9182 [26:43<10:54,  3.96it/s]
 72%|███████████████████████████████████████████████████████▉                      | 6592/9182 [26:43<09:47,  4.41it/s]
 72%|████████████████████████████████████████████████████████                      | 6593/9182 [26:44<11:36,  3.72it/s]
 72%|████████████████████████████████████████████████████████                      | 6594/9182 [26:44<12:31,  3.45it/s]
 72%|████████████████████████████████████████████████████████                      | 6595/9182 [26:45<11:54,  3.62it/s]
 72%|████████████████████████████████████████████████████████                      | 6596/9182 [26:45<13:19,  3.23it/s]
 72%|████████████████████████████████████████████████████████                      | 6597/9182 [26:45<13:57,  3.09it/s]
 72%|████████████████████████████████████████████████████████                      | 6598/9182 [26:46<13:57,  3.08it/s]
 72%|████████████████████████████████████████████████████████                      | 6599/9182 [26:46<14:29,  2.97it/s]

 72%|████████████████████████████████████████████████████████                      | 6600/9182 [26:46<15:45,  2.73it/s]
 72%|████████████████████████████████████████████████████████                      | 6601/9182 [26:47<14:51,  2.90it/s]
 72%|████████████████████████████████████████████████████████                      | 6602/9182 [26:47<12:25,  3.46it/s]
 72%|████████████████████████████████████████████████████████                      | 6603/9182 [26:47<14:41,  2.93it/s]
 72%|████████████████████████████████████████████████████████                      | 6604/9182 [26:47<12:24,  3.46it/s]
 72%|████████████████████████████████████████████████████████                      | 6605/9182 [26:47<10:03,  4.27it/s]
 72%|████████████████████████████████████████████████████████                      | 6606/9182 [26:48<09:35,  4.48it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6607/9182 [26:48<09:54,  4.33it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6608/9182 [26:48<10:56,  3.92it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6609/9182 [26:49<11:26,  3.75it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6610/9182 [26:49<11:40,  3.67it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6611/9182 [26:49<12:05,  3.54it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6612/9182 [26:49<12:29,  3.43it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6613/9182 [26:50<10:32,  4.06it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6614/9182 [26:50<12:54,  3.31it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6615/9182 [26:50<11:35,  3.69it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6616/9182 [26:50<11:11,  3.82it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6617/9182 [26:51<09:14,  4.63it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6619/9182 [26:51<07:32,  5.66it/s]
 72%|████████████████████████████████████████████████████████▏                     | 6620/9182 [26:51<08:38,  4.94it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6622/9182 [26:51<06:39,  6.40it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6623/9182 [26:52<08:44,  4.88it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6624/9182 [26:52<08:16,  5.16it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6626/9182 [26:52<09:52,  4.32it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6627/9182 [26:53<11:03,  3.85it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6628/9182 [26:53<11:04,  3.84it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6629/9182 [26:53<10:43,  3.96it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6630/9182 [26:54<10:22,  4.10it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6631/9182 [26:54<10:04,  4.22it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6633/9182 [26:54<06:50,  6.21it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6634/9182 [26:54<09:30,  4.47it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6635/9182 [26:55<13:55,  3.05it/s]
 72%|████████████████████████████████████████████████████████▎                     | 6636/9182 [26:55<12:00,  3.53it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6637/9182 [26:55<10:29,  4.04it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6638/9182 [26:56<11:14,  3.77it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6639/9182 [26:56<12:32,  3.38it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6640/9182 [26:56<11:08,  3.80it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6641/9182 [26:56<10:57,  3.86it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6642/9182 [26:57<11:30,  3.68it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6644/9182 [26:57<09:34,  4.42it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6645/9182 [26:57<11:04,  3.82it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6646/9182 [26:58<13:19,  3.17it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6647/9182 [26:58<11:53,  3.55it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6648/9182 [26:58<09:49,  4.30it/s]
 72%|████████████████████████████████████████████████████████▍                     | 6649/9182 [26:58<08:24,  5.02it/s]
 72%|████████████████████████████████████████████████████████▌                     | 6654/9182 [26:59<05:08,  8.19it/s]
 72%|████████████████████████████████████████████████████████▌                     | 6655/9182 [26:59<05:34,  7.57it/s]
 72%|████████████████████████████████████████████████████████▌                     | 6656/9182 [26:59<05:36,  7.51it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6657/9182 [26:59<07:16,  5.78it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6658/9182 [27:00<09:45,  4.31it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6659/9182 [27:00<10:48,  3.89it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6660/9182 [27:00<09:04,  4.63it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6661/9182 [27:00<09:58,  4.21it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6664/9182 [27:01<05:49,  7.20it/s]
 73%|████████████████████████████████████████████████████████▌                     | 6665/9182 [27:02<14:47,  2.84it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6666/9182 [27:02<13:57,  3.01it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6667/9182 [27:02<12:34,  3.33it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6670/9182 [27:03<10:40,  3.92it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6671/9182 [27:03<09:44,  4.30it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6673/9182 [27:04<09:40,  4.32it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6674/9182 [27:05<18:07,  2.31it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6675/9182 [27:05<16:17,  2.57it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6676/9182 [27:05<14:50,  2.81it/s]
 73%|████████████████████████████████████████████████████████▋                     | 6677/9182 [27:05<14:49,  2.82it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6681/9182 [27:06<06:51,  6.08it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6683/9182 [27:06<09:53,  4.21it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6685/9182 [27:07<09:39,  4.31it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6686/9182 [27:07<10:40,  3.90it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6687/9182 [27:08<10:26,  3.98it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6688/9182 [27:08<10:06,  4.11it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6689/9182 [27:08<09:29,  4.38it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6690/9182 [27:09<12:16,  3.38it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6691/9182 [27:09<11:47,  3.52it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6692/9182 [27:09<10:54,  3.81it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6693/9182 [27:10<14:32,  2.85it/s]
 73%|████████████████████████████████████████████████████████▊                     | 6694/9182 [27:10<12:14,  3.39it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6698/9182 [27:10<07:46,  5.32it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6699/9182 [27:11<10:15,  4.03it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6700/9182 [27:11<09:35,  4.32it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6701/9182 [27:11<09:08,  4.52it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6702/9182 [27:12<11:44,  3.52it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6703/9182 [27:12<15:08,  2.73it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6704/9182 [27:12<12:41,  3.26it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6705/9182 [27:13<12:33,  3.29it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6706/9182 [27:13<11:51,  3.48it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6707/9182 [27:13<12:03,  3.42it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6708/9182 [27:13<11:13,  3.67it/s]
 73%|████████████████████████████████████████████████████████▉                     | 6709/9182 [27:14<12:13,  3.37it/s]
 73%|█████████████████████████████████████████████████████████                     | 6710/9182 [27:14<10:56,  3.77it/s]
 73%|█████████████████████████████████████████████████████████                     | 6711/9182 [27:14<11:14,  3.66it/s]
 73%|█████████████████████████████████████████████████████████                     | 6712/9182 [27:14<10:01,  4.11it/s]
 73%|█████████████████████████████████████████████████████████                     | 6713/9182 [27:15<09:42,  4.24it/s]
 73%|█████████████████████████████████████████████████████████                     | 6714/9182 [27:15<10:57,  3.76it/s]
 73%|█████████████████████████████████████████████████████████                     | 6715/9182 [27:15<10:37,  3.87it/s]
 73%|█████████████████████████████████████████████████████████                     | 6716/9182 [27:16<16:32,  2.48it/s]
 73%|█████████████████████████████████████████████████████████                     | 6719/9182 [27:16<09:08,  4.49it/s]
 73%|█████████████████████████████████████████████████████████                     | 6720/9182 [27:16<09:32,  4.30it/s]
 73%|█████████████████████████████████████████████████████████                     | 6721/9182 [27:17<08:23,  4.89it/s]
 73%|█████████████████████████████████████████████████████████                     | 6722/9182 [27:17<11:09,  3.67it/s]
 73%|█████████████████████████████████████████████████████████                     | 6723/9182 [27:17<12:14,  3.35it/s]
 73%|█████████████████████████████████████████████████████████                     | 6724/9182 [27:18<12:42,  3.22it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6725/9182 [27:18<14:15,  2.87it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6726/9182 [27:18<12:50,  3.19it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6727/9182 [27:19<10:39,  3.84it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6728/9182 [27:19<13:06,  3.12it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6729/9182 [27:19<12:01,  3.40it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6730/9182 [27:19<10:46,  3.79it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6731/9182 [27:20<10:52,  3.76it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6732/9182 [27:20<10:46,  3.79it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6733/9182 [27:20<09:59,  4.08it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6734/9182 [27:21<11:33,  3.53it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6735/9182 [27:21<10:30,  3.88it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6736/9182 [27:21<09:08,  4.46it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6737/9182 [27:21<11:20,  3.59it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6738/9182 [27:22<11:27,  3.56it/s]
 73%|█████████████████████████████████████████████████████████▏                    | 6739/9182 [27:22<13:20,  3.05it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6740/9182 [27:22<12:40,  3.21it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6741/9182 [27:22<11:38,  3.50it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6742/9182 [27:23<10:14,  3.97it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6743/9182 [27:23<10:46,  3.77it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6744/9182 [27:23<10:16,  3.96it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6745/9182 [27:23<10:12,  3.98it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6746/9182 [27:24<11:04,  3.67it/s]
 73%|█████████████████████████████████████████████████████████▎                    | 6748/9182 [27:24<08:07,  5.00it/s]
 74%|█████████████████████████████████████████████████████████▎                    | 6749/9182 [27:25<08:50,  4.59it/s]
 74%|█████████████████████████████████████████████████████████▎                    | 6750/9182 [27:25<14:41,  2.76it/s]
 74%|█████████████████████████████████████████████████████████▎                    | 6751/9182 [27:25<14:58,  2.71it/s]
 74%|█████████████████████████████████████████████████████████▎                    | 6752/9182 [27:26<13:24,  3.02it/s]
 74%|█████████████████████████████████████████████████████████▎                    | 6753/9182 [27:26<11:46,  3.44it/s]
 74%|█████████████████████████████████████████████████████████▎                    | 6754/9182 [27:26<12:43,  3.18it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6755/9182 [27:26<10:21,  3.90it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6756/9182 [27:27<10:59,  3.68it/s]

 74%|█████████████████████████████████████████████████████████▍                    | 6757/9182 [27:27<09:53,  4.09it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6758/9182 [27:27<09:49,  4.11it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6759/9182 [27:27<11:53,  3.40it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6760/9182 [27:27<09:45,  4.14it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6761/9182 [27:28<10:25,  3.87it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6762/9182 [27:28<12:10,  3.31it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6764/9182 [27:29<09:00,  4.47it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6765/9182 [27:29<10:46,  3.74it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6766/9182 [27:29<10:18,  3.90it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6767/9182 [27:29<09:40,  4.16it/s]
 74%|█████████████████████████████████████████████████████████▍                    | 6768/9182 [27:29<08:57,  4.49it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6769/9182 [27:30<11:45,  3.42it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6770/9182 [27:30<10:17,  3.91it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6771/9182 [27:30<11:03,  3.63it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6772/9182 [27:31<11:42,  3.43it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6773/9182 [27:31<12:40,  3.17it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6774/9182 [27:31<11:15,  3.56it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6775/9182 [27:32<10:58,  3.66it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6776/9182 [27:32<10:16,  3.90it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6777/9182 [27:32<10:27,  3.84it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6778/9182 [27:33<13:08,  3.05it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6779/9182 [27:33<13:23,  2.99it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6780/9182 [27:33<12:24,  3.23it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6781/9182 [27:33<11:33,  3.46it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6782/9182 [27:34<11:51,  3.37it/s]
 74%|█████████████████████████████████████████████████████████▌                    | 6783/9182 [27:34<12:18,  3.25it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6784/9182 [27:34<11:52,  3.37it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6785/9182 [27:35<10:29,  3.81it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6786/9182 [27:35<10:54,  3.66it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6787/9182 [27:35<10:51,  3.68it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6791/9182 [27:36<09:35,  4.16it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6792/9182 [27:36<09:00,  4.42it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6793/9182 [27:37<10:03,  3.96it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6794/9182 [27:37<11:53,  3.35it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6795/9182 [27:37<11:22,  3.50it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6796/9182 [27:37<09:49,  4.05it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6797/9182 [27:38<09:42,  4.10it/s]
 74%|█████████████████████████████████████████████████████████▋                    | 6798/9182 [27:38<08:28,  4.69it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6799/9182 [27:38<09:19,  4.26it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6800/9182 [27:38<08:21,  4.75it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6801/9182 [27:38<08:38,  4.59it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6802/9182 [27:39<09:40,  4.10it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6803/9182 [27:39<12:03,  3.29it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6804/9182 [27:40<13:50,  2.86it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6805/9182 [27:40<12:10,  3.26it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6806/9182 [27:40<14:39,  2.70it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6807/9182 [27:41<12:24,  3.19it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6808/9182 [27:41<10:33,  3.75it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6809/9182 [27:41<09:50,  4.02it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6810/9182 [27:41<13:04,  3.02it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6811/9182 [27:41<10:31,  3.76it/s]
 74%|█████████████████████████████████████████████████████████▊                    | 6812/9182 [27:42<10:13,  3.86it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6815/9182 [27:42<10:18,  3.83it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6816/9182 [27:43<09:23,  4.20it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6817/9182 [27:43<12:14,  3.22it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6818/9182 [27:44<13:57,  2.82it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6820/9182 [27:45<16:17,  2.42it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6821/9182 [27:45<14:55,  2.64it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6822/9182 [27:45<15:07,  2.60it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6823/9182 [27:46<13:40,  2.88it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6824/9182 [27:46<15:52,  2.48it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6825/9182 [27:47<15:20,  2.56it/s]
 74%|█████████████████████████████████████████████████████████▉                    | 6826/9182 [27:47<12:25,  3.16it/s]
 74%|██████████████████████████████████████████████████████████                    | 6833/9182 [27:48<06:49,  5.73it/s]
 74%|██████████████████████████████████████████████████████████                    | 6834/9182 [27:48<07:21,  5.32it/s]
 74%|██████████████████████████████████████████████████████████                    | 6835/9182 [27:49<13:33,  2.88it/s]
 74%|██████████████████████████████████████████████████████████                    | 6837/9182 [27:49<11:14,  3.48it/s]
 74%|██████████████████████████████████████████████████████████                    | 6839/9182 [27:50<08:43,  4.47it/s]
 74%|██████████████████████████████████████████████████████████                    | 6840/9182 [27:50<08:11,  4.77it/s]
 75%|██████████████████████████████████████████████████████████                    | 6841/9182 [27:50<07:18,  5.34it/s]
 75%|██████████████████████████████████████████████████████████                    | 6842/9182 [27:50<07:25,  5.25it/s]
 75%|██████████████████████████████████████████████████████████▏                   | 6843/9182 [27:50<07:58,  4.89it/s]
 75%|██████████████████████████████████████████████████████████▏                   | 6845/9182 [27:51<09:17,  4.19it/s]
 75%|██████████████████████████████████████████████████████████▏                   | 6846/9182 [27:51<08:25,  4.62it/s]
 75%|██████████████████████████████████████████████████████████▏                   | 6847/9182 [27:51<07:29,  5.20it/s]
 75%|██████████████████████████████████████████████████████████▏                   | 6852/9182 [27:51<04:59,  7.77it/s]
 75%|██████████████████████████████████████████████████████████▏                   | 6856/9182 [27:52<03:25, 11.31it/s]
 75%|██████████████████████████████████████████████████████████▎                   | 6858/9182 [27:52<06:23,  6.05it/s]
 75%|██████████████████████████████████████████████████████████▎                   | 6860/9182 [27:53<05:57,  6.49it/s]
 75%|██████████████████████████████████████████████████████████▎                   | 6865/9182 [27:53<04:12,  9.18it/s]
 75%|██████████████████████████████████████████████████████████▎                   | 6871/9182 [27:53<02:50, 13.53it/s]
 75%|██████████████████████████████████████████████████████████▍                   | 6873/9182 [27:54<03:53,  9.89it/s]
 75%|██████████████████████████████████████████████████████████▍                   | 6875/9182 [27:54<05:39,  6.80it/s]
 75%|██████████████████████████████████████████████████████████▍                   | 6877/9182 [27:55<05:36,  6.85it/s]
 75%|██████████████████████████████████████████████████████████▍                   | 6878/9182 [27:55<06:16,  6.12it/s]
 75%|██████████████████████████████████████████████████████████▍                   | 6879/9182 [27:55<06:52,  5.59it/s]
 75%|██████████████████████████████████████████████████████████▍                   | 6880/9182 [27:55<06:28,  5.92it/s]
 75%|██████████████████████████████████████████████████████████▌                   | 6891/9182 [27:56<02:44, 13.90it/s]
 75%|██████████████████████████████████████████████████████████▌                   | 6893/9182 [27:56<03:43, 10.23it/s]
 75%|██████████████████████████████████████████████████████████▌                   | 6895/9182 [27:56<03:31, 10.80it/s]
 75%|██████████████████████████████████████████████████████████▌                   | 6897/9182 [27:57<04:53,  7.78it/s]
 75%|██████████████████████████████████████████████████████████▌                   | 6899/9182 [27:57<06:09,  6.19it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6902/9182 [27:58<05:33,  6.83it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6903/9182 [27:58<05:42,  6.66it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6907/9182 [27:58<04:17,  8.84it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6910/9182 [27:59<06:50,  5.54it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6911/9182 [28:00<07:32,  5.01it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6912/9182 [28:00<09:17,  4.07it/s]
 75%|██████████████████████████████████████████████████████████▋                   | 6913/9182 [28:00<09:13,  4.10it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6916/9182 [28:01<11:28,  3.29it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6917/9182 [28:01<10:14,  3.69it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6918/9182 [28:02<09:33,  3.94it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6919/9182 [28:02<09:26,  4.00it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6920/9182 [28:02<09:11,  4.10it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6921/9182 [28:03<12:21,  3.05it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6922/9182 [28:03<10:42,  3.52it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6923/9182 [28:03<09:45,  3.86it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6924/9182 [28:04<12:12,  3.08it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6925/9182 [28:04<13:24,  2.81it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6926/9182 [28:04<11:26,  3.29it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6927/9182 [28:04<10:26,  3.60it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6928/9182 [28:05<08:46,  4.28it/s]
 75%|██████████████████████████████████████████████████████████▊                   | 6929/9182 [28:05<08:34,  4.38it/s]
 76%|██████████████████████████████████████████████████████████▉                   | 6942/9182 [28:05<01:35, 23.52it/s]
 76%|███████████████████████████████████████████████████████████                   | 6946/9182 [28:05<02:00, 18.57it/s]
 76%|███████████████████████████████████████████████████████████                   | 6949/9182 [28:07<05:36,  6.64it/s]
 76%|███████████████████████████████████████████████████████████                   | 6952/9182 [28:09<11:16,  3.30it/s]
 76%|███████████████████████████████████████████████████████████                   | 6954/9182 [28:09<10:23,  3.58it/s]
 76%|███████████████████████████████████████████████████████████                   | 6956/9182 [28:10<09:01,  4.11it/s]
 76%|███████████████████████████████████████████████████████████                   | 6958/9182 [28:11<13:27,  2.75it/s]
 76%|███████████████████████████████████████████████████████████                   | 6959/9182 [28:11<12:33,  2.95it/s]
 76%|███████████████████████████████████████████████████████████                   | 6960/9182 [28:12<13:52,  2.67it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6961/9182 [28:15<36:18,  1.02it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6962/9182 [28:15<29:27,  1.26it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6963/9182 [28:15<24:23,  1.52it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6964/9182 [28:16<19:24,  1.90it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6965/9182 [28:16<16:35,  2.23it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6966/9182 [28:18<33:03,  1.12it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6967/9182 [28:18<29:28,  1.25it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6968/9182 [28:19<24:02,  1.53it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6969/9182 [28:19<18:32,  1.99it/s]
 76%|███████████████████████████████████████████████████████████▏                  | 6970/9182 [28:19<14:52,  2.48it/s]

 76%|███████████████████████████████████████████████████████████▏                  | 6971/9182 [28:19<13:40,  2.69it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6977/9182 [28:20<05:10,  7.11it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6978/9182 [28:21<12:30,  2.94it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6979/9182 [28:22<13:37,  2.70it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6984/9182 [28:23<10:36,  3.45it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6986/9182 [28:23<09:47,  3.74it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6987/9182 [28:24<10:08,  3.61it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6988/9182 [28:24<13:06,  2.79it/s]
 76%|███████████████████████████████████████████████████████████▎                  | 6989/9182 [28:26<24:19,  1.50it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 6994/9182 [28:26<10:34,  3.45it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 6996/9182 [28:27<09:21,  3.89it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 6998/9182 [28:27<10:05,  3.61it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 6999/9182 [28:28<10:02,  3.62it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 7000/9182 [28:28<09:23,  3.87it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 7001/9182 [28:28<08:58,  4.05it/s]
 76%|███████████████████████████████████████████████████████████▍                  | 7003/9182 [28:28<06:27,  5.62it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7005/9182 [28:28<06:29,  5.59it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7006/9182 [28:29<05:58,  6.07it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7008/9182 [28:30<11:24,  3.18it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7013/9182 [28:30<06:04,  5.96it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7015/9182 [28:31<07:48,  4.62it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7016/9182 [28:32<10:31,  3.43it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7017/9182 [28:32<11:18,  3.19it/s]
 76%|███████████████████████████████████████████████████████████▌                  | 7018/9182 [28:32<09:52,  3.65it/s]
 76%|███████████████████████████████████████████████████████████▋                  | 7019/9182 [28:32<08:52,  4.06it/s]
 76%|███████████████████████████████████████████████████████████▋                  | 7020/9182 [28:32<07:57,  4.53it/s]
 76%|███████████████████████████████████████████████████████████▋                  | 7021/9182 [28:33<08:02,  4.48it/s]
 76%|███████████████████████████████████████████████████████████▋                  | 7023/9182 [28:33<05:39,  6.36it/s]
 76%|███████████████████████████████████████████████████████████▋                  | 7024/9182 [28:33<06:33,  5.49it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7025/9182 [28:33<06:27,  5.56it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7028/9182 [28:34<06:26,  5.58it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7029/9182 [28:34<08:59,  3.99it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7030/9182 [28:35<10:14,  3.50it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7031/9182 [28:35<10:28,  3.42it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7032/9182 [28:36<20:45,  1.73it/s]
 77%|███████████████████████████████████████████████████████████▋                  | 7033/9182 [28:37<25:30,  1.40it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7034/9182 [28:38<20:25,  1.75it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7036/9182 [28:38<16:37,  2.15it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7037/9182 [28:38<14:40,  2.44it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7042/9182 [28:40<11:56,  2.99it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7043/9182 [28:40<11:38,  3.06it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7044/9182 [28:41<11:01,  3.23it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7045/9182 [28:41<10:05,  3.53it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7046/9182 [28:41<10:26,  3.41it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7047/9182 [28:41<11:10,  3.18it/s]
 77%|███████████████████████████████████████████████████████████▊                  | 7048/9182 [28:42<10:47,  3.30it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7049/9182 [28:42<11:05,  3.20it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7050/9182 [28:43<14:02,  2.53it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7051/9182 [28:43<14:33,  2.44it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7052/9182 [28:44<16:24,  2.16it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7053/9182 [28:44<18:56,  1.87it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7054/9182 [28:45<17:30,  2.03it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7055/9182 [28:45<18:50,  1.88it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7056/9182 [28:46<16:06,  2.20it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7057/9182 [28:47<24:17,  1.46it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7058/9182 [28:48<25:39,  1.38it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7059/9182 [28:48<20:47,  1.70it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7060/9182 [28:48<19:35,  1.81it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7061/9182 [28:49<15:56,  2.22it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7062/9182 [28:49<15:02,  2.35it/s]
 77%|███████████████████████████████████████████████████████████▉                  | 7063/9182 [28:49<12:42,  2.78it/s]
 77%|████████████████████████████████████████████████████████████                  | 7064/9182 [28:49<11:05,  3.18it/s]
 77%|████████████████████████████████████████████████████████████                  | 7065/9182 [28:50<08:54,  3.96it/s]
 77%|████████████████████████████████████████████████████████████                  | 7066/9182 [28:50<14:13,  2.48it/s]
 77%|████████████████████████████████████████████████████████████                  | 7067/9182 [28:51<13:35,  2.59it/s]
 77%|████████████████████████████████████████████████████████████                  | 7068/9182 [28:51<11:03,  3.19it/s]
 77%|████████████████████████████████████████████████████████████                  | 7069/9182 [28:51<10:10,  3.46it/s]
 77%|████████████████████████████████████████████████████████████                  | 7070/9182 [28:52<16:29,  2.14it/s]
 77%|████████████████████████████████████████████████████████████                  | 7071/9182 [28:52<17:14,  2.04it/s]
 77%|████████████████████████████████████████████████████████████                  | 7072/9182 [28:53<13:48,  2.55it/s]
 77%|████████████████████████████████████████████████████████████                  | 7073/9182 [28:53<12:11,  2.88it/s]
 77%|████████████████████████████████████████████████████████████                  | 7074/9182 [28:53<12:46,  2.75it/s]
 77%|████████████████████████████████████████████████████████████                  | 7075/9182 [28:53<11:43,  3.00it/s]
 77%|████████████████████████████████████████████████████████████                  | 7076/9182 [28:54<10:48,  3.25it/s]
 77%|████████████████████████████████████████████████████████████                  | 7077/9182 [28:54<10:47,  3.25it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7078/9182 [28:55<16:34,  2.11it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7079/9182 [28:55<14:26,  2.43it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7080/9182 [28:55<12:40,  2.76it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7081/9182 [28:56<11:15,  3.11it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7082/9182 [28:56<12:28,  2.80it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7083/9182 [28:57<12:23,  2.82it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7084/9182 [28:57<16:45,  2.09it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7085/9182 [28:58<18:23,  1.90it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7086/9182 [28:58<15:23,  2.27it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7087/9182 [28:59<14:40,  2.38it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7088/9182 [28:59<15:31,  2.25it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7089/9182 [28:59<14:16,  2.44it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7090/9182 [29:00<16:42,  2.09it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7091/9182 [29:00<16:09,  2.16it/s]
 77%|████████████████████████████████████████████████████████████▏                 | 7092/9182 [29:01<17:00,  2.05it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7093/9182 [29:02<16:15,  2.14it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7094/9182 [29:02<20:29,  1.70it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7095/9182 [29:02<16:07,  2.16it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7096/9182 [29:02<12:23,  2.80it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7099/9182 [29:03<06:56,  5.00it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7100/9182 [29:03<06:23,  5.43it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7101/9182 [29:03<08:34,  4.04it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7102/9182 [29:03<07:22,  4.70it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7103/9182 [29:04<10:16,  3.37it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7104/9182 [29:04<10:45,  3.22it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7105/9182 [29:04<09:30,  3.64it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7106/9182 [29:05<09:23,  3.68it/s]
 77%|████████████████████████████████████████████████████████████▎                 | 7107/9182 [29:05<08:07,  4.26it/s]
 77%|████████████████████████████████████████████████████████████▍                 | 7108/9182 [29:05<08:04,  4.28it/s]
 77%|████████████████████████████████████████████████████████████▍                 | 7113/9182 [29:05<04:08,  8.32it/s]
 77%|████████████████████████████████████████████████████████████▍                 | 7114/9182 [29:06<04:18,  8.01it/s]
 77%|████████████████████████████████████████████████████████████▍                 | 7115/9182 [29:06<07:11,  4.79it/s]
 77%|████████████████████████████████████████████████████████████▍                 | 7116/9182 [29:06<07:09,  4.81it/s]
 78%|████████████████████████████████████████████████████████████▍                 | 7117/9182 [29:07<07:21,  4.68it/s]
 78%|████████████████████████████████████████████████████████████▍                 | 7118/9182 [29:07<10:19,  3.33it/s]
 78%|████████████████████████████████████████████████████████████▍                 | 7119/9182 [29:07<11:01,  3.12it/s]
 78%|████████████████████████████████████████████████████████████▍                 | 7120/9182 [29:08<09:14,  3.72it/s]
 78%|████████████████████████████████████████████████████████████▍                 | 7121/9182 [29:08<10:47,  3.18it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7122/9182 [29:08<09:14,  3.72it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7123/9182 [29:09<09:51,  3.48it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7124/9182 [29:09<08:52,  3.87it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7125/9182 [29:09<09:06,  3.77it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7129/9182 [29:09<04:05,  8.37it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7131/9182 [29:10<04:54,  6.97it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7132/9182 [29:10<04:53,  6.98it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7133/9182 [29:10<05:13,  6.54it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7134/9182 [29:10<07:30,  4.55it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7135/9182 [29:11<07:59,  4.27it/s]
 78%|████████████████████████████████████████████████████████████▌                 | 7136/9182 [29:11<08:35,  3.97it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7137/9182 [29:12<14:51,  2.29it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7138/9182 [29:12<14:06,  2.42it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7140/9182 [29:13<10:38,  3.20it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7141/9182 [29:13<15:42,  2.17it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7142/9182 [29:14<12:53,  2.64it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7143/9182 [29:14<15:46,  2.15it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7144/9182 [29:15<14:35,  2.33it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7145/9182 [29:15<14:08,  2.40it/s]

 78%|████████████████████████████████████████████████████████████▋                 | 7146/9182 [29:15<13:03,  2.60it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7147/9182 [29:15<10:46,  3.15it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7150/9182 [29:16<06:36,  5.13it/s]
 78%|████████████████████████████████████████████████████████████▋                 | 7151/9182 [29:17<09:36,  3.52it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7152/9182 [29:17<09:30,  3.56it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7153/9182 [29:18<15:23,  2.20it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7154/9182 [29:18<16:55,  2.00it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7155/9182 [29:19<13:30,  2.50it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7156/9182 [29:19<13:08,  2.57it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7157/9182 [29:19<15:11,  2.22it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7158/9182 [29:20<12:39,  2.67it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7159/9182 [29:20<11:18,  2.98it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7160/9182 [29:21<15:13,  2.21it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7161/9182 [29:21<16:10,  2.08it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7162/9182 [29:22<18:19,  1.84it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7163/9182 [29:22<17:14,  1.95it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7164/9182 [29:24<26:44,  1.26it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7165/9182 [29:24<20:36,  1.63it/s]
 78%|████████████████████████████████████████████████████████████▊                 | 7166/9182 [29:24<17:58,  1.87it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7167/9182 [29:25<14:34,  2.30it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7168/9182 [29:25<14:00,  2.40it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7169/9182 [29:25<11:21,  2.95it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7170/9182 [29:25<11:12,  2.99it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7171/9182 [29:26<09:55,  3.38it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7172/9182 [29:26<09:24,  3.56it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7173/9182 [29:26<11:34,  2.89it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7174/9182 [29:27<12:28,  2.68it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7175/9182 [29:27<14:52,  2.25it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7176/9182 [29:28<13:15,  2.52it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7177/9182 [29:28<13:10,  2.54it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7178/9182 [29:29<17:06,  1.95it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7179/9182 [29:29<13:42,  2.43it/s]
 78%|████████████████████████████████████████████████████████████▉                 | 7180/9182 [29:29<12:19,  2.71it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7181/9182 [29:30<16:06,  2.07it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7182/9182 [29:30<13:35,  2.45it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7183/9182 [29:31<12:08,  2.74it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7184/9182 [29:31<11:36,  2.87it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7185/9182 [29:31<10:53,  3.06it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7186/9182 [29:31<10:07,  3.29it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7187/9182 [29:32<11:21,  2.93it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7188/9182 [29:32<09:35,  3.47it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7189/9182 [29:33<11:55,  2.78it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7190/9182 [29:33<12:41,  2.62it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7191/9182 [29:33<11:16,  2.94it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7192/9182 [29:33<10:07,  3.28it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7193/9182 [29:34<09:51,  3.36it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7194/9182 [29:34<11:20,  2.92it/s]
 78%|█████████████████████████████████████████████████████████████                 | 7195/9182 [29:35<10:48,  3.06it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7196/9182 [29:35<17:02,  1.94it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7197/9182 [29:36<16:08,  2.05it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7198/9182 [29:37<18:00,  1.84it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7199/9182 [29:37<16:53,  1.96it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7200/9182 [29:37<13:02,  2.53it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7201/9182 [29:38<16:14,  2.03it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7202/9182 [29:38<14:18,  2.31it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7203/9182 [29:38<12:27,  2.65it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7204/9182 [29:38<10:34,  3.12it/s]
 78%|█████████████████████████████████████████████████████████████▏                | 7207/9182 [29:39<05:34,  5.90it/s]
 79%|█████████████████████████████████████████████████████████████▏                | 7208/9182 [29:39<07:26,  4.42it/s]
 79%|█████████████████████████████████████████████████████████████▏                | 7209/9182 [29:39<06:51,  4.80it/s]
 79%|█████████████████████████████████████████████████████████████▏                | 7210/9182 [29:39<06:59,  4.70it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7211/9182 [29:40<08:21,  3.93it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7212/9182 [29:40<08:48,  3.73it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7214/9182 [29:40<05:40,  5.78it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7215/9182 [29:40<06:22,  5.14it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7216/9182 [29:40<05:48,  5.65it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7217/9182 [29:41<05:23,  6.08it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7218/9182 [29:41<06:15,  5.24it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7219/9182 [29:41<05:38,  5.80it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7220/9182 [29:41<06:11,  5.28it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7221/9182 [29:41<05:41,  5.75it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7222/9182 [29:42<05:56,  5.49it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7223/9182 [29:42<06:25,  5.08it/s]
 79%|█████████████████████████████████████████████████████████████▎                | 7224/9182 [29:42<05:56,  5.49it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7225/9182 [29:43<08:40,  3.76it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7226/9182 [29:43<12:24,  2.63it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7227/9182 [29:44<12:14,  2.66it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7228/9182 [29:44<12:57,  2.51it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7229/9182 [29:44<11:17,  2.88it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7230/9182 [29:44<09:07,  3.57it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7232/9182 [29:44<05:43,  5.68it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7233/9182 [29:44<05:10,  6.29it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7236/9182 [29:45<03:44,  8.67it/s]
 79%|█████████████████████████████████████████████████████████████▍                | 7238/9182 [29:45<03:36,  8.96it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7240/9182 [29:45<05:13,  6.19it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7241/9182 [29:46<04:58,  6.49it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7242/9182 [29:46<04:50,  6.67it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7243/9182 [29:47<09:19,  3.46it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7244/9182 [29:47<11:38,  2.77it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7245/9182 [29:48<10:26,  3.09it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7246/9182 [29:48<15:26,  2.09it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7247/9182 [29:49<16:19,  1.98it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7248/9182 [29:50<16:29,  1.95it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7249/9182 [29:50<17:57,  1.79it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7250/9182 [29:50<16:15,  1.98it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7251/9182 [29:51<13:42,  2.35it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7252/9182 [29:51<13:39,  2.35it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7253/9182 [29:51<11:56,  2.69it/s]
 79%|█████████████████████████████████████████████████████████████▌                | 7254/9182 [29:51<09:33,  3.36it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7255/9182 [29:52<07:53,  4.07it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7256/9182 [29:52<12:13,  2.63it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7257/9182 [29:52<11:22,  2.82it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7259/9182 [29:53<09:07,  3.51it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7260/9182 [29:54<11:08,  2.88it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7261/9182 [29:54<12:46,  2.51it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7262/9182 [29:54<10:18,  3.11it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7263/9182 [29:55<17:20,  1.84it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7264/9182 [29:55<14:08,  2.26it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7265/9182 [29:56<14:04,  2.27it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7266/9182 [29:56<13:24,  2.38it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7267/9182 [29:56<10:51,  2.94it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7268/9182 [29:57<09:19,  3.42it/s]
 79%|█████████████████████████████████████████████████████████████▋                | 7269/9182 [29:58<19:08,  1.67it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7270/9182 [29:58<16:23,  1.94it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7271/9182 [29:59<16:30,  1.93it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7272/9182 [29:59<15:31,  2.05it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7273/9182 [30:00<19:28,  1.63it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7276/9182 [30:00<09:12,  3.45it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7277/9182 [30:01<08:53,  3.57it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7278/9182 [30:01<11:05,  2.86it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7279/9182 [30:02<12:00,  2.64it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7280/9182 [30:02<11:35,  2.74it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7281/9182 [30:02<12:37,  2.51it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7282/9182 [30:03<14:42,  2.15it/s]
 79%|█████████████████████████████████████████████████████████████▊                | 7283/9182 [30:03<13:03,  2.42it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7285/9182 [30:03<08:12,  3.85it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7286/9182 [30:03<08:02,  3.93it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7287/9182 [30:04<08:48,  3.59it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7288/9182 [30:06<23:27,  1.35it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7289/9182 [30:06<19:30,  1.62it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7290/9182 [30:07<17:20,  1.82it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7291/9182 [30:07<15:58,  1.97it/s]

 79%|█████████████████████████████████████████████████████████████▉                | 7292/9182 [30:07<13:16,  2.37it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7293/9182 [30:08<12:12,  2.58it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7294/9182 [30:08<10:53,  2.89it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7295/9182 [30:08<09:16,  3.39it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7296/9182 [30:08<09:00,  3.49it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7297/9182 [30:09<13:16,  2.37it/s]
 79%|█████████████████████████████████████████████████████████████▉                | 7298/9182 [30:09<12:57,  2.42it/s]
 79%|██████████████████████████████████████████████████████████████                | 7299/9182 [30:09<11:24,  2.75it/s]
 80%|██████████████████████████████████████████████████████████████                | 7300/9182 [30:10<14:50,  2.11it/s]
 80%|██████████████████████████████████████████████████████████████                | 7301/9182 [30:10<12:48,  2.45it/s]
 80%|██████████████████████████████████████████████████████████████                | 7302/9182 [30:11<13:24,  2.34it/s]
 80%|██████████████████████████████████████████████████████████████                | 7303/9182 [30:11<12:09,  2.58it/s]
 80%|██████████████████████████████████████████████████████████████                | 7304/9182 [30:12<10:27,  2.99it/s]
 80%|██████████████████████████████████████████████████████████████                | 7305/9182 [30:12<11:08,  2.81it/s]
 80%|██████████████████████████████████████████████████████████████                | 7306/9182 [30:12<12:14,  2.55it/s]
 80%|██████████████████████████████████████████████████████████████                | 7307/9182 [30:13<13:31,  2.31it/s]
 80%|██████████████████████████████████████████████████████████████                | 7308/9182 [30:14<20:30,  1.52it/s]
 80%|██████████████████████████████████████████████████████████████                | 7309/9182 [30:14<16:52,  1.85it/s]
 80%|██████████████████████████████████████████████████████████████                | 7310/9182 [30:15<19:19,  1.61it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7318/9182 [30:15<05:12,  5.97it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7319/9182 [30:16<07:27,  4.16it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7320/9182 [30:16<07:51,  3.95it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7321/9182 [30:17<07:25,  4.17it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7324/9182 [30:17<05:00,  6.18it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7325/9182 [30:17<05:10,  5.99it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7326/9182 [30:17<05:09,  6.00it/s]
 80%|██████████████████████████████████████████████████████████████▏               | 7327/9182 [30:18<07:36,  4.06it/s]
 80%|██████████████████████████████████████████████████████████████▎               | 7331/9182 [30:18<05:29,  5.61it/s]
 80%|██████████████████████████████████████████████████████████████▎               | 7332/9182 [30:19<05:41,  5.42it/s]
 80%|██████████████████████████████████████████████████████████████▎               | 7333/9182 [30:19<09:29,  3.25it/s]
 80%|██████████████████████████████████████████████████████████████▎               | 7334/9182 [30:20<10:37,  2.90it/s]
 80%|██████████████████████████████████████████████████████████████▎               | 7335/9182 [30:20<10:11,  3.02it/s]
 80%|██████████████████████████████████████████████████████████████▎               | 7339/9182 [30:20<04:48,  6.38it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7343/9182 [30:21<04:45,  6.45it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7346/9182 [30:21<05:02,  6.08it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7347/9182 [30:22<05:31,  5.53it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7349/9182 [30:22<05:52,  5.20it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7350/9182 [30:22<06:03,  5.04it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7351/9182 [30:23<06:48,  4.48it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7352/9182 [30:23<07:01,  4.34it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7353/9182 [30:24<09:32,  3.19it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7354/9182 [30:25<15:17,  1.99it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7355/9182 [30:26<19:04,  1.60it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7356/9182 [30:26<15:58,  1.91it/s]
 80%|██████████████████████████████████████████████████████████████▍               | 7357/9182 [30:27<19:42,  1.54it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7358/9182 [30:27<15:56,  1.91it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7359/9182 [30:27<12:11,  2.49it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7360/9182 [30:27<11:32,  2.63it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7361/9182 [30:28<10:52,  2.79it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7362/9182 [30:28<09:57,  3.05it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7364/9182 [30:28<08:27,  3.58it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7365/9182 [30:28<07:32,  4.02it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7366/9182 [30:29<11:34,  2.62it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7367/9182 [30:30<10:54,  2.77it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7368/9182 [30:30<14:52,  2.03it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7369/9182 [30:31<12:32,  2.41it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7370/9182 [30:32<17:28,  1.73it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7371/9182 [30:32<16:42,  1.81it/s]
 80%|██████████████████████████████████████████████████████████████▌               | 7372/9182 [30:32<12:48,  2.35it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7375/9182 [30:33<10:38,  2.83it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7377/9182 [30:34<10:32,  2.85it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7378/9182 [30:35<12:26,  2.42it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7379/9182 [30:35<12:28,  2.41it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7380/9182 [30:35<11:23,  2.64it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7381/9182 [30:35<09:36,  3.12it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7382/9182 [30:35<08:30,  3.52it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7383/9182 [30:36<08:31,  3.51it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7384/9182 [30:36<06:58,  4.30it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7385/9182 [30:36<08:13,  3.64it/s]
 80%|██████████████████████████████████████████████████████████████▋               | 7386/9182 [30:36<06:51,  4.37it/s]
 80%|██████████████████████████████████████████████████████████████▊               | 7387/9182 [30:37<07:22,  4.06it/s]
 80%|██████████████████████████████████████████████████████████████▊               | 7389/9182 [30:37<06:39,  4.49it/s]
 80%|██████████████████████████████████████████████████████████████▊               | 7390/9182 [30:37<07:39,  3.90it/s]
 80%|██████████████████████████████████████████████████████████████▊               | 7391/9182 [30:38<12:19,  2.42it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7392/9182 [30:39<13:07,  2.27it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7393/9182 [30:40<15:41,  1.90it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7394/9182 [30:40<14:42,  2.03it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7395/9182 [30:40<12:56,  2.30it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7396/9182 [30:41<17:49,  1.67it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7397/9182 [30:42<15:05,  1.97it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7398/9182 [30:42<13:01,  2.28it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7399/9182 [30:42<10:03,  2.95it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7400/9182 [30:42<09:55,  2.99it/s]
 81%|██████████████████████████████████████████████████████████████▊               | 7401/9182 [30:44<22:19,  1.33it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7402/9182 [30:44<20:23,  1.45it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7403/9182 [30:45<15:24,  1.92it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7404/9182 [30:45<14:46,  2.01it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7405/9182 [30:45<12:07,  2.44it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7406/9182 [30:46<10:25,  2.84it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7407/9182 [30:46<10:16,  2.88it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7408/9182 [30:47<12:10,  2.43it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7409/9182 [30:47<12:06,  2.44it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7410/9182 [30:47<11:10,  2.64it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7411/9182 [30:48<13:22,  2.21it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7412/9182 [30:48<11:34,  2.55it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7413/9182 [30:48<11:48,  2.50it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7414/9182 [30:49<09:21,  3.15it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7415/9182 [30:49<09:10,  3.21it/s]
 81%|██████████████████████████████████████████████████████████████▉               | 7416/9182 [30:49<08:50,  3.33it/s]
 81%|███████████████████████████████████████████████████████████████               | 7417/9182 [30:49<07:18,  4.03it/s]
 81%|███████████████████████████████████████████████████████████████               | 7419/9182 [30:49<05:08,  5.72it/s]
 81%|███████████████████████████████████████████████████████████████               | 7420/9182 [30:50<07:27,  3.93it/s]
 81%|███████████████████████████████████████████████████████████████               | 7421/9182 [30:50<06:39,  4.41it/s]
 81%|███████████████████████████████████████████████████████████████               | 7422/9182 [30:50<07:37,  3.85it/s]
 81%|███████████████████████████████████████████████████████████████               | 7423/9182 [30:51<07:35,  3.86it/s]
 81%|███████████████████████████████████████████████████████████████               | 7424/9182 [30:51<06:48,  4.31it/s]
 81%|███████████████████████████████████████████████████████████████               | 7425/9182 [30:51<06:21,  4.60it/s]
 81%|███████████████████████████████████████████████████████████████               | 7426/9182 [30:51<05:41,  5.14it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7431/9182 [30:51<02:21, 12.36it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7433/9182 [30:52<02:36, 11.19it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7435/9182 [30:52<02:31, 11.50it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7437/9182 [30:53<05:30,  5.29it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7438/9182 [30:53<07:42,  3.77it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7439/9182 [30:53<07:14,  4.01it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7440/9182 [30:54<08:05,  3.59it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7441/9182 [30:54<08:01,  3.61it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7442/9182 [30:54<07:35,  3.82it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7443/9182 [30:54<07:12,  4.02it/s]
 81%|███████████████████████████████████████████████████████████████▏              | 7444/9182 [30:55<06:24,  4.52it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7448/9182 [30:55<03:08,  9.18it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7450/9182 [30:55<03:54,  7.40it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7453/9182 [30:55<03:48,  7.57it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7454/9182 [30:56<03:56,  7.31it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7455/9182 [30:57<12:45,  2.26it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7456/9182 [30:58<12:08,  2.37it/s]
 81%|███████████████████████████████████████████████████████████████▎              | 7460/9182 [31:00<14:07,  2.03it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7461/9182 [31:00<12:50,  2.23it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7463/9182 [31:00<09:18,  3.08it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7464/9182 [31:01<08:39,  3.30it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7465/9182 [31:01<09:12,  3.11it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7466/9182 [31:01<08:37,  3.32it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7467/9182 [31:02<07:19,  3.90it/s]

 81%|███████████████████████████████████████████████████████████████▍              | 7468/9182 [31:02<08:57,  3.19it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7469/9182 [31:02<09:51,  2.89it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7470/9182 [31:03<09:08,  3.12it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7471/9182 [31:03<11:33,  2.47it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7472/9182 [31:03<10:26,  2.73it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7473/9182 [31:04<11:57,  2.38it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7474/9182 [31:04<11:40,  2.44it/s]
 81%|███████████████████████████████████████████████████████████████▍              | 7475/9182 [31:05<09:57,  2.86it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7476/9182 [31:05<09:59,  2.85it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7477/9182 [31:06<14:39,  1.94it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7478/9182 [31:06<11:54,  2.39it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7479/9182 [31:07<14:35,  1.95it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7480/9182 [31:07<15:09,  1.87it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7481/9182 [31:08<15:52,  1.79it/s]
 81%|███████████████████████████████████████████████████████████████▌              | 7482/9182 [31:08<12:31,  2.26it/s]
 82%|███████████████████████████████████████████████████████████████▌              | 7485/9182 [31:10<13:48,  2.05it/s]
 82%|███████████████████████████████████████████████████████████████▌              | 7486/9182 [31:10<14:06,  2.00it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7496/9182 [31:11<04:40,  6.00it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7497/9182 [31:11<05:49,  4.82it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7498/9182 [31:12<07:29,  3.75it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7499/9182 [31:12<06:55,  4.05it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7500/9182 [31:13<08:33,  3.27it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7501/9182 [31:13<10:18,  2.72it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7502/9182 [31:13<08:53,  3.15it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7503/9182 [31:15<14:07,  1.98it/s]
 82%|███████████████████████████████████████████████████████████████▋              | 7504/9182 [31:15<12:10,  2.30it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7505/9182 [31:15<10:31,  2.65it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7506/9182 [31:15<09:53,  2.82it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7508/9182 [31:16<10:06,  2.76it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7509/9182 [31:16<08:39,  3.22it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7511/9182 [31:17<07:46,  3.58it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7512/9182 [31:18<10:59,  2.53it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7513/9182 [31:18<11:24,  2.44it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7514/9182 [31:19<15:05,  1.84it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7515/9182 [31:19<14:22,  1.93it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7516/9182 [31:19<11:41,  2.37it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7517/9182 [31:20<10:58,  2.53it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7518/9182 [31:21<18:16,  1.52it/s]
 82%|███████████████████████████████████████████████████████████████▊              | 7519/9182 [31:21<15:04,  1.84it/s]
 82%|███████████████████████████████████████████████████████████████▉              | 7522/9182 [31:23<12:58,  2.13it/s]
 82%|███████████████████████████████████████████████████████████████▉              | 7527/9182 [31:23<07:38,  3.61it/s]
 82%|███████████████████████████████████████████████████████████████▉              | 7528/9182 [31:24<07:36,  3.62it/s]
 82%|███████████████████████████████████████████████████████████████▉              | 7529/9182 [31:24<06:54,  3.99it/s]
 82%|███████████████████████████████████████████████████████████████▉              | 7530/9182 [31:24<06:50,  4.03it/s]
 82%|████████████████████████████████████████████████████████████████              | 7538/9182 [31:24<02:26, 11.26it/s]
 82%|████████████████████████████████████████████████████████████████              | 7541/9182 [31:24<02:39, 10.27it/s]
 82%|████████████████████████████████████████████████████████████████              | 7543/9182 [31:25<03:59,  6.84it/s]
 82%|████████████████████████████████████████████████████████████████              | 7545/9182 [31:26<05:15,  5.20it/s]
 82%|████████████████████████████████████████████████████████████████              | 7547/9182 [31:26<05:01,  5.42it/s]
 82%|████████████████████████████████████████████████████████████████              | 7548/9182 [31:27<06:15,  4.35it/s]
 82%|████████████████████████████████████████████████████████████████▏             | 7549/9182 [31:27<07:17,  3.73it/s]
 82%|████████████████████████████████████████████████████████████████▏             | 7550/9182 [31:27<07:24,  3.67it/s]
 82%|████████████████████████████████████████████████████████████████▏             | 7551/9182 [31:27<06:38,  4.09it/s]
 82%|████████████████████████████████████████████████████████████████▏             | 7552/9182 [31:28<06:43,  4.04it/s]
 82%|████████████████████████████████████████████████████████████████▏             | 7562/9182 [31:29<04:36,  5.85it/s]
 82%|████████████████████████████████████████████████████████████████▏             | 7563/9182 [31:30<06:03,  4.45it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7564/9182 [31:30<06:54,  3.90it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7565/9182 [31:31<06:36,  4.08it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7566/9182 [31:31<07:29,  3.59it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7567/9182 [31:32<09:53,  2.72it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7568/9182 [31:32<09:09,  2.93it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7569/9182 [31:32<08:19,  3.23it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7570/9182 [31:32<08:24,  3.20it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7571/9182 [31:33<08:38,  3.11it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7572/9182 [31:33<08:27,  3.17it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7574/9182 [31:34<07:48,  3.43it/s]
 82%|████████████████████████████████████████████████████████████████▎             | 7575/9182 [31:34<07:15,  3.69it/s]
 83%|████████████████████████████████████████████████████████████████▎             | 7576/9182 [31:35<09:58,  2.68it/s]
 83%|████████████████████████████████████████████████████████████████▎             | 7577/9182 [31:35<10:26,  2.56it/s]
 83%|████████████████████████████████████████████████████████████████▎             | 7578/9182 [31:36<12:41,  2.11it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7579/9182 [31:36<13:04,  2.04it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7581/9182 [31:39<19:18,  1.38it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7582/9182 [31:39<17:45,  1.50it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7583/9182 [31:39<14:54,  1.79it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7584/9182 [31:40<15:31,  1.72it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7585/9182 [31:40<13:44,  1.94it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7586/9182 [31:41<12:45,  2.08it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7587/9182 [31:41<12:29,  2.13it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7588/9182 [31:41<11:58,  2.22it/s]
 83%|████████████████████████████████████████████████████████████████▍             | 7592/9182 [31:41<05:24,  4.91it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7593/9182 [31:42<05:18,  5.00it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7594/9182 [31:43<10:01,  2.64it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7599/9182 [31:43<05:34,  4.73it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7600/9182 [31:44<06:59,  3.77it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7601/9182 [31:44<07:50,  3.36it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7602/9182 [31:45<09:40,  2.72it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7605/9182 [31:45<07:35,  3.46it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7606/9182 [31:46<09:37,  2.73it/s]
 83%|████████████████████████████████████████████████████████████████▌             | 7607/9182 [31:47<09:13,  2.85it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7608/9182 [31:47<10:12,  2.57it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7609/9182 [31:48<12:23,  2.12it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7610/9182 [31:49<15:24,  1.70it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7611/9182 [31:49<14:31,  1.80it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7612/9182 [31:49<11:48,  2.22it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7613/9182 [31:50<11:50,  2.21it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7614/9182 [31:51<14:58,  1.75it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7615/9182 [31:51<13:39,  1.91it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7616/9182 [31:52<13:46,  1.89it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7617/9182 [31:53<15:31,  1.68it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7618/9182 [31:53<16:40,  1.56it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7619/9182 [31:53<12:39,  2.06it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7620/9182 [31:53<10:02,  2.59it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7621/9182 [31:54<09:10,  2.84it/s]
 83%|████████████████████████████████████████████████████████████████▋             | 7622/9182 [31:54<09:48,  2.65it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7623/9182 [31:54<08:12,  3.16it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7624/9182 [31:55<08:11,  3.17it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7625/9182 [31:55<12:10,  2.13it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7626/9182 [31:56<10:26,  2.48it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7627/9182 [31:56<08:59,  2.88it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7628/9182 [31:56<10:52,  2.38it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7629/9182 [31:56<08:33,  3.02it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7630/9182 [31:57<07:19,  3.53it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7632/9182 [31:57<05:04,  5.09it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7634/9182 [31:57<05:21,  4.82it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7635/9182 [31:58<05:41,  4.53it/s]
 83%|████████████████████████████████████████████████████████████████▊             | 7636/9182 [31:58<07:25,  3.47it/s]
 83%|████████████████████████████████████████████████████████████████▉             | 7641/9182 [31:58<03:10,  8.07it/s]
 83%|████████████████████████████████████████████████████████████████▉             | 7643/9182 [31:58<03:23,  7.58it/s]
 83%|████████████████████████████████████████████████████████████████▉             | 7645/9182 [31:59<03:16,  7.82it/s]
 83%|████████████████████████████████████████████████████████████████▉             | 7649/9182 [31:59<02:07, 12.03it/s]
 83%|████████████████████████████████████████████████████████████████▉             | 7651/9182 [32:00<03:20,  7.62it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7653/9182 [32:00<05:24,  4.71it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7655/9182 [32:00<04:19,  5.88it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7657/9182 [32:02<07:29,  3.39it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7660/9182 [32:02<05:35,  4.54it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7661/9182 [32:02<06:13,  4.07it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7662/9182 [32:03<06:05,  4.15it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7663/9182 [32:03<06:20,  4.00it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7664/9182 [32:03<06:12,  4.08it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7665/9182 [32:04<07:19,  3.45it/s]
 83%|█████████████████████████████████████████████████████████████████             | 7666/9182 [32:04<06:23,  3.95it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7667/9182 [32:04<07:41,  3.28it/s]

 84%|█████████████████████████████████████████████████████████████████▏            | 7668/9182 [32:04<06:56,  3.64it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7669/9182 [32:05<07:23,  3.41it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7670/9182 [32:05<08:31,  2.96it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7674/9182 [32:06<05:49,  4.31it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7675/9182 [32:06<06:52,  3.65it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7676/9182 [32:07<11:10,  2.25it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7678/9182 [32:09<13:52,  1.81it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7679/9182 [32:09<12:04,  2.07it/s]
 84%|█████████████████████████████████████████████████████████████████▏            | 7680/9182 [32:11<19:16,  1.30it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7689/9182 [32:12<06:55,  3.60it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7690/9182 [32:12<07:12,  3.45it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7691/9182 [32:13<07:37,  3.26it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7692/9182 [32:14<10:39,  2.33it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7693/9182 [32:14<11:25,  2.17it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7694/9182 [32:15<10:42,  2.32it/s]
 84%|█████████████████████████████████████████████████████████████████▎            | 7695/9182 [32:15<11:13,  2.21it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7696/9182 [32:16<11:34,  2.14it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7697/9182 [32:16<09:26,  2.62it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7698/9182 [32:16<08:06,  3.05it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7699/9182 [32:16<07:42,  3.21it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7700/9182 [32:17<08:49,  2.80it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7701/9182 [32:17<09:15,  2.67it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7702/9182 [32:18<13:03,  1.89it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7706/9182 [32:20<13:31,  1.82it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7707/9182 [32:21<11:42,  2.10it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7708/9182 [32:21<12:23,  1.98it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7709/9182 [32:21<11:23,  2.15it/s]
 84%|█████████████████████████████████████████████████████████████████▍            | 7710/9182 [32:22<09:25,  2.60it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7711/9182 [32:22<08:11,  2.99it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7712/9182 [32:22<08:16,  2.96it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7713/9182 [32:22<07:06,  3.44it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7714/9182 [32:23<06:42,  3.65it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7715/9182 [32:23<07:59,  3.06it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7716/9182 [32:24<09:39,  2.53it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7717/9182 [32:24<11:08,  2.19it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7718/9182 [32:24<09:17,  2.63it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7719/9182 [32:25<08:57,  2.72it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7720/9182 [32:25<07:01,  3.47it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7721/9182 [32:25<06:17,  3.87it/s]
 84%|█████████████████████████████████████████████████████████████████▌            | 7722/9182 [32:26<11:21,  2.14it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7728/9182 [32:26<03:37,  6.68it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7730/9182 [32:29<10:39,  2.27it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7732/9182 [32:29<09:08,  2.64it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7733/9182 [32:29<08:48,  2.74it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7734/9182 [32:31<13:30,  1.79it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7735/9182 [32:31<12:42,  1.90it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7736/9182 [32:31<10:27,  2.31it/s]
 84%|█████████████████████████████████████████████████████████████████▋            | 7739/9182 [32:31<05:47,  4.15it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7741/9182 [32:32<06:36,  3.63it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7748/9182 [32:33<04:01,  5.95it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7749/9182 [32:33<04:36,  5.18it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7750/9182 [32:33<04:26,  5.38it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7751/9182 [32:34<05:06,  4.67it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7752/9182 [32:34<04:55,  4.84it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7753/9182 [32:34<05:25,  4.39it/s]
 84%|█████████████████████████████████████████████████████████████████▊            | 7754/9182 [32:34<04:47,  4.97it/s]
 84%|█████████████████████████████████████████████████████████████████▉            | 7755/9182 [32:35<04:54,  4.85it/s]
 84%|█████████████████████████████████████████████████████████████████▉            | 7756/9182 [32:35<05:34,  4.27it/s]
 84%|█████████████████████████████████████████████████████████████████▉            | 7757/9182 [32:35<05:20,  4.45it/s]
 84%|█████████████████████████████████████████████████████████████████▉            | 7758/9182 [32:36<06:53,  3.44it/s]
 85%|█████████████████████████████████████████████████████████████████▉            | 7759/9182 [32:36<06:25,  3.69it/s]
 85%|█████████████████████████████████████████████████████████████████▉            | 7760/9182 [32:36<07:15,  3.26it/s]
 85%|█████████████████████████████████████████████████████████████████▉            | 7761/9182 [32:36<07:49,  3.03it/s]
 85%|█████████████████████████████████████████████████████████████████▉            | 7766/9182 [32:37<02:55,  8.05it/s]
 85%|█████████████████████████████████████████████████████████████████▉            | 7768/9182 [32:37<03:32,  6.66it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7770/9182 [32:37<03:17,  7.13it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7772/9182 [32:38<03:51,  6.09it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7773/9182 [32:38<04:27,  5.26it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7774/9182 [32:38<04:42,  4.99it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7775/9182 [32:39<07:13,  3.25it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7776/9182 [32:40<07:47,  3.01it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7777/9182 [32:40<11:21,  2.06it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7778/9182 [32:40<09:14,  2.53it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7779/9182 [32:41<08:24,  2.78it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7780/9182 [32:41<09:29,  2.46it/s]
 85%|██████████████████████████████████████████████████████████████████            | 7781/9182 [32:45<31:18,  1.34s/it]
 85%|██████████████████████████████████████████████████████████████████            | 7782/9182 [32:45<23:15,  1.00it/s]
 85%|██████████████████████████████████████████████████████████████████▏           | 7792/9182 [32:45<05:04,  4.56it/s]
 85%|██████████████████████████████████████████████████████████████████▏           | 7794/9182 [32:46<05:19,  4.34it/s]
 85%|██████████████████████████████████████████████████████████████████▏           | 7795/9182 [32:47<06:34,  3.51it/s]
 85%|██████████████████████████████████████████████████████████████████▏           | 7796/9182 [32:49<12:18,  1.88it/s]
 85%|██████████████████████████████████████████████████████████████████▏           | 7797/9182 [32:49<11:54,  1.94it/s]
 85%|██████████████████████████████████████████████████████████████████▏           | 7798/9182 [32:50<12:18,  1.88it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7799/9182 [32:50<12:27,  1.85it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7804/9182 [32:50<05:21,  4.29it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7806/9182 [32:52<07:15,  3.16it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7807/9182 [32:52<09:42,  2.36it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7808/9182 [32:54<11:34,  1.98it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7809/9182 [32:55<15:20,  1.49it/s]
 85%|██████████████████████████████████████████████████████████████████▎           | 7813/9182 [32:58<16:29,  1.38it/s]
 85%|██████████████████████████████████████████████████████████████████▍           | 7814/9182 [32:58<14:25,  1.58it/s]
 85%|██████████████████████████████████████████████████████████████████▍           | 7815/9182 [32:59<15:11,  1.50it/s]
 85%|██████████████████████████████████████████████████████████████████▍           | 7816/9182 [32:59<13:11,  1.72it/s]
 85%|██████████████████████████████████████████████████████████████████▍           | 7823/9182 [32:59<04:35,  4.93it/s]
 85%|██████████████████████████████████████████████████████████████████▍           | 7826/9182 [33:00<03:51,  5.86it/s]
 85%|██████████████████████████████████████████████████████████████████▍           | 7828/9182 [33:00<04:36,  4.90it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7830/9182 [33:02<09:36,  2.35it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7831/9182 [33:03<09:38,  2.34it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7832/9182 [33:04<11:09,  2.02it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7833/9182 [33:04<09:55,  2.26it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7834/9182 [33:04<08:55,  2.52it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7835/9182 [33:05<09:04,  2.47it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7836/9182 [33:05<08:47,  2.55it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7837/9182 [33:05<08:18,  2.70it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7838/9182 [33:07<15:08,  1.48it/s]
 85%|██████████████████████████████████████████████████████████████████▌           | 7839/9182 [33:07<11:54,  1.88it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7844/9182 [33:07<05:30,  4.05it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7845/9182 [33:08<06:07,  3.63it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7846/9182 [33:08<05:46,  3.85it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7847/9182 [33:09<06:43,  3.31it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7848/9182 [33:09<06:25,  3.46it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7849/9182 [33:09<05:44,  3.87it/s]
 85%|██████████████████████████████████████████████████████████████████▋           | 7850/9182 [33:09<05:23,  4.12it/s]
 86%|██████████████████████████████████████████████████████████████████▋           | 7851/9182 [33:09<05:04,  4.37it/s]
 86%|██████████████████████████████████████████████████████████████████▋           | 7852/9182 [33:10<04:33,  4.85it/s]
 86%|██████████████████████████████████████████████████████████████████▋           | 7853/9182 [33:10<05:16,  4.19it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7863/9182 [33:11<02:54,  7.56it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7864/9182 [33:12<03:50,  5.71it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7865/9182 [33:12<04:36,  4.76it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7866/9182 [33:12<04:36,  4.77it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7867/9182 [33:13<06:57,  3.15it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7868/9182 [33:13<06:41,  3.28it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7869/9182 [33:13<06:15,  3.50it/s]
 86%|██████████████████████████████████████████████████████████████████▊           | 7872/9182 [33:13<03:34,  6.11it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7874/9182 [33:14<04:33,  4.78it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7875/9182 [33:14<04:48,  4.53it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7876/9182 [33:15<06:57,  3.13it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7877/9182 [33:15<07:02,  3.09it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7878/9182 [33:16<07:42,  2.82it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7879/9182 [33:16<08:48,  2.47it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7880/9182 [33:17<08:00,  2.71it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7881/9182 [33:17<07:18,  2.96it/s]

 86%|██████████████████████████████████████████████████████████████████▉           | 7882/9182 [33:17<07:30,  2.89it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7883/9182 [33:18<08:11,  2.64it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7884/9182 [33:18<09:38,  2.24it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7885/9182 [33:19<08:09,  2.65it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7886/9182 [33:19<08:55,  2.42it/s]
 86%|██████████████████████████████████████████████████████████████████▉           | 7887/9182 [33:19<09:04,  2.38it/s]
 86%|███████████████████████████████████████████████████████████████████           | 7891/9182 [33:20<04:51,  4.42it/s]
 86%|███████████████████████████████████████████████████████████████████           | 7892/9182 [33:23<18:28,  1.16it/s]
 86%|███████████████████████████████████████████████████████████████████           | 7893/9182 [33:24<15:42,  1.37it/s]
 86%|███████████████████████████████████████████████████████████████████           | 7894/9182 [33:24<13:16,  1.62it/s]
 86%|███████████████████████████████████████████████████████████████████           | 7900/9182 [33:25<06:50,  3.12it/s]
 86%|███████████████████████████████████████████████████████████████████           | 7901/9182 [33:25<06:44,  3.17it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7902/9182 [33:26<07:07,  2.99it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7903/9182 [33:26<07:52,  2.70it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7904/9182 [33:27<06:42,  3.17it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7905/9182 [33:27<07:09,  2.97it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7906/9182 [33:27<06:50,  3.11it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7907/9182 [33:27<06:28,  3.28it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7908/9182 [33:28<07:15,  2.93it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7909/9182 [33:28<06:51,  3.09it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7910/9182 [33:29<07:57,  2.67it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7911/9182 [33:29<06:45,  3.13it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7912/9182 [33:29<07:26,  2.85it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7913/9182 [33:30<08:09,  2.59it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7914/9182 [33:31<14:48,  1.43it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7915/9182 [33:31<12:16,  1.72it/s]
 86%|███████████████████████████████████████████████████████████████████▏          | 7916/9182 [33:31<09:23,  2.25it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7918/9182 [33:33<12:02,  1.75it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7919/9182 [33:34<17:06,  1.23it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7920/9182 [33:35<13:40,  1.54it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7923/9182 [33:36<13:22,  1.57it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7924/9182 [33:37<11:21,  1.84it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7925/9182 [33:37<09:33,  2.19it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7926/9182 [33:38<09:51,  2.12it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7927/9182 [33:38<08:55,  2.34it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7928/9182 [33:38<08:50,  2.36it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7929/9182 [33:39<09:06,  2.29it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7930/9182 [33:39<08:20,  2.50it/s]
 86%|███████████████████████████████████████████████████████████████████▎          | 7931/9182 [33:40<09:08,  2.28it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7932/9182 [33:40<08:37,  2.42it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7933/9182 [33:40<07:22,  2.82it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7934/9182 [33:40<06:30,  3.19it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7935/9182 [33:41<07:45,  2.68it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7936/9182 [33:41<06:58,  2.98it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7937/9182 [33:42<09:18,  2.23it/s]
 86%|███████████████████████████████████████████████████████████████████▍          | 7942/9182 [33:43<06:58,  2.96it/s]
 87%|███████████████████████████████████████████████████████████████████▍          | 7943/9182 [33:43<06:41,  3.08it/s]
 87%|███████████████████████████████████████████████████████████████████▍          | 7944/9182 [33:44<07:06,  2.91it/s]
 87%|███████████████████████████████████████████████████████████████████▍          | 7945/9182 [33:44<08:03,  2.56it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7949/9182 [33:45<06:04,  3.38it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7950/9182 [33:46<06:58,  2.95it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7951/9182 [33:46<06:51,  2.99it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7952/9182 [33:47<08:24,  2.44it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7953/9182 [33:47<07:31,  2.72it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7954/9182 [33:47<07:03,  2.90it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7955/9182 [33:48<07:36,  2.69it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7956/9182 [33:48<08:11,  2.50it/s]
 87%|███████████████████████████████████████████████████████████████████▌          | 7957/9182 [33:48<07:39,  2.66it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7963/9182 [33:49<02:36,  7.80it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7965/9182 [33:49<03:02,  6.68it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7967/9182 [33:49<02:36,  7.78it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7969/9182 [33:50<02:26,  8.27it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7971/9182 [33:51<05:57,  3.39it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7972/9182 [33:51<06:01,  3.35it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7973/9182 [33:52<06:15,  3.22it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7974/9182 [33:52<06:07,  3.29it/s]
 87%|███████████████████████████████████████████████████████████████████▋          | 7975/9182 [33:52<05:55,  3.40it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7980/9182 [33:53<03:29,  5.75it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7981/9182 [33:53<03:51,  5.19it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7982/9182 [33:54<05:39,  3.53it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7983/9182 [33:54<06:43,  2.97it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7984/9182 [33:55<08:24,  2.38it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7985/9182 [33:55<08:14,  2.42it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7986/9182 [33:56<08:43,  2.29it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7989/9182 [33:57<09:43,  2.04it/s]
 87%|███████████████████████████████████████████████████████████████████▊          | 7990/9182 [33:58<09:41,  2.05it/s]
 87%|███████████████████████████████████████████████████████████████████▉          | 7991/9182 [33:59<08:28,  2.34it/s]
 87%|███████████████████████████████████████████████████████████████████▉          | 7992/9182 [33:59<09:59,  1.98it/s]
 87%|███████████████████████████████████████████████████████████████████▉          | 7993/9182 [33:59<09:33,  2.07it/s]
 87%|███████████████████████████████████████████████████████████████████▉          | 7998/9182 [34:01<08:32,  2.31it/s]
 87%|███████████████████████████████████████████████████████████████████▉          | 8000/9182 [34:04<12:32,  1.57it/s]
 87%|███████████████████████████████████████████████████████████████████▉          | 8001/9182 [34:04<11:09,  1.76it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8007/9182 [34:04<05:04,  3.86it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8009/9182 [34:04<04:20,  4.51it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8011/9182 [34:05<06:14,  3.12it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8012/9182 [34:07<08:27,  2.31it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8013/9182 [34:07<08:49,  2.21it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8014/9182 [34:08<08:36,  2.26it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8015/9182 [34:08<07:27,  2.61it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8017/9182 [34:10<14:23,  1.35it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8018/9182 [34:11<12:22,  1.57it/s]
 87%|████████████████████████████████████████████████████████████████████          | 8019/9182 [34:11<10:40,  1.82it/s]
 87%|████████████████████████████████████████████████████████████████████▏         | 8024/9182 [34:11<05:01,  3.84it/s]
 87%|████████████████████████████████████████████████████████████████████▏         | 8025/9182 [34:19<25:15,  1.31s/it]
 87%|████████████████████████████████████████████████████████████████████▏         | 8026/9182 [34:19<21:38,  1.12s/it]
 87%|████████████████████████████████████████████████████████████████████▏         | 8027/9182 [34:19<17:39,  1.09it/s]
 87%|████████████████████████████████████████████████████████████████████▏         | 8028/9182 [34:19<14:47,  1.30it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8037/9182 [34:21<06:43,  2.84it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8038/9182 [34:22<07:01,  2.72it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8039/9182 [34:22<07:13,  2.63it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8040/9182 [34:22<07:04,  2.69it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8041/9182 [34:23<06:44,  2.82it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8042/9182 [34:23<06:12,  3.06it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8043/9182 [34:23<06:19,  3.00it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8044/9182 [34:23<06:07,  3.10it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8045/9182 [34:24<05:47,  3.27it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8046/9182 [34:24<05:29,  3.44it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8047/9182 [34:25<06:57,  2.72it/s]
 88%|████████████████████████████████████████████████████████████████████▎         | 8048/9182 [34:25<08:09,  2.32it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8049/9182 [34:25<07:04,  2.67it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8050/9182 [34:26<07:11,  2.62it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8051/9182 [34:26<06:11,  3.05it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8052/9182 [34:26<05:07,  3.67it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8053/9182 [34:26<05:07,  3.67it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8054/9182 [34:27<04:31,  4.16it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8055/9182 [34:27<04:11,  4.48it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8056/9182 [34:27<03:57,  4.74it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8057/9182 [34:28<04:18,  4.36it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8058/9182 [34:28<05:47,  3.23it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8059/9182 [34:28<05:21,  3.50it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8060/9182 [34:29<06:30,  2.87it/s]
 88%|████████████████████████████████████████████████████████████████████▍         | 8061/9182 [34:29<06:39,  2.80it/s]
 88%|████████████████████████████████████████████████████████████████████▌         | 8069/9182 [34:29<01:48, 10.27it/s]
 88%|████████████████████████████████████████████████████████████████████▌         | 8071/9182 [34:29<02:08,  8.68it/s]
 88%|████████████████████████████████████████████████████████████████████▌         | 8073/9182 [34:30<02:34,  7.18it/s]
 88%|████████████████████████████████████████████████████████████████████▌         | 8075/9182 [34:30<02:13,  8.28it/s]
 88%|████████████████████████████████████████████████████████████████████▌         | 8077/9182 [34:31<03:42,  4.96it/s]
 88%|████████████████████████████████████████████████████████████████████▌         | 8078/9182 [34:31<04:43,  3.90it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8079/9182 [34:32<05:52,  3.13it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8080/9182 [34:32<05:39,  3.25it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8081/9182 [34:33<06:54,  2.65it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8082/9182 [34:33<06:05,  3.01it/s]

 88%|████████████████████████████████████████████████████████████████████▋         | 8083/9182 [34:33<05:07,  3.57it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8084/9182 [34:33<04:47,  3.81it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8085/9182 [34:34<04:32,  4.02it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8086/9182 [34:34<05:14,  3.49it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8087/9182 [34:35<05:01,  3.63it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8088/9182 [34:35<08:50,  2.06it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8089/9182 [34:36<12:19,  1.48it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8090/9182 [34:37<10:26,  1.74it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8091/9182 [34:37<08:51,  2.05it/s]
 88%|████████████████████████████████████████████████████████████████████▋         | 8092/9182 [34:37<08:02,  2.26it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8097/9182 [34:38<03:26,  5.27it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8098/9182 [34:38<04:36,  3.92it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8099/9182 [34:39<05:50,  3.09it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8100/9182 [34:40<07:34,  2.38it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8101/9182 [34:40<06:42,  2.69it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8102/9182 [34:41<08:06,  2.22it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8103/9182 [34:41<08:04,  2.23it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8104/9182 [34:41<06:48,  2.64it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8105/9182 [34:41<06:07,  2.93it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8106/9182 [34:42<06:22,  2.81it/s]
 88%|████████████████████████████████████████████████████████████████████▊         | 8107/9182 [34:42<07:15,  2.47it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8108/9182 [34:43<06:55,  2.58it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8109/9182 [34:43<07:42,  2.32it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8110/9182 [34:44<06:53,  2.60it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8111/9182 [34:44<07:26,  2.40it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8112/9182 [34:44<06:25,  2.77it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8113/9182 [34:44<06:13,  2.86it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8114/9182 [34:45<05:20,  3.33it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8115/9182 [34:45<06:14,  2.85it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8116/9182 [34:47<15:06,  1.18it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8117/9182 [34:47<12:57,  1.37it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8118/9182 [34:48<10:12,  1.74it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8119/9182 [34:49<11:28,  1.54it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8120/9182 [34:50<12:28,  1.42it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8121/9182 [34:50<10:45,  1.64it/s]
 88%|████████████████████████████████████████████████████████████████████▉         | 8122/9182 [34:50<09:38,  1.83it/s]
 88%|█████████████████████████████████████████████████████████████████████         | 8123/9182 [34:50<07:36,  2.32it/s]
 88%|█████████████████████████████████████████████████████████████████████         | 8124/9182 [34:51<06:04,  2.91it/s]
 88%|█████████████████████████████████████████████████████████████████████         | 8125/9182 [34:51<07:28,  2.36it/s]
 88%|█████████████████████████████████████████████████████████████████████         | 8126/9182 [34:52<07:18,  2.41it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8127/9182 [34:52<07:43,  2.27it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8128/9182 [34:52<06:34,  2.67it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8129/9182 [34:53<07:24,  2.37it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8130/9182 [34:53<06:05,  2.88it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8131/9182 [34:54<07:19,  2.39it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8132/9182 [34:54<07:56,  2.21it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8133/9182 [34:54<06:42,  2.61it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8134/9182 [34:58<21:38,  1.24s/it]
 89%|█████████████████████████████████████████████████████████████████████         | 8135/9182 [34:58<15:54,  1.10it/s]
 89%|█████████████████████████████████████████████████████████████████████         | 8136/9182 [34:58<13:03,  1.34it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8141/9182 [35:01<11:27,  1.51it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8142/9182 [35:01<09:58,  1.74it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8143/9182 [35:01<08:47,  1.97it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8144/9182 [35:02<07:42,  2.24it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8145/9182 [35:02<06:48,  2.54it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8146/9182 [35:02<06:35,  2.62it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8147/9182 [35:03<05:42,  3.02it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8148/9182 [35:03<05:30,  3.13it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8149/9182 [35:03<05:56,  2.90it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8150/9182 [35:04<06:15,  2.75it/s]
 89%|█████████████████████████████████████████████████████████████████████▏        | 8151/9182 [35:04<05:03,  3.40it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8152/9182 [35:04<06:20,  2.71it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8157/9182 [35:04<02:20,  7.30it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8159/9182 [35:06<04:36,  3.69it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8161/9182 [35:07<06:19,  2.69it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8162/9182 [35:08<06:26,  2.64it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8163/9182 [35:08<08:07,  2.09it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8164/9182 [35:08<07:21,  2.30it/s]
 89%|█████████████████████████████████████████████████████████████████████▎        | 8165/9182 [35:08<06:04,  2.79it/s]
 89%|█████████████████████████████████████████████████████████████████████▍        | 8167/9182 [35:09<05:53,  2.87it/s]
 89%|█████████████████████████████████████████████████████████████████████▍        | 8168/9182 [35:10<05:51,  2.89it/s]
 89%|█████████████████████████████████████████████████████████████████████▍        | 8169/9182 [35:10<06:22,  2.65it/s]
 89%|█████████████████████████████████████████████████████████████████████▍        | 8170/9182 [35:10<05:29,  3.07it/s]
 89%|█████████████████████████████████████████████████████████████████████▍        | 8171/9182 [35:11<05:08,  3.27it/s]
 89%|█████████████████████████████████████████████████████████████████████▍        | 8172/9182 [35:11<04:27,  3.78it/s]
 89%|█████████████████████████████████████████████████████████████████████▌        | 8184/9182 [35:14<04:31,  3.67it/s]
 89%|█████████████████████████████████████████████████████████████████████▌        | 8185/9182 [35:14<04:51,  3.42it/s]
 89%|█████████████████████████████████████████████████████████████████████▌        | 8186/9182 [35:15<04:50,  3.43it/s]
 89%|█████████████████████████████████████████████████████████████████████▌        | 8187/9182 [35:15<04:29,  3.70it/s]
 89%|█████████████████████████████████████████████████████████████████████▌        | 8195/9182 [35:16<02:13,  7.41it/s]
 89%|█████████████████████████████████████████████████████████████████████▌        | 8196/9182 [35:16<02:46,  5.91it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8197/9182 [35:17<04:02,  4.07it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8198/9182 [35:17<04:43,  3.47it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8199/9182 [35:18<05:25,  3.02it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8200/9182 [35:18<04:55,  3.33it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8201/9182 [35:18<05:13,  3.12it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8202/9182 [35:19<04:40,  3.49it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8203/9182 [35:19<05:35,  2.92it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8204/9182 [35:19<05:36,  2.91it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8205/9182 [35:20<05:37,  2.90it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8206/9182 [35:20<07:35,  2.14it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8207/9182 [35:21<06:07,  2.65it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8208/9182 [35:21<06:38,  2.45it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8209/9182 [35:22<08:21,  1.94it/s]
 89%|█████████████████████████████████████████████████████████████████████▋        | 8210/9182 [35:22<06:53,  2.35it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8211/9182 [35:22<07:07,  2.27it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8212/9182 [35:23<07:20,  2.20it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8213/9182 [35:24<09:18,  1.73it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8214/9182 [35:24<08:07,  1.99it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8215/9182 [35:25<08:40,  1.86it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8216/9182 [35:25<07:34,  2.12it/s]
 89%|█████████████████████████████████████████████████████████████████████▊        | 8217/9182 [35:25<06:21,  2.53it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8218/9182 [35:25<05:45,  2.79it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8219/9182 [35:26<06:07,  2.62it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8220/9182 [35:26<04:48,  3.33it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8221/9182 [35:28<12:43,  1.26it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8222/9182 [35:28<09:53,  1.62it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8223/9182 [35:29<09:54,  1.61it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8224/9182 [35:29<08:03,  1.98it/s]
 90%|█████████████████████████████████████████████████████████████████████▊        | 8225/9182 [35:29<07:15,  2.20it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8226/9182 [35:30<06:59,  2.28it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8227/9182 [35:30<05:59,  2.65it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8228/9182 [35:30<05:18,  2.99it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8229/9182 [35:31<06:46,  2.34it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8230/9182 [35:31<05:48,  2.73it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8231/9182 [35:32<05:46,  2.74it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8232/9182 [35:32<05:25,  2.92it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8233/9182 [35:32<05:47,  2.73it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8234/9182 [35:33<07:57,  1.98it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8236/9182 [35:34<07:20,  2.15it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8237/9182 [35:35<11:56,  1.32it/s]
 90%|█████████████████████████████████████████████████████████████████████▉        | 8240/9182 [35:36<06:34,  2.39it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8241/9182 [35:37<07:23,  2.12it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8242/9182 [35:37<07:47,  2.01it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8243/9182 [35:37<07:04,  2.21it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8244/9182 [35:38<06:42,  2.33it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8245/9182 [35:38<07:12,  2.17it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8246/9182 [35:39<06:39,  2.34it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8247/9182 [35:41<14:10,  1.10it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8248/9182 [35:41<11:07,  1.40it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8249/9182 [35:41<09:57,  1.56it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8250/9182 [35:42<08:32,  1.82it/s]

 90%|██████████████████████████████████████████████████████████████████████        | 8251/9182 [35:42<07:12,  2.15it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8252/9182 [35:42<05:57,  2.60it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8253/9182 [35:42<04:38,  3.34it/s]
 90%|██████████████████████████████████████████████████████████████████████        | 8254/9182 [35:43<05:10,  2.99it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8255/9182 [35:43<04:46,  3.23it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8256/9182 [35:43<05:13,  2.96it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8257/9182 [35:44<05:41,  2.71it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8258/9182 [35:44<04:51,  3.17it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8259/9182 [35:47<18:12,  1.18s/it]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8260/9182 [35:48<14:35,  1.05it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8261/9182 [35:48<11:27,  1.34it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8262/9182 [35:48<08:58,  1.71it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8263/9182 [35:48<07:08,  2.15it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8264/9182 [35:49<05:54,  2.59it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8266/9182 [35:49<04:53,  3.12it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8267/9182 [35:50<04:36,  3.30it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8268/9182 [35:50<05:02,  3.02it/s]
 90%|██████████████████████████████████████████████████████████████████████▏       | 8269/9182 [35:50<05:10,  2.94it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8270/9182 [35:50<04:57,  3.07it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8272/9182 [35:50<03:09,  4.80it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8275/9182 [35:51<02:43,  5.54it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8276/9182 [35:51<03:23,  4.45it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8277/9182 [35:52<04:32,  3.32it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8281/9182 [35:52<02:30,  5.99it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8282/9182 [35:53<02:33,  5.88it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8283/9182 [35:53<03:02,  4.92it/s]
 90%|██████████████████████████████████████████████████████████████████████▎       | 8284/9182 [35:53<03:20,  4.48it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8285/9182 [35:53<03:51,  3.88it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8286/9182 [35:54<03:43,  4.01it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8287/9182 [35:54<04:18,  3.46it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8288/9182 [35:55<06:09,  2.42it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8289/9182 [35:55<04:52,  3.05it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8290/9182 [35:55<04:04,  3.65it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8291/9182 [35:56<05:23,  2.76it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8292/9182 [35:56<07:13,  2.05it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8293/9182 [35:56<05:41,  2.60it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8297/9182 [35:57<03:17,  4.49it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8298/9182 [35:57<03:00,  4.90it/s]
 90%|██████████████████████████████████████████████████████████████████████▍       | 8299/9182 [35:57<03:06,  4.75it/s]
 90%|██████████████████████████████████████████████████████████████████████▌       | 8300/9182 [35:58<03:18,  4.43it/s]
 90%|██████████████████████████████████████████████████████████████████████▌       | 8301/9182 [35:58<03:59,  3.68it/s]
 90%|██████████████████████████████████████████████████████████████████████▌       | 8302/9182 [35:59<05:31,  2.66it/s]
 90%|██████████████████████████████████████████████████████████████████████▌       | 8303/9182 [35:59<05:18,  2.76it/s]
 90%|██████████████████████████████████████████████████████████████████████▌       | 8304/9182 [36:00<06:41,  2.19it/s]
 90%|██████████████████████████████████████████████████████████████████████▌       | 8309/9182 [36:00<02:39,  5.48it/s]
 91%|██████████████████████████████████████████████████████████████████████▌       | 8310/9182 [36:02<06:07,  2.37it/s]
 91%|██████████████████████████████████████████████████████████████████████▌       | 8311/9182 [36:02<06:38,  2.18it/s]
 91%|██████████████████████████████████████████████████████████████████████▌       | 8312/9182 [36:03<06:01,  2.40it/s]
 91%|██████████████████████████████████████████████████████████████████████▌       | 8313/9182 [36:03<05:36,  2.58it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8314/9182 [36:03<05:02,  2.87it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8315/9182 [36:05<09:52,  1.46it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8316/9182 [36:05<08:46,  1.65it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8317/9182 [36:05<07:10,  2.01it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8318/9182 [36:06<06:32,  2.20it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8319/9182 [36:08<15:28,  1.08s/it]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8320/9182 [36:08<11:56,  1.20it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8321/9182 [36:09<09:26,  1.52it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8322/9182 [36:09<09:45,  1.47it/s]
 91%|██████████████████████████████████████████████████████████████████████▋       | 8328/9182 [36:10<03:22,  4.22it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8329/9182 [36:10<03:36,  3.95it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8330/9182 [36:10<03:47,  3.74it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8331/9182 [36:11<03:25,  4.15it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8332/9182 [36:11<05:24,  2.62it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8333/9182 [36:12<04:39,  3.03it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8334/9182 [36:14<11:08,  1.27it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8335/9182 [36:14<10:08,  1.39it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8336/9182 [36:15<07:59,  1.76it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8337/9182 [36:15<07:08,  1.97it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8342/9182 [36:17<07:06,  1.97it/s]
 91%|██████████████████████████████████████████████████████████████████████▊       | 8343/9182 [36:21<14:54,  1.07s/it]
 91%|██████████████████████████████████████████████████████████████████████▉       | 8344/9182 [36:22<12:30,  1.12it/s]
 91%|██████████████████████████████████████████████████████████████████████▉       | 8345/9182 [36:22<10:22,  1.34it/s]
 91%|██████████████████████████████████████████████████████████████████████▉       | 8346/9182 [36:22<10:05,  1.38it/s]
 91%|██████████████████████████████████████████████████████████████████████▉       | 8347/9182 [36:23<08:50,  1.57it/s]
 91%|██████████████████████████████████████████████████████████████████████▉       | 8348/9182 [36:23<07:10,  1.94it/s]
 91%|██████████████████████████████████████████████████████████████████████▉       | 8357/9182 [36:26<05:11,  2.65it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8358/9182 [36:26<05:02,  2.72it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8359/9182 [36:27<05:18,  2.59it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8360/9182 [36:27<04:40,  2.93it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8361/9182 [36:27<04:09,  3.29it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8362/9182 [36:27<04:17,  3.18it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8363/9182 [36:28<04:20,  3.15it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8364/9182 [36:28<05:02,  2.71it/s]
 91%|███████████████████████████████████████████████████████████████████████       | 8365/9182 [36:29<06:06,  2.23it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8374/9182 [36:30<02:55,  4.60it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8375/9182 [36:31<03:13,  4.16it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8376/9182 [36:31<03:59,  3.36it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8377/9182 [36:32<04:12,  3.19it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8378/9182 [36:32<03:40,  3.65it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8380/9182 [36:32<03:12,  4.16it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8381/9182 [36:33<03:52,  3.44it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8382/9182 [36:33<04:10,  3.20it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8383/9182 [36:34<04:56,  2.70it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8384/9182 [36:34<04:06,  3.24it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8385/9182 [36:34<03:47,  3.51it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8386/9182 [36:34<03:49,  3.47it/s]
 91%|███████████████████████████████████████████████████████████████████████▏      | 8387/9182 [36:35<04:18,  3.08it/s]
 91%|███████████████████████████████████████████████████████████████████████▎      | 8388/9182 [36:35<03:56,  3.36it/s]
 91%|███████████████████████████████████████████████████████████████████████▎      | 8389/9182 [36:35<03:52,  3.41it/s]
 91%|███████████████████████████████████████████████████████████████████████▎      | 8398/9182 [36:36<01:06, 11.77it/s]
 91%|███████████████████████████████████████████████████████████████████████▎      | 8400/9182 [36:36<01:52,  6.96it/s]
 91%|███████████████████████████████████████████████████████████████████████▎      | 8401/9182 [36:38<04:08,  3.14it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8404/9182 [36:38<03:32,  3.65it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8405/9182 [36:39<04:52,  2.66it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8406/9182 [36:40<04:53,  2.65it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8407/9182 [36:40<04:51,  2.65it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8408/9182 [36:41<04:29,  2.88it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8409/9182 [36:41<06:51,  1.88it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8410/9182 [36:42<06:09,  2.09it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8411/9182 [36:42<05:28,  2.35it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8412/9182 [36:42<05:13,  2.45it/s]
 92%|███████████████████████████████████████████████████████████████████████▍      | 8413/9182 [36:42<04:18,  2.98it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8417/9182 [36:44<03:46,  3.37it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8418/9182 [36:45<06:59,  1.82it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8419/9182 [36:46<06:28,  1.96it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8420/9182 [36:46<05:40,  2.24it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8421/9182 [36:46<05:25,  2.34it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8422/9182 [36:46<04:31,  2.80it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8423/9182 [36:47<03:58,  3.18it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8424/9182 [36:49<11:15,  1.12it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8425/9182 [36:51<14:08,  1.12s/it]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8426/9182 [36:51<11:27,  1.10it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8427/9182 [36:51<09:30,  1.32it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8428/9182 [36:52<07:24,  1.70it/s]
 92%|███████████████████████████████████████████████████████████████████████▌      | 8429/9182 [36:52<07:12,  1.74it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8436/9182 [36:54<03:25,  3.63it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8437/9182 [36:54<03:33,  3.49it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8438/9182 [36:54<03:33,  3.48it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8439/9182 [36:55<03:54,  3.17it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8440/9182 [36:55<03:37,  3.41it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8441/9182 [36:55<03:05,  4.00it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8442/9182 [36:56<04:46,  2.59it/s]

 92%|███████████████████████████████████████████████████████████████████████▋      | 8443/9182 [36:57<06:49,  1.81it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8444/9182 [36:57<06:02,  2.04it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8445/9182 [36:59<10:25,  1.18it/s]
 92%|███████████████████████████████████████████████████████████████████████▋      | 8446/9182 [36:59<08:24,  1.46it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8447/9182 [37:00<07:50,  1.56it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8448/9182 [37:01<09:00,  1.36it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8449/9182 [37:01<07:24,  1.65it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8450/9182 [37:01<05:56,  2.05it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8451/9182 [37:02<06:11,  1.97it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8452/9182 [37:02<05:13,  2.33it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8453/9182 [37:02<04:04,  2.98it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8454/9182 [37:02<03:24,  3.57it/s]
 92%|███████████████████████████████████████████████████████████████████████▊      | 8459/9182 [37:05<05:40,  2.13it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8464/9182 [37:08<05:57,  2.01it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8465/9182 [37:08<05:24,  2.21it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8466/9182 [37:08<04:54,  2.43it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8467/9182 [37:08<05:17,  2.25it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8468/9182 [37:09<04:44,  2.51it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8469/9182 [37:09<04:18,  2.75it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8470/9182 [37:09<03:48,  3.11it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8472/9182 [37:11<05:15,  2.25it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8473/9182 [37:11<05:29,  2.15it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8474/9182 [37:11<05:18,  2.22it/s]
 92%|███████████████████████████████████████████████████████████████████████▉      | 8475/9182 [37:12<05:03,  2.33it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8476/9182 [37:12<04:18,  2.73it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8477/9182 [37:12<03:47,  3.10it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8478/9182 [37:12<03:04,  3.82it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8479/9182 [37:13<03:16,  3.58it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8480/9182 [37:13<03:58,  2.94it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8481/9182 [37:14<06:45,  1.73it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8482/9182 [37:14<06:08,  1.90it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8483/9182 [37:15<05:26,  2.14it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8486/9182 [37:15<03:00,  3.86it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8487/9182 [37:15<02:38,  4.38it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8488/9182 [37:16<04:32,  2.55it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8489/9182 [37:17<04:39,  2.48it/s]
 92%|████████████████████████████████████████████████████████████████████████      | 8490/9182 [37:17<04:23,  2.63it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8495/9182 [37:17<01:48,  6.34it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8497/9182 [37:17<01:32,  7.43it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8499/9182 [37:18<01:46,  6.44it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8500/9182 [37:18<01:56,  5.86it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8501/9182 [37:18<02:44,  4.13it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8502/9182 [37:19<03:17,  3.44it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8503/9182 [37:19<03:53,  2.90it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8504/9182 [37:20<03:58,  2.85it/s]
 93%|████████████████████████████████████████████████████████████████████████▏     | 8505/9182 [37:21<05:02,  2.24it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8506/9182 [37:21<05:31,  2.04it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8507/9182 [37:22<04:44,  2.37it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8508/9182 [37:22<05:58,  1.88it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8514/9182 [37:22<02:00,  5.53it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8515/9182 [37:24<04:56,  2.25it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8516/9182 [37:25<04:45,  2.33it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8517/9182 [37:25<04:38,  2.39it/s]
 93%|████████████████████████████████████████████████████████████████████████▎     | 8518/9182 [37:25<03:56,  2.81it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8520/9182 [37:26<02:51,  3.85it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8521/9182 [37:27<06:07,  1.80it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8522/9182 [37:28<06:42,  1.64it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8523/9182 [37:28<05:54,  1.86it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8524/9182 [37:28<04:51,  2.25it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8525/9182 [37:29<04:37,  2.36it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8526/9182 [37:29<03:49,  2.86it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8527/9182 [37:29<03:29,  3.12it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8528/9182 [37:30<04:24,  2.47it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8529/9182 [37:31<05:46,  1.89it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8530/9182 [37:32<05:54,  1.84it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8531/9182 [37:32<06:15,  1.74it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8532/9182 [37:32<05:14,  2.07it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8533/9182 [37:32<04:33,  2.38it/s]
 93%|████████████████████████████████████████████████████████████████████████▍     | 8534/9182 [37:33<04:47,  2.25it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8535/9182 [37:33<04:33,  2.37it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8536/9182 [37:34<03:33,  3.03it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8537/9182 [37:35<05:05,  2.11it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8538/9182 [37:35<06:57,  1.54it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8539/9182 [37:36<05:26,  1.97it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8540/9182 [37:36<05:06,  2.09it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8541/9182 [37:37<05:01,  2.12it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8542/9182 [37:39<12:59,  1.22s/it]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8543/9182 [37:40<10:03,  1.06it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8544/9182 [37:40<08:32,  1.25it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8545/9182 [37:40<06:37,  1.60it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8546/9182 [37:40<05:07,  2.07it/s]
 93%|████████████████████████████████████████████████████████████████████████▌     | 8547/9182 [37:41<04:18,  2.45it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8550/9182 [37:42<03:37,  2.91it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8551/9182 [37:43<05:53,  1.79it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8552/9182 [37:43<05:24,  1.94it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8556/9182 [37:44<03:14,  3.22it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8557/9182 [37:44<03:02,  3.43it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8558/9182 [37:44<02:54,  3.58it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8559/9182 [37:45<02:53,  3.59it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8560/9182 [37:45<03:35,  2.88it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8561/9182 [37:45<03:03,  3.39it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8562/9182 [37:46<03:37,  2.86it/s]
 93%|████████████████████████████████████████████████████████████████████████▋     | 8563/9182 [37:47<06:37,  1.56it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8564/9182 [37:48<05:58,  1.73it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8565/9182 [37:48<05:16,  1.95it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8566/9182 [37:48<04:31,  2.27it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8567/9182 [37:48<04:00,  2.55it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8568/9182 [37:51<11:51,  1.16s/it]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8577/9182 [37:53<03:48,  2.65it/s]
 93%|████████████████████████████████████████████████████████████████████████▊     | 8578/9182 [37:53<03:55,  2.56it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8579/9182 [37:55<04:48,  2.09it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8580/9182 [37:55<04:20,  2.31it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8581/9182 [37:55<03:52,  2.59it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8582/9182 [37:55<03:53,  2.57it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8583/9182 [37:56<04:55,  2.03it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8584/9182 [37:56<04:20,  2.29it/s]
 93%|████████████████████████████████████████████████████████████████████████▉     | 8585/9182 [37:57<05:34,  1.79it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8586/9182 [37:58<04:45,  2.09it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8587/9182 [37:58<04:08,  2.39it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8588/9182 [37:59<06:23,  1.55it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8589/9182 [37:59<05:14,  1.88it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8590/9182 [38:00<04:02,  2.45it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8591/9182 [38:00<03:29,  2.82it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8592/9182 [38:00<04:17,  2.29it/s]
 94%|████████████████████████████████████████████████████████████████████████▉     | 8593/9182 [38:01<03:52,  2.53it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8594/9182 [38:01<03:20,  2.93it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8595/9182 [38:01<02:57,  3.30it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8596/9182 [38:01<03:00,  3.24it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8597/9182 [38:02<02:55,  3.34it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8598/9182 [38:02<02:51,  3.40it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8599/9182 [38:02<03:01,  3.20it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8600/9182 [38:03<02:49,  3.44it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8601/9182 [38:03<02:22,  4.08it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8602/9182 [38:03<02:54,  3.32it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8603/9182 [38:04<02:52,  3.36it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8604/9182 [38:05<04:44,  2.03it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8605/9182 [38:05<05:30,  1.74it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8606/9182 [38:06<04:57,  1.94it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8607/9182 [38:06<04:31,  2.12it/s]
 94%|█████████████████████████████████████████████████████████████████████████     | 8608/9182 [38:07<04:20,  2.20it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8609/9182 [38:07<04:52,  1.96it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8610/9182 [38:07<04:26,  2.15it/s]

 94%|█████████████████████████████████████████████████████████████████████████▏    | 8611/9182 [38:08<04:39,  2.04it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8612/9182 [38:08<04:41,  2.02it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8613/9182 [38:09<03:36,  2.63it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8614/9182 [38:09<04:15,  2.23it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8615/9182 [38:10<04:10,  2.26it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8616/9182 [38:10<04:53,  1.93it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8617/9182 [38:11<04:46,  1.97it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8618/9182 [38:11<04:12,  2.23it/s]
 94%|█████████████████████████████████████████████████████████████████████████▏    | 8619/9182 [38:11<03:59,  2.35it/s]
 94%|█████████████████████████████████████████████████████████████████████████▎    | 8633/9182 [38:12<00:45, 12.04it/s]
 94%|█████████████████████████████████████████████████████████████████████████▎    | 8635/9182 [38:14<01:54,  4.78it/s]
 94%|█████████████████████████████████████████████████████████████████████████▎    | 8636/9182 [38:14<02:07,  4.27it/s]
 94%|█████████████████████████████████████████████████████████████████████████▎    | 8637/9182 [38:15<02:17,  3.95it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8638/9182 [38:15<02:37,  3.46it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8639/9182 [38:15<02:39,  3.39it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8640/9182 [38:16<04:14,  2.13it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8641/9182 [38:17<04:08,  2.17it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8642/9182 [38:18<04:46,  1.89it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8643/9182 [38:18<04:10,  2.15it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8644/9182 [38:18<03:37,  2.47it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8645/9182 [38:18<03:12,  2.79it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8646/9182 [38:20<05:18,  1.68it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8647/9182 [38:20<04:33,  1.95it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8648/9182 [38:20<04:38,  1.92it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8649/9182 [38:20<03:40,  2.42it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8651/9182 [38:21<03:23,  2.61it/s]
 94%|█████████████████████████████████████████████████████████████████████████▍    | 8652/9182 [38:21<02:58,  2.97it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8653/9182 [38:22<02:50,  3.10it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8654/9182 [38:22<03:29,  2.52it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8655/9182 [38:25<07:57,  1.10it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8656/9182 [38:25<06:31,  1.34it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8657/9182 [38:25<05:54,  1.48it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8658/9182 [38:26<04:44,  1.84it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8659/9182 [38:26<04:33,  1.91it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8660/9182 [38:26<03:42,  2.34it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8661/9182 [38:27<03:11,  2.72it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8662/9182 [38:27<03:40,  2.36it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8663/9182 [38:27<03:22,  2.56it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8664/9182 [38:28<02:59,  2.89it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8665/9182 [38:28<02:49,  3.05it/s]
 94%|█████████████████████████████████████████████████████████████████████████▌    | 8666/9182 [38:28<03:03,  2.82it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8667/9182 [38:29<03:12,  2.67it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8668/9182 [38:29<04:03,  2.11it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8669/9182 [38:30<04:15,  2.01it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8670/9182 [38:30<03:25,  2.49it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8671/9182 [38:31<03:43,  2.28it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8672/9182 [38:31<03:29,  2.44it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8673/9182 [38:31<03:05,  2.74it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8674/9182 [38:31<02:49,  3.00it/s]
 94%|█████████████████████████████████████████████████████████████████████████▋    | 8676/9182 [38:32<01:49,  4.64it/s]
 95%|█████████████████████████████████████████████████████████████████████████▋    | 8677/9182 [38:33<03:16,  2.57it/s]
 95%|█████████████████████████████████████████████████████████████████████████▋    | 8678/9182 [38:33<03:05,  2.71it/s]
 95%|█████████████████████████████████████████████████████████████████████████▋    | 8679/9182 [38:34<04:03,  2.06it/s]
 95%|█████████████████████████████████████████████████████████████████████████▋    | 8680/9182 [38:34<03:50,  2.18it/s]
 95%|█████████████████████████████████████████████████████████████████████████▋    | 8681/9182 [38:34<03:28,  2.41it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8682/9182 [38:35<03:37,  2.30it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8683/9182 [38:35<02:55,  2.85it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8684/9182 [38:36<03:02,  2.73it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8685/9182 [38:36<03:06,  2.67it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8686/9182 [38:36<03:30,  2.35it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8687/9182 [38:37<04:08,  1.99it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8689/9182 [38:38<03:10,  2.58it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8690/9182 [38:40<06:37,  1.24it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8691/9182 [38:40<05:22,  1.52it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8693/9182 [38:42<06:16,  1.30it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8694/9182 [38:42<05:20,  1.52it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8695/9182 [38:42<04:31,  1.79it/s]
 95%|█████████████████████████████████████████████████████████████████████████▊    | 8696/9182 [38:42<03:33,  2.28it/s]
 95%|█████████████████████████████████████████████████████████████████████████▉    | 8697/9182 [38:43<02:59,  2.70it/s]
 95%|█████████████████████████████████████████████████████████████████████████▉    | 8701/9182 [38:43<01:17,  6.23it/s]
 95%|█████████████████████████████████████████████████████████████████████████▉    | 8703/9182 [38:45<03:41,  2.16it/s]
 95%|█████████████████████████████████████████████████████████████████████████▉    | 8709/9182 [38:45<01:49,  4.33it/s]
 95%|█████████████████████████████████████████████████████████████████████████▉    | 8711/9182 [38:46<02:17,  3.43it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8712/9182 [38:47<02:49,  2.78it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8713/9182 [38:48<02:56,  2.66it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8714/9182 [38:48<03:01,  2.57it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8715/9182 [38:49<03:20,  2.32it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8716/9182 [38:49<03:25,  2.26it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8717/9182 [38:49<02:59,  2.58it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8718/9182 [38:50<03:47,  2.04it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8719/9182 [38:51<04:17,  1.80it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8720/9182 [38:51<03:41,  2.08it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8721/9182 [38:51<02:52,  2.67it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8722/9182 [38:52<02:56,  2.61it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8723/9182 [38:52<03:03,  2.50it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8724/9182 [38:52<02:35,  2.95it/s]
 95%|██████████████████████████████████████████████████████████████████████████    | 8725/9182 [38:53<02:48,  2.71it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8726/9182 [38:53<02:40,  2.84it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8727/9182 [38:54<03:40,  2.07it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8728/9182 [38:54<03:57,  1.92it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8729/9182 [38:55<03:29,  2.16it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8730/9182 [38:55<03:05,  2.43it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8731/9182 [38:55<02:36,  2.88it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8732/9182 [38:56<02:24,  3.11it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8733/9182 [38:56<02:36,  2.87it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8734/9182 [38:57<03:04,  2.42it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8735/9182 [38:57<02:56,  2.53it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8736/9182 [38:57<02:28,  3.00it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8737/9182 [38:58<02:42,  2.74it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8738/9182 [38:58<03:14,  2.29it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8739/9182 [38:58<02:38,  2.80it/s]
 95%|██████████████████████████████████████████████████████████████████████████▏   | 8740/9182 [38:59<03:43,  1.98it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8741/9182 [38:59<03:12,  2.29it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8744/9182 [39:00<01:43,  4.23it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8745/9182 [39:01<02:47,  2.61it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8746/9182 [39:01<03:38,  1.99it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8747/9182 [39:03<04:38,  1.56it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8748/9182 [39:03<04:04,  1.78it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8749/9182 [39:03<03:15,  2.22it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8750/9182 [39:04<04:19,  1.67it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8751/9182 [39:04<03:42,  1.93it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8752/9182 [39:05<03:26,  2.09it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8753/9182 [39:05<03:13,  2.22it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8754/9182 [39:05<02:31,  2.82it/s]
 95%|██████████████████████████████████████████████████████████████████████████▎   | 8755/9182 [39:08<06:40,  1.07it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8756/9182 [39:08<05:08,  1.38it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8757/9182 [39:08<04:07,  1.72it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8758/9182 [39:09<03:22,  2.09it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8759/9182 [39:09<03:21,  2.10it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8760/9182 [39:09<02:46,  2.54it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8761/9182 [39:09<02:18,  3.05it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8762/9182 [39:10<02:38,  2.66it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8763/9182 [39:10<02:19,  3.01it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8764/9182 [39:11<04:10,  1.67it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8765/9182 [39:12<04:25,  1.57it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8766/9182 [39:12<03:49,  1.81it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8767/9182 [39:13<04:05,  1.69it/s]
 95%|██████████████████████████████████████████████████████████████████████████▍   | 8768/9182 [39:13<03:18,  2.09it/s]
 96%|██████████████████████████████████████████████████████████████████████████▍   | 8769/9182 [39:13<02:46,  2.49it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8770/9182 [39:14<02:36,  2.64it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8771/9182 [39:14<02:26,  2.80it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8772/9182 [39:15<02:29,  2.75it/s]

 96%|██████████████████████████████████████████████████████████████████████████▌   | 8773/9182 [39:15<03:50,  1.78it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8774/9182 [39:16<03:21,  2.02it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8775/9182 [39:16<03:04,  2.21it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8776/9182 [39:16<02:34,  2.62it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8777/9182 [39:16<02:07,  3.18it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8778/9182 [39:17<01:52,  3.58it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8779/9182 [39:17<02:38,  2.54it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8780/9182 [39:18<02:23,  2.80it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8781/9182 [39:18<02:15,  2.96it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8782/9182 [39:18<02:55,  2.27it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8783/9182 [39:19<02:37,  2.53it/s]
 96%|██████████████████████████████████████████████████████████████████████████▌   | 8784/9182 [39:19<02:41,  2.47it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8785/9182 [39:21<05:48,  1.14it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8786/9182 [39:22<04:47,  1.38it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8787/9182 [39:22<04:02,  1.63it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8788/9182 [39:22<03:17,  2.00it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8789/9182 [39:22<02:37,  2.49it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8790/9182 [39:23<02:30,  2.60it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8791/9182 [39:23<02:17,  2.85it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8792/9182 [39:24<03:10,  2.05it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8793/9182 [39:24<03:43,  1.74it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8794/9182 [39:25<03:21,  1.92it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8795/9182 [39:25<02:53,  2.23it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8796/9182 [39:25<02:20,  2.75it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8797/9182 [39:26<02:03,  3.13it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8798/9182 [39:26<01:37,  3.94it/s]
 96%|██████████████████████████████████████████████████████████████████████████▋   | 8799/9182 [39:27<03:03,  2.09it/s]
 96%|██████████████████████████████████████████████████████████████████████████▊   | 8800/9182 [39:28<04:30,  1.41it/s]
 96%|██████████████████████████████████████████████████████████████████████████▊   | 8801/9182 [39:32<10:21,  1.63s/it]
 96%|██████████████████████████████████████████████████████████████████████████▊   | 8802/9182 [39:32<07:38,  1.21s/it]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8816/9182 [39:32<01:08,  5.37it/s]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8819/9182 [39:34<01:31,  3.98it/s]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8821/9182 [39:36<02:13,  2.70it/s]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8823/9182 [39:36<01:59,  3.01it/s]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8824/9182 [39:36<01:49,  3.27it/s]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8825/9182 [39:36<01:50,  3.24it/s]
 96%|██████████████████████████████████████████████████████████████████████████▉   | 8826/9182 [39:36<01:37,  3.66it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8831/9182 [39:37<01:01,  5.74it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8832/9182 [39:38<01:18,  4.45it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8833/9182 [39:39<02:33,  2.27it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8834/9182 [39:39<02:25,  2.39it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8835/9182 [39:40<02:17,  2.53it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8836/9182 [39:40<02:45,  2.09it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8837/9182 [39:41<02:22,  2.41it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8838/9182 [39:44<06:14,  1.09s/it]
 96%|███████████████████████████████████████████████████████████████████████████   | 8839/9182 [39:44<04:53,  1.17it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8840/9182 [39:44<03:44,  1.52it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8841/9182 [39:44<03:22,  1.68it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8842/9182 [39:45<02:45,  2.05it/s]
 96%|███████████████████████████████████████████████████████████████████████████   | 8843/9182 [39:45<02:07,  2.66it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8844/9182 [39:45<02:09,  2.61it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8849/9182 [39:47<02:08,  2.59it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8850/9182 [39:48<02:16,  2.42it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8851/9182 [39:48<02:40,  2.06it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8855/9182 [39:49<01:33,  3.50it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8856/9182 [39:50<02:19,  2.34it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8857/9182 [39:51<02:52,  1.88it/s]
 96%|███████████████████████████████████████████████████████████████████████████▏  | 8858/9182 [39:51<02:41,  2.01it/s]
 96%|███████████████████████████████████████████████████████████████████████████▎  | 8859/9182 [39:52<02:25,  2.23it/s]
 96%|███████████████████████████████████████████████████████████████████████████▎  | 8860/9182 [39:52<02:05,  2.57it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8861/9182 [39:54<04:01,  1.33it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8862/9182 [39:54<03:25,  1.56it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8863/9182 [39:54<02:58,  1.79it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8864/9182 [39:55<02:53,  1.83it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8865/9182 [39:55<02:14,  2.35it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8866/9182 [39:55<01:51,  2.84it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8867/9182 [39:55<01:46,  2.97it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8868/9182 [39:56<01:27,  3.57it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8869/9182 [39:56<01:45,  2.98it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8870/9182 [39:56<01:48,  2.87it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8871/9182 [39:57<02:04,  2.49it/s]
 97%|███████████████████████████████████████████████████████████████████████████▎  | 8872/9182 [39:57<01:59,  2.60it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8873/9182 [39:58<01:59,  2.59it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8874/9182 [39:58<02:14,  2.29it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8875/9182 [39:59<02:03,  2.49it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8876/9182 [39:59<02:16,  2.25it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8877/9182 [40:00<02:24,  2.11it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8878/9182 [40:00<01:51,  2.73it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8879/9182 [40:01<02:03,  2.45it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8880/9182 [40:01<02:39,  1.89it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8881/9182 [40:01<02:22,  2.11it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8882/9182 [40:02<02:00,  2.49it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8883/9182 [40:02<02:13,  2.24it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8884/9182 [40:03<01:58,  2.52it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8886/9182 [40:04<02:12,  2.24it/s]
 97%|███████████████████████████████████████████████████████████████████████████▍  | 8887/9182 [40:04<02:25,  2.03it/s]
 97%|███████████████████████████████████████████████████████████████████████████▌  | 8888/9182 [40:04<02:03,  2.39it/s]
 97%|███████████████████████████████████████████████████████████████████████████▌  | 8889/9182 [40:05<01:56,  2.52it/s]
 97%|███████████████████████████████████████████████████████████████████████████▌  | 8891/9182 [40:10<07:08,  1.47s/it]
 97%|███████████████████████████████████████████████████████████████████████████▌  | 8902/9182 [40:11<01:47,  2.61it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8903/9182 [40:12<01:49,  2.56it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8904/9182 [40:12<01:53,  2.45it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8905/9182 [40:12<01:42,  2.69it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8906/9182 [40:13<01:39,  2.78it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8907/9182 [40:13<01:34,  2.90it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8908/9182 [40:14<02:42,  1.69it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8909/9182 [40:15<02:45,  1.65it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8910/9182 [40:16<02:23,  1.90it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8911/9182 [40:16<02:19,  1.94it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8916/9182 [40:18<02:10,  2.03it/s]
 97%|███████████████████████████████████████████████████████████████████████████▋  | 8917/9182 [40:19<02:08,  2.06it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8918/9182 [40:19<01:57,  2.24it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8922/9182 [40:19<01:06,  3.88it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8923/9182 [40:19<01:08,  3.80it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8924/9182 [40:21<02:05,  2.05it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8925/9182 [40:21<02:02,  2.10it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8926/9182 [40:22<01:51,  2.30it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8927/9182 [40:22<01:52,  2.27it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8928/9182 [40:22<01:32,  2.76it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8929/9182 [40:22<01:19,  3.16it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8930/9182 [40:24<02:07,  1.97it/s]
 97%|███████████████████████████████████████████████████████████████████████████▊  | 8931/9182 [40:24<02:22,  1.76it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8932/9182 [40:25<02:33,  1.63it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8933/9182 [40:25<02:20,  1.77it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8934/9182 [40:26<01:56,  2.14it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8935/9182 [40:26<01:50,  2.24it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8936/9182 [40:27<01:43,  2.38it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8937/9182 [40:27<01:27,  2.79it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8938/9182 [40:27<01:46,  2.29it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8939/9182 [40:29<02:22,  1.70it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8940/9182 [40:29<02:14,  1.80it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8941/9182 [40:30<02:07,  1.89it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8942/9182 [40:30<02:25,  1.65it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8944/9182 [40:30<01:29,  2.65it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8945/9182 [40:31<01:27,  2.71it/s]
 97%|███████████████████████████████████████████████████████████████████████████▉  | 8946/9182 [40:31<01:36,  2.45it/s]
 97%|████████████████████████████████████████████████████████████████████████████  | 8947/9182 [40:32<01:32,  2.54it/s]
 97%|████████████████████████████████████████████████████████████████████████████  | 8948/9182 [40:32<01:49,  2.15it/s]
 97%|████████████████████████████████████████████████████████████████████████████  | 8949/9182 [40:32<01:40,  2.31it/s]
 97%|████████████████████████████████████████████████████████████████████████████  | 8950/9182 [40:33<01:36,  2.41it/s]
 97%|████████████████████████████████████████████████████████████████████████████  | 8951/9182 [40:33<01:29,  2.58it/s]
 97%|████████████████████████████████████████████████████████████████████████████  | 8952/9182 [40:34<01:30,  2.55it/s]

 98%|████████████████████████████████████████████████████████████████████████████  | 8953/9182 [40:34<01:45,  2.17it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8954/9182 [40:35<01:46,  2.15it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8955/9182 [40:35<01:52,  2.01it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8956/9182 [40:36<01:45,  2.14it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8957/9182 [40:36<02:07,  1.76it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8958/9182 [40:37<01:48,  2.06it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8959/9182 [40:37<01:28,  2.52it/s]
 98%|████████████████████████████████████████████████████████████████████████████  | 8961/9182 [40:39<01:54,  1.94it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8962/9182 [40:39<02:06,  1.73it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8963/9182 [40:39<02:07,  1.72it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8967/9182 [40:41<01:51,  1.93it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8968/9182 [40:42<01:40,  2.13it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8969/9182 [40:42<01:37,  2.19it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8970/9182 [40:43<01:31,  2.33it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8971/9182 [40:43<01:30,  2.33it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8973/9182 [40:44<01:35,  2.19it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8974/9182 [40:45<01:49,  1.89it/s]
 98%|████████████████████████████████████████████████████████████████████████████▏ | 8975/9182 [40:45<01:40,  2.05it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8976/9182 [40:45<01:22,  2.49it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8977/9182 [40:45<01:17,  2.64it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8978/9182 [40:46<01:09,  2.91it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8979/9182 [40:48<03:13,  1.05it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8980/9182 [40:50<04:20,  1.29s/it]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8981/9182 [40:51<03:34,  1.06s/it]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8982/9182 [40:51<02:42,  1.23it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8983/9182 [40:51<02:15,  1.47it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8984/9182 [40:52<01:44,  1.90it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8985/9182 [40:52<01:33,  2.11it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8986/9182 [40:52<01:24,  2.32it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8987/9182 [40:53<01:42,  1.91it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8988/9182 [40:53<01:19,  2.44it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8989/9182 [40:54<01:29,  2.16it/s]
 98%|████████████████████████████████████████████████████████████████████████████▎ | 8990/9182 [40:54<01:41,  1.89it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8991/9182 [40:55<01:29,  2.14it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8992/9182 [40:55<01:23,  2.28it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8993/9182 [40:55<01:18,  2.40it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8994/9182 [40:56<01:11,  2.62it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8995/9182 [40:56<01:13,  2.53it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8996/9182 [40:57<01:25,  2.17it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8997/9182 [40:57<01:09,  2.68it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8998/9182 [40:57<01:07,  2.71it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 8999/9182 [40:58<01:13,  2.51it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 9000/9182 [40:58<01:07,  2.70it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 9001/9182 [40:58<01:03,  2.85it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 9002/9182 [40:59<01:02,  2.89it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 9003/9182 [41:00<01:24,  2.12it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 9004/9182 [41:00<01:25,  2.08it/s]
 98%|████████████████████████████████████████████████████████████████████████████▍ | 9005/9182 [41:01<01:18,  2.24it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9006/9182 [41:01<01:40,  1.76it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9007/9182 [41:02<01:41,  1.72it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9008/9182 [41:02<01:30,  1.92it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9009/9182 [41:03<01:25,  2.02it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9010/9182 [41:03<01:21,  2.10it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9011/9182 [41:04<01:13,  2.32it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9012/9182 [41:04<01:07,  2.54it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9018/9182 [41:04<00:30,  5.33it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9019/9182 [41:04<00:29,  5.49it/s]
 98%|████████████████████████████████████████████████████████████████████████████▌ | 9020/9182 [41:06<01:04,  2.53it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9021/9182 [41:07<01:28,  1.83it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9022/9182 [41:07<01:16,  2.08it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9023/9182 [41:07<01:05,  2.41it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9024/9182 [41:08<00:58,  2.70it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9025/9182 [41:10<02:18,  1.14it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9026/9182 [41:11<01:58,  1.32it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9027/9182 [41:11<01:47,  1.44it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9028/9182 [41:11<01:24,  1.81it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9029/9182 [41:11<01:12,  2.12it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9030/9182 [41:12<01:09,  2.19it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9031/9182 [41:13<01:04,  2.36it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9032/9182 [41:14<01:28,  1.70it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9033/9182 [41:14<01:29,  1.67it/s]
 98%|████████████████████████████████████████████████████████████████████████████▋ | 9034/9182 [41:14<01:15,  1.95it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9035/9182 [41:15<01:12,  2.04it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9036/9182 [41:15<01:00,  2.39it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9037/9182 [41:16<01:02,  2.34it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9038/9182 [41:16<01:11,  2.02it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9039/9182 [41:16<01:09,  2.06it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9040/9182 [41:17<00:57,  2.47it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9041/9182 [41:17<01:00,  2.31it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9042/9182 [41:17<00:59,  2.34it/s]
 98%|████████████████████████████████████████████████████████████████████████████▊ | 9043/9182 [41:18<01:07,  2.05it/s]
 99%|████████████████████████████████████████████████████████████████████████████▊ | 9049/9182 [41:19<00:25,  5.21it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9050/9182 [41:19<00:28,  4.60it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9051/9182 [41:20<00:36,  3.64it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9052/9182 [41:21<01:05,  1.98it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9053/9182 [41:21<00:55,  2.31it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9054/9182 [41:22<01:03,  2.03it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9057/9182 [41:23<00:49,  2.54it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9058/9182 [41:23<00:46,  2.69it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9059/9182 [41:23<00:47,  2.58it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9060/9182 [41:24<00:43,  2.80it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9061/9182 [41:24<00:41,  2.91it/s]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9062/9182 [41:28<02:40,  1.34s/it]
 99%|████████████████████████████████████████████████████████████████████████████▉ | 9063/9182 [41:28<02:03,  1.04s/it]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9071/9182 [41:29<00:37,  2.94it/s]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9072/9182 [41:30<00:38,  2.86it/s]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9073/9182 [41:31<00:45,  2.38it/s]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9074/9182 [41:31<00:41,  2.58it/s]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9075/9182 [41:32<01:05,  1.64it/s]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9076/9182 [41:33<01:04,  1.66it/s]
 99%|█████████████████████████████████████████████████████████████████████████████ | 9077/9182 [41:33<00:53,  1.95it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9082/9182 [41:34<00:34,  2.86it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9083/9182 [41:35<00:32,  3.02it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9084/9182 [41:35<00:40,  2.43it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9087/9182 [41:39<01:04,  1.46it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9088/9182 [41:39<01:02,  1.51it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9089/9182 [41:40<00:57,  1.63it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9090/9182 [41:40<00:50,  1.81it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9091/9182 [41:40<00:42,  2.15it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9092/9182 [41:40<00:36,  2.46it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▏| 9093/9182 [41:40<00:32,  2.75it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9094/9182 [41:41<00:27,  3.17it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9095/9182 [41:41<00:25,  3.40it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9096/9182 [41:41<00:27,  3.10it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9097/9182 [41:42<00:30,  2.80it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9098/9182 [41:42<00:33,  2.47it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9099/9182 [41:43<00:31,  2.60it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9100/9182 [41:43<00:27,  2.95it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9101/9182 [41:43<00:30,  2.63it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9102/9182 [41:44<00:26,  3.05it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9103/9182 [41:44<00:31,  2.54it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9104/9182 [41:45<00:32,  2.37it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9105/9182 [41:45<00:36,  2.13it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9106/9182 [41:46<00:36,  2.08it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9107/9182 [41:46<00:33,  2.24it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▎| 9108/9182 [41:47<00:37,  1.97it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9109/9182 [41:47<00:39,  1.86it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9110/9182 [41:48<00:35,  2.04it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9111/9182 [41:49<00:43,  1.65it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9112/9182 [41:49<00:40,  1.75it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9113/9182 [41:50<00:32,  2.11it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9114/9182 [41:50<00:31,  2.15it/s]

 99%|█████████████████████████████████████████████████████████████████████████████▍| 9115/9182 [41:50<00:33,  2.03it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9116/9182 [41:51<00:29,  2.20it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9119/9182 [41:51<00:15,  4.09it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9120/9182 [41:52<00:21,  2.83it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9121/9182 [41:52<00:24,  2.51it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9122/9182 [41:52<00:20,  2.97it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▍| 9123/9182 [41:55<00:47,  1.23it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9124/9182 [41:55<00:43,  1.35it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9125/9182 [41:55<00:34,  1.67it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9126/9182 [41:55<00:28,  1.97it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9127/9182 [41:56<00:22,  2.39it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9128/9182 [41:56<00:17,  3.03it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9129/9182 [41:56<00:15,  3.41it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9130/9182 [41:57<00:28,  1.83it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9131/9182 [41:58<00:25,  2.01it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9132/9182 [41:58<00:20,  2.50it/s]
 99%|█████████████████████████████████████████████████████████████████████████████▌| 9136/9182 [41:58<00:09,  4.78it/s]
100%|█████████████████████████████████████████████████████████████████████████████▌| 9137/9182 [41:59<00:09,  4.69it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9138/9182 [41:59<00:11,  3.75it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9139/9182 [41:59<00:11,  3.90it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9140/9182 [42:00<00:14,  3.00it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9141/9182 [42:00<00:15,  2.57it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9142/9182 [42:00<00:13,  3.06it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9143/9182 [42:01<00:13,  2.90it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9144/9182 [42:01<00:10,  3.50it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9145/9182 [42:01<00:10,  3.55it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9146/9182 [42:01<00:08,  4.32it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9147/9182 [42:01<00:06,  5.14it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9148/9182 [42:01<00:05,  5.67it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9149/9182 [42:02<00:05,  5.88it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9150/9182 [42:02<00:06,  4.79it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9151/9182 [42:02<00:06,  4.81it/s]
100%|█████████████████████████████████████████████████████████████████████████████▋| 9152/9182 [42:02<00:06,  4.47it/s]
100%|█████████████████████████████████████████████████████████████████████████████▊| 9158/9182 [42:03<00:02,  9.03it/s]
100%|█████████████████████████████████████████████████████████████████████████████▊| 9159/9182 [42:03<00:03,  5.80it/s]
100%|█████████████████████████████████████████████████████████████████████████████▊| 9160/9182 [42:03<00:03,  6.07it/s]
100%|█████████████████████████████████████████████████████████████████████████████▊| 9161/9182 [42:04<00:03,  5.64it/s]
100%|█████████████████████████████████████████████████████████████████████████████▊| 9166/9182 [42:04<00:01, 11.23it/s]
100%|██████████████████████████████████████████████████████████████████████████████| 9182/9182 [42:05<00:00,  3.64it/s]

MemoryError: Unable to allocate 5.01 GiB for an array with shape (7999, 84121) and data type float64