# 리스트 표현식
* 리스트 안에 for 반복문과 if else 조건문을 한번에 적어서 리스트를 만드는 방법
* 여러 줄의 코드를 1줄로 줄일 수 있다.
* for 문과 if else 문을 사용해서 처리할 때 보다 속도가 빠르다.
* [실행할 명령 for 변수 in list, tuple]

1부터 10까지 들어있는 리스트 만들기

In [2]:
l1 = []
for i in range(1,11):
    l1.append(i)
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
l1 = [i for i in range(1,11)]
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# 리스트 표현식과 일반 반복문의 속도 차이

In [6]:
import time

In [8]:
start = time.time()
a = []
for i in range(1,200000000):
    a.append(i+5)
print(a[:10])

print("코드 실행 시간: ", time.time() - start)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
코드 실행 시간:  25.848328113555908

In [12]:
start2 = time.time()
b=[]
b = [i+5 for i in range(1,20000000)]
print(b[:10])
print("코드 실행 시간: ", time.time() - start2)

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
코드 실행 시간:  1.5685882568359375

In [17]:
import numpy as np

In [19]:
start3 = time.time()

c = np.arange(1,200000000)
c += 5
print(c[:10])

print("코드 실행 시간: ", time.time() - start3)

[ 6  7  8  9 10 11 12 13 14 15]
코드 실행 시간:  0.7863366603851318

1에서 10까지의 숫자 중 짝수만 더해서 리스트 만들기

In [2]:
l1 = []
for i in range(1,11):
    if i % 2 == 0:
        l1.append(i)
l1

[2, 4, 6, 8, 10]

In [4]:
l2 = [i for i in range(1,11) if i % 2 == 0]
l2

[2, 4, 6, 8, 10]

## 다중 반복문을 사용한 리스트 표현식
[i*j for i in range(2,10) for j in range(1,9)]

In [6]:
gugu = []
for i in range(2,10):
    for j in range(1,10):
        gugu.append(f"{i} X {j} = {i*j}")
gugu

['2 X 1 = 2',
 '2 X 2 = 4',
 '2 X 3 = 6',
 '2 X 4 = 8',
 '2 X 5 = 10',
 '2 X 6 = 12',
 '2 X 7 = 14',
 '2 X 8 = 16',
 '2 X 9 = 18',
 '3 X 1 = 3',
 '3 X 2 = 6',
 '3 X 3 = 9',
 '3 X 4 = 12',
 '3 X 5 = 15',
 '3 X 6 = 18',
 '3 X 7 = 21',
 '3 X 8 = 24',
 '3 X 9 = 27',
 '4 X 1 = 4',
 '4 X 2 = 8',
 '4 X 3 = 12',
 '4 X 4 = 16',
 '4 X 5 = 20',
 '4 X 6 = 24',
 '4 X 7 = 28',
 '4 X 8 = 32',
 '4 X 9 = 36',
 '5 X 1 = 5',
 '5 X 2 = 10',
 '5 X 3 = 15',
 '5 X 4 = 20',
 '5 X 5 = 25',
 '5 X 6 = 30',
 '5 X 7 = 35',
 '5 X 8 = 40',
 '5 X 9 = 45',
 '6 X 1 = 6',
 '6 X 2 = 12',
 '6 X 3 = 18',
 '6 X 4 = 24',
 '6 X 5 = 30',
 '6 X 6 = 36',
 '6 X 7 = 42',
 '6 X 8 = 48',
 '6 X 9 = 54',
 '7 X 1 = 7',
 '7 X 2 = 14',
 '7 X 3 = 21',
 '7 X 4 = 28',
 '7 X 5 = 35',
 '7 X 6 = 42',
 '7 X 7 = 49',
 '7 X 8 = 56',
 '7 X 9 = 63',
 '8 X 1 = 8',
 '8 X 2 = 16',
 '8 X 3 = 24',
 '8 X 4 = 32',
 '8 X 5 = 40',
 '8 X 6 = 48',
 '8 X 7 = 56',
 '8 X 8 = 64',
 '8 X 9 = 72',
 '9 X 1 = 9',
 '9 X 2 = 18',
 '9 X 3 = 27',
 '9 X 4 = 36',
 '9 X 5 = 45',
 '9 X 6 = 54',
 '9 X 7 = 63',
 '9 X 8 = 72',
 '9 X 9 = 81']

In [8]:
[f"{i} X {j} = {i*j}" for i in range(2,10) for j in range(1,10)]

['2 X 1 = 2',
 '2 X 2 = 4',
 '2 X 3 = 6',
 '2 X 4 = 8',
 '2 X 5 = 10',
 '2 X 6 = 12',
 '2 X 7 = 14',
 '2 X 8 = 16',
 '2 X 9 = 18',
 '3 X 1 = 3',
 '3 X 2 = 6',
 '3 X 3 = 9',
 '3 X 4 = 12',
 '3 X 5 = 15',
 '3 X 6 = 18',
 '3 X 7 = 21',
 '3 X 8 = 24',
 '3 X 9 = 27',
 '4 X 1 = 4',
 '4 X 2 = 8',
 '4 X 3 = 12',
 '4 X 4 = 16',
 '4 X 5 = 20',
 '4 X 6 = 24',
 '4 X 7 = 28',
 '4 X 8 = 32',
 '4 X 9 = 36',
 '5 X 1 = 5',
 '5 X 2 = 10',
 '5 X 3 = 15',
 '5 X 4 = 20',
 '5 X 5 = 25',
 '5 X 6 = 30',
 '5 X 7 = 35',
 '5 X 8 = 40',
 '5 X 9 = 45',
 '6 X 1 = 6',
 '6 X 2 = 12',
 '6 X 3 = 18',
 '6 X 4 = 24',
 '6 X 5 = 30',
 '6 X 6 = 36',
 '6 X 7 = 42',
 '6 X 8 = 48',
 '6 X 9 = 54',
 '7 X 1 = 7',
 '7 X 2 = 14',
 '7 X 3 = 21',
 '7 X 4 = 28',
 '7 X 5 = 35',
 '7 X 6 = 42',
 '7 X 7 = 49',
 '7 X 8 = 56',
 '7 X 9 = 63',
 '8 X 1 = 8',
 '8 X 2 = 16',
 '8 X 3 = 24',
 '8 X 4 = 32',
 '8 X 5 = 40',
 '8 X 6 = 48',
 '8 X 7 = 56',
 '8 X 8 = 64',
 '8 X 9 = 72',
 '9 X 1 = 9',
 '9 X 2 = 18',
 '9 X 3 = 27',
 '9 X 4 = 36',
 '9 X 5 = 45',
 '9 X 6 = 54',
 '9 X 7 = 63',
 '9 X 8 = 72',
 '9 X 9 = 81']

# 파일 읽기 쓰기 open(), with open()
## 1) 파일에 문자열을 쓰거나 읽을때는 open 함수 사용
* 파일저장
변수명 = open("파일이름", 모드(w:쓰기, r:읽기) <br>
변수명.write("저장할 내용")<br>
변수명.close()<br>
**close()를 안하면 게속 열려있음**

In [9]:
file = open("test.txt", "w")
file.write("파일 만들기 연습")
file.close()

* 파일열기<br>
변수1 = open("파일이름", 파일모드(r)) <br>
변수2 = 변수1.read()<br>
변수1.close

In [10]:
file1 = open("test.txt", "r")
my_file=file1.read()
file1.close()
print(my_file)

파일 만들기 연습

## with open
* with open은 close()를 하지 않아도 자동으로 close() 처리를 해줌

In [12]:
with open("test2.txt", 'w') as file3:
    file3.write("with open을 사용하면 파일을 자동으로 닫아주어 편리하다.")

In [13]:
with open("test2.txt", 'r') as file4:
    data = file4.read()        # data에 test2.txt 저장된 내용 할당
print(data)

with open을 사용하면 파일을 자동으로 닫아주어 편리하다.

# encoding에 따른 읽기 오류
* 운영체제나 (windows,linux, macOS) 한글/영어 윈도우에 따라서 인코딩 되는 포멧이 달라짐
* 인코딩에 따른 오류가 발생 가능
* web 표준은 utf-8이므로 인코딩은 utf-8로 하는 것이 좋다.
* windows의 경우 인코딩이 cp949이므로 주의

In [14]:
with open("test_utf-8.txt", 'w', encoding='utf-8') as file5:
    file5.write("이것은 with open으로 만든 utf-8 인코딩 파일입니다.")

In [17]:
with open("test_utf-8.txt", 'r') as file6:
    file6_data = file6.read()
print(file6_data)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 0: illegal multibyte sequence

In [18]:
# encoding이 있어야 에러가 나지 않음
with open("test_utf-8.txt", 'r', encoding='utf-8') as file6:
    file6_data = file6.read()
print(file6_data)

이것은 with open으로 만든 utf-8 인코딩 파일입니다.

# json 파일 읽어와서 내용 정리하기

In [20]:
with open("./data/서울특별시_관광지입장정보_2011_2016.json",'r',encoding='utf-8') as file7:
    trip_info = file7.read()
trip_info

'[\n    {\n        "ForNum": 44722,\n        "NatNum": 75991,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 11017,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "운현궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 132399,\n        "NatNum": 237330,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 3133,\n        "NatNum": 21267,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 18226,\n        "NatNum": 24223,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 233828,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 93554,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "서울역사박물관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 13935,\n        "NatNum": 52140,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 61115,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "서울시립미술관 본관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 10,\n        "NatNum": 1885,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 32412,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 19308,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 5214,\n        "NatNum": 6956,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 13,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 333,\n        "NatNum": 1823,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 14,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 4704,\n        "NatNum": 16634,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 15,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 52484,\n        "NatNum": 642290,\n        "addrCd": 1171,\n        "gungu": "송파구",\n        "resNm": "롯데월드",\n        "rnum": 16,\n        "sido": "서울특별시",\n        "yyyymm": "201112"\n    },\n    {\n        "ForNum": 27814,\n        "NatNum": 28061,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 546,\n        "NatNum": 5978,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "운현궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 105370,\n        "NatNum": 133012,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 1451,\n        "NatNum": 15722,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 8817,\n        "NatNum": 8068,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 13033,\n        "NatNum": 227077,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 1138,\n        "NatNum": 78179,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "서울역사박물관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 11151,\n        "NatNum": 44855,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 213467,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "서울시립미술관 본관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 15,\n        "NatNum": 1252,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 6625,\n        "NatNum": 14090,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 18881,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 24492,\n        "NatNum": 9167,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 13,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 62,\n        "NatNum": 860,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 14,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 66868,\n        "NatNum": 670056,\n        "addrCd": 1171,\n        "gungu": "송파구",\n        "resNm": "롯데월드",\n        "rnum": 15,\n        "sido": "서울특별시",\n        "yyyymm": "201212"\n    },\n    {\n        "ForNum": 25550,\n        "NatNum": 38553,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 101942,\n        "NatNum": 145544,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 1986,\n        "NatNum": 20035,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6048,\n        "NatNum": 13896,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 9083,\n        "NatNum": 286992,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 13282,\n        "NatNum": 99301,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6,\n        "NatNum": 706,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 6732,\n        "NatNum": 14607,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 23245,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 43129,\n        "NatNum": 11886,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 16,\n        "NatNum": 1248,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 1445,\n        "NatNum": 11890,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201312"\n    },\n    {\n        "ForNum": 29928,\n        "NatNum": 41561,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 129946,\n        "NatNum": 190501,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 1693,\n        "NatNum": 19473,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 3891,\n        "NatNum": 5951,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 7195,\n        "NatNum": 258781,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 14723,\n        "NatNum": 44272,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 12,\n        "NatNum": 486,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 6263,\n        "NatNum": 27205,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 24527,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 42443,\n        "NatNum": 7478,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 5,\n        "NatNum": 1036,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 823,\n        "NatNum": 8869,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201412"\n    },\n    {\n        "ForNum": 33342,\n        "NatNum": 59738,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창덕궁",\n        "rnum": 1,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 170379,\n        "NatNum": 148961,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "경복궁",\n        "rnum": 2,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 1783,\n        "NatNum": 27172,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "창경궁",\n        "rnum": 3,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 3406,\n        "NatNum": 14936,\n        "addrCd": 1111,\n        "gungu": "종로구",\n        "resNm": "종묘",\n        "rnum": 4,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 13127,\n        "NatNum": 281457,\n        "addrCd": 1117,\n        "gungu": "용산구",\n        "resNm": "국립중앙박물관",\n        "rnum": 5,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 15197,\n        "NatNum": 68749,\n        "addrCd": 1114,\n        "gungu": "중구",\n        "resNm": "덕수궁",\n        "rnum": 6,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 16,\n        "NatNum": 2221,\n        "addrCd": 1135,\n        "gungu": "노원구",\n        "resNm": "태릉 ·  강릉 · 조선왕릉전시관",\n        "rnum": 7,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 5588,\n        "NatNum": 44232,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문형무소역사관",\n        "rnum": 8,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 0,\n        "NatNum": 22587,\n        "addrCd": 1141,\n        "gungu": "서대문구",\n        "resNm": "서대문자연사박물관",\n        "rnum": 9,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 29520,\n        "NatNum": 8822,\n        "addrCd": 1144,\n        "gungu": "마포구",\n        "resNm": "트릭아이미술관",\n        "rnum": 10,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 3,\n        "NatNum": 1647,\n        "addrCd": 1165,\n        "gungu": "서초구",\n        "resNm": "헌릉ㆍ인릉",\n        "rnum": 11,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    },\n    {\n        "ForNum": 492,\n        "NatNum": 14454,\n        "addrCd": 1168,\n        "gungu": "강남구",\n        "resNm": "선릉·정릉",\n        "rnum": 12,\n        "sido": "서울특별시",\n        "yyyymm": "201512"\n    }\n]'

In [21]:
trip_info[0]["Fornum"]
# 딕셔너리가 아닌 str이므로 인덱싱 불가능

TypeError: string indices must be integers

In [22]:
import json

In [25]:
# json으로 바꾸면 str 이 아닌 dict로 타입이 지정됨
data = json.loads(trip_info)
data[0]["ForNum"]

44722

In [31]:
for item in data[0]:     # key를 반환
    print(item)
print()
for item in data[:2]:    # 큰 단위로 2개 출력
    for key in item:
        print(key)

ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm

ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm
ForNum
NatNum
addrCd
gungu
resNm
rnum
sido
yyyymm

In [34]:
for item in data[:2]:
    print(item['ForNum'])
    print(item['NatNum'])
    print(item['addrCd'])
    print(item['gungu'])
    print(item['resNm'])
    print(item['rnum'])
    print(item['sido'])
    print(item['yyyymm'])
    print()

44722
75991
1111
종로구
창덕궁
1
서울특별시
201112

0
11017
1111
종로구
운현궁
2
서울특별시
201112

In [39]:
year = []
sido = []
place = []
foreigners = []
total = []

for item in data:
    foreigners.append(item['ForNum'])
    total.append(item['NatNum'])
    place.append(item['resNm'])
    sido.append(item['sido'])
    year.append(item['yyyymm'])

tour_info = dict(년월=year, 시도=sido, 장소=place, 외국인=foreigners, 전체방문=total)

In [35]:
import pandas as pd

In [41]:
df = pd.DataFrame(tour_info)
df.head()

       년월     시도   장소     외국인    전체방문
0  201112  서울특별시  창덕궁   44722   75991
1  201112  서울특별시  운현궁       0   11017
2  201112  서울특별시  경복궁  132399  237330
3  201112  서울특별시  창경궁    3133   21267
4  201112  서울특별시   종묘   18226   24223

* 딕셔너리를 바로 만들어서 데이터프레임으로 변환
* key, value를 직접 할당해서 딕셔너리 만들기

In [46]:
result = {}
for key in data[0]:
    value_list = []
    for item in data:
        value_list.append(item[key])
    print(key, value_list)
    result[key] = value_list
    
result

ForNum [44722, 0, 132399, 3133, 18226, 0, 0, 13935, 0, 10, 0, 0, 5214, 333, 4704, 52484, 27814, 546, 105370, 1451, 8817, 13033, 1138, 11151, 0, 15, 6625, 0, 24492, 62, 66868, 25550, 101942, 1986, 6048, 9083, 13282, 6, 6732, 0, 43129, 16, 1445, 29928, 129946, 1693, 3891, 7195, 14723, 12, 6263, 0, 42443, 5, 823, 33342, 170379, 1783, 3406, 13127, 15197, 16, 5588, 0, 29520, 3, 492]
NatNum [75991, 11017, 237330, 21267, 24223, 233828, 93554, 52140, 61115, 1885, 32412, 19308, 6956, 1823, 16634, 642290, 28061, 5978, 133012, 15722, 8068, 227077, 78179, 44855, 213467, 1252, 14090, 18881, 9167, 860, 670056, 38553, 145544, 20035, 13896, 286992, 99301, 706, 14607, 23245, 11886, 1248, 11890, 41561, 190501, 19473, 5951, 258781, 44272, 486, 27205, 24527, 7478, 1036, 8869, 59738, 148961, 27172, 14936, 281457, 68749, 2221, 44232, 22587, 8822, 1647, 14454]
addrCd [1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1171, 1111, 1111, 1111, 1111, 1111, 1117, 1111, 1114, 1114, 1135, 1141, 1141, 1144, 1165, 1171, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168, 1111, 1111, 1111, 1111, 1117, 1114, 1135, 1141, 1141, 1144, 1165, 1168]
gungu ['종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '송파구', '종로구', '종로구', '종로구', '종로구', '종로구', '용산구', '종로구', '중구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '송파구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구', '종로구', '종로구', '종로구', '종로구', '용산구', '중구', '노원구', '서대문구', '서대문구', '마포구', '서초구', '강남구']
resNm ['창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '롯데월드', '창덕궁', '운현궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '서울역사박물관', '덕수궁', '서울시립미술관 본관', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '롯데월드', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉', '창덕궁', '경복궁', '창경궁', '종묘', '국립중앙박물관', '덕수궁', '태릉 ·  강릉 · 조선왕릉전시관', '서대문형무소역사관', '서대문자연사박물관', '트릭아이미술관', '헌릉ㆍ인릉', '선릉·정릉']
rnum [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
sido ['서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시', '서울특별시']
yyyymm ['201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201112', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201212', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201312', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201412', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512', '201512']

In [48]:
result_df = pd.DataFrame(result)
result_df

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

* setdefault 함수를 이용해 만들기

In [52]:
dic_result = {}
for dicts in data:
    for key, value in dicts.items():
        # print(key,value)
        dic_result.setdefault(key, []).append(value) # key가 있으면 그냥 없으면 [] 생성
dic_result

{'ForNum': [44722,
  0,
  132399,
  3133,
  18226,
  0,
  0,
  13935,
  0,
  10,
  0,
  0,
  5214,
  333,
  4704,
  52484,
  27814,
  546,
  105370,
  1451,
  8817,
  13033,
  1138,
  11151,
  0,
  15,
  6625,
  0,
  24492,
  62,
  66868,
  25550,
  101942,
  1986,
  6048,
  9083,
  13282,
  6,
  6732,
  0,
  43129,
  16,
  1445,
  29928,
  129946,
  1693,
  3891,
  7195,
  14723,
  12,
  6263,
  0,
  42443,
  5,
  823,
  33342,
  170379,
  1783,
  3406,
  13127,
  15197,
  16,
  5588,
  0,
  29520,
  3,
  492],
 'NatNum': [75991,
  11017,
  237330,
  21267,
  24223,
  233828,
  93554,
  52140,
  61115,
  1885,
  32412,
  19308,
  6956,
  1823,
  16634,
  642290,
  28061,
  5978,
  133012,
  15722,
  8068,
  227077,
  78179,
  44855,
  213467,
  1252,
  14090,
  18881,
  9167,
  860,
  670056,
  38553,
  145544,
  20035,
  13896,
  286992,
  99301,
  706,
  14607,
  23245,
  11886,
  1248,
  11890,
  41561,
  190501,
  19473,
  5951,
  258781,
  44272,
  486,
  27205,
  24527,
  7478,
  1036,
  8869,
  59738,
  148961,
  27172,
  14936,
  281457,
  68749,
  2221,
  44232,
  22587,
  8822,
  1647,
  14454],
 'addrCd': [1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1171,
  1111,
  1111,
  1111,
  1111,
  1111,
  1117,
  1111,
  1114,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1171,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168,
  1111,
  1111,
  1111,
  1111,
  1117,
  1114,
  1135,
  1141,
  1141,
  1144,
  1165,
  1168],
 'gungu': ['종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '종로구',
  '중구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '송파구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구',
  '종로구',
  '종로구',
  '종로구',
  '종로구',
  '용산구',
  '중구',
  '노원구',
  '서대문구',
  '서대문구',
  '마포구',
  '서초구',
  '강남구'],
 'resNm': ['창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '롯데월드',
  '창덕궁',
  '운현궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '서울역사박물관',
  '덕수궁',
  '서울시립미술관 본관',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '롯데월드',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉',
  '창덕궁',
  '경복궁',
  '창경궁',
  '종묘',
  '국립중앙박물관',
  '덕수궁',
  '태릉 ·  강릉 · 조선왕릉전시관',
  '서대문형무소역사관',
  '서대문자연사박물관',
  '트릭아이미술관',
  '헌릉ㆍ인릉',
  '선릉·정릉'],
 'rnum': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12],
 'sido': ['서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시',
  '서울특별시'],
 'yyyymm': ['201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201112',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201212',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201312',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201412',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512',
  '201512']}

In [50]:
d2 = {}
d2.setdefault("key",3)
d2

{'key': 3}

In [53]:
dic_result_df = pd.DataFrame(dic_result)
dic_result_df

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]