국민은행 앱 사용자 리뷰 데이터 JSON 파일을 읽어와서 csv 파일로 변환하기

In [66]:
import json
import pandas as pd

In [67]:
with open("./data/com_kbstar_kbbank.json", 'r', encoding = 'utf-8') as file:
    data = file.read()

In [68]:
reviews = json.loads(data)
len(reviews)

2223

In [69]:
reviews[6]

{'사용자': '이이민우',
 '별점': '3',
 '리뷰': '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
 '날짜': '2025년 3월 3일',
 '개발자 응답': None}

In [7]:
review_dict = {}

for dict in reviews:
    for key, value in dict.items():
        review_dict.setdefault(key,[]).append(value)

In [11]:
review_dict_df = pd.DataFrame(review_dict)
review_dict_df.head()

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...

In [15]:
result = {}
for key in reviews[0]:
    temp = []
    for review in reviews:
        if key == '별점':
            temp.append(int(review[key]))
        else:
            temp2 = str(review[key]).replace('!',' ').replace('.',' ').replace(',',' ')
            temp.append(temp2)
    result[key] = temp
len(result['별점'])
df = pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다 현금이나 실물 ...,2025년 3월 2일,고객님 안녕하세요 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으...
1,윤태경,5,KB스타뱅킹 입출금계좌를 가입한 후 전반적으로 매우 만족스러운 경험을 했습니다 ...,2025년 1월 20일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임 그리고 메뉴이동도 불편함 뒤로가...,2025년 1월 14일,안녕하세요 고객님 KB스타뱅킹 이용에 불편을 드려 죄송합니다 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요 KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만 네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요 KB스타뱅킹 이용에 불편을 드려 죄송합니다 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,고객님 안녕하세요 KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다 앱 이용 ...

# 치킨집

In [77]:
with open("./data/전국치킨집리스트.json", 'r', encoding = 'utf-8') as file:
    data2 = file.read()

In [78]:
reviews2 = json.loads(data2)
len(reviews2)

37

In [17]:
# 기본적으로 header와 body가 있음 그 중 정보는 body에 위치
reviews2[0]['body'].keys()

dict_keys(['items', 'numOfRows', 'pageNo', 'totalCount'])

In [32]:
# body는 dict 형식으로 그 중 items에 개별 가게 정보가 담겨있음
# items는 list 형식으로 모든 리스트가 동일한 키를 가짐
reviews2[0]['body']['items'][0].keys()

dict_keys(['bizesId', 'bizesNm', 'brchNm', 'indsLclsCd', 'indsLclsNm', 'indsMclsCd', 'indsMclsNm', 'indsSclsCd', 'indsSclsNm', 'ksicCd', 'ksicNm', 'ctprvnCd', 'ctprvnNm', 'signguCd', 'signguNm', 'adongCd', 'adongNm', 'ldongCd', 'ldongNm', 'lnoCd', 'plotSctCd', 'plotSctNm', 'lnoMnno', 'lnoSlno', 'lnoAdr', 'rdnmCd', 'rdnm', 'bldMnno', 'bldSlno', 'bldMngNo', 'bldNm', 'rdnmAdr', 'oldZipcd', 'newZipcd', 'dongNo', 'flrNo', 'hoNo', 'lon', 'lat'])

In [29]:
reviews2[1]['body']['totalCount']

36064

In [76]:
chick_dict = {}

for list in reviews2:
    for list2 in list['body']['items']:
        for key, value in list2.items():
            chick_dict.setdefault(key,[]).append(value)

In [38]:
reviews2[0]['body']['items'][0]['bizesNm']

'장모님치킨가창점'

In [45]:
reviews2[0]['body']['items'][0]['ctprvnCd']

'27'

In [50]:
chick_dict['bizesNm']

['장모님치킨가창점',
 '짱구피자치킨',
 '쭈노치킨',
 '치킨뱅이',
 '치킨월드율량점',
 'KFC',
 '토마토두마리치킨',
 '페리카나치킨연수우성체인점',
 '페리카나치킨벽산분점',
 '페리카나치킨',
 '피자앤닭컴',
 '하림치킨',
 '핫썬치킨옥동점',
 'BHC치킨',
 '치킨아이',
 '더화덕',
 '월드양념통닭',
 'BBQ치킨',
 '치킨마루',
 '교촌치킨',
 '새때치킨대산점',
 '본스치킨',
 '치킨매니아',
 '둘둘치킨',
 '굽네치킨',
 'BHC치킨',
 '교촌',
 '맛있는파닭',
 '보드람치킨',
 '오븐에꾸운닭',
 'BBQ치킨완주3공단점',
 '자담치킨앤호프카페',
 '교촌치킨',
 '페리카나중곡2점',
 '땡큐맘치킨',
 '이맛치킨',
 '쥬라기치킨',
 '네네치킨',
 '티바두마리치킨',
 '교촌치킨',
 '지코바양념치킨',
 '페리카나치킨',
 '자연담은치킨',
 '굽네치킨',
 '교촌치킨',
 '교촌치킨',
 'BBQ치킨',
 '노랑통닭',
 '꿀닭',
 '에디슨DHA치킨',
 'BBQ치킨',
 '꿀닭',
 '페리카나치킨삼척당저점',
 '다져스치킨',
 '오븐에꾸운닭',
 '동키치킨',
 'BHC치킨',
 '네네치킨',
 '네네치킨',
 '또래오래',
 '에디슨DHA치킨하안점',
 '통티닭강정',
 '멕시칸치킨',
 '처갓집양념치킨',
 'BBQ치킨',
 '구어스치킨',
 '꿀닭화명점',
 '깐부치킨',
 '코리안숯불바베큐',
 '부어치킨만수6동점',
 '페리카나치킨',
 '교촌치킨',
 '달콤한닭강정',
 'BHC치킨',
 '에디슨DHA치킨',
 '교촌치킨중계역점',
 '페리카나',
 '닭사부',
 '네네치킨상암점',
 'KFC서초우성점',
 '다기야',
 '도깨비치킨',
 '부어치킨작전서운동점',
 '멕시카나동삼점',
 'BHC치킨익산동산점',
 'BBQ치킨상모사곡점',
 '멕시칸치킨동부보성점',
 '지코바숯불양념치킨충주1호점',
 '쓰리피치킨',
 'BHC치킨정읍수성점',
 '페리카나',
 '치킨매니아부산화명점',
 'BHC치킨광주일곡점',
 '호식이두마리치킨화정점',
 '멕시칸치킨창신점',
 '에디슨DHA치킨남산타운점',
 '에디슨DHA치킨용인신갈지구점',
 '에디슨DHA치킨',
 '멕시카나비산점',
 '에디슨DHA치킨양주자이점',
 '강정이가기가막혀율량사천점',
 '맘스터치목동2호점',
 '페리카나삼천점',
 '멕시카나토평점',
 '치킨신드롬쌍문1호',
 '처갓집양념치킨',
 '페리카나평촌2점',
 '속초닭강정',
 '아프리카치킨',
 '큰통치킨',
 'BBQ치킨',
 '구어조은닭가경점',
 '페리카나청주영동점',
 'BBQ치킨용인상현점',
 'BHC치킨오산원동점',
 '맘스터치화명점',
 '치킨678전주아중점',
 '맥켄치킨',
 '쪼끼군다리치킨',
 '부어치킨영광읍점',
 '멜롱닭',
 '치킨매니아산본2호점',
 '라이스팡조치원점',
 '치킨매니아정릉1호점',
 '멕시카나',
 '굽자나조치원점',
 '페리카나신원당점',
 'BBQ치킨화정달빛마을점',
 'BHC치킨신포점',
 '치킨678대전가오점',
 '부어치킨도담마을점',
 '가보세통닭',
 '네네치킨삼학점',
 '지코바숯불양념치킨',
 '감사합니닭',
 'BBQ치킨',
 'BBQ치킨',
 '교촌치킨',
 'BBQ치킨김해외동점',
 '컬투치킨덕소사랑1호점',
 '티바두마리치킨',
 '가마로강정',
 '클레어수제치킨',
 '옛날통닭노형점',
 '조선통닭',
 '마일드치킨',
 'BHC치킨',
 '돈치킨',
 '놀부옛날통닭퇴계1호점',
 '치킨반장',
 '비에이치시',
 'BBQ치킨',
 'BBQ치킨',
 '바른치킨',
 '호야옛날통닭',
 '꼬꼬집합소',
 'BHC치킨',
 '6일닭강정',
 '피자샵해남점',
 '학성통닭',
 '경아두마리치킨',
 '디디치킨석동점',
 '옛날통닭',
 '옛날가마솥시골통닭',
 '맥켄치킨',
 '교촌치킨',
 '소문난통닭5900',
 '또봉이통닭',
 '교촌치킨곤지암점',
 '조선의옛날통닭',
 '치코파닭',
 '놀부옛날통닭용암점',
 '서가마통닭',
 '1988추억의통닭',
 '호식이두마리치킨',
 '네네치킨',
 '멕시카나치킨',
 'BBQ치킨',
 '먹방',
 '교촌치킨',
 '화계치킨',
 '바른치킨',
 '네네치킨',
 '충만치킨오류점',
 '용천옛날통닭',
 '송원닭집',
 '신화치킨',
 '네네치킨',
 'BHC치킨',
 '옛날통닭',
 '고담치킨',
 '미소치킨',
 '써니치킨',
 '치킨퐁백운점',
 '네네치킨',
 '옛날통닭',
 '옛날통닭지귀점',
 '부어치킨노암점',
 '홍치킨',
 '태진티앤디',
 '치킨더비',
 '믹스밥',
 '북일치킨',
 '호식이두마리치킨신시가지점',
 'BHC치킨',
 'KFC',
 '옛날통닭',
 '두리통닭',
 '용안통닭',
 '허선생치킨',
 '지코바양념치킨송도점',
 '다겐닭스',
 '바르닭치킨',
 '가마솥치킨',
 '유나네후다닭통닭',
 '8800켄터키치킨',
 '놀부옛날통닭',
 'BHC치킨',
 '호치킨하우스',
 '깐부치킨',
 '티바두마리치킨',
 '처가집',
 'BHC치킨',
 '또봉이통닭',
 '호식이두마리치킨',
 '호식이두마리치킨',
 '명품통닭',
 '멕시카나',
 '디디치킨',
 '충만치킨',
 '박군치킨',
 '장모님옛날통닭',
 '딸부자네통닭',
 '꽃보다치킨',
 '호치킨',
 '노랑통닭',
 '교촌치킨풍호점',
 'BHC치킨',
 'BHC치킨',
 '미쳐버린파닭',
 '통닭원5900',
 'BHC치킨우석대점',
 '처갓집양념치킨',
 '한국통닭',
 '옛날통닭',
 '파닭파닭',
 '옛날통닭여상점',
 '추억의옛날통닭',
 '시골통닭',
 '네네치킨합천점',
 '윤가네옛날통닭',
 '옛날통닭새벽닭',
 '옛날통닭',
 '위키드스노우썬더치킨',
 'BBQ치킨',
 '신통치킨',
 '영달이두마리치킨',
 '오븐愛통닭',
 '교촌치킨',
 'BBQ치킨',
 'BHC치킨중산사월점',
 '필바든치킨소사벌점',
 '산동요리점',
 '구통치킨칠곡읍내점',
 '치킨처럼',
 '또닭또닭',
 '큐스',
 '더썬치킨남',
 'BBQ치킨',
 '디디치킨',
 '노랑통닭',
 '한국통닭',
 '옛날통닭',
 'BHC치킨',
 '그집마늘치킨신평점',
 '가마로강정정림점',
 '지코바양념치킨',
 '치킨퐁',
 '치킨아지트',
 '짱치킨',
 'BHC치킨도봉점',
 '신나계옛날통닭',
 'BBQ치킨',
 '고기굽는남자',
 '경성옛날통닭',
 '치킨통',
 '달구치킨',
 'Bhc치킨',
 '바른치킨여주대점',
 '못말리는파닭',
 '땅땅치킨',
 '투존치킨',
 '네네치킨함열점',
 '처갓집양념치킨',
 '꼴통닭선생',
 'BHC치킨',
 '본스치킨',
 '중앙통닭',
 '그시절옛날통닭',
 '동래통닭',
 '노랑통닭',
 '태양치킨',
 '치킨매니아',
 '멕시카나치킨',
 '신통치킨',
 'BHC치킨불국점',
 'BBQ치킨',
 '홀릭옛날통닭',
 '진미통닭',
 '명품통닭',
 '또봉이통닭',
 '국빈치킨',
 '네네치킨',
 '대구통닭',
 '60계치킨',
 '유강옛날통닭',
 '황제두마리치킨',
 'TG원닭강정',
 '우리동네닭집탕정',
 '삼대가옛날통닭',
 '티바두마리치킨',
 '천년지기',
 '노랑통닭',
 '가마로강정',
 '가마로강정',
 '박군치킨',
 '허갈닭강정',
 '옛날시골통닭',
 '노랑통닭',
 '교촌치킨',
 '투마리치킨',
 '구통치킨',
 '치킨아이',
 '옛날통닭',
 '신통치킨',
 'BHC치킨',
 '정원치킨',
 '이서방양념치킨',
 '신둔페리카나',
 '좋은통닭',
 '람스두마리치킨',
 '승리의통닭',
 '호로록통닭',
 '울랄라바베큐',
 '깻잎두마리치킨남악점',
 '왕천파닭',
 '황당한치킨용이점',
 '부라더짬뽕치킨',
 '돈치킨',
 '호식이두마리치킨',
 '시장통닭',
 '한앤둘치킨',
 'BHC치킨',
 '상문이숯불두마리치킨신안평거점',
 '또래오래삼성점',
 '명품옛날시골통닭',
 '쌀통닭',
 '또봉이통닭오산운암점',
 '꿈애본통닭',
 '치킨더홈',
 '켄지',
 'BBQ치킨',
 'BHC치킨',
 'TeaCup',
 '옛날통닭',
 '가마솥옛날통닭',
 '치킨마루',
 '든든치킨',
 '공룡치킨',
 '투존치킨교암점',
 '시장통닭',
 '처갓집양념치킨.명가치킨',
 'BBQ치킨제주봉개점',
 '호식이두마리치킨',
 'BHC치킨',
 '치킨처럼',
 'BHC치킨',
 '왕대벌치킨',
 '다모아식당치킨호프',
 '옛날통닭',
 '동큐치킨',
 '쌍파닭',
 '와우치킨',
 '꿈에본닭',
 '둘리치킨',
 '멕시칸치킨',
 '씨앤에프후라이드치킨',
 '멕시칸치킨',
 '맥스양념치킨',
 '맥시칸양념통닭',
 '맥시칸양념통닭',
 '헬로순살치킨',
 '리스치킨',
 '멕시칸치킨',
 '예스굿치킨',
 '멕시칸치킨',
 '놀부살로만치킨',
 '샤르망치킨호프',
 '돈치킨',
 '꼬꼬네치킨호프',
 '에그파파치킨박달점',
 '교촌치킨',
 '알라디아치킨',
 '페리카나홍제점',
 '깨돌치킨',
 'BHC치킨원앙행복점',
 '조광심민속왕순대',
 '신날개',
 '오븐에빠진닭',
 '토토안동선계찜닭',
 '누룽지통닭구이',
 '공항치킨',
 '티바두마리치킨옥정점',
 '진미가마솥통닭',
 '페리카나혁신도시점',
 '마장동육회포차앤문어흑형치킨',
 '불로불러정남점',
 'BBQ치킨광주화정점',
 '훌랄라참숯바베큐치킨곤지암리조트점',
 '본투비마늘치킨종로5가점',
 '고대삼성삼통치킨',
 '통큐치킨',
 'BHC치킨오천고천점',
 '팜치킨호프',
 '김가네얼큰이',
 '목포시장닭집',
 '바니치킨호프',
 '발리두번째이야기',
 '캠프치킨',
 '지코바양념치킨',
 '네네치킨서귀포2호점',
 '치킨신드롬',
 '두존두마리치킨',
 '멕시카나순성점',
 '디디치킨',
 '호식이두마리치킨읍내점',
 'BBQ치킨아침고요수목원점',
 '장모님치킨삼랑진점',
 '계림원누룽지통닭구이부평점',
 '페리카나',
 '피자나라치킨공주부천약대점',
 '야들리애치킨',
 '삼삼S치킨',
 '허갈닭강정용운점',
 '쌀통닭금호1호점',
 '거성치킨',
 '얼큰이통닭',
 '닭집',
 '매운찜닭',
 '페리카나',
 '바투치킨',
 '멕시칸치킨',
 '아쁘리까',
 '신하양념치킨',
 '교촌치킨',
 'BBQ치킨',
 '굿타임페리카나',
 '코리엔탈깻잎치킨',
 '페리카나',
 '굿모닝피자치킨',
 '교촌치킨',
 '처갓집양념치킨안정점',
 '멕시칸치킨',
 '두존두마리치킨문덕오천점',
 '장모님치킨',
 '또래오래',
 '지코바숯불치킨장평점',
 '훌랄라참숯바베큐치킨송담점',
 '멕시칸치킨',
 '옛날통닭',
 '킴스바베큐',
 '쌀개통닭',
 '연동치킨호프',
 '더착한79치킨충남대점',
 '만남치킨&호프',
 '삼오통닭호프',
 '양키즈',
 '대구통닭',
 '맘스터치안지랑역점',
 '페리카나강구점',
 '피자나라치킨공주',
 '시골통닭',
 '36계누룽지통닭구이',
 '동키치킨',
 '달리는꼬꼬숯불치킨',
 '노랑통닭',
 '굽네치킨난지캠핑장점난지캠핑장점',
 '굽네치킨',
 '굽네치킨율하점',
 '굽네치킨여수관문점',
 '굽네치킨내수점',
 '굽네치킨광주하나로클럽점',
 '멕시카나치킨진영점',
 '굽네치킨',
 '다가올레신흥점',
 '굽네치킨',
 '굽네치킨길음동점',
 '꼴깍치킨BeerPub',
 '누나홀닭구로디지털단지역점',
 '호치킨하우스',
 '지코바치킨주례점',
 '롱다리치킨',
 '동키치킨',
 '교촌치킨후암점',
 '코리엔탈깻잎치킨',
 '하림맥시칸치킨',
 '굽네치킨',
 '영월치킨',
 '노랑통닭수성점',
 '핍치스두마리치킨',
 '굽네치킨합덕점',
 '굽네치킨주월점',
 '굽네치킨',
 '굽네치킨길동점',
 '굽네치킨경복궁점',
 '굽네치킨용원웅동점',
 '굽네치킨평화점',
 '굽네치킨녹번점',
 '굽네치킨청담점',
 '굽네치킨계룡점',
 '굽네치킨',
 '굽네치킨',
 '굽네치킨',
 '굽네치킨상계6,7동점',
 '교원파닭',
 '굽네치킨형곡점',
 '치킨아이',
 '훌랄라참숯바베큐치킨',
 '꼬끼오옛날통닭',
 '맘스터치',
 'BHC치킨청평점',
 '땡큐맘',
 '멕시칸치킨터미널점',
 '오롯이닭',
 '터줏대감고창본점',
 '굽네치킨',
 '길손닭집',
 'BBQ치킨',
 'KFC',
 '지코바숯불치킨화명2호점',
 '이승윤의알통떡강정신탄진점',
 '또래오래방촌점',
 '또봉이통닭파주우정한울점',
 '화통치킨진보점',
 '대왕파닭',
 '맥시칸양념치킨체인본부점',
 '이젠닭',
 '처갓집',
 '오늘은닭이랑',
 '참숯불에꾸운닭',
 '우리동네꼴깍치킨입석점',
 '그냥통닭',
 '오복마늘통닭',
 '오븐에빠진닭공주대점',
 '처갓집양념치킨남면점',
 '다사랑담양점',
 'KFC둔산이마트점',
 '우리동네꼴깍치킨',
 '꼬꼬리아',
 '처갓집',
 'KFC금정이마트',
 '아주커치킨',
 '코리엔탈깻잎치킨',
 '옛날통닭',
 '굽네치킨',
 '꼬키오',
 '무등통닭',
 '대왕통닭',
 '박군치킨남양점',
 '딥스치킨',
 '박군치킨병점동점',
 '써핑치킨엔호프수완직영점',
 'KFC',
 '아주커치킨',
 '굽네치킨',
 '호식이두마리치킨송내1호점',
 '자담치킨',
 '굽네치킨',
 '교촌치킨',
 '가마로강정',
 '페리카나치킨수완점',
 '네네치킨',
 'BHC치킨검산점',
 '굽네치킨오금점',
 '훌랄라참숯바베큐치킨고창1점',
 '빅투치킨진천읍점',
 '굽네치킨거제장승포점',
 '팔팔통닭',
 '가마로강정',
 '놀부옛날통닭',
 '구어조은닭처갓집양념치킨',
 'BHC치킨비에이치씨월곡점',
 '구어조은닭',
 '네네치킨',
 '뉴멕시칸',
 '치킨나라석남본점',
 '네네치킨',
 '교촌치킨',
 '교촌치킨',
 '멕시카나',
 '멕시칸치킨',
 '땡큐맘치킨전주평화점',
 '굽네치킨',
 '네네치킨',
 '네네치킨계양사동점',
 '네네치킨학장.엄궁점',
 '멕시카나치킨',
 '맘스터치능곡점',
 '멕켄치킨',
 '멕시칸치킨',
 '또래오래동삼점',
 '또봉이통닭',
 '멕시카나치킨',
 '충만치킨',
 'BHC치킨정자중앙점',
 '처갓집양념치킨',
 'BBQ치킨',
 '사쿠사쿠',
 'BHC치킨반곡점',
 '부어치킨',
 '또봉이통닭',
 '치킨촌',
 'BBQ치킨',
 '부천남자치킨',
 '화르화르',
 'BHC치킨',
 '문정시영아파트관리소',
 '새나라치킨',
 '동키치킨제천점',
 '굽네치킨순천1호점',
 '하림맥시칸',
 '치킨뱅이',
 '땡큐치킨',
 '팬클럽치킨',
 '이서방통닭',
 '극동평화아파트관리사무소',
 '진미통닭',
 '가마로강정',
 '수제통닭',
 '멕시칸치킨',
 '시골양념통닭',
 '처갓집통닭',
 'BBQ치킨',
 '윙윙',
 '페리카나치킨',
 '오븐마루',
 '쭈노치킨',
 '훌랄라참숯바베큐궐동서',
 'BBQ치킨',
 '갈래또바베큐치킨',
 '둘둘치킨',
 'BBQ치킨',
 'BHC치킨화성봉담점',
 '멕시칸치킨호프',
 '꼬꼬두마리치킨',
 '범동페리카나',
 '비에이치시치킨',
 '부가네얼큰이',
 '남해통닭',
 'BBQ치킨',
 'BBQ치킨',
 '또래오래',
 '또래오래',
 '또래오래안동중앙점',
 '불로만숯불바베큐',
 '멕시칸치킨',
 '멕시칸치킨',
 '하림맥시칸',
 '호식이두마리치킨',
 '하림맥시칸',
 '네네치킨',
 '꼬추닥치킨',
 '바른치킨',
 '옛날수제통닭',
 '맥캔치킨',
 '와커치킨',
 '깐부치킨선정릉역점',
 '굽네치킨',
 '땡큐맘치킨',
 '또래오래',
 '림스치킨',
 '성원',
 '강정이기가막혀미평봉계점',
 '멕시칸치킨',
 'BHC치킨',
 'BHC치킨',
 '치킨사냥',
 '오븐에꾸운닭',
 '티바두마리치킨불로봉무점',
 '포촌치킨',
 '화통치킨',
 '또래오래',
 '홍희통닭',
 '하림맥시칸.',
 '옛날통닭',
 '옛날통닭',
 '페리카나',
 '치코파닭',
 'BHC치킨',
 '더참한통닭',
 'BBQ치킨',
 'BHC치킨',
 '처갓집양념치킨',
 'BHC치킨',
 '추억의옛날통닭',
 'BHC치킨',
 '쭈노치킨',
 '티바두마리치킨',
 '치킨본점',
 '또봉이통닭',
 '투싼',
 '디디치킨',
 '처갓집',
 '체스터후라이드치킨',
 '치킨밸리',
 '박군치킨',
 '영심이양념치킨호',
 '하우스홀드',
 '다사랑',
 '코리안숯불닭바베큐동천',
 '다사랑',
 '바비큐보스',
 '멕시칸치킨',
 '동키치킨',
 '굽네치킨',
 '페리카나',
 '네네치킨',
 '굽는치킨',
 '퓨전부영통닭',
 '루시',
 '마슬랜',
 '문동치킨',
 '교촌치키니',
 '닥큐치킨',
 '코리안바베큐',
 '반반무마니',
 '다사랑',
 '누나홀닭',
 '호식이두마리치킨충주1호',
 '그린팜치킨',
 '퀸통닭',
 '알통떡강정',
 '경아두마리치킨',
 '또봉이통닭',
 '두리닭강정',
 '썬더치킨',
 '치킨몰',
 '바른치킨',
 '멕시칸치킨',
 'KFC구서점',
 '또봉이통닭',
 '바른치킨',
 '옛날통닭',
 '박군치킨',
 '오케이치킨',
 'BHC치킨',
 '페리카나',
 '봉이치킨낙산점',
 'olleh',
 '백록통닭',
 '충만치킨',
 '페리카나12.13단지점',
 '페리카나',
 '계림원누룽지통닭구이',
 '하림양념통닭',
 '페리카나북변점',
 '파닭파닭',
 '하림멕시칸',
 '하림멕시칸',
 '멕시카나나운2지곡점',
 '털보네치킨호프',
 '아이커치킨돌산점',
 '비에이치시치킨',
 '훌랄라참숯바베큐',
 '중앙닭집',
 '호식이두마리치킨정왕1호점',
 '페리카나치킨',
 '치킨뱅이',
 '치킨뱅이',
 'BBQ치킨봉산점',
 'BBQ치킨',
 '멕시카나치킨',
 '순실로치킨',
 '세원양념치킨',
 '처갓집양념치킨',
 '처갓집양념치킨',
 '준열정육점.치킨',
 '체니코스',
 '우리집치킨',
 '와커치킨',
 '유진바베큐치킨',
 '처갓집치킨',
 '위드치킨',
 '디디치킨',
 '신제주치킨하우스',
 '북청닭강정처갓집양념통닭교동점',
 '아주커치킨풍암1점',
 '에디슨',
 '옹헤야숯불바베큐동탄7점',
 '치킨더홈',
 '칸꼬시부영점',
 '최가네',
 '치킨런',
 '소문난통닭',
 '페리카나치킨',
 '땅땅치킨호프',
 '티바두마리치킨',
 '훌랄라참숯바베큐',
 '또봉이통닭카페',
 '홀썸치킨',
 '누릉지통닭구이강릉점',
 '88켄터키',
 '잉치킨',
 'BBQ치킨',
 '페리카나',
 '교촌하숙',
 '철인7호',
 '소스와꼬꼬',
 '굿모닝살로치킨',
 '삼익통닭',
 '맘스터치',
 '교촌치킨답십리1호점',
 '멕시칸양념통닭',
 '노나네치킨',
 'BBQ치킨',
 'BBQ치킨',
 'BBQ치킨교하가온점',
 '네네치킨피자',
 '맥스치킨',
 '멕시칸양념통',
 '교촌산림계',
 '광주통닭',
 '치킨하우스',
 '광주통닭',
 'BBQ치킨',
 '네네치킨',
 '대광토탈키친',
 '본스치킨',
 '수성치킨',
 '페리카나운정2점',
 '헝그리파닭',
 '굽네치킨원통점',
 '화홍통닭',
 '옛날통닭',
 'BHC치킨',
 '굽네외동점',
 '송원바베큐치킨도청오룡점',
 '충만치킨',
 '치킨먹는날',
 '돈치킨',
 '못난감자앤치킨',
 'BHC치킨광주진월점',
 '밀밭',
 '티바치킨앤새우신갈직영점',
 '썬더치킨',
 '옛날통닭외도점',
 'BHC치킨',
 '더참한통닭',
 '노랑통닭',
 '노랑통닭',
 '멕시카나',
 'KFC',
 '바른치킨',
 '치킨테라스',
 '광령치킨',
 '추억의통닭',
 '착한통닭',
 '태권치킨',
 '호식이두마리치킨',
 '네네치킨칠성점',
 '썬더치킨',
 '별꽃향기치킨',
 '투존치킨',
 '지코바양념치킨',
 '옛날통닭',
 '전설의치킨',
 '우리들치킨',
 'BHC치킨',
 '815켄터키후라이드치킨',
 '일곡치킨',
 '자담치킨',
 '치코파닭&굽는치킨',
 '옛날수제통닭',
 '교촌치킨',
 '프라이앤치킨',
 '호식이두마리치킨',
 '콩닭',
 '잿등통닭',
 'BHC치킨',
 '퓨전치킨바베큐',
 '굽네치킨',
 '경원치킨본점',
 '금강두마리치킨',
 'BBQ치킨',
 '제석로시장통닭당리7호',
 '충만치킨숙대점',
 '푸라닭',
 '비애이치씨',
 '맛깔집앤치킨',
 '굿닭치킨',
 '멕코이치킨',
 'BHC치킨독산맛나거리점',
 '투존치킨',
 '노성삼촌치킨',
 '또봉이통닭',
 '떴다파닭',
 '호식이두마리치킨신당점',
 'BHC치킨',
 '소프트치킨',
 '호야옛날통닭와수점',
 '불티나는닭강정',
 '네네치킨',
 '또봉이통닭',
 '통닭',
 '동홍옛날통닭',
 'BHC치킨',
 '김철이팥죽',
 '위너스치킨',
 '촌닭이두마리',
 '딸보치킨',
 '노랑통닭',
 '부어치킨관동대점',
 '왕파골뱅이&수제치킨',
 '치킨파티',
 '지코바양념치킨',
 'BHC치킨송정역점',
 '호식이두마리치킨',
 '페리카나치킨',
 '왕애두마리치킨',
 'BBQ치킨',
 'BBQ치킨',
 'BBQ치킨',
 '옛날통닭',
 '보드람치킨',
 'BBQ치킨',
 '네네치킨',
 'BBQ치킨',
 'BBQ치킨',
 '용천통닭',
 '호야옛날통닭',
 '마이마이치킨',
 '디디치킨',
 '아리아리닭강정',
 '충만치킨',
 'AUGUSTCHICKEN',
 '치킨소리',
 '매포옛날통닭',
 '봉이치킨',
 'BHC치킨',
 '굽네치킨',
 '처갓집양념치킨',
 '굽네치킨광명34동점',
 'BBQ치킨하단점',
 '허갈닭강정',
 '처갓집양념치킨',
 '치킨스토리',
 '케이준치킨',
 '네네치킨피자',
 '털보닭집',
 '닭포',
 '오유니통닭',
 '감성시대',
 '굽네치킨용산점',
 '쌀민족쌀통닭',
 '호식이두마리치킨',
 'BBQ치킨',
 'BHC치킨',
 'BBQ치킨',
 '강정이기가막혀구로점',
 '썬더치킨삼정점삼정점',
 '치킨짱',
 '푸라닭신제주점',
 'KFC',
 '맛닭꼬',
 '교촌치킨',
 '꼬꼬댁치킨',
 '왕천파닭',
 '알콩닭콩',
 '한국통닭',
 '푸라닭',
 'BBQ치킨올리브치킨호원점',
 '굽네치킨',
 '직화맨치킨걸',
 '서천멕시칸',
 '60계치킨암사선사점',
 'BBQ치킨',
 'BHC치킨',
 '디디치킨',
 '명품통닭선인점',
 '치킨공식',
 '교촌치킨까치산역점',
 '치킨박사두마리치킨',
 '더썬치킨',
 '처갓집통닭',
 '호식이두마리치킨',
 '두두두마리치킨',
 '호식이두마리치킨',
 '또봉이치킨',
 '투마리치킨하늘도시점',
 '노랑통닭',
 ...]

In [54]:
chick_df = pd.DataFrame(chick_dict)
chick_df.head(5)

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816

In [53]:
len(chick_df)

36064

In [75]:
chick_dict_new = {}

for list in reviews2:
    for list2 in list['body']['items']:
        # zip 함수를 통해 묶음
        for key, value in zip(list['header']['columns'], list2.values()):
            chick_dict_new.setdefault(key,[]).append(value)
            
chick_df_new = pd.DataFrame(chick_dict_new)
chick_df_new.head(5)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816

# pandas의 json_normalize를 이용해서 쉽게 json에서 DataFrame으로 만들기

In [79]:
pd.json_normalize(data2[0]['body']['items'])

TypeError: string indices must be integers