In [1]:
import json
import pandas as pd

In [8]:
with open("./data/호텔스닷컴리뷰정리.txt", 'r', encoding = 'utf-8') as file:
    data = file.read()

In [10]:
len(data)

347

In [15]:
print(data)

호텔 인포 테이블
----------------------------------------------------------
hotelId
호텔이름
호텔등급
총리뷰수
평점
청결도 "cleanliness":"8.0",
서비스 "service":"7.6",
편안함 "comfort":"8.2",
시설상태 "condition":"7.8",
주변환경 "neighbourhood":"8.2"
지역 region
시도 locality
----------------------------------------------------------
사용자리뷰 테이블
리뷰일
고객id "itineraryId"
여행타입
평점
리뷰 text

In [84]:
column = ['hotelId', '호텔이름', '호텔등급', '총리뷰수', '평점', '청결도', '서비스', '편안함','시설상태', '주변환경', '지역', '시도']

In [16]:
with open("./data/hotels_korea_reviews_text.json", 'r', encoding = 'utf-8') as file2:
    data2 = file2.read()

In [18]:
hotels = json.loads(data2)
len(hotels)

9027

In [23]:
hotels[0].keys()

dict_keys(['data'])

In [41]:
hotels[101].keys()

dict_keys(['data'])

In [25]:
hotels[0]['data'].keys()

dict_keys(['page', 'suggestedLanguages', 'common', 'body', 'debug'])

In [27]:
hotels[0]['data']['page'].keys()

dict_keys(['html', 'head'])

In [31]:
hotels[0]['data']['page']['head'].keys()

dict_keys(['title', 'links', 'metas', 'linkedData'])

In [32]:
hotels[0]['data']['page']['head']['title']

'거제 상상속의집 (SangSang Hotel) 이용 후기'

In [40]:
hotels[0]['data']['body'].keys()

dict_keys(['pageType', 'pdpHeader', 'breadcrumb', 'welcomeRewards', 'propertyDescription', 'featuredPrice', 'topQueryFormCtaText', 'query', 'reviewContent', 'phoneNumbers', 'miscellaneous'])

In [64]:
hotels[0]['data']['body']['reviewContent'].keys()

dict_keys(['guestFilter', 'filters', 'overall', 'sort', 'pagination', 'reviews', 'navigation'])

In [68]:
# 평점
hotels[0]['data']['body']['reviewContent']['overall']['rating']

'7.8'

### hotels[0]['data']['body']['pdpHeader']

In [52]:
hotels[0]['data']['body']['pdpHeader']

{'backToSRPLink': '/search.do?destination-id=1693260&q-room-0-adults=2&q-rooms=1&q-room-0-children=0',
 'backToSRPText': '거제, 경상남도, 한국의 모든 숙박 시설',
 'hotelId': 1041793024}

In [53]:
# hotelId
hotels[0]['data']['body']['pdpHeader']['hotelId']

1041793024

### hotels[0]['data']['body']['propertyDescription']

In [198]:
hotels[0]['data']['body']['propertyDescription']

{'pdpLink': '/ho1041793024/?q-rooms=1&hotelId=1041793024&display=description',
 'localisedAddress': '경상남도 거제시 일운면 거제대로 2752',
 'address': {'countryName': '한국',
  'locality': '거제시',
  'postalCode': '53326',
  'region': '경상남도',
  'streetAddress': '일운면 거제대로 2752',
  'countryAlpha3Code': 'KOR'},
 'priceMatchEnabled': True,
 'name': '상상속의집 (SangSang Hotel)',
 'starRatingTitle': '3성급',
 'starRating': 3.0}

In [50]:
# 호텔 이름
hotels[0]['data']['body']['propertyDescription']['name']

'상상속의집 (SangSang Hotel)'

In [54]:
# 호텔 등급
hotels[0]['data']['body']['propertyDescription']['starRatingTitle']

'3성급'

In [147]:
# 평점
hotels[0]['data']['body']['reviewContent']['overall']['rating']

'7.8'

In [200]:
# 지역
hotels[60]['data']['body']['propertyDescription']['address']['streetAddress']

'강북구 솔매로 62-3'

In [201]:
# 지역
hotels[56]['data']['body']['propertyDescription']['address']

{'countryName': '한국',
 'locality': '여수시',
 'region': '전라남도',
 'streetAddress': '오동도로 111',
 'countryAlpha3Code': 'KOR'}

In [56]:
# 시도
hotels[0]['data']['body']['propertyDescription']['address']['locality']

'거제시'

### hotels[0]['data']['body']['reviewContent']['overall']

In [71]:
hotels[0]['data']['body']['reviewContent']['overall']

{'selectedFilterType': 'all',
 'scoresFilterParams': [{'key': 'display', 'value': 'reviews'},
  {'key': 'q-rooms', 'value': '1'},
  {'key': 'reviewOrder', 'value': 'date_newest_first'},
  {'key': 'hotelId', 'value': '1041793024'},
  {'key': 'tripTypeFilter', 'value': 'all'},
  {'key': 'reviewTab', 'value': 'brand-reviews'}],
 'rating': '7.8',
 'superb': False,
 'badge': '좋음',
 'badgeTooltipPosition': 'tr',
 'totalCount': 67,
 'scores': [{'score': '10.0',
   'maximumScore': '10',
   'minimumScore': '10',
   'count': 24,
   'url': '/ho1041793024-tr/?scoreFilter=10&display=reviews&q-rooms=1&reviewOrder=date_newest_first&hotelId=1041793024&tripTypeFilter=all&reviewTab=brand-reviews'},
  {'score': '8.0',
   'maximumScore': '9',
   'minimumScore': '8',
   'count': 26,
   'url': '/ho1041793024-tr/?scoreFilter=8&display=reviews&q-rooms=1&reviewOrder=date_newest_first&hotelId=1041793024&tripTypeFilter=all&reviewTab=brand-reviews'},
  {'score': '6.0',
   'maximumScore': '7',
   'minimumScore': '6',
   'count': 8,
   'url': '/ho1041793024-tr/?scoreFilter=6&display=reviews&q-rooms=1&reviewOrder=date_newest_first&hotelId=1041793024&tripTypeFilter=all&reviewTab=brand-reviews'},
  {'score': '4.0',
   'maximumScore': '5',
   'minimumScore': '4',
   'count': 5,
   'url': '/ho1041793024-tr/?scoreFilter=4&display=reviews&q-rooms=1&reviewOrder=date_newest_first&hotelId=1041793024&tripTypeFilter=all&reviewTab=brand-reviews'},
  {'score': '2.0',
   'maximumScore': '3',
   'minimumScore': '1',
   'count': 4,
   'url': '/ho1041793024-tr/?scoreFilter=2&display=reviews&q-rooms=1&reviewOrder=date_newest_first&hotelId=1041793024&tripTypeFilter=all&reviewTab=brand-reviews'}],
 'ratingAspects': {'cleanliness': '8.0',
  'service': '7.6',
  'comfort': '8.2',
  'condition': '7.8',
  'neighbourhood': '8.2'}}

In [72]:
# 평점
hotels[0]['data']['body']['reviewContent']['overall']['rating']

'7.8'

In [73]:
# 총리뷰수
hotels[0]['data']['body']['reviewContent']['overall']['totalCount']

67

In [74]:
hotels[0]['data']['body']['reviewContent']['overall']['ratingAspects']

{'cleanliness': '8.0',
 'service': '7.6',
 'comfort': '8.2',
 'condition': '7.8',
 'neighbourhood': '8.2'}

In [102]:
# 청결도
hotels[9]['data']['body']['reviewContent']['overall']['ratingAspects']['cleanliness']

'10.0'

In [101]:
# 서비스
hotels[9]['data']['body']['reviewContent']['overall']['ratingAspects']['service']

'10.0'

In [146]:
# 편안함
hotels[0]['data']['body']['reviewContent']['overall']['ratingAspects']['comfort']

'8.2'

In [104]:
hotels[9]['data']['body']['reviewContent']['overall']['ratingAspects']

{'cleanliness': '10.0', 'service': '10.0', 'condition': '10.0'}

In [82]:
# 시설상태
hotels[0]['data']['body']['reviewContent']['overall']['ratingAspects']['condition']

'7.8'

In [81]:
# 주변환경
hotels[0]['data']['body']['reviewContent']['overall']['ratingAspects']['neighbourhood']

'8.2'

In [ ]:
column = ['hotelId', '호텔이름', '호텔등급', '총리뷰수', '평점', '청결도', '서비스', '편안함','시설상태', '주변환경', '지역', '시도']

In [237]:
hotel_dic = {}

for key in column:
    hotel_dic.setdefault(key,[])

for li in hotels:
    # hotelId
    if li['data']['body']['pdpHeader']['hotelId'] not in hotel_dic['hotelId']:

        hotel_dic['hotelId'].append(li['data']['body']['pdpHeader']['hotelId'])
        hotel_dic['호텔이름'].append(li['data']['body']['propertyDescription']['name'])
        hotel_dic['호텔등급'].append(li['data']['body']['propertyDescription']['starRatingTitle'])
        hotel_dic['총리뷰수'].append(li['data']['body']['reviewContent']['overall']['totalCount'])
        hotel_dic['평점'].append(li['data']['body']['reviewContent']['overall']['rating'])


        hotel_dic['청결도'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('cleanliness',None))
        hotel_dic['서비스'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('service',None))
        hotel_dic['편안함'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('comfort',None))
        hotel_dic['시설상태'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('condition',None))
        hotel_dic['주변환경'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('neighbourhood',None))


        hotel_dic['지역'].append(li['data']['body']['propertyDescription']['address'].get('region',None))
        hotel_dic['시도'].append(li['data']['body']['propertyDescription']['address']['locality'])

In [149]:
hotel_dic = {}

for key in column:
    hotel_dic.setdefault(key,[])

for li in hotels:
    if li['data']['body']['pdpHeader']['hotelId'] is not in hotel_dic['hotelId']:
        hotel_dic['hotelId'].append(li['data']['body']['pdpHeader']['hotelId'])
        hotel_dic['호텔이름'].append(li['data']['body']['propertyDescription']['name'])
    hotel_dic['호텔등급'].append(li['data']['body']['propertyDescription']['starRatingTitle'])
    hotel_dic['총리뷰수'].append(li['data']['body']['reviewContent']['overall']['totalCount'])
    hotel_dic['평점'].append(li['data']['body']['reviewContent']['overall']['rating'])
    
    
    hotel_dic['청결도'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('cleanliness',"8.0"))
    hotel_dic['서비스'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('service',"7.6"))
    hotel_dic['편안함'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('comfort',"8.2"))
    hotel_dic['시설상태'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('condition',"7.8"))
    hotel_dic['주변환경'].append(li['data']['body']['reviewContent']['overall']['ratingAspects'].get('neighbourhood',"8.2"))
    
    
    hotel_dic['시도'].append(li['data']['body']['propertyDescription']['address']['locality'])
    
    if 'region' in li['data']['body']['propertyDescription']['address'].keys():
        hotel_dic['지역'].append(li['data']['body']['propertyDescription']['address']['region'])
    else:    
        gu = li['data']['body']['propertyDescription']['streetAddress'].split(" ")
        hotel_dic['지역'].append(gu[0])

KeyError: 'streetAddress'

In [238]:
hotel_df = pd.DataFrame(hotel_dic)
hotel_df.head(5)

,hotelId,호텔이름,호텔등급,총리뷰수,평점,청결도,서비스,편안함,시설상태,주변환경,지역,시도
0,1041793024,상상속의집 (SangSang Hotel),3성급,67,7.8,8.0,7.6,8.2,7.8,8.2,경상남도,거제시
1,589827,바다마루 제주 (Badamaru Jeju),2.5성급,20,8.4,9.0,8.4,8.6,8.4,5.0,제주특별자치도,서귀포시
2,589840,아리수 호텔 (Hotel Arisu),3성급,31,8.2,8.2,8.4,8.2,8.2,6.0,경기도,김포시
3,1138393120,힐링모텔 (Healing Motel),2.5성급,10,6.2,6.2,6.2,7.0,6.2,8.0,인천광역시,인천광역시
4,1366851616,동대문 PR 모던 스튜디오 (Dongdaemun PR. Mondern Studio),3성급,1,8.0,10.0,10.0,None,10.0,None,서울특별시,서울특별시

In [203]:
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']

{'groups': [{'items': [{'itineraryId': '72009037635503',
     'brand': 'expedia',
     'genuineMsg': 'Expedia 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2020년 11월 20일',
     'reviewDbDate': '1606003200000',
     'reviewer': {'name': '나미', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '',
     'description': '주차가 객실당 한칸씩 차고가 있는게 굉장히 특이했으며 가장 편리했음.\n간혹 차에 무언가를 두고와서 가지러 가는 경험을 하는데 리조트나 다른 펜션이었다면 주차장까지 내려가는 번거로움이 있었겠지만 이 호텔에서는 객실 바로밑에 주차장이 있어서 주차장이 가장편리 하였다.\n하지만 방음 수준은 최악'},
    {'itineraryId': '9202656047317',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2020년 11월 14일',
     'reviewDbDate': '1605744000000',
     'reviewer': {'name': 'SUNG KYU', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '훌륭한 뷰의 넓고 깨끗한 객실',
     'description': '1. 오션뷰\n  - 남해안의 어느 숙박업소가 그렇듯이 오션뷰가 좋습니다. 이 호텔앞의 바다는 이런 저런 구조물이나 배도 많이 없이 아주 잔잔하고 깔끔한 바다입니다.\n2. 객실 컨디션\n  - 요금에 비해 방크기가 매우 넓고요 깨끗합니다.\n3. 월풀\n  - 욕실이 아닌, 창가에 마련된 오션뷰의 월풀은 여행의 설레임을 증폭시킵니다.\n4. 주차장\n  - 1실 1주차장. 객실과 연결되어 있어 기분좋네요.'},
    {'itineraryId': '9196559102828',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2020년 8월 11일',
     'reviewDbDate': '1597881600000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '거제 지세포 좋은 숙소',
     'description': '커플이 다녀가기에 좋은 숙소. 프라이빗함과 뷰도 갖춘 좋은 곳',
     'response': {'author': '상상속의집',
      'text': '안녕하세요 상상속의집입니다.\n좋은 후기 감사합니다.\n다음에 기회되시면 한번더 방문부탁드리겠습니다.'}},
    {'itineraryId': '9201554317978',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2020년 8월 10일',
     'reviewDbDate': '1597276800000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '위치와 뷰는 추천! ',
     'description': '위치와 뷰는 정말 좋습니다. 개별주차장이 생각보다 쓰기 좋았습니다. 다만, 호텔보다는 고급 모텔의 느낌이 났습니다. 수건, 침대커버 등 청결상태가 제 마음에 100%는 들지않아 아쉬움이 있습니다. ',
     'response': {'author': '상상속의집',
      'text': '안녕하세요 상상속의집입니다.\n고객님이 남겨주신 의견은 즉각 개선할수 있도록\n하겠습니다.\n이용해주셔서 감사합니다.'}},
    {'itineraryId': '9196473456283',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2020년 8월 7일',
     'reviewDbDate': '1597190400000',
     'reviewer': {'name': 'su kyung', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '깔끔하고 뷰가 좋았어요',
     'description': '스탠다드 이용했어요\n방마다 차고가 있어서 편하게 짐 옮겼네요\n제가 이용한 방에 티비에 빨간선이 있네요 이건 참고해주시고 ',
     'response': {'author': '상상속의집',
      'text': '안녕하세요 상상속의집입니다.\n투숙중에 불편한부분이 발생되어 죄송합니다.\n즉각 티비는 교체 완료했었습니다.\n감사합니다.\n다음에 기회가되시면 재방문 부탁드립니다.'}},
    {'itineraryId': '71000309099267',
     'brand': 'expedia',
     'genuineMsg': 'Expedia 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2019년 9월 12일',
     'reviewDbDate': '1597104000000',
     'reviewer': {'name': '따꿍이', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '',
     'description': '일단 깨끗하고 무엇보다주차한 곳에서 바로 룸\n으로 연결된다는 것이 넘 좋았어요~~욕조도 무지커서 가족과함께 씻기도 좋았구요..\n다만 연식이 있어서인지 욕실에 냄새가 조금나는거 같아 일점뺏어요..ㅋ\n조식은 아주간단한 정도니 큰 기대는 마시길.\n성수기에 간것치곤 알맞은 가격이었어요~^^',
     'response': {'author': '상상속의집',
      'text': '안녕하세요 ~ 상상속의집입니다.\n좋은후기 감사합니다.\n고객님이 말씀해주신 욕실냄새는 빠른시일내에 원인을 찾은후 개선해도록하겠습니다.\n이용해주셔 감사합니다.'}},
    {'itineraryId': '9201194045923',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '2박 가족 여행',
     'reviewDate': '2020년 7월 15일',
     'reviewDbDate': '1595116800000',
     'reviewer': {'name': 'suhan', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '조용하고 분위기 좋은',
     'description': '조용하고 가족과 함께 2박3일 편하게 여행하고 왔네요.',
     'response': {'author': '상상속의집',
      'text': '안녕하세요 ~\n고객님 이용해주셔 감사합니다.\n다음에도 이용부탁드립니다.'}},
    {'itineraryId': '9196050465566',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2020년 6월 26일',
     'reviewDbDate': '1593734400000',
     'reviewer': {'name': 'SANGRYONG', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '',
     'description': '만족합니다.',
     'response': {'author': '김명석',
      'text': '상상속의집 이용해주셔서 감사합니다.~\n다음에도 이용부탁드립니다.\n오늘 하루도 좋은 하루되세요~!!'}},
    {'itineraryId': '9195718125010',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2020년 4월 17일',
     'reviewDbDate': '1587600000000',
     'reviewer': {'name': 'Jungki', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '4.0',
     'badge': '보통',
     'summary': '사전 통보해야할 사항 위반',
     'description': '공사장 소음과 작업자들의 분주한 소음으로 새벽부터 잠을 설쳤습니다.\n공사가 있다는 것을 사전에 통보받지 못하였습니다.',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. 후기를 작성해 주셔서 감사드립니다.\n\n현재 호텔 상상속의집은 패밀리룸 리모델링 공사 중입니다. 예약 및 체크인시 고객님께 미리 안내를 해드리지 못해 고객님께 큰 불편을 끼쳐드린 점에 대해서 매우 송구스럽게 생각합니다.\n\n저희 호텔 상상속의집은 이번 고객님께 끼친 불편에 대해 반성하며 앞으로 더 나은 호텔이 될 수 있도록 하겠습니다.'}},
    {'itineraryId': '9206508579578',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2020년 2월 21일',
     'reviewDbDate': '1583020800000',
     'reviewer': {'name': 'bora', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '',
     'description': '막 넓진않고 세식구 하루 자긴 괜춘해요^^',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다.\n후기를 남겨주셔서 감사드립니다.\n\n코로나19 때문에 많이 힘든 상황임에도 불구하고 저희 호텔에서 편안한 시간을 가질 수 있었다는 점에서 안도감을 느낍니다.\n\n아무쪼록 앞으로도 건강에 문제없도록 유의하시기 바랍니다. 감사합니다.'}},
    {'itineraryId': '9211413842441',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2020년 2월 7일',
     'reviewDbDate': '1581465600000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '6.0',
     'badge': '좋음',
     'summary': '전반적으로 별로. ',
     'description': "장점.\n1실1주차. 주차장에서 방에 바로 들어갈 수 있어서 짐 들고 체크인하루 갈 필요 없음. \n개별난방 가능. 수건 넉넉함. 영화 결제해서 볼 수 있는 셋탑박스 있음. \n\n단점.\n두시 반에 도착해서 카운터에 '예약했는데요' 한마디 했더니 '체크인은 세시입니다.' 만 말하고 직원은 응대 더이상 안하고 자기 할일 함. 너무 딱 잘라말했고 세시라는데 별달리 할 수 있는말 없어서 마냥 로비에 앉아 기다림. \n방문 열자마자 엄청난 습도. 청소 막 끝난 뒤였는지 모르겠지만. 창문 열어놔도 잘 안 빠짐. \n바다 보이는 큰 창문은 더러워서 풍경 안 보임. 더러운 거 민감해서 보기싫어 계속 커튼 쳐둠. \n창밖 보며 넓은 욕조 사용 가능한 구조였지만 욕조에 딸린 샤워기가 없어서 욕조 청소를 따로 할 수 없는 구조라 찝찝함에 결국 무용지물. \n샤워부스랑 화장실이 같이 있었는데 화장실에 슬리퍼 없어서 불편. \n단층이라 생각했는데 윗층이 있었는지 가족단위 애들 뛰는 소리 엄청 잘 들림. 방음 취약. \n호텔이라기 보다는 모텔. ",
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. 고객님의 장점과 단점에 자세한 후기 작성에 대해서 감사드립니다.\n\n우선 체크인 과정에서 프론트 직원이 보다 더 따뜻하고 적극적인 자세로 고객님을 맞이했어야 했으나, 고객님께 첫인상부터 좋지 않은 것 같아서 사과드립니다. 객실 청소가 빨리 끝났을 경우에는 오후3시 이전에도 체크인이 가능한 경우가 있지만 당시에는 그런 상황이 아니었던 것으로 보입니다. 그렇다고 하더라도 고객님께 따뜻한 자세로 양해를 구했어야 했으나 직원의 자세에 부족함이 있었던 것 같습니다. 이 부분에 대해서는 다시 한 번 재교육하도록 하겠습니다.\n\n그리고 객실 내의 환기가 부족해 습도가 많이 남아 있었던 점과 창문 상태, 객실 구조 및 비품 상태에서 오는 불편함, 방음 취약 등 고객님께서 투숙하시기 전에 가졌던 기대감에 전혀 미치지 못한 것 같아서 죄송할 따름입니다.\n\n다시 한 번 고객님의 지적 사항에 대해서 고쳐나가야 할 것은 고쳐나가며 다시는 이런 일이 없도록 하겠습니다. 감사합니다.'}},
    {'itineraryId': '9211166387771',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2020년 1월 12일',
     'reviewDbDate': '1578960000000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '불편한 부분이 있었으나 그럭저럭 만족!',
     'description': '날씨가 흐려서 아쉬웠으나,\n이건 어쩔 수 없는 일이고..\n\n화장실 샤워기 위생이 좋아보이진 않더라구요.\n방음도 좋은편은 아닙니다. \n옆방 투숙객에 따라 다르겠으나,\n전반적으로 소음이 전달되더라구요..\n\n그외 서비스, 난방 등은 만족스러웠습니다:)',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. \n맑은 날씨와 함께 편안하고 행복한 시간을 보낼 수 있었으면 더할 나위 없었겠지만, 아쉽게도 그러지 못한 것 같아서 아쉬울 따름입니다. 고객님께서 지적한 사항에 대해서는 다시 한 번 검토 후 개선하도록 하겠습니다.'}},
    {'itineraryId': '9205537092506',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2019년 12월 20일',
     'reviewDbDate': '1578355200000',
     'reviewer': {'name': 'Gayul', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '공간활용 짱',
     'description': '여기 숙박 완전 만족입니다. 넓어서 좋아요',
     'response': {'author': '상상속의집',
      'text': '저희 호텔 상상속의집에 대해 만족해 주셔서 감사드립니다. 새해 복 많이 받으세요.'}},
    {'itineraryId': '9210621688359',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2020년 1월 1일',
     'reviewDbDate': '1578096000000',
     'reviewer': {'name': 'Chungkee', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '',
     'description': '위치와 관리 상태 좋아요',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 만점과 좋은 후기를 작성해 주셔서 감사드립니다.'}},
    {'itineraryId': '9205734195501',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '2박 가족 여행',
     'reviewDate': '2019년 12월 27일',
     'reviewDbDate': '1577923200000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '시간이 나면 다시 방문 하고 싶은 곳',
     'description': '넓고 훌륭한 뷰의 객실과 개인 차고가 너무나 좋았습니다. 스파욕조가 말랑말랑 고무(?)재질이어서 안전 했습니다. 안내 건물에 있는 맛집 버거집과 예쁜 카페가 있는데 마침 비가 와서 편하게 잘 이용 했습니다. 시간이 나서 다음 거제 여행을 갈 수 있다면 다시 방문하고 싶은 곳 입니다 ',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 저희 호텔 상상속의집에서 편안하고 즐거운 시간을 지내고 10점 만점과 함께 만족스러운 후기를 작성해주셔서 감사드립니다.\n\n고객님의 다음 거제 여행에서 다시 한 번 꼭 뵐 수 있기를 바라는 바입니다. 감사합니다.'}},
    {'itineraryId': '9210795416763',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2019년 12월 20일',
     'reviewDbDate': '1577145600000',
     'reviewer': {'name': 'JUHYEON', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '이틀전 예약 후 떠나는 급행여행',
     'description': '전체적으로 좋았습니다 따뜻했구요. \n다만..\n빗이 있었으면 하는 생각을 좀 했습니다.\n동향이라 아침 일출 보는데 좋은거 같아요.\n날씨가 흐려 보지 못했지만요 ㅜ\n',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다.\n후기를 작성해 주셔서 감사드립니다. \n저희 호텔 상상속의집은 새해 해맞이 명소로서 겨울철 객실에서 바로 일출을 볼 수 있다는 것이 최고 장점이지만, 부득이하게 날씨가 흐려서 일출을 보지 못한 것에 대해서 안타깝게 생각합니다. \n\n객실 비품의 경우는 한 번 검토해 보도록 하겠습니다.\n\n감사합니다.'},
     'reviewImageContent': {'reviewImages': [{'caption': '기타',
        'availableSizes': 'ybn',
        'imageUrl': 'https://a.travel-assets.com/ugc/hotel-reviews/CD58DCE5064B7EC92416A10BD3D30E92765B59C31577160286806.jpg?impolicy=rs&w=520'}],
      'firstImage': {'src': 'https://a.travel-assets.com/ugc/hotel-reviews/CD58DCE5064B7EC92416A10BD3D30E92765B59C31577160286806.jpg?impolicy=rs&w=520',
       'size': 'y'}}},
    {'itineraryId': '9205554325789',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2019년 12월 8일',
     'reviewDbDate': '1576108800000',
     'reviewer': {'name': 'JINSUK', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '4.0',
     'badge': '보통',
     'summary': '별로예요.',
     'description': '환기가 안됐는지 목욕탕습기냄새가 입구부터 방안에 진동했고\n목욕탕은 훨씬냄새가 심했으며 심지어 물도 잘 안빠져서 매우 불편했습니다.',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다.\n\n고객님의 투숙 중 불편함에 따른 실망감을 끼쳐드린 점에 대해서 사과드립니다. 저희 호텔은 욕실과 별개로 바다 쪽 창가에도 반신 욕조가 있기 때문에 겨울철을 맞이하여 환기 및 관리가 필요하지만 다소 부족했던 것 같습니다. 배수의 경우에는 하수구 냄새를 막기 위해서 별도의 필터를 설치해 놓았기 때문에 배수 속도가 느린 편입니다.\n\n고객님의 이러한 지적을 겸허히 받아들여 다시 한 번 더 좋은 호텔로 거듭나도록 노력하겠습니다. 감사합니다.'}},
    {'itineraryId': '9210580152000',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2019년 12월 6일',
     'reviewDbDate': '1575936000000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '',
     'description': '프런트에서 주의사항 얘기 해주시는데 아웃사이더가 랩하는 줄ㅠㅠ 욕조에 물때가ㅠㅠ\n방에서 보는 일출은 멋있었습니다',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다.\n고객님께서 후기 작성에 감사드립니다.\n\n12월달이 객실에서 일출을 감상하는데 가장 좋을 때라서 매우 만족스러웠겠지만, 객실 청소와 체크인 과정에서 약간의 불편함이 있었던 것 같습니다. 고객님께서 지적하신 사항은 다시 한 번 담당 직원에게 연락하여 조치하고 개선하도록 하겠습니다. 감사합니다.'}},
    {'itineraryId': '9205502571783',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2019년 12월 4일',
     'reviewDbDate': '1575763200000',
     'reviewer': {'name': 'HaNa', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '2.0',
     'badge': '별로',
     'summary': '별로에요',
     'description': '위생상태가 너무 별로 였어요.. \n그중에서도 화장실이 정말 최악이었어요 \n담배냄새가 타일에 찌들었는지 담배냄새가 나더라구요 아누 오래된 화장실냄새 .. 심지어 물이 내려가지 않아서 \n정말 화장실 바닥에 발 딛기가 싫었어요 티비 앞에 침대가 있는게 아니라 화장실 바로 옆에 침대가 붙어있고 ..\n차라리 이가격이면 좀 더 깨끗한 모텔을 가고싶네요 \n가격이 높은 방은 좀더 좋은가요? \n그런거라면 다룬 객실도 신경좀 써주세요 \n하루빨리 밤이 지나서 체크아웃 하기만을 기다려본건 처음이었어요',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다.\n\n고객님께서 저희 호텔 상상속의집에 대해 큰 기대를 하고 숙박하셨을텐데, 이에 부응하지 못한 점에 대해서 사과드립니다.\n\n저희 호텔 상상속의집은 모든 고객님께 깔끔하고 깨끗한 객실에서 편안한 숙박 환경을 제공해 드리기 위해서 철저한 하우스키핑 관리와 꾸준한 환기 점검을 하고 있으나, 미흡한 점이 있었던 것 같습니다.\n\n그리고, 화장실 배수의 경우는 하수구의 악취를 방지를 하기 위해서 필터를 설치해놓아서 배수 속도가 느린데 이러한 점 역시 고객님께 큰 불편함을 끼쳐드린 듯 합니다.\n\n고객님께서 작성해주신 따끔한 지적을 겸허히 받아들이며, 고객님의 리뷰를 토대로 앞으로 더 나은 호텔 상상속의집이 될 수 있도록 개선하는데 노력하도록 하겠습니다. 감사합니다.'}},
    {'itineraryId': '9205410044681',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'other',
     'tripTypeText': '1박 여행',
     'reviewDate': '2019년 11월 29일',
     'reviewDbDate': '1575331200000',
     'reviewer': {'name': 'HYUNJUNG', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '',
     'description': '숙소가 너무 예뻐요!! 방도 넓어서 욕조도 예쁘고 뷰도 너무 좋고 편안하게 쉬기에 조용해서 너무 좋았어요!',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. \n\n고객님께서 저희 호텔에서 숙박하시면서 너무나 만족하신 것 같아서 저희도 기쁩니다.\n\n기회가 있다면 꼭 재방문 부탁드립니다.'}},
    {'itineraryId': '9205448865394',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '1박 가족 여행',
     'reviewDate': '2019년 11월 28일',
     'reviewDbDate': '1575244800000',
     'reviewer': {'name': 'LEE', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '풍경이 아름다워서 불편함을 잊게되네요♡',
     'description': '부모님 모시고 가족여행이였습니다.\n방안이 워낙 넓어 3명이 아주 편하게 지냈고, \n방안의 욕조도 좋았고, 전망은 탁월했습니다.\n단, 체크인한테 짐을 다 빼지않고 일단 체크인 먼저 하고 각 개인별 주차하라는 안내를 좀더 확실하게 해주시면 좋을것 같고, \n개별 주차장에서 룸으로 올라가는 계단이 너무 좁고 어둡고 높아서 짐을 가지고 올라가는 것도 무척 힘들었고 아이들이 어리면 더 힘들것 같아요\n엘리베이터가 반드시 있어야되는데, 이해가 안가는 부분이였습니다.\n그것빼고는 직원분들도 친절하고 일단 풍경이 아름다우니, 다 넘어가게되는것 같아요\n방안도 아주 따뜻했습니다.',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. \n세세한 숙박 후기를 작성해 주셔서 감사드립니다.\n연말, 연초의 상상속의집은 객실에서 바로 일출을 볼 수 있는데다가 아침 햇빛이 좋아서 그 어느 때보다 좋은 시기입니다. 저희 호텔 상상속의집의 건물 구조상 불편한 점이 있었음에도 불구하고 저희 호텔 상상속의집에서 편안하고 행복한 시간을 보낼 수 있었던 점에 대해서 매우 감사하게 생각합니다. \n\n기회가 있다면 또 다음에 재방문 부탁드리겠습니다. 감사합니다.'},
     'reviewImageContent': {'reviewImages': [{'caption': '기타',
        'availableSizes': 'ybn',
        'imageUrl': 'https://a.travel-assets.com/ugc/hotel-reviews/216B7D9F0326971A17480C26E46A15E9C8957CA41575257026216.jpg?impolicy=rs&w=520'},
       {'caption': '기타',
        'availableSizes': 'ybn',
        'imageUrl': 'https://a.travel-assets.com/ugc/hotel-reviews/1DD24DEF33FD5D766A716530D57E6EEBAF0596D61575257077168.jpg?impolicy=rs&w=520'}],
      'firstImage': {'src': 'https://a.travel-assets.com/ugc/hotel-reviews/216B7D9F0326971A17480C26E46A15E9C8957CA41575257026216.jpg?impolicy=rs&w=520',
       'size': 'y'}}},
    {'itineraryId': '8032491109450',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'family',
     'tripTypeText': '2박 가족 여행',
     'reviewDate': '2019년 10월 3일',
     'reviewDbDate': '1570492800000',
     'reviewer': {'name': 'YEHO', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '10.0',
     'badge': '최고 좋음',
     'summary': '상상속의집 패밀리룸 좋아요~',
     'description': '패밀리룸 이용했는데 엄청 넓고 두층이 아예 분리가 되어 있어서 좋았어요 \r\n아이들이 상상속의집을 엄청 좋아했습니다\r\n차고로 들어가 아래로 내려가는 구조여서 지하 냄새가 났고 천정 구석에 거미줄이 약간 있었고 놀랍게도 소파 등받이 뒤에 누구것인지 모를 여성속옷과 티셔츠, 바지까지 박혀 있는 것을 아이들이 찾아냈네요 ㅎㅎ 그냥 조용히 버렸습니다\r\n그럼에도 불구하고 너무 넓고 두층을 이용할 수 있어서 만족했습니다 \r\n조식은 셀프가 아니고 개인별로 서비스해주시더군요 굳이..\r\n욕조가 넓고 소프트한 재질이어서 좋았어요 \r\n욕실도 넓고 수건 추가요청했더니 엄청 많이 주시더라고요 ㅎㅎ\r\n성수기에는 가격이 얼마인지 몰라도 비수기 1박 33만원(성인2+어린이2)이어서 매우 만족스럽습니다~',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다.\n투숙 후기를 남겨주셔서 감사드립니다.\n\n객실 관리에 있어서 여러가지 부족한 점이 있었음에도 불구하고 만족스러운 숙박과 함께 만점을 주신 고객님의 너그러움에 몸둘바를 두지 못하겠습니다. 저희 호텔 상상속의집에서 만족스러운 숙박을 할 수 있어서 매우 감사하게 생각하며, 기회가 있다면 다시 재방문 부탁드리겠습니다.\n\n다음에는 더욱 만족스러운 숙박을 할 수 있도록 노력하겠습니다.\n\n감사합니다.'}},
    {'itineraryId': '8006687906433',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'romance',
     'tripTypeText': '1박 로맨틱 여행',
     'reviewDate': '2019년 10월 4일',
     'reviewDbDate': '1570406400000',
     'reviewer': {'name': 'Ho-Cheol', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '8.0',
     'badge': '매우 좋음',
     'summary': '',
     'description': '서비스는 보통이였던 것 같습니다. 호텔 구조와 여행하기에는 위치가 너무 좋았어요.',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. 호텔 상상속의집 투숙 후기를 남겨주셔서 감사드립니다. 다음에는 만점을 받을 수 있도록 더욱 노력하겠습니다. 감사합니다.'}},
    {'itineraryId': '8071845116000',
     'brand': 'hcom',
     'genuineMsg': 'Hotels.com 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'romance',
     'tripTypeText': '1박 로맨틱 여행',
     'reviewDate': '2019년 9월 17일',
     'reviewDbDate': '1568937600000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '6.0',
     'badge': '좋음',
     'summary': '경치는 베스트인데 방음 상태가 영~~~',
     'description': '주변 경치, 조망등은 베스트 였으나 호실간 방음은 상태가 좋치 않음, 간단하게 제공되는 아침 식사는 9시부터 인데 조금 빠르게 줄 수 있으면 좋겠응. 체크인시 문의 필요.',
     'response': {'author': '상상속의집',
      'text': '안녕하세요. 상상속의집입니다. 후기를 작성해주셔서 감사드립니다.\n\n고객님께서 지적해 주신 방문 문제와 조식 시간 문제가 상상속의집에서 투숙하시면서 불편함을 끼쳐드리고 오점을 남긴 것 같아서 저희로서도 안타깝고 죄송하게 생각합니다.\n\n고객님의 지적을 겸허히 받아드리며 더 나은 호텔 상상속의집이 될 수 있도록 노력하겠습니다.\n\n감사합니다.'}},
    {'itineraryId': '9205019665159',
     'brand': 'expedia',
     'genuineMsg': 'Expedia 실제 이용 고객 후기',
     'googleTranslateEnabled': False,
     'tripType': 'romance',
     'tripTypeText': '1박 로맨틱 여행',
     'reviewDate': '2019년 9월 7일',
     'reviewDbDate': '1568505600000',
     'reviewer': {'name': '', 'locality': 'kr', 'locale': 'ko_KR'},
     'rating': '4.0',

In [180]:
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']['groups'][0]['items'][0]

{'itineraryId': '72009037635503',
 'brand': 'expedia',
 'genuineMsg': 'Expedia 실제 이용 고객 후기',
 'googleTranslateEnabled': False,
 'tripType': 'family',
 'tripTypeText': '1박 가족 여행',
 'reviewDate': '2020년 11월 20일',
 'reviewDbDate': '1606003200000',
 'reviewer': {'name': '나미', 'locality': 'kr', 'locale': 'ko_KR'},
 'rating': '10.0',
 'badge': '최고 좋음',
 'summary': '',
 'description': '주차가 객실당 한칸씩 차고가 있는게 굉장히 특이했으며 가장 편리했음.\n간혹 차에 무언가를 두고와서 가지러 가는 경험을 하는데 리조트나 다른 펜션이었다면 주차장까지 내려가는 번거로움이 있었겠지만 이 호텔에서는 객실 바로밑에 주차장이 있어서 주차장이 가장편리 하였다.\n하지만 방음 수준은 최악'}

In [181]:
# 리뷰일
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']['groups'][0]['items'][0]['reviewDate']

'2020년 11월 20일'

In [182]:
# 고객id
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']['groups'][0]['items'][0]['itineraryId']

'72009037635503'

In [183]:
# 여행타입
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']['groups'][0]['items'][0]['tripType']

'family'

In [184]:
# 평점
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']['groups'][0]['items'][0]['rating']

'10.0'

In [185]:
# 리뷰
hotels[0]['data']['body']['reviewContent']['reviews']['hermes']['groups'][0]['items'][0]['description']

'주차가 객실당 한칸씩 차고가 있는게 굉장히 특이했으며 가장 편리했음.\n간혹 차에 무언가를 두고와서 가지러 가는 경험을 하는데 리조트나 다른 펜션이었다면 주차장까지 내려가는 번거로움이 있었겠지만 이 호텔에서는 객실 바로밑에 주차장이 있어서 주차장이 가장편리 하였다.\n하지만 방음 수준은 최악'

In [219]:
hotels[0]['data']['body']['pdpHeader']

{'backToSRPLink': '/search.do?destination-id=1693260&q-room-0-adults=2&q-rooms=1&q-room-0-children=0',
 'backToSRPText': '거제, 경상남도, 한국의 모든 숙박 시설',
 'hotelId': 1041793024}

In [240]:
review_dic = {}

column2 = ['hotelId', '리뷰일', '고객id', '여행타입', '평점', '리뷰']

for key in column2:
    review_dic.setdefault(key,[])

for li in hotels:
    for i in li['data']['body']['reviewContent']['reviews']['hermes']['groups']:
        for j in i['items']:
            review_dic['hotelId'].append(li['data']['body']['pdpHeader']['hotelId'])
            review_dic['리뷰일'].append(j['reviewDate'])
            review_dic['고객id'].append(j.get('itineraryId', None))
            review_dic['여행타입'].append(j['tripType'])
            review_dic['평점'].append(j['rating'])
            
            temp = str(j['description'])
            temp = temp.replace('\n',' ')
            
            review_dic['리뷰'].append(temp)

In [241]:
review_df = pd.DataFrame(review_dic)
review_df.tail(3)

           hotelId           리뷰일           고객id          여행타입    평점 리뷰
208482  1344945952  2020년 9월 14일  9196902905665      business   8.0
208483  1344945952  2020년 7월 13일  9201269638204      business   2.0
208484  1344945952  2020년 5월 22일  9195821601150  with-friends  10.0

In [242]:
review_df.to_csv("호텔스닷컴리뷰.csv", encoding='utf-8', index=False)
hotel_df.to_csv("호텔스닷컴리뷰.csv", encoding='utf-8', index=False)