# 신용카드사기탐지_모델만들기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [7]:
data = pd.read_csv('./data/fraud.csv')
data

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,30560609640617,fraud_Reilly and Sons,health_fitness,43.77,Michael,Olson,M,558 Michael Estates,Luray,...,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,1388534347,39.946837,-91.333331,0
1852390,2020-12-31 23:59:09,3556613125071656,fraud_Hoppe-Parisian,kids_pets,111.84,Jose,Vasquez,M,572 Davis Mountains,Lake Jackson,...,29.0393,-95.4401,28739,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,1388534349,29.661049,-96.186633,0
1852391,2020-12-31 23:59:15,6011724471098086,fraud_Rau-Robel,kids_pets,86.88,Ann,Lawson,F,144 Evans Islands Apt. 683,Burbank,...,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,1388534355,46.658340,-119.715054,0
1852392,2020-12-31 23:59:24,4079773899158,fraud_Breitenberg LLC,travel,7.99,Eric,Preston,M,7020 Doyle Stream Apt. 951,Mesa,...,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,1388534364,44.470525,-117.080888,0
1852393,2020-12-31 23:59:34,4170689372027579,fraud_Dare-Marvin,entertainment,38.13,Samuel,Frey,M,830 Myers Plaza Apt. 384,Edmond,...,35.6665,-97.4798,116001,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,1388534374,36.210097,-97.036372,0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1852394 entries, 0 to 1852393
Data columns (total 22 columns):
 #   Column                 Dtype
---  ------                 -----
 0   trans_date_trans_time  object
 1   cc_num                 int64
 2   merchant               object
 3   category               object
 4   amt                    float64
 5   first                  object
 6   last                   object
 7   gender                 object
 8   street                 object
 9   city                   object
 10  state                  object
 11  zip                    int64
 12  lat                    float64
 13  long                   float64
 14  city_pop               int64
 15  job                    object
 16  dob                    object
 17  trans_num              object
 18  unix_time              int64
 19  merch_lat              float64
 20  merch_long             float64
 21  is_fraud               int64
dtypes: float64(5), int64(5), object(12)
memory usage: 310.9+ MB

In [9]:
data.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06,1.852394e+06
mean,4.173860e+17,7.006357e+01,4.881326e+04,3.853931e+01,-9.022783e+01,8.864367e+04,1.358674e+09,3.853898e+01,-9.022794e+01,5.210015e-03
std,1.309115e+18,1.592540e+02,2.688185e+04,5.071470e+00,1.374789e+01,3.014876e+05,1.819508e+07,5.105604e+00,1.375969e+01,7.199217e-02
min,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902742e+01,-1.666716e+02,0.000000e+00
25%,1.800429e+14,9.640000e+00,2.623700e+04,3.466890e+01,-9.679800e+01,7.410000e+02,1.343017e+09,3.474012e+01,-9.689944e+01,0.000000e+00
50%,3.521417e+15,4.745000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.443000e+03,1.357089e+09,3.936890e+01,-8.744069e+01,0.000000e+00
75%,4.642255e+15,8.310000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.374581e+09,4.195626e+01,-8.024511e+01,0.000000e+00
max,4.992346e+18,2.894890e+04,9.992100e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.388534e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [13]:
data.columns

Index(['trans_date_trans_time', 'cc_num', 'merchant', 'category', 'amt',
       'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat',
       'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

In [17]:
from ydata_profiling import ProfileReport

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [19]:
profile = ProfileReport(data,title='Profiling Report')
profile.to_file("fraud_eda.html")

Summarize dataset:   0%|                                             | 0/27 [00:01<?, ?it/s, Describe variable: gender]
Summarize dataset:  67%|██████████████████████▋           | 18/27 [01:42<00:42,  4.67s/it, Describe variable: is_fraud]
  5%|███▊                                                                               | 1/22 [01:32<32:16, 92.19s/it]
  9%|███████▌                                                                           | 2/22 [01:33<12:43, 38.17s/it]
 14%|███████████▎                                                                       | 3/22 [01:33<06:42, 21.21s/it]
 18%|███████████████                                                                    | 4/22 [01:34<03:51, 12.88s/it]
Summarize dataset:  81%|███████████████████████████▋      | 22/27 [02:00<00:26,  5.33s/it, Describe variable: is_fraud]
100%|██████████████████████████████████████████████████████████████████████████████████| 22/22 [01:50<00:00,  5.02s/it]
Summarize dataset: 100%|██████████████████████████████████████████████████| 112/112 [03:57<00:00,  2.12s/it, Completed]
Generate report structure: 100%|█████████████████████████████████████████████████████████| 1/1 [00:24<00:00, 24.36s/it]
Render HTML: 100%|███████████████████████████████████████████████████████████████████████| 1/1 [00:05<00:00,  5.88s/it]
Export report to file: 100%|█████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 26.13it/s]

In [18]:
data.isna().sum()

trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [20]:
obj_cols = data.select_dtypes(include='object')
num_cols = data.select_dtypes(exclude='object')

In [25]:
# 컬럼 별로 주요한 값을 하나의 리스트에 정리
important_cols = []
for col in obj_cols:
    print('='*30, col,'='*30)
    print(col, obj_cols[col].nunique())  # 종류 몇개인지 확인
    print()
    print(obj_cols[col].value_counts())
    print()
    print(data[[col,'is_fraud']].groupby(col).mean().sort_values(by='is_fraud', ascending=False))
    print()
    ratio_result = data[[col,'is_fraud']].groupby(col).mean().sort_values(by='is_fraud', ascending=False)
    important_cols.append(ratio_result[ratio_result['is_fraud']>0.4].index)

============================== trans_date_trans_time ==============================
trans_date_trans_time 1819551

trans_date_trans_time
2019-04-22 16:02:01    4
2020-06-01 01:37:47    4
2020-06-02 12:47:07    4
2020-10-05 19:37:49    4
2020-12-13 17:53:47    4
                      ..
2019-01-01 00:41:45    1
2019-01-01 00:42:26    1
2019-01-01 00:43:38    1
2019-01-01 00:44:20    1
2020-12-31 23:50:17    1
Name: count, Length: 1819551, dtype: int64

                       is_fraud
trans_date_trans_time
2019-09-11 22:58:11         1.0
2019-12-22 01:09:30         1.0
2019-02-12 23:49:17         1.0
2019-09-23 06:33:47         1.0
2019-05-03 04:38:52         1.0
...                         ...
2019-01-01 00:41:45         0.0
2019-01-01 00:42:26         0.0
2019-01-01 00:43:38         0.0
2019-01-01 00:44:20         0.0
2020-12-31 23:50:17         0.0

[1819551 rows x 1 columns]

============================== merchant ==============================
merchant 693

merchant
fraud_Kilback LLC                        6262
fraud_Cormier LLC                        5246
fraud_Schumm PLC                         5195
fraud_Kuhn LLC                           5031
fraud_Boyer PLC                          4999
                                         ...
fraud_Douglas, DuBuque and McKenzie      1101
fraud_Treutel-King                       1098
fraud_Satterfield-Lowe                   1095
fraud_Hahn, Douglas and Schowalter       1091
fraud_Ritchie, Bradtke and Stiedemann    1090
Name: count, Length: 693, dtype: int64

                                       is_fraud
merchant
fraud_Kozey-Boehm                      0.021755
fraud_Herman, Treutel and Dickens      0.020321
fraud_Terry-Huel                       0.019553
fraud_Kerluke-Abshire                  0.018975
fraud_Mosciski, Ziemann and Farrell    0.018788
...                                         ...
fraud_Reichert-Weissnat                0.000000
fraud_Ritchie, Bradtke and Stiedemann  0.000000
fraud_Hodkiewicz, Prohaska and Paucek  0.000000
fraud_Gulgowski LLC                    0.000000
fraud_Schroeder Group                  0.000000

[693 rows x 1 columns]

============================== category ==============================
category 14

category
gas_transport     188029
grocery_pos       176191
home              175460
shopping_pos      166463
kids_pets         161727
shopping_net      139322
entertainment     134118
food_dining       130729
personal_care     130085
health_fitness    122553
misc_pos          114229
misc_net           90654
grocery_net        64878
travel             57956
Name: count, dtype: int64

                is_fraud
category
shopping_net    0.015927
misc_net        0.013039
grocery_pos     0.012645
shopping_pos    0.006344
gas_transport   0.004106
misc_pos        0.002819
grocery_net     0.002697
travel          0.002692
personal_care   0.002229
entertainment   0.002177
kids_pets       0.001880
food_dining     0.001568
home            0.001510
health_fitness  0.001510

============================== first ==============================
first 355

first
Christopher    38112
Robert         30743
Jessica        29236
David          28564
Michael        28539
               ...
Nicole             9
Phyllis            8
Molly              8
Angelica           7
Samantha           7
Name: count, Length: 355, dtype: int64

          is_fraud
first
Calvin    1.000000
Samantha  1.000000
Cameron   1.000000
Nicole    1.000000
Molly     1.000000
...            ...
Crystal   0.001370
Jenna     0.001144
Erin      0.000457
Deborah   0.000000
Melvin    0.000000

[355 rows x 1 columns]

============================== last ==============================
last 486

last
Smith        40940
Williams     33661
Davis        31434
Johnson      28590
Rodriguez    24879
             ...
Strong           8
Freeman          8
Schaefer         7
Blake            7
Bartlett         7
Name: count, Length: 486, dtype: int64

           is_fraud
last
Schaefer   1.000000
Santiago   1.000000
Golden     1.000000
Wells      1.000000
Bartlett   1.000000
...             ...
Nolan      0.000685
Francis    0.000000
Fernandez  0.000000
Conley     0.000000
Ayers      0.000000

[486 rows x 1 columns]

============================== gender ==============================
gender 2

gender
F    1014749
M     837645
Name: count, dtype: int64

        is_fraud
gender
M       0.005673
F       0.004828

============================== street ==============================
street 999

street
444 Robert Mews                    4392
908 Brooks Brook                   4392
320 Nicholson Orchard              4386
5796 Lee Coves Apt. 286            4386
03512 Jackson Ports                4386
                                   ...
610 Pacheco Parkway                   7
9599 Washington Field Suite 238       7
3437 Ross Flat Apt. 592               7
5124 Wendy Skyway Suite 154           7
007 Tonya Isle Suite 299              6
Name: count, Length: 999, dtype: int64

                                  is_fraud
street
007 Tonya Isle Suite 299               1.0
01770 Kevin Lodge Suite 190            1.0
024 Williams Parkway                   1.0
055 Stephanie Turnpike Suite 559       1.0
56261 Keith Plaza                      1.0
...                                    ...
1911 Fisher Brook                      0.0
126 Underwood Drive                    0.0
1652 James Mews                        0.0
899 Michele View Suite 960             0.0
9572 Austin Forge Suite 612            0.0

[999 rows x 1 columns]

============================== city ==============================
city 906

city
Birmingham     8040
San Antonio    7312
Utica          7309
Phoenix        7297
Meridian       7289
               ...
Karns City        7
Streator          7
Chattanooga       7
Bruce             7
Wever             6
Name: count, Length: 906, dtype: int64

              is_fraud
city
Angwin             1.0
Madisonville       1.0
Lexington          1.0
Lockhart           1.0
Las Vegas          1.0
...                ...
Kirtland Afb       0.0
Mayersville        0.0
Milwaukee          0.0
Tomahawk           0.0
Alton              0.0

[906 rows x 1 columns]

============================== state ==============================
state 51

state
TX    135269
NY    119419
PA    114173
CA     80495
OH     66627
MI     65825
IL     62212
FL     60775
AL     58521
MO     54904
MN     45433
AR     44611
NC     43134
VA     41756
WI     41738
SC     41731
KY     40981
IN     39539
IA     38804
OK     38050
MD     37345
GA     37340
WV     36529
NJ     35131
NE     34425
KS     32939
MS     30021
LA     29953
WY     27776
WA     27040
OR     26408
TN     24913
ME     23433
NM     23427
ND     21183
CO     19766
SD     17574
MA     17562
VT     16812
MT     16806
AZ     15362
UT     15357
NH     11727
CT     10979
NV      8058
ID      8035
DC      5130
HI      3649
AK      2963
RI       745
DE         9
Name: count, dtype: int64

       is_fraud
state
DE     1.000000
RI     0.020134
AK     0.016875
OR     0.007460
NH     0.006737
VA     0.006538
TN     0.006382
NE     0.006275
MN     0.006163
NY     0.006113
DC     0.006043
KS     0.005859
NV     0.005833
CO     0.005818
ME     0.005718
SC     0.005655
MS     0.005629
FL     0.005496
IN     0.005488
GA     0.005463
WI     0.005463
IA     0.005438
MD     0.005436
KY     0.005417
OH     0.005403
OK     0.005256
SD     0.005235
IL     0.005208
NM     0.005165
CT     0.005101
PA     0.005010
CA     0.004994
MA     0.004954
MO     0.004772
AL     0.004750
WA     0.004660
NJ     0.004583
MI     0.004542
NC     0.004521
HI     0.004385
TX     0.004376
AR     0.004371
WY     0.004284
VT     0.004283
AZ     0.004166
ID     0.004107
MT     0.004106
WV     0.003997
UT     0.003972
ND     0.003965
LA     0.003773

============================== job ==============================
job 497

job
Film/video editor             13898
Exhibition designer           13167
Surveyor, land/geomatics      12436
Naval architect               12434
Materials engineer            11711
                              ...
Veterinary surgeon                8
Engineer, water                   8
Contracting civil engineer        7
Ship broker                       7
Warehouse manager                 7
Name: count, Length: 497, dtype: int64

                          is_fraud
job
Accountant, chartered     1.000000
Warehouse manager         1.000000
Careers adviser           1.000000
Solicitor                 1.000000
Ship broker               1.000000
...                            ...
Health physicist          0.000686
Contractor                0.000458
Engineer, communications  0.000000
Engineer, drilling        0.000000
Stage manager             0.000000

[497 rows x 1 columns]

============================== dob ==============================
dob 984

dob
1977-03-23    8044
1988-09-15    6574
1981-08-29    6571
1955-05-06    5121
1960-01-13    4395
              ...
1962-03-14       7
1944-06-17       7
1970-06-25       7
1932-05-09       7
1998-08-02       6
Name: count, Length: 984, dtype: int64

            is_fraud
dob
2001-07-17       1.0
2002-03-17       1.0
1925-08-29       1.0
1927-02-03       1.0
1944-05-30       1.0
...              ...
1949-10-04       0.0
1975-04-16       0.0
1973-10-19       0.0
1975-06-29       0.0
1930-02-28       0.0

[984 rows x 1 columns]

============================== trans_num ==============================
trans_num 1852394

trans_num
1765bb45b3aa3224b4cdcb6e7a96cee3    1
0b242abb623afc578575680df30655b9    1
1f76529f8574734946361c461b024d99    1
a1a22d70485983eac12b5b88dad1cf95    1
6b849c168bdad6f867558c3793159a81    1
                                   ..
413636e759663f264aae1819a4d4f231    1
8a6293af5ed278dea14448ded2685fea    1
baae0b096835c975857eea7e28dde3dc    1
991c04803b4d4eeab30d6245a872e3d3    1
f12cf52be2175703db789a4644c32f25    1
Name: count, Length: 1852394, dtype: int64

                                  is_fraud
trans_num
1beffe8ba58d868ca424b2da19aa17c5       1.0
347b8b8d2898fc0e3a3a4dee5026a397       1.0
6591db4e9b8f5823312ca8b70db64848       1.0
091947c9af7865558616ae08505b8f7a       1.0
07d67e15b9ed9f64d0e1fd7db283a0af       1.0
...                                    ...
00017fcc7a37796b5ebf048464185744       0.0
00018ba4aaeb4d893423d6b2426f02db       0.0
0001911bd16f115b060cef4cdd238a5c       0.0
0001915769fd20ee9f76ec525525ec19       0.0
000048ecb6c1d9337bcc27109b46794d       0.0

[1852394 rows x 1 columns]

In [26]:
# 값이 있는 컬럼만 다시 정리
final_cols = []

for col in important_cols:
    if len(col) > 0:
        print(col.name, '\t',len(col))
        final_cols.append(col.name)
        
final_cols

trans_date_trans_time 	 9637
first 	 18
last 	 21
street 	 91
city 	 70
state 	 1
job 	 22
dob 	 90
trans_num 	 9651

['trans_date_trans_time',
 'first',
 'last',
 'street',
 'city',
 'state',
 'job',
 'dob',
 'trans_num']

In [28]:
# 컬럼 별로 주요한 값을 하나의 리스트에 정리 (범주형 변수와 동일)
for col in num_cols.iloc[:,:-1]:  # class 함수는 col에 제외
    print('='*30, col,'='*30)
    print(col, num_cols[col].describe())  # 값 범위 파악
    print()
    num_cols[col].plot(kind='hist')
    plt.show()
    print()
    print(data[[col,'is_fraud']].groupby(col).mean().sort_values(by='is_fraud', ascending=False))
    print()
    ratio_result = data[[col,'is_fraud']].groupby(col).mean().sort_values(by='is_fraud', ascending=False)
    important_cols.append(ratio_result[ratio_result['is_fraud']>0.40].index)
    print()

============================== cc_num ==============================
cc_num count    1.852394e+06
mean     4.173860e+17
std      1.309115e+18
min      6.041621e+10
25%      1.800429e+14
50%      3.521417e+15
75%      4.642255e+15
max      4.992346e+18
Name: cc_num, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

                     is_fraud
cc_num
501818133297              1.0
501894933032              1.0
2295963260374698          1.0
2242176657877538          1.0
6011935564104173          1.0
...                       ...
3583293909206278          0.0
375248307838179           0.0
3583635130604947          0.0
4810839835482794272       0.0
4584931703207308232       0.0

[999 rows x 1 columns]


============================== amt ==============================
amt count    1.852394e+06
mean     7.006357e+01
std      1.592540e+02
min      1.000000e+00
25%      9.640000e+00
50%      4.745000e+01
75%      8.310000e+01
max      2.894890e+04
Name: amt, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

          is_fraud
amt
281.28         1.0
984.69         1.0
984.59         1.0
684.27         1.0
277.20         1.0
...            ...
25086.94       0.0
26544.12       0.0
27119.77       0.0
27390.12       0.0
11960.97       0.0

[60616 rows x 1 columns]


============================== zip ==============================
zip count    1.852394e+06
mean     4.881326e+04
std      2.688185e+04
min      1.257000e+03
25%      2.623700e+04
50%      4.817400e+04
75%      7.204200e+04
max      9.992100e+04
Name: zip, dtype: float64


       is_fraud
zip
4032        1.0
99921       1.0
68375       1.0
67346       1.0
63966       1.0
...         ...
79413       0.0
39113       0.0
19149       0.0
87117       0.0
15217       0.0

[985 rows x 1 columns]

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

============================== lat ==============================
lat count    1.852394e+06
mean     3.853931e+01
std      5.071470e+00
min      2.002710e+01
25%      3.466890e+01
50%      3.935430e+01
75%      4.194040e+01
max      6.669330e+01
Name: lat, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

         is_fraud
lat
27.8942       1.0
66.6933       1.0
29.4400       1.0
55.4732       1.0
48.0379       1.0
...           ...
42.9782       0.0
31.3833       0.0
40.0369       0.0
38.8564       0.0
31.4647       0.0

[983 rows x 1 columns]


============================== long ==============================
long count    1.852394e+06
mean    -9.022783e+01
std      1.374789e+01
min     -1.656723e+02
25%     -9.679800e+01
50%     -8.747690e+01
75%     -8.015800e+01
max     -6.795030e+01
Name: long, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

           is_fraud
long
-133.1171       1.0
-122.2750       1.0
-122.3022       1.0
-122.4477       1.0
-81.8140        1.0
...             ...
-106.5503       0.0
-88.0434        0.0
-85.4834        0.0
-111.9027       0.0
-111.1439       0.0

[983 rows x 1 columns]


============================== city_pop ==============================
city_pop count    1.852394e+06
mean     8.864367e+04
std      3.014876e+05
min      2.300000e+01
25%      7.410000e+02
50%      2.443000e+03
75%      2.032800e+04
max      2.906700e+06
Name: city_pop, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

          is_fraud
city_pop
296965         1.0
242803         1.0
198659         1.0
28506          1.0
121            1.0
...            ...
595            0.0
376            0.0
103927         0.0
310            0.0
43             0.0

[891 rows x 1 columns]


============================== unix_time ==============================
unix_time count    1.852394e+06
mean     1.358674e+09
std      1.819508e+07
min      1.325376e+09
25%      1.343017e+09
50%      1.357089e+09
75%      1.374581e+09
max      1.388534e+09
Name: unix_time, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

            is_fraud
unix_time
1341538357       1.0
1344862776       1.0
1329090557       1.0
1354665315       1.0
1350857340       1.0
...              ...
1325378505       0.0
1325378546       0.0
1325378618       0.0
1325378660       0.0
1388533817       0.0

[1819583 rows x 1 columns]


============================== merch_lat ==============================
merch_lat count    1.852394e+06
mean     3.853898e+01
std      5.105604e+00
min      1.902742e+01
25%      3.474012e+01
50%      3.936890e+01
75%      4.195626e+01
max      6.751027e+01
Name: merch_lat, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

           is_fraud
merch_lat
34.739887       1.0
67.510267       1.0
38.449115       1.0
35.672329       1.0
31.799209       1.0
...             ...
19.054867       0.0
19.054924       0.0
19.056832       0.0
19.056869       0.0
66.610031       0.0

[1754157 rows x 1 columns]


============================== merch_long ==============================
merch_long count    1.852394e+06
mean    -9.022794e+01
std      1.375969e+01
min     -1.666716e+02
25%     -9.689944e+01
50%     -8.744069e+01
75%     -8.024511e+01
max     -6.695090e+01
Name: merch_long, dtype: float64

C:\Users\Admin\AppData\Local\Temp\ipykernel_32280\1033640488.py:7: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

             is_fraud
merch_long
-95.687871        1.0
-89.176591        1.0
-103.432490       1.0
-87.651246        1.0
-97.675129        1.0
...               ...
-166.628475       0.0
-166.628201       0.0
-166.627418       0.0
-166.627073       0.0
-166.653605       0.0

[1809753 rows x 1 columns]

In [29]:
# 값이 있는 컬럼만 다시 정리
final_cols = []

for col in important_cols:
    if len(col) > 0:
        print(col.name, '\t',len(col))
        final_cols.append(col.name)  # 값의 컬럼 이름을 추가
        
final_cols
## groupby 연산을 했을 때 의미가 있어보이는 컬럼들을 토대로 진행

trans_date_trans_time 	 9637
first 	 18
last 	 21
street 	 91
city 	 70
state 	 1
job 	 22
dob 	 90
trans_num 	 9651
cc_num 	 91
amt 	 5800
zip 	 88
lat 	 88
long 	 87
city_pop 	 69
unix_time 	 9637
merch_lat 	 9588
merch_long 	 9636

['trans_date_trans_time',
 'first',
 'last',
 'street',
 'city',
 'state',
 'job',
 'dob',
 'trans_num',
 'cc_num',
 'amt',
 'zip',
 'lat',
 'long',
 'city_pop',
 'unix_time',
 'merch_lat',
 'merch_long']

In [31]:
data_set1 = data[final_cols]
data_set1

,trans_date_trans_time,first,last,street,city,state,job,dob,trans_num,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long
0,2019-01-01 00:00:18,Jennifer,Banks,561 Perry Cove,Moravian Falls,NC,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,2703186189652095,4.97,28654,36.0788,-81.1781,3495,1325376018,36.011293,-82.048315
1,2019-01-01 00:00:44,Stephanie,Gill,43039 Riley Greens Suite 393,Orient,WA,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,630423337322,107.23,99160,48.8878,-118.2105,149,1325376044,49.159047,-118.186462
2,2019-01-01 00:00:51,Edward,Sanchez,594 White Dale Suite 530,Malad City,ID,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,38859492057661,220.11,83252,42.1808,-112.2620,4154,1325376051,43.150704,-112.154481
3,2019-01-01 00:01:16,Jeremy,White,9443 Cynthia Court Apt. 038,Boulder,MT,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,3534093764340240,45.00,59632,46.2306,-112.1138,1939,1325376076,47.034331,-112.561071
4,2019-01-01 00:03:06,Tyler,Garcia,408 Bradley Rest,Doe Hill,VA,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,375534208663984,41.96,24433,38.4207,-79.4629,99,1325376186,38.674999,-78.632459
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1852389,2020-12-31 23:59:07,Michael,Olson,558 Michael Estates,Luray,MO,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,30560609640617,43.77,63453,40.4931,-91.8912,519,1388534347,39.946837,-91.333331
1852390,2020-12-31 23:59:09,Jose,Vasquez,572 Davis Mountains,Lake Jackson,TX,Futures trader,1999-12-27,2090647dac2c89a1d86c514c427f5b91,3556613125071656,111.84,77566,29.0393,-95.4401,28739,1388534349,29.661049,-96.186633
1852391,2020-12-31 23:59:15,Ann,Lawson,144 Evans Islands Apt. 683,Burbank,WA,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,6011724471098086,86.88,99323,46.1966,-118.9017,3684,1388534355,46.658340,-119.715054
1852392,2020-12-31 23:59:24,Eric,Preston,7020 Doyle Stream Apt. 951,Mesa,ID,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,4079773899158,7.99,83643,44.6255,-116.4493,129,1388534364,44.470525,-117.080888
1852393,2020-12-31 23:59:34,Samuel,Frey,830 Myers Plaza Apt. 384,Edmond,OK,Media buyer,1993-05-10,1765bb45b3aa3224b4cdcb6e7a96cee3,4170689372027579,38.13,73034,35.6665,-97.4798,116001,1388534374,36.210097,-97.036372

In [32]:
X = pd.get_dummies(data_set1, drop_first=True)

MemoryError: Unable to allocate 3.07 TiB for an array with shape (1852394, 1819551) and data type bool

In [ ]:
y = data['is_fraud']