# 1. requests 모듈: HTTP프로토콜을 사용할 수 있게 해주는 모듈
* request모듈 사용 설명서
    * [requests 설명서](https://requests.readthedocs.io/en/latest/)

In [1]:
import requests
import pandas as pd
import json

In [2]:
# 기본적인 틀
####################################################################################

# 주소
url = "https://openapi.naver.com/v1/search/blog"

# 파라미터
payload = {'query': '핀테크', 'display': 100, 'start': 1, 'sort': 'sim'}  

# 아이디 비밀번호 header로 입력
headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 'X-Naver-Client-Secret' : 'UaIJQBMlNd'}

# 본격적으로 분석
r = requests.get(url,params=payload, headers=headers)

# r.json = request의 응답 객체
data = r.json()
data

{'lastBuildDate': 'Tue, 01 Apr 2025 10:26:54 +0900',
 'total': 456210,
 'start': 1,
 'display': 100,
 'items': [{'title': '[<b>핀테크</b>] 2024년 <b>핀테크</b> 업계 결산: 놀라운 3가지 변화',
   'link': 'https://blog.naver.com/xoom777/223708685044',
   'description': '동안 <b>핀테크</b> 업계에는 예상치 못한 변화의 바람이 불었습니다. 한동안 주춤했던 트렌드가... 올 한 해 <b>핀테크</b> 업계를 뜨겁게 달군 3가지 트렌드에 대해 자세히 살펴보겠습니다. 암호화폐의 귀환, 기관... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241229'},
  {'title': '<b>핀테크</b> 투자 후기',
   'link': 'https://blog.naver.com/kan1687/223812724931',
   'description': '<b>핀테크</b> 투자, 아직도 망설이고 계신가요?  여러분 혹시 이런 고민 해보신 적 있나요? &quot;<b>핀테크</b> 분야가 떴다는데, 지금 시작해도 괜찮을까? 좀 더 상황을 지켜봐야 하나?&quot; 사실 이런 생각은 투자를 고민하는 우리... ',
   'bloggername': '우정잉♥',
   'bloggerlink': 'blog.naver.com/kan1687',
   'postdate': '20250329'},
  {'title': '[인사이트 캠퍼스] 2025 동계 <b>핀테크</b> 캠프 (with 전주대학교... ',
   'link': 'https://blog.naver.com/fininsight/223734638126',
   'description': '전주대학교 친구들이 직접 여의도까지 방문하여 <b>핀테크</b>(FinTech)의 세계를 탐구할 기회를 가질 수... <b>핀테크</b>의 개념부터 해당 기술을 적용하는 사업 분야 그리고 앞으로의 트렌드까지 현업자의 시선에서 면밀하게... ',
   'bloggername': '핀인사이트 (Fininsight)',
   'bloggerlink': 'blog.naver.com/fininsight',
   'postdate': '20250122'},
  {'title': '[AI <b>핀테크</b>] AI와 빅데이터로 금융 시장을 재편하는 <b>핀테크</b>... ',
   'link': 'https://blog.naver.com/jangpung_/223765345858',
   'description': '이제 대출도 AI가 하는 시대 출처 : 파가야 테크놀러지스 홈페이지 금융과 기술이 만나는 <b>핀테크</b>... 제공하는 <b>핀테크</b> 기업으로, 현재 미국, 이스라엘, 케이맨 제도 등여러나라에서 사업을 진행하고 있다.... ',
   'bloggername': '낭만을 꿈꾸는 일상',
   'bloggerlink': 'blog.naver.com/jangpung_',
   'postdate': '20250218'},
  {'title': 'IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대',
   'link': 'https://blog.naver.com/jaso_/223736810791',
   'description': 'IPAY <b>핀테크</b>관련주 ETF -미국 CBDC 코인 서비스 실험 확대 IPAY ETF는 모바일 결제 산업에 투자하는 ETF로 <b>핀테크</b>관련주라고 보시면 되는데요. 이번 포스팅에선 IPAY <b>핀테크</b>관련주 ETF, 투자수익률, 미국 CBDC... ',
   'bloggername': '미국주식 퍼주마',
   'bloggerlink': 'blog.naver.com/jaso_',
   'postdate': '20250130'},
  {'title': '맨틀 MNT 코인 디파이 <b>핀테크</b> 서비스 소개',
   'link': 'https://blog.naver.com/tmglove/223781181469',
   'description': '웹2와 웹3을 아우르며 기관과 개인 그리고 리테일을 위한 다양한 <b>핀테크</b> 서비스 출시를 준비하고 있다고 하는데요. 그래서 오늘은 MNT 코인의 디파이 <b>핀테크</b> 서비스에 대해 알아보겠습니다. <b>핀테크</b>로... ',
   'bloggername': 'Hello-',
   'bloggerlink': 'blog.naver.com/tmglove',
   'postdate': '20250302'},
  {'title': '[<b>핀테크</b> 리더] # 2024 금융위원회 선정 10대 기업 _ 1편',
   'link': 'https://blog.naver.com/koreafintech/223675560515',
   'description': "[<b>핀테크</b> 리더] ⭐ # 2024 금융위원회 선정 10대 기업 _ 1편 금융위원회는 &lt;코리아 <b>핀테크</b> 위크 2024&gt;에서 작년에 이어 'K-Fintech 30' 프로젝트에 선정된 유망 <b>핀테크</b> 기업 10개사를 발굴하여 소개하였습니다. 'K... ",
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241128'},
  {'title': '맨틀 네트워크 코인 MNT <b>핀테크</b> 서비스 등장',
   'link': 'https://blog.naver.com/ghfjvb465/223781841217',
   'description': '맨틀네트워크 코인 <b>핀테크</b>와 크립토 경계 허물기 소개, 시세, 전망 코하! 경제적 자유 얻기... 이번 포스팅에서는 맨틀네트워크 코인 MNT의 <b>핀테크</b> 분야 진출 서비스 소개에 대한 내용을 함께 알아보는... ',
   'bloggername': '노마드신지테의 경제적자유얻기 챌린지',
   'bloggerlink': 'blog.naver.com/ghfjvb465',
   'postdate': '20250303'},
  {'title': '맨틀 코인 전망 디파이를 넘어 <b>핀테크</b>로 확장하는 미래',
   'link': 'https://blog.naver.com/duswnswlstlf/223782041308',
   'description': 'WEB2와 WEB3를 아우르는 기업들이 늘어나고 있지만 현실은 <b>핀테크</b> 기업들이 크립토 산업에 진출할 뿐, 크립토 기업들이 <b>핀테크</b> 사업으로 진출한 경우는 없네요. 가끔은 왜 WEB3 기업들은 디파이를 넘어서 WEB2의... ',
   'bloggername': '이기사 블로그',
   'bloggerlink': 'blog.naver.com/duswnswlstlf',
   'postdate': '20250303'},
  {'title': '테크놀로지스(PGY): AI 기반 대출 혁신의 주목받는 <b>핀테크</b> 기업',
   'link': 'https://blog.naver.com/an5217/223810108719',
   'description': '최근 <b>핀테크</b> 업계에서 주목받는 기업 **파가야 테크놀로지스(NASDAQ:PGY)**가 투자자와 애널리스트들... 제공하는 <b>핀테크</b> 기업입니다. 머신러닝 알고리즘을 통해 개인 대출, 자동차 대출, POS(Point-of-Sale)... ',
   'bloggername': '오늘 하루도 절도있고 검소하게',
   'bloggerlink': 'blog.naver.com/an5217',
   'postdate': '20250326'},
  {'title': '네이버클라우드 X 서울대학교 KDT 빅데이터 <b>핀테크</b> 전문가 과정',
   'link': 'https://blog.naver.com/n_cloudplatform/223790788385',
   'description': '서울대학교 KDT 빅데이터 <b>핀테크</b> 전문가 과정에 캡스톤 참여기업으로 함께한 네이버클라우드의... 서울대학교 빅데이터 <b>핀테크</b> AI 고급 전문가 과정 서울대학교가 주관하는 고용노동부의 K... ',
   'bloggername': '네이버클라우드 (NAVER Cloud)',
   'bloggerlink': 'blog.naver.com/n_cloudplatform',
   'postdate': '20250311'},
  {'title': '서울형 R&amp;D <b>핀테크</b> 기술사업화 지원사업 완벽 가이드!',
   'link': 'https://blog.naver.com/thebsc777/223802246310',
   'description': '이번에 서울경제진흥원에서 공고한 25년 서울형 R&amp;D <b>핀테크</b> 기술사업화 지원사업 에 대해 상세히 알아보겠습니다. <b>핀테크</b> 분야 기업이라면 절대 놓치면 안 될 이번 지원사업, 꼼꼼히 살펴볼게요! 1. 지원... ',
   'bloggername': '정책지원알림',
   'bloggerlink': 'blog.naver.com/thebsc777',
   'postdate': '20250323'},
  {'title': '25년 금융 클라우드 지원사업 <b>핀테크</b> 기업 클라우드는... ',
   'link': 'https://blog.naver.com/xeno_solution/223791865385',
   'description': '이번에 <b>핀테크</b> 기업 담당하고 계신 분들이 주목할 만한 소식이 업데이트되어 가지고 왔습니다~ 다름... <b>핀테크</b> 기업의 경우 보안 기능과 빠르게 처리가 가능한 인프라를 요구할 수밖에 없습니다. 그렇기... ',
   'bloggername': '클라우드를 가장 잘 하는 회사, 제노솔루션',
   'bloggerlink': 'blog.naver.com/xeno_solution',
   'postdate': '20250311'},
  {'title': '페이버스와 알아보는 2025 글로벌 <b>핀테크</b> 규제 변화',
   'link': 'https://blog.naver.com/payverse/223809522693',
   'description': '2025년 주목해야 할 글로벌 <b>핀테크</b> 규제 변화 안녕하세요, 페이버스 입니다 :) <b>핀테크</b> 산업은 전 세계적으로 빠르게 성장하고 있으며, 이에 따라 각국의 규제 환경도 계속해서 변화하고 있습니다.... ',
   'bloggername': '페이버스(PayVerse)',
   'bloggerlink': 'blog.naver.com/payverse',
   'postdate': '20250326'},
  {'title': '<b>핀테크</b> 개인 경제에 혁명적 영향을 느끼게 하다',
   'link': 'https://blog.naver.com/anawoncham/223685650464',
   'description': '<b>핀테크</b> FinTech는 Finance과 Technology의 결합으로, 최근 몇 년간 급속도로 발전하고 있는 분야예요. 이제는 우리 생활의 많은 부분에서 <b>핀테크</b>는 개인 경제에 혁명인 영향을 느끼게 하고 있는데요. 오늘은... ',
   'bloggername': '♣ 끄적이내 ♣',
   'bloggerlink': 'blog.naver.com/anawoncham',
   'postdate': '20241207'},
  {'title': '2025년 <b>핀테크</b> 트렌드: 새로운 금융 패러다임과 기회의 장',
   'link': 'https://blog.naver.com/dismalist/223762273788',
   'description': '2025년, <b>핀테크</b>(FinTech)는 더 이상 &quot;미래의 금융&quot;이 아닙니다. 바로 우리의 일상에 깊숙이 스며든 현실이자 새로운 금융 패러다임을 형성하는 강력한 동력인데요. 이번 포스팅에서는 2025년 <b>핀테크</b> 산업을... ',
   'bloggername': '마법고양이의 기묘한 이야기',
   'bloggerlink': 'blog.naver.com/dismalist',
   'postdate': '20250216'},
  {'title': '“<b>핀테크</b>-금융회사-투자기관 만남의 장” ｢제2회 <b>핀테크</b> 오픈... ',
   'link': 'https://blog.naver.com/blogfsc/223666157308',
   'description': '-<b>핀테크</b>-금융회사 협업 및 <b>핀테크</b> 기업 투자 유치를 확대하는 교류 행사 -금융위원회, <b>핀테크</b> 산업의 지속 성장을 위해 과감한 디지털 금융정책 추진 금융위원회는 11월 19일(화), 서울 창업허브(공덕)에서... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20241119'},
  {'title': '<b>핀테크</b> 전문가 국비지원 과정 - KG 이니시스 실무자 멘토링',
   'link': 'https://blog.naver.com/gkea04/223815900160',
   'description': '<b>핀테크</b> 산업의 현황과 전망 <b>핀테크</b>(FinTech)는 금융(Finance)과 기술(Technology)의 합성어로, IT 기술을 활용하여 금융 서비스를 제공하는 산업을 말합니다. 최근 몇 년간 <b>핀테크</b> 산업은 빠르게 성장하고 있으며, 이는... ',
   'bloggername': 'KG 에듀원 교육 상담님의 블로그',
   'bloggerlink': 'blog.naver.com/gkea04',
   'postdate': '20250331'},
  {'title': '<b>핀테크</b>로 외국에 보내는 송금 비용 낮추기',
   'link': 'https://blog.naver.com/e9pay7200/223790123142',
   'description': '그중에서도 스마트폰을 이용해 금융업무를 볼 수 있게 해주는 <b>핀테크</b> 기술의 등장으로 금융시장에서 상당한 변화를 맞이하게 됐답니다. <b>핀테크</b>의 등장으로 현재 대부분의 금융업무는 스마트폰을 통해... ',
   'bloggername': '해외송금이 쉬워지는 순간 이나인페이',
   'bloggerlink': 'blog.naver.com/e9pay7200',
   'postdate': '20250310'},
  {'title': '[기자단 뉴스] 보험 <b>핀테크</b> 트렌드 (인슈어테크/온디맨드 보험)',
   'link': 'https://blog.naver.com/koreafintech/223661661653',
   'description': '보험 <b>핀테크</b> 트렌드 제12기 대학생 기자단 이서현 인슈어테크 인슈어테크는 보험과 기술의 합성어로... 보험 <b>핀테크</b> 트렌드 인슈어테크와 온디맨드 보험은 보험 산업의 혁신을 이끄는 핵심 요소로, 소비자에게... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241118'},
  {'title': '<b>핀테크</b> 뜻 종류 기업 국내 미국 관련주 총정리!',
   'link': 'https://blog.naver.com/se4125/223711366625',
   'description': '<b>핀테크</b>는 금융과 기술의 결합으로, 우리의 금융 생활을 혁신하는 핵심 분야로 떠오르고 있습니다. 간편결제, 대출, 투자, 자산관리가지 <b>핀테크</b>는 더 이상 선택이 아닌 필수가 되고 있는데요. 그런데... ',
   'bloggername': '자유연구소',
   'bloggerlink': 'blog.naver.com/se4125',
   'postdate': '20250101'},
  {'title': '[4/14까지][서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고... ',
   'link': 'https://blog.naver.com/ilsinbc/223800254706',
   'description': '기술 [서울] 2025년 <b>핀테크</b> 기술사업화 지원사업 공고(서울형 R&amp;D 지원사업) 소관부처·지자체 : 서울특별시 사업수행기관 : 서울경제진흥원 신청기간 : 2025.03.25 ~ 2025.04.14 사업개요 2025년 <b>핀테크</b>... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250318'},
  {'title': '<b>핀테크</b> 뜻 투자방법 알아봐요',
   'link': 'https://blog.naver.com/jungmk1570/223602309573',
   'description': '오늘은 <b>핀테크</b>(FinTech)를 활용한 소액 투자에 대해 이야기해보려고 해요. 최근 주식시장과 금리인하의 변동성으로 인해 많은 사람들이 안정적인 투자처를 찾고 있습니다. 이러한 상황에서 <b>핀테크</b> 플랫폼을... ',
   'bloggername': '재테크 허니',
   'bloggerlink': 'blog.naver.com/jungmk1570',
   'postdate': '20241001'},
  {'title': '<b>핀테크</b> 기업을 위한 금융 클라우드 지원 사업 (~4/4)',
   'link': 'https://blog.naver.com/n_cloudplatform/223790696137',
   'description': '돈과 개인정보를 다루는 만큼 금융∙<b>핀테크</b> 업계는 보안이 정말 중요한데요. 그렇기 때문에 금융∙<b>핀테크</b> 기업이 혁신적인 서비스를 개발하기 위해선 믿을 수 있는 안전한 클라우드 환경이 꼭... ',
   'bloggername': '네이버클라우드 (NAVER Cloud)',
   'bloggerlink': 'blog.naver.com/n_cloudplatform',
   'postdate': '20250310'},
  {'title': '<b>핀테크</b>로 바뀐 금융의 미래... 2025 일본 <b>핀테크</b> 혁신기업 연수단',
   'link': 'https://blog.naver.com/iloveimier/223768487894',
   'description': '바로 <b>핀테크</b>(FinTech)의 등장 덕분인데요!! 오늘은 우리 생활 속 중요한 부분으로 자리 잡은 <b>핀테크</b>에 대해 좀 더 깊이 알아보고, 이와 관련된 연수 프로그램을 소개해 드리겠습니다! <b>핀테크</b>란? <b>핀테크</b>는... ',
   'bloggername': '한경협국제경영원(IMI) 블로그',
   'bloggerlink': 'blog.naver.com/iloveimier',
   'postdate': '20250221'},
  {'title': '테솔 컬리지, 2025년 <b>핀테크</b>허브 기업 선정!',
   'link': 'https://blog.naver.com/tesol_college/223813299337',
   'description': '2025년 <b>핀테크</b>허브입주기업으로 선정되었습니다! 이번 선정을 통해 테솔컬리지는 영어교육과 기술이 융합된 에듀테크 기반 사업모델을 더욱 본격적으로 전개할 수 있게 되었습니다.  <b>핀테크</b>허브란?... ',
   'bloggername': '테솔 자격증 : TESOL College',
   'bloggerlink': 'blog.naver.com/tesol_college',
   'postdate': '20250328'},
  {'title': '대한민국의 디지털 금융 혁신: 세계가 주목하는 K-<b>핀테크</b>',
   'link': 'https://blog.naver.com/tnalsrla2002/223797958470',
   'description': '대한민국은 최첨단 디지털 금융 기술을 기반으로 <b>핀테크</b>(FinTech) 강국으로 성장하고 있으며, 글로벌... 글로벌 <b>핀테크</b> 시장을 선도하는 대한민국 한국의 <b>핀테크</b> 기업들은 글로벌 시장에 진출하며, 해외에서도... ',
   'bloggername': 'IT감사팀장이 전하는 보안•감사•포렌식',
   'bloggerlink': 'blog.naver.com/tnalsrla2002',
   'postdate': '20250316'},
  {'title': '[ 업스타트 홀딩스 ] AI와 금융의 만남,<b>핀테크</b> 대출 시장을... ',
   'link': 'https://blog.naver.com/gopagi7/223814284723',
   'description': '개요 업스타트 홀딩스(티커: UPST)는 AI 기반 대출 플랫폼을 운영하는 <b>핀테크</b> 기업으로, 전통적인... ㆍ규제 및 경쟁 심화 → <b>핀테크</b> 기업 및 전통 금융기관과 경쟁. 5. 향후 전망 ㆍAI 모델 고도화 → 신용... ',
   'bloggername': '사고싶은주식',
   'bloggerlink': 'blog.naver.com/gopagi7',
   'postdate': '20250329'},
  {'title': '[<b>핀테크</b>] 2025 <b>핀테크</b> 전망: 주목해야 할 10가지 변화',
   'link': 'https://blog.naver.com/xoom777/223702449504',
   'description': '2025년이 다가오면서, 금융 기술, 즉 <b>핀테크</b> 분야에서 흥미로운 변화들이 예상되고 있어. 인공지능의... 이제 2025년에 주목해야 할 10가지 <b>핀테크</b> 트렌드를 함께 살펴보자. 1. 웰스테크(WealthTech)의 부상... ',
   'bloggername': 'Ich fange an',
   'bloggerlink': 'blog.naver.com/xoom777',
   'postdate': '20241223'},
  {'title': '소셜 <b>핀테크</b>, 왜 사람들이 계속 이용할까?',
   'link': 'https://blog.naver.com/flyfirst0101/223789749173',
   'description': '<b>핀테크</b>를 활용해서 2~3천만원의 결혼 자금을 만드는 사람부터 1천만원 이내의 시드머니를 빠른 시간내에 확보하여 투자에 활용하는 사람까지 참여자들이 급속도로 늘어나고 있습니다. 재밌는 점은 소셜 <b>핀테크</b>... ',
   'bloggername': '아임인 공식 블로그',
   'bloggerlink': 'blog.naver.com/flyfirst0101',
   'postdate': '20250309'},
  {'title': '아프리카 스타트업 생태계의 <b>핀테크</b> 중심 현상 속 주요... ',
   'link': 'https://blog.naver.com/viewist/223662800063',
   'description': "최근 한 자리에서 아프리카 스타트업 생태계의 주요 특징 중 하나가 '<b>핀테크</b> 중심의 성장'이라고... 아프리카 스타트업 생태계는 <b>핀테크</b> 중심지? 가장 최근 유니콘 기업으로 등극한 나이지리아의 모니포인트를... ",
   'bloggername': '아프리카의 IT와 스타트업 <<AFRITUP 아프릿업>>',
   'bloggerlink': 'blog.naver.com/viewist',
   'postdate': '20241116'},
  {'title': '[기자단 뉴스] 2024년 <b>핀테크</b> 해외 이슈',
   'link': 'https://blog.naver.com/koreafintech/223621158409',
   'description': '2024년 <b>핀테크</b> 해외 이슈 제12기 대학생 기자단 이서현 이제는 손바닥 결제 시대? 중국의 텐센트가... 기사를 작성하며 제가 ‘손바닥 결제’와 ‘암호화폐 채굴’이라는 주제를 선택한 이유는 <b>핀테크</b> 분야의... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20241016'},
  {'title': '[프로모션] 최대 9600만원 지원, NHN Cloud <b>핀테크</b> 기업 수요... ',
   'link': 'https://blog.naver.com/nhncloud_official/223805041831',
   'description': 'NHN Cloud는 <b>핀테크</b> 기업에게 중요한 안전한 인프라와 폭넓은 기술 지원을 5년 연속 제공하고 있습니다. NHN Cloud의 <b>핀테크</b> 기업을 위한 특별한 혜택을 안내해 드립니다. ‘금융 클라우드 지원사업’이란?... ',
   'bloggername': '유연하게 안전하게 비즈니스에 힘이 되다 ☁️',
   'bloggerlink': 'blog.naver.com/nhncloud_official',
   'postdate': '20250325'},
  {'title': '금융혁신의 물결, 금융회사와 <b>핀테크</b> 기업의 만남',
   'link': 'https://blog.naver.com/bbcoco_/223816763860',
   'description': '금융회사-<b>핀테크</b> 기업 상호만남(Meet-Up) 행사가 성황리에 개최되었습니다. 이번 행사는 금융혁신법상 지정대리인 및 위탁테스트 제도를 적극 활용하여 <b>핀테크</b> 기업과 금융회사의 협업을 촉진하기 위해 2023년부터... ',
   'bloggername': '귀염둥이모험기',
   'bloggerlink': 'blog.naver.com/bbcoco_',
   'postdate': '20250331'},
  {'title': '<b>핀테크</b> 뜻 관련주 기업 추천앱 예시 알아보기',
   'link': 'https://blog.naver.com/choi9503/223713796013',
   'description': '<b>핀테크</b> 뜻 관련주 기업 추천앱 예시 알아보기 최근 몇 년간 <b>핀테크</b>라는 산업의 성장이 눈에 띄게 증가하고 있습니다 특히 아세안 지역에서의 확장이 두드러지고 있는데, 인도네시아나 말레이시아 그리고... ',
   'bloggername': '부동산 경제 건강 일상 맛집 이야기 !!',
   'bloggerlink': 'blog.naver.com/choi9503',
   'postdate': '20250104'},
  {'title': '<b>핀테크</b> 기업 종류 뜻 및 서비스와 관련 용어',
   'link': 'https://blog.naver.com/possiblehoya/223387198263',
   'description': '이번 포스팅에서는 우리나라에서 카카오페이, 네이버페이 등으로 유명한 <b>핀테크</b> 기업 종류와 뜻 그리고 관련 서비스와 용어 등에 대해 정리해 보도록 하겠습니다! <b>핀테크</b> 뜻 무엇일까?! <b>핀테크</b>(FinTech)는... ',
   'bloggername': '커피 이코노미스트',
   'bloggerlink': 'blog.naver.com/possiblehoya',
   'postdate': '20240318'},
  {'title': '<b>핀테크</b> 뜻 유래 기업 사례',
   'link': 'https://blog.naver.com/toresi/223471507785',
   'description': '<b>핀테크</b> 하루 1분 금융경제용어 안녕하세요. ^^ 오늘의 경제용어입니다. <b>핀테크</b> 뜻은 무엇인가? <b>핀테크</b>(FinTech) 금융(Finance)과 기술(Technology)의 합성어로, 금융 서비스를 기술적으로 혁신하여 융합하는 것을... ',
   'bloggername': '은행원쀼에게 금융 묻고 더블로',
   'bloggerlink': 'blog.naver.com/toresi',
   'postdate': '20240607'},
  {'title': '서울<b>핀테크</b>랩, ‘<b>핀테크</b> 스타트업을 위한 정부지원사업·R&amp;D... ',
   'link': 'https://blog.naver.com/venturesquare_/223727540072',
   'description': '서울<b>핀테크</b>랩은 1월 14일 서울<b>핀테크</b>랩에서 <b>핀테크</b> 기업을 대상으로 ‘2025년 서울<b>핀테크</b>랩과 함께하는 <b>핀테크</b> 스타트업을 위한 정부지원사업·R&amp;D·TIPS 알아보기’ 컨퍼런스를 개최하고 마무리했다고 밝혔다.... ',
   'bloggername': 'VentureSquare',
   'bloggerlink': 'blog.naver.com/venturesquare_',
   'postdate': '20250116'},
  {'title': '[3/26까지][금융위원회]2025년 제1차 <b>핀테크</b> 해외진출 컨설팅... ',
   'link': 'https://blog.naver.com/ilsinbc/223788341613',
   'description': '수출 2025년 제1차 <b>핀테크</b> 해외진출 컨설팅 참여기업 모집 공고 소관부처·지자체 : 금융위원회 사업수행기관 : 한국<b>핀테크</b>지원센터 신청기간 : 2025.03.05 ~ 2025.03.26 사업개요 한국<b>핀테크</b>지원센터(이하... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250308'},
  {'title': '더즌 공모주 수요예측 결과 <b>핀테크</b> 관련주',
   'link': 'https://blog.naver.com/bss2062/223792343321',
   'description': '더즌 공모주 수요예측 결과 <b>핀테크</b> 관련주 카카오페이의 자회사로도 알려져 있는 더즌이 내일 청약에... 기업정보 더즌은 인터넷, 모바일을 통해 간편하게 금융 거래를 제공해 주는 <b>핀테크</b> 기업이다. 우리가... ',
   'bloggername': '슈레카의 경제노트',
   'bloggerlink': 'blog.naver.com/bss2062',
   'postdate': '20250311'},
  {'title': 'K-<b>핀테크</b> 글로벌화를 통한 성장(Scale-up) 지원',
   'link': 'https://blog.naver.com/blogfsc/223749886170',
   'description': '2025년 제1차 「<b>핀테크</b> 지원협의체」 개최 -해외진출 지원 프로그램 예산 신설 등 정부·금융회사 연계 해외진출 지원 -코리아 <b>핀테크</b> 위크(AI와 <b>핀테크</b>를 주제로 11월 개최) 글로벌존 확장 예정... ',
   'bloggername': '금융위원회 공식 블로그',
   'bloggerlink': 'blog.naver.com/blogfsc',
   'postdate': '20250206'},
  {'title': '글로벌 금융 혁신을 향한 도전 : 쿠콘, 싱가폴 <b>핀테크</b> 페스티벌... ',
   'link': 'https://blog.naver.com/webcashgroup/223660359266',
   'description': 'WE-하 오늘 전해 드릴 이야기는 최근 비즈니스 데이터 플랫폼 기업 쿠콘이 세계 최대 <b>핀테크</b> 행사인 ‘싱가포르 <b>핀테크</b> 페스티벌 2024’에 참가했다는 소식입니다! 싱가포르 <b>핀테크</b> 페스티벌은 매년 전 세계의... ',
   'bloggername': '웹케시그룹 공식 블로그',
   'bloggerlink': 'blog.naver.com/webcashgroup',
   'postdate': '20241114'},
  {'title': 'AI <b>핀테크</b>와 재테크',
   'link': 'https://blog.naver.com/commbooks/223704297144',
   'description': 'AI와 <b>핀테크</b> 기술이 금융과 재테크 분야를 어떻게 혁신하는지 탐구한다. AI 기반 로보어드바이저와... AI와 <b>핀테크</b> 기술을 효과적으로 활용한 재테크 전략과 함께 윤리적 기준을 고려한 금융 서비스의 미래를... ',
   'bloggername': '커뮤니케이션북스',
   'bloggerlink': 'blog.naver.com/commbooks',
   'postdate': '20241224'},
  {'title': '이것도 <b>핀테크</b>? 운전 습관에 따라 보험료가... ',
   'link': 'https://blog.naver.com/koreafintech/223803803517',
   'description': '이것도 <b>핀테크</b>? #1편 운전 습관에 따라 보험료가 달라지는 BBI (Behavior-Based Insurance) 인슈어테크로... 오늘은 보험의 <b>핀테크</b>인 인슈어테크(InsureTech) 중 “운전행태 기반 자동차 보험 (BBI, Behavior-Based Insurance)... ',
   'bloggername': '한국핀테크지원센터',
   'bloggerlink': 'blog.naver.com/koreafintech',
   'postdate': '20250321'},
  {'title': "'<b>핀테크</b>'에 대해서 알고있나요?",
   'link': 'https://blog.naver.com/mmdm1989/223669850292',
   'description': "'<b>핀테크</b>'란 금융(Finance)과 기술(Technology)의 합성어로 금융과 정보통신(IT)기술의 융합을 통한... <b>핀테크</b>는 2000년대 초반, 인터넷이 발달하면서 태동하였습니다. 직접적으로 영향을 미친 것은... ",
   'bloggername': 'SD명문학원',
   'bloggerlink': 'blog.naver.com/mmdm1989',
   'postdate': '20241122'},
  {'title': '경제용어 <b>핀테크</b>,(모바일 시대)',
   'link': 'https://blog.naver.com/expert_1/223784395284',
   'description': '<b>핀테크</b>가 무엇인지 그 개념과 어떠한 분야에서 유용하게 쓰이고 있는지 간단하게 정리를 해보겠습니다. <b>핀테크</b>(FinTech/ Financial Technology)는 금융(Finance)과 기술(Technology)이 합쳐진 말입니다. 금융 서비스와... ',
   'bloggername': '빛을 담는 마법사',
   'bloggerlink': 'blog.naver.com/expert_1',
   'postdate': '20250305'},
  {'title': '금융의 디지털 혁신을 만들어준 <b>핀테크</b>',
   'link': 'https://blog.naver.com/kiat_tech/223691416200',
   'description': '<b>핀테크</b> 2.0 시대 돌입 ✔ <b>핀테크</b>는 스마트폰 등장 이후 디지털 결제, 대출, 투자 등으로 확장된 금융 혁신 기술 ✔ AI 기반 <b>핀테크</b>는 개인화된 금융 비서 역할과 효율성 극대화로 스마트한 금융 서비스 제공... ',
   'bloggername': '한국산업기술진흥원 블로그',
   'bloggerlink': 'blog.naver.com/kiat_tech',
   'postdate': '20241227'},
  {'title': '금융산업 전문인력 양성 ‘<b>핀테크</b> 캠프’ 운영',
   'link': 'https://blog.naver.com/leebangheui/223724159445',
   'description': '전주대학교(총장 박진배) 대학일자리플러스센터는 <b>핀테크</b> 산업에 관심이 있는 재학생 및 졸업생 29명을 대상으로 지난 1월 7일부터 3박 4일 간 서울국제금융센터(One IFC)에서“<b>핀테크</b> 캠프”를 운영했다고... ',
   'bloggername': 'BANGABANGA',
   'bloggerlink': 'blog.naver.com/leebangheui',
   'postdate': '20250113'},
  {'title': '미국과 영국 <b>핀테크</b>(Fintech)석사 추천학교 (feat.... ',
   'link': 'https://blog.naver.com/mskonan/223652313232',
   'description': '요즘 <b>핀테크</b>(Fintech)에 대한 관심이 높아지고 있습니다. 오늘은 미국과 영국에서 <b>핀테크</b>(Fintech)를 공부할수 있는 학교를 살펴보겠습니다. <b>핀테크</b>(Fintech)란 금융(Financial)과 기술... ',
   'bloggername': '30년 유학전문가의 유학이야기',
   'bloggerlink': 'blog.naver.com/mskonan',
   'postdate': '20241108'},
  {'title': '2025년! 한국 <b>핀테크</b>의 기업공개(IPO)가 시작된다.',
   'link': 'https://blog.naver.com/sijifs/223710220973',
   'description': '한국 <b>핀테크</b>의 기업공개(IPO)가 시작된다. 한국 <b>핀테크</b> 기업, 10년만에 흑자 전환 날짜 2024.12.31. 신문사 한국경제 기사제목 &quot;10여년 만의 흑자&quot;…<b>핀테크</b>社 내년 대도약하나 What <b>핀테크</b> 토스 앱을 운영하고... ',
   'bloggername': '[MitakuyeOyasin] 사진-책-연극-뮤지컬-동물-스페인',
   'bloggerlink': 'blog.naver.com/sijifs',
   'postdate': '20241231'},
  {'title': '[예산소진시까지][금융위원회]2025년 <b>핀테크</b> 보안지원 사업 공고',
   'link': 'https://blog.naver.com/ilsinbc/223773767425',
   'description': '기술 2025년 <b>핀테크</b> 보안지원 사업 공고 소관부처·지자체 : 금융위원회 사업수행기관 : 한국<b>핀테크</b>지원센터 신청기간 : 예산 소진시까지 사업개요 오픈뱅킹 참여기업, 금융규제 테스트베드 선정기업... ',
   'bloggername': '경영지도사 김진영의 105세 경영',
   'bloggerlink': 'blog.naver.com/ilsinbc',
   'postdate': '20250225'},
  {'title': "한국<b>핀테크</b>산업협회, '중소 <b>핀테크</b> 기업을 위한 AML 전략... ",
   'link': 'https://blog.naver.com/venturesquare_/223731241945',
   'description': '한국<b>핀테크</b>산업협회(이하 협회)는 Asia Fintech Alliance(AFA·아시아 <b>핀테크</b> 연합)와 공동으로 ‘중소 <b>핀테크</b> 기업을 위한 AML 전략’을 주제로 웨비나를 개최했다. 이번 웨비나는 아시아 14개국의 <b>핀테크</b>... ',
   'bloggername': 'VentureSquare',

In [3]:
headers

{'X-Naver-Client-Id': 'KWqT_uEHMFwBxZHzqvXj',
 'X-Naver-Client-Secret': 'UaIJQBMlNd'}

네이버 검색 API를 이용해서 책을 검색하고 결과를 데이터프레임으로 만드세요
* 검색어는 input()을 이용해서 입력받은 값을 이용하세요.

In [4]:
keyword = input('제목을 입력하세요: ')

url = "https://openapi.naver.com/v1/search/book.json"
payload = {'query': keyword, 'display': 100}  

# 아이디 비밀번호 header로 입력
headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 'X-Naver-Client-Secret' : 'UaIJQBMlNd'}

# 본격적으로 분석
r = requests.get(url, params=payload, headers=headers)

data = r.json()         

book_dic = {}
for item in data['items']:
    for key, value in item.items():
        book_dic.setdefault(key,[]).append(value)

book_df = pd.DataFrame(book_dic)
book_df

제목을 입력하세요: 파이썬

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
95,마케터의 파이썬 (코딩의 C도 모르는 우리들을 위한 맞춤 프로그래밍 가이드),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324903...,정희석,19800,e비즈북스,20220126,9791157832361,코딩의 첫 허들을 성공적으로 넘는 마케터가 되자!\n\n파이썬 관련 강의와 도서는 ...
96,파이썬 알고리즘,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324907...,최영규,24840,생능출판,20210128,9788970504797,현대 사회를 살아가고 있는 우리에게 ‘알고리즘’은 더 이상 낯선 단어가 아닙니다. ...
97,시간순삭 파이썬 (당신의 1분 1초를 아껴줄),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324837...,천인국^정영민^최자영,22000,생능북스,20200827,9788970504650,이 책은 프로그래밍을 처음 시작하거나 너무 어려워 기초부터 다시 배우고 싶은 학습자...
98,두근두근 파이썬 (쉽고! 재밌고! 흥미로운 코딩 맛!),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324646...,천인국,24000,생능출판,20170116,9788970508931,『두근두근 파이썬』은 프로그래밍을 처음 시작하는 학습자도 쉽게 따라올 수 있도록 변...
99,자기주도 파이썬 (정보영재 및 올림피아드를 위한 최적의 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324730...,한컴에듀케이션 알고리즘연구소,0,복두출판사,20210730,9791166750564,이 책의 활용 방법\n이 책은 각 단원마다 따라하면서 쉽게 익힐 수 있는 기본학습과...

In [5]:
# 네이버 검색 API 예제 - 블로그 검색

####################################################################
# 1. url 주소로 서버에 url과 parameter를 보냄
# 2. 서버로부터 응답을 받음
# 3, 응답코드가 200이면 출력
####################################################################

import os
import sys
import urllib.request

book = input('제목을 입력하세요: ')

client_id = "KWqT_uEHMFwBxZHzqvXj"
client_secret = "UaIJQBMlNd"

encText = urllib.parse.quote(book)   # parse.quote는 utf-8코드로 인코딩
url = "https://openapi.naver.com/v1/search/book.json?query=" + encText # JSON 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + encText # XML 결과
# 블로그는 blog,json / 뉴스는 news.json / 백과사전은 encyc.json 등으로 구분


request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)

response = urllib.request.urlopen(request)
rescode = response.getcode()

if(rescode==200):      # 에러코드
    response_body = response.read()
else:
    print("Error Code:" + rescode)
    
data2 = response_body.decode('utf-8') # 컴퓨터 언어 -> 한글로 디코딩 실행
data2 = json.loads(data2)       # 문자를 딕셔너리로

book_dic2 = {}
for item in data2['items']:
    for key, value in item.items():
        book_dic2.setdefault(key,[]).append(value)

book_df2 = pd.DataFrame(book_dic2)
book_df2

제목을 입력하세요: 파이썬

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
5,"제대로 시작하는 챗GPT와 AI 활용 with 파이썬 (프롬프트 엔지니어링, 음성 ...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_536839...,에이먼 엘 암리,22500,한빛미디어,20250324,9791169213639,파이썬으로 배우는AI와 챗GPT 활용법!\n매혹적인 인공지능의 세계를 탐험하며 실제...
6,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324609...,홍의경,29440,생능출판,20220309,9788970506784,코딩 실력을 키우는 지름길은 실습이다.\n\n2008년 즈음에 검인정 중학교 교과서...
7,CODING BASICS PYTHON (파이썬),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324409...,김상민^장성식^김일태,18000,렉스미디어닷넷,20220210,9788959604210,파이썬으로 다지는 프로그래밍의 기초\n\nㆍ 다양한 예제를 활용하여 초보자도 쉽게 ...
8,파이썬 (제2판),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324362...,염기원^오지영,16200,북두,20220120,9791166750991,책의 전반부는 비전공자의 입장에서 비전공자를 위한 파이썬 프로그래밍의 기초적인 내용...
9,파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324891...,천인국,10800,인피니티북스,20170830,9791185578330,컴퓨팅 사고(Computational Thinking)는 자넷 윙 교수가 2006년...

함수 이용 풀이

In [6]:
def unpack(data):
    book_dic = {}
    for item in data['items']:
        for key, value in item.items():
            book_dic.setdefault(key,[]).append(value)
    return book_dic

def unpack2(data, dic):
    for item in data['items']:
        for key, value in item.items():
            dic.setdefault(key,[]).append(value)
    return dic

In [7]:
keyword = input('제목을 입력하세요: ')

url = "https://openapi.naver.com/v1/search/book.json"
payload = {'query': keyword, 'display': 100, 'start':1, 'sort': 'sim'}  

# 아이디 비밀번호 header로 입력
headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 'X-Naver-Client-Secret' : 'UaIJQBMlNd'}

# 본격적으로 분석
r = requests.get(url, params=payload, headers=headers)
data = r.json()   

print("전체 검색 페이지 수: ", data['total'], "검색할 페이지 수: ", int(data['total']//100 + 1))

book_dic = unpack(data)
book_df = pd.DataFrame(book_dic)
book_df

제목을 입력하세요: 파이썬
전체 검색 페이지 수:  1113 검색할 페이지 수:  12

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
95,마케터의 파이썬 (코딩의 C도 모르는 우리들을 위한 맞춤 프로그래밍 가이드),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324903...,정희석,19800,e비즈북스,20220126,9791157832361,코딩의 첫 허들을 성공적으로 넘는 마케터가 되자!\n\n파이썬 관련 강의와 도서는 ...
96,파이썬 알고리즘,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324907...,최영규,24840,생능출판,20210128,9788970504797,현대 사회를 살아가고 있는 우리에게 ‘알고리즘’은 더 이상 낯선 단어가 아닙니다. ...
97,시간순삭 파이썬 (당신의 1분 1초를 아껴줄),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324837...,천인국^정영민^최자영,22000,생능북스,20200827,9788970504650,이 책은 프로그래밍을 처음 시작하거나 너무 어려워 기초부터 다시 배우고 싶은 학습자...
98,두근두근 파이썬 (쉽고! 재밌고! 흥미로운 코딩 맛!),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324646...,천인국,24000,생능출판,20170116,9788970508931,『두근두근 파이썬』은 프로그래밍을 처음 시작하는 학습자도 쉽게 따라올 수 있도록 변...
99,자기주도 파이썬 (정보영재 및 올림피아드를 위한 최적의 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324730...,한컴에듀케이션 알고리즘연구소,0,복두출판사,20210730,9791166750564,이 책의 활용 방법\n이 책은 각 단원마다 따라하면서 쉽게 익힐 수 있는 기본학습과...

# 2. 네이버 API로 검색한 결과 최대한 가져오기
* 1회 네이버 서버에 요청
* 응답에서 total을 찾아서 display로 나누어 총 반복할 페이지 산출
* 반복문 작성 및 종료 조건 설정
* 1페이지 결과를 데이터 프레임으로 만들고 리스트에 append
* 반복이 끝난 후 리스트에 append 된 데이터 프레임을 1개로 합침

In [8]:
def unpack(data):
    book_dic = {}
    for item in data['items']:
        for key, value in item.items():
            book_dic.setdefault(key,[]).append(value)
    return book_dic

def unpack2(data, dic):
    for item in data['items']:
        for key, value in item.items():
            dic.setdefault(key,[]).append(value)
    return dic

### for 문 이용한 풀이

In [9]:
keyword = input('제목을 입력하세요: ')

url = "https://openapi.naver.com/v1/search/book.json"
payload = {'query': keyword, 'display': 100, 'start':1, 'sort': 'sim'}  

headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 'X-Naver-Client-Secret' : 'UaIJQBMlNd'}

r = requests.get(url, params=payload, headers=headers)
data = r.json()     
book_dic = unpack(data)

page = data['total'] // 100 + 1

for i in range(101,1000,100):
    if data['total'] > page*100:
        break
    payload = {'query': keyword, 'display': 100, 'start':i, 'sort': 'sim'}  
    r = requests.get(url, params=payload, headers=headers)
    data = r.json()   
    book_dic = unpack2(data, book_dic)
    

book_df = pd.DataFrame(book_dic)    
book_df

제목을 입력하세요: 파이썬

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
995,IoT 사물인터넷을 위한 라즈베리파이 4 정석 (파이썬을 활용한 센서제어 및 나만의...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324646...,최주호^김재범^정동진,0,앤써북,20191130,9791185553573,『IoT 사물인터넷을 위한 라즈베리파이 4 정석』은 왕초보도 라즈베리파이를 이용해 ...
996,파이썬으로 배우는 Anti-Virus 구조와 원리 (예제와 오픈소스를 통해 이해하는...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324562...,최원혁,30600,비제이퍼블릭,20170927,9791186697412,파이썬을 통해 전체적인 백신의 구조와 동작 원리를 정확한 이해할 수 있도록 안내한다...
997,이토록 쉬운 딥러닝을 위한 기초 수학 with 파이썬,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324361...,마스이 도시카츠,0,루비페이퍼,20190813,9791186710524,딥러닝도 모르겠는데 수학은 손놓은 지 오래다?\n이 책을 한마디로 설명하자면 ‘수학...
998,파이썬을 활용한 공격적 & 방어적 해킹 프로그래밍 세트 (창의적이고 새로운 관점을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324903...,저스틴 지이츠,0,에이콘출판,20150511,9788960777064,[파이썬을 활용한 공격적 & 방어적 해킹 프로그래밍 세트]는 해커와 모의 침투 테스...
999,파이썬과 케라스를 이용한 딥러닝/강화학습 주식투자 (퀀트 투자 알고리즘 트레이딩을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324920...,김문권,0,위키북스,20180529,9791158391065,강화학습은 스스로 학습하는 머신러닝 기법으로서 주식 데이터 학습에 잘 적용되는 기법...

### while문 이용한 풀이

In [10]:
keyword = input('제목을 입력하세요: ')

url = "https://openapi.naver.com/v1/search/book.json"
i = 1
book_dic = {}
            

while (i <= 1000):
    payload = {'query': keyword, 'display': 100, 'start':i, 'sort': 'sim'}  
    headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 'X-Naver-Client-Secret' : 'UaIJQBMlNd'}
    r = requests.get(url, params=payload, headers=headers)
    
    data = r.json()
    for item in data['items']:
        for key, value in item.items():
            book_dic.setdefault(key,[]).append(value)
    
    if i >= (data['total']):
        break
    else:
        if i == 901:
            i += 99
        else:
            i += 100
            
# pd.concat() 합치는 함수

book_df = pd.DataFrame(book_dic)    
book_df

제목을 입력하세요: 파이썬

,title,link,image,author,discount,publisher,pubdate,isbn,description
0,"혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임,...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_528593...,문현일,23400,한빛미디어,20250214,9791169213271,“파이썬을 배워서 어디에 활용할 수 있을지 궁금했나요?”\n나의 신용카드 내역 분석...
1,혼자 공부하는 파이썬 (1:1 과외하듯 배우는 프로그래밍 자습서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_325076...,윤인성,19800,한빛미디어,20220601,9791162245651,혼자 해도 충분하다! 1:1 과외하듯 배우는 파이썬 프로그래밍 자습서\n\n『혼자 ...
2,Do it! 점프 투 파이썬 (중학생도 첫날부터 실습하는 초고속 입문서),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_403540...,박응용,19800,이지스퍼블리싱,20230615,9791163034735,프로그래밍 분야 8년 연속 베스트셀러!\n《Do it! 점프 투 파이썬》 전면 개정...
3,밑바닥부터 시작하는 딥러닝 1(리마스터판) (파이썬으로 익히는 딥러닝 이론과 구현),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_526155...,사이토 고키,23400,한빛미디어,20250124,9791169213387,딥러닝 분야 부동의 베스트셀러!\n머리로 이해하고 손으로 익히는 가장 쉬운 딥러닝 ...
4,50개의 프로젝트로 완성하는 파이썬 업무 자동화 (프로젝트 따라하기로 업무 자동화 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_537377...,오토코더,19800,위즈앤북(Wiznbook),20250317,9791198685353,ㆍ퀴즈와 QR 코드 생성부터 나만의 음성 비서 제작까지 다양한 프로젝트 대공개!\n...
...,...,...,...,...,...,...,...,...,...
1095,"챗GPT와 업무자동화 (1분 만에 끝내는 엑셀, 구글 시트, 파워포인트, 파이썬 자...",https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_386135...,김철수,16200,위키북스,20230321,9791158394288,"코드 한 줄 몰라도 1분 만에 끝내는 엑셀, 구글 스프레드시트, 파워포인트 업무 자..."
1096,프로그래밍 정석(개념을 잡아주는) (기초 연산부터 고급 문제해결 능력까지 파이썬을 ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,제니퍼 캠벨^폴 그리스^제이슨 몬토조^그렉 윌슨,0,에이콘출판,20100504,9788960771338,"『개념을 잡아주는 프로그래밍 정석』은 기본적인 프로그래밍 요소부터 알고리즘, 디버깅..."
1097,머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이노...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324665...,서민우,0,앤써북,20220520,9791185553979,〈머신러닝 딥러닝을 이용한 A.I. 자율주행 RC카 프로젝트 with 파이썬+아두이...
1098,파이썬 딥러닝 파이토치(Python Deep Learning PyTorch),https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324549...,이경택^방성수^안상준,14800,정보문화사,20201008,9788956748573,파이썬은 선택이 아닌 필수! 파이토치로 딥러닝 입문하기!\n\n이 책은 딥러닝 기술...
1099,Let’s Start Coding with Raptor & Python (랩터 & ...,https://search.shopping.naver.com/book/catalog...,https://shopping-phinf.pstatic.net/main_324972...,김충석,0,앤아이컴즈,20190815,9788993163568,▶ 이 책은 Python(파이썬)을 다룬 이론서입니다.

# 3. request 모듈 사용법

* 1) 모듈 불러오기 : import requests
* 2) url 변수에 저장
* 3) url 파라미터
    * payload = {파라미터1 : value, 파라미터2 : value}
* 4) header
    * headers = {key : value}
* 5) HTTP 요청 보내기 get, post
    * get: r = request.get(url, params=payload, headers=headers)
    * post: r = request.post(url,data={key:value})
* 6) 만들어진 url 확인: print(r.url)
* 7) 응답 코드 확인: print(r.status_code)
* 8) 응답 요소 출력: r.text, r.content, r.json()

In [11]:
import requests
url= ""
payload = dict()
headers = {}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()

In [14]:
import requests
url= "https://openapi.naver.com/v1/search/book.json"
payload = {'query': '핀테크', 'display': 100, 'start':1, 'sort': 'sim'}
headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 
           'X-Naver-Client-Secret' : 'UaIJQBMlNd'}
r = requests.get(url, params=payload, headers=headers)
print(r.url)
print(r.status_code)
response = r.json()
response2 = r.content   # 디코딩 X

https://openapi.naver.com/v1/search/book.json?query=%ED%95%80%ED%85%8C%ED%81%AC&display=100&start=1&sort=sim
200

In [13]:
response

{'lastBuildDate': 'Tue, 01 Apr 2025 10:30:38 +0900',
 'total': 106,
 'start': 1,
 'display': 100,
 'items': [{'title': '핀테크',
   'link': 'https://search.shopping.naver.com/book/catalog/32438306822',
   'image': 'https://shopping-phinf.pstatic.net/main_3243830/32438306822.20230920073135.jpg',
   'author': '한석주',
   'discount': '11400',
   'publisher': '커뮤니케이션북스',
   'pubdate': '20151101',
   'isbn': '9791130441436',
   'description': '디지털 기술의 발달은 금융의 모든 것을 바꾸고 있다. 기술 기반의 스타트업들과 비금융권 기업들이 금융 시장에 진입하며 은행을 해체하고 대체해 가는 시대가 오고 있다. 핀테크의 핵심은 기술을 통해 기존의 금융 기관이 제공하지 못했던 부분을 채워 주고, 편의성 증대, 비용 절감, 리스크 분산, 기대 수익 증가 등 고객에게 새로운 가치를 주는 데 있다. 특히 고객들이 쌓은 데이터를 분석해 틈새를 찾아내고 새로운 시장으로 만드는 것이 중요하다. 이 책은 핀테크의 의미와 지급 결제, 대출, 자산관리, 가상 화폐 등 다양한 분야별 성공 사례와 시사점, 오프라인 기업의 대응, 그리고 각국의 핀테크 산업 육성 정책에 대해 살펴본다.'},
  {'title': '핀테크 (IT와 금융이 만나는 새로운 세상)',
   'link': 'https://search.shopping.naver.com/book/catalog/32506472036',
   'image': 'https://shopping-phinf.pstatic.net/main_3250647/32506472036.20220527060350.jpg',
   'author': '강창호',
   'discount': '0',
   'publisher': '한빛미디어',
   'pubdate': '20150605',
   'isbn': '9788968482007',
   'description': '금융과 기술로 혁신하는 핀테크 시장을 선점하라!\n\n상시 연결된 디지털 세상에서 혁신적인 금융 서비스를 제공하기 위한 최고의 핀테크 안내서!\n\n핀테크’란 금융을 뜻하는 파이낸셜(Financial)과 기술(Technology)의 합성어로 스마트 기기를 이용한 지급 결제 서비스뿐만 아니라 예금과 대출 및 자산 관리 등의 각종 금융 서비스를 IT 기술을 통해 처리하는 금융과 IT가 융합된 산업을 뜻한다. 이 책에서는 핀테크로 시작된 디지털 금융의 혁신을 위해 변화하는 시장 상황과 다양한 해외 선도 기업의 사례를 알아보고, 기업이 어떻게 변화해야 할 것인지 구체적으로 살펴본다. 애플, 구글, 페이팔, 알리바바 등 최신 기술을 무기로 새롭게 등장한 금융 플레이어들과 대적하기 위해 반드시 알고 있어야 할 핀테크의 모든 것을 다루면서 기술과 금융을 소비하는 금융 소비자에 대한 이해 및 소비자 경험 향상을 통해 기업이 나아가야 할 방향을 제시한다. 이 책은 핀테크 전문가가 들려주는 가장 확실한 핀테크 혁신 노하우로, 디지털 금융 혁신을 이해하고 준비하려는 금융 기관의 임원 및 현업 담당자뿐만 아니라 핀테크와 관련된 다양한 해외 사례 및 활용 방법을 고민하고 있는 금융 IT 종사자, 디지털 뱅킹의 미래에 대해 인사이트를 얻고자 하는 사람들에게도 실질적인 도움을 줄 수 있는 책이다.'},
  {'title': '핀테크 4.0 (핀테크 혁명과 금융의 미래)',
   'link': 'https://search.shopping.naver.com/book/catalog/52000746624',
   'image': 'https://shopping-phinf.pstatic.net/main_5200074/52000746624.20241219071112.jpg',
   'author': '김종현',
   'discount': '17100',
   'publisher': '한국금융연수원',
   'pubdate': '20241216',
   'isbn': '9788928782284',
   'description': '본서에서는 세계 최초로 핀테크 산업의 발전을 4단계로 구분하여 설명하는 [핀테크 4.0]의 개념을 도입하였다. 이러한 개념적 틀을 토대로 핀테크 산업에 대한 이론적인 설명 및 실무의 이해와 필요한 긴요한 요소들을 적재적소에 배치하였다. 아울러 60여개의 핀테크 기업에 대한 상세 분석을 포함한 풍부한 실례를 다뤘기에 산업계뿐만 아니라 교육현장에서도 활용가능성이 높다.'},
  {'title': '핀테크와 법 (제3판)',
   'link': 'https://search.shopping.naver.com/book/catalog/32441765997',
   'image': 'https://shopping-phinf.pstatic.net/main_3244176/32441765997.20221229073758.jpg',
   'author': '강현구^유주선^이성남',
   'discount': '19800',
   'publisher': '씨아이알',
   'pubdate': '20201112',
   'isbn': '9791156109020',
   'description': '핀테크의 영역과 그에 대한 법률문제의 간격을 \n어떻게 좁힐 수 있을 것인가\n\n핀테크 관련 기술의 발전이 급속하게 진행 중에 있다. 2018년 개정 이후 2년이 지난 후 이러한 핀테크 관련 법제를 반영하지 않으면 안 된다는 집필자들의 의견이 모아져 개정 3판을 금번에 출간하게 된 것이다.\n금번에 개정되는 제3판은 다음 내용을 업데이트하였다.\n\n첫째, 2020년 제안된 「전자금융거래법」 개정안에 대한 내용을 담았다.\n둘째, 소액해외송금업 관련 최근 개정된 「외국환거래법」의 내용을 반영하였다.\n셋째, P2P 대출과 관련하여 그동안 입법 방안이라는 내용을 담고 있었지만, 금번 개정판에서는 이제 제정된 P2P 대출법인 「온라인투자연계금융업 및 이용자 보호에 관한 법률」의 내용을 새로이 기술하였다.\n넷째, 「인터넷전문은행법」이 도입됨에 따라 인터넷전문은행 도입 관련 법적 쟁점에 새로운 법률의 주요 내용을 담았다.\n다섯째, 핀테크와 보험 파트에 인슈어테크에 관한 최신 내용을 담았다. 보험상품 개발에서부터 보험계약의 체결 및 보험금청구 등에서 발생할 수 있는 인슈어테크의 내용을 새로이 담았다.\n여섯째, 데이터 3법이 개정됨에 따라 빅데이터 관련 법적 쟁점과 그 영향 등의 내용을 담았다.\n일곱째, 가상통화 관련 법제로서 불완전하지만 가상자산을 법제화한 개정 「특정 금융거래정보의 보고 및 이용 등에 관한 법률」 내용을 간략히 다루었다.\n여덟째, 「금융혁신지원 특별법」의 주요 내용을 담았다. 그동안 확정되지 않았던 금융혁신지원특별법안에 대한 내용을 담았던 것을 제정된 법률의 내용으로 담았다.'},
  {'title': '핀테크 전쟁 (세계 금융 시장의 거대한 트렌드 | 새로운 돈의 시대가 온다)',
   'link': 'https://search.shopping.naver.com/book/catalog/32466678930',
   'image': 'https://shopping-phinf.pstatic.net/main_3246667/32466678930.20230920071709.jpg',
   'author': '브렛 킹',
   'discount': '13500',
   'publisher': '예문',
   'pubdate': '20150612',
   'isbn': '9788956592503',
   'description': '다가오는 미래, 달라지는 금융의 패러다임을 한 권으로 읽는다!\n\n핀테크란 금융을 뜻하는 파이낸셜(financial)과 기술(techique)의 합성어이다. 즉, IT와 금융의 융합형 산업을 뜻한다. 『핀테크 전쟁』은 이러한 핀테크의 미래에 관한 통찰력을 제공하고, 앞으로 20~30년 동안 금융계의 흐름을 좌우할 기술과 비즈니스 모델을 보여준다. 이에 세계적으로 핀테크 산업을 주도하는 CEO와 전문가 29인 및 금융 평론가 브렛 킹의 대담 내용을 담았다.\n\n세계 최대 금융 관련 팟캐스트인 《Breaking Banks》의 방송 내용을 엮은 이 책은 P2P대출과 커뮤니티뱅킹, 지불결제, 지점이 사라진 인터넷 전문 은행, 비트코인, 디지털 혹은 암호화 화폐, 재무 복지와 저축을 돕는 신개념 도구 등 핀테크의 전 분야에 관한 설명 및 궁금증과 현황, 전망을 소개한다. 이를 통해 요즘 대세라는 핀테크가 무엇인지, 그리고 앞으로 돈의 흐름이 어디로 향할 것인지에 관한 인사이트를 얻을 수 있을 것이다.'},
  {'title': '핀테크 시대 (기술변화와 함께 다가오는 법과 규제 패러다임의 변화)',
   'link': 'https://search.shopping.naver.com/book/catalog/32485543581',
   'image': 'https://shopping-phinf.pstatic.net/main_3248554/32485543581.20220527034931.jpg',
   'author': '고학수^권남훈^노혁준^박광배^박상철',
   'discount': '0',
   'publisher': '박영사',
   'pubdate': '20151205',
   'isbn': '9791130328034',
   'description': '▶ 이 책은 핀테크 시대를 다룬 이론서입니다.'},
  {'title': '핀테크 4.0 (핀테크 혁명과 금융의 미래)',
   'link': 'https://search.shopping.naver.com/book/catalog/32677902620',
   'image': 'https://shopping-phinf.pstatic.net/main_3267790/32677902620.20241227071338.jpg',
   'author': '김종현',
   'discount': '18050',
   'publisher': '한국금융연수원',
   'pubdate': '20200805',
   'isbn': '9788928727292',
   'description': '본서에서는 세계 최초로 핀테크 산업의 발전을 4단계로 구분하여 설명하는 [핀테크 4.0]의 개념을 도입하였다. 이러한 개념적 틀을 토대로 핀테크 산업에 대한 이론적인 설명 및 실무의 이해와 필요한 긴요한 요소들을 적재적소에 배치하였다. 아울러 60여개의 핀테크 기업에 대한 상세 분석을 포함한 풍부한 실례를 다뤘기에 산업계뿐만 아니라 교육현장에서도 활용가능성이 높다.'},
  {'title': '핀테크 4.0 (핀테크 혁명과 금융의 미래)',
   'link': 'https://search.shopping.naver.com/book/catalog/32454456445',
   'image': 'https://shopping-phinf.pstatic.net/main_3245445/32454456445.20220527025312.jpg',
   'author': '김종현',
   'discount': '0',
   'publisher': '한국금융연수원',
   'pubdate': '20200805',
   'isbn': '9788928726127',
   'description': '『핀테크 4.0』은 〈핀테크란 무엇인가?〉, 〈핀테크의 태동과 성장사〉, 〈춘추전국시대인 글로벌 핀테크 시장〉, 〈국내외 대응 현황 및 국내 핀테크 산업의 당면 이슈〉, 〈핀테크 산업의 미래〉 등이 수록되어 있다.'},
  {'title': '핀테크 혁명 (모바일 은행 설립자가 알려주는 핀테크 시대의 돈 관리 기술)',
   'link': 'https://search.shopping.naver.com/book/catalog/32466958984',
   'image': 'https://shopping-phinf.pstatic.net/main_3246695/32466958984.20221229072809.jpg',
   'author': '앤 보덴',
   'discount': '20700',
   'publisher': '유엑스리뷰',
   'pubdate': '20200303',
   'isbn': '9791188314430',
   'description': '다양한 핀테크 서비스와 비즈니스 모델을 완벽히 분석하여 핀테크의 가능성과 모바일 기반의 돈 관리 기술을 이해시켜 주는 책. 영국 최고의 모바일 은행 스탈링뱅크의 창업자이자 금융 전문가인 앤 보덴은 이 책을 통해 우리가 돈을 어떻게 저축하고, 지출하고, 투자하면 좋을지 집중 조명한다. 스마트폰을 이용한 몇 가지의 새로운 행동을 받아들이는 것만으로도 은행 잔고는 한층 풍족해질 수 있다. 이 책은 돈에 관한 전통적인 사고방식을 날려주고, 그동안 우리가 금융기관에 대해 가졌던 고정관념을 깬다. 또 스마트 뱅킹과 오픈뱅킹의 이점 및 핀테크의 새로운 솔루션을 알려줌으로써, 저축과 투자에서부터 연금, 각종 요금 납부, 해외여행 경비에 이르기까지 넓은 범위에서 다양한 핀테크식 해결책을 다룬다. 영국의 핀테크 서비스 사례들을 중점적으로 다루면서 핀테크를 쉽고 흥미롭게 이해할 수 있게 해주며, 동시에 개인을 위한 혁신적 돈 관리 기술들을 소개함으로써 사람들이 더 스마트하게 소비하고 저축하는 방안을 제시한다.'},
  {'title': '핀테크와 법 (제2판)',
   'link': 'https://search.shopping.naver.com/book/catalog/32506678795',
   'image': 'https://shopping-phinf.pstatic.net/main_3250667/32506678795.20220527051739.jpg',
   'author': '강현구',
   'discount': '0',
   'publisher': '씨아이알',
   'pubdate': '20180622',
   'isbn': '9791156106067',
   'description': '핀테크의 영역과 그에 대한 법률문제의 간격을 어떻게 좁힐 수 있을 것인가\n\n『핀테크와 법』을 출간한 후 1년의 시간이 지났다. 시시각각으로 기술 발전이 거듭하고 있음에도 핀테크 관련 법률체계는 답보상태가 유지되고 있는 모습이다. 지급결제나 P2P 대출, 크라우드 펀딩, 가상통화 등의 영역에서 금융과 기술이 더욱더 결합하고 있음을 우리는 목격하고 있다.\n\n제2판은 지난 해 출간한 제1판의 체제를 계속 유지하기로 하였다. 다만, 금번 판은 다음과 같은 사항을 추가 보완하면서 독자들의 호응에 기대키로 한다. 첫째, 1년 사이에 변화된 핀테크의 영역을 업데이트하는 작업을 하였다. 지급결제, 송금, 크라우드 펀딩, P2P 대출, 인터넷 전문은행 및 자산관리 부문에서 최신의 내용을 간략하게 담았다. 둘째, 핀테크 영역에서 가장 괄목한 만한 성장과 변모를 계속하고 있는 P2P 대출, 가상통화에 대한 내용을 보다 더 풍부하게 제공하는 작업을 하였다. 셋째, 금융혁신지원특별법, 일명 ‘핀테크 특별법’에 대한 내용을 간략하게 설명하였다. 아직 입법화되지 않았기 때문에, 금번 발간하는 책자에 삽입하는 것이 합리적인가에 대한 주저함이 없는 것은 아니었지만, 실무에서 유익할 수 있음을 감안하여 간략하게 소개하는 것으로 집필진의 의견을 정리하였다. 넷째, 짜임새나 목차 번호, 오탈자 등을 다시 수정 보완하는 작업을 하였다. 독자들의 혼동을 가져올 수 있는 목차번호나 오탈자 등이 윤독 과정 중 발견되어 이들에 대한 수정작업을 한 것이다.\n\n양서를 출간해야 한다는 마음은 충천해 있지만, 눈 깜짝할 사이에 변화가 지속되고 있는 핀테크의 영역을 따라잡기에는 시간상, 건강상의 여건이 허락되지 않았다. 그럼에도 불구하고 우리 셋은 1년 만에 『핀테크와 법』 제2판을 발간함으로써, 제1판 발간 시 독자들과의 약속을 지키게 되었다. 부족한 부분은 지속적으로 보완할 것을 약속드린다.'},
  {'title': '핀테크 3.0 (핀테크 혁명과 금융의 미래)',
   'link': 'https://search.shopping.naver.com/book/catalog/32505121654',
   'image': 'https://shopping-phinf.pstatic.net/main_3250512/32505121654.20220521130137.jpg',
   'author': '김종현',
   'discount': '0',
   'publisher': '한국금융연수원',
   'pubdate': '20180508',
   'isbn': '9788928724857',
   'description': '▶ 핀테크에 관한 내용을 담은 전문서적입니다.'},
  {'title': '핀테크와 법',
   'link': 'https://search.shopping.naver.com/book/catalog/32466653988',
   'image': 'https://shopping-phinf.pstatic.net/main_3246665/32466653988.20220527024747.jpg',
   'author': '강현구',
   'discount': '0',
   'publisher': '씨아이알',
   'pubdate': '20170420',
   'isbn': '9791156103066',
   'description': '『핀테크와 법』은 핀테크를 이해하기 위한 기초사항을 설명하고 핀테크에 대한 기본적인 사항을 이해한 후 핀테크와 관련된 법률문제를 탐구하였다. 핀테크 영역에서 의미가 있다고 판단되는 지급결제, 해외송금, 크라우드 펀딩, P2P 대출, 인터넷전문은행, 자산관리 및 인슈어테크 등에 관한 사항이 심도 있게 논의된다.'},
  {'title': 'AI 핀테크와 재테크',
   'link': 'https://search.shopping.naver.com/book/catalog/52013378619',
   'image': 'https://shopping-phinf.pstatic.net/main_5201337/52013378619.20241220071432.jpg',
   'author': '임명수',
   'discount': '10800',
   'publisher': '커뮤니케이션북스',
   'pubdate': '20241223',
   'isbn': '9791173073267',
   'description': 'AI와 핀테크 기술이 금융과 재테크 분야를 어떻게 혁신하는지 탐구한다. AI 기반 로보어드바이저와 자동화 시스템은 개인 투자자들에게 맞춤형 자산 관리와 투자 전략을 제공하며, 금융 시장의 접근성을 높인다. 그러나 데이터 프라이버시, 알고리즘 편향성 등 윤리적 문제도 동반된다. AI와 핀테크 기술을 효과적으로 활용한 재테크 전략과 함께 윤리적 기준을 고려한 금융 서비스의 미래를 제시한다.'},
  {'title': '내일의 핀테크 (금융대혁명의 시대, 어떻게 살아남을 것인가?)',
   'link': 'https://search.shopping.naver.com/book/catalog/32436124758',
   'image': 'https://shopping-phinf.pstatic.net/main_3243612/32436124758.20221019145031.jpg',
   'author': '홍장원',
   'discount': '11700',
   'publisher': '매경출판',
   'pubdate': '20160222',
   'isbn': '9791155424070',
   'description': "『내일의 핀테크』는 ‘삼성 직원을 제외하고 가장 먼저 삼성페이를 경험한’ 핀테크 전문기자 홍장원이 일반인들을 위해 쓴 '핀테크' 안내서다. 런던, 파리, 바르샤바, 실리콘밸리를 넘어 밴쿠버와 도쿄까지 6개국을 직접 돌며 풀어낸 살아있는 핀테크 이야기를 들려준다. 저자의 글을 읽으면서 핀테크가 바꿔 갈 미래의 모습을 상상해볼 수 있을 것이다."},
  {'title': '차이나 핀테크 (중국에선 현금이 필요없다)',
   'link': 'https://search.shopping.naver.com/book/catalog/32438307673',
   'image': 'https://shopping-phinf.pstatic.net/main_3243830/32438307673.20221229073433.jpg',
   'author': '구자근',
   'discount': '10800',
   'publisher': '스리체어스',
   'pubdate': '20180220',
   'isbn': '9791186984284',
   'description': "중국은 자타가 공인하는 세계 최고의 핀테크 강국이다. 글로벌 회계법인 언스트앤드영(EY)이 발표한 '2017 핀테크 도입지수'에서 69퍼센트를 기록하며 조사대상 20개국 중 1위를 기록했고, 세계 핀테크 기업 10위권 내에 5개 기업을 올렸다. \n\n\n\n중국의 성공적인 핀테크 사회 진입은 중국 금융을 둘러싼 경제.사회 전반의 요소가 인터넷 플랫폼을 통해 융합하여 최적화된 서비스를 만들었기에 가능했다. 중국 핀테크 금융의 생태계가 기업, 개인, 공동체 등 사회 주체를 모두 연결하고 있다. 중국 핀테크 사례는 제도로서의 기능을 확실히 해낸 중국 금융 당국과 혁신적인 기술과 상호 공존이라는 철학으로 시장의 리더가 된 기업, 변화에 민첩하게 반응해 그대로 흡수된 소비자들이 공통으로 만들어 낸 창신의 결정체다.\n\n\n\n저자는 중국이 신용 사회를 건너뛰어 핀테크 시스템으로 바로 진입할 수 있었던 배경과 과정에 주목한다. 알리바바와 텐센트라는 거대 IT 기업들이 전자상거래와 메신저라는 대규모 플랫폼을 어떻게 활용해 중국인들을 모바일 결제로 끌어들였는지를 각각의 핀테크 상품들로 분석했다. 알리페이와 세서미 크레딧, 위뱅크와 웨이상 등이 바꿔놓은 중국인들의 경제생활을 들여다봤다.\n\n\n\n---\n\n\n\n북저널리즘은 북(BOOK)과 저널리즘(JOURNALISM)의 합성어다. 우리가 지금, 깊이 읽어야 할 주제를 다룬다. 단순한 사실 전달을 넘어 새로운 관점과 해석을 제시하고 사유의 운동을 촉진한다. 현실과 밀착한 지식, 지혜로운 정보를 지향한다. bookjournalism.com"},
  {'title': '핀테크 에센셜',
   'link': 'https://search.shopping.naver.com/book/catalog/32492522723',
   'image': 'https://shopping-phinf.pstatic.net/main_3249252/32492522723.20220527061728.jpg',
   'author': '이근주',
   'discount': '0',
   'publisher': '도서출판 블록체인',
   'pubdate': '20200118',
   'isbn': '9791196796617',
   'description': "글로벌 관점에서 바라본 『핀테크 에센셜』은 국내는 물론 전세계에서 급속하게 확산되고 하루가 다르게 성장하는 핀테크를 다각도로 조망한다. '글로벌 관점에서 바라본 핀테크 에센셜'은 나날이 혁신하는 핀테크 분야에서 새로운 흐름을 꿰뚫는 통찰을 제공함으로써 다가오는 비즈니스 기회를 포착할 수 있는 길을 제시한다. 금융서비스 분야에서 새로운 혁신을 꾀하는 스타트업은 물론이고 핀테크를 포용하려는 금융권에 종사하는 이들 모두를 위한 도서이다."},
  {'title': '핀테크가 강한 나라 (석학 9인의 금융 플랫폼 미래 통찰)',
   'link': 'https://search.shopping.naver.com/book/catalog/46825713618',
   'image': 'https://shopping-phinf.pstatic.net/main_4682571/46825713618.20240404092906.jpg',
   'author': '강형구^김솔^김우진^류혁선^안수현',
   'discount': '35100',
   'publisher': '한울아카데미',
   'pubdate': '20240408',
   'isbn': '9788946075139',
   'description': '빅테크 플랫폼 시대에 금융이 나아갈 길\n\n최근 10년 금융 서비스는 몰라보게 달라졌다. 스마트폰으로 언제 어디서든 여러 은행의 금리를 비교하며 지점에 직접 가지 않고도 통장을 만들고 대출이나 환전 같은 업무를 볼 수 있다. \n스마트폰 보급과 다양한 핀테크 서비스들의 등장으로 금융의 경계가 흐려지고 있으며 금융과 정보통신기술의 결합으로 등장한 새로운 핀테크 산업에 기대와 우려가 겹쳐 있다.\n금융은 항상 당시 최고의 기술을 활용하여 발전해 왔다. 새로운 기술 및 사업 모델의 창의적 활용을 권장하고 금융 혁신의 제도적 기반을 제공하면서도 소비자 보호, 금융회사와 플랫폼 간 공정한 협업과 경쟁, 금융시스템의 안정 등을 뒷받침할 수 있는 제도를 수립하는 것이 필요하다. \n이러한 문제의식을 가지고 여러 학문 분야의 석학들이 머리를 맞대고 금융 플랫폼이 제기하는 다양한 이슈를 종합적이고 균형 있게 조망했다. 이 책은 핀테크를 통해 금융소비자 보호, 금융 포용성 확대, 지속가능한 성장의 파트너이자, 금융 혁신을 이루는 등 한국 금융이 나아가야 할 길을 제시한다. 또한 이러한 미래 비전을 위해 정부가 의지를 가지고 갖추어야 할 제도와 규제는 어떠해야 할지에 대한 고민도 담았다.'},
  {'title': '핀테크 인사이트 (돈의 미래를 주도할 핀테크 기술 트렌드와 미래 예측)',
   'link': 'https://search.shopping.naver.com/book/catalog/32493234759',
   'image': 'https://shopping-phinf.pstatic.net/main_3249323/32493234759.20221230073118.jpg',
   'author': '메가트렌드 랩',
   'discount': '15300',
   'publisher': '율곡출판사',
   'pubdate': '20180208',
   'isbn': '9791187897262',
   'description': '바야흐로 핀테크 전성시대다. 모든 언론의 경제면에는 핀테크로 대변되는 가상화폐, 인터넷 은행, 간편결제, 로보어드바이저, P2P대출 등의 관련 기사가 쉴새없이 쏟아지고 있다. 면면을 보면 금융과 정보통신기술의 융합이라는 공통적인 키워드를 도출해낼 수 있다. 이제는 정보통신기술을 이해하지 못하면 금융을 이야기할 수 없게 되고 있다. 이 때문에 핀테크 기업이 IT 인력을 대거 흡수하고 있다. 단편적인 예로 골드만삭스가 금융이 아닌 IT 회사라는 슬로건을 걸고 있고, 실제로 약 3만 3천 명의 정규직원 중 약 9천여 명이 IT 인력으로 구성되어 있다. \n\n핀테크 산업의 성장으로 금융혁신이 이루어지고 있다. 기존과 다른 양상으로 사업기회가 생겨나고 있고, 크라우드펀딩이나 P2P, ICO 등의 새로운 펀딩방식이 탄생하고 있다. 핀테크는 시간이 지날수록 발전하면서 소비자들의 금융 생활을 더욱 편하게 만들 것이다. 앞으로 어떤 혁신적인 핀테크 서비스로 우리 생활을 편하게 할 수 있을지 기대가 된다. 이러한 시점에 핀테크 트렌드를 미리 파악하고 체계적인 지식을 쌓아두는 것이 불확실한 미래를 준비하는 데 큰 도움이 될 것이다. 특히 금융 및 IT 분야의 전문가들이 공동저자로 참여하여 현장의 모습을 생생하게 전하고 있다는 점이 매력적이다. 많은 독자들이 핀테크를 이해하는 데 있어 도움이 되기를 간절히 바란다(윤정석, 삼성전자 책임 연구원, 추천의 글).'},
  {'title': '핀테크 보안경영 (보안사령부를 구축하라)',
   'link': 'https://search.shopping.naver.com/book/catalog/32492053731',
   'image': 'https://shopping-phinf.pstatic.net/main_3249205/32492053731.20221019145226.jpg',
   'author': '김려성',
   'discount': '30600',
   'publisher': '진한엠앤비',
   'pubdate': '20160420',
   'isbn': '9791170094371',
   'description': '핀테크 보안은 금융거래의 신뢰성을 유지하면서 금융과 IT 융합에 의해 편의성과 다양성을 지원할 수 있어야 한다. 사용자측면의 사전 보안에서 서버측면의 사후 보안으로 보안 프레임워크가 변화되고 있다. 그래서 다양한 인증기술의 수용, 기술의 중립성 구현, 사용자의 보안의식 강화 등의 구체적 목적을 가지고 추진되어야 한다. 핀테크 서비스를 제공하는 기업은 보안대책을 수립함에 있어 핀테크 관련 보 안정책에 대한 명확한 이해를 바탕으로 종합적인 핀테크 서비스 안전성 확보방안을 수립해야 하겠다.'},
  {'title': '핀테크 규제와 실무 (지급결제와 본인인증편)',
   'link': 'https://search.shopping.naver.com/book/catalog/32441626104',
   'image': 'https://shopping-phinf.pstatic.net/main_3244162/32441626104.20230313183513.jpg',
   'author': '예자선',
   'discount': '31500',
   'publisher': '삼일인포마인',
   'pubdate': '20210824',
   'isbn': '9791167840059',
   'description': '온·오프라인 결제와 송금, 본인확인서비스와 전자서명(인증서)에 대한 총정리\n\n[특장점]\nㆍ한 권으로 끝내는 법규, 비즈니스 모델, 현안의 이해\nㆍ다수 이용자가 일상적으로 이용하는 결제와 송금서비스는 금융플랫폼으로 도약하기 위한 초석으로, 기존사업자들과 신규사업자들이 치열한 경쟁을 하고 있는 영역이다. 실물경제와 밀접한 관련이 있고 해외서비스와 바로 연계될 가능성이 있기 때문에 규제와 활성화 양쪽 측면에서 제도적 개입과 논의도 많은 분야이다. 전자금융거래와 밀접한 관련이 있는 본인확인 영역 역시, 공인인증서 폐지 논의와 함께 통신사가 독점하던 본인확인서비스를 대체할 수 있는 사설인증서 등장과 전자문서 활성화 추세로 새로운 국면에 접어들고 있다.\nㆍ이 책은 여신전문금융업법과 전자금융거래법, 전자서명법, 전자상거래법의 현행 법규과 개정안, 가이드라인, 유권해석 등을 망라하여, 각 비즈니스 모델의 참가 사업자들이 누구인지, 어떤 라이선스가 필요하고, 어떤 제휴관계를 맺고 있는지, 어떤 규제를 받고 있는지를 한눈에 정리함으로써, 실무 프로세스를 만들고 제도적 현안을 이해하는데 즉각적인 도움을 받을 수 있다.'},
  {'title': '진짜 핀테크 이야기 (한 발 앞서 정복하는)',
   'link': 'https://search.shopping.naver.com/book/catalog/32492630762',
   'image': 'https://shopping-phinf.pstatic.net/main_3249263/32492630762.20221228073118.jpg',
   'author': '목승환',
   'discount': '13500',
   'publisher': '한즈미디어(한스미디어)',
   'pubdate': '20150924',
   'isbn': '9788959758586',
   'description': '금융과 IT를 두루 섭렵한 핀테크 전문가가 이야기하는 핀테크의 모든 것. 핀테크의 진정한 개념과 확산 범위, 세계 핀테크 기업들의 현황과 국내 상황, 발전을 위한 조언까지 핀테크에 관심 있는 이들이들이라면 반드시 알아야할 정보를 담았다. \n\n\n\n이 책은 총 9장으로 구성되어 있다. 1장에서는 ‘핀테크란 무엇인가’라는 주제로 핀테크의 정의와 기본 개념을 살펴보기로 한다. 2장 ‘누구도 알려주지 않는 뒷이야기들’에서는 핀테크를 본격적으로 알아보기 전에 그 등장 배경을 논의해보도록 한다. 3장에서는 핀테크의 분류와 예전 국내외 사례에 대해서 살펴볼 것이다. 4장에서는 핀테크의 사업적 측면과 사회적 측면의 양면성을 고찰해볼 것이다. 5장에서는 우리가 알아야 하는 국내외 핀테크 서비스를 소개하고자 한다.\n\n\n\n 6장에서는 ‘우리 삶 속의 핀테크’라는 주제로 핀테크의 중요성에 대해 알아보고 7장에서는 미래 핀테크에 대한 전망과 그로써 바뀔 우리의 삶에 대해 언급한다. 그리고 8장에서는 지금까지 살펴봤던 핀테크 관련논의 중에서도 주목할 만한 최근의 동향을 이야기한다. 마지막 9장에서는 ‘핀테크가 가야 할 길’이라는 주제로 지금까지 다룬 내용을 정리하며 마무리한다.'},
  {'title': '핀테크 세상을 열다 (30편의 카툰으로 만나는 핀테크 이야기)',
   'link': 'https://search.shopping.naver.com/book/catalog/32506888625',
   'image': 'https://shopping-phinf.pstatic.net/main_3250688/32506888625.20221231084138.jpg',
   'author': '김동우^김진영',
   'discount': '11520',
   'publisher': '한빛미디어',
   'pubdate': '20160105',
   'isbn': '9788968482458',
   'description': '『핀테크 세상을 열다』 는 전문 컨설턴트들이 일반 대중의 눈높이에 맞춰 핀테크를 쉽고 재미있게 이해할 수 있도록 30편의 카툰으로 구성한 입문서다. ‘핀테크란 무엇인가?’에서 시작하여 핀테크의 개념을 설명해 줄 뿐만 아니라 핀테크가 실제로 일상 생활에서 어떻게 활용되고 있는지 해외, 국내 사례를 통해 살펴본다.'},
  {'title': '왜 지금 핀테크인가 (송금, 결제에서 인터넷 전문은행까지 손끝에서 이뤄지는 금융 신세계)',
   'link': 'https://search.shopping.naver.com/book/catalog/32504578763',
   'image': 'https://shopping-phinf.pstatic.net/main_3250457/32504578763.20220527045610.jpg',
   'author': '현경민',
   'discount': '0',
   'publisher': '미래의창',
   'pubdate': '20150810',
   'isbn': '9788959893454',
   'description': '미래 금융을 디자인하는 핀테크 혁명의 모든 것!\n\n『왜 지금 핀테크인가』는 금융과 ICT 분야에서 오랫동안 일해온 저자들이 생생한 현장 경험과 지식을 바탕으로 우리의 일상 깊숙이 파고들고 있는 핀테크 산업의 이모저모를 파헤친다. 특히 핀테크가 금융산업 전반을 어떻게 바꿔나가고 있는지 알기 쉽게 설명하고, 분야별 한국 핀테크 산업의 현황과 현주소를 제대로 짚어낸다.\n\n최근 핀테크 산업의 가장 뜨거운 이슈인 인터넷 전문은행에 대해서도 다룬다. 인터넷 전문은행이란 은행 지점을 통한 대면 거래를 통하지 않고 인터넷을 주 영업 채널로 활용하는 은행을 의미한다. 이에 국내 인터넷 전문은행의 활성화와 발전을 위해서는 금산분리의 선별적 완화, 겸업주의 허용, 자기자본 기준의 완화 등 조심스런 규제 완화가 필요하다고 말한다.'},
  {'title': '핀테크와 블록체인의 미래 (핀테크는 어떻게 디지털 혁명을 가져왔나)',
   'link': 'https://search.shopping.naver.com/book/catalog/49371595622',
   'image': 'https://shopping-phinf.pstatic.net/main_4937159/49371595622.20240725092126.jpg',
   'author': '김선미^길재식',
   'discount': '31500',
   'publisher': '북오션',
   'pubdate': '20240814',
   'isbn': '9788967998370',
   'description': '#금융의 미래를 선도할 혁신기술\n#핀테크와 블록체인, 두 기술의 만남이 열어갈 새로운 시대\n#전문가의 통찰로 읽는 금융 혁명의 로드맵\n#기술과 정책, 현재와 미래를 아우르는 가이드북\n\n\n핀테크와 블록체인의 미래를 통찰하다\n\n블록체인 전문 공학 박사와 IT 전문 베테랑 기자가 함께 쓴 《핀테크와 블록체인의 미래》. 이 책은 핀테크와 블록체인 기술의 원리부터 산업 동향, 정부 정책, 시장 전망까지 폭넓게 다루고 있다. 저자들의 풍부한 경험과 전문성이 결합되어 독자들에게 깊이 있는 통찰을 제공한다.\n이 책의 가장 큰 특징은 기술과 서비스의 논리적 연결에 중점을 두어 균형 잡힌 시각을 제공한다는 점이다. 핀테크 기술의 발전 과정과 현재 상황을 상세히 설명하며, 동시에 블록체인 기술의 잠재력과 한계를 객관적으로 분석한다. 특히 두 기술의 융합 가능성을 심도 있게 탐구하여, 미래 금융 생태계의 모습을 그려내고 있다.\n저자들은 단순히 현재 상황을 설명하는 데 그치지 않고, 핀테크와 블록체인의 미래에 대한 전망도 제시한다. 중앙은행 디지털 화폐(CBDC), 증권 토큰 발행(STO) 등 차세대 핀테크 기술과 서비스에 대한 분석을 통해, 독자들이 미래 금융 산업의 모습을 그려볼 수 있도록 돕는다.\n더불어 정부 정책과 규제에 대한 분석도 제공한다. 핀테크와 블록체인 기술에 대한 각국 정부의 입장과 규제 동향을 소개하며, 이러한 정책이 산업에 미치는 영향을 심층적으로 고찰한다. 특히 최근 주목받고 있는 토큰 증권 제도와 같은 새로운 규제 체계에 대한 설명은 독자들에게 유용한 정보가 될 것이다.'},
  {'title': 'AI 핀테크와 재테크 큰글자책',
   'link': 'https://search.shopping.naver.com/book/catalog/52013377620',
   'image': 'https://shopping-phinf.pstatic.net/main_5201337/52013377620.20241220071412.jpg',
   'author': '임명수',
   'discount': '22500',
   'publisher': '커뮤니케이션북스',
   'pubdate': '20241223',
   'isbn': '9791173073274',
   'description': 'AI와 핀테크 기술이 금융과 재테크 분야를 어떻게 혁신하는지 탐구한다. AI 기반 로보어드바이저와 자동화 시스템은 개인 투자자들에게 맞춤형 자산 관리와 투자 전략을 제공하며, 금융 시장의 접근성을 높인다. 그러나 데이터 프라이버시, 알고리즘 편향성 등 윤리적 문제도 동반된다. AI와 핀테크 기술을 효과적으로 활용한 재테크 전략과 함께 윤리적 기준을 고려한 금융 서비스의 미래를 제시한다.'},
  {'title': '핀테크 기술용어 사전',
   'link': 'https://search.shopping.naver.com/book/catalog/32466972779',
   'image': 'https://shopping-phinf.pstatic.net/main_3246697/32466972779.20221019104722.jpg',
   'author': '비피기술거래^비피제이기술거래',
   'discount': '22500',
   'publisher': '비티타임즈',
   'pubdate': '20210719',
   'isbn': '9791163452942',
   'description': '인문학을 전공한 분이나 초보자들이 관련 기술 일을 접할 때 용어 때문에 어려움이 많아 관련 기술에 대한 용어를 정리해보았다.\n 관련된 시험을 준비하는 대학생, 비전공자들, 전공자들, 직장인들에게 도움이 되길 바란다.\n 이 책은 핀테크와 관련된 용어를 정리해 보았다.'},
  {'title': '금융플랫폼과 금융회사의 비즈니스 (핀테크 규제와 실무 2)',
   'link': 'https://search.shopping.naver.com/book/catalog/32443148262',
   'image': 'https://shopping-phinf.pstatic.net/main_3244314/32443148262.20240816071209.jpg',

In [16]:
response2

b'{\n\t"lastBuildDate":"Tue, 01 Apr 2025 10:33:06 +0900",\n\t"total":106,\n\t"start":1,\n\t"display":100,\n\t"items":[\n\t\t{\n\t\t\t"title":"\xed\x95\x80\xed\x85\x8c\xed\x81\xac",\n\t\t\t"link":"https:\\/\\/search.shopping.naver.com\\/book\\/catalog\\/32438306822",\n\t\t\t"image":"https:\\/\\/shopping-phinf.pstatic.net\\/main_3243830\\/32438306822.20230920073135.jpg",\n\t\t\t"author":"\xed\x95\x9c\xec\x84\x9d\xec\xa3\xbc",\n\t\t\t"discount":"11400",\n\t\t\t"publisher":"\xec\xbb\xa4\xeb\xae\xa4\xeb\x8b\x88\xec\xbc\x80\xec\x9d\xb4\xec\x85\x98\xeb\xb6\x81\xec\x8a\xa4",\n\t\t\t"pubdate":"20151101",\n\t\t\t"isbn":"9791130441436",\n\t\t\t"description":"\xeb\x94\x94\xec\xa7\x80\xed\x84\xb8 \xea\xb8\xb0\xec\x88\xa0\xec\x9d\x98 \xeb\xb0\x9c\xeb\x8b\xac\xec\x9d\x80 \xea\xb8\x88\xec\x9c\xb5\xec\x9d\x98 \xeb\xaa\xa8\xeb\x93\xa0 \xea\xb2\x83\xec\x9d\x84 \xeb\xb0\x94\xea\xbe\xb8\xea\xb3\xa0 \xec\x9e\x88\xeb\x8b\xa4. \xea\xb8\xb0\xec\x88\xa0 \xea\xb8\xb0\xeb\xb0\x98\xec\x9d\x98 \xec\x8a\xa4\xed\x83\x80\xed\x8a\xb8\xec\x97\x85\xeb\x93\xa4\xea\xb3\xbc \xeb\xb9\x84\xea\xb8\x88\xec\x9c\xb5\xea\xb6\x8c \xea\xb8\xb0\xec\x97\x85\xeb\x93\xa4\xec\x9d\xb4 \xea\xb8\x88\xec\x9c\xb5 \xec\x8b\x9c\xec\x9e\xa5\xec\x97\x90 \xec\xa7\x84\xec\x9e\x85\xed\x95\x98\xeb\xa9\xb0 \xec\x9d\x80\xed\x96\x89\xec\x9d\x84 \xed\x95\xb4\xec\xb2\xb4\xed\x95\x98\xea\xb3\xa0 \xeb\x8c\x80\xec\xb2\xb4\xed\x95\xb4 \xea\xb0\x80\xeb\x8a\x94 \xec\x8b\x9c\xeb\x8c\x80\xea\xb0\x80 \xec\x98\xa4\xea\xb3\xa0 \xec\x9e\x88\xeb\x8b\xa4. \xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x9d\x98 \xed\x95\xb5\xec\x8b\xac\xec\x9d\x80 \xea\xb8\xb0\xec\x88\xa0\xec\x9d\x84 \xed\x86\xb5\xed\x95\xb4 \xea\xb8\xb0\xec\xa1\xb4\xec\x9d\x98 \xea\xb8\x88\xec\x9c\xb5 \xea\xb8\xb0\xea\xb4\x80\xec\x9d\xb4 \xec\xa0\x9c\xea\xb3\xb5\xed\x95\x98\xec\xa7\x80 \xeb\xaa\xbb\xed\x96\x88\xeb\x8d\x98 \xeb\xb6\x80\xeb\xb6\x84\xec\x9d\x84 \xec\xb1\x84\xec\x9b\x8c \xec\xa3\xbc\xea\xb3\xa0, \xed\x8e\xb8\xec\x9d\x98\xec\x84\xb1 \xec\xa6\x9d\xeb\x8c\x80, \xeb\xb9\x84\xec\x9a\xa9 \xec\xa0\x88\xea\xb0\x90, \xeb\xa6\xac\xec\x8a\xa4\xed\x81\xac \xeb\xb6\x84\xec\x82\xb0, \xea\xb8\xb0\xeb\x8c\x80 \xec\x88\x98\xec\x9d\xb5 \xec\xa6\x9d\xea\xb0\x80 \xeb\x93\xb1 \xea\xb3\xa0\xea\xb0\x9d\xec\x97\x90\xea\xb2\x8c \xec\x83\x88\xeb\xa1\x9c\xec\x9a\xb4 \xea\xb0\x80\xec\xb9\x98\xeb\xa5\xbc \xec\xa3\xbc\xeb\x8a\x94 \xeb\x8d\xb0 \xec\x9e\x88\xeb\x8b\xa4. \xed\x8a\xb9\xed\x9e\x88 \xea\xb3\xa0\xea\xb0\x9d\xeb\x93\xa4\xec\x9d\xb4 \xec\x8c\x93\xec\x9d\x80 \xeb\x8d\xb0\xec\x9d\xb4\xed\x84\xb0\xeb\xa5\xbc \xeb\xb6\x84\xec\x84\x9d\xed\x95\xb4 \xed\x8b\x88\xec\x83\x88\xeb\xa5\xbc \xec\xb0\xbe\xec\x95\x84\xeb\x82\xb4\xea\xb3\xa0 \xec\x83\x88\xeb\xa1\x9c\xec\x9a\xb4 \xec\x8b\x9c\xec\x9e\xa5\xec\x9c\xbc\xeb\xa1\x9c \xeb\xa7\x8c\xeb\x93\x9c\xeb\x8a\x94 \xea\xb2\x83\xec\x9d\xb4 \xec\xa4\x91\xec\x9a\x94\xed\x95\x98\xeb\x8b\xa4. \xec\x9d\xb4 \xec\xb1\x85\xec\x9d\x80 \xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x9d\x98 \xec\x9d\x98\xeb\xaf\xb8\xec\x99\x80 \xec\xa7\x80\xea\xb8\x89 \xea\xb2\xb0\xec\xa0\x9c, \xeb\x8c\x80\xec\xb6\x9c, \xec\x9e\x90\xec\x82\xb0\xea\xb4\x80\xeb\xa6\xac, \xea\xb0\x80\xec\x83\x81 \xed\x99\x94\xed\x8f\x90 \xeb\x93\xb1 \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xeb\xb6\x84\xec\x95\xbc\xeb\xb3\x84 \xec\x84\xb1\xea\xb3\xb5 \xec\x82\xac\xeb\xa1\x80\xec\x99\x80 \xec\x8b\x9c\xec\x82\xac\xec\xa0\x90, \xec\x98\xa4\xed\x94\x84\xeb\x9d\xbc\xec\x9d\xb8 \xea\xb8\xb0\xec\x97\x85\xec\x9d\x98 \xeb\x8c\x80\xec\x9d\x91, \xea\xb7\xb8\xeb\xa6\xac\xea\xb3\xa0 \xea\xb0\x81\xea\xb5\xad\xec\x9d\x98 \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xec\x82\xb0\xec\x97\x85 \xec\x9c\xa1\xec\x84\xb1 \xec\xa0\x95\xec\xb1\x85\xec\x97\x90 \xeb\x8c\x80\xed\x95\xb4 \xec\x82\xb4\xed\x8e\xb4\xeb\xb3\xb8\xeb\x8b\xa4."\n\t\t},\n\t\t{\n\t\t\t"title":"\xed\x95\x80\xed\x85\x8c\xed\x81\xac (IT\xec\x99\x80 \xea\xb8\x88\xec\x9c\xb5\xec\x9d\xb4 \xeb\xa7\x8c\xeb\x82\x98\xeb\x8a\x94 \xec\x83\x88\xeb\xa1\x9c\xec\x9a\xb4 \xec\x84\xb8\xec\x83\x81)",\n\t\t\t"link":"https:\\/\\/search.shopping.naver.com\\/book\\/catalog\\/32506472036",\n\t\t\t"image":"https:\\/\\/shopping-phinf.pstatic.net\\/main_3250647\\/32506472036.20220527060350.jpg",\n\t\t\t"author":"\xea\xb0\x95\xec\xb0\xbd\xed\x98\xb8",\n\t\t\t"discount":"0",\n\t\t\t"publisher":"\xed\x95\x9c\xeb\xb9\x9b\xeb\xaf\xb8\xeb\x94\x94\xec\x96\xb4",\n\t\t\t"pubdate":"20150605",\n\t\t\t"isbn":"9788968482007",\n\t\t\t"description":"\xea\xb8\x88\xec\x9c\xb5\xea\xb3\xbc \xea\xb8\xb0\xec\x88\xa0\xeb\xa1\x9c \xed\x98\x81\xec\x8b\xa0\xed\x95\x98\xeb\x8a\x94 \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xec\x8b\x9c\xec\x9e\xa5\xec\x9d\x84 \xec\x84\xa0\xec\xa0\x90\xed\x95\x98\xeb\x9d\xbc!\\n\\n\xec\x83\x81\xec\x8b\x9c \xec\x97\xb0\xea\xb2\xb0\xeb\x90\x9c \xeb\x94\x94\xec\xa7\x80\xed\x84\xb8 \xec\x84\xb8\xec\x83\x81\xec\x97\x90\xec\x84\x9c \xed\x98\x81\xec\x8b\xa0\xec\xa0\x81\xec\x9d\xb8 \xea\xb8\x88\xec\x9c\xb5 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4\xeb\xa5\xbc \xec\xa0\x9c\xea\xb3\xb5\xed\x95\x98\xea\xb8\xb0 \xec\x9c\x84\xed\x95\x9c \xec\xb5\x9c\xea\xb3\xa0\xec\x9d\x98 \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xec\x95\x88\xeb\x82\xb4\xec\x84\x9c!\\n\\n\xed\x95\x80\xed\x85\x8c\xed\x81\xac\xe2\x80\x99\xeb\x9e\x80 \xea\xb8\x88\xec\x9c\xb5\xec\x9d\x84 \xeb\x9c\xbb\xed\x95\x98\xeb\x8a\x94 \xed\x8c\x8c\xec\x9d\xb4\xeb\x82\xb8\xec\x85\x9c(Financial)\xea\xb3\xbc \xea\xb8\xb0\xec\x88\xa0(Technology)\xec\x9d\x98 \xed\x95\xa9\xec\x84\xb1\xec\x96\xb4\xeb\xa1\x9c \xec\x8a\xa4\xeb\xa7\x88\xed\x8a\xb8 \xea\xb8\xb0\xea\xb8\xb0\xeb\xa5\xbc \xec\x9d\xb4\xec\x9a\xa9\xed\x95\x9c \xec\xa7\x80\xea\xb8\x89 \xea\xb2\xb0\xec\xa0\x9c \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4\xeb\xbf\x90\xeb\xa7\x8c \xec\x95\x84\xeb\x8b\x88\xeb\x9d\xbc \xec\x98\x88\xea\xb8\x88\xea\xb3\xbc \xeb\x8c\x80\xec\xb6\x9c \xeb\xb0\x8f \xec\x9e\x90\xec\x82\xb0 \xea\xb4\x80\xeb\xa6\xac \xeb\x93\xb1\xec\x9d\x98 \xea\xb0\x81\xec\xa2\x85 \xea\xb8\x88\xec\x9c\xb5 \xec\x84\x9c\xeb\xb9\x84\xec\x8a\xa4\xeb\xa5\xbc IT \xea\xb8\xb0\xec\x88\xa0\xec\x9d\x84 \xed\x86\xb5\xed\x95\xb4 \xec\xb2\x98\xeb\xa6\xac\xed\x95\x98\xeb\x8a\x94 \xea\xb8\x88\xec\x9c\xb5\xea\xb3\xbc IT\xea\xb0\x80 \xec\x9c\xb5\xed\x95\xa9\xeb\x90\x9c \xec\x82\xb0\xec\x97\x85\xec\x9d\x84 \xeb\x9c\xbb\xed\x95\x9c\xeb\x8b\xa4. \xec\x9d\xb4 \xec\xb1\x85\xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xed\x95\x80\xed\x85\x8c\xed\x81\xac\xeb\xa1\x9c \xec\x8b\x9c\xec\x9e\x91\xeb\x90\x9c \xeb\x94\x94\xec\xa7\x80\xed\x84\xb8 \xea\xb8\x88\xec\x9c\xb5\xec\x9d\x98 \xed\x98\x81\xec\x8b\xa0\xec\x9d\x84 \xec\x9c\x84\xed\x95\xb4 \xeb\xb3\x80\xed\x99\x94\xed\x95\x98\xeb\x8a\x94 \xec\x8b\x9c\xec\x9e\xa5 \xec\x83\x81\xed\x99\xa9\xea\xb3\xbc \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xed\x95\xb4\xec\x99\xb8 \xec\x84\xa0\xeb\x8f\x84 \xea\xb8\xb0\xec\x97\x85\xec\x9d\x98 \xec\x82\xac\xeb\xa1\x80\xeb\xa5\xbc \xec\x95\x8c\xec\x95\x84\xeb\xb3\xb4\xea\xb3\xa0, \xea\xb8\xb0\xec\x97\x85\xec\x9d\xb4 \xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xeb\xb3\x80\xed\x99\x94\xed\x95\xb4\xec\x95\xbc \xed\x95\xa0 \xea\xb2\x83\xec\x9d\xb8\xec\xa7\x80 \xea\xb5\xac\xec\xb2\xb4\xec\xa0\x81\xec\x9c\xbc\xeb\xa1\x9c \xec\x82\xb4\xed\x8e\xb4\xeb\xb3\xb8\xeb\x8b\xa4. \xec\x95\xa0\xed\x94\x8c, \xea\xb5\xac\xea\xb8\x80, \xed\x8e\x98\xec\x9d\xb4\xed\x8c\x94, \xec\x95\x8c\xeb\xa6\xac\xeb\xb0\x94\xeb\xb0\x94 \xeb\x93\xb1 \xec\xb5\x9c\xec\x8b\xa0 \xea\xb8\xb0\xec\x88\xa0\xec\x9d\x84 \xeb\xac\xb4\xea\xb8\xb0\xeb\xa1\x9c \xec\x83\x88\xeb\xa1\xad\xea\xb2\x8c \xeb\x93\xb1\xec\x9e\xa5\xed\x95\x9c \xea\xb8\x88\xec\x9c\xb5 \xed\x94\x8c\xeb\xa0\x88\xec\x9d\xb4\xec\x96\xb4\xeb\x93\xa4\xea\xb3\xbc \xeb\x8c\x80\xec\xa0\x81\xed\x95\x98\xea\xb8\xb0 \xec\x9c\x84\xed\x95\xb4 \xeb\xb0\x98\xeb\x93\x9c\xec\x8b\x9c \xec\x95\x8c\xea\xb3\xa0 \xec\x9e\x88\xec\x96\xb4\xec\x95\xbc \xed\x95\xa0 \xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x9d\x98 \xeb\xaa\xa8\xeb\x93\xa0 \xea\xb2\x83\xec\x9d\x84 \xeb\x8b\xa4\xeb\xa3\xa8\xeb\xa9\xb4\xec\x84\x9c \xea\xb8\xb0\xec\x88\xa0\xea\xb3\xbc \xea\xb8\x88\xec\x9c\xb5\xec\x9d\x84 \xec\x86\x8c\xeb\xb9\x84\xed\x95\x98\xeb\x8a\x94 \xea\xb8\x88\xec\x9c\xb5 \xec\x86\x8c\xeb\xb9\x84\xec\x9e\x90\xec\x97\x90 \xeb\x8c\x80\xed\x95\x9c \xec\x9d\xb4\xed\x95\xb4 \xeb\xb0\x8f \xec\x86\x8c\xeb\xb9\x84\xec\x9e\x90 \xea\xb2\xbd\xed\x97\x98 \xed\x96\xa5\xec\x83\x81\xec\x9d\x84 \xed\x86\xb5\xed\x95\xb4 \xea\xb8\xb0\xec\x97\x85\xec\x9d\xb4 \xeb\x82\x98\xec\x95\x84\xea\xb0\x80\xec\x95\xbc \xed\x95\xa0 \xeb\xb0\xa9\xed\x96\xa5\xec\x9d\x84 \xec\xa0\x9c\xec\x8b\x9c\xed\x95\x9c\xeb\x8b\xa4. \xec\x9d\xb4 \xec\xb1\x85\xec\x9d\x80 \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xec\xa0\x84\xeb\xac\xb8\xea\xb0\x80\xea\xb0\x80 \xeb\x93\xa4\xeb\xa0\xa4\xec\xa3\xbc\xeb\x8a\x94 \xea\xb0\x80\xec\x9e\xa5 \xed\x99\x95\xec\x8b\xa4\xed\x95\x9c \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xed\x98\x81\xec\x8b\xa0 \xeb\x85\xb8\xed\x95\x98\xec\x9a\xb0\xeb\xa1\x9c, \xeb\x94\x94\xec\xa7\x80\xed\x84\xb8 \xea\xb8\x88\xec\x9c\xb5 \xed\x98\x81\xec\x8b\xa0\xec\x9d\x84 \xec\x9d\xb4\xed\x95\xb4\xed\x95\x98\xea\xb3\xa0 \xec\xa4\x80\xeb\xb9\x84\xed\x95\x98\xeb\xa0\xa4\xeb\x8a\x94 \xea\xb8\x88\xec\x9c\xb5 \xea\xb8\xb0\xea\xb4\x80\xec\x9d\x98 \xec\x9e\x84\xec\x9b\x90 \xeb\xb0\x8f \xed\x98\x84\xec\x97\x85 \xeb\x8b\xb4\xeb\x8b\xb9\xec\x9e\x90\xeb\xbf\x90\xeb\xa7\x8c \xec\x95\x84\xeb\x8b\x88\xeb\x9d\xbc \xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x99\x80 \xea\xb4\x80\xeb\xa0\xa8\xeb\x90\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xed\x95\xb4\xec\x99\xb8 \xec\x82\xac\xeb\xa1\x80 \xeb\xb0\x8f \xed\x99\x9c\xec\x9a\xa9 \xeb\xb0\xa9\xeb\xb2\x95\xec\x9d\x84 \xea\xb3\xa0\xeb\xaf\xbc\xed\x95\x98\xea\xb3\xa0 \xec\x9e\x88\xeb\x8a\x94 \xea\xb8\x88\xec\x9c\xb5 IT \xec\xa2\x85\xec\x82\xac\xec\x9e\x90, \xeb\x94\x94\xec\xa7\x80\xed\x84\xb8 \xeb\xb1\x85\xed\x82\xb9\xec\x9d\x98 \xeb\xaf\xb8\xeb\x9e\x98\xec\x97\x90 \xeb\x8c\x80\xed\x95\xb4 \xec\x9d\xb8\xec\x82\xac\xec\x9d\xb4\xed\x8a\xb8\xeb\xa5\xbc \xec\x96\xbb\xea\xb3\xa0\xec\x9e\x90 \xed\x95\x98\xeb\x8a\x94 \xec\x82\xac\xeb\x9e\x8c\xeb\x93\xa4\xec\x97\x90\xea\xb2\x8c\xeb\x8f\x84 \xec\x8b\xa4\xec\xa7\x88\xec\xa0\x81\xec\x9d\xb8 \xeb\x8f\x84\xec\x9b\x80\xec\x9d\x84 \xec\xa4\x84 \xec\x88\x98 \xec\x9e\x88\xeb\x8a\x94 \xec\xb1\x85\xec\x9d\xb4\xeb\x8b\xa4."\n\t\t},\n\t\t{\n\t\t\t"title":"\xed\x95\x80\xed\x85\x8c\xed\x81\xac 4.0 (\xed\x95\x80\xed\x85\x8c\xed\x81\xac \xed\x98\x81\xeb\xaa\x85\xea\xb3\xbc \xea\xb8\x88\xec\x9c\xb5\xec\x9d\x98 \xeb\xaf\xb8\xeb\x9e\x98)",\n\t\t\t"link":"https:\\/\\/search.shopping.naver.com\\/book\\/catalog\\/52000746624",\n\t\t\t"image":"https:\\/\\/shopping-phinf.pstatic.net\\/main_5200074\\/52000746624.20241219071112.jpg",\n\t\t\t"author":"\xea\xb9\x80\xec\xa2\x85\xed\x98\x84",\n\t\t\t"discount":"17100",\n\t\t\t"publisher":"\xed\x95\x9c\xea\xb5\xad\xea\xb8\x88\xec\x9c\xb5\xec\x97\xb0\xec\x88\x98\xec\x9b\x90",\n\t\t\t"pubdate":"20241216",\n\t\t\t"isbn":"9788928782284",\n\t\t\t"description":"\xeb\xb3\xb8\xec\x84\x9c\xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xec\x84\xb8\xea\xb3\x84 \xec\xb5\x9c\xec\xb4\x88\xeb\xa1\x9c \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xec\x82\xb0\xec\x97\x85\xec\x9d\x98 \xeb\xb0\x9c\xec\xa0\x84\xec\x9d\x84 4\xeb\x8b\xa8\xea\xb3\x84\xeb\xa1\x9c \xea\xb5\xac\xeb\xb6\x84\xed\x95\x98\xec\x97\xac \xec\x84\xa4\xeb\xaa\x85\xed\x95\x98\xeb\x8a\x94 [\xed\x95\x80\xed\x85\x8c\xed\x81\xac 4.0]\xec\x9d\x98 \xea\xb0\x9c\xeb\x85\x90\xec\x9d\x84 \xeb\x8f\x84\xec\x9e\x85\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4. \xec\x9d\xb4\xeb\x9f\xac\xed\x95\x9c \xea\xb0\x9c\xeb\x85\x90\xec\xa0\x81 \xed\x8b\x80\xec\x9d\x84 \xed\x86\xa0\xeb\x8c\x80\xeb\xa1\x9c \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xec\x82\xb0\xec\x97\x85\xec\x97\x90 \xeb\x8c\x80\xed\x95\x9c \xec\x9d\xb4\xeb\xa1\xa0\xec\xa0\x81\xec\x9d\xb8 \xec\x84\xa4\xeb\xaa\x85 \xeb\xb0\x8f \xec\x8b\xa4\xeb\xac\xb4\xec\x9d\x98 \xec\x9d\xb4\xed\x95\xb4\xec\x99\x80 \xed\x95\x84\xec\x9a\x94\xed\x95\x9c \xea\xb8\xb4\xec\x9a\x94\xed\x95\x9c \xec\x9a\x94\xec\x86\x8c\xeb\x93\xa4\xec\x9d\x84 \xec\xa0\x81\xec\x9e\xac\xec\xa0\x81\xec\x86\x8c\xec\x97\x90 \xeb\xb0\xb0\xec\xb9\x98\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4. \xec\x95\x84\xec\x9a\xb8\xeb\x9f\xac 60\xec\x97\xac\xea\xb0\x9c\xec\x9d\x98 \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xea\xb8\xb0\xec\x97\x85\xec\x97\x90 \xeb\x8c\x80\xed\x95\x9c \xec\x83\x81\xec\x84\xb8 \xeb\xb6\x84\xec\x84\x9d\xec\x9d\x84 \xed\x8f\xac\xed\x95\xa8\xed\x95\x9c \xed\x92\x8d\xeb\xb6\x80\xed\x95\x9c \xec\x8b\xa4\xeb\xa1\x80\xeb\xa5\xbc \xeb\x8b\xa4\xeb\xa4\x98\xea\xb8\xb0\xec\x97\x90 \xec\x82\xb0\xec\x97\x85\xea\xb3\x84\xeb\xbf\x90\xeb\xa7\x8c \xec\x95\x84\xeb\x8b\x88\xeb\x9d\xbc \xea\xb5\x90\xec\x9c\xa1\xed\x98\x84\xec\x9e\xa5\xec\x97\x90\xec\x84\x9c\xeb\x8f\x84 \xed\x99\x9c\xec\x9a\xa9\xea\xb0\x80\xeb\x8a\xa5\xec\x84\xb1\xec\x9d\xb4 \xeb\x86\x92\xeb\x8b\xa4."\n\t\t},\n\t\t{\n\t\t\t"title":"\xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x99\x80 \xeb\xb2\x95 (\xec\xa0\x9c3\xed\x8c\x90)",\n\t\t\t"link":"https:\\/\\/search.shopping.naver.com\\/book\\/catalog\\/32441765997",\n\t\t\t"image":"https:\\/\\/shopping-phinf.pstatic.net\\/main_3244176\\/32441765997.20221229073758.jpg",\n\t\t\t"author":"\xea\xb0\x95\xed\x98\x84\xea\xb5\xac^\xec\x9c\xa0\xec\xa3\xbc\xec\x84\xa0^\xec\x9d\xb4\xec\x84\xb1\xeb\x82\xa8",\n\t\t\t"discount":"19800",\n\t\t\t"publisher":"\xec\x94\xa8\xec\x95\x84\xec\x9d\xb4\xec\x95\x8c",\n\t\t\t"pubdate":"20201112",\n\t\t\t"isbn":"9791156109020",\n\t\t\t"description":"\xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x9d\x98 \xec\x98\x81\xec\x97\xad\xea\xb3\xbc \xea\xb7\xb8\xec\x97\x90 \xeb\x8c\x80\xed\x95\x9c \xeb\xb2\x95\xeb\xa5\xa0\xeb\xac\xb8\xec\xa0\x9c\xec\x9d\x98 \xea\xb0\x84\xea\xb2\xa9\xec\x9d\x84 \\n\xec\x96\xb4\xeb\x96\xbb\xea\xb2\x8c \xec\xa2\x81\xed\x9e\x90 \xec\x88\x98 \xec\x9e\x88\xec\x9d\x84 \xea\xb2\x83\xec\x9d\xb8\xea\xb0\x80\\n\\n\xed\x95\x80\xed\x85\x8c\xed\x81\xac \xea\xb4\x80\xeb\xa0\xa8 \xea\xb8\xb0\xec\x88\xa0\xec\x9d\x98 \xeb\xb0\x9c\xec\xa0\x84\xec\x9d\xb4 \xea\xb8\x89\xec\x86\x8d\xed\x95\x98\xea\xb2\x8c \xec\xa7\x84\xed\x96\x89 \xec\xa4\x91\xec\x97\x90 \xec\x9e\x88\xeb\x8b\xa4. 2018\xeb\x85\x84 \xea\xb0\x9c\xec\xa0\x95 \xec\x9d\xb4\xed\x9b\x84 2\xeb\x85\x84\xec\x9d\xb4 \xec\xa7\x80\xeb\x82\x9c \xed\x9b\x84 \xec\x9d\xb4\xeb\x9f\xac\xed\x95\x9c \xed\x95\x80\xed\x85\x8c\xed\x81\xac \xea\xb4\x80\xeb\xa0\xa8 \xeb\xb2\x95\xec\xa0\x9c\xeb\xa5\xbc \xeb\xb0\x98\xec\x98\x81\xed\x95\x98\xec\xa7\x80 \xec\x95\x8a\xec\x9c\xbc\xeb\xa9\xb4 \xec\x95\x88 \xeb\x90\x9c\xeb\x8b\xa4\xeb\x8a\x94 \xec\xa7\x91\xed\x95\x84\xec\x9e\x90\xeb\x93\xa4\xec\x9d\x98 \xec\x9d\x98\xea\xb2\xac\xec\x9d\xb4 \xeb\xaa\xa8\xec\x95\x84\xec\xa0\xb8 \xea\xb0\x9c\xec\xa0\x95 3\xed\x8c\x90\xec\x9d\x84 \xea\xb8\x88\xeb\xb2\x88\xec\x97\x90 \xec\xb6\x9c\xea\xb0\x84\xed\x95\x98\xea\xb2\x8c \xeb\x90\x9c \xea\xb2\x83\xec\x9d\xb4\xeb\x8b\xa4.\\n\xea\xb8\x88\xeb\xb2\x88\xec\x97\x90 \xea\xb0\x9c\xec\xa0\x95\xeb\x90\x98\xeb\x8a\x94 \xec\xa0\x9c3\xed\x8c\x90\xec\x9d\x80 \xeb\x8b\xa4\xec\x9d\x8c \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xec\x97\x85\xeb\x8d\xb0\xec\x9d\xb4\xed\x8a\xb8\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4.\\n\\n\xec\xb2\xab\xec\xa7\xb8, 2020\xeb\x85\x84 \xec\xa0\x9c\xec\x95\x88\xeb\x90\x9c \xe3\x80\x8c\xec\xa0\x84\xec\x9e\x90\xea\xb8\x88\xec\x9c\xb5\xea\xb1\xb0\xeb\x9e\x98\xeb\xb2\x95\xe3\x80\x8d \xea\xb0\x9c\xec\xa0\x95\xec\x95\x88\xec\x97\x90 \xeb\x8c\x80\xed\x95\x9c \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xec\x95\x98\xeb\x8b\xa4.\\n\xeb\x91\x98\xec\xa7\xb8, \xec\x86\x8c\xec\x95\xa1\xed\x95\xb4\xec\x99\xb8\xec\x86\xa1\xea\xb8\x88\xec\x97\x85 \xea\xb4\x80\xeb\xa0\xa8 \xec\xb5\x9c\xea\xb7\xbc \xea\xb0\x9c\xec\xa0\x95\xeb\x90\x9c \xe3\x80\x8c\xec\x99\xb8\xea\xb5\xad\xed\x99\x98\xea\xb1\xb0\xeb\x9e\x98\xeb\xb2\x95\xe3\x80\x8d\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\xb0\x98\xec\x98\x81\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4.\\n\xec\x85\x8b\xec\xa7\xb8, P2P \xeb\x8c\x80\xec\xb6\x9c\xea\xb3\xbc \xea\xb4\x80\xeb\xa0\xa8\xed\x95\x98\xec\x97\xac \xea\xb7\xb8\xeb\x8f\x99\xec\x95\x88 \xec\x9e\x85\xeb\xb2\x95 \xeb\xb0\xa9\xec\x95\x88\xec\x9d\xb4\xeb\x9d\xbc\xeb\x8a\x94 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xea\xb3\xa0 \xec\x9e\x88\xec\x97\x88\xec\xa7\x80\xeb\xa7\x8c, \xea\xb8\x88\xeb\xb2\x88 \xea\xb0\x9c\xec\xa0\x95\xed\x8c\x90\xec\x97\x90\xec\x84\x9c\xeb\x8a\x94 \xec\x9d\xb4\xec\xa0\x9c \xec\xa0\x9c\xec\xa0\x95\xeb\x90\x9c P2P \xeb\x8c\x80\xec\xb6\x9c\xeb\xb2\x95\xec\x9d\xb8 \xe3\x80\x8c\xec\x98\xa8\xeb\x9d\xbc\xec\x9d\xb8\xed\x88\xac\xec\x9e\x90\xec\x97\xb0\xea\xb3\x84\xea\xb8\x88\xec\x9c\xb5\xec\x97\x85 \xeb\xb0\x8f \xec\x9d\xb4\xec\x9a\xa9\xec\x9e\x90 \xeb\xb3\xb4\xed\x98\xb8\xec\x97\x90 \xea\xb4\x80\xed\x95\x9c \xeb\xb2\x95\xeb\xa5\xa0\xe3\x80\x8d\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xec\x83\x88\xeb\xa1\x9c\xec\x9d\xb4 \xea\xb8\xb0\xec\x88\xa0\xed\x95\x98\xec\x98\x80\xeb\x8b\xa4.\\n\xeb\x84\xb7\xec\xa7\xb8, \xe3\x80\x8c\xec\x9d\xb8\xed\x84\xb0\xeb\x84\xb7\xec\xa0\x84\xeb\xac\xb8\xec\x9d\x80\xed\x96\x89\xeb\xb2\x95\xe3\x80\x8d\xec\x9d\xb4 \xeb\x8f\x84\xec\x9e\x85\xeb\x90\xa8\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc \xec\x9d\xb8\xed\x84\xb0\xeb\x84\xb7\xec\xa0\x84\xeb\xac\xb8\xec\x9d\x80\xed\x96\x89 \xeb\x8f\x84\xec\x9e\x85 \xea\xb4\x80\xeb\xa0\xa8 \xeb\xb2\x95\xec\xa0\x81 \xec\x9f\x81\xec\xa0\x90\xec\x97\x90 \xec\x83\x88\xeb\xa1\x9c\xec\x9a\xb4 \xeb\xb2\x95\xeb\xa5\xa0\xec\x9d\x98 \xec\xa3\xbc\xec\x9a\x94 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xec\x95\x98\xeb\x8b\xa4.\\n\xeb\x8b\xa4\xec\x84\xaf\xec\xa7\xb8, \xed\x95\x80\xed\x85\x8c\xed\x81\xac\xec\x99\x80 \xeb\xb3\xb4\xed\x97\x98 \xed\x8c\x8c\xed\x8a\xb8\xec\x97\x90 \xec\x9d\xb8\xec\x8a\x88\xec\x96\xb4\xed\x85\x8c\xed\x81\xac\xec\x97\x90 \xea\xb4\x80\xed\x95\x9c \xec\xb5\x9c\xec\x8b\xa0 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xec\x95\x98\xeb\x8b\xa4. \xeb\xb3\xb4\xed\x97\x98\xec\x83\x81\xed\x92\x88 \xea\xb0\x9c\xeb\xb0\x9c\xec\x97\x90\xec\x84\x9c\xeb\xb6\x80\xed\x84\xb0 \xeb\xb3\xb4\xed\x97\x98\xea\xb3\x84\xec\x95\xbd\xec\x9d\x98 \xec\xb2\xb4\xea\xb2\xb0 \xeb\xb0\x8f \xeb\xb3\xb4\xed\x97\x98\xea\xb8\x88\xec\xb2\xad\xea\xb5\xac \xeb\x93\xb1\xec\x97\x90\xec\x84\x9c \xeb\xb0\x9c\xec\x83\x9d\xed\x95\xa0 \xec\x88\x98 \xec\x9e\x88\xeb\x8a\x94 \xec\x9d\xb8\xec\x8a\x88\xec\x96\xb4\xed\x85\x8c\xed\x81\xac\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xec\x83\x88\xeb\xa1\x9c\xec\x9d\xb4 \xeb\x8b\xb4\xec\x95\x98\xeb\x8b\xa4.\\n\xec\x97\xac\xec\x84\xaf\xec\xa7\xb8, \xeb\x8d\xb0\xec\x9d\xb4\xed\x84\xb0 3\xeb\xb2\x95\xec\x9d\xb4 \xea\xb0\x9c\xec\xa0\x95\xeb\x90\xa8\xec\x97\x90 \xeb\x94\xb0\xeb\x9d\xbc \xeb\xb9\x85\xeb\x8d\xb0\xec\x9d\xb4\xed\x84\xb0 \xea\xb4\x80\xeb\xa0\xa8 \xeb\xb2\x95\xec\xa0\x81 \xec\x9f\x81\xec\xa0\x90\xea\xb3\xbc \xea\xb7\xb8 \xec\x98\x81\xed\x96\xa5 \xeb\x93\xb1\xec\x9d\x98 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xec\x95\x98\xeb\x8b\xa4.\\n\xec\x9d\xbc\xea\xb3\xb1\xec\xa7\xb8, \xea\xb0\x80\xec\x83\x81\xed\x86\xb5\xed\x99\x94 \xea\xb4\x80\xeb\xa0\xa8 \xeb\xb2\x95\xec\xa0\x9c\xeb\xa1\x9c\xec\x84\x9c \xeb\xb6\x88\xec\x99\x84\xec\xa0\x84\xed\x95\x98\xec\xa7\x80\xeb\xa7\x8c \xea\xb0\x80\xec\x83\x81\xec\x9e\x90\xec\x82\xb0\xec\x9d\x84 \xeb\xb2\x95\xec\xa0\x9c\xed\x99\x94\xed\x95\x9c \xea\xb0\x9c\xec\xa0\x95 \xe3\x80\x8c\xed\x8a\xb9\xec\xa0\x95 \xea\xb8\x88\xec\x9c\xb5\xea\xb1\xb0\xeb\x9e\x98\xec\xa0\x95\xeb\xb3\xb4\xec\x9d\x98 \xeb\xb3\xb4\xea\xb3\xa0 \xeb\xb0\x8f \xec\x9d\xb4\xec\x9a\xa9 \xeb\x93\xb1\xec\x97\x90 \xea\xb4\x80\xed\x95\x9c \xeb\xb2\x95\xeb\xa5\xa0\xe3\x80\x8d \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xea\xb0\x84\xeb\x9e\xb5\xed\x9e\x88 \xeb\x8b\xa4\xeb\xa3\xa8\xec\x97\x88\xeb\x8b\xa4.\\n\xec\x97\xac\xeb\x8d\x9f\xec\xa7\xb8, \xe3\x80\x8c\xea\xb8\x88\xec\x9c\xb5\xed\x98\x81\xec\x8b\xa0\xec\xa7\x80\xec\x9b\x90 \xed\x8a\xb9\xeb\xb3\x84\xeb\xb2\x95\xe3\x80\x8d\xec\x9d\x98 \xec\xa3\xbc\xec\x9a\x94 \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xec\x95\x98\xeb\x8b\xa4. \xea\xb7\xb8\xeb\x8f\x99\xec\x95\x88 \xed\x99\x95\xec\xa0\x95\xeb\x90\x98\xec\xa7\x80 \xec\x95\x8a\xec\x95\x98\xeb\x8d\x98 \xea\xb8\x88\xec\x9c\xb5\xed\x98\x81\xec\x8b\xa0\xec\xa7\x80\xec\x9b\x90\xed\x8a\xb9\xeb\xb3\x84\xeb\xb2\x95\xec\x95\x88\xec\x97\x90 \xeb\x8c\x80\xed\x95\x9c \xeb\x82\xb4\xec\x9a\xa9\xec\x9d\x84 \xeb\x8b\xb4\xec\x95\x98\xeb\x8d\x98 \xea\xb

* 모든 검색 결과를 가져오기 위해서는 여러 페이지 정보를 수집
* 전체 결과 / 1페이지 표시 개수 = 전체 페이지 수
* start 부분 + 1페이지 표시 개수 = 다음 페이지 데이터 수집 가능
* 반복문을 이용해서 start에 100씩 더해서 최대 1000이 되도록 하면 최대한 많은 데이터 수집 가능

# 블로그, 책, 뉴스 동시에 수집하기

In [22]:
keyword = input('제목을 입력하세요: ')

book_dic = {}

for category in ['blog', 'book', 'news']:
    
    url = f"https://openapi.naver.com/v1/search/{category}.json"
    i = 1

    while (i <= 1000):
        payload = {'query': keyword, 'display': 100, 'start':i, 'sort': 'sim'}  
        headers = {'X-Naver-Client-Id' : "KWqT_uEHMFwBxZHzqvXj", 'X-Naver-Client-Secret' : 'UaIJQBMlNd'}
        r = requests.get(url, params=payload, headers=headers)

        data = r.json()
        for item in data['items']:
            for key, value in item.items():
                book_dic.setdefault(key,[]).append(value)

        if i >= (data['total']):
            break
        else:
            if i == 901:
                i += 99
            else:
                i += 100
            
# pd.concat() 합치는 함수

book_df = pd.DataFrame(book_dic)    
book_df

제목을 입력하세요: 파이썬

ValueError: All arrays must be of the same length

컬럼 값이 다른 경우 리스트로 받아서 데이터프레임으로 변경

In [37]:
import requests
import pandas as pd

keyword = input('제목을 입력하세요: ')

total_list = []

headers = {
    'X-Naver-Client-Id': "KWqT_uEHMFwBxZHzqvXj",
    'X-Naver-Client-Secret': 'UaIJQBMlNd'
}

for category in ['blog', 'book', 'news']:
    url = f"https://openapi.naver.com/v1/search/{category}.json"
    i = 1

    while i <= 1000:  # 반드시 1000을 초과하지 않도록 제한
        payload = {'query': keyword, 'display': 100, 'start': i, 'sort': 'sim'}
        r = requests.get(url, params=payload, headers=headers)

        if r.status_code == 200:
            data = r.json()

            if 'items' in data:
                total_list.extend(data['items'])
            else:
                print(f"'items' 없음. 받은 데이터: {data}")
                break

            total_results = data.get('total', 0)
            
            if (i + 100 > total_results) or (i + 100 > 1000):
                break
            else:
                i += 100

        else:
            print(f"API 호출 실패: {r.status_code}, 내용: {r.text}")
            break
final_df = pd.DataFrame(total_list)
final_df

제목을 입력하세요: 파이썬

,title,link,description,bloggername,bloggerlink,postdate,image,author,discount,publisher,pubdate,isbn,originallink,pubDate
0,대구<b>파이썬</b>학원 실전 기술 익힌 곳,https://blog.naver.com/xshinerx/223787876858,그때 힘이 되어 준 대구<b>파이썬</b>학원에 대한 글을 써보려 해요! IT 위주...,▶ 제이의 맛있는 세상 ◀,blog.naver.com/xshinerx,20250308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,대전자바학원 <b>파이썬</b> 앱개발 공부하고 취업까지,https://blog.naver.com/mamansiri/223750243246,저는 <b>파이썬</b>부터 시작해 백엔드 개발에 필요한 다양한 과정을 배우기로 결...,반짝반짝 너와 나,blog.naver.com/mamansiri,20250206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,<b>파이썬</b> 자격증 시험 종류 및 취득과정,https://blog.naver.com/hwani-0627/223748981099,오늘은 <b>파이썬</b> 자격증 시험 종류 및 취득과정에 대해서 자세히 알려드리도...,화닝의 일본어+교육 교실,blog.naver.com/hwani-0627,20250205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,<b>파이썬</b> 학원 AI를 개발하는 국비지원,https://blog.naver.com/newtechm/223801070808,<b>파이썬</b> 학원 AI를 개발하는 국비지원 최근 <b>파이썬</b>(Pyth...,법무법인 천선,blog.naver.com/newtechm,20250318,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(<b>파이썬</b> 학습기록)역시 개발공부 바닥도 고인물 투성. 내 길은...,https://blog.naver.com/currybread0/223761299487,최근 <b>파이썬</b> 학습에 있어서 꽤나 큰 변화가 있었기에 이를 기록하고자 합...,찰나의 실행과 독서 그리고 성장,blog.naver.com/currybread0,20250215,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,"&quot;금융 데이터 전문가되세요&quot;...키움증권, '디지털 아카데미' 1...",https://www.lcnews.co.kr/news/articleView.html...,정규교과는 ▲<b>파이썬</b> 프로그래밍 (데이터 분석 및 활용 능력 향상) ▲S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.lcnews.co.kr/news/articleView.html...,"Thu, 20 Feb 2025 14:54:00 +0900"
2996,"“금융 데이터 전문가 양성”…키움증권, ‘디지털 아카데미’ 1기생 모...",https://n.news.naver.com/mnews/article/009/000...,"정규교과는 <b>파이썬</b> 프로그래밍(데이터 분석·활용 능력 향상), SQL 이...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.mk.co.kr/article/11245828,"Thu, 20 Feb 2025 14:29:00 +0900"
2997,“금융 데이터 전문가 육성” 키움證 ‘디지털 아카데미’ 가동,https://n.news.naver.com/mnews/article/014/000...,정규교과는 △<b>파이썬</b> 프로그래밍 △구조적쿼리언어(SQL) 이해와 활용 △...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.fnnews.com/news/202502201422066173,"Thu, 20 Feb 2025 14:25:00 +0900"
2998,"“금융 데이터 전문가로 성장”…키움증권, ‘디지털 아카데미’ 1기생...",https://www.sentv.co.kr/article/view/sentv2025...,정규 교과는 ▲<b>파이썬</b> 프로그래밍 (데이터 분석 및 활용 능력 향상) ▲...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.sentv.co.kr/article/view/sentv2025...,"Thu, 20 Feb 2025 14:22:00 +0900"
2999,"키움증권, 디지털 교육생 모집...&quot;금융 데이터 전문가 양성&quot;",http://www.finomy.com/news/articleView.html?id...,정규교과는 ▲<b>파이썬</b> 프로그래밍 (데이터 분석 및 활용 능력 향상) ▲S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.finomy.com/news/articleView.html?id...,"Thu, 20 Feb 2025 13:58:00 +0900"

# 3개 카테고리 수집 코드를 함수화하기

In [34]:
def naver_search(category):
    response_result = []
    page = 1
    start_num2 = 1
    while True:
        url = f"https://openapi.naver.com/v1/search{category}.json"
        Client_Id = 'KWqT_uEHMFwBxZHzqvXj'
        Client_Secret=  'UaIJQBMlNd'
        payload = dict(query=keyword, display=100, start=start_num2, sort='sim')
        headers = {
            'X-Naver-Client-Id': "KWqT_uEHMFwBxZHzqvXj",
            'X-Naver-Client-Secret': 'UaIJQBMlNd'
            }
        r = requests.get(url,params=payload, headers=headers)
        print(r.url, end='\r')
        print(r.status_code, end='\r')
        response = r.json()
        total_pages = (response['total'] // 100) +1

        if category == 'blog':
            response_blog.append(response)
        elif category == 'news':
            response_news.append(response)
        elif category == 'book':
            response_book.append(response)

        if start_num2 == 1000:
            break
        if start_num2 < 901:
            start_num2 += 100
        elif start_num2 == 901:
            start_num2 += 99

In [35]:
import time

keyword = input("검색할 키워드를 입력해주세요 ")

for category in ['blog', 'news', 'book']:
    naver_search_result = naver_search(category)
    result_df = unpack(naver_search_result)
    display(result_df)

검색할 키워드를 입력해주세요 파이썬

KeyError: 'total'

In [18]:
for category in ['book', 'blog']:
    dic_categoty = 1
print(book_category)

NameError: name 'book_category' is not defined