# xml: html처럼 태그 기반으로 자료를 저장한 포멧
* xml parser를 통해서 str을 xml로 변환하는 작업이 필요
* xml로 변환이 되면 태그 기반으로 자료를 찾아서 정리
* 태그에서 자료를 추출할때는 beautifulsoup이라는 라이브러리를 이용

In [1]:
import requests
import json
import pandas as pd

In [2]:
rent_dic = {}
i = 1

while i <= 20:
    url = 'http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list'
    payload = {'serviceKey' : "lwJZpRMDn/p4YZe0Hzrf92CTBVmSbWToaTJgutxn3oJ6kss3RSoaZtwPvQiQLKYowcKSOnj3h6G54NvRysgQGA==", 
               'numOfRows' : 100, 
               'pageNo' : i,
               'dataType': 'json'}  

    response = requests.get(url, params=payload)
    data = response.json()

    for item in data['body']['items']:
        for key, value in item.items():
            rent_dic.setdefault(key,[]).append(value)
    
    i += 1
        
        
rent_df = pd.DataFrame(rent_dic)
rent_df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

* xml로 데이터를 받으면 처음에는 단순 문자열로 받게 된다.
* 문자열을 xml 문서로 변환해야 함
* beautifulsoup을 이용해 변환
* beautifulsoup의 메서드인 select, select_one을 이용해 css 셀렉터 기반으로 데이터가 위치한 태그를 찾아서 내용 추출

In [29]:
url = 'http://apis.data.go.kr/B551408/rent-loan-rate-info/rate-list'
payload = {'serviceKey' : "lwJZpRMDn/p4YZe0Hzrf92CTBVmSbWToaTJgutxn3oJ6kss3RSoaZtwPvQiQLKYowcKSOnj3h6G54NvRysgQGA==", 
           'numOfRows' : 20, 
           'pageNo' : 1,
           'dataType': 'XML'}  

response = requests.get(url, params=payload)
response = response.text
response

'<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>20</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item></items></body></response>'

# BeautifulSoup
* https://www.crummy.com/software/BeautifulSoup/bs4/doc.ko/ 참고
* pip install beautifulsoup4
* from bs4 import BeautifulSoup as bs
* find, find_all 함수 : xml, html에서 태그 기반으로 내용을 찾음
* select, select_one 함수 : xml, html에서 css selector 기반으로 내용을 찾음
* find_all, select는 해당 태그나 css select를 가진 부분을 모두 찾아서 리스트로 반환
* find, select_one은 여러 태그나 css selector 중에서 가장 먼저 나오는 태그, selector를 한 개만 찾아줌
* 찾아온 태그.name : 태그 이름 반환
* 찾아온 태그.text, .string : 태그 안쪽의 텍스트 반환

### 반복문으로 태그를 자동 추출해서 만들기

In [4]:
from bs4 import BeautifulSoup as bs

In [30]:
soup = bs(response, 'xml')
print(soup)

<?xml version="1.0" encoding="utf-8"?>
<response><header><resultCode>00</resultCode><resultMsg>정상</resultMsg></header><body><pageNo>1</pageNo><totalCount>18</totalCount><numOfRows>20</numOfRows><items><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>산업은행</organId><callCenter>1588-1500</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>제주은행</organId><callCenter>1588-0079</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>SC은행</organId><callCenter>1588-1599</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>전북은행</organId><callCenter>1588-4477</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>수협은행</organId><callCenter>1588-1515</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.26</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>우리은행</organId><callCenter>1599-5000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.64</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>경남은행</organId><callCenter>1588-8585</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.5</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>카카오뱅크</organId><callCenter>1599-3333</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.38</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>아이엠뱅크</organId><callCenter>1588-5050</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.18</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>하나은행</organId><callCenter>1599-1111</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.74</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>토스뱅크</organId><callCenter>1661-7654</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.7</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>케이뱅크</organId><callCenter>1522-1000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.89</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>국민은행</organId><callCenter>1644-9999</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>3.84</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>부산은행</organId><callCenter>1588-6200</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.05</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>농협은행</organId><callCenter>1588-2100</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.0</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>기업은행</organId><callCenter>1566-2566</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.11</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>광주은행</organId><callCenter>1600-4000</callCenter></item><item><bssYmdStart>20250310</bssYmdStart><interest4_1>4.07</interest4_1><interest3_2>0</interest3_2><interest4_2>0</interest4_2><interest2_1>0</interest2_1><interest1_2>0</interest1_2><interest3_1>0</interest3_1><interest2_2>0</interest2_2><interest1_1>0</interest1_1><bssYmdEnd>20250316</bssYmdEnd><organId>신한은행</organId><callCenter>1599-8000</callCenter></item></items></body></response>

In [31]:
soup.select_one('resultCode')

In [32]:
items = soup.select_one('items')
item = items.select('item')

In [33]:
for tag in items.select_one('item'):
    print(tag.name)

bssYmdStart
interest4_1
interest3_2
interest4_2
interest2_1
interest1_2
interest3_1
interest2_2
interest1_1
bssYmdEnd
organId
callCenter

In [34]:
items = soup.select_one('items')
bssYmdStart_list = items.select('bssYmdStart')
interest4_1_list = items.select('interest4_1')
interest3_2_list = items.select('interest3_2')
interest4_2_list = items.select('interest4_2')
interest2_1_list = items.select('interest2_1')
interest1_2_list = items.select('interest1_2')
interest3_1_list = items.select('interest3_1')
interest2_2_list = items.select('interest2_2')
interest1_1_list = items.select('interest1_1')
bssYmdEnd_list = items.select('bssYmdEnd')
organId_list = items.select('organId')
callCenter_list = items.select('callCenter')

In [35]:
tag_list = [bssYmdStart_list,interest4_1_list, interest3_2_list, interest4_2_list,interest2_1_list, interest1_2_list, interest3_1_list, interest2_2_list, interest1_1_list, bssYmdEnd_list, organId_list, callCenter_list]

result = {}

for lists in tag_list:
    for item in lists:
        result.setdefault(item.name, []).append(item.text)

result

{'bssYmdStart': ['20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310',
  '20250310'],
 'interest4_1': ['0',
  '0',
  '0',
  '4.89',
  '0',
  '4.26',
  '4.64',
  '3.5',
  '3.38',
  '4.18',
  '3.74',
  '3.7',
  '3.89',
  '3.84',
  '4.05',
  '4.0',
  '4.11',
  '4.07'],
 'interest3_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest4_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest2_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest1_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest3_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest2_2': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'interest1_1': ['0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0',
  '0'],
 'bssYmdEnd': ['20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316',
  '20250316'],
 'organId': ['산업은행',
  '제주은행',
  'SC은행',
  '전북은행',
  '수협은행',
  '우리은행',
  '경남은행',
  '카카오뱅크',
  '아이엠뱅크',
  '하나은행',
  '토스뱅크',
  '케이뱅크',
  '국민은행',
  '부산은행',
  '농협은행',
  '기업은행',
  '광주은행',
  '신한은행'],
 'callCenter': ['1588-1500',
  '1588-0079',
  '1588-1599',
  '1588-4477',
  '1588-1515',
  '1599-5000',
  '1588-8585',
  '1599-3333',
  '1588-5050',
  '1599-1111',
  '1661-7654',
  '1522-1000',
  '1644-9999',
  '1588-6200',
  '1588-2100',
  '1566-2566',
  '1600-4000',
  '1599-8000']}

In [36]:
for item in soup.select("items"):
    for tags in item.select('item'):
        for tag in tags:
            result.setdefault(tag.name,[]).append(tag.text)
            
df = pd.DataFrame(result)
df

,bssYmdStart,interest4_1,interest3_2,interest4_2,interest2_1,interest1_2,interest3_1,interest2_2,interest1_1,bssYmdEnd,organId,callCenter
0,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
1,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
2,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
3,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
4,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
5,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
6,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
7,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
8,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
9,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
10,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
11,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
12,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
13,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
14,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
15,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
16,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
17,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000
18,20250310,0,0,0,0,0,0,0,0,20250316,산업은행,1588-1500
19,20250310,0,0,0,0,0,0,0,0,20250316,제주은행,1588-0079
20,20250310,0,0,0,0,0,0,0,0,20250316,SC은행,1588-1599
21,20250310,4.89,0,0,0,0,0,0,0,20250316,전북은행,1588-4477
22,20250310,0,0,0,0,0,0,0,0,20250316,수협은행,1588-1515
23,20250310,4.26,0,0,0,0,0,0,0,20250316,우리은행,1599-5000
24,20250310,4.64,0,0,0,0,0,0,0,20250316,경남은행,1588-8585
25,20250310,3.5,0,0,0,0,0,0,0,20250316,카카오뱅크,1599-3333
26,20250310,3.38,0,0,0,0,0,0,0,20250316,아이엠뱅크,1588-5050
27,20250310,4.18,0,0,0,0,0,0,0,20250316,하나은행,1599-1111
28,20250310,3.74,0,0,0,0,0,0,0,20250316,토스뱅크,1661-7654
29,20250310,3.7,0,0,0,0,0,0,0,20250316,케이뱅크,1522-1000
30,20250310,3.89,0,0,0,0,0,0,0,20250316,국민은행,1644-9999
31,20250310,3.84,0,0,0,0,0,0,0,20250316,부산은행,1588-6200
32,20250310,4.05,0,0,0,0,0,0,0,20250316,농협은행,1588-2100
33,20250310,4.0,0,0,0,0,0,0,0,20250316,기업은행,1566-2566
34,20250310,4.11,0,0,0,0,0,0,0,20250316,광주은행,1600-4000
35,20250310,4.07,0,0,0,0,0,0,0,20250316,신한은행,1599-8000

In [12]:
for tag in soup.select('items')[0]:
    for key in tag:
        print(key.name, key.text)

bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 산업은행
callCenter 1588-1500
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 제주은행
callCenter 1588-0079
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId SC은행
callCenter 1588-1599
bssYmdStart 20250310
interest4_1 4.89
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 전북은행
callCenter 1588-4477
bssYmdStart 20250310
interest4_1 0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 수협은행
callCenter 1588-1515
bssYmdStart 20250310
interest4_1 4.26
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 우리은행
callCenter 1599-5000
bssYmdStart 20250310
interest4_1 4.64
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 경남은행
callCenter 1588-8585
bssYmdStart 20250310
interest4_1 3.5
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 카카오뱅크
callCenter 1599-3333
bssYmdStart 20250310
interest4_1 3.38
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 아이엠뱅크
callCenter 1588-5050
bssYmdStart 20250310
interest4_1 4.18
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 하나은행
callCenter 1599-1111
bssYmdStart 20250310
interest4_1 3.74
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 토스뱅크
callCenter 1661-7654
bssYmdStart 20250310
interest4_1 3.7
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 케이뱅크
callCenter 1522-1000
bssYmdStart 20250310
interest4_1 3.89
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 국민은행
callCenter 1644-9999
bssYmdStart 20250310
interest4_1 3.84
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 부산은행
callCenter 1588-6200
bssYmdStart 20250310
interest4_1 4.05
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 농협은행
callCenter 1588-2100
bssYmdStart 20250310
interest4_1 4.0
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 기업은행
callCenter 1566-2566
bssYmdStart 20250310
interest4_1 4.11
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 광주은행
callCenter 1600-4000
bssYmdStart 20250310
interest4_1 4.07
interest3_2 0
interest4_2 0
interest2_1 0
interest1_2 0
interest3_1 0
interest2_2 0
interest1_1 0
bssYmdEnd 20250316
organId 신한은행
callCenter 1599-8000

## xml에 있는 모든 key를 추출하기

In [13]:
tag_names = []

for item in soup.select("item"):
    for tag in item:
        tag_names.append(tag.name)
tag_names

['bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter',
 'bssYmdStart',
 'interest4_1',
 'interest3_2',
 'interest4_2',
 'interest2_1',
 'interest1_2',
 'interest3_1',
 'interest2_2',
 'interest1_1',
 'bssYmdEnd',
 'organId',
 'callCenter']

# 집합자료형 set : 중복 없는 데이터 집합 만들기
* 리스트 속 중복된 요소들이 한개씩만 남게됨

In [14]:
tags = set(tag_names)
tags

{'bssYmdEnd',
 'bssYmdStart',
 'callCenter',
 'interest1_1',
 'interest1_2',
 'interest2_1',
 'interest2_2',
 'interest3_1',
 'interest3_2',
 'interest4_1',
 'interest4_2',
 'organId'}

In [15]:
result = {}
for tags in soup.select("item"):
    for tag in tags:
        result.setdefault(tag,[]).append()

TypeError: list.append() takes exactly one argument (0 given)

# 금융위원회_서민금융상품기본정보

In [ ]:
https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo

In [ ]:
lwJZpRMDn/p4YZe0Hzrf92CTBVmSbWToaTJgutxn3oJ6kss3RSoaZtwPvQiQLKYowcKSOnj3h6G54NvRysgQGA==

## JSON 데이터 정리

In [16]:
result_dic = {}
i = 1

while i <= 48:
    url = 'https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo'
    payload = {'serviceKey' : "lwJZpRMDn/p4YZe0Hzrf92CTBVmSbWToaTJgutxn3oJ6kss3RSoaZtwPvQiQLKYowcKSOnj3h6G54NvRysgQGA==", 
               'numOfRows' : 100, 
               'pageNo' : i,
               'resultType': 'json'}  

    response = requests.get(url, params=payload)
    data = response.json()

    for item in data['response']['body']['items']['item']:
        for key, value in item.items():
            result_dic.setdefault(key,[]).append(value)
    
    i += 1
        
        
result_df = pd.DataFrame(result_dic)
result_df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,None,1,대출상품,None,None,None,None,None,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,None,1,대출상품,None,None,None,None,None,202502010700

In [77]:
soup = bs(response2, 'xml')
print(soup)

<?xml version="1.0" encoding="utf-8"?>
<response>
<header>
<resultCode>00</resultCode>
<resultMsg>NORMAL SERVICE.</resultMsg>
</header>
<body>
<numOfRows>100</numOfRows>
<pageNo>48</pageNo>
<totalCount>4741</totalCount>
<items>
<item>
<basYm>202110</basYm>
<snq>389</snq>
<finPrdNm>경기도 중소기업 육성자금(운전_일자리창출기업)</finPrdNm>
<lnLmt>30000만원</lnLmt>
<irtCtg>-</irtCtg>
<irt>은행금리</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>2년</maxDfrmTrm>
<maxRdptTrm>3년</maxRdptTrm>
<rdptMthd>균등분할상환</rdptMthd>
<usge>운전</usge>
<trgt>중소기업</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경기신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경기</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>도내 중소기업으로서 아래 어느 하나에 해당하는 기업일자리기업 : 최근 1년 이내 신규고용을 창출한 기업(기존대비 고용인원 증가 및 1년 이상 고용유지를 확약한 경우에 한함)</suprTgtDtlCond>
<age>없음</age>
<incm>없음</incm>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경기신용보증재단</grnInst>
<jnMthd>경기신용보증재단 각 지점 및 기술평가센터 방문</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<etcRefSbjc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<hdlInst>경기신용보증재단</hdlInst>
<cnpl>경기신용보증재단 각 지점 및 기술평가센터(1577-5900)</cnpl>
<rltSite>https://www.gcgf.or.kr/gcgf/subIndex/82.do</rltSite>
<tgtFltr>사업자,소상공인</tgtFltr>
<hdlInstDtlVw>경기신용보증재단</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>연중 수시(자금 소진시까지)</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>390</snq>
<finPrdNm>경기도 중소기업 육성자금(운전_혁신창업사업화기업)</finPrdNm>
<lnLmt>50000만원</lnLmt>
<irtCtg>고정금리</irtCtg>
<irt>은행금리</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>2년</maxDfrmTrm>
<maxRdptTrm>3년</maxRdptTrm>
<rdptMthd>균등분할상환</rdptMthd>
<usge>운전</usge>
<trgt>중소기업</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경기신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경기</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>도내 중소기업으로서 아래 어느 하나에 해당하는 기업기술력보유기업 : ① 보증신청 접수일 현재 최근 2년 이내 등록(출원)된 특허권 또는 실용신안권 (전용실시권) 보유기업② 부품·소재 전문 확인기업③ 신기술인증(NET) 보유기업④ 신제품인증(NEP) 보유기업⑤ 규제샌드박스 적용 대상으로 확정된 기업⑥ 창업경진대회 입상기업 : 보증신청 접수일 현재 최근 2년 이내 정부, 도, 또는 시·군, 공공기관, 대학 등에서 주관한 창업경진대회 입상기업유망창업기업 : ① 창업지원기관 입주기업 : 도내 벤처센터, 테크노파크, 창조경제혁신센터, 스타트업캠퍼스, 창업보육센터 등 공공 지원기관 입주기업② 도 주관 창업 지원사업을 정상적으로 완료한 기업</suprTgtDtlCond>
<age>없음</age>
<incm>없음</incm>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경기신용보증재단</grnInst>
<jnMthd>경기신용보증재단 각 지점 및 기술평가센터 방문</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<etcRefSbjc>대출은행 : 농협은행, 신한은행, 우리은행, 하나은행, SC은행</etcRefSbjc>
<hdlInst>경기신용보증재단</hdlInst>
<cnpl>경기신용보증재단 각 지점 및 기술평가센터(1577-5900)</cnpl>
<rltSite>https://www.gcgf.or.kr/gcgf/subIndex/82.do</rltSite>
<tgtFltr>사업자,소상공인</tgtFltr>
<hdlInstDtlVw>경기신용보증재단, 대출은행 : 농협은행, 신한은행, 우리은행, 하나은행, SC은행</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>연중 수시(자금 소진시까지)</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>391</snq>
<finPrdNm>경기도 중소기업 육성자금(운전_성장디딤돌 기업)</finPrdNm>
<lnLmt>50000만원</lnLmt>
<irtCtg>-</irtCtg>
<irt>은행금리</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>2년</maxDfrmTrm>
<maxRdptTrm>3년</maxRdptTrm>
<rdptMthd>균등분할상환</rdptMthd>
<usge>운전</usge>
<trgt>중소기업</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경기신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경기</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>도내 중소기업으로서 아래 어느 하나에 해당하는 기업고성장기업 : ① 전년대비 매출액 20% 이상 증가한 기업② 최근 3개년 연속 매출액 10% 이상 증가한 기업성장동력기업 : ① 경기도 전략산업 및 4차 산업혁명 관련 업종 영위 기업② 「뿌리산업 진흥과 첨단화에 관한 법률 시행령」에 따른 뿌리산업 업종 영위 기업</suprTgtDtlCond>
<age>없음</age>
<incm>없음</incm>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경기신용보증재단</grnInst>
<jnMthd>경기신용보증재단 각 지점 및 기술평가센터 방문</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<etcRefSbjc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<hdlInst>경기신용보증재단</hdlInst>
<cnpl>경기신용보증재단 각 지점 및 기술평가센터(1577-5900)</cnpl>
<rltSite>https://www.gcgf.or.kr/gcgf/subIndex/82.do</rltSite>
<tgtFltr>사업자,소상공인</tgtFltr>
<hdlInstDtlVw>경기신용보증재단</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>연중 수시(자금 소진시까지)</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>392</snq>
<finPrdNm>금융기관 특별출연 협약보증</finPrdNm>
<lnLmt>80000만원</lnLmt>
<irtCtg>-</irtCtg>
<irt>-</irt>
<maxTotLnTrm>5(시설자금: 5년 초과 가능)</maxTotLnTrm>
<maxDfrmTrm>-</maxDfrmTrm>
<maxRdptTrm>-</maxRdptTrm>
<rdptMthd>-</rdptMthd>
<usge>운영·시설</usge>
<trgt>중소기업, 소상공인</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경기신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경기</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>경기도내 본점 또는 사업장이 소재하고 있는 중소기업 및 소상공인</suprTgtDtlCond>
<age>없음</age>
<incm>없음</incm>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경기신용보증재단</grnInst>
<jnMthd>상담 및 문의 : 경기신용보증재단 각 지점 (1577-5900)</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst>최종산출보증료율에서 0.2% 차감, 최저 1% 로 운용</lnIcdcst>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<etcRefSbjc>보증비율 50백만원 이하 100%, 50백만원 초과 90%</etcRefSbjc>
<hdlInst>경기신용보증재단</hdlInst>
<cnpl>경기신용보증재단 각 지점(1577-5900)</cnpl>
<rltSite>https://www.gcgf.or.kr/gcgf/subIndex/60.do</rltSite>
<tgtFltr>사업자,소상공인</tgtFltr>
<hdlInstDtlVw>경기신용보증재단, 협약체결 시중은행</hdlInstDtlVw>
<prdExisYn>Y</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>2011.03.14 ~ 자금소진시 또는 사업종료시</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>393</snq>
<finPrdNm>경기도 취약 소상공인 자금(경영개선자금)</finPrdNm>
<lnLmt>2000만원</lnLmt>
<irtCtg>-</irtCtg>
<irt>4.15%</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>0년</maxDfrmTrm>
<maxRdptTrm>5년</maxRdptTrm>
<rdptMthd>원리금균등분할상환</rdptMthd>
<usge>운영·시설</usge>
<trgt>사업자, 소상공인</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경기신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경기</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>사업장 소재지가 경기도인 자접수일 현재 대표자가 만20세 이상인 자교육이수(온라인 포함 6시간 이상) 요건을 충족하는 자금융소외자(저소득,저신용자)¹ 또는 사회적 약자²   1. 금융소외자 : 연소득이 47백만원 이하이면서 개인신용평점 744점 이하   2. 사회적약자 : 50대 가장(은퇴자, 실직자), 장애인, 다문화가정, 한부모가정, 다둥이가정, 북한이탈주민, 기초생활수급자, 차상위계층특별지원자금 대상자 : 상기 요건을 모두 충족하며 경기도내 시군추천 소상공인특례보증 담당공무원이 추천한 자로, 내부 평가위원회 심의를 통과한 자</suprTgtDtlCond>
<age>없음</age>
<incm>(금융소외자) 연소득이 47백만원 이하</incm>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc>(금융소외자) 개인신용평점 744점 이하</crdtSc>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경기신용보증재단</grnInst>
<jnMthd>상담 및 문의 : 경기신용보증재단 각 지점 (1577-5900)</jnMthd>
<rpymdCfe>-</rpymdCfe>
<lnIcdcst>보증료율 연 0.5%</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>경기도 1.0% 이차보전인센티브(페이백, Pay Back)(지원대상) 경기도 취약 소상공인 자금 전액 상환자(지원내용) 전액상환까지 총 부담한 정상이자의 일부를 계산하여 환급</prftAddIrtCond>
<etcRefSbjc>* 상세 융자기간 (경영개선자금) 거치기간 없이 60개월 이내 원리금 균분상환</etcRefSbjc>
<hdlInst>경기신용보증재단, 협약은행</hdlInst>
<cnpl>경기신용보증재단 각 지점 (1577-5900)</cnpl>
<rltSite>https://www.gcgf.or.kr/gcgf/subIndex/62.do</rltSite>
<tgtFltr>사업자, 소상공인</tgtFltr>
<hdlInstDtlVw>경기신용보증재단, 경기도 소재 농협은행</hdlInstDtlVw>
<prdExisYn>N</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>2022.04.11 ~ 자금 소진 시까지</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>394</snq>
<finPrdNm>경기도 취약 소상공인 자금(특별지원자금)</finPrdNm>
<lnLmt>5000만원</lnLmt>
<irtCtg>-</irtCtg>
<irt>4.15%</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>0년</maxDfrmTrm>
<maxRdptTrm>5년</maxRdptTrm>
<rdptMthd>원리금균등분할상환</rdptMthd>
<usge>운영·시설</usge>
<trgt>사업자, 소상공인</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경기신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경기</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>사업장 소재지가 경기도인 자접수일 현재 대표자가 만20세 이상인 자교육이수(온라인 포함 6시간 이상) 요건을 충족하는 자금융소외자(저소득,저신용자)¹ 또는 사회적 약자²   1. 금융소외자 : 연소득이 47백만원 이하이면서 개인신용평점 744점 이하   2. 사회적약자 : 50대 가장(은퇴자, 실직자), 장애인, 다문화가정, 한부모가정, 다둥이가정, 북한이탈주민, 기초생활수급자, 차상위계층특별지원자금 대상자 : 상기 요건을 모두 충족하며 경기도내 시군추천 소상공인특례보증 담당공무원이 추천한 자로, 내부 평가위원회 심의를 통과한 자</suprTgtDtlCond>
<age>없음</age>
<incm>(금융소외자) 연소득이 47백만원 이하</incm>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc>(금융소외자) 개인신용평점 744점 이하</crdtSc>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경기신용보증재단</grnInst>
<jnMthd>상담 및 문의 : 경기신용보증재단 각 지점 (1577-5900)</jnMthd>
<rpymdCfe>-</rpymdCfe>
<lnIcdcst>보증료율 연 0.5%</lnIcdcst>
<ovItrYr>-</ovItrYr>
<prftAddIrtCond>경기도 1.0% 이차보전인센티브(페이백, Pay Back)(지원대상) 경기도 취약 소상공인 자금 전액 상환자(지원내용) 전액상환까지 총 부담한 정상이자의 일부를 계산하여 환급</prftAddIrtCond>
<etcRefSbjc>* 상세 융자기간 (특별지원자금) 거치기간 없이 60개월 이내 원리금 균분상환</etcRefSbjc>
<hdlInst>경기신용보증재단, 협약은행</hdlInst>
<cnpl>경기신용보증재단 각 지점 (1577-5900)</cnpl>
<rltSite>https://www.gcgf.or.kr/gcgf/subIndex/62.do</rltSite>
<tgtFltr>사업자, 소상공인</tgtFltr>
<hdlInstDtlVw>경기신용보증재단, 경기도 소재 농협은행</hdlInstDtlVw>
<prdExisYn>N</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>2022.04.11 ~ 자금 소진 시까지</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>395</snq>
<finPrdNm>일반경영안정자금(창업초기자금)</finPrdNm>
<lnLmt>7000만원</lnLmt>
<irtCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<irt>-</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>2년</maxDfrmTrm>
<maxRdptTrm>3년</maxRdptTrm>
<rdptMthd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<usge>운영·시설</usge>
<trgt>사업자, 소상공인</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경북신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경북</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>사업자등록증 기준 업력 1년 이상의 소상공인중소벤처기업부 장관이 정한 교육과정을 12시간 이상 수료한 소상공인</suprTgtDtlCond>
<age>없음</age>
<incm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경북신용보증재단</grnInst>
<jnMthd>기관 문의</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<etcRefSbjc>교육 인정기간교육 수료일로부터 1년반까지</etcRefSbjc>
<hdlInst>경북신용보증재단</hdlInst>
<cnpl>경북신용보증재단 054-474-7100</cnpl>
<rltSite>https://gbsinbo.co.kr/renew/credit/normal_04_01.html</rltSite>
<tgtFltr>사업자, 소상공인</tgtFltr>
<hdlInstDtlVw>경북신용보증재단</hdlInstDtlVw>
<prdExisYn>N</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>상시</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>396</snq>
<finPrdNm>일반경영안정자금(여성가장 지원)</finPrdNm>
<lnLmt>7000만원</lnLmt>
<irtCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<irt>-</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>2년</maxDfrmTrm>
<maxRdptTrm>3년</maxRdptTrm>
<rdptMthd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<usge>운영·시설</usge>
<trgt>사업자, 소상공인</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경북신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경북</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>경제활동이 불가능한 부양가족만 있는 여성가장 소상공인※가족관계증명서 등재가족(배우자, 직계 존·비속, 형제자매 등) 중 주민등록등본 상 최근 6개월 이상 동일 세대 세대원으로 등록된 자 전체가 경제활동 능력이 없는 경우</suprTgtDtlCond>
<age>없음</age>
<incm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rsdArea xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<crdtSc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<anin xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housHoldCnt xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<housAr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnTgtHous xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<rfrcCnpl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<grnInst>경북신용보증재단</grnInst>
<jnMthd>기관 문의</jnMthd>
<rpymdCfe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<lnIcdcst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<ovItrYr xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prftAddIrtCond xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<etcRefSbjc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<hdlInst>경북신용보증재단</hdlInst>
<cnpl>경북신용보증재단 054-474-7100</cnpl>
<rltSite>https://gbsinbo.co.kr/renew/credit/normal_04_01.html</rltSite>
<tgtFltr>사업자, 소상공인</tgtFltr>
<hdlInstDtlVw>경북신용보증재단</hdlInstDtlVw>
<prdExisYn>N</prdExisYn>
<cv19Rfrc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<prdCtg>1</prdCtg>
<prdNm>대출상품</prdNm>
<cv19SuprCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<cv19SuprTgtDtlCtn xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<mgmDln>상시</mgmDln>
<prdCtg2>정책자금</prdCtg2>
<fileWrtDt>202502010700</fileWrtDt>
</item>
<item>
<basYm>202110</basYm>
<snq>397</snq>
<finPrdNm>일반경영안정자금(사업전환자금)</finPrdNm>
<lnLmt>10000만원</lnLmt>
<irtCtg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<irt>-</irt>
<maxTotLnTrm>5년</maxTotLnTrm>
<maxDfrmTrm>2년</maxDfrmTrm>
<maxRdptTrm>3년</maxRdptTrm>
<rdptMthd xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:nil="true"/>
<usge>운영·시설</usge>
<trgt>사업자, 소상공인</trgt>
<instCtg>일반기관</instCtg>
<ofrInstNm>경북신용보증재단</ofrInstNm>
<rsdAreaPamtEqltIstm>경북</rsdAreaPamtEqltIstm>
<suprTgtDtlCond>소상공인 재창업패키지 교육을 수료한 소상공인</suprTgtDtlCond>
<age>없음</age>

## XML 데이터 정리

In [76]:
result2_dic = {}
i = 1

while i <= 48:
    url = 'https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo'
    payload = {'serviceKey' : "lwJZpRMDn/p4YZe0Hzrf92CTBVmSbWToaTJgutxn3oJ6kss3RSoaZtwPvQiQLKYowcKSOnj3h6G54NvRysgQGA==", 
               'numOfRows' : 100, 
               'pageNo' : i,
               'resultType': 'xml'}  

    response2 = requests.get(url, params=payload)
    response2 = response2.text

    soup2 = bs(response2, 'xml')

    for item in soup2.select('item'):
        for tag in item:
            if (tag.name):
                result2_dic.setdefault(tag.name, []).append(tag.text)
                
    i += 1

    
result2_df = pd.DataFrame(result2_dic)
result2_df

,basYm,snq,finPrdNm,lnLmt,irtCtg,irt,maxTotLnTrm,maxDfrmTrm,maxRdptTrm,rdptMthd,...,prdExisYn,cv19Rfrc,prdCtg,prdNm,cv19SuprCtg,cv19SuprCtn,cv19SuprTgtDtlCtn,mgmDln,prdCtg2,fileWrtDt
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

In [75]:
result2_dic = {}
column = ['기준년월','순번', '금융상품명', '대출한도', '금리구분', '금리', '(최대)총대출기간', '(최대)거치기간', '(최대)상환기간', '상환방법', '용도', '대상', '기관구분', '제공기관명', '거주지역원금균등분할상환', '지원대상상세조건' ,'연령' ,'소득', '거주지역' ,'신용등급' ,'연소득' ,'주택보유수', '주택면적', '대출대상주택' ,'문의처 및 연락처' ,'보증기관', '가입(신청)방법', '중도상환수수료', '대출부대비용', '연체이자율(연)', '우대금리/가산금리 조건' ,'기타 참고사항', '취급기관', '연락처', '관련 사이트', '대상_필터', '취급기간_상세보기용', '상품존재여부', '문의처(코로나)', '상품구분', '상품명', '코로나19 지원구분', '코로나19 지원내용', '코로나19 지원대상 상세내용', '운영기한', '상품구분 2', '파일작성일시']

i = 1

while i <= 48:
    url = 'https://apis.data.go.kr/1160100/service/GetSmallLoanFinanceInstituteInfoService/getOrdinaryFinanceInfo'
    payload = {'serviceKey' : "lwJZpRMDn/p4YZe0Hzrf92CTBVmSbWToaTJgutxn3oJ6kss3RSoaZtwPvQiQLKYowcKSOnj3h6G54NvRysgQGA==", 
               'numOfRows' : 100, 
               'pageNo' : i,
               'resultType': 'xml'}  

    response2 = requests.get(url, params=payload)
    response2 = response2.text

    soup2 = bs(response2, 'xml')
                
    for item in soup2.select('item'):
        tags = item.find_all(True)
    
        for col, tag in zip(column, tags):
            result2_dic.setdefault(col, []).append(tag.text)
                
    i += 1
                
result2_df = pd.DataFrame(result2_dic)
result2_df

,기준년월,순번,금융상품명,대출한도,금리구분,금리,(최대)총대출기간,(최대)거치기간,(최대)상환기간,상환방법,...,상품존재여부,문의처(코로나),상품구분,상품명,코로나19 지원구분,코로나19 지원내용,코로나19 지원대상 상세내용,운영기한,상품구분 2,파일작성일시
0,202503,1,새희망홀씨Ⅱ,3500만원,변동금리,은행별 상이,은행별 상이,-,-,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
1,202503,2,징검다리론,3000만원,변동금리,은행별 상이,5년,1년,4년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,기관 문의,-,202504010700
2,202503,3,"우리지역 氣-Up 서포트론(영세 소기업,소상공인)","5,00010,000 (코로나 19 피해 소기업, 소상공인)",변동금리,6.27~8.97%,5년,1년,4년,원금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
3,202503,4,경상남도 청년 전세자금(경상남도 협약 상품)(경상남도 청년주택 임차보증금 이자지원사업),9000만원,변동금리,은행별 상이,임대차계약기간 이내 최대 2년,0년,0년,일시상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
4,202503,5,i-ONE근로자생활안정자금대출,1000만원,고정금리,1.5 / 2.6 / 1.0 / 3.0,"근로자생활안정자금, 임금체불생계비, 체불근로자생계비 : 2년, 4년, 5년, 6년,...",6년,5년,원(리)금균등분할상환,...,Y,-,1,대출상품,-,-,-,상시,-,202504010700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4736,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4737,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4738,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
4739,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
4740,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

In [74]:
result3_dic = {}
column = ['기준년월','순번', '금융상품명', '대출한도', '금리구분', '금리', '(최대)총대출기간', '(최대)거치기간', '(최대)상환기간', '상환방법', '용도', '대상', '기관구분', '제공기관명', '거주지역원금균등분할상환', '지원대상상세조건' ,'연령' ,'소득', '거주지역' ,'신용등급' ,'연소득' ,'주택보유수', '주택면적', '대출대상주택' ,'문의처 및 연락처' ,'보증기관', '가입(신청)방법', '중도상환수수료', '대출부대비용', '연체이자율(연)', '우대금리/가산금리 조건' ,'기타 참고사항', '취급기관', '연락처', '관련 사이트', '대상_필터', '취급기간_상세보기용', '상품존재여부', '문의처(코로나)', '상품구분', '상품명', '코로나19 지원구분', '코로나19 지원내용', '코로나19 지원대상 상세내용', '운영기한', '상품구분 2', '파일작성일시']


for item in soup2.select('item'):
    tags = item.find_all(True)
    
    for col, tag in zip(column, tags):
        result3_dic.setdefault(col, []).append(tag.text)
            
result3_df = pd.DataFrame(result3_dic)
result3_df

,기준년월,순번,금융상품명,대출한도,금리구분,금리,(최대)총대출기간,(최대)거치기간,(최대)상환기간,상환방법,...,상품존재여부,문의처(코로나),상품구분,상품명,코로나19 지원구분,코로나19 지원내용,코로나19 지원대상 상세내용,운영기한,상품구분 2,파일작성일시
0,202110,389,경기도 중소기업 육성자금(운전_일자리창출기업),30000만원,-,은행금리,5년,2년,3년,균등분할상환,...,Y,,1,대출상품,,,,연중 수시(자금 소진시까지),정책자금,202502010700
1,202110,390,경기도 중소기업 육성자금(운전_혁신창업사업화기업),50000만원,고정금리,은행금리,5년,2년,3년,균등분할상환,...,Y,,1,대출상품,,,,연중 수시(자금 소진시까지),정책자금,202502010700
2,202110,391,경기도 중소기업 육성자금(운전_성장디딤돌 기업),50000만원,-,은행금리,5년,2년,3년,균등분할상환,...,Y,,1,대출상품,,,,연중 수시(자금 소진시까지),정책자금,202502010700
3,202110,392,금융기관 특별출연 협약보증,80000만원,-,-,5(시설자금: 5년 초과 가능),-,-,-,...,Y,,1,대출상품,,,,2011.03.14 ~ 자금소진시 또는 사업종료시,정책자금,202502010700
4,202110,393,경기도 취약 소상공인 자금(경영개선자금),2000만원,-,4.15%,5년,0년,5년,원리금균등분할상환,...,N,,1,대출상품,,,,2022.04.11 ~ 자금 소진 시까지,정책자금,202502010700
5,202110,394,경기도 취약 소상공인 자금(특별지원자금),5000만원,-,4.15%,5년,0년,5년,원리금균등분할상환,...,N,,1,대출상품,,,,2022.04.11 ~ 자금 소진 시까지,정책자금,202502010700
6,202110,395,일반경영안정자금(창업초기자금),7000만원,,-,5년,2년,3년,,...,N,,1,대출상품,,,,상시,정책자금,202502010700
7,202110,396,일반경영안정자금(여성가장 지원),7000만원,,-,5년,2년,3년,,...,N,,1,대출상품,,,,상시,정책자금,202502010700
8,202110,397,일반경영안정자금(사업전환자금),10000만원,,-,5년,2년,3년,,...,N,,1,대출상품,,,,상시,정책자금,202502010700
9,202110,398,북구 디딤돌 특례보증,2000만원,,-,5년,1년,4년,원금균등분할상환,...,N,,1,대출상품,,,,2022.02.18.~ 소진시,정책자금,202502010700
10,202110,399,생활안정자금 융자(자녀양육비),1000만원,고정금리,1.5%,"4, 5년",1년,"3, 4년",원금균등분할상환,...,Y,,1,대출상품,,,,2023. 1. 5.(목)부터 사업마감일(별도공지)까지,정책자금,202502010700
11,202110,400,2023년 남구 소상공인 경영안정자금 지원 특례보증,2000만원,-,특정금리,"2,5년",2년,3년,"만기일시상환, 원금균등분할상환",...,Y,,1,대출상품,,,,한도 소진 시까지,,202502010700
12,202110,401,2023년 달성군 소상공인 경영안정자금 지원 특례보증,3000만원,-,특정금리,"2,5년",2년,3년,"만기일시상환, 원금균등분할상환",...,Y,,1,대출상품,,,,한도 소진 시까지,,202502010700
13,202110,402,대구굴기 특별보증,20000만원,-,특정금리,5년,"1,2년","3,4년","만기일시상환, 원금균등분할상환",...,Y,,1,대출상품,,,,한도 소진 시까지,,202502010700
14,202110,403,대구스타트업 리더스펀드 협약보증,40000만원,-,특정금리,5년,1년,4년,"만기일시상환, 원금균등분할상환",...,Y,,1,대출상품,,,,한도 소진 시까지,,202502010700
15,202110,404,보은군 소상공인지원자금,5000만원,변동금리,은행금리 - 2%,3년,-,-,일시상환,...,Y,,1,대출상품,,,,,,202502010700
16,202110,405,북구 청년창업 특례보증,3000만원,-,특정금리,"2,5년",2년,3년,"만기일시상환, 원금균등분할상환",...,Y,,1,대출상품,,,,한도 소진 시까지,,202502010700
17,202110,406,은행동행론,1500만원,고정금리,2~4%,5년,-,5년,원리금균등분할상환,...,Y,,1,대출상품,,,,상시,,202502010700
18,202110,407,증평군 소상공인지원자금,5000만원,변동금리,은행금리 - 3%,3년,-,-,일시상환,...,Y,,1,대출상품,,,,,,202502010700
19,202110,408,전세사기 피해자 전용 디딤돌대출,40000만원,"고정금리, 변동금리",1.85~2.70%,"10, 15, 20, 30년","0, 1, 2, 3년",-,"원(리)금균등분할상환, 체증식분할상환",...,Y,,1,대출상품,,,,상시,,202502010700
20,202110,409,전세피해 임차인 버팀목 대출,24000만원,변동금리,1.2~2.7%,2년,2년,0년,만기일시 또는 혼합상환,...,Y,,1,대출상품,,,,상시,,202502010700
21,202110,410,전세피해 임차인 버팀목 대출(대환),40000만원,변동금리,1.2~2.7%,6개월,6개월,0년,만기일시,...,Y,,1,대출상품,,,,상시,,202502010700
22,202110,411,비정상거처 이주지원 버팀목대출,"공공 50만원, 그 외 8,000만원",변동금리,"5천만원한도 0, 5천만원초과 1.2~1.8",2년,2년,0년,만기일시,...,Y,,1,대출상품,,,,상시,,202502010700
23,202110,412,전세사기 피해자 최우선 변제금 전세자금 대출,24000만원,변동금리,1.2~3.0%,2년,2년,0년,만기일시,...,Y,,1,대출상품,,,,상시,,202502010700
24,202110,413,창업시설 조성자금,총사업비의 70% (단 융자한도 감액기준 해당 시 40~60%),변동금리,1.5~1.9%,"7년(최장12년) (상환, 거치)",7년,-,"만기일시상환, 원리금(원금) 균등분할상환",...,Y,,1,대출상품,,,,,,202502010700
25,202110,414,공동협업공간 조성자금,총사업비의 70~80% (단 융자한도 감액기준 해당 시 40~60%),변동금리,1.5~1.9%,"7년(최장12년) (상환, 거치)",7년,-,"만기일시상환, 원리금(원금) 균등분할상환",...,Y,,1,대출상품,,,,,,202502010700
26,202110,415,임대상가 조성자금,총사업비의 80% (단 융자한도 감액기준 해당 시 50~70%),변동금리,1.5~1.9%,"7년(최장12년) (상환, 거치)",7년,-,"만기일시상환, 원리금(원금) 균등분할상환",...,Y,,1,대출상품,,,,,,202502010700
27,202110,416,상가 리모델링자금,총사업비의 70~80% (단 융자한도 감액기준 해당 시 40~60%),변동금리,1.5~1.9%,"7년(최장12년) (상환, 거치)",7년,-,"만기일시상환, 원리금(원금) 균등분할상환",...,Y,,1,대출상품,,,,,,202502010700
28,202110,417,저소득주민 생활안정융자금 대출 (주거보증금),1000만원,고정금리,1%,5년,1년,4년,균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
29,202110,418,중소기업육성자금(벤처.지식산업지원자금),"(시설) 50,000(운전) 20,000",고정금리,1.8%,시설 5년운전 2년,2년,시설 3년,- 시설자금 : 2년 거치 3년균분상환 - 운전자금 : 일시상환,...,Y,,1,대출상품,,,,,,202502010700
30,202110,419,군산 산업위기대응특별지역 지원 특례보증,19900만원,고정금리,3.06%,5년,"0, 1년",5년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
31,202110,420,서민금융회사 상생협력 협약보증,5000만원,-,대출실행 은행에 문의,"1, 8년",1년,7년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
32,202110,421,수출유망 소상공인 지원 특례보증(수출 두드림 기업 지원),7000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700
33,202110,422,수출유망 소상공인 지원 특례보증(일반 수출기업 지원),7000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700
34,202110,423,스마트 소공인 육성 협약보증(하나은행),10000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700
35,202110,424,스마트소공인 육성 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
36,202110,425,"온(溫, ON)택트 특례보증",2850만원,변동금리,대출실행 은행에 문의,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
37,202110,426,위기업종 지원 협약보증,5000만원,-,-,"1, 5년",1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
38,202110,427,익산시 소상공인 특례보증(2023 하나은행 출연),5000만원,고정금리,약 1.6%,5년,1년,4년,원금균등분할상환,...,Y,,1,대출상품,,,,,,202502010700
39,202110,428,중소벤처기업부 소상공인자금,7000만원,자금별 별도금리 적용,-,5년,2년,3년,분할상환,...,Y,,1,대출상품,,,,,,202502010700
40,202110,429,착한가격업소 활성화 지원 특별보증,2000만원,-,-,5년,-,-,-,...,Y,,1,대출상품,,,,,,202502010700

In [83]:
for item in soup2.select("item"):
    for tags in item:
        print(tags.name)
        # 개행이 None으로 출력되어 예외처리 필요

None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None
housHoldCnt
None
housAr
None
lnTgtHous
None
rfrcCnpl
None
grnInst
None
jnMthd
None
rpymdCfe
None
lnIcdcst
None
ovItrYr
None
prftAddIrtCond
None
etcRefSbjc
None
hdlInst
None
cnpl
None
rltSite
None
tgtFltr
None
hdlInstDtlVw
None
prdExisYn
None
cv19Rfrc
None
prdCtg
None
prdNm
None
cv19SuprCtg
None
cv19SuprCtn
None
cv19SuprTgtDtlCtn
None
mgmDln
None
prdCtg2
None
fileWrtDt
None
None
basYm
None
snq
None
finPrdNm
None
lnLmt
None
irtCtg
None
irt
None
maxTotLnTrm
None
maxDfrmTrm
None
maxRdptTrm
None
rdptMthd
None
usge
None
trgt
None
instCtg
None
ofrInstNm
None
rsdAreaPamtEqltIstm
None
suprTgtDtlCond
None
age
None
incm
None
rsdArea
None
crdtSc
None
anin
None