# 정적 웹피이지 수집하기
* 순수 HTML, CSS로 만들어진 페이지
* javascript로 내용을 갱신하지 않는 페이지

In [8]:
import requests
from bs4 import BeautifulSoup as bs

In [9]:
url = 'https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber=1&pageSize=24'
r = requests.get(url)
r = r.text

In [10]:
soup = bs(r, 'lxml')
soup

<!DOCTYPE html>
<html lang="ko">
<head><link content="IE=Edge" href="https://m.yes24.com/Home/Best?DispNo=001" http-equiv="X-UA-Compatible" media="only screen and(max-width: 640px)" rel="alternate"/>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type"/>
<meta content="dpr, width, viewport-width, rtt, downlink, ect, UA, UA-Platform, UA-Arch, UA-Model, UA-Mobile, UA-Full-Version" http-equiv="Accept-CH"/>
<meta content="86400" http-equiv="Accept-CH-Lifetime"/>
<meta content="unsafe-url" name="referrer"/>
<meta content="width=1170" name="viewport"/>
<title> 국내도서 종합 베스트 - 예스24 </title>
<meta content="예스24" name="title"/>
<meta content="YOUR EVERY STORY 문화 콘텐츠 플랫폼, 예스24" name="description"/>
<meta content="인터넷 서점, 온라인 쇼핑, 상품 추천, 쇼핑몰, 상품 검색, 도서 정보, 국내도서, 외국도서, 전자책, eBook, 이북, 크레마, 공연, 콘서트, 뮤지컬, 음반, 예매, DVD, 블루레이, 예스24, YES24, 교보문고, 알라딘, 리센스, 예스24 도서용품, 친환경 PB 브랜드, 사은품, 굿즈" name="keywords"/>
<link href="//www.yes24.com/OpensearchDescription.xml" rel="search" title="YES24" type="application/opensearchdescription+xml"/>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/m/common/xds.min.js?v=20210909" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery-1.12.4.min.js" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.menu-aim.js?v=20220321" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.easing.1.3.min.js?v=20220321" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/util.js?v=20240626b" type="text/javascript"></script>
<script charset="euc-kr" src="https://www.yes24.com/JavaScript/Yes_header.js?v=20250317" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/hiveSlide.js?v=20240321a" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/jqueryExtends.js?v=20240321a" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/recentviewgoods.js?v=20250317" type="text/javascript"></script>
<script src="https://www.yes24.com/Javascript/Search/bulletSearch.js?v=20250317" type="text/javascript"></script>
<script src="https://www.yes24.com/24/Scripts/YES24.Common-1.6.js?v=20250317" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/common/RedirectWebSiteList.min.js?v=20250317" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/common/RedirectWebSite.min.js?v=20250317" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/d/scl/simplebar.js?v=20240222" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/jquery/jquery.lazyload.min.1.9.7.js?v=20220321" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/p/ui/openinside.pack.js?v=20250317" type="text/javascript"></script>
<link charset="euc-kr" href="https://image.yes24.com/sysimage/yesUI/hack/Newstyle.css?v=20211122a" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/hack/renewHack.css?v=20240614" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/yesCom.css?v=20250107" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesHeaderN4.css?v=20240920" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/yesFooterN4.css?v=20250313" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/wideLayout.css?v=20240229" rel="stylesheet" type="text/css"/>
<link href="https://image.yes24.com/sysimage/yesUI/layout/simplebar.css?v=20240222" rel="stylesheet" type="text/css"/>
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="https://image.yes24.com/sysimage/yesUI/hack/renewHack_ie.css?v=20240614" />
	<![endif]-->
<link href="https://image.yes24.com/sysimage/renew/gnb/favicon_n.ico" rel="shortcut icon" type="image/x-icon"/>
<script type="text/javascript">
		var YesData = new function() {
			var _HTTP_URL = "https://www.yes24.com";
			var _BLOG_URL = "https://blog.yes24.com/";
			var _IMG_HOST_IMG = "https://image.yes24.com";
			var _IsWelcomePage = "False";
			var _MEM_AGE = 0;
			var _PID = "";
			var _ParenerInfomagion ={};
			var _NOW_HTTP_URL = "https://www.yes24.com";
			var _IsdevServer = "False";
			var _IsHttps = "True";

			this.HTTP_URL = function(){return _HTTP_URL;}
			this.NOW_HTTP_URL = function(){return _NOW_HTTP_URL;}
			this.BLOG_URL = function(){return _BLOG_URL;}
			this.IMG_HOST_IMG = function(){return _IMG_HOST_IMG;}
			this.IsHttps = function(){return _IsHttps;}
			this.IsWelcomePage = function(){return _IsWelcomePage;}
			this.MEM_AGE = function(){return _MEM_AGE;}
			this.PID = function(){return _PID;}
			this.ParenerInfomagion = function(){return _ParenerInfomagion;}
			this.IsdevServer = function(){return _IsdevServer;}
		}

		$(document).ready(function () {

		});//ready

		// 최근본 상품
		var recentViewGoods = new RecentViewGoods();

		// 광고창을 계속 불러올지 여부
		var SearchBarRenderingEnable = true;

		// dfinery 디파이너리 위한 설정 값
		var USERNO = '';
		var IS_NATIVE_APPS = false;
		var is_debug = Boolean(1);

	    // 스크립트 참조 여부 설정 값
	    var scToday = new Date().getFullYear() + "-" + ('0' + (new Date().getMonth() + 1)).slice(-2) + "-" + ('0' + (new Date().getDate())).slice(-2);
	    var scExpDate = "2023-07-06";   // 스크립트 참조 만료일 지정
	    var IsScExpDate = scToday > scExpDate ? false : true;
    </script>
<script src="https://www.yes24.com/javascript/common.js?v=20250319" type="text/javascript"></script>
<script src="https://www.yes24.com/JavaScript/headerSetting.js?v=20250103" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/clickstream.min.js?v=20211110" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfinery.min.js?v=20240329" type="text/javascript"></script>
<script src="https://image.yes24.com/sysimage/Contents/Scripts/c/logging/dfineryHelper.js?v=20240329" type="text/javascript"></script>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager -->
<script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-WM4K93V');
    </script>
<!-- End Google Tag Manager -->
<!-- RTB HOUSE 메인 태깅 코드 -->
<script>
	    (function(w,d,dn,t){w[dn]=w[dn]||[];w[dn].push({eventType:'init',value:t,dc:'asia'});
	    var f=d.getElementsByTagName('script')[0],c=d.createElement('script');c.async=true;
	    c.src='https://tags.creativecdn.com/ld87UMn0bZ6wjXtzlyVc.js';
	    f.parentNode.insertBefore(c,f);})(window,document,'rtbhEvents','ld87UMn0bZ6wjXtzlyVc');
	    (rtbhEvents = window.rtbhEvents || []).push({});
    </script>
<!-- End RTB HOUSE 메인 태깅 코드 -->
<link href="https://image.yes24.com/sysimage/yesUI/yesUI.css?v=20250317" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/layout/pcBase.css?ver=20241218_a" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/best/best.css?ver=20250116" media="all" rel="stylesheet" type="text/css"/><link href="https://image.yes24.com/sysimage/yesUI/yesLocation.css?ver=20210823" media="all" rel="stylesheet" type="text/css"/></head>
<body>
<!-- 광고 스크립트 - 공통 -->
<!-- Google Tag Manager (noscript) -->
<noscript>
<iframe height="0" src="https://www.googletagmanager.com/ns.html?id=GTM-WM4K93V" style="display:none;visibility:hidden" width="0"></iframe>
</noscript>
<!-- End Google Tag Manager (noscript) -->
<dl id="yesSkip">
<dt>콘텐츠 바로가기</dt>
<dd><a href="#wrapperContent">본문 바로가기</a></dd>
</dl>
<hr/>
<!-- !!!!!!!!!!########## 전체 페이지 영역 시작 ##########!!!!!!!!!! -->
<div class="" id="yesWrap">
<div id="yesHeaderArea" style="">
<!-- ########## TOPBANNER 영역 시작 ########## -->
<section>
<div id="upperBnWrap" style="display:none;">
<div id="upperBnRoll">
<div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#c0deff"><a href="https://event.yes24.com/onlyApp" onclick="setWcode('001');"><img alt="도서앱" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0326_topbn_480x50_L_01.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#e0fbbd"><a href="https://event.yes24.com/present?eventNo=257315" onclick="setWcode('001');"><img alt="북커버북팩" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0326_topbn_480x50_R_01.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#d5c9fa"><a href="https://event.yes24.com/yesBenefit" onclick="setWcode('001');"><img alt="4월혜택" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0326_topbn_480x50_L_02.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#f2eab4"><a href="https://event.yes24.com/present?eventNo=257315" onclick="setWcode('001');"><img alt="북커버북팩" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0326_topbn_480x50_R_01.png" width="480"/></a></div>
</div>
</div><div class="upperBnSet" style="display:none;">
<div class="upperBnArea">
<div class="upperBnSetLft" style="background-color:#fb6aed"><a href="https://event.yes24.com/Anniversary26" onclick="setWcode('001');"><img alt="창립" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0326_topbn_480x50_L_03.png" width="480"/></a></div>
<div class="upperBnSetRgt" style="background-color:#fbd3f7"><a href="https://event.yes24.com/present?eventNo=257315" onclick="setWcode('001');"><img alt="북커버북팩" height="50" src="https://image.yes24.com/images/01_Banner/welcome/topBanner/2025/0326_topbn_480x50_R_01.png" width="480"/></a></div>
</div>
</div>
</div>
<div class="upperClose"><a href="javascript:void(0);" onclick="hideUpperBn();"><em class="yBlind">TOP BANNER 닫기</em></a></div>
</div>
</section>
<script type="text/javascript">
		function hideUpperBn() {
			setWcode('001_001');
			var todayDate = new Date();
			setCookie("UPPER_BN_SHOW", "OK", 1); // 오른쪽 숫자는 쿠키를 유지할 기간(day)을 설정합니다
			$("#upperBnWrap").css("display", "none");
		}

		if (getCookie("UPPER_BN_SHOW") == "") {
			$("#upperBnWrap").css("display","");
		}
		$('#upperBnRoll .upperBnSet').eq( Math.floor(Math.random()*$("#upperBnRoll .upperBnSet").length) ).show();

		//SSL 페이지에서 접근시 Top Banner 영역 제거
		if(location.href.indexOf("https://ssl.yes24.com/")> -1) {
			$("#upperBnWrap").remove();
		}
	</script>
<!-- ########## TOPBANNER 영역 끝 ########## -->
<!-- ########## HEADER 영역 시작 ########## -->
<div id="yHeader">
<h1><a class="logo" href="https://www.yes24.com/main/default.aspx" onclick="setWcode('001_004');"><svg aria-label="YES24" role="img" type="image/svg+xml"><image alt="YES24" height="103" src="https://image.yes24.com/sysimage/renew/gnb/logoN4.png" width="200" xlink:href="https://image.yes24.com/sysimage/renew/gnb/logoN4.svg" xmlns:xlink="http://www.w3.org/1999/xlink"/></svg></a></h1>
<div id="yHeaderWrap">
<!-- %%%%%%%%%% 해더 Top 영역 시작 %%%%%%%%%% -->
<div class="yHeaderTop">
<h2 class="yBlind">YES24 카테고리 리스트</h2>
<ul class="cateLi" id="ulCategoryList"><li class="cate001 cateOn"><a href="https://www.yes24.com/Mall/Main/Book/001?CategoryNumber=001" onclick="setWcode('001_002_001')" title="국내도서"><em class="txt">국내도서</em></a></li><li class="cate002"><a href="https://www.yes24.com/Mall/Main/Foreign/002?CategoryNumber=002" onclick="setWcode('001_002_002')" title="외국도서"><em class="txt">외국도서</em></a></li><li class="cate018"><a href="https://www.yes24.com/Mall/Main/used/018?CategoryNumber=018" onclick="setWcode('001_002_011')" title="중고샵"><em class="txt">중고샵</em></a></li><li class="cate017"><a href="https://www.yes24.com/Mall/Main/eBook/017?CategoryNumber=017" onclick="setWcode('001_002_003')" title="eBook"><em class="txt">eBook</em></a></li><li class="cateCrC"><a href="https://cremaclub.yes24.com/BookClub/Main" onclick="setWcode('001_002_016')" title="크레마클럽"><em class="txt">크레마클럽</em><em class="ico_newSup"></em></a></li><li class="cate003"><a href="https://www.yes24.com/Mall/Main/Music/003?CategoryNumber=003" onclick="setWcode('001_002_005')" title="CD/LP"><em class="txt">CD/LP</em></a></li><li class="cate004"><a href="https://www.yes24.com/Mall/Main/Dvd/004?CategoryNumber=004" onclick="setWcode('001_002_006')" title="DVD/Blu-ray"><em class="txt">DVD/BD</em></a></li><li class="cate006"><a href="https://www.yes24.com/Mall/Main/Gift/006?CategoryNumber=006" onclick="setWcode('001_002_009')" title="GIFT"><em class="txt"><u>문구</u>/GIFT</em></a></li><li class="cateENT"><a href="http://ticket.yes24.com" onclick="setWcode('001_002_008')" target="_blank" title="티켓"><em class="txt">티켓</em><em class="ico_newW bgGNB">새창이동</em></a></li></ul>
<h2 class="yBlind">YES24 유틸메뉴</h2>
<ul class="utilLi">
<li id="LoginText">
<input id="hdfLoginYn" type="hidden" value="N"/>
<a href="https://www.yes24.com/Templates/FTLogin.aspx" onclick="setWcode('001_003_001')"><em class="txt">로그인</em></a>
</li>
<li><a href="https://www.yes24.com/Member/Join/Accept.aspx" onclick="setWcode('001_003_003')">회원가입</a></li>
<li class="myPgGrp">
<a href="javascript:void(0);" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrD bgGNB">하위메뉴보기</em></a>
<dl class="myPgDl">
<dt><a href="https://www.yes24.com/Member/FTMypageMain.aspx" onclick="setWcode('001_003_013')"><em class="txt">마이페이지</em><em class="ico_arrU bgGNB">이동</em></a></dt>
<dd>
<ul>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_004')">주문내역	 </a></li>
<li><a href="https://www.yes24.com/Member/FTGoMyBlog.aspx?type=list" onclick="setWcode('001_003_005')" target="_blank">마이리스트   </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESPoint.aspx" onclick="setWcode('001_003_006')">YES포인트    </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_1YESMoney.aspx" onclick="setWcode('001_003_007')">YES머니      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_3GiftCard.aspx" onclick="setWcode('001_003_014')">YES상품권      </a></li>
<li><a href="https://www.yes24.com/Templates/FTMyAccount_4Coupon.aspx" onclick="setWcode('001_003_008')">쿠폰         </a></li>
<li><a href="https://www.yes24.com/Member/MyPage_reconfirmPW.aspx" onclick="setWcode('001_003_009')">회원정보     </a></li>
</ul>
</dd>
</dl>
</li>
<li><a href="https://ssl.yes24.com/Cart/Cart" onclick="setWcode('001_003_010')"><em class="txt">카트</em></a></li>
<li><a href="https://ssl.yes24.com/MyPageOrderList/MyPageOrderList" onclick="setWcode('001_003_011')"><em class="txt">주문/배송</em></a></li>
<li class="lastLi"><a href="https://www.yes24.com/Templates/FTCusMain.aspx?Wcode=001_003_012" onclick="setWcode('001_003_012')"><em class="txt">고객센터</em></a></li>
</ul>
<dl class="globalYesInfoDl">
<dt><a href="javascript:void(0);"><em class="txt">Global YES24</em><em class="ico_arr bgGNB">안내보기</em></a></dt>
<dd>
<div class="globalYesInfoContArea">
<div class="globalYesInfoCont">
<p class="yesInfo_tit">Global YES24는?</p>
<p class="yesInfo_des">
									K-POP/K-Drama 관련상품(음반,도서,DVD)을<br/> 영문/중문 으로 이용하실 수 있습니다.
								</p>
<div class="yesInfo_globalTxt">
<p class="globalTxt_des">
										Korean wave shopping mall, sell the <br/>K-POP/K-Drama (CD,DVD,Blu-ray,Book)
										We aceept PayPal/UnionPay/Alipay<br/> and support English/Chinese Language service
									</p>
<a class="btnC btn_blue" href="https://global.yes24.com" onclick="setWcode('001_016_002')" target="_blank"><span class="bWrap"><em class="txt">English</em></span></a>
<p class="globalTxt_des">
									 作为出售正规 K-POP/K-Drama 相关(CD,图书,DVD) 韩流商品的网站, 支持 中文/英文 等海外结账方式
									</p>
<a class="btnC btn_blue" href="https://cn.yes24.com" onclick="setWcode('001_016_003')" target="_blank"><span class="bWrap"><em class="txt">中文</em></span></a>
<p class="globalTxt_des">
									 Exclusive ticket sales for domestic and international pop artists
									</p>
<a class="btnC btn_blue" href="http://ticket.yes24.com/English?Gcode=009_205" onclick="setWcode('001_016_004')" target="_blank"><span class="bWrap"><em class="txt">Global yesticket</em></span></a>
</div>
</div>
</div>
</dd>
</dl>
</div>
<!-- %%%%%%%%%% 해더 Top 영역 끝 %%%%%%%%%% -->
<hr/>
<!-- %%%%%%%%%% 해더 Mid 영역 시작 %%%%%%%%%% -->
<div class="yHeaderMid">
<div class="yesSearch">
<form accept-charset="utf-8" action="//www.yes24.com/product/search?" id="yesSForm" method="get" name="HeadForm" onsubmit="return check_search();">
<input id="keywordAd" name="keywordAd" type="hidden" value=""/>
<input id="keyword" name="keyword" type="hidden"/>
<input id="domain" name="domain" type="hidden" value="ALL"/>
<input id="qdomain" name="qdomain" type="hidden" value="전체"/>
<fieldset>
<legend>검색</legend>
<span class="schIpt">
<label><input accesskey="s" autocomplete="off" class="iptTxt" id="query" maxlength="80" name="query" onblur="blurSearchBar();" onfocus="showLatestSearchList();" onkeydown="SearchBarRenderingEnableSet(false);init_searchbox();" onmousedown="SearchBarRenderingEnableSet(false);Common_init_searchbox();" style="ime-mode: active;" title="YES24 검색어 입력" type="text" value=""/></label>
</span>
<div style="position:absolute;top:-1000em;left:0;width:1px;height:1px;overflow:hidden;">
<script charset="euc-kr" src="//adgirl.yes24.com/RealMedia/ads/adstream_mjx.ads/www.yes24.com/Header/SearchBar@x01" type="text/javascript"></script>
<script type="text/javascript">
							try {
								OAS_RICH("x01");
							} catch (e) { }
						</script>
</div>
<script type="text/javascript">
						var url = location.href;
						var reUrl = url.toLowerCase();

						$(document).ready(function () {
							//검색결과
						    if (reUrl.indexOf('/product/search') > -1 && reUrl.indexOf('/product/search/searchkeyword') <= 0) {
								SearchBarRenderingEnable = false;

								if (getParamValue("query") != undefined) {
									$("#query").val($("#hidSearchWord").val());
									fnGetValueDomain($("#hidSearchDomain").val());
									$("#domain").val($("#hidSearchDomain").val());
									$("#qdomain").val($("#hidSearchQdomain").val());
								}
							}
							if (SearchBarRenderingEnable == true) {
								fnSearchBarRendering();
							}
						});

						// 검색어 입력창에 포커스 시
						function SearchBarRenderingEnableSet(enable) {
							//광고 제거
							SearchBarRenderingEnable = enable;
							$("#ulSchScopeOpt").hide();
						}

						// 검색어 입력창 광고 노출
						function fnSearchBarRendering() {
							var seardtext = $('#hdSearchBarText').val();
							var bannerLink = $("#hdSearchBarLink").val();

							$('#query').val(seardtext);
							$('#query').addClass("iptTxt iptTxtAd");
							$('#keywordAd').val(bannerLink);
						}

						//검색창 선택 시
						function showLatestSearchList() {
							SearchBarRenderingEnableSet(false);
							if (String($("input#query").val()).length == 0) {
								try{
									srchHistory.show();
								}catch(e){}
								$("#suggestSearchList").hide();
								$("#searchKeyLayer").show();
								$("#latestSearchList").show();
							} else {
								BulletSearchRenewal.InitBulletSearch();
								showSuggestSearchList();
							}
						}

						//검색창 포커스 아웃
						function blurSearchBar() {
							var queryValue = $("#query").val();
							if (queryValue == "" || queryValue == null) {

In [11]:
soup.select_one('span.gd_nameE').text

'AI 시대의 실용적 생존 가이드'

In [12]:
soup.select("#yesBestList > li")[0].text

'\n\n\n\n\n1\n\n위 상승\n\n\n\n\n\n\n\n\n\n\n\n\n\n미리보기\n\n\n\n\n\n\n[도서]\n단 한 번의 삶\n[ 양장 ]\n단 한 번의 삶 새창이동\n\n\n\n김영하 저\r\n                            \n복복서가\n2025년 04월\n\n\n구매혜택\n\n만년필용 노트+커버+스티커 세트/케이블 파우치(포인트 차감)\n\n\n\n10%\n15,120원\n16,800원\n포인트적립840원\n\n\n\r\n                                판매지수 224,271\r\n                            \n\n회원리뷰(7건)\n\n\n리뷰 총점8.9\n\n\n정보 더 보기/감추기\n\n\n\n\n\xa0종이책 리뷰 (1건)\n\xa0eBook 리뷰 (0건)\n\xa0종이책 한줄평 (6건)\n\xa0eBook 한줄평 (0건)\n\n\n\n\n\n\n\n\n\n#인생이야기\n\n\n#사유와감성\n\n\n#작가의에세이\n\n\n\n\n이벤트\n사은품\n『단 한 번의 삶』 - 영하의 무물 소책자\n(25.03.24 ~ 00.12.31)\n\n\n\n\n\n\n\n\n\n\n수량감소\n수량증가\n\n\n카트에 넣기\n바로구매\n리스트에 넣기\n\n\n\n'

In [16]:
for title in soup.select("a.gd_name"):
    print(title.text)

단 한 번의 삶
듀얼 브레인
어른의 품격을 채우는 100일 필사 노트
소년이 온다
성적 초격차를 만드는 독서력 수업
어른의 행복은 조용하다
내면소통 명상수업
모순
별별 직업 상담소
초역 부처의 말
여학교의 별 4
넥서스
하루 한 장 나의 어휘력을 위한 필사 노트
2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상
그릿 GRIT
별에게
2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하
행동하지 않으면 인생은 바뀌지 않는다
급류
스토너
2025 제16회 젊은작가상 수상작품집
2025 헝그리스포츠 7일 완성 생활스포츠지도사 2급 필기
작별하지 않는다
ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC

In [23]:
rating_list = soup.select("rating_grade.yes_b")
rating_list

[]

In [25]:
price_list = soup.select("div.info_row.info_price em.yes_b")
price_list

[<em class="yes_b">15,120</em>,
 <em class="yes_b">18,900</em>,
 <em class="yes_b">18,000</em>,
 <em class="yes_b">13,500</em>,
 <em class="yes_b">17,820</em>,
 <em class="yes_b">16,020</em>,
 <em class="yes_b">25,200</em>,
 <em class="yes_b">11,700</em>,
 <em class="yes_b">14,220</em>,
 <em class="yes_b">16,020</em>,
 <em class="yes_b">7,650</em>,
 <em class="yes_b">25,020</em>,
 <em class="yes_b">21,420</em>,
 <em class="yes_b">14,850</em>,
 <em class="yes_b">16,920</em>,
 <em class="yes_b">15,120</em>,
 <em class="yes_b">14,400</em>,
 <em class="yes_b">15,210</em>,
 <em class="yes_b">12,600</em>,
 <em class="yes_b">15,120</em>,
 <em class="yes_b">6,930</em>,
 <em class="yes_b">27,900</em>,
 <em class="yes_b">15,120</em>,
 <em class="yes_b">17,820</em>]

# 네이버 도서 추출하기
* 제목, 저자, 출판사, 출간일, 평점 및 개수, 도서 가격, e북 가격 수집

In [30]:
import time
import requests
from bs4 import BeautifulSoup as bs

In [49]:
url = 'https://search.shopping.naver.com/book/search?'
headers = {'cookie':'NNB=WIZI75NE765WO; NSCS=1; tooltipDisplayed=true; NFS=2; ba.uuid=a3902156-1942-486e-b888-8b3ef110105b; ASID=af7da55d000001953b62ba180000006b; NaverSuggestUse=use%26unuse; SHP_BUCKET_ID=9; NAC=qmArBgQfAtN0B; nid_inf=1935310690; NID_AUT=Qf1cwdmM6d+WoZOc8YyVc1wUghzeDkK8Kke1+xeHe7TcXl2dn+QNWdVqt7mwcOpF; NID_JKL=AJS3Zh1d0IKTDm4UcfsX8K5FTFg+Ffp5HMXOJiWrqrk=; NACT=1; SRT30=1743639306; NID_SES=AAABnvOpyKSOW+Pz46b1z5ZJDlnX2HZxb7xVIgL0JvGGObI0Fn5nyw4NbC+9iQSr/LokhqRZMUXeUOE251Mnap0HF3KNVPomJir6wdXd/3f2PKSgNhOMYcy18HRgD7uj4K+3/+uZfdztyrBqNHV+oySIetjFDYYAmCVZxgRUFKtnl27PuQxqKJk/67ZZlODh4d6CIiCS3sTSXmDS8xChyVFk57eBHJQtjIDlvj0PFN6O9XjR3GsjTHnFGYe+5aPMXn9c6b9oJJFM8CPS9oXfzrUBdU22ZFLcxg+LYvo0zBjZ0I0SS2PluS7lWHgfuiO5/AerP++1ZSp1qPUtsJfs3YV6zEBZkKbbxq3RpEEzsmKC0/AyK0SkKbS3Fs1j18/KveQOB9xEzA6xDVUsYwYTRzIO6sQ8LcMGCB18WDkq4ptx6sk9nNNBzzBszhJuEwBpZQw31gOHS0nE1G/B4w/2k/5tQRXzw0FpmCN4O9a7eLWa68YmbFqHqjI5lXzpN3wmPYV89oDq8PHakkmdYjQ5Vz/DLfRsQvrhwDCbFnx4Ma7Jzxzg; page_uid=i+3WllpzLi0ssBmkVd8ssssssf4-138111; sus_val=aUcQIWiH+BAaRmR57IQ2Gnwh; SRT5=1743646951; BUC=7PBNEO-OpA414Pn3Zcd-FF1_upRi-1DcP_2qQveDVuc=', 'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Whale/4.30.291.11 Safari/537.36'}

payload = dict(bookTabType='ALL', pageIndex=1, pageSize=40, prevQuery='%EB%84%A4%EC%9D%B4%EB%B2%84%EB%8F%84%EC%84%9C%20%ED%8C%8C%EC%9D%B4%EC%8D%AC', query='파이썬', sort='REL')


r = requests.get(url, params=payload, headers=headers)
r = r.content

soup = bs(r, 'lxml')
soup

<!DOCTYPE html>

In [50]:
print(soup.select_one("div.bookListItem_text_area__6gSV2").text)

컴퓨터/IT 111위혼자 만들면서 공부하는 파이썬 (37개 라이브러리와 API로 보고서, 차트, 게임, 맵, AI 챗봇 만들기|저자 직강 유튜브 강의, 오픈 채팅 제공)저자문현일출판한빛미디어2025.02.14.평점5.0 (4)

# yes24 베스트셀러 자료 수집하기
* 도서명, 저자, 출판사, 출간일, 가격, 회원리뷰점수, 회원리뷰 건수, handshake error

In [205]:
url = 'https://www.yes24.com/product/category/bestseller'
payload = dict(categoryNumber='001', pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
soup = bs(r.content, 'lxml')

In [96]:
soup.select_one('span.authPub.info_auth a').text

'김영하'

In [152]:
author_list = []

for item in soup.select('div.info_row.info_pubGrp'):
    print(item)
    author_list.append(item.select_one('span.authPub.info_auth a').text)

<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2598%2581%25ED%2595%2598&amp;authorNo=673&amp;author=김영하" target="">김영하</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b3%b5%eb%b3%b5%ec%84%9c%ea%b0%80&amp;query=%25EB%25B3%25B5%25EB%25B3%25B5%25EC%2584%259C%25EA%25B0%2580">복복서가</a></span>
<span class="authPub info_date">2025년 04월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2584%25A0%2520%25EB%25AA%25B0%25EB%25A6%25AD&amp;authorNo=487104&amp;author=이선 몰릭" target="">이선 몰릭</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%258B%25A0%25EB%258F%2599%25EC%2588%2599&amp;authorNo=155164&amp;author=신동숙" target="">신동숙</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%83%81%ec%83%81%ec%8a%a4%ed%80%98%ec%96%b4&amp;query=%25EC%2583%2581%25EC%2583%2581%25EC%258A%25A4%25ED%2580%2598%25EC%2596%25B4">상상스퀘어</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A2%2585%25EC%259B%2590&amp;authorNo=135500&amp;author=김종원" target="">김종원</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b2%ad%eb%a6%bcLife&amp;query=%25EC%25B2%25AD%25EB%25A6%25BCLife">청림Life</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EA%25B0%2595&amp;authorNo=341&amp;author=한강" target="">한강</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b0%bd%eb%b9%84&amp;query=%25EC%25B0%25BD%25EB%25B9%2584">창비</a></span>
<span class="authPub info_date">2014년 05월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2588%2598%25EB%25AF%25B8&amp;authorNo=488842&amp;author=김수미" target="">김수미</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b9%85%ed%94%bc%ec%8b%9c&amp;query=%25EB%25B9%2585%25ED%2594%25BC%25EC%258B%259C">빅피시</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2583%259C%25EC%2588%2598&amp;authorNo=288320&amp;author=태수" target="">태수</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%8e%98%ec%9d%b4%ec%a7%802%eb%b6%81%ec%8a%a4&amp;query=%25ED%258E%2598%25EC%259D%25B4%25EC%25A7%25802%25EB%25B6%2581%25EC%258A%25A4">페이지2북스</a></span>
<span class="authPub info_date">2024년 11월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A3%25BC%25ED%2599%2598&amp;authorNo=142070&amp;author=김주환" target="">김주환</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b8%ed%94%8c%eb%a3%a8%ec%97%94%ec%85%9c&amp;query=%25EC%259D%25B8%25ED%2594%258C%25EB%25A3%25A8%25EC%2597%2594%25EC%2585%259C">인플루엔셜</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2596%2591%25EA%25B7%2580%25EC%259E%2590&amp;authorNo=109194&amp;author=양귀자" target="">양귀자</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%93%b0%eb%8b%a4&amp;query=%25EC%2593%25B0%25EB%258B%25A4">쓰다</a></span>
<span class="authPub info_date">2013년 04월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259A%2594%25EC%258B%259C%25ED%2583%2580%25EC%25BC%2580%2520%25EC%258B%25A0%25EC%258A%25A4%25EC%25BC%2580&amp;authorNo=165803&amp;author=요시타케 신스케" target="">요시타케 신스케</a> 글그림/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B6%258C%25EB%2582%25A8%25ED%259D%25AC&amp;authorNo=118705&amp;author=권남희" target="">권남희</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%a3%bc%eb%8b%88%ec%96%b4%ea%b9%80%ec%98%81%ec%82%ac&amp;query=%25EC%25A3%25BC%25EB%258B%2588%25EC%2596%25B4%25EA%25B9%2580%25EC%2598%2581%25EC%2582%25AC">주니어김영사</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25BD%2594%25EC%259D%25B4%25EC%25BC%2580%2520%25EB%25A5%2598%25EB%2585%25B8%25EC%258A%25A4%25EC%25BC%2580&amp;authorNo=138755&amp;author=코이케 류노스케" target="">코이케 류노스케</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B0%2595%25EC%259E%25AC%25ED%2598%2584&amp;authorNo=124886&amp;author=박재현" target="">박재현</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%8f%ac%eb%a0%88%ec%8a%a4%ed%8a%b8%eb%b6%81%ec%8a%a4&amp;query=%25ED%258F%25AC%25EB%25A0%2588%25EC%258A%25A4%25ED%258A%25B8%25EB%25B6%2581%25EC%258A%25A4">포레스트북스</a></span>
<span class="authPub info_date">2024년 05월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2599%2580%25EC%2595%25BC%25EB%25A7%2588%2520%25EC%2595%25BC%25EB%25A7%2588&amp;authorNo=339854&amp;author=와야마 야마" target="">와야마 야마</a> 글그림/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2598%2584%25EC%258A%25B9%25ED%259D%25AC&amp;authorNo=250920&amp;author=현승희" target="">현승희</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%ac%b8%ed%95%99%eb%8f%99%eb%84%a4&amp;query=%25EB%25AC%25B8%25ED%2595%2599%25EB%258F%2599%25EB%2584%25A4">문학동네</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259C%25A0%25EB%25B0%259C%2520%25ED%2595%2598%25EB%259D%25BC%25EB%25A6%25AC&amp;authorNo=167623&amp;author=유발 하라리" target="">유발 하라리</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%25AA%2585%25EC%25A3%25BC&amp;authorNo=121375&amp;author=김명주" target="">김명주</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ea%b9%80%ec%98%81%ec%82%ac&amp;query=%25EA%25B9%2580%25EC%2598%2581%25EC%2582%25AC">김영사</a></span>
<span class="authPub info_date">2024년 10월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259C%25A0%25EC%2584%25A0%25EA%25B2%25BD&amp;authorNo=166709&amp;author=유선경" target="">유선경</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9c%84%ec%a6%88%eb%8d%a4%ed%95%98%ec%9a%b0%ec%8a%a4&amp;query=%25EC%259C%2584%25EC%25A6%2588%25EB%258D%25A4%25ED%2595%2598%25EC%259A%25B0%25EC%258A%25A4">위즈덤하우스</a></span>
<span class="authPub info_date">2024년 10월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25ED%2583%259C%25EC%2584%25B1&amp;authorNo=154511&amp;author=최태성" target="">최태성</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b4%ed%88%ac%ec%8a%a4%eb%b6%81+&amp;query=%25EC%259D%25B4%25ED%2588%25AC%25EC%258A%25A4%25EB%25B6%2581%2520">이투스북 </a></span>
<span class="authPub info_date">2024년 12월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A3%25BC%25ED%2599%2598&amp;authorNo=142070&amp;author=김주환" target="">김주환</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b8%ed%94%8c%eb%a3%a8%ec%97%94%ec%85%9c&amp;query=%25EC%259D%25B8%25ED%2594%258C%25EB%25A3%25A8%25EC%2597%2594%25EC%2585%259C">인플루엔셜</a></span>
<span class="authPub info_date">2025년 02월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2595%2588%25EB%2585%2595%25EB%258B%25AC&amp;authorNo=165613&amp;author=안녕달" target="">안녕달</a> 글그림
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b0%bd%eb%b9%84&amp;query=%25EC%25B0%25BD%25EB%25B9%2584">창비</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25ED%2583%259C%25EC%2584%25B1&amp;authorNo=154511&amp;author=최태성" target="">최태성</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b4%ed%88%ac%ec%8a%a4%eb%b6%81+&amp;query=%25EC%259D%25B4%25ED%2588%25AC%25EC%258A%25A4%25EB%25B6%2581%2520">이투스북 </a></span>
<span class="authPub info_date">2024년 12월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B8%258C%25EB%259D%25BC%25EC%259D%25B4%25EC%2596%25B8%2520%25ED%258A%25B8%25EB%25A0%2588%25EC%259D%25B4%25EC%258B%259C&amp;authorNo=101624&amp;author=브라이언 트레이시" target="">브라이언 트레이시</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2595%25EC%25A7%2580%25ED%2598%2584&amp;authorNo=183679&amp;author=정지현" target="">정지현</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%98%84%eb%8c%80%ec%a7%80%ec%84%b1&amp;query=%25ED%2598%2584%25EB%258C%2580%25EC%25A7%2580%25EC%2584%25B1">현대지성</a></span>
<span class="authPub info_date">2024년 11월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2595%25EB%258C%2580%25EA%25B1%25B4&amp;authorNo=173691&amp;author=정대건" target="">정대건</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%af%bc%ec%9d%8c%ec%82%ac&amp;query=%25EB%25AF%25BC%25EC%259D%258C%25EC%2582%25AC">민음사</a></span>
<span class="authPub info_date">2022년 12월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A1%25B4%2520%25EC%259C%258C%25EB%25A6%25AC%25EC%2597%2584%25EC%258A%25A4&amp;authorNo=168400&amp;author=존 윌리엄스" target="">존 윌리엄스</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%258A%25B9%25EC%259A%25B1&amp;authorNo=124618&amp;author=김승욱" target="">김승욱</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%95%8c%ec%97%90%ec%9d%b4%ec%b9%98%ec%bd%94%eb%a6%ac%ec%95%84(RHK)&amp;query=%25EC%2595%258C%25EC%2597%2590%25EC%259D%25B4%25EC%25B9%2598%25EC%25BD%2594%25EB%25A6%25AC%25EC%2595%2584(RHK)">알에이치코리아(RHK)</a></span>
<span class="authPub info_date">2015년 01월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B0%25B1%25EC%2598%25A8%25EC%259C%25A0&amp;authorNo=304055&amp;author=백온유" target="">백온유</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B0%2595%25EB%25B3%25B4%25EB%259D%25BC&amp;authorNo=344419&amp;author=강보라" target="">강보라</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%259C%25EC%259E%25A5%25EC%259B%2590&amp;authorNo=306717&amp;author=서장원" target="">서장원</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2595%25B4%25EB%2582%2598&amp;authorNo=253719&amp;author=성해나" target="">성해나</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2598%259C%25EB%25A0%25B9&amp;authorNo=368997&amp;author=성혜령" target="">성혜령</a> 저 외 2명
                                        <span class="moreAuthArea">
<span class="moreAuthBtn"><a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.cCont_listArea'),event);">정보 더 보기/감추기</a></span>
<span class="moreAuthLi">
<span class="moreAuthLiCont">
<ul>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B0%25B1%25EC%2598%25A8%25EC%259C%25A0&amp;authorNo=304055&amp;author=백온유" target="">백온유</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B0%2595%25EB%25B3%25B4%25EB%259D%25BC&amp;authorNo=344419&amp;author=강보라" target="">강보라</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%259C%25EC%259E%25A5%25EC%259B%2590&amp;authorNo=306717&amp;author=서장원" target="">서장원</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2595%25B4%25EB%2582%2598&amp;authorNo=253719&amp;author=성해나" target="">성해나</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2598%259C%25EB%25A0%25B9&amp;authorNo=368997&amp;author=성혜령" target="">성혜령</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25ED%259D%25AC%25EC%25A3%25BC&amp;authorNo=345050&amp;author=이희주" target="">이희주</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2598%2584%25ED%2598%25B8%25EC%25A0%2595&amp;authorNo=350594&amp;author=현호정" target="">현호정</a></li>
</ul>
</span>
</span>
</span>
</span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%ac%b8%ed%95%99%eb%8f%99%eb%84%a4&amp;query=%25EB%25AC%25B8%25ED%2595%2599%25EB%258F%2599%25EB%2584%25A4">문학동네</a></span>
<span class="authPub info_date">2025년 04월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25ED%2598%2584%25EA%25B7%25BC&amp;authorNo=429420&amp;author=한현근" target="">한현근</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%a7%81%ec%97%85%ec%83%81%ec%a0%90&amp;query=%25EC%25A7%2581%25EC%2597%2585%25EC%2583%2581%25EC%25A0%2590">직업상점</a></span>
<span class="authPub info_date">2025년 01월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EA%25B0%2595&amp;authorNo=341&amp;author=한강" target="">한강</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%ac%b8%ed%95%99%eb%8f%99%eb%84%a4&amp;query=%25EB%25AC%25B8%25ED%2595%2599%25EB%258F%2599%25EB%2584%25A4">문학동네</a></span>
<span class="authPub info_date">2021년 09월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=ETS&amp;authorNo=156974&amp;author=ETS" target="">ETS</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=YBM(%ec%99%80%ec%9d%b4%eb%b9%84%ec%97%a0)&amp;query=YBM(%25EC%2599%2580%25EC%259D%25B4%25EB%25B9%2584%25EC%2597%25A0)">YBM(와이비엠)</a></span>
<span class="authPub info_date">2023년 12월</span>
</div>

In [153]:
author_list

['김영하',
 '이선 몰릭',
 '김종원',
 '한강',
 '김수미',
 '태수',
 '김주환',
 '양귀자',
 '요시타케 신스케',
 '코이케 류노스케',
 '와야마 야마',
 '유발 하라리',
 '유선경',
 '최태성',
 '김주환',
 '안녕달',
 '최태성',
 '브라이언 트레이시',
 '정대건',
 '존 윌리엄스',
 '백온유',
 '한현근',
 '한강',
 'ETS']

In [99]:
publisher_list = []

for item in soup.select('span.authPub.info_pub a'):
    publisher_list.append(item.text)

In [100]:
publisher_list

['복복서가',
 '상상스퀘어',
 '청림Life',
 '창비',
 '빅피시',
 '페이지2북스',
 '인플루엔셜',
 '쓰다',
 '주니어김영사',
 '포레스트북스',
 '문학동네',
 '김영사',
 '위즈덤하우스',
 '이투스북 ',
 '인플루엔셜',
 '창비',
 '이투스북 ',
 '현대지성',
 '민음사',
 '알에이치코리아(RHK)',
 '문학동네',
 '직업상점',
 '문학동네',
 'YBM(와이비엠)']

In [102]:
publishdate_list = []

for item in soup.select('span.authPub.info_date'):
    publishdate_list.append(item.text)

In [103]:
publishdate_list

['2025년 04월',
 '2025년 03월',
 '2025년 03월',
 '2014년 05월',
 '2025년 03월',
 '2024년 11월',
 '2025년 03월',
 '2013년 04월',
 '2025년 03월',
 '2024년 05월',
 '2025년 03월',
 '2024년 10월',
 '2024년 10월',
 '2024년 12월',
 '2025년 02월',
 '2025년 03월',
 '2024년 12월',
 '2024년 11월',
 '2022년 12월',
 '2015년 01월',
 '2025년 04월',
 '2025년 01월',
 '2021년 09월',
 '2023년 12월']

In [109]:
cost_list = []

for item in soup.select('strong.txt_num'):
    cost_list.append(item.text)

In [110]:
cost_list

['15,120원',
 '18,900원',
 '18,000원',
 '13,500원',
 '17,820원',
 '16,020원',
 '25,200원',
 '11,700원',
 '14,220원',
 '16,020원',
 '7,650원',
 '25,020원',
 '21,420원',
 '14,850원',
 '16,920원',
 '15,120원',
 '14,400원',
 '15,210원',
 '12,600원',
 '15,120원',
 '6,930원',
 '27,900원',
 '15,120원',
 '17,820원']

In [130]:
reviewscore_list = []
i = 1
for item in soup.select('span.rating_grade em.yes_b'):
    reviewscore_list.append(item.text)
    if i == 10 or i == 19:
        reviewscore_list.append(None)
    i += 1

In [131]:
reviewscore_list

['9.0',
 '8.7',
 '9.9',
 '9.7',
 '9.9',
 '9.5',
 '10.0',
 '9.6',
 '10.0',
 '9.4',
 None,
 '9.4',
 '9.5',
 '9.6',
 '9.9',
 '10.0',
 '9.6',
 '9.3',
 '9.1',
 '9.3',
 None,
 '9.9',
 '9.6',
 '9.7']

In [125]:
reviewnum_list = []
i=1
for item in soup.select('em.txC_blue'):
    reviewnum_list.append(item.text)
    if i == 10 or i == 19:
        reviewnum_list.append(None)
    i += 1

In [126]:
reviewnum_list

['8',
 '37',
 '56',
 '3,845',
 '67',
 '188',
 '10',
 '1,390',
 '2',
 '348',
 None,
 '225',
 '695',
 '57',
 '42',
 '25',
 '48',
 '247',
 '263',
 '491',
 None,
 '31',
 '2,006',
 '402']

In [154]:
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs

i = 1
j = 1

name_list = []
author_list = []
publisher_list = []
publishdate_list = []
cost_list = []
reviewscore_list = []
reviewnum_list = []

for item in soup.select('a.gd_name'):  # .gd_name도 가능
    # result.setdefault("도서명", []).append(item) -> 이런 식으로 바로 딕셔너리 형성도 가능
    name_list.append(item.text)

for item in soup.select('div.info_row.info_pubGrp'):
    author_list.append(item.select_one('span.authPub.info_auth a').text)

for item in soup.select('span.authPub.info_pub a'):
    publisher_list.append(item.text)

for item in soup.select('span.authPub.info_date'):
    publishdate_list.append(item.text)
    
for item in soup.select('strong.txt_num'):
    cost_list.append(item.text)
    
for item in soup.select('span.rating_grade em.yes_b'):
    reviewscore_list.append(item.text)
    if i == 10 or i == 19:
        reviewscore_list.append('미발매')
    i += 1
    
for item in soup.select('em.txC_blue'):
    reviewnum_list.append(item.text)
    if j == 10 or j == 19:
        reviewnum_list.append('미발매')
    j += 1

<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2598%2581%25ED%2595%2598&amp;authorNo=673&amp;author=김영하" target="">김영하</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b3%b5%eb%b3%b5%ec%84%9c%ea%b0%80&amp;query=%25EB%25B3%25B5%25EB%25B3%25B5%25EC%2584%259C%25EA%25B0%2580">복복서가</a></span>
<span class="authPub info_date">2025년 04월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2584%25A0%2520%25EB%25AA%25B0%25EB%25A6%25AD&amp;authorNo=487104&amp;author=이선 몰릭" target="">이선 몰릭</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%258B%25A0%25EB%258F%2599%25EC%2588%2599&amp;authorNo=155164&amp;author=신동숙" target="">신동숙</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%83%81%ec%83%81%ec%8a%a4%ed%80%98%ec%96%b4&amp;query=%25EC%2583%2581%25EC%2583%2581%25EC%258A%25A4%25ED%2580%2598%25EC%2596%25B4">상상스퀘어</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A2%2585%25EC%259B%2590&amp;authorNo=135500&amp;author=김종원" target="">김종원</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b2%ad%eb%a6%bcLife&amp;query=%25EC%25B2%25AD%25EB%25A6%25BCLife">청림Life</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EA%25B0%2595&amp;authorNo=341&amp;author=한강" target="">한강</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b0%bd%eb%b9%84&amp;query=%25EC%25B0%25BD%25EB%25B9%2584">창비</a></span>
<span class="authPub info_date">2014년 05월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2588%2598%25EB%25AF%25B8&amp;authorNo=488842&amp;author=김수미" target="">김수미</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b9%85%ed%94%bc%ec%8b%9c&amp;query=%25EB%25B9%2585%25ED%2594%25BC%25EC%258B%259C">빅피시</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2583%259C%25EC%2588%2598&amp;authorNo=288320&amp;author=태수" target="">태수</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%8e%98%ec%9d%b4%ec%a7%802%eb%b6%81%ec%8a%a4&amp;query=%25ED%258E%2598%25EC%259D%25B4%25EC%25A7%25802%25EB%25B6%2581%25EC%258A%25A4">페이지2북스</a></span>
<span class="authPub info_date">2024년 11월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A3%25BC%25ED%2599%2598&amp;authorNo=142070&amp;author=김주환" target="">김주환</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b8%ed%94%8c%eb%a3%a8%ec%97%94%ec%85%9c&amp;query=%25EC%259D%25B8%25ED%2594%258C%25EB%25A3%25A8%25EC%2597%2594%25EC%2585%259C">인플루엔셜</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2596%2591%25EA%25B7%2580%25EC%259E%2590&amp;authorNo=109194&amp;author=양귀자" target="">양귀자</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%93%b0%eb%8b%a4&amp;query=%25EC%2593%25B0%25EB%258B%25A4">쓰다</a></span>
<span class="authPub info_date">2013년 04월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259A%2594%25EC%258B%259C%25ED%2583%2580%25EC%25BC%2580%2520%25EC%258B%25A0%25EC%258A%25A4%25EC%25BC%2580&amp;authorNo=165803&amp;author=요시타케 신스케" target="">요시타케 신스케</a> 글그림/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B6%258C%25EB%2582%25A8%25ED%259D%25AC&amp;authorNo=118705&amp;author=권남희" target="">권남희</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%a3%bc%eb%8b%88%ec%96%b4%ea%b9%80%ec%98%81%ec%82%ac&amp;query=%25EC%25A3%25BC%25EB%258B%2588%25EC%2596%25B4%25EA%25B9%2580%25EC%2598%2581%25EC%2582%25AC">주니어김영사</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25BD%2594%25EC%259D%25B4%25EC%25BC%2580%2520%25EB%25A5%2598%25EB%2585%25B8%25EC%258A%25A4%25EC%25BC%2580&amp;authorNo=138755&amp;author=코이케 류노스케" target="">코이케 류노스케</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B0%2595%25EC%259E%25AC%25ED%2598%2584&amp;authorNo=124886&amp;author=박재현" target="">박재현</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%8f%ac%eb%a0%88%ec%8a%a4%ed%8a%b8%eb%b6%81%ec%8a%a4&amp;query=%25ED%258F%25AC%25EB%25A0%2588%25EC%258A%25A4%25ED%258A%25B8%25EB%25B6%2581%25EC%258A%25A4">포레스트북스</a></span>
<span class="authPub info_date">2024년 05월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2599%2580%25EC%2595%25BC%25EB%25A7%2588%2520%25EC%2595%25BC%25EB%25A7%2588&amp;authorNo=339854&amp;author=와야마 야마" target="">와야마 야마</a> 글그림/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2598%2584%25EC%258A%25B9%25ED%259D%25AC&amp;authorNo=250920&amp;author=현승희" target="">현승희</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%ac%b8%ed%95%99%eb%8f%99%eb%84%a4&amp;query=%25EB%25AC%25B8%25ED%2595%2599%25EB%258F%2599%25EB%2584%25A4">문학동네</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259C%25A0%25EB%25B0%259C%2520%25ED%2595%2598%25EB%259D%25BC%25EB%25A6%25AC&amp;authorNo=167623&amp;author=유발 하라리" target="">유발 하라리</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EB%25AA%2585%25EC%25A3%25BC&amp;authorNo=121375&amp;author=김명주" target="">김명주</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ea%b9%80%ec%98%81%ec%82%ac&amp;query=%25EA%25B9%2580%25EC%2598%2581%25EC%2582%25AC">김영사</a></span>
<span class="authPub info_date">2024년 10월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259C%25A0%25EC%2584%25A0%25EA%25B2%25BD&amp;authorNo=166709&amp;author=유선경" target="">유선경</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9c%84%ec%a6%88%eb%8d%a4%ed%95%98%ec%9a%b0%ec%8a%a4&amp;query=%25EC%259C%2584%25EC%25A6%2588%25EB%258D%25A4%25ED%2595%2598%25EC%259A%25B0%25EC%258A%25A4">위즈덤하우스</a></span>
<span class="authPub info_date">2024년 10월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25ED%2583%259C%25EC%2584%25B1&amp;authorNo=154511&amp;author=최태성" target="">최태성</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b4%ed%88%ac%ec%8a%a4%eb%b6%81+&amp;query=%25EC%259D%25B4%25ED%2588%25AC%25EC%258A%25A4%25EB%25B6%2581%2520">이투스북 </a></span>
<span class="authPub info_date">2024년 12월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A3%25BC%25ED%2599%2598&amp;authorNo=142070&amp;author=김주환" target="">김주환</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b8%ed%94%8c%eb%a3%a8%ec%97%94%ec%85%9c&amp;query=%25EC%259D%25B8%25ED%2594%258C%25EB%25A3%25A8%25EC%2597%2594%25EC%2585%259C">인플루엔셜</a></span>
<span class="authPub info_date">2025년 02월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2595%2588%25EB%2585%2595%25EB%258B%25AC&amp;authorNo=165613&amp;author=안녕달" target="">안녕달</a> 글그림
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b0%bd%eb%b9%84&amp;query=%25EC%25B0%25BD%25EB%25B9%2584">창비</a></span>
<span class="authPub info_date">2025년 03월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25B5%259C%25ED%2583%259C%25EC%2584%25B1&amp;authorNo=154511&amp;author=최태성" target="">최태성</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%9d%b4%ed%88%ac%ec%8a%a4%eb%b6%81+&amp;query=%25EC%259D%25B4%25ED%2588%25AC%25EC%258A%25A4%25EB%25B6%2581%2520">이투스북 </a></span>
<span class="authPub info_date">2024년 12월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B8%258C%25EB%259D%25BC%25EC%259D%25B4%25EC%2596%25B8%2520%25ED%258A%25B8%25EB%25A0%2588%25EC%259D%25B4%25EC%258B%259C&amp;authorNo=101624&amp;author=브라이언 트레이시" target="">브라이언 트레이시</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2595%25EC%25A7%2580%25ED%2598%2584&amp;authorNo=183679&amp;author=정지현" target="">정지현</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ed%98%84%eb%8c%80%ec%a7%80%ec%84%b1&amp;query=%25ED%2598%2584%25EB%258C%2580%25EC%25A7%2580%25EC%2584%25B1">현대지성</a></span>
<span class="authPub info_date">2024년 11월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A0%2595%25EB%258C%2580%25EA%25B1%25B4&amp;authorNo=173691&amp;author=정대건" target="">정대건</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%af%bc%ec%9d%8c%ec%82%ac&amp;query=%25EB%25AF%25BC%25EC%259D%258C%25EC%2582%25AC">민음사</a></span>
<span class="authPub info_date">2022년 12월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%25A1%25B4%2520%25EC%259C%258C%25EB%25A6%25AC%25EC%2597%2584%25EC%258A%25A4&amp;authorNo=168400&amp;author=존 윌리엄스" target="">존 윌리엄스</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%258A%25B9%25EC%259A%25B1&amp;authorNo=124618&amp;author=김승욱" target="">김승욱</a> 역
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%95%8c%ec%97%90%ec%9d%b4%ec%b9%98%ec%bd%94%eb%a6%ac%ec%95%84(RHK)&amp;query=%25EC%2595%258C%25EC%2597%2590%25EC%259D%25B4%25EC%25B9%2598%25EC%25BD%2594%25EB%25A6%25AC%25EC%2595%2584(RHK)">알에이치코리아(RHK)</a></span>
<span class="authPub info_date">2015년 01월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B0%25B1%25EC%2598%25A8%25EC%259C%25A0&amp;authorNo=304055&amp;author=백온유" target="">백온유</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B0%2595%25EB%25B3%25B4%25EB%259D%25BC&amp;authorNo=344419&amp;author=강보라" target="">강보라</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%259C%25EC%259E%25A5%25EC%259B%2590&amp;authorNo=306717&amp;author=서장원" target="">서장원</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2595%25B4%25EB%2582%2598&amp;authorNo=253719&amp;author=성해나" target="">성해나</a>, <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2598%259C%25EB%25A0%25B9&amp;authorNo=368997&amp;author=성혜령" target="">성혜령</a> 저 외 2명
                                        <span class="moreAuthArea">
<span class="moreAuthBtn"><a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.cCont_listArea'),event);">정보 더 보기/감추기</a></span>
<span class="moreAuthLi">
<span class="moreAuthLiCont">
<ul>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25B0%25B1%25EC%2598%25A8%25EC%259C%25A0&amp;authorNo=304055&amp;author=백온유" target="">백온유</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B0%2595%25EB%25B3%25B4%25EB%259D%25BC&amp;authorNo=344419&amp;author=강보라" target="">강보라</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%259C%25EC%259E%25A5%25EC%259B%2590&amp;authorNo=306717&amp;author=서장원" target="">서장원</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2595%25B4%25EB%2582%2598&amp;authorNo=253719&amp;author=성해나" target="">성해나</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2584%25B1%25ED%2598%259C%25EB%25A0%25B9&amp;authorNo=368997&amp;author=성혜령" target="">성혜령</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25ED%259D%25AC%25EC%25A3%25BC&amp;authorNo=345050&amp;author=이희주" target="">이희주</a></li>
<li><em class="bl_dot bgYUI"></em><a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2598%2584%25ED%2598%25B8%25EC%25A0%2595&amp;authorNo=350594&amp;author=현호정" target="">현호정</a></li>
</ul>
</span>
</span>
</span>
</span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%ac%b8%ed%95%99%eb%8f%99%eb%84%a4&amp;query=%25EB%25AC%25B8%25ED%2595%2599%25EB%258F%2599%25EB%2584%25A4">문학동네</a></span>
<span class="authPub info_date">2025년 04월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25ED%2598%2584%25EA%25B7%25BC&amp;authorNo=429420&amp;author=한현근" target="">한현근</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%a7%81%ec%97%85%ec%83%81%ec%a0%90&amp;query=%25EC%25A7%2581%25EC%2597%2585%25EC%2583%2581%25EC%25A0%2590">직업상점</a></span>
<span class="authPub info_date">2025년 01월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%259C%25EA%25B0%2595&amp;authorNo=341&amp;author=한강" target="">한강</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%ac%b8%ed%95%99%eb%8f%99%eb%84%a4&amp;query=%25EB%25AC%25B8%25ED%2595%2599%25EB%258F%2599%25EB%2584%25A4">문학동네</a></span>
<span class="authPub info_date">2021년 09월</span>
</div>
<div class="info_row info_pubGrp">
<span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=ETS&amp;authorNo=156974&amp;author=ETS" target="">ETS</a> 저
                            </span>
<span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=YBM(%ec%99%80%ec%9d%b4%eb%b9%84%ec%97%a0)&amp;query=YBM(%25EC%2599%2580%25EC%259D%25B4%25EB%25B9%2584%25EC%2597%25A0)">YBM(와이비엠)</a></span>
<span class="authPub info_date">2023년 12월</span>
</div>

In [155]:
total = [name_list, author_list, publisher_list, publishdate_list, cost_list, reviewscore_list, reviewnum_list]
column = ['도서명', '저자', '출판사', '출간일', '가격', '회원리뷰 점수', '회원리뷰 건수']

In [156]:
for lists in total:
    print(len(lists))

24
24
24
24
24
24
24

In [157]:
result_dic = {}

for col, value in zip(column, total):
    result_dic[col] = value

result_df = pd.DataFrame(result_dic)
result_df

,도서명,저자,출판사,출간일,가격,회원리뷰 점수,회원리뷰 건수
0,단 한 번의 삶,김영하,복복서가,2025년 04월,"15,120원",9.0,8
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,"18,900원",8.7,37
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,"18,000원",9.9,56
3,소년이 온다,한강,창비,2014년 05월,"13,500원",9.7,"3,845"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,"17,820원",9.9,67
5,어른의 행복은 조용하다,태수,페이지2북스,2024년 11월,"16,020원",9.5,188
6,내면소통 명상수업,김주환,인플루엔셜,2025년 03월,"25,200원",10.0,10
7,모순,양귀자,쓰다,2013년 04월,"11,700원",9.6,"1,390"
8,별별 직업 상담소,요시타케 신스케,주니어김영사,2025년 03월,"14,220원",10.0,2
9,초역 부처의 말,코이케 류노스케,포레스트북스,2024년 05월,"16,020원",9.4,348
10,여학교의 별 4,와야마 야마,문학동네,2025년 03월,"7,650원",미발매,미발매
11,넥서스,유발 하라리,김영사,2024년 10월,"25,020원",9.4,225
12,하루 한 장 나의 어휘력을 위한 필사 노트,유선경,위즈덤하우스,2024년 10월,"21,420원",9.5,695
13,"2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상",최태성,이투스북,2024년 12월,"14,850원",9.6,57
14,그릿 GRIT,김주환,인플루엔셜,2025년 02월,"16,920원",9.9,42
15,별에게,안녕달,창비,2025년 03월,"15,120원",10.0,25
16,"2025 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하",최태성,이투스북,2024년 12월,"14,400원",9.6,48
17,행동하지 않으면 인생은 바뀌지 않는다,브라이언 트레이시,현대지성,2024년 11월,"15,210원",9.3,247
18,급류,정대건,민음사,2022년 12월,"12,600원",9.1,263
19,스토너,존 윌리엄스,알에이치코리아(RHK),2015년 01월,"15,120원",9.3,491
20,2025 제16회 젊은작가상 수상작품집,백온유,문학동네,2025년 04월,"6,930원",미발매,미발매
21,2025 헝그리스포츠 7일 완성 생활스포츠지도사 2급 필기,한현근,직업상점,2025년 01월,"27,900원",9.9,31
22,작별하지 않는다,한강,문학동네,2021년 09월,"15,120원",9.6,"2,006"
23,ETS 토익 정기시험 기출문제집 1000 Vol. 4 RC,ETS,YBM(와이비엠),2023년 12월,"17,820원",9.7,402

In [165]:
# yes24 전체 페이지에서 책 정보가 들어있는 부분만 잘라서 book_list에 저장
book_list = soup.select("ul#yesBestList > li")
# book_list = soup.select("ul#yesBestList").select("li") 도 가능
book_list

[<li class="" data-goods-no="144021119" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">1</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="단 한 번의 삶" border="0" class="lazy" data-original="https://image.yes24.com/goods/144021119/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(144021119); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); ">단 한 번의 삶</a>
 <span class="gd_feature">[ 양장 ]</span>
 <a class="bgYUI ico_nWin" href="/product/goods/144021119" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">단 한 번의 삶 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%2598%2581%25ED%2595%2598&amp;authorNo=673&amp;author=김영하" target="">김영하</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%eb%b3%b5%eb%b3%b5%ec%84%9c%ea%b0%80&amp;query=%25EB%25B3%25B5%25EB%25B3%25B5%25EC%2584%259C%25EA%25B0%2580">복복서가</a></span>
 <span class="authPub info_date">2025년 04월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=257190">만년필용 노트+커버+스티커 세트/케이블 파우치(포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">15,120</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">16,800</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>840원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 224,271
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/144021119?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">9</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_9">리뷰 총점</span><em class="yes_b">8.9</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (1건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (8건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (0건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B8%25EC%2583%259D%25EC%259D%25B4%25EC%2595%25BC%25EA%25B8%25B0&amp;hashNm=%ec%9d%b8%ec%83%9d%ec%9d%b4%ec%95%bc%ea%b8%b0" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '인생이야기', '144021119','6696');">#인생이야기</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%2582%25AC%25EC%259C%25A0%25EC%2599%2580%25EA%25B0%2590%25EC%2584%25B1&amp;hashNm=%ec%82%ac%ec%9c%a0%ec%99%80%ea%b0%90%ec%84%b1" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '사유와감성', '144021119','6832');">#사유와감성</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259E%2591%25EA%25B0%2580%25EC%259D%2598%25EC%2597%2590%25EC%2584%25B8%25EC%259D%25B4&amp;hashNm=%ec%9e%91%ea%b0%80%ec%9d%98%ec%97%90%ec%84%b8%ec%9d%b4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '작가의에세이', '144021119','2167');">#작가의에세이</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="txt"><a href="https://event.yes24.com/detail?eventNo=257293">『단 한 번의 삶』 - 영하의 무물 소책자</a></span>
 <span class="date">(25.03.24 ~ 00.12.31)</span>
 </div>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="144021119" id="ordChk_144021119" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_144021119" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('144021119'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('144021119'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('144021119', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('144021119', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" onclick="order_payment.addMyListV3('144021119', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_144021119" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":144021119,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"단 한 번의 삶","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001034","goodsSortNm":"에세이","goodsAuth":"&lt;김영하&gt; 저","shopPrice":16800.00,"salePrice":15120.00,"discountShopPrice":1680.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="142876017" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">2</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/142876017" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="듀얼 브레인" border="0" class="lazy" data-original="https://image.yes24.com/goods/142876017/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(142876017); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/142876017" onclick="wiseLogV2('BS', '001_005_001', ''); ">듀얼 브레인</a>
 <span class="gd_nameE">AI 시대의 실용적 생존 가이드</span>
 <a class="bgYUI ico_nWin" href="/product/goods/142876017" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">듀얼 브레인 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%259D%25B4%25EC%2584%25A0%2520%25EB%25AA%25B0%25EB%25A6%25AD&amp;authorNo=487104&amp;author=이선 몰릭" target="">이선 몰릭</a> 저/<a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EC%258B%25A0%25EB%258F%2599%25EC%2588%2599&amp;authorNo=155164&amp;author=신동숙" target="">신동숙</a> 역
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%83%81%ec%83%81%ec%8a%a4%ed%80%98%ec%96%b4&amp;query=%25EC%2583%2581%25EC%2583%2581%25EC%258A%25A4%25ED%2580%2598%25EC%2596%25B4">상상스퀘어</a></span>
 <span class="authPub info_date">2025년 03월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/earlyReader?eventNo=257341">[이달의 책 4월] 독서 트래킹 포스터 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">18,900</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">21,000</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>1,050원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 262,401
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/142876017?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">38</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_9">리뷰 총점</span><em class="yes_b">8.7</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (11건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (26건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (1건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EC%259D%2598%25EC%259D%25BC%25EC%259E%2590%25EB%25A6%25AC&amp;hashNm=%eb%af%b8%eb%9e%98%ec%9d%98%ec%9d%bc%ec%9e%90%eb%a6%ac" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '미래의일자리', '142876017','3517');">#미래의일자리</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EB%25A5%25BC%25EA%25B7%25B8%25EB%25A6%25AC%25EB%258B%25A4&amp;hashNm=%eb%af%b8%eb%9e%98%eb%a5%bc%ea%b7%b8%eb%a6%ac%eb%8b%a4" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '미래를그리다', '142876017','6691');">#미래를그리다</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%25AF%25B8%25EB%259E%2598%25EC%25A0%2584%25EB%259E%25B5&amp;hashNm=%eb%af%b8%eb%9e%98%ec%a0%84%eb%9e%b5" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '미래전략', '142876017','5290');">#미래전략</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=AI%25EA%25B4%2580%25EB%25A0%25A8%25EC%2584%259C&amp;hashNm=AI%ea%b4%80%eb%a0%a8%ec%84%9c" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', 'AI관련서', '142876017','4492');">#AI관련서</a>
 </span>
 </div>
 <div class="info_row info_relG">
                     관련상품 :                            <span class="relG"><a href="/product/goods/143587354">eBook <span class="relG_num">14,700원</span></a></span>
 </div>
 </div>
 <div class="item_btnCol">
 <span class="btn_row">
 <span class="chkBox" style=""><label><input class="basic" data-goodsno="142876017" id="ordChk_142876017" name="ORD_GOODS_CHKBOX" style="" type="checkbox"/><span class="bgYUI chk"></span></label></span>
 <span class="numBox">
 <span class="yesIpt ipt_wSizeF">
 <input class="ac yes_m" id="ordCnt_142876017" maxlength="3" name="ORD_GOODS_CNT" onkeyup="return checkNumeric(this);" style="ime-mode:disabled !important" title="수량설정" type="text" value="1"/>
 </span>
 <button class="minus" onclick="order_payment.downOrderCount('142876017'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량감소</span></button>
 <button class="plus" onclick="order_payment.upOrderCount('142876017'); wiseLogV2('BS', '001_005_006', '');" type="button"><span class="bgYUI">수량증가</span></button>
 </span>
 </span>
 <a class="btnC btn_blue" href="javascript:void(0);" onclick="order_payment.addCartV3('142876017', '', this, '', '', '', '', 'Search', true); wiseLogV2('BS', '001_005_007', '');"><span class="bWrap"><em class="txt">카트에 넣기</em></span></a>
 <a class="btnC btn_sBlue" href="javascript:void(0);" onclick="order_payment.orderDirectV3('142876017', '', this, '', '', '', '', 'Search'); wiseLogV2('BS', '001_005_008', '');"><span class="bWrap"><em class="txt">바로구매</em></span></a>
 <a class="btnC" href="javascript:void(0);" onclick="order_payment.addMyListV3('142876017', '', '', true, ''); wiseLogV2('BS', '001_005_010', '');;"><span class="bWrap"><em class="txt">리스트에 넣기</em></span></a>
 <input id="ordOpt_142876017" name="ORD_GOODS_OPT" type="hidden" value='{"goods_no":142876017,"goods_seq":1,"order_limit_yn":"N","order_remain_count":0,"event_no":0,"add_cart_yn":"Y","goods_state":"02","order_limit_count":0,"resource_key":"01","limit_age_yn":"N","limit_age":0,"member_age":0,"goods_name":"듀얼 브레인","noint_quotamonth":0,"min_cnt":0,"max_cnt":0,"opt_salepr":0,"opt_yn":"N","opt_inst_yn":"N","flat_rate_yn":null,"rent_goods_yn":"N","bookclue_yn":"N","goods_gb":"01","goodsSortNo":"001022","goodsSortNm":"자기계발","goodsAuth":"&lt;이선 몰릭&gt; 저/&lt;신동숙&gt; 역","shopPrice":21000.00,"salePrice":18900.00,"discountShopPrice":2100.00}'/>
 </div>
 </div>
 </li>,
 <li class="" data-goods-no="142687238" data-iy-no="0" data-statgb="02">
 <div class="itemUnit">
 <div class="item_img">
 <div class="img_canvas">
 <div class="img_upper">
 <em class="ico rank">3</em>
 <span class="rank_info rank_even">
 <span class="ico"></span><em class="txt rank"></em><em class="txt">위 상승</em>
 </span>
 </div>
 <span class="img_item">
 <span class="img_grp">
 <a class="lnk_img" href="/product/goods/142687238" onclick="wiseLogV2('BS', '001_005_001', ''); ">
 <em class="img_bdr">
 <img alt="어른의 품격을 채우는 100일 필사 노트" border="0" class="lazy" data-original="https://image.yes24.com/goods/142687238/L" src="https://image.yes24.com/momo/Noimg_L.jpg"/>
 </em>
 </a>
 </span>
 </span>
 </div>
 <div class="img_btn">
 <a class="btnC btn_preview" href="javascript:yes24GU.openPreviewCheck(142687238); wiseLogV2('BS', '001_005_011', '');"><span class="bWrap"><em class="txt">미리보기</em></span></a>
 </div>
 </div>
 <div class="item_info">
 <div class="info_row info_keynote">
 </div>
 <div class="info_row info_name">
 <span class="gd_res">[도서]</span>
 <a class="gd_name" href="/product/goods/142687238" onclick="wiseLogV2('BS', '001_005_001', ''); ">어른의 품격을 채우는 100일 필사 노트</a>
 <span class="gd_feature">[ 양장 ]</span>
 <a class="bgYUI ico_nWin" href="/product/goods/142687238" onclick="wiseLogV2('BS', '001_005_001', ''); " target="_blank">어른의 품격을 채우는 100일 필사 노트 새창이동</a>
 </div>
 <div class="info_row info_pubGrp">
 <span class="authPub info_auth" onclick="wiseLogV2('BS', '001_005_002', '');">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EA%25B9%2580%25EC%25A2%2585%25EC%259B%2590&amp;authorNo=135500&amp;author=김종원" target="">김종원</a> 저
                             </span>
 <span class="authPub info_pub" onclick="wiseLogV2('BS', '001_005_003', '');"><a href="https://www.yes24.com/product/search?&amp;domain=ALL&amp;company=%ec%b2%ad%eb%a6%bcLife&amp;query=%25EC%25B2%25AD%25EB%25A6%25BCLife">청림Life</a></span>
 <span class="authPub info_date">2025년 03월</span>
 </div>
 <dl class="info_present">
 <dt><em class="bgYUI ico_present">구매혜택</em></dt>
 <dd>
 <a href="https://event.yes24.com/template?EventNo=257553">[자기계발 기획] 아몬드 나무 명화 텀블러 (포인트 차감)</a>
 </dd>
 </dl>
 <div class="info_row info_price">
 <span class="txt_sale"><em class="num">10</em>%</span>
 <strong class="txt_num"><em class="yes_b">18,000</em>원</strong>
 <span class="txt_num dash"><em class="yes_m">20,000</em>원</span>
 <span class="yPoint"><em class="bgYUI ico_point">포인트적립</em>1,000원</span>
 </div>
 <div class="info_row info_rating">
 <span class="saleNum">
                                 판매지수 169,401
                             </span>
 <span class="rating_rvCount">
 <a href="https://www.yes24.com/product/goods/142687238?ReviewYn=Y" onclick="wiseLogV2('BS', '001_005_004', '');"><em class="bit">회원리뷰</em>(<em class="txC_blue">56</em>건)</a>
 </span>
 <span class="rating_grade">
 <span class="bgYUI tRating tRating_10">리뷰 총점</span><em class="yes_b">9.9</em>
 <span class="moreRatingArea">
 <span class="moreRatingBtn">
 <a class="bgYUI" href="javascript:void(0);" onclick="toggleLiCont(this,$('.sGLi'),event);">정보 더 보기/감추기</a>
 </span>
 <span class="moreRatingLi">
 <span class="moreRatingLiRow">
 <ul class="yesAlertLi">
 <li><em class="bl_dot bgYUI"> </em>종이책 리뷰 (37건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 리뷰 (0건)</li>
 <li><em class="bl_dot bgYUI"> </em>종이책 한줄평 (19건)</li>
 <li><em class="bl_dot bgYUI"> </em>eBook 한줄평 (0건)</li>
 </ul>
 </span>
 </span>
 </span>
 </span>
 </div>
 <div class="info_row info_deli" name="delvTextArea"></div>
 <div class="info_row info_tag">
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25EB%2582%2598%25EB%25A5%25BC%25EC%259E%2583%25EC%25A7%2580%25EB%25A7%2588&amp;hashNm=%eb%82%98%eb%a5%bc%ec%9e%83%ec%a7%80%eb%a7%88" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '나를잃지마', '142687238','7493');">#나를잃지마</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2592%2588%25EA%25B2%25A9%25EC%259E%2588%25EB%258A%2594%25EC%2582%25B6&amp;hashNm=%ed%92%88%ea%b2%a9%ec%9e%88%eb%8a%94%ec%82%b6" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '품격있는삶', '142687238','7492');">#품격있는삶</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%2584%25EC%2582%25AC&amp;hashNm=%ed%95%84%ec%82%ac" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '필사', '142687238','7185');">#필사</a>
 </span>
 <span class="tag">
 <a href="https://www.yes24.com/product/search?domain=ALL&amp;query=%25ED%2595%2584%25EC%2582%25AC%25EC%2597%25B0%25EC%258A%25B5&amp;hashNm=%ed%95%84%ec%82%ac%ec%97%b0%ec%8a%b5" onclick="wiseLogV2('BS', '001_005_005', ''); setTagClickExtraCode('100', '필사연습', '142687238','5514');">#필사연습</a>
 </span>
 </div>
 <div class="info_row info_event">
 <div class="event">
 <span class="iconC freeD"><em class="txt">이벤트</em></span>
 <span class="iconC"><em class="txt">사은품</em></span>
 <span class="iconC"><em class="txt">기획전</em></span>

In [169]:
# 책제목
book_title = book_list[0].select_one(".gd_name").text
book_title

'단 한 번의 삶'

In [170]:
# 저자
author = book_list[0].select_one(".info_row.info_pubGrp a").text
author

'김영하'

In [171]:
# 출판사
publisher = book_list[0].select_one(".authPub.info_pub a").text
publisher

'복복서가'

In [182]:
# 출간일
date_pub = book_list[0].select_one(".authPub.info_date").text
date_pub

'2025년 04월'

In [181]:
# 가격
price = int(book_list[0].select_one(".info_row.info_price em.yes_b").text.replace(',',''))
price

15120

In [190]:
# 평점
rating = float(book_list[0].select_one(".rating_grade em.yes_b").text)
rating

8.9

In [ ]:
# 출간일
date = book_list[0].select_one(".authPub.info_date").text
date

In [193]:
# 리뷰 수
n_reviews = book_list[0].select_one(".info_row.info_rating em.txC_blue").text               
n_reviews

'9'

In [312]:
result = {}
column = ['book_title', 'author', 'publisher', 'date_pub', 'price', 'rating', 'n_reviews']

for i in range(1,10):
    url = 'https://www.yes24.com/product/category/bestseller'
    payload = dict(categoryNumber='001', pageNumber=i, pageSize=120)
    r = requests.get(url, params=payload)
    soup = bs(r.content, 'lxml')
    time.sleep(5)

    book_list = soup.select("ul#yesBestList > li")

    for book in book_list:
        book_title = book.select_one(".gd_name").text              # 책제목
        author = book.select_one(".info_row.info_pubGrp a").text   # 저자
        publisher = book.select_one(".authPub.info_pub a").text    # 출판사
        date_pub = book.select_one(".authPub.info_date").text      # 출간일
        price = int(book.select_one(".info_row.info_price em.yes_b").text.replace(',',''))    # 가격
        if (book.select_one(".rating_grade em.yes_b")):            # 평점
            rating = float(book.select_one(".rating_grade em.yes_b").text)
        else:
            rating = 0
        if (book.select_one(".info_row.info_rating em.txC_blue")): # 리뷰 수
            n_reviews = book.select_one(".info_row.info_rating em.txC_blue").text   
        else:
            n_reviews = 0

        values = [book_title, author, publisher, date_pub, price, rating, n_reviews]

        for col, val in zip(column, values):
            result.setdefault(col, []).append(val)

    
result_df = pd.DataFrame(result)
result_df

,book_title,author,publisher,date_pub,price,rating,n_reviews
0,단 한 번의 삶,김영하,복복서가,2025년 04월,15120,8.9,9
1,듀얼 브레인,이선 몰릭,상상스퀘어,2025년 03월,18900,8.7,38
2,어른의 품격을 채우는 100일 필사 노트,김종원,청림Life,2025년 03월,18000,9.9,56
3,소년이 온다,한강,창비,2014년 05월,13500,9.7,"3,845"
4,성적 초격차를 만드는 독서력 수업,김수미,빅피시,2025년 03월,17820,9.9,67
...,...,...,...,...,...,...,...
994,오십의 기술,이호선,카시오페아,2023년 04월,16200,9.2,48
995,햇빛초 대나무 숲에 새 글이 올라왔습니다,황지영,우리학교,2020년 08월,13050,9.9,68
996,처음 읽는 그리스 로마 신화 2,최설희,미래엔아이세움,2020년 08월,10800,9.9,84
997,"칵테일, 러브, 좀비",조예은,안전가옥,2020년 04월,11700,9.2,"1,132"
998,와일드 로봇,피터 브라운,거북이북스,2019년 07월,15120,9.9,86

만약에 저자가 많으면 ?
아래 코드에서 엮자, 저자 여러명 등은 수가 다름

In [207]:
result['author'][28]

'정관 스님'

In [233]:
len(book_list[1].select(".authPub.info_auth a"))

2

In [232]:
len(book_list[5].select(".authPub.info_auth a"))

1

In [231]:
len(book_list[18].select(".authPub.info_auth a"))

1

In [230]:
len(book_list[28].select(".authPub.info_auth a"))

4

In [276]:
book_list[20].select_one(".authPub.info_auth").text.split('/')[1].replace("\n"," ")

'\n백온유, 강보라, 서장원, 성해나, 성혜령 저 외 2명\r\n                                        \n정보 더 보기/감추기\n\n\n\n백온유\n강보라\n서장원\n성해나\n성혜령\n이희주\n현호정\n\n\n\n\n'

In [277]:
payload = dict(categoryNumber='001', pageNumber=1, pageSize=120)
r = requests.get(url, params=payload)
soup = bs(r.content, 'lxml')

book_list_mini = soup.select("ul#yesBestList > li")

In [307]:
i = 1
for book in book_list_mini:
    
    if len(book.select_one(".authPub.info_auth").text.split('/')) == 2:
        print(i,book.select_one(".authPub.info_auth").text, end='')
        if book.select_one(".authPub.info_auth").text.split('/')[0][-3:] == '글그림':
            print(book.select_one(".authPub.info_auth").text.split('/')[0][:-4])
        elif book.select_one(".authPub.info_auth").text.split('/')[0][-2:] == ' 글':
            print(book.select_one(".authPub.info_auth").text.split('/')[0][:-2], book.select_one(".authPub.info_auth").text.split('/')[1][:-3])
            print('정상작동')
        elif book.select_one(".authPub.info_auth").text.split('/')[0][-2:] == ' 저':
            print(book.select_one(".authPub.info_auth").text.split('/')[0][:-2])
        elif book.select_one(".authPub.info_auth").text.split('/')[0][-2:] == '원저':
            print(book.select_one(".authPub.info_auth").text.split('/')[1][:-2],book.select_one(".authPub.info_auth").text.split('/')[2][:-3])
        print(len(book.select_one(".authPub.info_auth").text.split('/')),'개')
        
    if len(book.select_one(".authPub.info_auth").text.split('/')) == 3:
        print(i,book.select_one(".authPub.info_auth").text, end='')
        if book.select_one(".authPub.info_auth").text.split('/')[0][-3:] == '글그림':
            print(book.select_one(".authPub.info_auth").text.split('/')[0][:-4])
        elif book.select_one(".authPub.info_auth").text.split('/')[0][-2:] == ' 글':
            print(book.select_one(".authPub.info_auth").text.split('/')[0][:-2],'/', book.select_one(".authPub.info_auth").text.split('/')[1][:-3])
        elif book.select_one(".authPub.info_auth").text.split('/')[0][-2:] == ' 저':
            if book.select_one(".authPub.info_auth").text.split('/')[1][-1] != '역':
                print(book.select_one(".authPub.info_auth").text.split('/')[0][:-2],'/', book.select_one(".authPub.info_auth").text.split('/')[1][:-3])
            elif book.select_one(".authPub.info_auth").text.split('/')[1][-1] == '역':
                print(book.select_one(".authPub.info_auth").text.split('/')[0][:-2])
        elif book.select_one(".authPub.info_auth").text.split('/')[0][-2:] == '원저':
            print(book.select_one(".authPub.info_auth").text.split('/')[1][:-2],'/',book.select_one(".authPub.info_auth").text.split('/')[2][:-3])
    

        print(len(book.select_one(".authPub.info_auth").text.split('/')),'개')
    i += 1

2
이선 몰릭 저/신동숙 역

이선 몰릭
2 개
9
요시타케 신스케 글그림/권남희 역

요시타케 신스케
2 개
10
코이케 류노스케 저/박재현 역

코이케 류노스케
2 개
11
와야마 야마 글그림/현승희 역

와야마 야마
2 개
12
유발 하라리 저/김명주 역

유발 하라리
2 개
18
브라이언 트레이시 저/정지현 역

브라이언 트레이시
2 개
20
존 윌리엄스 저/김승욱 역

존 윌리엄스
2 개
21
백온유, 강보라, 서장원, 성해나, 성혜령 저 외 2명

정보 더 보기/감추기



백온유
강보라
서장원
성해나
성혜령
이희주
현호정




2 개
29
정관 스님, 후남 셀만 저/베로니크 회거 사진/양혜영 역

정관 스님, 후남 셀만 / 베로니크 회거
3 개
34
안-엘렌 클레르, 뱅상 트리부 저/구영옥 역

안-엘렌 클레르, 뱅상 트리부
2 개
44
벤저민 하디 저/최은아 역

벤저민 하디
2 개
45
김지훤 글/하꼬방 그림

김지훤 하꼬방 그림

정상작동
2 개
54
태 킴 저/김정민 역/김상균 감수

태 킴
3 개
55
타치바나 오레코 글그림/유유리 역

타치바나 오레코
2 개
57
아이다이로 글그림/장혜영 역

아이다이로
2 개
60
알에스미디어 글/정수영 그림/강용철 감수

알에스미디어 / 정수영
3 개
63
네빌 고다드 저/홍주연 역

네빌 고다드
2 개
65
클레어 키건 저/홍한별 역

클레어 키건
2 개
68
칼 에드워드 세이건 저/홍승수 역

칼 에드워드 세이건
2 개
70
센바 쿠로노 글그림/반기모 역

센바 쿠로노
2 개
74
데일 카네기 저/임상훈 역

데일 카네기
2 개
75
최설희 글/김덕영 그림

최설희 김덕영 그림

정상작동
2 개
78
강효미 글/김무연 그림/권윤정 감수

강효미 / 김무연
3 개
79
리처드 도킨스 저/홍영남, 이상임 역

리처드 도킨스
2 개
80
김지원, 김혜원, 도헌정, 허완, 조성도 저 외 5명

정보 더 보기/감추기



김지원
김혜원
도헌정
허완
조성도
김희라
오별님
윤성원
김송희
손현




2 개
81
유발 하라리 저/조현욱 역/이태수 감수

유발 하라리
3 개
88
정주희 저/이수진 감수

정주희
2 개
91
김화요 글/오윤화 그림

김화요 오윤화 그림

정상작동
2 개
94
인이이 저/장려진 역

인이이
2 개
95
도야마 시게히코 저/전경아 역

도야마 시게히코
2 개
98
헤르만 헤세 저/전영애 역

헤르만 헤세
2 개
100
예소연, 김기태, 문지혁, 서장원, 정기현 저 외 1명

정보 더 보기/감추기



예소연
김기태
문지혁
서장원
정기현
최민우




2 개
106
모건 하우절 저/이지연 역

모건 하우절
2 개
107
모건 하우절 저/이수경 역

모건 하우절
2 개
110
설민석, 남이담 글/정현희 그림/강석화 감수

설민석, 남이담 / 정현희
3 개
112
로이스 라우리 저/장은수 역

로이스 라우리
2 개
117
카모시다 하지메 저/미조구치 케이지 그림/이승원 역

카모시다 하지메 / 미조구치 케이지
3 개
118
카모시다 하지메 저/미조구치 케이지 그림/이승원 역

카모시다 하지메 / 미조구치 케이지
3 개

In [342]:
i = 1
for book in book_list_mini:
    print()
    author = book.select_one(".authPub.info_auth").text.split('/')
    print('리스트 :', author)
    if len(author) >= 2:
        for per in author:
            per = per.replace("\n",' ').replace("\r",' ').strip()
            if per[-2:] == '그림' or per[-2:] == '원저' or per[-2:] == '사진' or per[-2:] == '편저':
                print(per, end=' ')
            elif per[-2:] == ' 저' or per[-2:] == ' 글':
                print(per, end=' ' )
            elif "감추기" == per[:3]:
                print(per[3:].strip())
    else: print(author[0].strip())

리스트 : ['\n김영하 저\r\n                            ']
김영하 저

리스트 : ['\n이선 몰릭 저', '신동숙 역\r\n                            ']
이선 몰릭 저
리스트 : ['\n김종원 저\r\n                            ']
김종원 저

리스트 : ['\n한강 저\r\n                            ']
한강 저

리스트 : ['\n김수미 저\r\n                            ']
김수미 저

리스트 : ['\n태수 저\r\n                            ']
태수 저

리스트 : ['\n김주환 저\r\n                            ']
김주환 저

리스트 : ['\n양귀자 저\r\n                            ']
양귀자 저

리스트 : ['\n요시타케 신스케 글그림', '권남희 역\r\n                            ']
요시타케 신스케 글그림
리스트 : ['\n코이케 류노스케 저', '박재현 역\r\n                            ']
코이케 류노스케 저
리스트 : ['\n와야마 야마 글그림', '현승희 역\r\n                            ']
와야마 야마 글그림
리스트 : ['\n유발 하라리 저', '김명주 역\r\n                            ']
유발 하라리 저
리스트 : ['\n유선경 저\r\n                            ']
유선경 저

리스트 : ['\n최태성 저\r\n                            ']
최태성 저

리스트 : ['\n김주환 저\r\n                            ']
김주환 저

리스트 : ['\n안녕달 글그림\r\n                            ']
안녕달 글그림

리스트 : ['\n최태성 저\r\n                            ']
최태성 저

리스트 : ['\n브라이언 트레이시 저', '정지현 역\r\n                            ']
브라이언 트레이시 저
리스트 : ['\n정대건 저\r\n                            ']
정대건 저

리스트 : ['\n존 윌리엄스 저', '김승욱 역\r\n                            ']
존 윌리엄스 저
리스트 : ['\n백온유, 강보라, 서장원, 성해나, 성혜령 저 외 2명\r\n                                        \n정보 더 보기', '감추기\n\n\n\n백온유\n강보라\n서장원\n성해나\n성혜령\n이희주\n현호정\n\n\n\n\n']
백온유 강보라 서장원 성해나 성혜령 이희주 현호정

리스트 : ['\n한현근 저\r\n                            ']
한현근 저

리스트 : ['\n한강 저\r\n                            ']
한강 저

리스트 : ['\nETS 저\r\n                            ']
ETS 저

리스트 : ['\nETS 저\r\n                            ']
ETS 저

리스트 : ['\n성해나 저\r\n                            ']
성해나 저

리스트 : ['\n오건영 저\r\n                            ']
오건영 저

리스트 : ['\n한강 저\r\n                            ']
한강 저

리스트 : ['\n정관 스님, 후남 셀만 저', '베로니크 회거 사진', '양혜영 역\r\n                            ']
정관 스님, 후남 셀만 저 베로니크 회거 사진
리스트 : ['\n스즈키 유우토 글그림\r\n                            ']
스즈키 유우토 글그림

리스트 : ['\n김직선 저\r\n                            ']
김직선 저

리스트 : ['\n니이 사토루 글그림\r\n                            ']
니이 사토루 글그림

리스트 : ['\n김지훈(포메뽀꼬) 저\r\n                            ']
김지훈(포메뽀꼬) 저

리스트 : ['\n안-엘렌 클레르, 뱅상 트리부 저', '구영옥 역\r\n                            ']
안-엘렌 클레르, 뱅상 트리부 저
리스트 : ['\n한동훈 저\r\n                            ']
한동훈 저

리스트 : ['\nDavid Cho 저\r\n                            ']
David Cho 저

리스트 : ['\n한강 저\r\n                            ']
한강 저

리스트 : ['\n김종원 저\r\n                            ']
김종원 저

리스트 : ['\n김종원 저\r\n                            ']
김종원 저

리스트 : ['\n프리드리히 니체 저\r\n                            ']
프리드리히 니체 저

리스트 : ['\n최태성 저\r\n                            ']
최태성 저

리스트 : ['\n김종원 저\r\n                            ']
김종원 저

리스트 : ['\n루리 글그림\r\n                            ']
루리 글그림

리스트 : ['\n벤저민 하디 저', '최은아 역\r\n                            ']
벤저민 하디 저
리스트 : ['\n김지훤 글', '하꼬방 그림\r\n                            ']
김지훤 글 하꼬방 그림
리스트 : ['\n타츠 유키노부 글그림\r\n                            ']
타츠 유키노부 글그림

리스트 : ['\n김종원 저\r\n                            ']
김종원 저

리스트 : ['\n정수봉, 이준영, 원효리, 이성열, 임다연 편저\r\n                            ']
정수봉, 이준영, 원효리, 이성열, 임다연 편저

리스트 : ['\n흔한남매 원저', '안치현 글', '유난희 그림', '이정모, 흔한컴퍼니 감수\r\n                            ']
흔한남매 원저 안치현 글 유난희 그림
리스트 : ['\n유은하 저\r\n                            ']
유은하 저

리스트 : ['\n천근아 저\r\n                            ']
천근아 저

리스트 : ['\n이철희 저\r\n                            ']
이철희 저

리스트 : ['\n신재은 저\r\n                            ']
신재은 저

리스트 : ['\n태 킴 저', '김정민 역', '김상균 감수\r\n                            ']
태 킴 저
리스트 : ['\n타치바나 오레코 글그림', '유유리 역\r\n                            ']
타치바나 오레코 글그림
리스트 : ['\n유설화 글그림\r\n                            ']
유설화 글그림

리스트 : ['\n아이다이로 글그림', '장혜영 역\r\n                            ']
아이다이로 글그림
리스트 : ['\n위혜정 저\r\n                            ']
위혜정 저

리스트 : ['\n김민철 편저\r\n                            ']
김민철 편저

리스트 : ['\n알에스미디어 글', '정수영 그림', '강용철 감수\r\n                            ']
알에스미디어 글 정수영 그림
리스트 : ['\n이어령 저\r\n                            ']
이어령 저

리스트 : ['\n백수린 저\r\n                            ']
백수린 저

리스트 : ['\n네빌 고다드 저', '홍주연 역\r\n                            ']
네빌 고다드 저
리스트 : ['\n세이노(SayNo) 저\r\n                            ']
세이노(SayNo) 저

리스트 : ['\n클레어 키건 저', '홍한별 역\r\n                            ']
클레어 키건 저
리스트 : ['\n최승필 저\r\n                            ']
최승필 저

리스트 : ['\n손원평 저\r\n                            ']
손원평 저

리스트 : ['\n칼 에드워드 세이건 저', '홍승수 역\r\n                            ']
칼 에드워드 세이건 저
리스트 : ['\n유현준 저\r\n                            ']
유현준 저

리스트 : ['\n센바 쿠로노 글그림', '반기모 역\r\n                            ']
센바 쿠로노 글그림
리스트 : ['\n해커스 일본어연구소 저\r\n                            ']
해커스 일본어연구소 저

리스트 : ['\n강용수 저\r\n                            ']
강용수 저

리스트 : ['\n문상훈 저\r\n                            ']
문상훈 저

리스트 : ['\n데일 카네기 저', '임상훈 역\r\n                            ']
데일 카네기 저
리스트 : ['\n최설희 글', '김덕영 그림\r\n                            ']
최설희 글 김덕영 그림
리스트 : ['\n강보라, 성해나, 윤단 저\r\n                            ']
강보라, 성해나, 윤단 저

리스트 : ['\n한강 저\r\n                            ']
한강 저

리스트 : ['\n강효미 글', '김무연 그림', '권윤정 감수\r\n                            ']
강효미 글 김무연 그림
리스트 : ['\n리처드 도킨스 저', '홍영남, 이상임 역\r\n                            ']
리처드 도킨스 저
리스트 : ['\n김지원, 김혜원, 도헌정, 허완, 조성도 저 외 5명\r\n                                        \n정보 더 보기', '감추기\n\n\n\n김지원\n김혜원\n도헌정\n허완\n조성도\n김희라\n오별님\n윤성원\n김송희\n손현\n\n\n\n\n']
김지원 김혜원 도헌정 허완 조성도 김희라 오별님 윤성원 김송희 손현

리스트 : ['\n유발 하라리 저', '조현욱 역', '이태수 감수\r\n                            ']
유발 하라리 저
리스트 : ['\n최승호 외 저\r\n                            ']
최승호 외 저

리스트 : ['\n조수용 저\r\n                            ']
조수용 저

리스트 : ['\n박준 저\r\n                            ']
박준 저

리스트 : ['\n박태웅 저\r\n                            ']
박태웅 저

리스트 : ['\n하마지 아키, 쿠미쵸 글그림\r\n                            ']
하마지 아키, 쿠미쵸 글그림

리스트 : ['\n이꽃님 저\r\n                            ']
이꽃님 저

리스트 : ['\n정주희 저', '이수진 감수\r\n                            ']
정주희 저
리스트 : ['\n하마지 아키 글그림\r\n                            ']
하마지 아키 글그림

리스트 : ['\n고시넷 NCS 연구소 편저\r\n                            ']
고시넷 NCS 연구소 편저

리스트 : ['\n김화요 글', '오윤화 그림\r\n                            ']
김화요 글 오윤화 그림
리스트 : ['\n빨간내복야코 원저', '전판교 글', '도니패밀리 그림', '샌드박스 네트워크 감수\r\n                            ']
빨간내복야코 원저 전판교 글 도니패밀리 그림
리스트 : ['\n오창석 저\r\n                            ']
오창석 저

리스트 : ['\n인이이 저', '장려진 역\r\n                            ']
인이이 저
리스트 : ['\n도야마 시게히코 저', '전경아 역\r\n                            ']
도야마 시게히코 저
리스트 : ['\n김종원 글\r\n                            ']
김종원 글

리스트 : ['\n제시카 윤 저\r\n                            ']
제시카 윤 저

리스트 : ['\n헤르만 헤세 저', '전영애 역\r\n                            ']
헤르만 헤세 저
리스트 : ['\n백유연 글그림\r\n                            ']
백유연 글그림

리스트 : ['\n예소연, 김기태, 문지혁, 서장원, 정기현 저 외 1명\r\n                                        \n정보 더 보기', '감추기\n\n\n\n예소연\n김기태\n문지혁\n서장원\n정기현\n최민우\n\n\n\n\n']
예소연 김기태 문지혁 서장원 정기현 최민우

리스트 : ['\n엄예정 저\r\n                            ']
엄예정 저

리스트 : ['\n박진여 저\r\n                            ']
박진여 저

리스트 : ['\n김주환 저\r\n                            ']
김주환 저

리스트 : ['\nDavid Cho 저\r\n                            ']
David Cho 저

리스트 : ['\n한강 저\r\n                            ']
한강 저

리스트 : ['\n모건 하우절 저', '이지연 역\r\n                            ']
모건 하우절 저
리스트 : ['\n모건 하우절 저', '이수경 역\r\n                            ']
모건 하우절 저
리스트 : ['\n한현근 저\r\n                            ']
한현근 저

리스트 : ['\n유창호 편저\r\n                            ']
유창호 편저

리스트 : ['\n설민석, 남이담 글', '정현희 그림', '강석화 감수\r\n                            ']
설민석, 남이담 글 정현희 그림
리스트 : ['\n슈뻘맨 원저', '밥푸울 글', '류수형 그림', '샌드박스 네트워크 감수\r\n                            ']
슈뻘맨 원저 밥푸울 글 류수형 그림
리스트 : ['\n로이스 라우리 저', '장은수 역\r\n                            ']
로이스 라우리 저
리스트 : ['\n최진영 저\r\n                            ']
최진영 저

리스트 : ['\n김대환 저\r\n                            ']
김대환 저

리스트 : ['\n박재한 저\r\n                            ']
박재한 저

리스트 : ['\n김종우 편저\r\n                            ']
김종우 편저

리스트 : ['\n카모시다 하지메 저', '미조구치 케이지 그림', '이승원 역\r\n                            ']
카모시다 하지메 저 미조구치 케이지 그림
리스트 : ['\n카모시다 하지메 저', '미조구치 케이지 그림', '이승원 역\r\n                            ']
카모시다 하지메 저 미조구치 케이지 그림
리스트 : ['\n혼Job취업연구소 편저\r\n                            ']
혼Job취업연구소 편저

리스트 : ['\n김영숙 저\r\n                            ']
김영숙 저

In [ ]:
<a class="gd_name" href="/product/goods/123258602" onclick="wiseLogV2('BS', '001_005_001', ''); ">과학을 보다</a>

In [287]:
book.select('li#data-goods-no')

[]

# 저자, 역자, 글그림, 편저 등 분류하기

In [333]:
author =""
photo = ""
trans = ""

for item in text_clean(book_list[28].select_one(".authPub.info_auth").text).split('/'):
    if '저' == item[-1]:
        author = item
    elif '사진' == item[-2:]:
        photo = item
    elif '역' == item[-1]:
        trans = item
    print(f"author {author} photo {photo} trans {trans}")

AttributeError: 'builtin_function_or_method' object has no attribute 'split'

In [320]:
def text_clean(text):
    return text.replace("\n",' ').replace('\r',' ').strip